import type { LexiconEntry } from "../types";

/** C1 sets 61–65: gastronomy, appearance, love & partnership, parenting, life stages. */
export const C1_PART13: LexiconEntry[] = [
  // Set 61 — Gastronomy
  ["palate", "n", "damak (zevki)", "The dish is too spicy for my palate.", "Yemek damak zevkim için fazla acı."],
  ["connoisseur", "n", "uzman, erbap", "He's a coffee connoisseur.", "Kahve erbabıdır."],
  ["delectable", "adj", "nefis", "The dessert was delectable.", "Tatlı nefisti."],
  ["piquant", "adj", "keskin, iştah açıcı (tat)", "The sauce has a piquant flavour.", "Sosun keskin bir tadı var."],
  ["pungent", "adj", "keskin kokulu", "Garlic has a pungent smell.", "Sarımsağın keskin bir kokusu var."],
  ["zesty", "adj", "ferah, limonlu, canlı (tat)", "It's a zesty summer salad.", "Ferah bir yaz salatası."],
  ["tangy", "adj", "ekşimsi, keskin", "Pomegranate molasses is tangy.", "Nar ekşisi ekşimsidir."],
  ["velvety", "adj", "kadifemsi", "The soup has a velvety texture.", "Çorbanın kadifemsi bir kıvamı var."],
  ["cloying", "adj", "bayıltıcı derecede tatlı", "The cake was cloyingly sweet.", "Pasta bayıltıcı derecede tatlıydı."],
  ["unpalatable", "adj", "tatsız, yenmez; kabul edilemez", "The truth was unpalatable.", "Gerçek kabul edilmesi zor bir şeydi."],
  ["garnish", "v", "süslemek (yemek)", "Garnish the dish with parsley.", "Yemeği maydanozla süsle."],
  ["infuse", "v", "demlemek, (tat) sindirmek", "Infuse the tea for five minutes.", "Çayı beş dakika demle."],
  ["braise", "v", "az suda ağır ateşte pişirmek", "Braise the lamb for three hours.", "Kuzuyu üç saat ağır ateşte pişir."],
  ["caramelise", "v", "karamelize etmek", "Caramelise the onions slowly.", "Soğanları yavaşça karamelize et."],
  ["artisanal", "adj", "zanaatkâr işi, el yapımı", "They sell artisanal cheese.", "El yapımı peynir satıyorlar."],
  ["farm-to-table", "adj", "tarladan sofraya", "It's a farm-to-table restaurant.", "Tarladan sofraya bir restoran."],
  ["culinary heritage", "n", "mutfak mirası", "Gaziantep has a rich culinary heritage.", "Gaziantep'in zengin bir mutfak mirası var."],
  ["tasting menu", "n", "tadım menüsü", "The chef offers a nine-course tasting menu.", "Şef dokuz çeşitlik bir tadım menüsü sunuyor."],
  ["aftertaste", "n", "ağızda kalan tat", "The wine has a bitter aftertaste.", "Şarabın ağızda acı bir tadı kalıyor."],
  ["moreish", "adj", "yedikçe yiyesi getiren", "These nuts are very moreish.", "Bu kuruyemişler yedikçe yiyesi getiriyor."],

  // Set 62 — Appearance
  ["chiselled", "adj", "keskin hatlı (yüz)", "He has a chiselled jaw.", "Keskin hatlı bir çenesi var."],
  ["gaunt", "adj", "zayıf ve bitkin görünen", "He looked gaunt after his illness.", "Hastalığından sonra bitkin ve zayıf görünüyordu."],
  ["haggard", "adj", "yorgun ve yıpranmış", "She looked haggard after the night shift.", "Gece vardiyasından sonra yorgun ve yıpranmış görünüyordu."],
  ["dishevelled", "adj", "dağınık, darmadağın", "He arrived dishevelled and late.", "Darmadağın ve geç geldi."],
  ["immaculate", "adj", "kusursuz, tertemiz", "She was immaculately dressed.", "Kusursuz giyinmişti."],
  ["dapper", "adj", "şık (erkek)", "He looked dapper in his suit.", "Takım elbisesiyle şıktı."],
  ["frumpy", "adj", "demode ve özensiz (giyim)", "I feel frumpy in this dress.", "Bu elbiseyle kendimi demode hissediyorum."],
  ["willowy", "adj", "uzun ve ince, narin", "The model was tall and willowy.", "Model uzun ve narindi."],
  ["portly", "adj", "iri yarı, göbekli", "A portly man opened the door.", "Göbekli bir adam kapıyı açtı."],
  ["lanky", "adj", "sırık gibi uzun", "He's a lanky teenager.", "Sırık gibi bir genç."],
  ["weather-beaten", "adj", "güneşten ve rüzgârdan yıpranmış", "The fisherman had a weather-beaten face.", "Balıkçının güneşten yıpranmış bir yüzü vardı."],
  ["ruddy", "adj", "kırmızı yanaklı", "He had a ruddy complexion.", "Kırmızı yanaklıydı."],
  ["sallow", "adj", "soluk sarı (ten)", "Her skin looked sallow.", "Teni soluk sarı görünüyordu."],
  ["freckled", "adj", "çilli", "She has a freckled nose.", "Burnu çilli."],
  ["bushy", "adj", "gür (kaş, sakal)", "He has bushy eyebrows.", "Gür kaşları var."],
  ["cropped", "adj", "kısa kesilmiş", "She has cropped hair.", "Saçları kısa kesilmiş."],
  ["piercing", "adj", "delici (bakış)", "He has piercing blue eyes.", "Delici mavi gözleri var."],
  ["poise", "n", "zarafet, duruş", "She walked with great poise.", "Büyük bir zarafetle yürüdü."],
  ["demeanour", "n", "tavır, davranış", "His calm demeanour reassured us.", "Sakin tavrı içimizi rahatlattı."],
  ["bearing", "n", "duruş, tavır", "He has a military bearing.", "Asker duruşu var."],

  // Set 63 — Love & partnership
  ["infatuation", "n", "geçici tutku, sevda", "It was just an infatuation.", "Sadece geçici bir tutkuydu."],
  ["courtship", "n", "flört dönemi", "Their courtship lasted two years.", "Flört dönemleri iki yıl sürdü."],
  ["betrothed", "adj", "nişanlı", "She was betrothed at eighteen.", "On sekizinde nişanlandı."],
  ["matrimony", "n", "evlilik (resmi)", "They were joined in holy matrimony.", "Kutsal evlilik bağıyla birleştiler."],
  ["spouse", "n", "eş", "Spouses are welcome at the dinner.", "Eşler yemeğe davetlidir."],
  ["fidelity", "n", "sadakat", "Fidelity is important in marriage.", "Evlilikte sadakat önemlidir."],
  ["infidelity", "n", "aldatma, sadakatsizlik", "The marriage ended because of infidelity.", "Evlilik aldatma yüzünden bitti."],
  ["amicable", "adj", "dostane", "They had an amicable divorce.", "Dostane bir şekilde boşandılar."],
  ["compatible", "adj", "uyumlu", "We're just not compatible.", "Sadece uyumlu değiliz."],
  ["soulmate", "n", "ruh eşi", "She believes he's her soulmate.", "Onun ruh eşi olduğuna inanıyor."],
  ["unrequited", "adj", "karşılıksız (aşk)", "It was a story of unrequited love.", "Karşılıksız bir aşk hikâyesiydi."],
  ["long-distance relationship", "n", "uzak mesafe ilişkisi", "Long-distance relationships are hard.", "Uzak mesafe ilişkileri zordur."],
  ["pop the question", "phr", "evlilik teklif etmek", "He popped the question on the beach.", "Plajda evlenme teklif etti."],
  ["tie the knot", "phr", "dünyaevine girmek", "They tied the knot in June.", "Haziranda dünyaevine girdiler."],
  ["on the rocks", "phr", "(ilişki) sallantıda", "Their marriage is on the rocks.", "Evlilikleri sallantıda."],
  ["head over heels in love", "phr", "sırılsıklam âşık", "They're head over heels in love.", "Sırılsıklam âşıklar."],
  ["settle for", "pv", "…ile yetinmek", "Don't settle for less than you deserve.", "Hak ettiğinden azıyla yetinme."],
  ["drift", "v", "(ilişkide) uzaklaşmak, sürüklenmek", "We just drifted over the years.", "Yıllar içinde sadece uzaklaştık."],
  ["reconcile with", "phr", "…ile barışmak", "She reconciled with her father.", "Babasıyla barıştı."],
  ["prenuptial agreement", "n", "evlilik öncesi sözleşme", "They signed a prenuptial agreement.", "Evlilik öncesi sözleşme imzaladılar."],

  // Set 64 — Parenting
  ["authoritative", "adj", "otoriter ama sevecen (ebeveynlik)", "Authoritative parenting sets clear rules with warmth.", "Otoriter ama sevecen ebeveynlik sıcaklıkla net kurallar koyar."],
  ["nurture", "v", "yetiştirmek, beslemek, geliştirmek", "Parents nurture their children's talents.", "Ebeveynler çocuklarının yeteneklerini geliştirir."],
  ["nature versus nurture", "phr", "doğa mı yetiştirme mi", "The nature versus nurture debate continues.", "Doğa mı yetiştirme mi tartışması sürüyor."],
  ["pamper", "v", "şımartmak, üzerine titremek", "Grandparents love to pamper their grandchildren.", "Büyükanne ve büyükbabalar torunlarını şımartmayı sever."],
  ["mollycoddle", "v", "aşırı korumak, el bebek gül bebek büyütmek", "Don't mollycoddle him — let him try.", "Onu el bebek gül bebek büyütme, denemesine izin ver."],
  ["overprotective", "adj", "aşırı korumacı", "Her parents are overprotective.", "Ailesi aşırı korumacı."],
  ["helicopter parent", "n", "helikopter ebeveyn", "Helicopter parents control every detail.", "Helikopter ebeveynler her ayrıntıyı kontrol eder."],
  ["permissive", "adj", "serbest bırakan, müsamahakâr", "They have a permissive parenting style.", "Müsamahakâr bir ebeveynlik tarzları var."],
  ["discipline", "v", "disipline etmek, cezalandırmak", "It's hard to discipline teenagers.", "Gençleri disipline etmek zor."],
  ["tantrum", "n", "öfke nöbeti (çocuk)", "The toddler threw a tantrum in the shop.", "Küçük çocuk dükkânda öfke nöbeti geçirdi."],
  ["toddler", "n", "yeni yürümeye başlayan çocuk", "Toddlers need constant attention.", "Yeni yürüyen çocuklar sürekli ilgi ister."],
  ["adolescence", "n", "ergenlik", "Adolescence can be a difficult time.", "Ergenlik zor bir dönem olabilir."],
  ["formative years", "n", "kişiliğin şekillendiği yıllar", "She spent her formative years in Ankara.", "Kişiliğinin şekillendiği yılları Ankara'da geçirdi."],
  ["role model", "n", "rol model", "Parents are their children's first role models.", "Ebeveynler çocuklarının ilk rol modelleridir."],
  ["childcare", "n", "çocuk bakımı", "Childcare is very expensive.", "Çocuk bakımı çok pahalı."],
  ["foster parent", "n", "koruyucu aile", "They became foster parents.", "Koruyucu aile oldular."],
  ["adoption", "n", "evlat edinme", "Adoption can take years.", "Evlat edinme yıllar alabilir."],
  ["single parent", "n", "tek ebeveyn", "She's a single parent of two.", "İki çocuklu tek ebeveyn."],
  ["latchkey kid", "n", "okuldan sonra evde yalnız kalan çocuk", "Many latchkey kids let themselves in after school.", "Birçok çocuk okuldan sonra eve yalnız giriyor."],
  ["bring someone up", "phr", "birini büyütmek", "She was brought up by her grandmother.", "Büyükannesi tarafından büyütüldü."],

  // Set 65 — Life stages
  ["infancy", "n", "bebeklik", "The disease is common in infancy.", "Hastalık bebeklikte yaygındır."],
  ["prime", "n", "en verimli dönem, olgunluk çağı", "She's in the prime of her life.", "Hayatının en verimli dönemindedir."],
  ["midlife crisis", "n", "orta yaş krizi", "He bought a sports car in a midlife crisis.", "Orta yaş kriziyle bir spor araba aldı."],
  ["twilight years", "n", "hayatın son yılları", "They spent their twilight years by the sea.", "Hayatlarının son yıllarını deniz kenarında geçirdiler."],
  ["senior citizen", "n", "yaşlı vatandaş", "Senior citizens travel free on buses.", "Yaşlı vatandaşlar otobüslerde ücretsiz seyahat ediyor."],
  ["elderly care", "n", "yaşlı bakımı", "Elderly care is a growing sector.", "Yaşlı bakımı büyüyen bir sektör."],
  ["frail", "adj", "zayıf, dermansız", "My grandfather is getting frail.", "Dedem dermansızlaşıyor."],
  ["sprightly", "adj", "dinç, çevik (yaşlı)", "She's a sprightly 90-year-old.", "90 yaşında dinç bir kadın."],
  ["longevity", "n", "uzun ömür", "Diet may explain their longevity.", "Beslenme uzun ömürlerini açıklayabilir."],
  ["milestone birthday", "n", "özel (dönüm noktası) doğum günü", "Turning 50 is a milestone birthday.", "50'ye girmek özel bir doğum günüdür."],
  ["rite of passage", "n", "geçiş töreni, dönüm noktası", "Getting a driving licence is a rite of passage.", "Ehliyet almak bir geçiş törenidir."],
  ["come of age", "phr", "reşit olmak; olgunlaşmak", "He came of age in the 1990s.", "1990'larda reşit oldu."],
  ["empty nest", "n", "çocukların evden ayrılması sonrası boş yuva", "They struggled with the empty nest.", "Boş yuva dönemiyle zorlandılar."],
  ["generational", "adj", "kuşaklar arası", "There are generational differences in technology use.", "Teknoloji kullanımında kuşaklar arası farklar var."],
  ["baby boomer", "n", "savaş sonrası kuşak (1946–64)", "Baby boomers are now retiring.", "Savaş sonrası kuşak şimdi emekli oluyor."],
  ["millennial", "n", "Y kuşağı üyesi", "Millennials grew up with the internet.", "Y kuşağı internetle büyüdü."],
  ["Gen Z", "n", "Z kuşağı", "Gen Z prefers video to text.", "Z kuşağı yazıya videoyu tercih ediyor."],
  ["mortality", "n", "ölümlülük", "The illness made him think about his own mortality.", "Hastalık ona kendi ölümlülüğünü düşündürdü."],
  ["bereavement", "n", "yas, yakınını kaybetme", "She took leave after a bereavement.", "Bir yakınını kaybettikten sonra izin aldı."],
  ["pass away", "pv", "vefat etmek", "His grandfather passed away last year.", "Dedesi geçen yıl vefat etti."],
];
