import type { LexiconEntry } from "../types";

/** C1 sets 21–25: clinical medicine, psychology, public health, biotechnology, the brain. */
export const C1_PART5: LexiconEntry[] = [
  // Set 21 — Clinical medicine
  ["symptomatic", "adj", "belirti gösteren", "Only a few patients were symptomatic.", "Sadece birkaç hasta belirti gösteriyordu."],
  ["asymptomatic", "adj", "belirtisiz", "Many carriers are asymptomatic.", "Birçok taşıyıcı belirtisizdir."],
  ["terminal", "adj", "ölümcül, son evre", "He was diagnosed with a terminal illness.", "Ölümcül bir hastalık teşhisi kondu."],
  ["benign", "adj", "iyi huylu", "Luckily, the tumour was benign.", "Neyse ki tümör iyi huyluydu."],
  ["malignant", "adj", "kötü huylu", "The tests showed a malignant tumour.", "Testler kötü huylu bir tümör gösterdi."],
  ["remission", "n", "(hastalığın) gerilemesi, remisyon", "She has been in remission for five years.", "Beş yıldır hastalığı gerilemiş durumda."],
  ["palliative care", "n", "palyatif bakım", "He is receiving palliative care.", "Palyatif bakım alıyor."],
  ["complication", "n", "komplikasyon", "There were complications after surgery.", "Ameliyattan sonra komplikasyonlar oldu."],
  ["intensive care", "n", "yoğun bakım", "She's in intensive care.", "Yoğun bakımda."],
  ["resuscitate", "v", "canlandırmak (tıbbi)", "Paramedics tried to resuscitate him.", "Sağlık görevlileri onu hayata döndürmeye çalıştı."],
  ["prescribe", "v", "reçete etmek", "The doctor prescribed antibiotics.", "Doktor antibiyotik reçete etti."],
  ["over-the-counter", "adj", "reçetesiz", "You can buy it over the counter.", "Reçetesiz alabilirsin."],
  ["placebo", "n", "plasebo", "Half the group got a placebo.", "Grubun yarısına plasebo verildi."],
  ["side effects", "n", "yan etkiler", "The drug has few side effects.", "İlacın yan etkisi az."],
  ["contraindication", "n", "kullanılmaması gereken durum", "Pregnancy is a contraindication for this drug.", "Hamilelik bu ilacın kullanılmaması gereken bir durumdur."],
  ["hereditary", "adj", "kalıtsal", "The condition is hereditary.", "Rahatsızlık kalıtsal."],
  ["degenerative", "adj", "dejeneratif, gittikçe kötüleşen", "Alzheimer's is a degenerative disease.", "Alzheimer dejeneratif bir hastalıktır."],
  ["outpatient", "n", "ayakta tedavi hastası", "The clinic treats outpatients.", "Klinik ayakta tedavi hastalarına bakıyor."],
  ["referral", "n", "sevk", "You need a referral to see a specialist.", "Uzmana görünmek için sevk gerekiyor."],
  ["bedside manner", "n", "(doktorun) hastaya yaklaşımı", "She has an excellent bedside manner.", "Hastalara yaklaşımı mükemmel."],

  // Set 22 — Psychology
  ["psyche", "n", "ruh, psişe", "War leaves scars on the human psyche.", "Savaş insan ruhunda yaralar bırakır."],
  ["disorder", "n", "bozukluk", "She was diagnosed with an eating disorder.", "Yeme bozukluğu teşhisi kondu."],
  ["post-traumatic", "adj", "travma sonrası", "Many survivors suffer from post-traumatic stress.", "Birçok hayatta kalan travma sonrası stres yaşıyor."],
  ["cognitive behavioural therapy", "n", "bilişsel davranışçı terapi", "Cognitive behavioural therapy helps with anxiety.", "Bilişsel davranışçı terapi kaygıya yardımcı olur."],
  ["coping mechanism", "n", "başa çıkma mekanizması", "Humour is his coping mechanism.", "Mizah onun başa çıkma mekanizması."],
  ["denial", "n", "inkâr", "He's in denial about his drinking.", "İçki sorununu inkâr ediyor."],
  ["projection", "n", "yansıtma (psikoloji)", "His anger at others may be projection.", "Başkalarına öfkesi bir yansıtma olabilir."],
  ["repress", "v", "bastırmak (duygu, anı)", "She repressed memories of the accident.", "Kazanın anılarını bastırdı."],
  ["trigger", "n", "tetikleyici", "Loud noises are a trigger for him.", "Yüksek sesler onun için bir tetikleyici."],
  ["self-sabotage", "n", "kendini baltalama", "Procrastination can be a form of self-sabotage.", "Erteleme bir tür kendini baltalama olabilir."],
  ["impostor syndrome", "n", "sahtekârlık sendromu", "Many successful people have impostor syndrome.", "Birçok başarılı insan sahtekârlık sendromu yaşar."],
  ["validation", "n", "onay görme, kabul", "Teenagers seek validation from their peers.", "Gençler akranlarından onay görmek ister."],
  ["attachment", "n", "bağlanma", "Early attachment affects adult relationships.", "Erken bağlanma yetişkin ilişkilerini etkiler."],
  ["temperament", "n", "mizaç", "The twins have very different temperaments.", "İkizlerin mizaçları çok farklı."],
  ["neurotic", "adj", "nevrotik, aşırı kaygılı", "He's a bit neurotic about germs.", "Mikroplar konusunda biraz aşırı kaygılı."],
  ["resilient mindset", "n", "dirençli zihniyet", "A resilient mindset helps after failure.", "Dirençli bir zihniyet başarısızlıktan sonra yardımcı olur."],
  ["catharsis", "n", "arınma, katarsis", "Writing about the loss was a catharsis.", "Kayıp hakkında yazmak bir arınmaydı."],
  ["psychosomatic", "adj", "psikosomatik", "Some headaches are psychosomatic.", "Bazı baş ağrıları psikosomatiktir."],
  ["well-adjusted", "adj", "uyumlu, dengeli", "She's a happy, well-adjusted child.", "Mutlu ve uyumlu bir çocuk."],
  ["mental resilience", "n", "zihinsel dayanıklılık", "Athletes train their mental resilience.", "Sporcular zihinsel dayanıklılıklarını çalıştırır."],

  // Set 23 — Public health
  ["public health", "n", "halk sağlığı", "Smoking is a major public health issue.", "Sigara önemli bir halk sağlığı sorunu."],
  ["vaccination", "n", "aşılama", "Vaccination rates have fallen.", "Aşılama oranları düştü."],
  ["herd immunity", "n", "toplum bağışıklığı", "Herd immunity protects the vulnerable.", "Toplum bağışıklığı savunmasızları korur."],
  ["quarantine", "n", "karantina", "Travellers had to go into quarantine.", "Yolcular karantinaya girmek zorundaydı."],
  ["transmission", "n", "bulaşma", "Masks reduce transmission.", "Maskeler bulaşmayı azaltır."],
  ["incidence", "n", "görülme sıklığı", "The incidence of diabetes is rising.", "Diyabetin görülme sıklığı artıyor."],
  ["prevalence", "n", "yaygınlık", "The prevalence of obesity is high.", "Obezitenin yaygınlığı yüksek."],
  ["mortality rate", "n", "ölüm oranı", "Infant mortality rates have fallen sharply.", "Bebek ölüm oranları keskin şekilde düştü."],
  ["sanitation", "n", "sağlık koşulları, kanalizasyon", "Poor sanitation spreads disease.", "Kötü sağlık koşulları hastalık yayar."],
  ["malnutrition", "n", "yetersiz beslenme", "Malnutrition affects millions of children.", "Yetersiz beslenme milyonlarca çocuğu etkiliyor."],
  ["sedentary lifestyle", "n", "hareketsiz yaşam", "A sedentary lifestyle increases health risks.", "Hareketsiz yaşam sağlık risklerini artırır."],
  ["preventable", "adj", "önlenebilir", "Most of these deaths are preventable.", "Bu ölümlerin çoğu önlenebilir."],
  ["screening", "n", "tarama (sağlık)", "Early screening saves lives.", "Erken tarama hayat kurtarır."],
  ["health inequalities", "n", "sağlık eşitsizlikleri", "Health inequalities exist between regions.", "Bölgeler arasında sağlık eşitsizlikleri var."],
  ["addiction", "n", "bağımlılık", "Gambling addiction is growing.", "Kumar bağımlılığı artıyor."],
  ["substance abuse", "n", "madde bağımlılığı", "The centre treats substance abuse.", "Merkez madde bağımlılığını tedavi ediyor."],
  ["contact tracing", "n", "temaslı takibi", "Contact tracing slowed the virus.", "Temaslı takibi virüsü yavaşlattı."],
  ["health campaign", "n", "sağlık kampanyası", "The health campaign targets young smokers.", "Sağlık kampanyası genç sigara içicileri hedefliyor."],
  ["life-threatening", "adj", "hayatı tehdit eden", "The injury wasn't life-threatening.", "Yaralanma hayati tehlike taşımıyordu."],
  ["frontline workers", "n", "ön saflarda çalışanlar", "Frontline workers risked their lives.", "Ön saflardaki çalışanlar hayatlarını riske attı."],

  // Set 24 — Biotechnology
  ["genome", "n", "genom", "Scientists mapped the human genome.", "Bilim insanları insan genomunu haritalandırdı."],
  ["DNA sequencing", "n", "DNA dizileme", "DNA sequencing is now cheap.", "DNA dizileme artık ucuz."],
  ["gene editing", "n", "gen düzenleme", "Gene editing raises ethical questions.", "Gen düzenleme etik soruları gündeme getiriyor."],
  ["cloning", "n", "klonlama", "Human cloning is banned.", "İnsan klonlama yasak."],
  ["stem cell", "n", "kök hücre", "Stem cell research could cure diseases.", "Kök hücre araştırmaları hastalıkları tedavi edebilir."],
  ["mutation", "n", "mutasyon", "The virus developed a new mutation.", "Virüs yeni bir mutasyon geliştirdi."],
  ["heredity", "n", "kalıtım", "Heredity affects our height.", "Kalıtım boyumuzu etkiler."],
  ["biotech", "n", "biyoteknoloji", "She works in biotech.", "Biyoteknoloji alanında çalışıyor."],
  ["pharmaceutical", "adj", "ilaç (sektörü), farmasötik", "Pharmaceutical companies fund much research.", "İlaç şirketleri araştırmaların çoğunu finanse ediyor."],
  ["synthesise", "v", "sentezlemek", "The drug was synthesised in a lab.", "İlaç laboratuvarda sentezlendi."],
  ["organism", "n", "organizma", "Bacteria are single-celled organisms.", "Bakteriler tek hücreli organizmalardır."],
  ["microbe", "n", "mikrop", "Microbes live in our gut.", "Bağırsaklarımızda mikroplar yaşar."],
  ["antibody", "n", "antikor", "The vaccine produces antibodies.", "Aşı antikor üretir."],
  ["pathogen", "n", "patojen, hastalık etkeni", "The pathogen spreads through water.", "Patojen su yoluyla yayılıyor."],
  ["bioethics", "n", "biyoetik", "Bioethics deals with medical dilemmas.", "Biyoetik tıbbi ikilemlerle ilgilenir."],
  ["designer baby", "n", "tasarım bebek", "Designer babies are a worrying idea.", "Tasarım bebekler endişe verici bir fikir."],
  ["lab-grown", "adj", "laboratuvarda üretilmiş", "Lab-grown meat may replace farming.", "Laboratuvarda üretilen et hayvancılığın yerini alabilir."],
  ["breakthrough treatment", "n", "çığır açan tedavi", "It's a breakthrough treatment for cancer.", "Kanser için çığır açan bir tedavi."],
  ["trial phase", "n", "deney aşaması", "The drug is in its final trial phase.", "İlaç son deney aşamasında."],
  ["patent", "n", "patent", "The company holds the patent.", "Patent şirkete ait."],

  // Set 25 — The brain
  ["neuron", "n", "nöron, sinir hücresi", "The brain contains billions of neurons.", "Beyin milyarlarca nöron içerir."],
  ["neuroscience", "n", "sinirbilim", "Neuroscience studies the nervous system.", "Sinirbilim sinir sistemini inceler."],
  ["nervous system", "n", "sinir sistemi", "Stress affects the nervous system.", "Stres sinir sistemini etkiler."],
  ["neuroplasticity", "n", "nöroplastisite, beynin değişebilirliği", "Neuroplasticity lets us learn at any age.", "Nöroplastisite her yaşta öğrenmemizi sağlar."],
  ["cerebral", "adj", "beyinle ilgili; entelektüel", "He had a cerebral haemorrhage.", "Beyin kanaması geçirdi."],
  ["cortex", "n", "korteks, beyin kabuğu", "The cortex controls thinking.", "Korteks düşünmeyi kontrol eder."],
  ["synapse", "n", "sinaps", "Learning strengthens synapses.", "Öğrenme sinapsları güçlendirir."],
  ["reflex", "n", "refleks", "Blinking is a reflex.", "Göz kırpmak bir reflekstir."],
  ["short-term memory", "n", "kısa süreli bellek", "Short-term memory holds about seven items.", "Kısa süreli bellek yaklaşık yedi öğe tutar."],
  ["long-term memory", "n", "uzun süreli bellek", "Sleep moves facts into long-term memory.", "Uyku bilgileri uzun süreli belleğe aktarır."],
  ["recall", "v", "hatırlamak (bilgiyi geri getirmek)", "I can't recall his name.", "Adını hatırlayamıyorum."],
  ["concussion", "n", "beyin sarsıntısı", "He suffered a concussion in the match.", "Maçta beyin sarsıntısı geçirdi."],
  ["dementia", "n", "bunama", "Dementia affects memory and thinking.", "Bunama hafızayı ve düşünmeyi etkiler."],
  ["cognitive decline", "n", "bilişsel gerileme", "Exercise may slow cognitive decline.", "Egzersiz bilişsel gerilemeyi yavaşlatabilir."],
  ["attention span", "n", "dikkat süresi", "Children have short attention spans.", "Çocukların dikkat süreleri kısadır."],
  ["dopamine", "n", "dopamin", "Social media gives us small hits of dopamine.", "Sosyal medya bize küçük dopamin dozları verir."],
  ["sleep deprivation", "n", "uykusuzluk (uykudan yoksun kalma)", "Sleep deprivation affects judgement.", "Uykusuzluk muhakemeyi etkiler."],
  ["circadian rhythm", "n", "sirkadiyen ritim, biyolojik saat", "Jet lag disrupts your circadian rhythm.", "Saat farkı biyolojik saatini bozar."],
  ["subconsciously", "adv", "bilinçaltında", "We subconsciously copy other people's gestures.", "Bilinçaltında başkalarının jestlerini taklit ederiz."],
  ["sensory", "adj", "duyusal", "Babies need sensory stimulation.", "Bebeklerin duyusal uyarana ihtiyacı var."],
];
