import type { LexiconEntry } from "../types";

/** C1 sets 6–10: scholarship, education policy, the workplace, leadership, entrepreneurship. */
export const C1_PART2: LexiconEntry[] = [
  // Set 6 — Scholarship
  ["discourse", "n", "söylem", "Political discourse has become more aggressive.", "Siyasi söylem daha saldırgan hale geldi."],
  ["paradigm", "n", "paradigma, model", "The discovery caused a paradigm shift.", "Keşif bir paradigma değişimine yol açtı."],
  ["framework", "n", "çerçeve", "The study uses a theoretical framework.", "Çalışma teorik bir çerçeve kullanıyor."],
  ["discipline", "n", "(akademik) disiplin, alan", "Linguistics is a young discipline.", "Dilbilim genç bir disiplin."],
  ["interdisciplinary", "adj", "disiplinlerarası", "It's an interdisciplinary project.", "Disiplinlerarası bir proje."],
  ["scholarly", "adj", "akademik, bilimsel", "She published a scholarly article.", "Akademik bir makale yayımladı."],
  ["treatise", "n", "inceleme, risale", "He wrote a treatise on ethics.", "Etik üzerine bir inceleme yazdı."],
  ["caveat", "n", "çekince, uyarı", "There's one caveat: the sample was small.", "Bir çekince var: örneklem küçüktü."],
  ["substantiate", "v", "kanıtlamak, temellendirmek", "Can you substantiate your claim?", "İddianı temellendirebilir misin?"],
  ["corroborate", "v", "doğrulamak, teyit etmek", "Witnesses corroborated her story.", "Tanıklar onun hikâyesini doğruladı."],
  ["extrapolate", "v", "genellemek, tahminde bulunmak (veriden)", "We can't extrapolate from such a small study.", "Bu kadar küçük bir çalışmadan genelleme yapamayız."],
  ["quantitative", "adj", "nicel", "The study uses quantitative data.", "Çalışma nicel veri kullanıyor."],
  ["qualitative", "adj", "nitel", "Interviews provide qualitative data.", "Görüşmeler nitel veri sağlar."],
  ["validity", "n", "geçerlilik", "Critics questioned the validity of the results.", "Eleştirmenler sonuçların geçerliliğini sorguladı."],
  ["rigorous", "adj", "titiz, sıkı", "The research was rigorous.", "Araştırma titizdi."],
  ["seminal", "adj", "çığır açan, temel", "It's a seminal work in psychology.", "Psikolojide çığır açan bir eser."],
  ["abstract", "n", "özet (makale)", "Read the abstract first.", "Önce özeti oku."],
  ["footnote", "n", "dipnot", "The source is given in a footnote.", "Kaynak bir dipnotta verilmiş."],
  ["academia", "n", "akademi, akademik dünya", "She left academia for industry.", "Akademiyi bırakıp sanayiye geçti."],
  ["erudite", "adj", "bilgili, âlim", "He's an erudite historian.", "Çok bilgili bir tarihçi."],

  // Set 7 — Education policy
  ["pedagogy", "n", "pedagoji", "Modern pedagogy focuses on the learner.", "Modern pedagoji öğrenciye odaklanır."],
  ["standardised testing", "n", "standart sınavlar", "Standardised testing dominates the school year.", "Standart sınavlar okul yılına hâkim."],
  ["streaming", "n", "(öğrencileri) seviyeye göre ayırma", "The school uses streaming in maths.", "Okul matematikte seviye gruplaması uyguluyor."],
  ["rote memorisation", "n", "ezbere dayalı öğrenme", "Rote memorisation doesn't build understanding.", "Ezbere dayalı öğrenme kavrayış geliştirmez."],
  ["critical thinking", "n", "eleştirel düşünme", "Schools should teach critical thinking.", "Okullar eleştirel düşünmeyi öğretmeli."],
  ["extracurricular", "adj", "ders dışı", "She does many extracurricular activities.", "Birçok ders dışı etkinliğe katılıyor."],
  ["attainment", "n", "başarı düzeyi, erişi", "The gap in attainment between regions is large.", "Bölgeler arası başarı farkı büyük."],
  ["underachieve", "v", "kapasitesinin altında başarı göstermek", "Bright children sometimes underachieve.", "Zeki çocuklar bazen kapasitelerinin altında kalır."],
  ["gifted", "adj", "üstün yetenekli", "The programme is for gifted children.", "Program üstün yetenekli çocuklar için."],
  ["inclusive education", "n", "kapsayıcı eğitim", "Inclusive education supports all learners.", "Kapsayıcı eğitim tüm öğrencileri destekler."],
  ["vocational", "adj", "mesleki", "He went to a vocational high school.", "Meslek lisesine gitti."],
  ["accreditation", "n", "akreditasyon", "The university gained international accreditation.", "Üniversite uluslararası akreditasyon aldı."],
  ["compulsory schooling", "n", "zorunlu eğitim", "Compulsory schooling lasts twelve years.", "Zorunlu eğitim on iki yıl sürer."],
  ["class size", "n", "sınıf mevcudu", "Smaller class sizes improve results.", "Daha küçük sınıf mevcutları sonuçları iyileştirir."],
  ["literacy rate", "n", "okuryazarlık oranı", "The literacy rate has risen to 97%.", "Okuryazarlık oranı %97'ye yükseldi."],
  ["dropout rate", "n", "okul terk oranı", "The dropout rate is highest in rural areas.", "Okul terk oranı en çok kırsal bölgelerde."],
  ["meritocracy", "n", "liyakat sistemi", "Is our society a true meritocracy?", "Toplumumuz gerçek bir liyakat sistemi mi?"],
  ["spoon-feed", "v", "hazıra alıştırmak, ağzına vermek", "Students shouldn't be spoon-fed answers.", "Öğrencilere cevaplar hazır verilmemeli."],
  ["hands-on learning", "n", "uygulamalı öğrenme", "Hands-on learning keeps pupils engaged.", "Uygulamalı öğrenme öğrencileri ilgili tutar."],
  ["foster", "v", "teşvik etmek, geliştirmek", "Teachers should foster curiosity.", "Öğretmenler merakı teşvik etmeli."],

  // Set 8 — The workplace
  ["remuneration", "n", "ücret, maaş (resmi)", "Remuneration is based on experience.", "Ücret deneyime göre belirlenir."],
  ["appraisal", "n", "performans değerlendirmesi", "I have my annual appraisal next week.", "Yıllık performans değerlendirmem gelecek hafta."],
  ["incentive", "n", "teşvik", "Bonuses are an incentive to work harder.", "Primler daha çok çalışmak için bir teşviktir."],
  ["absenteeism", "n", "devamsızlık", "Absenteeism rose during the winter.", "Kışın devamsızlık arttı."],
  ["presenteeism", "n", "hasta olduğu halde işe gelme", "Presenteeism can spread illness at work.", "Hasta halde işe gelmek iş yerinde hastalık yayabilir."],
  ["workforce", "n", "iş gücü", "Women make up half the workforce.", "Kadınlar iş gücünün yarısını oluşturuyor."],
  ["downsizing", "n", "küçülme (personel azaltma)", "Downsizing led to 300 job losses.", "Küçülme 300 kişinin işini kaybetmesine yol açtı."],
  ["unionise", "v", "sendikalaşmak", "The workers voted to unionise.", "İşçiler sendikalaşma yönünde oy verdi."],
  ["industrial action", "n", "grev ve iş bırakma eylemleri", "Teachers are taking industrial action.", "Öğretmenler iş bırakma eylemi yapıyor."],
  ["grievance", "n", "şikâyet, dert", "Staff can raise grievances with HR.", "Personel şikâyetlerini İK'ya iletebilir."],
  ["whistle-blower", "n", "muhbir (usulsüzlüğü ifşa eden)", "A whistle-blower exposed the fraud.", "Bir muhbir dolandırıcılığı ifşa etti."],
  ["glass ceiling", "n", "cam tavan", "She broke through the glass ceiling.", "Cam tavanı kırdı."],
  ["nepotism", "n", "kayırmacılık, akraba kayırma", "Nepotism is common in family firms.", "Aile şirketlerinde akraba kayırma yaygın."],
  ["office politics", "n", "ofis politikası", "I hate office politics.", "Ofis politikasından nefret ederim."],
  ["micromanage", "v", "her ayrıntıya karışmak", "My boss micromanages everything.", "Patronum her şeye karışıyor."],
  ["onboarding", "n", "(yeni çalışan) uyum süreci", "Onboarding takes two weeks.", "Uyum süreci iki hafta sürüyor."],
  ["attrition", "n", "(personel) kayıp oranı, yıpranma", "Staff attrition is high in call centres.", "Çağrı merkezlerinde personel kaybı yüksek."],
  ["work ethic", "n", "iş ahlakı", "She has a strong work ethic.", "Güçlü bir iş ahlakı var."],
  ["red tape", "n", "bürokratik engeller", "Red tape slows everything down.", "Bürokratik engeller her şeyi yavaşlatıyor."],
  ["pull your weight", "phr", "üzerine düşeni yapmak", "Everyone needs to pull their weight.", "Herkes üzerine düşeni yapmalı."],

  // Set 9 — Leadership
  ["visionary", "adj", "vizyoner, ileri görüşlü", "She's a visionary leader.", "Vizyoner bir lider."],
  ["charismatic", "adj", "karizmatik", "He's a charismatic speaker.", "Karizmatik bir konuşmacı."],
  ["decisive", "adj", "kararlı, hızlı karar veren", "In a crisis, leaders must be decisive.", "Krizde liderler kararlı olmalı."],
  ["authoritarian", "adj", "otoriter", "He has an authoritarian style.", "Otoriter bir tarzı var."],
  ["empower", "v", "yetkilendirmek, güçlendirmek", "Good leaders empower their teams.", "İyi liderler ekiplerini güçlendirir."],
  ["inspire confidence", "phr", "güven vermek", "Her calm voice inspires confidence.", "Sakin sesi güven veriyor."],
  ["spearhead", "v", "öncülük etmek", "She spearheaded the campaign.", "Kampanyaya öncülük etti."],
  ["at the helm", "phr", "dümende, başında", "With her at the helm, the company grew.", "O başındayken şirket büyüdü."],
  ["delegation", "n", "yetki devri; heyet", "Effective delegation saves time.", "Etkili yetki devri zaman kazandırır."],
  ["figurehead", "n", "göstermelik lider", "The king is just a figurehead.", "Kral sadece göstermelik bir lider."],
  ["succession", "n", "halef olma, yerine geçme", "The company has no succession plan.", "Şirketin bir halef planı yok."],
  ["mandate", "n", "yetki, görev", "The government has a clear mandate.", "Hükümetin açık bir yetkisi var."],
  ["prerogative", "n", "ayrıcalık, özel yetki", "It's the manager's prerogative to decide.", "Karar vermek müdürün özel yetkisi."],
  ["consensus-building", "n", "uzlaşı oluşturma", "Consensus-building takes patience.", "Uzlaşı oluşturmak sabır ister."],
  ["track record", "n", "geçmiş başarı, sicil", "She has an excellent track record.", "Mükemmel bir geçmiş başarısı var."],
  ["lead by example", "phr", "örnek olarak liderlik etmek", "Managers should lead by example.", "Yöneticiler örnek olarak liderlik etmeli."],
  ["take the initiative", "phr", "inisiyatif almak", "Don't wait — take the initiative.", "Bekleme, inisiyatif al."],
  ["call the shots", "phr", "kararları vermek, sözü geçmek", "Who calls the shots here?", "Burada kararları kim veriyor?"],
  ["the buck stops here", "phr", "sorumluluk bende", "As CEO, the buck stops with me.", "CEO olarak sorumluluk bende."],
  ["steer", "v", "yönlendirmek", "She steered the company through the crisis.", "Şirketi krizden geçirerek yönlendirdi."],

  // Set 10 — Entrepreneurship
  ["entrepreneur", "n", "girişimci", "He became an entrepreneur at 22.", "22 yaşında girişimci oldu."],
  ["start-up", "n", "yeni kurulan şirket, girişim", "She works for a tech start-up.", "Bir teknoloji girişiminde çalışıyor."],
  ["venture capital", "n", "risk sermayesi", "They raised venture capital.", "Risk sermayesi topladılar."],
  ["seed funding", "n", "tohum yatırım", "The app received seed funding.", "Uygulama tohum yatırım aldı."],
  ["business plan", "n", "iş planı", "Every start-up needs a business plan.", "Her girişimin bir iş planına ihtiyacı var."],
  ["scalable", "adj", "ölçeklenebilir", "Investors want scalable ideas.", "Yatırımcılar ölçeklenebilir fikirler istiyor."],
  ["profit margin", "n", "kâr marjı", "Profit margins are thin in food retail.", "Gıda perakendesinde kâr marjları düşük."],
  ["cash flow", "n", "nakit akışı", "Many small businesses fail because of cash flow.", "Birçok küçük işletme nakit akışı yüzünden batıyor."],
  ["turnover", "n", "ciro", "The company has an annual turnover of 5 million.", "Şirketin yıllık cirosu 5 milyon."],
  ["overheads", "n", "genel giderler", "Working from home reduces overheads.", "Evden çalışmak genel giderleri azaltır."],
  ["bankrupt", "adj", "iflas etmiş", "The firm went bankrupt in 2019.", "Firma 2019'da iflas etti."],
  ["merger", "n", "birleşme", "The merger created the country's largest bank.", "Birleşme ülkenin en büyük bankasını yarattı."],
  ["acquisition", "n", "satın alma (şirket)", "The acquisition cost $2 billion.", "Satın alma 2 milyar dolara mal oldu."],
  ["pitch", "n", "(yatırımcıya) sunum", "She gave a great pitch to investors.", "Yatırımcılara harika bir sunum yaptı."],
  ["gap in the market", "phr", "pazardaki boşluk", "They spotted a gap in the market.", "Pazarda bir boşluk fark ettiler."],
  ["risk-averse", "adj", "riskten kaçınan", "Banks are risk-averse.", "Bankalar riskten kaçınır."],
  ["disruptive", "adj", "yıkıcı (yenilikçi), düzeni bozan", "Uber was a disruptive business model.", "Uber düzeni bozan bir iş modeliydi."],
  ["franchise", "n", "franchise, bayilik", "They bought a coffee shop franchise.", "Bir kahve dükkânı franchise'ı aldılar."],
  ["bootstrap", "v", "kendi imkânlarıyla kurmak", "They bootstrapped the company without investors.", "Şirketi yatırımcı olmadan kendi imkânlarıyla kurdular."],
  ["get off the ground", "phr", "başlamak, rayına oturmak", "It took a year to get the business off the ground.", "İşi rayına oturtmak bir yıl sürdü."],
];
