import type { LexiconEntry } from "../types";

/** C1 sets 31–35: sociology, culture & identity, historiography, philosophy, belief. */
export const C1_PART7: LexiconEntry[] = [
  // Set 31 — Sociology
  ["socioeconomic", "adj", "sosyoekonomik", "Socioeconomic status affects health.", "Sosyoekonomik durum sağlığı etkiler."],
  ["stratification", "n", "tabakalaşma", "Social stratification limits opportunity.", "Toplumsal tabakalaşma fırsatları sınırlar."],
  ["upward mobility", "n", "yukarı doğru sosyal hareketlilik", "Education drives upward mobility.", "Eğitim yukarı doğru hareketliliği sağlar."],
  ["disenfranchised", "adj", "hakları elinden alınmış, dışlanmış", "Many young people feel disenfranchised.", "Birçok genç kendini dışlanmış hissediyor."],
  ["underclass", "n", "alt sınıf", "The report describes a growing underclass.", "Rapor büyüyen bir alt sınıfı anlatıyor."],
  ["affluent", "adj", "varlıklı, zengin", "They live in an affluent suburb.", "Varlıklı bir banliyöde yaşıyorlar."],
  ["deprivation", "n", "yoksunluk", "Areas of deprivation need investment.", "Yoksunluk yaşanan bölgelerin yatırıma ihtiyacı var."],
  ["social fabric", "n", "toplumsal doku", "Crime damages the social fabric.", "Suç toplumsal dokuya zarar verir."],
  ["alienation", "n", "yabancılaşma", "Urban life can cause alienation.", "Şehir hayatı yabancılaşmaya neden olabilir."],
  ["conformity", "n", "uyumculuk, uyma", "Society pressures us towards conformity.", "Toplum bizi uymaya zorlar."],
  ["subculture", "n", "alt kültür", "Skateboarding has its own subculture.", "Kaykayın kendi alt kültürü var."],
  ["patriarchal", "adj", "ataerkil", "It was a patriarchal society.", "Ataerkil bir toplumdu."],
  ["egalitarian", "adj", "eşitlikçi", "They have an egalitarian relationship.", "Eşitlikçi bir ilişkileri var."],
  ["nuclear family", "n", "çekirdek aile", "The nuclear family is becoming less common.", "Çekirdek aile giderek azalıyor."],
  ["extended family", "n", "geniş aile", "We live near our extended family.", "Geniş ailemizin yakınında yaşıyoruz."],
  ["social cohesion", "n", "toplumsal uyum", "Shared values build social cohesion.", "Ortak değerler toplumsal uyumu güçlendirir."],
  ["civic", "adj", "yurttaşlıkla ilgili", "Voting is a civic duty.", "Oy vermek bir yurttaşlık görevidir."],
  ["philanthropy", "n", "hayırseverlik", "Her philanthropy funded ten schools.", "Hayırseverliği on okulu finanse etti."],
  ["grassroots movement", "n", "tabandan gelen hareket", "It began as a grassroots movement.", "Tabandan gelen bir hareket olarak başladı."],
  ["social unrest", "n", "toplumsal huzursuzluk", "Rising prices led to social unrest.", "Artan fiyatlar toplumsal huzursuzluğa yol açtı."],

  // Set 32 — Culture & identity
  ["heritage language", "n", "miras dil", "Children of migrants may lose their heritage language.", "Göçmen çocukları miras dillerini kaybedebilir."],
  ["cultural appropriation", "n", "kültürel sahiplenme", "The design was criticised as cultural appropriation.", "Tasarım kültürel sahiplenme olarak eleştirildi."],
  ["hybrid", "adj", "melez, karma", "They have a hybrid identity.", "Melez bir kimlikleri var."],
  ["cosmopolitan", "adj", "kozmopolit", "Istanbul has always been cosmopolitan.", "İstanbul her zaman kozmopolit olmuştur."],
  ["parochial", "adj", "dar görüşlü, yöresel", "His views are rather parochial.", "Görüşleri oldukça dar."],
  ["ethnocentric", "adj", "etnik merkezci", "The textbook is ethnocentric.", "Ders kitabı etnik merkezci."],
  ["homogeneous", "adj", "türdeş, homojen", "The village is culturally homogeneous.", "Köy kültürel olarak homojen."],
  ["heterogeneous", "adj", "heterojen, karışık", "The class is linguistically heterogeneous.", "Sınıf dil açısından karışık."],
  ["assimilation", "n", "asimilasyon", "Assimilation can erase traditions.", "Asimilasyon gelenekleri silebilir."],
  ["acculturation", "n", "kültürleşme", "Acculturation takes generations.", "Kültürleşme kuşaklar sürer."],
  ["folklore", "n", "folklor", "Nasreddin Hodja is part of Turkish folklore.", "Nasreddin Hoca Türk folklorunun bir parçası."],
  ["ritualistic", "adj", "ritüel niteliğinde", "Tea drinking is almost ritualistic in Turkey.", "Türkiye'de çay içmek neredeyse bir ritüel."],
  ["custom-bound", "adj", "geleneklere bağlı", "It's a custom-bound community.", "Geleneklere bağlı bir topluluk."],
  ["cultural capital", "n", "kültürel sermaye", "Books at home build cultural capital.", "Evdeki kitaplar kültürel sermaye oluşturur."],
  ["intangible heritage", "n", "somut olmayan miras", "Ebru art is UNESCO intangible heritage.", "Ebru sanatı UNESCO somut olmayan mirası."],
  ["globalised", "adj", "küreselleşmiş", "We live in a globalised world.", "Küreselleşmiş bir dünyada yaşıyoruz."],
  ["melting pot", "n", "eritme potası", "New York is a melting pot of cultures.", "New York kültürlerin eritme potası."],
  ["diasporic", "adj", "diasporaya ait", "Diasporic communities keep old traditions alive.", "Diaspora toplulukları eski gelenekleri yaşatır."],
  ["rootless", "adj", "köksüz", "Moving so often made her feel rootless.", "Bu kadar sık taşınmak onu köksüz hissettirdi."],
  ["kinship", "n", "akrabalık, yakınlık", "There's a strong sense of kinship in the village.", "Köyde güçlü bir akrabalık duygusu var."],

  // Set 33 — History & historiography
  ["historiography", "n", "tarih yazımı", "Ottoman historiography has changed a lot.", "Osmanlı tarih yazımı çok değişti."],
  ["primary source", "n", "birincil kaynak", "Letters are valuable primary sources.", "Mektuplar değerli birincil kaynaklardır."],
  ["secondary source", "n", "ikincil kaynak", "Textbooks are secondary sources.", "Ders kitapları ikincil kaynaklardır."],
  ["revisionist", "adj", "revizyonist", "His revisionist history caused debate.", "Revizyonist tarih yorumu tartışmaya yol açtı."],
  ["anachronism", "n", "anakronizm, çağ dışılık", "A phone in a Roman film is an anachronism.", "Roma filminde telefon bir anakronizmdir."],
  ["epoch", "n", "çağ, devir", "The printing press marked a new epoch.", "Matbaa yeni bir çağ başlattı."],
  ["annals", "n", "yıllıklar, tarihçe", "The event is recorded in the annals of the city.", "Olay şehrin tarihçesinde kayıtlı."],
  ["chronicle", "v", "kaydetmek, tarihçesini yazmak", "The book chronicles the war.", "Kitap savaşın tarihçesini anlatıyor."],
  ["hegemony", "n", "hegemonya, üstünlük", "The empire's hegemony lasted centuries.", "İmparatorluğun hegemonyası yüzyıllar sürdü."],
  ["imperialism", "n", "emperyalizm", "Imperialism shaped the modern world.", "Emperyalizm modern dünyayı şekillendirdi."],
  ["decolonisation", "n", "sömürgesizleştirme", "Decolonisation followed the Second World War.", "Sömürgesizleştirme İkinci Dünya Savaşı'nı izledi."],
  ["annexation", "n", "ilhak", "The annexation was condemned internationally.", "İlhak uluslararası alanda kınandı."],
  ["abdicate", "v", "tahttan feragat etmek", "The king abdicated in 1936.", "Kral 1936'da tahttan feragat etti."],
  ["regime", "n", "rejim", "The regime collapsed in 1989.", "Rejim 1989'da çöktü."],
  ["insurgency", "n", "isyan, ayaklanma hareketi", "The insurgency lasted years.", "İsyan yıllarca sürdü."],
  ["aftermath", "n", "sonrası, ardından gelen dönem", "In the aftermath of the war, cities were rebuilt.", "Savaşın ardından şehirler yeniden inşa edildi."],
  ["precedent", "n", "emsal, öncül örnek", "The case set a precedent.", "Dava bir emsal oluşturdu."],
  ["watershed", "n", "dönüm noktası", "1923 was a watershed in Turkish history.", "1923 Türk tarihinde bir dönüm noktasıydı."],
  ["collective memory", "n", "toplumsal bellek", "The earthquake is part of our collective memory.", "Deprem toplumsal belleğimizin bir parçası."],
  ["posterity", "n", "gelecek kuşaklar", "The letters were kept for posterity.", "Mektuplar gelecek kuşaklar için saklandı."],

  // Set 34 — Philosophy
  ["metaphysics", "n", "metafizik", "Metaphysics asks what reality is.", "Metafizik gerçekliğin ne olduğunu sorar."],
  ["epistemology", "n", "epistemoloji, bilgi felsefesi", "Epistemology studies knowledge.", "Epistemoloji bilgiyi inceler."],
  ["existential", "adj", "varoluşsal", "He had an existential crisis at forty.", "Kırk yaşında varoluşsal bir kriz geçirdi."],
  ["empiricism", "n", "deneycilik", "Empiricism values experience over theory.", "Deneycilik deneyimi teoriden üstün tutar."],
  ["relativism", "n", "görecelik", "Moral relativism says there's no universal truth.", "Ahlaki görecelik evrensel bir hakikat olmadığını söyler."],
  ["utilitarian", "adj", "faydacı", "It was a utilitarian decision.", "Faydacı bir karardı."],
  ["determinism", "n", "belirlenimcilik", "Determinism denies free will.", "Belirlenimcilik özgür iradeyi reddeder."],
  ["dichotomy", "n", "ikilik, ayrım", "There's a false dichotomy between work and life.", "İş ve yaşam arasında yanlış bir ikilik var."],
  ["paradox", "n", "paradoks", "It's a paradox that more choice makes us less happy.", "Daha fazla seçeneğin bizi daha az mutlu etmesi bir paradoks."],
  ["axiom", "n", "aksiyom, temel önerme", "It's an axiom that time is money.", "Zamanın para olduğu temel bir önermedir."],
  ["syllogism", "n", "kıyas (mantık)", "Logic students study syllogisms.", "Mantık öğrencileri kıyasları inceler."],
  ["tenet", "n", "ilke, esas", "Honesty is a basic tenet of the religion.", "Dürüstlük dinin temel ilkelerinden biri."],
  ["moral compass", "n", "ahlaki pusula", "She has a strong moral compass.", "Güçlü bir ahlaki pusulası var."],
  ["nihilism", "n", "nihilizm, hiççilik", "Nihilism rejects all values.", "Nihilizm tüm değerleri reddeder."],
  ["stoicism", "n", "stoacılık", "Stoicism teaches calm acceptance.", "Stoacılık sakin bir kabullenişi öğretir."],
  ["abstract concept", "n", "soyut kavram", "Justice is an abstract concept.", "Adalet soyut bir kavramdır."],
  ["thought experiment", "n", "düşünce deneyi", "Philosophers use thought experiments.", "Filozoflar düşünce deneyleri kullanır."],
  ["inherent", "adj", "doğasında olan, içkin", "There are inherent risks in any sport.", "Her sporun doğasında riskler vardır."],
  ["intrinsic", "adj", "özünde olan, içsel", "Learning has intrinsic value.", "Öğrenmenin kendi içinde bir değeri vardır."],
  ["contemplative", "adj", "düşünceli, tefekkür eden", "He's in a contemplative mood.", "Tefekküre dalmış bir halde."],

  // Set 35 — Belief
  ["faith-based", "adj", "inanç temelli", "Faith-based charities run the shelter.", "Barınağı inanç temelli hayır kurumları işletiyor."],
  ["devout", "adj", "dindar", "Her grandmother is a devout Muslim.", "Büyükannesi dindar bir Müslüman."],
  ["agnostic", "adj", "agnostik", "He describes himself as agnostic.", "Kendini agnostik olarak tanımlıyor."],
  ["theology", "n", "ilahiyat", "She studied theology in Ankara.", "Ankara'da ilahiyat okudu."],
  ["doctrine", "n", "doktrin, öğreti", "The church's doctrine is strict.", "Kilisenin öğretisi katı."],
  ["dogma", "n", "dogma", "Science should question dogma.", "Bilim dogmaları sorgulamalı."],
  ["dogmatic", "adj", "dogmatik", "Don't be so dogmatic.", "Bu kadar dogmatik olma."],
  ["pilgrimage", "n", "hac, kutsal yolculuk", "Millions make the pilgrimage to Mecca.", "Milyonlarca kişi Mekke'ye hacca gider."],
  ["sect", "n", "mezhep, tarikat", "The religion has many sects.", "Dinin birçok mezhebi var."],
  ["mysticism", "n", "tasavvuf, mistisizm", "Rumi's poetry is full of mysticism.", "Mevlana'nın şiiri tasavvufla dolu."],
  ["sermon", "n", "vaaz", "The imam gave a sermon on kindness.", "İmam iyilik üzerine bir vaaz verdi."],
  ["deity", "n", "tanrı, ilah", "The Greeks worshipped many deities.", "Yunanlılar birçok tanrıya taparlardı."],
  ["worship", "v", "ibadet etmek, tapmak", "People worship in many different ways.", "İnsanlar farklı şekillerde ibadet eder."],
  ["afterlife", "n", "ahiret, öbür dünya", "Many religions believe in an afterlife.", "Birçok din ahirete inanır."],
  ["divine", "adj", "ilahi, kutsal", "They believed the king had divine power.", "Kralın ilahi bir güce sahip olduğuna inanıyorlardı."],
  ["sacrilege", "n", "kutsala saygısızlık", "Damaging the temple was seen as sacrilege.", "Tapınağa zarar vermek kutsala saygısızlık sayıldı."],
  ["interfaith", "adj", "dinlerarası", "They organised an interfaith dialogue.", "Dinlerarası bir diyalog düzenlediler."],
  ["fundamentalism", "n", "köktendincilik", "Fundamentalism exists in many religions.", "Köktendincilik birçok dinde vardır."],
  ["secularism", "n", "laiklik", "Secularism separates state and religion.", "Laiklik devlet ile dini ayırır."],
  ["asceticism", "n", "zühd, çilecilik", "The monks lived a life of asceticism.", "Keşişler çileci bir hayat yaşadı."],
];
