import type { LexiconEntry } from "../types";

/** C1 sets 11–15: financial markets, economic policy, justice, governance, international relations. */
export const C1_PART3: LexiconEntry[] = [
  // Set 11 — Financial markets
  ["stock exchange", "n", "borsa", "The company is listed on the stock exchange.", "Şirket borsada işlem görüyor."],
  ["volatile", "adj", "oynak, dalgalı", "Cryptocurrency prices are highly volatile.", "Kripto para fiyatları son derece oynak."],
  ["bull market", "n", "yükseliş piyasası", "Investors enjoyed a long bull market.", "Yatırımcılar uzun bir yükseliş piyasasının keyfini çıkardı."],
  ["bear market", "n", "düşüş piyasası", "We're entering a bear market.", "Bir düşüş piyasasına giriyoruz."],
  ["portfolio", "n", "portföy", "Diversify your investment portfolio.", "Yatırım portföyünü çeşitlendir."],
  ["diversify", "v", "çeşitlendirmek", "Farmers are diversifying into tourism.", "Çiftçiler turizme yönelerek çeşitleniyor."],
  ["dividend", "n", "temettü, kâr payı", "The company pays an annual dividend.", "Şirket yıllık kâr payı dağıtıyor."],
  ["asset", "n", "varlık", "Property is their main asset.", "Emlak onların ana varlığı."],
  ["liability", "n", "yükümlülük, borç; sorun", "The company's liabilities exceed its assets.", "Şirketin borçları varlıklarını aşıyor."],
  ["speculation", "n", "spekülasyon", "Speculation drove up house prices.", "Spekülasyon konut fiyatlarını yükseltti."],
  ["bubble", "n", "balon (ekonomik)", "Experts warn of a housing bubble.", "Uzmanlar bir konut balonu konusunda uyarıyor."],
  ["hedge", "v", "(riske karşı) korunmak", "Investors buy gold to hedge against inflation.", "Yatırımcılar enflasyona karşı korunmak için altın alır."],
  ["liquidity", "n", "likidite, nakde çevrilebilirlik", "Banks need enough liquidity.", "Bankaların yeterli likiditeye ihtiyacı var."],
  ["equity", "n", "öz sermaye; hisse", "They own 30% of the equity.", "Hisselerin %30'u onların."],
  ["bond", "n", "tahvil", "Government bonds are considered safe.", "Devlet tahvilleri güvenli kabul edilir."],
  ["yield", "n", "getiri", "The bond has a yield of 8%.", "Tahvilin getirisi %8."],
  ["plunge", "v", "sert düşmek", "Shares plunged after the announcement.", "Duyurudan sonra hisseler sert düştü."],
  ["rally", "n", "toparlanma, yükseliş (piyasa)", "Markets staged a rally on Friday.", "Piyasalar cuma günü toparlandı."],
  ["insider trading", "n", "içeriden bilgiyle ticaret", "He was jailed for insider trading.", "İçeriden bilgiyle ticaret yaptığı için hapse girdi."],
  ["bailout", "n", "kurtarma paketi", "The bank received a government bailout.", "Banka hükümetten kurtarma paketi aldı."],

  // Set 12 — Economic policy
  ["austerity", "n", "kemer sıkma politikası", "Austerity led to cuts in public services.", "Kemer sıkma kamu hizmetlerinde kesintilere yol açtı."],
  ["stimulus", "n", "teşvik (ekonomik)", "The government announced a stimulus package.", "Hükümet bir teşvik paketi açıkladı."],
  ["taxation", "n", "vergilendirme", "Taxation funds public services.", "Vergilendirme kamu hizmetlerini finanse eder."],
  ["progressive tax", "n", "artan oranlı vergi", "A progressive tax takes more from the rich.", "Artan oranlı vergi zenginlerden daha fazla alır."],
  ["tariff", "n", "gümrük vergisi", "The US imposed tariffs on steel.", "ABD çeliğe gümrük vergisi uyguladı."],
  ["protectionism", "n", "korumacılık", "Protectionism can harm global trade.", "Korumacılık küresel ticarete zarar verebilir."],
  ["free trade", "n", "serbest ticaret", "The countries signed a free trade agreement.", "Ülkeler serbest ticaret anlaşması imzaladı."],
  ["deregulation", "n", "serbestleştirme, kuralsızlaştırma", "Deregulation of banks led to the crisis.", "Bankaların serbestleştirilmesi krize yol açtı."],
  ["privatisation", "n", "özelleştirme", "Privatisation of the railways was controversial.", "Demiryollarının özelleştirilmesi tartışmalıydı."],
  ["nationalise", "v", "devletleştirmek", "The government nationalised the airline.", "Hükümet havayolunu devletleştirdi."],
  ["central bank", "n", "merkez bankası", "The central bank raised interest rates.", "Merkez bankası faiz oranlarını artırdı."],
  ["monetary policy", "n", "para politikası", "Monetary policy aims to control inflation.", "Para politikası enflasyonu kontrol etmeyi amaçlar."],
  ["public debt", "n", "kamu borcu", "Public debt has reached 60% of GDP.", "Kamu borcu GSYH'nin %60'ına ulaştı."],
  ["tax evasion", "n", "vergi kaçakçılığı", "Tax evasion costs the state billions.", "Vergi kaçakçılığı devlete milyarlara mal oluyor."],
  ["tax haven", "n", "vergi cenneti", "The money was hidden in a tax haven.", "Para bir vergi cennetinde saklanmıştı."],
  ["welfare benefits", "n", "sosyal yardımlar", "Millions rely on welfare benefits.", "Milyonlarca kişi sosyal yardımlara bağımlı."],
  ["universal basic income", "n", "evrensel temel gelir", "Some countries are testing universal basic income.", "Bazı ülkeler evrensel temel geliri deniyor."],
  ["trickle-down", "adj", "damlama (ekonomisi)", "Critics reject trickle-down economics.", "Eleştirmenler damlama ekonomisini reddediyor."],
  ["sanctions", "n", "yaptırımlar", "The EU imposed sanctions on the country.", "AB ülkeye yaptırımlar uyguladı."],
  ["fiscal year", "n", "mali yıl", "The fiscal year ends in December.", "Mali yıl aralıkta sona erer."],

  // Set 13 — Justice
  ["jurisdiction", "n", "yargı yetkisi", "The court has no jurisdiction in this case.", "Mahkemenin bu davada yargı yetkisi yok."],
  ["litigation", "n", "dava süreci, yargılama", "Litigation can take years.", "Dava süreci yıllar sürebilir."],
  ["plaintiff", "n", "davacı", "The plaintiff asked for compensation.", "Davacı tazminat talep etti."],
  ["testimony", "n", "tanıklık, ifade", "Her testimony was crucial.", "Onun ifadesi çok önemliydi."],
  ["perjury", "n", "yalan yere yemin", "He was charged with perjury.", "Yalan yere yeminle suçlandı."],
  ["appellate court", "n", "istinaf/temyiz mahkemesi", "The case went to the appellate court.", "Dava istinaf mahkemesine gitti."],
  ["acquittal", "n", "beraat", "The acquittal surprised everyone.", "Beraat kararı herkesi şaşırttı."],
  ["conviction", "n", "mahkûmiyet; inanç", "He has two previous convictions.", "Daha önce iki mahkûmiyeti var."],
  ["miscarriage of justice", "n", "adli hata", "It was a clear miscarriage of justice.", "Açık bir adli hataydı."],
  ["due process", "n", "hukuki süreç, usul güvencesi", "Everyone has the right to due process.", "Herkesin hukuki süreç hakkı vardır."],
  ["presumption of innocence", "n", "masumiyet karinesi", "The presumption of innocence is a basic right.", "Masumiyet karinesi temel bir haktır."],
  ["statute", "n", "kanun, tüzük", "The statute was passed in 1990.", "Kanun 1990'da kabul edildi."],
  ["infringe", "v", "ihlal etmek", "The law infringes on privacy.", "Yasa gizliliği ihlal ediyor."],
  ["liable", "adj", "sorumlu (hukuken)", "The company is liable for the damage.", "Şirket zarardan hukuken sorumlu."],
  ["negligence", "n", "ihmal", "The doctor was accused of negligence.", "Doktor ihmalle suçlandı."],
  ["injunction", "n", "ihtiyati tedbir kararı", "The court issued an injunction.", "Mahkeme bir ihtiyati tedbir kararı verdi."],
  ["custody", "n", "velayet; gözaltı", "She was given custody of the children.", "Çocukların velayeti ona verildi."],
  ["bail", "n", "kefalet", "He was released on bail.", "Kefaletle serbest bırakıldı."],
  ["plead guilty", "phr", "suçunu kabul etmek", "She pleaded guilty to theft.", "Hırsızlık suçunu kabul etti."],
  ["the rule of law", "n", "hukukun üstünlüğü", "Democracy depends on the rule of law.", "Demokrasi hukukun üstünlüğüne dayanır."],

  // Set 14 — Governance
  ["governance", "n", "yönetişim", "Good governance requires transparency.", "İyi yönetişim şeffaflık gerektirir."],
  ["bureaucrat", "n", "bürokrat", "Bureaucrats run the ministries.", "Bakanlıkları bürokratlar yönetiyor."],
  ["decentralise", "v", "yerinden yönetime geçmek, merkezi dağıtmak", "The plan is to decentralise power.", "Plan gücü yerel yönetimlere dağıtmak."],
  ["devolution", "n", "yetki devri (yerel yönetime)", "Scotland gained devolution in 1999.", "İskoçya 1999'da yerel yönetim yetkisi kazandı."],
  ["legitimacy", "n", "meşruiyet", "The election gave the government legitimacy.", "Seçim hükümete meşruiyet kazandırdı."],
  ["sovereignty", "n", "egemenlik", "National sovereignty belongs to the people.", "Egemenlik kayıtsız şartsız milletindir."],
  ["constitution", "n", "anayasa", "The constitution guarantees free speech.", "Anayasa ifade özgürlüğünü güvence altına alır."],
  ["amendment", "n", "değişiklik (yasa, anayasa)", "Parliament approved the amendment.", "Meclis değişikliği onayladı."],
  ["veto", "v", "veto etmek", "The president vetoed the bill.", "Cumhurbaşkanı tasarıyı veto etti."],
  ["ratify", "v", "onaylamak (antlaşma)", "Parliament ratified the treaty.", "Meclis antlaşmayı onayladı."],
  ["bill", "n", "kanun tasarısı", "The bill was debated for hours.", "Tasarı saatlerce tartışıldı."],
  ["incumbent", "n", "görevdeki kişi", "The incumbent won re-election.", "Görevdeki aday yeniden seçildi."],
  ["electorate", "n", "seçmenler", "The electorate is divided.", "Seçmenler bölünmüş durumda."],
  ["populism", "n", "popülizm", "Populism is rising across Europe.", "Popülizm Avrupa genelinde yükseliyor."],
  ["polarisation", "n", "kutuplaşma", "Political polarisation is increasing.", "Siyasi kutuplaşma artıyor."],
  ["civil liberties", "n", "sivil özgürlükler", "The law threatens civil liberties.", "Yasa sivil özgürlükleri tehdit ediyor."],
  ["censorship laws", "n", "sansür yasaları", "Strict censorship laws limit the press.", "Katı sansür yasaları basını sınırlıyor."],
  ["public sector", "n", "kamu sektörü", "He works in the public sector.", "Kamu sektöründe çalışıyor."],
  ["checks and balances", "n", "denge ve denetim mekanizması", "A democracy needs checks and balances.", "Bir demokrasinin denge ve denetim mekanizmalarına ihtiyacı var."],
  ["landslide victory", "n", "ezici zafer", "The party won a landslide victory.", "Parti ezici bir zafer kazandı."],

  // Set 15 — International relations
  ["diplomacy", "n", "diplomasi", "The crisis was solved through diplomacy.", "Kriz diplomasi yoluyla çözüldü."],
  ["diplomat", "n", "diplomat", "She worked as a diplomat in Tokyo.", "Tokyo'da diplomat olarak çalıştı."],
  ["embassy", "n", "büyükelçilik", "Apply for a visa at the embassy.", "Vizeye büyükelçilikten başvur."],
  ["consulate", "n", "konsolosluk", "The consulate is in Istanbul.", "Konsolosluk İstanbul'da."],
  ["ally", "n", "müttefik", "The two countries are close allies.", "İki ülke yakın müttefik."],
  ["alliance", "n", "ittifak", "NATO is a military alliance.", "NATO askeri bir ittifaktır."],
  ["summit meeting", "n", "zirve toplantısı", "Leaders met at a summit meeting in Geneva.", "Liderler Cenevre'de bir zirve toplantısında buluştu."],
  ["bilateral", "adj", "ikili, iki taraflı", "They signed a bilateral agreement.", "İkili bir anlaşma imzaladılar."],
  ["multilateral", "adj", "çok taraflı", "Climate change needs multilateral action.", "İklim değişikliği çok taraflı eylem gerektirir."],
  ["ceasefire", "n", "ateşkes", "A ceasefire was agreed.", "Ateşkes üzerinde anlaşıldı."],
  ["peacekeeping", "n", "barışı koruma", "UN peacekeeping forces arrived.", "BM barış gücü geldi."],
  ["humanitarian aid", "n", "insani yardım", "Humanitarian aid reached the region.", "İnsani yardım bölgeye ulaştı."],
  ["refugee crisis", "n", "mülteci krizi", "Turkey hosts millions during the refugee crisis.", "Türkiye mülteci krizinde milyonlarca kişiye ev sahipliği yapıyor."],
  ["escalation", "n", "tırmanma (gerginlik)", "The UN warned of further escalation.", "BM gerginliğin daha da tırmanması konusunda uyardı."],
  ["de-escalate", "v", "gerginliği azaltmak", "Both sides agreed to de-escalate.", "İki taraf da gerginliği azaltmayı kabul etti."],
  ["territorial dispute", "n", "toprak anlaşmazlığı", "The territorial dispute has lasted decades.", "Toprak anlaşmazlığı onlarca yıldır sürüyor."],
  ["geopolitical", "adj", "jeopolitik", "Turkey has a key geopolitical position.", "Türkiye'nin kilit bir jeopolitik konumu var."],
  ["superpower", "n", "süper güç", "China is becoming a superpower.", "Çin bir süper güç haline geliyor."],
  ["foreign policy", "n", "dış politika", "The new government changed its foreign policy.", "Yeni hükümet dış politikasını değiştirdi."],
  ["envoy", "n", "elçi, temsilci", "A special envoy was sent to the talks.", "Görüşmelere özel bir elçi gönderildi."],
];
