import type { LexiconEntry } from "../types";

/** C1 sets 26–30: media power, digital ethics, criticism, literary analysis, stage & screen. */
export const C1_PART6: LexiconEntry[] = [
  // Set 26 — Media power
  ["agenda-setting", "n", "gündem belirleme", "The media play an agenda-setting role.", "Medya gündem belirleyici bir rol oynar."],
  ["spin", "n", "(haberi) çarpıtma, lehine yorumlama", "The government put a positive spin on the figures.", "Hükümet rakamları olumlu yönde çarpıttı."],
  ["spin doctor", "n", "imaj yöneticisi (siyasi)", "Spin doctors manage the minister's image.", "İmaj yöneticileri bakanın imajını yönetiyor."],
  ["mouthpiece", "n", "sözcü, borazan", "The paper is a mouthpiece for the government.", "Gazete hükümetin borazanı."],
  ["media outlet", "n", "medya kuruluşu", "Several media outlets reported the story.", "Birkaç medya kuruluşu haberi verdi."],
  ["conglomerate", "n", "holding, şirketler topluluğu", "A media conglomerate owns the channel.", "Kanal bir medya holdingine ait."],
  ["gatekeeper", "n", "bekçi, kapı tutucu (bilgi akışında)", "Editors act as gatekeepers of news.", "Editörler haberin kapı bekçisi gibi davranır."],
  ["disinformation", "n", "dezenformasyon", "Disinformation campaigns target elections.", "Dezenformasyon kampanyaları seçimleri hedef alıyor."],
  ["libel", "n", "(yazılı) hakaret, iftira", "The newspaper was sued for libel.", "Gazeteye iftira davası açıldı."],
  ["defamation", "n", "karalama, itibar zedeleme", "He sued for defamation.", "Karalama nedeniyle dava açtı."],
  ["self-censorship", "n", "öz sansür", "Fear leads to self-censorship.", "Korku öz sansüre yol açar."],
  ["watchdog", "n", "denetleyici kurum", "The media should be a watchdog of power.", "Medya gücün denetleyicisi olmalı."],
  ["exposé", "n", "ifşa haberi", "The magazine published an exposé on the factory.", "Dergi fabrikayla ilgili bir ifşa haberi yayımladı."],
  ["leak", "v", "sızdırmak", "Someone leaked the report to the press.", "Biri raporu basına sızdırdı."],
  ["tabloid journalism", "n", "magazin gazeteciliği", "Tabloid journalism invades privacy.", "Magazin gazeteciliği mahremiyeti ihlal ediyor."],
  ["public opinion", "n", "kamuoyu", "Public opinion turned against the plan.", "Kamuoyu plana karşı döndü."],
  ["framing", "n", "çerçeveleme", "The framing of the story was biased.", "Haberin çerçevelemesi taraflıydı."],
  ["news cycle", "n", "haber döngüsü", "The story dominated the news cycle.", "Haber, haber döngüsüne hâkim oldu."],
  ["soundbite", "n", "akılda kalan kısa alıntı", "Politicians speak in soundbites.", "Siyasetçiler akılda kalıcı kısa cümlelerle konuşur."],
  ["op-ed", "n", "görüş yazısı", "She wrote an op-ed about education.", "Eğitim üzerine bir görüş yazısı yazdı."],

  // Set 27 — Digital ethics
  ["data privacy", "n", "veri gizliliği", "Data privacy laws protect users.", "Veri gizliliği yasaları kullanıcıları korur."],
  ["consent", "n", "rıza, onay", "Apps must ask for your consent.", "Uygulamalar onayını istemek zorunda."],
  ["surveillance capitalism", "n", "gözetim kapitalizmi", "Critics warn of surveillance capitalism.", "Eleştirmenler gözetim kapitalizmi konusunda uyarıyor."],
  ["algorithmic bias", "n", "algoritmik önyargı", "Algorithmic bias can lead to discrimination.", "Algoritmik önyargı ayrımcılığa yol açabilir."],
  ["deepfake", "n", "deepfake, sahte video", "The deepfake looked completely real.", "Sahte video tamamen gerçek görünüyordu."],
  ["facial recognition", "n", "yüz tanıma", "Facial recognition is used at airports.", "Havalimanlarında yüz tanıma kullanılıyor."],
  ["opt out", "pv", "katılmamayı seçmek", "You can opt out of data sharing.", "Veri paylaşımından çıkmayı seçebilirsin."],
  ["terms of service", "n", "hizmet şartları", "Nobody reads the terms of service.", "Kimse hizmet şartlarını okumuyor."],
  ["accountable AI", "n", "hesap verebilir yapay zekâ", "Regulators want accountable AI.", "Düzenleyiciler hesap verebilir yapay zekâ istiyor."],
  ["digital divide", "n", "dijital uçurum", "The digital divide excludes poorer families.", "Dijital uçurum yoksul aileleri dışlıyor."],
  ["open source", "adj", "açık kaynak", "The software is open source.", "Yazılım açık kaynak."],
  ["intellectual property", "n", "fikri mülkiyet", "Piracy violates intellectual property.", "Korsanlık fikri mülkiyeti ihlal eder."],
  ["piracy", "n", "korsanlık", "Online piracy costs the film industry.", "İnternet korsanlığı film sektörüne zarar veriyor."],
  ["hack", "v", "hacklemek, izinsiz girmek", "Someone hacked my email account.", "Biri e-posta hesabımı hackledi."],
  ["ransomware", "n", "fidye yazılımı", "Ransomware attacked the hospital's computers.", "Fidye yazılımı hastanenin bilgisayarlarına saldırdı."],
  ["two-factor authentication", "n", "iki adımlı doğrulama", "Turn on two-factor authentication.", "İki adımlı doğrulamayı aç."],
  ["regulate", "v", "düzenlemek (yasal)", "Governments want to regulate AI.", "Hükümetler yapay zekâyı düzenlemek istiyor."],
  ["right to be forgotten", "n", "unutulma hakkı", "EU law includes the right to be forgotten.", "AB hukuku unutulma hakkını içeriyor."],
  ["tech giant", "n", "teknoloji devi", "Tech giants dominate the market.", "Teknoloji devleri piyasaya hâkim."],
  ["attention economy", "n", "dikkat ekonomisi", "Apps compete in the attention economy.", "Uygulamalar dikkat ekonomisinde yarışıyor."],

  // Set 28 — Criticism
  ["critique", "n", "eleştiri (inceleme)", "She wrote a critique of the exhibition.", "Sergi hakkında bir eleştiri yazdı."],
  ["acclaim", "n", "beğeni, alkış", "The novel won critical acclaim.", "Roman eleştirmenlerin beğenisini kazandı."],
  ["lauded", "adj", "övülen", "The lauded director made a new film.", "Övgüyle anılan yönetmen yeni bir film çekti."],
  ["panned", "adj", "yerden yere vurulmuş", "The film was panned by critics.", "Film eleştirmenlerce yerden yere vuruldu."],
  ["derivative", "adj", "özgün olmayan, taklit", "The album sounds derivative.", "Albüm özgün değil, taklit gibi."],
  ["pretentious", "adj", "iddialı, gösterişçi", "The dialogue was pretentious.", "Diyaloglar gösterişçiydi."],
  ["poignant", "adj", "dokunaklı", "It's a poignant story about loss.", "Kayıp üzerine dokunaklı bir hikâye."],
  ["evocative", "adj", "çağrışım yapan, hisler uyandıran", "The photos are very evocative.", "Fotoğraflar çok şey çağrıştırıyor."],
  ["understated", "adj", "abartısız, sade", "Her performance was understated but powerful.", "Performansı abartısız ama güçlüydü."],
  ["overwrought", "adj", "aşırı duygusal, abartılı", "The ending felt overwrought.", "Son bölüm aşırı duygusal geldi."],
  ["thought-provoking", "adj", "düşündürücü", "It's a thought-provoking documentary.", "Düşündürücü bir belgesel."],
  ["formulaic", "adj", "kalıplaşmış, formüle bağlı", "The plot is formulaic.", "Konu kalıplaşmış."],
  ["nuanced", "adj", "incelikli, nüanslı", "The film offers a nuanced view of war.", "Film savaşa incelikli bir bakış sunuyor."],
  ["virtuoso", "n", "virtüöz, usta icracı", "She's a virtuoso on the violin.", "Kemanda bir virtüöz."],
  ["tour de force", "n", "ustalık gösterisi, şaheser", "His performance was a tour de force.", "Performansı bir ustalık gösterisiydi."],
  ["genre-defining", "adj", "türünü tanımlayan", "It's a genre-defining album.", "Türünü tanımlayan bir albüm."],
  ["cult classic", "n", "kült klasik", "The film became a cult classic.", "Film kült klasik oldu."],
  ["masterful", "adj", "ustaca", "The book is a masterful piece of writing.", "Kitap ustaca yazılmış bir eser."],
  ["lacklustre", "adj", "sönük, cansız", "The team gave a lacklustre performance.", "Takım sönük bir performans sergiledi."],
  ["reception", "n", "karşılanma, tepki", "The book had a mixed reception.", "Kitap karışık tepkiler aldı."],

  // Set 29 — Literary analysis
  ["imagery", "n", "imgelem, tasvir", "The poem is full of natural imagery.", "Şiir doğa imgeleriyle dolu."],
  ["motif", "n", "motif", "Water is a recurring motif in the novel.", "Su romanda tekrar eden bir motif."],
  ["foreshadowing", "n", "önceden sezdirme", "The storm is an example of foreshadowing.", "Fırtına önceden sezdirmeye bir örnek."],
  ["narrative voice", "n", "anlatı sesi", "The narrative voice is ironic.", "Anlatı sesi ironik."],
  ["unreliable narrator", "n", "güvenilmez anlatıcı", "The story has an unreliable narrator.", "Hikâyenin güvenilmez bir anlatıcısı var."],
  ["stream of consciousness", "n", "bilinç akışı", "Woolf used stream of consciousness.", "Woolf bilinç akışı tekniğini kullandı."],
  ["juxtaposition", "n", "yan yana koyma, karşıtlık", "The juxtaposition of rich and poor is striking.", "Zengin ve yoksulun yan yana konması çarpıcı."],
  ["connotation", "n", "yan anlam, çağrışım", "'Home' has warm connotations.", "'Yuva' kelimesinin sıcak çağrışımları var."],
  ["subtext", "n", "alt metin", "The subtext of the play is political.", "Oyunun alt metni siyasi."],
  ["allusion", "n", "gönderme, ima", "The title is an allusion to Shakespeare.", "Başlık Shakespeare'e bir gönderme."],
  ["canon", "n", "(edebi) kanon", "The novel is part of the literary canon.", "Roman edebi kanonun bir parçası."],
  ["epilogue", "n", "sonsöz", "The epilogue is set ten years later.", "Sonsöz on yıl sonrasında geçiyor."],
  ["prologue", "n", "önsöz, giriş", "The prologue introduces the narrator.", "Giriş bölümü anlatıcıyı tanıtıyor."],
  ["denouement", "n", "çözüm (hikâyenin sonu)", "The denouement is surprisingly calm.", "Hikâyenin çözümü şaşırtıcı derecede sakin."],
  ["archetype", "n", "arketip, ilk örnek", "The wise old man is a common archetype.", "Bilge yaşlı adam yaygın bir arketip."],
  ["pastiche", "n", "pastiş, öykünme", "The novel is a pastiche of Victorian fiction.", "Roman Viktorya dönemi kurgusuna bir öykünme."],
  ["satirical", "adj", "hicivli", "It's a satirical novel about bureaucracy.", "Bürokrasi üzerine hicivli bir roman."],
  ["lyrical", "adj", "lirik, şiirsel", "Her prose is lyrical.", "Düzyazısı şiirsel."],
  ["dystopian", "adj", "distopik", "'1984' is a dystopian novel.", "'1984' distopik bir roman."],
  ["coming-of-age", "adj", "büyüme/olgunlaşma (hikâyesi)", "It's a coming-of-age story set in Izmir.", "İzmir'de geçen bir olgunlaşma hikâyesi."],

  // Set 30 — Stage & screen
  ["cinematography", "n", "görüntü yönetimi", "The cinematography is stunning.", "Görüntü yönetimi göz alıcı."],
  ["montage", "n", "montaj", "The film opens with a montage of old photos.", "Film eski fotoğraflardan oluşan bir montajla açılıyor."],
  ["auteur", "n", "auteur, imzası olan yönetmen", "Nuri Bilge Ceylan is an auteur.", "Nuri Bilge Ceylan bir auteur yönetmen."],
  ["arthouse", "adj", "sanat (filmi)", "She prefers arthouse films.", "Sanat filmlerini tercih ediyor."],
  ["box-office flop", "n", "gişe fiyaskosu", "The sequel was a box-office flop.", "Devam filmi gişede fiyasko oldu."],
  ["ensemble cast", "n", "kalabalık oyuncu kadrosu", "The film has a strong ensemble cast.", "Filmin güçlü ve kalabalık bir oyuncu kadrosu var."],
  ["understudy", "n", "yedek oyuncu", "The understudy took over the lead role.", "Yedek oyuncu başrolü devraldı."],
  ["monologue", "n", "monolog", "Her monologue moved the audience.", "Monoloğu seyirciyi duygulandırdı."],
  ["improvisation", "n", "doğaçlama", "Much of the dialogue was improvisation.", "Diyalogların çoğu doğaçlamaydı."],
  ["stage adaptation", "n", "sahne uyarlaması", "The novel got a stage adaptation.", "Romanın sahne uyarlaması yapıldı."],
  ["curtain call", "n", "(oyun sonu) selamlama", "The actors took three curtain calls.", "Oyuncular üç kez selamlamaya çıktı."],
  ["matinee", "n", "gündüz gösterimi", "We saw the Saturday matinee.", "Cumartesi gündüz gösterimini izledik."],
  ["box-office receipts", "n", "gişe hasılatı", "Box-office receipts reached $1 billion.", "Gişe hasılatı 1 milyar dolara ulaştı."],
  ["screen adaptation", "n", "beyaz perde uyarlaması", "The screen adaptation changed the ending.", "Beyaz perde uyarlaması sonu değiştirdi."],
  ["dialogue-driven", "adj", "diyaloğa dayalı", "It's a slow, dialogue-driven drama.", "Yavaş, diyaloğa dayalı bir dram."],
  ["slapstick", "n", "fiziksel (kaba) komedi", "Children love slapstick.", "Çocuklar fiziksel komediye bayılır."],
  ["period drama", "n", "dönem dizisi/filmi", "The period drama is set in the 1920s.", "Dönem dizisi 1920'lerde geçiyor."],
  ["method acting", "n", "metot oyunculuğu", "He's famous for method acting.", "Metot oyunculuğuyla ünlü."],
  ["on-screen chemistry", "n", "ekran uyumu", "The leads have great on-screen chemistry.", "Başrollerin ekran uyumu harika."],
  ["the fourth wall", "n", "dördüncü duvar", "The character breaks the fourth wall.", "Karakter dördüncü duvarı yıkıyor."],
];
