import type { LexiconEntry } from "../types";

/** C1 sets 16–20: climate policy, ecology, farming & food systems, urban challenges, engineering. */
export const C1_PART4: LexiconEntry[] = [
  // Set 16 — Climate policy
  ["decarbonise", "v", "karbonsuzlaştırmak", "Industry must decarbonise by 2050.", "Sanayi 2050'ye kadar karbonsuzlaşmalı."],
  ["net zero", "n", "net sıfır (emisyon)", "The country pledged to reach net zero.", "Ülke net sıfıra ulaşma sözü verdi."],
  ["emissions target", "n", "emisyon hedefi", "Few countries meet their emissions targets.", "Az sayıda ülke emisyon hedefini tutturuyor."],
  ["carbon tax", "n", "karbon vergisi", "A carbon tax makes pollution expensive.", "Karbon vergisi kirliliği pahalı hale getirir."],
  ["pledge", "n", "taahhüt, söz", "Governments made pledges at the summit.", "Hükümetler zirvede taahhütlerde bulundu."],
  ["adaptation", "n", "uyum (iklime)", "Adaptation is as important as prevention.", "Uyum, önleme kadar önemlidir."],
  ["resilience", "n", "dayanıklılık, direnç", "Cities must build climate resilience.", "Şehirler iklim dayanıklılığı oluşturmalı."],
  ["greenwashing", "n", "yeşil aklama", "The ad was accused of greenwashing.", "Reklam yeşil aklamayla suçlandı."],
  ["climate refugee", "n", "iklim mültecisi", "Rising seas may create millions of climate refugees.", "Yükselen denizler milyonlarca iklim mültecisi yaratabilir."],
  ["climate justice", "n", "iklim adaleti", "Climate justice asks rich countries to pay more.", "İklim adaleti zengin ülkelerin daha fazla ödemesini talep eder."],
  ["permafrost", "n", "donmuş toprak", "Melting permafrost releases methane.", "Eriyen donmuş toprak metan salıyor."],
  ["methane", "n", "metan", "Cattle produce large amounts of methane.", "Sığırlar büyük miktarda metan üretir."],
  ["carbon capture", "n", "karbon yakalama", "Carbon capture technology is still expensive.", "Karbon yakalama teknolojisi hâlâ pahalı."],
  ["ice sheet", "n", "buz tabakası", "The Greenland ice sheet is melting fast.", "Grönland buz tabakası hızla eriyor."],
  ["global average", "n", "küresel ortalama", "Temperatures are above the global average.", "Sıcaklıklar küresel ortalamanın üzerinde."],
  ["unsustainable", "adj", "sürdürülemez", "Our current lifestyle is unsustainable.", "Mevcut yaşam tarzımız sürdürülemez."],
  ["climate sceptic", "n", "iklim değişikliğine şüpheyle bakan", "Climate sceptics dispute the data.", "İklim şüphecileri verilere itiraz ediyor."],
  ["transition", "n", "geçiş", "The transition to clean energy is under way.", "Temiz enerjiye geçiş sürüyor."],
  ["accord", "n", "anlaşma, uzlaşma", "The Paris Accord was signed in 2015.", "Paris Anlaşması 2015'te imzalandı."],
  ["phase down", "pv", "aşamalı olarak azaltmak", "Countries agreed to phase down coal.", "Ülkeler kömürü aşamalı azaltmayı kabul etti."],

  // Set 17 — Ecology
  ["ecologist", "n", "ekolojist", "Ecologists study how species interact.", "Ekolojistler türlerin nasıl etkileştiğini inceler."],
  ["keystone species", "n", "kilit tür", "Bees are a keystone species.", "Arılar kilit bir türdür."],
  ["invasive species", "n", "istilacı tür", "Invasive species threaten native plants.", "İstilacı türler yerli bitkileri tehdit ediyor."],
  ["native", "adj", "yerli, doğal (tür)", "The tulip is native to Central Asia.", "Lale Orta Asya'ya özgü bir bitkidir."],
  ["endemic", "adj", "endemik, bir bölgeye özgü", "Turkey has many endemic plants.", "Türkiye'de birçok endemik bitki var."],
  ["habitat loss", "n", "yaşam alanı kaybı", "Habitat loss is the main threat to wildlife.", "Yaşam alanı kaybı yaban hayatına en büyük tehdit."],
  ["rewilding", "n", "yeniden yabanlaştırma", "Rewilding projects bring back wolves.", "Yeniden yabanlaştırma projeleri kurtları geri getiriyor."],
  ["reforestation", "n", "yeniden ağaçlandırma", "Reforestation helps absorb carbon.", "Yeniden ağaçlandırma karbon emilimine yardım eder."],
  ["wetland", "n", "sulak alan", "Wetlands are vital for birds.", "Sulak alanlar kuşlar için hayati önemde."],
  ["coral reef", "n", "mercan resifi", "Coral reefs are dying due to warm water.", "Mercan resifleri sıcak su nedeniyle ölüyor."],
  ["bleaching", "n", "(mercan) beyazlaması", "Coral bleaching is caused by heat.", "Mercan beyazlaması sıcaktan kaynaklanır."],
  ["biodegradable", "adj", "doğada çözünebilen", "Use biodegradable bags.", "Doğada çözünebilen poşetler kullan."],
  ["pesticide", "n", "tarım ilacı, böcek ilacı", "Pesticides harm bees.", "Tarım ilaçları arılara zarar verir."],
  ["runoff", "n", "(tarımsal) yüzey akışı", "Fertiliser runoff pollutes rivers.", "Gübre akışı nehirleri kirletiyor."],
  ["extinction", "n", "nesli tükenme", "Many species face extinction.", "Birçok tür yok olma tehlikesiyle karşı karşıya."],
  ["apex predator", "n", "zirve yırtıcı", "The wolf is an apex predator.", "Kurt bir zirve yırtıcıdır."],
  ["carrying capacity", "n", "taşıma kapasitesi", "The island has exceeded its carrying capacity.", "Ada taşıma kapasitesini aştı."],
  ["symbiosis", "n", "ortak yaşam, simbiyoz", "The fish and the coral live in symbiosis.", "Balık ve mercan ortak yaşam içinde."],
  ["pristine", "adj", "bozulmamış, tertemiz", "The lake is in pristine condition.", "Göl el değmemiş durumda."],
  ["fragile ecosystem", "n", "hassas ekosistem", "Tourism damages this fragile ecosystem.", "Turizm bu hassas ekosisteme zarar veriyor."],

  // Set 18 — Farming & food systems
  ["agriculture", "n", "tarım", "Agriculture employs many people in Turkey.", "Türkiye'de tarım birçok insana istihdam sağlıyor."],
  ["crop yield", "n", "ürün verimi", "Drought reduced crop yields.", "Kuraklık ürün verimini düşürdü."],
  ["irrigation", "n", "sulama", "Modern irrigation saves water.", "Modern sulama su tasarrufu sağlar."],
  ["fertiliser", "n", "gübre", "Farmers use too much fertiliser.", "Çiftçiler çok fazla gübre kullanıyor."],
  ["livestock", "n", "çiftlik hayvanları, büyükbaş/küçükbaş", "Livestock farming produces emissions.", "Hayvancılık emisyon üretir."],
  ["monoculture", "n", "tek ürün tarımı", "Monoculture depletes the soil.", "Tek ürün tarımı toprağı tüketir."],
  ["crop rotation", "n", "ekim nöbeti", "Crop rotation keeps soil healthy.", "Ekim nöbeti toprağı sağlıklı tutar."],
  ["genetically modified", "adj", "genetiği değiştirilmiş", "Genetically modified crops are controversial.", "Genetiği değiştirilmiş ürünler tartışmalıdır."],
  ["food security", "n", "gıda güvenliği", "Climate change threatens food security.", "İklim değişikliği gıda güvenliğini tehdit ediyor."],
  ["food waste", "n", "gıda israfı", "A third of food is wasted.", "Gıdanın üçte biri israf ediliyor."],
  ["harvest", "n", "hasat", "The hazelnut harvest starts in August.", "Fındık hasadı ağustosta başlar."],
  ["smallholder", "n", "küçük çiftçi", "Smallholders struggle to compete.", "Küçük çiftçiler rekabet etmekte zorlanıyor."],
  ["subsistence farming", "n", "geçimlik tarım", "Many families rely on subsistence farming.", "Birçok aile geçimlik tarıma bağımlı."],
  ["free-range", "adj", "serbest gezen (hayvan)", "We buy free-range eggs.", "Gezen tavuk yumurtası alıyoruz."],
  ["intensive farming", "n", "yoğun tarım", "Intensive farming harms animal welfare.", "Yoğun tarım hayvan refahına zarar veriyor."],
  ["supply chain", "n", "tedarik zinciri", "The pandemic disrupted supply chains.", "Pandemi tedarik zincirlerini aksattı."],
  ["food miles", "n", "gıda kilometresi", "Local food has fewer food miles.", "Yerel gıdanın taşıma mesafesi daha kısadır."],
  ["arable land", "n", "tarıma elverişli arazi", "Only a third of the land is arable.", "Arazinin sadece üçte biri tarıma elverişli."],
  ["drought-stricken", "adj", "kuraklıktan etkilenmiş", "Drought-stricken farmers need help.", "Kuraklıktan etkilenen çiftçilerin yardıma ihtiyacı var."],
  ["cash crop", "n", "ticari ürün", "Cotton is a major cash crop.", "Pamuk önemli bir ticari üründür."],

  // Set 19 — Urban challenges
  ["urban decay", "n", "kentsel çöküntü", "The district suffered from urban decay.", "Semt kentsel çöküntüden etkilendi."],
  ["overcrowding", "n", "aşırı kalabalık", "Overcrowding is a problem in schools.", "Aşırı kalabalık okullarda bir sorun."],
  ["housing shortage", "n", "konut açığı", "The city faces a housing shortage.", "Şehir konut açığıyla karşı karşıya."],
  ["displacement", "n", "yerinden edilme", "Gentrification causes displacement.", "Soylulaştırma yerinden edilmeye yol açar."],
  ["segregation", "n", "ayrışma, ayrım", "Residential segregation divides the city.", "Konut ayrışması şehri bölüyor."],
  ["informal settlement", "n", "gecekondu, kayıt dışı yerleşim", "Informal settlements grew around the city.", "Şehrin çevresinde kayıt dışı yerleşimler büyüdü."],
  ["urban heat island", "n", "kentsel ısı adası", "Concrete creates an urban heat island.", "Beton kentsel ısı adası oluşturur."],
  ["walkable", "adj", "yürünebilir", "Walkable neighbourhoods are healthier.", "Yürünebilir mahalleler daha sağlıklı."],
  ["mixed-use", "adj", "karma kullanımlı", "The project is a mixed-use development.", "Proje karma kullanımlı bir gelişim alanı."],
  ["public realm", "n", "kamusal alan", "Investment in the public realm improves life.", "Kamusal alana yatırım yaşamı iyileştirir."],
  ["commuter town", "n", "yatakhane şehri", "It has become a commuter town.", "Bir yatakhane şehrine dönüştü."],
  ["brownfield site", "n", "eski sanayi alanı (yeniden kullanılacak)", "They're building homes on a brownfield site.", "Eski bir sanayi alanına evler inşa ediyorlar."],
  ["green belt", "n", "yeşil kuşak", "Building on the green belt is restricted.", "Yeşil kuşakta yapılaşma kısıtlı."],
  ["social housing", "n", "sosyal konut", "The council built more social housing.", "Belediye daha fazla sosyal konut inşa etti."],
  ["urban renewal", "n", "kentsel dönüşüm", "Urban renewal is changing Istanbul.", "Kentsel dönüşüm İstanbul'u değiştiriyor."],
  ["liveability", "n", "yaşanabilirlik", "Vienna tops the liveability rankings.", "Viyana yaşanabilirlik sıralamasında birinci."],
  ["commuting time", "n", "işe gidiş-dönüş süresi", "Average commuting time is 90 minutes.", "Ortalama işe gidiş-dönüş süresi 90 dakika."],
  ["car-free", "adj", "araçsız", "The centre became a car-free zone.", "Merkez araçsız bölge oldu."],
  ["footfall", "n", "(mağaza, bölge) ziyaretçi sayısı", "Footfall in shopping centres has dropped.", "AVM'lerdeki ziyaretçi sayısı düştü."],
  ["sprawling", "adj", "yayılmış, dağınık büyüyen", "Istanbul is a sprawling city.", "İstanbul yayılmış bir şehir."],

  // Set 20 — Engineering
  ["feat", "n", "başarı, marifet", "The bridge is an engineering feat.", "Köprü bir mühendislik harikası."],
  ["prototype", "n", "prototip", "They tested the prototype for months.", "Prototipi aylarca test ettiler."],
  ["specification", "n", "teknik özellik, şartname", "The product meets all specifications.", "Ürün tüm şartnameleri karşılıyor."],
  ["load-bearing", "adj", "taşıyıcı (yapı)", "Don't remove a load-bearing wall.", "Taşıyıcı bir duvarı kaldırma."],
  ["reinforced concrete", "n", "betonarme", "The building is made of reinforced concrete.", "Bina betonarmedir."],
  ["retrofit", "v", "(eski yapıya) sonradan donanım eklemek, güçlendirmek", "Old schools are being retrofitted.", "Eski okullar güçlendiriliyor."],
  ["tunnel", "n", "tünel", "The Eurasia Tunnel runs under the Bosphorus.", "Avrasya Tüneli Boğaz'ın altından geçiyor."],
  ["suspension bridge", "n", "asma köprü", "The Çanakkale Bridge is a suspension bridge.", "Çanakkale Köprüsü bir asma köprüdür."],
  ["dam", "n", "baraj", "The Atatürk Dam is on the Euphrates.", "Atatürk Barajı Fırat üzerinde."],
  ["reservoir", "n", "su haznesi, rezervuar", "The reservoir is only 20% full.", "Rezervuar sadece %20 dolu."],
  ["sewage", "n", "kanalizasyon atığı", "The sewage system needs upgrading.", "Kanalizasyon sisteminin iyileştirilmesi gerekiyor."],
  ["maintenance", "n", "bakım", "The bridge is closed for maintenance.", "Köprü bakım nedeniyle kapalı."],
  ["seismic isolation", "n", "sismik izolasyon", "The new hospital uses seismic isolation.", "Yeni hastane sismik izolasyon kullanıyor."],
  ["durability", "n", "dayanıklılık", "Stone has great durability.", "Taş son derece dayanıklıdır."],
  ["precision", "n", "hassasiyet", "The parts are made with great precision.", "Parçalar büyük bir hassasiyetle üretiliyor."],
  ["blueprint for", "phr", "…için model/plan", "The project is a blueprint for other cities.", "Proje diğer şehirler için bir model."],
  ["structural", "adj", "yapısal", "The earthquake caused structural damage.", "Deprem yapısal hasara neden oldu."],
  ["collapse", "v", "çökmek", "Several buildings collapsed in the earthquake.", "Depremde birkaç bina çöktü."],
  ["inspect", "v", "denetlemek, muayene etmek", "Engineers inspected the bridge.", "Mühendisler köprüyü denetledi."],
  ["building code", "n", "yapı yönetmeliği", "The building didn't meet the building code.", "Bina yapı yönetmeliğine uygun değildi."],
];
