import type { LexiconEntry } from "../types";

/** C1 sets 46–50: academic writing, corporate language, manner & movement, sounds & speech, looking & seeing. */
export const C1_PART10: LexiconEntry[] = [
  // Set 46 — Academic writing phrases
  ["it is widely acknowledged that", "phr", "…genel kabul görmektedir", "It is widely acknowledged that sleep aids memory.", "Uykunun hafızaya yardımcı olduğu genel kabul görmektedir."],
  ["there is a growing body of evidence", "phr", "giderek artan kanıtlar var", "There is a growing body of evidence that exercise helps.", "Egzersizin faydalı olduğuna dair giderek artan kanıtlar var."],
  ["this essay will argue that", "phr", "bu makale …savunacaktır", "This essay will argue that exams should be abolished.", "Bu makale sınavların kaldırılması gerektiğini savunacaktır."],
  ["it could be contended that", "phr", "…ileri sürülebilir", "It could be contended that technology isolates us.", "Teknolojinin bizi yalnızlaştırdığı ileri sürülebilir."],
  ["a case in point", "phr", "buna güzel bir örnek", "Plastic bags are a case in point.", "Plastik poşetler buna güzel bir örnek."],
  ["to a large extent", "phr", "büyük ölçüde", "Success depends to a large extent on effort.", "Başarı büyük ölçüde çabaya bağlıdır."],
  ["it remains to be seen", "phr", "…henüz belli değil, göreceğiz", "It remains to be seen whether the plan works.", "Planın işe yarayıp yaramayacağını zaman gösterecek."],
  ["in the final analysis", "phr", "son tahlilde", "In the final analysis, cost is what matters.", "Son tahlilde önemli olan maliyet."],
  ["with the exception of", "phr", "…hariç", "With the exception of Ali, everyone passed.", "Ali hariç herkes geçti."],
  ["the extent to which", "phr", "…in ne ölçüde olduğu", "We examined the extent to which diet affects mood.", "Beslenmenin ruh halini ne ölçüde etkilediğini inceledik."],
  ["lends weight to", "phr", "…i destekler, …e güç katar", "This study lends weight to the theory.", "Bu çalışma teoriyi destekliyor."],
  ["calls into question", "phr", "…i sorgulatır", "The new data calls into question earlier findings.", "Yeni veriler önceki bulguları sorgulatıyor."],
  ["sheds light on", "phr", "…e ışık tutar", "The letters shed light on his early life.", "Mektuplar onun erken yaşamına ışık tutuyor."],
  ["draws on", "phr", "…den yararlanır", "The paper draws on interviews with teachers.", "Makale öğretmenlerle yapılan görüşmelerden yararlanıyor."],
  ["falls within the scope of", "phr", "…kapsamına girer", "This question falls outside the scope of the study.", "Bu soru çalışmanın kapsamı dışında kalıyor."],
  ["give rise to concern", "phr", "endişeye yol açmak", "The figures give rise to concern.", "Rakamlar endişeye yol açıyor."],
  ["broadly speaking", "phr", "genel olarak konuşursak", "Broadly speaking, the results were positive.", "Genel olarak konuşursak sonuçlar olumluydu."],
  ["it is worth noting that", "phr", "…belirtmekte fayda var", "It is worth noting that the sample was small.", "Örneklemin küçük olduğunu belirtmekte fayda var."],
  ["by way of illustration", "phr", "örnek vermek gerekirse", "By way of illustration, consider Japan.", "Örnek vermek gerekirse, Japonya'yı düşünün."],
  ["the underlying cause", "phr", "altta yatan neden", "Poverty is the underlying cause.", "Altta yatan neden yoksulluk."],

  // Set 47 — Corporate language
  ["leverage", "v", "kaldıraç olarak kullanmak, değerlendirmek", "We should leverage our experience.", "Deneyimimizi değerlendirmeliyiz."],
  ["synergy", "n", "sinerji", "The merger will create synergy.", "Birleşme sinerji yaratacak."],
  ["core competency", "n", "temel yetkinlik", "Design is our core competency.", "Tasarım temel yetkinliğimiz."],
  ["deliverable", "n", "teslim edilecek iş/çıktı", "The deliverables are due on Friday.", "Teslim edilecek işler cuma günü bekleniyor."],
  ["value proposition", "n", "değer önerisi", "What's our value proposition?", "Değer önerimiz nedir?"],
  ["bottom line", "n", "net kâr; sonuç", "The changes improved the bottom line.", "Değişiklikler net kârı artırdı."],
  ["touch base", "phr", "kısaca görüşmek, iletişime geçmek", "Let's touch base next week.", "Gelecek hafta kısaca görüşelim."],
  ["circle back", "phr", "(konuya) sonra dönmek", "Let's circle back to this later.", "Buna sonra dönelim."],
  ["think outside the box", "phr", "kalıpların dışında düşünmek", "We need to think outside the box.", "Kalıpların dışında düşünmeliyiz."],
  ["low-hanging fruit", "n", "kolay kazanımlar", "Start with the low-hanging fruit.", "Kolay kazanımlarla başla."],
  ["move the needle", "phr", "fark yaratmak", "This campaign won't move the needle.", "Bu kampanya fark yaratmaz."],
  ["bandwidth", "n", "(mecazi) zaman/enerji kapasitesi", "I don't have the bandwidth for another project.", "Başka bir proje için vaktim yok."],
  ["streamlined", "adj", "sadeleştirilmiş, verimli", "We now have a streamlined process.", "Artık sadeleştirilmiş bir sürecimiz var."],
  ["key performance indicator", "n", "temel performans göstergesi", "Sales are our main key performance indicator.", "Satışlar ana performans göstergemiz."],
  ["return on investment", "n", "yatırım getirisi", "What's the return on investment?", "Yatırım getirisi nedir?"],
  ["due diligence", "n", "durum tespiti, detaylı inceleme", "Do your due diligence before buying.", "Satın almadan önce detaylı inceleme yap."],
  ["fast-track", "v", "hızlandırmak, öncelik vermek", "They fast-tracked her promotion.", "Terfisini hızlandırdılar."],
  ["headcount", "n", "personel sayısı", "We need to reduce headcount.", "Personel sayısını azaltmamız gerek."],
  ["stakeholder buy-in", "n", "paydaş desteği", "We need stakeholder buy-in first.", "Önce paydaş desteğine ihtiyacımız var."],
  ["run something by someone", "phr", "(fikrini almak için) birine danışmak", "Let me run it by my manager.", "Müdürüme bir danışayım."],

  // Set 48 — Manner & movement
  ["saunter", "v", "ağır ağır yürümek", "He likes to saunter into meetings late.", "Toplantılara geç ve ağır ağır girmeyi sever."],
  ["stride", "v", "uzun adımlarla yürümek", "She strode confidently to the stage.", "Sahneye kendinden emin adımlarla yürüdü."],
  ["stroll", "v", "gezinmek, dolaşmak", "Let's stroll along the Kordon.", "Hadi Kordon boyunca gezinelim."],
  ["trudge", "v", "yorgun argın yürümek", "We had to trudge home through the snow.", "Karda yorgun argın eve yürümek zorunda kaldık."],
  ["stagger", "v", "sendelemek", "He staggered and fell.", "Sendeledi ve düştü."],
  ["stumble", "v", "tökezlemek", "I stumbled on the stairs.", "Merdivende tökezledim."],
  ["dash", "v", "fırlamak, koşmak", "I must dash — my ferry leaves soon.", "Koşmam lazım, vapurum birazdan kalkıyor."],
  ["scurry", "v", "koşuşturmak (küçük adımlarla)", "Mice scurried across the floor.", "Fareler yerde koşuşturdu."],
  ["wander", "v", "gezinmek, amaçsızca dolaşmak", "I love to wander around the old town.", "Eski şehirde amaçsızca dolaşmayı severim."],
  ["creep", "v", "sessizce sokulmak, sinsice ilerlemek", "He crept downstairs at midnight.", "Gece yarısı sessizce aşağı indi."],
  ["limp", "v", "topallamak", "He limped off the pitch.", "Sahadan topallayarak çıktı."],
  ["tiptoe", "v", "parmak uçlarında yürümek", "I tiptoed past the baby's room.", "Bebeğin odasının önünden parmak uçlarımda geçtim."],
  ["slouch", "v", "kamburunu çıkarıp oturmak/durmak", "Don't slouch at your desk.", "Masanda kambur oturma."],
  ["fidget", "v", "kıpır kıpır olmak, yerinde duramamak", "The kids fidgeted during the speech.", "Çocuklar konuşma sırasında yerlerinde duramadı."],
  ["lunge", "v", "atılmak, hamle yapmak", "Watch the goalkeeper lunge for the ball.", "Kalecinin topa atılışını izle."],
  ["sprawl", "v", "yayılıp uzanmak", "He sprawled on the sofa.", "Kanepeye yayılıp uzandı."],
  ["clamber", "v", "(zorlukla) tırmanmak", "We clambered over the rocks.", "Kayaların üzerinden zorlukla tırmandık."],
  ["hobble", "v", "aksayarak yürümek", "The old man hobbled to the bus stop.", "Yaşlı adam aksayarak otobüs durağına yürüdü."],
  ["plod", "v", "ağır ağır ilerlemek", "The project is plodding along.", "Proje ağır ağır ilerliyor."],
  ["meander", "v", "kıvrılarak akmak; oyalanarak ilerlemek", "The river meanders through the valley.", "Nehir vadide kıvrılarak akıyor."],

  // Set 49 — Sounds & speech
  ["mumble", "v", "mırıldanmak, anlaşılmaz konuşmak", "Don't mumble — speak clearly.", "Mırıldanma, açık konuş."],
  ["mutter", "v", "homurdanmak, söylenmek", "He muttered something under his breath.", "Kendi kendine bir şeyler söylendi."],
  ["stammer", "v", "kekelemek", "She stammered an apology.", "Kekeleyerek özür diledi."],
  ["babble", "v", "anlamsız konuşmak, gevezelik etmek", "The baby babbled happily.", "Bebek mutlu mutlu agucuk yaptı."],
  ["drawl", "v", "ağır ağır uzatarak konuşmak", "He drawled his words.", "Kelimeleri uzatarak konuştu."],
  ["bellow", "v", "gürlemek, bağırmak", "The coach bellowed at the players.", "Antrenör oyunculara gürledi."],
  ["shriek", "v", "çığlık atmak, ciyaklamak", "The children shrieked with laughter.", "Çocuklar kahkahayla çığlık attı."],
  ["snap", "v", "çıkışmak, ters cevap vermek", "Sorry I snapped at you.", "Sana çıkıştığım için özür dilerim."],
  ["retort", "v", "karşılık vermek (sert)", "'That's not true!' she retorted.", "'Bu doğru değil!' diye karşılık verdi."],
  ["blurt out", "pv", "ağzından kaçırmak", "He blurted out the secret.", "Sırrı ağzından kaçırdı."],
  ["rustle", "v", "hışırdamak", "Leaves rustled in the wind.", "Yapraklar rüzgârda hışırdadı."],
  ["creak", "v", "gıcırdamak", "The old door creaked.", "Eski kapı gıcırdadı."],
  ["rumble", "v", "gürlemek, guruldamak", "Thunder rumbled in the distance.", "Uzaklarda gök gürledi."],
  ["hum", "v", "mırıldanarak şarkı söylemek; vızıldamak", "She hummed a tune while cooking.", "Yemek yaparken bir ezgi mırıldandı."],
  ["clatter", "v", "takırdamak", "Plates clattered in the kitchen.", "Mutfakta tabaklar takırdadı."],
  ["thud", "n", "gümbürtü, pat sesi", "The book fell with a thud.", "Kitap pat diye düştü."],
  ["screech", "v", "(fren) cırlamak, acı acı ötmek", "The car screeched to a halt.", "Araba fren sesiyle durdu."],
  ["murmur", "n", "mırıltı, uğultu", "There was a murmur of agreement.", "Onaylayan bir mırıltı yükseldi."],
  ["ear-splitting", "adj", "kulak patlatan", "The music was ear-splitting.", "Müzik kulak patlatıyordu."],
  ["hushed", "adj", "kısık, fısıltılı", "They spoke in hushed voices.", "Fısıltıyla konuştular."],

  // Set 50 — Looking & seeing
  ["gaze", "v", "uzun uzun bakmak, dalıp bakmak", "She gazed out of the window.", "Pencereden dışarı dalıp baktı."],
  ["glare", "v", "öfkeyle bakmak", "He glared at me across the table.", "Masanın karşısından bana öfkeyle baktı."],
  ["peer", "v", "dikkatle bakmak, gözlerini kısarak bakmak", "She peered into the dark room.", "Karanlık odaya gözlerini kısarak baktı."],
  ["squint", "v", "gözlerini kısmak", "I had to squint in the bright sun.", "Parlak güneşte gözlerimi kısmak zorunda kaldım."],
  ["glimpse", "n", "bir anlık görüntü", "We caught a glimpse of the dolphins.", "Yunusları bir anlığına gördük."],
  ["peek", "v", "gizlice bakmak", "Don't peek at the answers!", "Cevaplara gizlice bakma!"],
  ["scan", "v", "gözden geçirmek, taramak", "I scanned the list for my name.", "Adımı bulmak için listeye göz gezdirdim."],
  ["gawp", "v", "ağzı açık bakakalmak", "Tourists gawped at the palace.", "Turistler saraya ağızları açık baktı."],
  ["ogle", "v", "(rahatsız edici şekilde) süzmek", "It's rude to ogle people.", "İnsanları süzmek kabalıktır."],
  ["behold", "v", "görmek, seyretmek (edebi)", "The view was a sight to behold.", "Manzara görülmeye değerdi."],
  ["discernible", "adj", "fark edilebilir", "There's no discernible difference.", "Fark edilebilir bir fark yok."],
  ["conspicuous", "adj", "göze çarpan", "He felt conspicuous in his suit.", "Takım elbisesiyle göze battığını hissetti."],
  ["inconspicuous", "adj", "göze çarpmayan", "The camera is small and inconspicuous.", "Kamera küçük ve göze çarpmıyor."],
  ["vantage point", "n", "gözlem noktası", "The hill is a good vantage point.", "Tepe iyi bir gözlem noktası."],
  ["eyesore", "n", "göze batan çirkin şey", "The old factory is an eyesore.", "Eski fabrika göze batan bir çirkinlik."],
  ["eye-catching", "adj", "göz alıcı", "The poster has an eye-catching design.", "Afişin göz alıcı bir tasarımı var."],
  ["catch sight of", "phr", "gözüne ilişmek", "I caught sight of her in the crowd.", "Kalabalıkta gözüme ilişti."],
  ["turn a blind eye to", "phr", "…e göz yummak", "The authorities turned a blind eye to it.", "Yetkililer buna göz yumdu."],
  ["in plain sight", "phr", "göz önünde", "The keys were in plain sight.", "Anahtarlar göz önündeydi."],
  ["at first glance", "phr", "ilk bakışta", "At first glance, the task looked easy.", "İlk bakışta görev kolay görünüyordu."],
];
