import type { LexiconEntry } from "../types";

/** C1 sets 76–80: diplomatic language, natural spoken responses, academic nouns, academic verbs, word pairs. */
export const C1_PART16: LexiconEntry[] = [
  // Set 76 — Diplomatic language
  ["I'm afraid that won't be possible", "phr", "korkarım bu mümkün olmayacak", "I'm afraid that won't be possible this week.", "Korkarım bu hafta mümkün olmayacak."],
  ["with the greatest respect", "phr", "en derin saygılarımla (ama katılmıyorum)", "With the greatest respect, I think you're mistaken.", "En derin saygılarımla, yanıldığınızı düşünüyorum."],
  ["I'm not entirely convinced", "phr", "tam olarak ikna olmadım", "I'm not entirely convinced by the figures.", "Rakamlar beni tam olarak ikna etmedi."],
  ["perhaps we could consider", "phr", "belki şunu değerlendirebiliriz", "Perhaps we could consider a different approach.", "Belki farklı bir yaklaşımı değerlendirebiliriz."],
  ["I was wondering whether", "phr", "acaba …diye merak ediyordum", "I was wondering whether you could help me.", "Acaba bana yardım edebilir misiniz diye merak ediyordum."],
  ["it might be worth", "phr", "…mek faydalı olabilir", "It might be worth checking the figures again.", "Rakamları tekrar kontrol etmek faydalı olabilir."],
  ["that's a fair point, but", "phr", "haklı bir nokta ama", "That's a fair point, but it's too late.", "Haklı bir nokta ama çok geç."],
  ["I appreciate your concern", "phr", "endişenizi anlıyorum", "I appreciate your concern, but we're fine.", "Endişenizi anlıyorum ama biz iyiyiz."],
  ["let's not lose sight of", "phr", "…i gözden kaçırmayalım", "Let's not lose sight of our main goal.", "Ana hedefimizi gözden kaçırmayalım."],
  ["to be perfectly honest", "phr", "açıkçası, tamamen dürüst olmak gerekirse", "To be perfectly honest, I'm disappointed.", "Tamamen dürüst olmak gerekirse, hayal kırıklığına uğradım."],
  ["I'd like to raise a concern", "phr", "bir endişemi dile getirmek isterim", "I'd like to raise a concern about the budget.", "Bütçeyle ilgili bir endişemi dile getirmek isterim."],
  ["could I just come in here", "phr", "burada söz alabilir miyim", "Could I just come in here with a quick point?", "Kısa bir nokta için burada söz alabilir miyim?"],
  ["if I could just finish", "phr", "sözümü bitirebilir miyim", "If I could just finish my point…", "Sözümü bitirebilirsem…"],
  ["I take your point, however", "phr", "ne demek istediğinizi anlıyorum, ancak", "I take your point; however, the cost is high.", "Ne demek istediğinizi anlıyorum, ancak maliyet yüksek."],
  ["that's not quite what I meant", "phr", "tam olarak onu kastetmedim", "Sorry, that's not quite what I meant.", "Pardon, tam olarak onu kastetmedim."],
  ["let me put it another way", "phr", "başka bir şekilde ifade edeyim", "Let me put it another way.", "Başka bir şekilde ifade edeyim."],
  ["I'll have to get back to you", "phr", "size dönüş yapmam gerekecek", "I'll have to get back to you on that.", "Bu konuda size dönüş yapmam gerekecek."],
  ["with that in mind", "phr", "bunu dikkate alarak", "With that in mind, let's move on.", "Bunu dikkate alarak devam edelim."],
  ["for the record", "phr", "kayıtlara geçsin diye, belirtmek isterim ki", "For the record, I disagreed.", "Belirtmek isterim ki ben katılmamıştım."],
  ["I hear what you're saying", "phr", "ne dediğini anlıyorum", "I hear what you're saying, but we can't change it.", "Ne dediğini anlıyorum ama değiştiremeyiz."],

  // Set 77 — Natural spoken responses
  ["fair play", "phr", "helal olsun, hakkını vermek lazım", "You finished it in a day? Fair play!", "Bir günde mi bitirdin? Helal olsun!"],
  ["tell me about it", "phr", "sorma, bilmez miyim", "This traffic is awful. — Tell me about it!", "Trafik berbat. — Sorma!"],
  ["I'll say", "phr", "hem de nasıl", "Was it hot? — I'll say!", "Sıcak mıydı? — Hem de nasıl!"],
  ["you can say that again", "phr", "çok doğru, aynen", "It's expensive. — You can say that again.", "Pahalı. — Aynen öyle."],
  ["don't get me wrong", "phr", "yanlış anlama", "Don't get me wrong, I like him.", "Yanlış anlama, onu seviyorum."],
  ["I wouldn't go that far", "phr", "o kadar da değil", "It's the best film ever? I wouldn't go that far.", "Tüm zamanların en iyi filmi mi? O kadar da değil."],
  ["fingers crossed", "phr", "inşallah, umarım", "Fingers crossed for the exam!", "Sınav için umarım her şey iyi geçer!"],
  ["touch wood", "phr", "tahtaya vur", "I've never been ill, touch wood.", "Hiç hasta olmadım, tahtaya vur."],
  ["fancy that", "phr", "vay be, şu işe bak", "She's moving to Japan? Fancy that!", "Japonya'ya mı taşınıyor? Şu işe bak!"],
  ["not on your life", "phr", "asla, hayatta olmaz", "Would you jump? — Not on your life!", "Atlar mısın? — Hayatta olmaz!"],
  ["search me", "phr", "ne bileyim, bilmiyorum", "Where's the key? — Search me!", "Anahtar nerede? — Ne bileyim!"],
  ["you're telling me", "phr", "bana mı söylüyorsun", "It's cold. — You're telling me!", "Hava soğuk. — Bana mı söylüyorsun!"],
  ["no hard feelings", "phr", "kırgınlık yok", "You won fair and square. No hard feelings.", "Hakkıyla kazandın. Kırgınlık yok."],
  ["over my dead body", "phr", "ölümü çiğnemeden olmaz", "Sell the house? Over my dead body!", "Evi satmak mı? Ölümü çiğnemeden olmaz!"],
  ["it's on the tip of my tongue", "phr", "dilimin ucunda", "Her name… it's on the tip of my tongue!", "Adı… dilimin ucunda!"],
  ["now you're talking", "phr", "işte şimdi konuştun", "Pizza tonight? Now you're talking!", "Bu akşam pizza mı? İşte şimdi konuştun!"],
  ["that'll be the day", "phr", "o günü de görürsek", "Him, on time? That'll be the day!", "O mu, zamanında mı? O günü de görürsek!"],
  ["I'm all for it", "phr", "sonuna kadar destekliyorum", "A four-day week? I'm all for it.", "Dört günlük çalışma haftası mı? Sonuna kadar destekliyorum."],
  ["say no more", "phr", "anladım, başka söze gerek yok", "You need a lift? Say no more.", "Arabayla bırakılman mı gerek? Başka söze gerek yok."],
  ["don't hold your breath", "phr", "boşuna bekleme", "He said he'd call, but don't hold your breath.", "Arayacağını söyledi ama boşuna bekleme."],

  // Set 78 — Academic nouns
  ["advent", "n", "gelişi, ortaya çıkışı", "The advent of the internet changed everything.", "İnternetin ortaya çıkışı her şeyi değiştirdi."],
  ["aggregate", "n", "toplam", "The team won 4–2 on aggregate.", "Takım toplamda 4-2 kazandı."],
  ["attribute", "n", "nitelik, özellik", "Patience is a key attribute for teachers.", "Sabır öğretmenler için kilit bir niteliktir."],
  ["constraint", "n", "kısıt, sınırlama", "Budget constraints limited the project.", "Bütçe kısıtları projeyi sınırladı."],
  ["criterion", "n", "ölçüt, kriter", "What are the criteria for selection?", "Seçim kriterleri nelerdir?", "çoğulu: criteria"],
  ["dimension", "n", "boyut", "The problem has a political dimension.", "Sorunun siyasi bir boyutu var."],
  ["domain", "n", "alan, saha", "This question lies outside my domain.", "Bu soru benim alanımın dışında."],
  ["facet", "n", "yön, boyut", "The book explores every facet of her life.", "Kitap hayatının her yönünü inceliyor."],
  ["implication", "n", "sonuç, çıkarım, ima", "Consider the implications of your decision.", "Kararının sonuçlarını düşün."],
  ["magnitude", "n", "büyüklük, boyut", "We didn't realise the magnitude of the problem.", "Sorunun büyüklüğünü fark etmedik."],
  ["notion", "n", "kavram, fikir", "The notion of privacy is changing.", "Mahremiyet kavramı değişiyor."],
  ["parameter", "n", "parametre, sınır", "We must work within these parameters.", "Bu sınırlar içinde çalışmalıyız."],
  ["phenomenon", "n", "olgu, fenomen", "Migration is a global phenomenon.", "Göç küresel bir olgudur.", "çoğulu: phenomena"],
  ["precedence", "n", "öncelik", "Safety takes precedence over speed.", "Güvenlik hızdan önce gelir."],
  ["spectrum", "n", "yelpaze, spektrum", "People across the political spectrum agree.", "Siyasi yelpazenin her kesimi hemfikir."],
  ["synthesis", "n", "sentez", "The book is a synthesis of recent research.", "Kitap son araştırmaların bir sentezi."],
  ["trajectory", "n", "gidişat, yörünge", "Her career is on an upward trajectory.", "Kariyeri yükselen bir gidişatta."],
  ["undercurrent", "n", "alttan alta hissedilen duygu", "There was an undercurrent of tension.", "Alttan alta bir gerginlik vardı."],
  ["veracity", "n", "doğruluk, gerçeklik", "Journalists must check the veracity of sources.", "Gazeteciler kaynakların doğruluğunu kontrol etmeli."],
  ["zeitgeist", "n", "çağın ruhu", "The film captures the zeitgeist of the 1990s.", "Film 1990'ların ruhunu yakalıyor."],

  // Set 79 — Academic verbs
  ["ascribe", "v", "atfetmek, bağlamak", "She ascribes her success to luck.", "Başarısını şansa bağlıyor."],
  ["concur", "v", "hemfikir olmak", "I concur with the previous speaker.", "Önceki konuşmacıyla hemfikirim."],
  ["constitute", "v", "oluşturmak, teşkil etmek", "Women constitute half the workforce.", "Kadınlar iş gücünün yarısını oluşturuyor."],
  ["delineate", "v", "tanımlamak, sınırlarını çizmek", "The report delineates the main risks.", "Rapor ana riskleri tanımlıyor."],
  ["elicit", "v", "(bilgi, tepki) ortaya çıkarmak, almak", "The question elicited no response.", "Soru hiçbir tepki almadı."],
  ["elucidate", "v", "açıklığa kavuşturmak", "Could you elucidate your point?", "Görüşünüzü açıklığa kavuşturabilir misiniz?"],
  ["encapsulate", "v", "özetlemek, özünü yakalamak", "The photo encapsulates the spirit of the city.", "Fotoğraf şehrin ruhunu özetliyor."],
  ["posit", "v", "ileri sürmek, varsaymak", "The theory posits that language is innate.", "Teori dilin doğuştan geldiğini ileri sürer."],
  ["postulate", "v", "varsaymak, önermek", "Scientists postulated the existence of the particle.", "Bilim insanları parçacığın varlığını varsaydı."],
  ["preempt", "v", "önüne geçmek, önceden davranmak", "We tried to preempt any complaints.", "Şikâyetlerin önüne geçmeye çalıştık."],
  ["refine", "v", "inceltmek, geliştirmek", "She refined her argument.", "Argümanını geliştirdi."],
  ["surmise", "v", "tahmin etmek, sezmek", "I surmised that he was tired.", "Yorgun olduğunu tahmin ettim."],
  ["underscore", "v", "vurgulamak, altını çizmek", "The crisis underscores the need for reform.", "Kriz reform ihtiyacının altını çiziyor."],
  ["warrant", "v", "gerektirmek, haklı kılmak", "The situation warrants urgent action.", "Durum acil eylem gerektiriyor."],
  ["yield", "v", "vermek, sonuç doğurmak; boyun eğmek", "The study yielded interesting results.", "Çalışma ilginç sonuçlar verdi."],
  ["culminate in", "phr", "…ile sonuçlanmak, doruğa ulaşmak", "The protests culminated in a general strike.", "Protestolar genel grevle doruğa ulaştı."],
  ["bear out", "pv", "doğrulamak", "The results bear out our theory.", "Sonuçlar teorimizi doğruluyor."],
  ["give credence to", "phr", "…e inandırıcılık kazandırmak", "New evidence gives credence to her story.", "Yeni kanıtlar hikâyesine inandırıcılık kazandırıyor."],
  ["hinge on", "pv", "…e bağlı olmak", "Everything hinges on the vote.", "Her şey oylamaya bağlı."],
  ["pertain to", "pv", "…ile ilgili olmak", "These rules pertain to all staff.", "Bu kurallar tüm personeli ilgilendiriyor."],

  // Set 80 — Word pairs
  ["odds and ends", "phr", "ıvır zıvır", "The drawer is full of odds and ends.", "Çekmece ıvır zıvırla dolu."],
  ["wear and tear", "phr", "yıpranma, aşınma", "The sofa shows signs of wear and tear.", "Kanepede yıpranma belirtileri var."],
  ["peace and quiet", "phr", "huzur ve sessizlik", "I just want some peace and quiet.", "Sadece biraz huzur ve sessizlik istiyorum."],
  ["safe and sound", "phr", "sağ salim", "They arrived safe and sound.", "Sağ salim vardılar."],
  ["sick and tired", "phr", "bıkıp usanmış", "I'm sick and tired of waiting.", "Beklemekten bıktım usandım."],
  ["give and take", "phr", "karşılıklı fedakârlık", "Marriage is all about give and take.", "Evlilik tamamen karşılıklı fedakârlıktır."],
  ["touch and go", "phr", "belirsiz, riskli", "It was touch and go whether we'd make it.", "Yetişip yetişemeyeceğimiz belirsizdi."],
  ["far and wide", "phr", "her yerden, dört bir yandan", "People came from far and wide.", "İnsanlar dört bir yandan geldi."],
  ["few and far between", "phr", "nadir, seyrek", "Good jobs are few and far between.", "İyi işler nadirdir."],
  ["the ins and outs", "phr", "incelikleri, ayrıntıları", "She knows the ins and outs of the business.", "İşin bütün inceliklerini biliyor."],
  ["ups and downs", "phr", "iniş çıkışlar", "Every relationship has its ups and downs.", "Her ilişkinin iniş çıkışları vardır."],
  ["in black and white", "phr", "yazılı olarak; net", "I want the agreement in black and white.", "Anlaşmayı yazılı olarak istiyorum."],
  ["short and sweet", "phr", "kısa ve öz", "Keep your speech short and sweet.", "Konuşmanı kısa ve öz tut."],
  ["loud and clear", "phr", "açık ve net", "I hear you loud and clear.", "Seni açık ve net duyuyorum."],
  ["high and dry", "phr", "ortada, yüzüstü", "They left us high and dry.", "Bizi ortada bıraktılar."],
  ["null and void", "phr", "hükümsüz, geçersiz", "The contract is null and void.", "Sözleşme hükümsüz."],
  ["part and parcel", "phr", "ayrılmaz parçası", "Stress is part and parcel of the job.", "Stres işin ayrılmaz parçası."],
  ["tried and tested", "phr", "denenmiş ve güvenilir", "It's a tried and tested method.", "Denenmiş ve güvenilir bir yöntem."],
  ["hustle and bustle", "phr", "koşuşturma, kalabalık telaşı", "I love the hustle and bustle of Istanbul.", "İstanbul'un koşuşturmasını seviyorum."],
  ["bits and pieces", "phr", "ufak tefek şeyler", "I need to pick up a few bits and pieces.", "Birkaç ufak tefek şey almam gerek."],
];
