import type { LexiconEntry } from "../types";

/** C1 sets 41–45: nuanced adverbs, cohesion devices, collocations, idioms, proverbs & sayings. */
export const C1_PART9: LexiconEntry[] = [
  // Set 41 — Nuanced adverbs
  ["categorically", "adv", "kesinlikle, kategorik olarak", "He categorically denied the claims.", "İddiaları kesinlikle reddetti."],
  ["conspicuously", "adv", "göze batacak şekilde", "She was conspicuously absent.", "Göze batacak şekilde yoktu."],
  ["inadvertently", "adv", "istemeden, yanlışlıkla", "I inadvertently deleted the file.", "İstemeden dosyayı sildim."],
  ["invariably", "adv", "her zaman, değişmez şekilde", "He invariably arrives late.", "Her zaman geç gelir."],
  ["ostensibly", "adv", "görünüşte, sözde", "He came, ostensibly to help.", "Görünüşte yardım etmek için geldi."],
  ["profoundly", "adv", "derinden", "The book profoundly changed me.", "Kitap beni derinden değiştirdi."],
  ["reputedly", "adv", "söylendiğine göre", "The house is reputedly haunted.", "Söylendiğine göre evde hayalet varmış."],
  ["scarcely", "adv", "neredeyse hiç, ancak", "I could scarcely believe it.", "Neredeyse inanamadım."],
  ["tacitly", "adv", "zımnen, üstü kapalı", "They tacitly agreed to ignore it.", "Görmezden gelmeye zımnen karar verdiler."],
  ["unwittingly", "adv", "farkında olmadan", "She unwittingly helped the thief.", "Farkında olmadan hırsıza yardım etti."],
  ["vehemently", "adv", "şiddetle", "He vehemently opposed the plan.", "Plana şiddetle karşı çıktı."],
  ["wholeheartedly", "adv", "yürekten, tüm kalbiyle", "I wholeheartedly agree.", "Tüm kalbimle katılıyorum."],
  ["painstakingly", "adv", "büyük özenle", "The mosaic was painstakingly restored.", "Mozaik büyük özenle restore edildi."],
  ["begrudgingly", "adv", "gönülsüzce", "He begrudgingly apologised.", "Gönülsüzce özür diledi."],
  ["decidedly", "adv", "kesinlikle, belirgin şekilde", "The weather is decidedly colder.", "Hava belirgin şekilde daha soğuk."],
  ["exceedingly", "adv", "son derece", "It's an exceedingly rare condition.", "Son derece nadir bir rahatsızlık."],
  ["fundamentally", "adv", "temelden, esasen", "The system is fundamentally flawed.", "Sistem temelden kusurlu."],
  ["markedly", "adv", "belirgin şekilde", "Sales have improved markedly.", "Satışlar belirgin şekilde arttı."],
  ["notably", "adv", "özellikle, bilhassa", "Several cities, notably Izmir, were affected.", "Birkaç şehir, özellikle İzmir, etkilendi."],
  ["subsequently", "adv", "sonradan, ardından", "He was arrested and subsequently released.", "Tutuklandı ve ardından serbest bırakıldı."],

  // Set 42 — Cohesion devices
  ["notwithstanding this", "phr", "buna rağmen", "Notwithstanding this, the project succeeded.", "Buna rağmen proje başarılı oldu."],
  ["be that as it may", "phr", "her ne kadar öyle olsa da", "Be that as it may, we must decide today.", "Her ne kadar öyle olsa da bugün karar vermeliyiz."],
  ["by the same token", "phr", "aynı şekilde, aynı mantıkla", "By the same token, we should also cut costs.", "Aynı mantıkla maliyetleri de düşürmeliyiz."],
  ["in the same vein", "phr", "aynı doğrultuda", "In the same vein, the second study found…", "Aynı doğrultuda ikinci çalışma şunu buldu…"],
  ["to that end", "phr", "bu amaçla", "To that end, we hired more staff.", "Bu amaçla daha fazla personel aldık."],
  ["with this in mind", "phr", "bunu göz önünde bulundurarak", "With this in mind, we changed the plan.", "Bunu göz önünde bulundurarak planı değiştirdik."],
  ["in so far as", "conj", "…dığı ölçüde", "I'll help in so far as I can.", "Elimden geldiği ölçüde yardım edeceğim."],
  ["inasmuch as", "conj", "…dığı için, …dığı ölçüde", "He's guilty inasmuch as he knew.", "Bildiği ölçüde suçlu."],
  ["insofar as", "conj", "…dığı kadarıyla", "Insofar as I know, it's true.", "Bildiğim kadarıyla doğru."],
  ["albeit", "conj", "gerçi, …olsa da", "It was a success, albeit a small one.", "Küçük de olsa bir başarıydı."],
  ["thereby", "adv", "böylece, bu suretle", "He saved money, thereby avoiding debt.", "Para biriktirdi, böylece borçtan kaçındı."],
  ["on balance", "phr", "genel olarak değerlendirildiğinde", "On balance, the benefits outweigh the costs.", "Genel olarak değerlendirildiğinde faydalar maliyetlerden ağır basıyor."],
  ["that said", "phr", "bununla birlikte", "It's expensive. That said, it's worth it.", "Pahalı. Bununla birlikte değer."],
  ["having said that", "phr", "bunu söyledikten sonra, yine de", "It's hard. Having said that, it's rewarding.", "Zor. Yine de tatmin edici."],
  ["as a corollary", "phr", "bunun doğal sonucu olarak", "As a corollary, prices will rise.", "Bunun doğal sonucu olarak fiyatlar artacak."],
  ["first and foremost", "phr", "her şeyden önce", "First and foremost, thank you all.", "Her şeyden önce hepinize teşekkürler."],
  ["last but not least", "phr", "son ama önemli", "Last but not least, thanks to my family.", "Son ama önemli, aileme teşekkürler."],
  ["not least because", "phr", "özellikle de …dığı için", "It's popular, not least because it's cheap.", "Özellikle de ucuz olduğu için popüler."],
  ["in essence", "phr", "özünde", "In essence, the two plans are the same.", "Özünde iki plan aynı."],
  ["by extension", "phr", "dolayısıyla, genişletirsek", "Parents, and by extension schools, must act.", "Ebeveynler ve dolayısıyla okullar harekete geçmeli."],

  // Set 43 — Collocations
  ["bone of contention", "phr", "anlaşmazlık konusu", "Money is a bone of contention.", "Para bir anlaşmazlık konusu."],
  ["vested interest", "n", "kişisel çıkar", "He has a vested interest in the project.", "Projede kişisel çıkarı var."],
  ["foregone conclusion", "n", "önceden belli olan sonuç", "The result was a foregone conclusion.", "Sonuç önceden belliydi."],
  ["sweeping changes", "n", "köklü değişiklikler", "The new CEO made sweeping changes.", "Yeni CEO köklü değişiklikler yaptı."],
  ["widespread support", "n", "geniş destek", "The plan has widespread support.", "Planın geniş desteği var."],
  ["deep-rooted", "adj", "köklü, derinlere işlemiş", "It's a deep-rooted problem.", "Köklü bir sorun."],
  ["far-reaching", "adj", "geniş kapsamlı", "The reforms will have far-reaching effects.", "Reformların geniş kapsamlı etkileri olacak."],
  ["long-standing", "adj", "uzun süredir var olan", "They have a long-standing rivalry.", "Uzun süredir devam eden bir rekabetleri var."],
  ["short-lived", "adj", "kısa ömürlü", "Their happiness was short-lived.", "Mutlulukları kısa ömürlü oldu."],
  ["ill-advised", "adj", "akılsızca, yanlış", "It was an ill-advised decision.", "Akılsızca bir karardı."],
  ["well-founded", "adj", "temelli, yerinde", "Your fears are well-founded.", "Korkuların yerinde."],
  ["half-hearted", "adj", "gönülsüz, yarım ağızla", "He made a half-hearted attempt.", "Gönülsüz bir girişimde bulundu."],
  ["heartfelt", "adj", "içten", "Please accept my heartfelt thanks.", "İçten teşekkürlerimi kabul edin."],
  ["pressing issue", "n", "acil sorun", "Housing is the most pressing issue.", "Konut en acil sorun."],
  ["stark contrast", "n", "keskin tezat", "There's a stark contrast between the two cities.", "İki şehir arasında keskin bir tezat var."],
  ["sheer luck", "n", "tamamen şans", "We won by sheer luck.", "Tamamen şans eseri kazandık."],
  ["gross negligence", "n", "ağır ihmal", "The company was guilty of gross negligence.", "Şirket ağır ihmalden suçluydu."],
  ["abject poverty", "n", "sefalet, derin yoksulluk", "Millions live in abject poverty.", "Milyonlarca kişi sefalet içinde yaşıyor."],
  ["vicious circle", "n", "kısır döngü", "Debt creates a vicious circle.", "Borç bir kısır döngü yaratır."],
  ["blatant lie", "n", "düpedüz yalan", "That's a blatant lie!", "Bu düpedüz yalan!"],

  // Set 44 — Idioms
  ["a double-edged sword", "phr", "iki ucu keskin kılıç", "Fame is a double-edged sword.", "Şöhret iki ucu keskin bir kılıçtır."],
  ["a moot point", "phr", "tartışmaya açık/artık önemsiz nokta", "Whether he knew is a moot point.", "Bilip bilmediği artık önemsiz bir nokta."],
  ["add insult to injury", "phr", "üstüne tuz biber ekmek", "To add insult to injury, it started raining.", "Üstüne tuz biber, yağmur başladı."],
  ["bite off more than you can chew", "phr", "boyundan büyük işe kalkışmak", "I bit off more than I could chew.", "Boyumdan büyük işe kalkıştım."],
  ["burn the midnight oil", "phr", "gece yarılarına kadar çalışmak", "She burned the midnight oil before the exam.", "Sınavdan önce gece yarılarına kadar çalıştı."],
  ["cut to the chase", "phr", "sadede gelmek", "Let's cut to the chase.", "Sadede gelelim."],
  ["go the extra mile", "phr", "fazlasını yapmak, ekstra çaba göstermek", "Our staff go the extra mile.", "Personelimiz fazlasını yapar."],
  ["in the same boat", "phr", "aynı durumda", "We're all in the same boat.", "Hepimiz aynı gemideyiz."],
  ["jump on the bandwagon", "phr", "modaya/rüzgâra uymak", "Everyone is jumping on the AI bandwagon.", "Herkes yapay zekâ rüzgârına kapılıyor."],
  ["keep someone at arm's length", "phr", "birine mesafeli durmak", "She keeps her colleagues at arm's length.", "İş arkadaşlarına mesafeli duruyor."],
  ["leave no stone unturned", "phr", "her yolu denemek", "Police will leave no stone unturned.", "Polis her yolu deneyecek."],
  ["move the goalposts", "phr", "kuralları sonradan değiştirmek", "The boss keeps moving the goalposts.", "Patron kuralları sürekli değiştiriyor."],
  ["on thin ice", "phr", "tehlikeli durumda, ince buz üstünde", "You're on thin ice after yesterday.", "Dünden sonra ince buz üstündesin."],
  ["read between the lines", "phr", "satır aralarını okumak", "Read between the lines of his email.", "E-postasının satır aralarını oku."],
  ["take something with a pinch of salt", "phr", "ihtiyatla yaklaşmak", "Take his advice with a pinch of salt.", "Tavsiyesine ihtiyatla yaklaş."],
  ["the writing is on the wall", "phr", "sonun geldiği belli", "The writing is on the wall for the old factory.", "Eski fabrikanın sonunun geldiği belli."],
  ["throw caution to the wind", "phr", "tedbiri elden bırakmak", "She threw caution to the wind and quit.", "Tedbiri elden bırakıp istifa etti."],
  ["a storm in a teacup", "phr", "bir bardak suda fırtına", "The argument was a storm in a teacup.", "Tartışma bir bardak suda fırtınaydı."],
  ["bark up the wrong tree", "phr", "yanlış kapı çalmak", "If you think I did it, you're barking up the wrong tree.", "Benim yaptığımı düşünüyorsan yanlış kapı çalıyorsun."],
  ["have a chip on your shoulder", "phr", "içinde ukde olmak, alıngan olmak", "He has a chip on his shoulder about his education.", "Eğitimi konusunda içinde bir ukde var."],

  // Set 45 — Sayings
  ["the pen is mightier than the sword", "phr", "kalem kılıçtan keskindir", "Journalists know the pen is mightier than the sword.", "Gazeteciler kalemin kılıçtan keskin olduğunu bilir."],
  ["actions speak louder than words", "phr", "söz değil, iş önemlidir", "Don't promise — actions speak louder than words.", "Söz verme, önemli olan iştir."],
  ["don't count your chickens", "phr", "dereyi görmeden paçaları sıvama", "Don't count your chickens before they hatch.", "Dereyi görmeden paçaları sıvama."],
  ["every cloud has a silver lining", "phr", "her işte bir hayır vardır", "Every cloud has a silver lining.", "Her işte bir hayır vardır."],
  ["the grass is always greener", "phr", "komşunun tavuğu komşuya kaz görünür", "The grass is always greener on the other side.", "Komşunun tavuğu komşuya kaz görünür."],
  ["when in Rome", "phr", "girdiğin yerin âdetlerine uy", "When in Rome, do as the Romans do.", "Nereye gidersen oranın âdetlerine uy."],
  ["too many cooks spoil the broth", "phr", "iki kaptan bir gemiyi batırır", "Too many cooks spoil the broth.", "İki kaptan bir gemiyi batırır."],
  ["the early bird catches the worm", "phr", "erken kalkan yol alır", "The early bird catches the worm.", "Erken kalkan yol alır."],
  ["where there's smoke, there's fire", "phr", "ateş olmayan yerden duman çıkmaz", "Where there's smoke, there's fire.", "Ateş olmayan yerden duman çıkmaz."],
  ["a stitch in time saves nine", "phr", "vaktinde yapılan küçük iş büyük zararı önler", "Fix the leak now — a stitch in time saves nine.", "Sızıntıyı şimdi tamir et, vaktinde yapılan iş büyük zararı önler."],
  ["practice makes perfect", "phr", "işleyen demir pas tutmaz", "Keep going — practice makes perfect.", "Devam et, işleyen demir pas tutmaz."],
  ["out of sight, out of mind", "phr", "gözden ırak olan gönülden de ırak olur", "Out of sight, out of mind.", "Gözden ırak olan gönülden de ırak olur."],
  ["birds of a feather flock together", "phr", "tencere yuvarlanmış kapağını bulmuş", "Birds of a feather flock together.", "Tencere yuvarlanmış kapağını bulmuş."],
  ["better the devil you know", "phr", "bildiğin şeytan bilmediğin melekten iyidir", "Better the devil you know than the devil you don't.", "Bildiğin şeytan bilmediğin melekten iyidir."],
  ["easier said than done", "phr", "söylemesi kolay", "Quitting sugar is easier said than done.", "Şekeri bırakmak söylemesi kolay."],
  ["no pain, no gain", "phr", "emek olmadan yemek olmaz", "No pain, no gain.", "Emek olmadan yemek olmaz."],
  ["Rome wasn't built in a day", "phr", "Roma bir günde kurulmadı", "Be patient — Rome wasn't built in a day.", "Sabırlı ol, Roma bir günde kurulmadı."],
  ["the proof of the pudding", "phr", "bir şeyin değeri denenince anlaşılır", "The proof of the pudding is in the eating.", "Bir şeyin değeri denenince anlaşılır."],
  ["you can't have your cake and eat it", "phr", "hem dağ hem bağ olmaz", "You can't have your cake and eat it.", "Hem dağ hem bağ olmaz."],
  ["time and tide wait for no man", "phr", "zaman kimseyi beklemez", "Time and tide wait for no man.", "Zaman kimseyi beklemez."],
];
