import type { LexiconEntry } from "../types";

/** C1 sets 56–60: influence, honesty & deceit, ambition, difficulty & effort, atmosphere. */
export const C1_PART12: LexiconEntry[] = [
  // Set 56 — Influence
  ["coax", "v", "tatlılıkla ikna etmek", "She coaxed the cat out from under the bed.", "Kediyi tatlılıkla yatağın altından çıkardı."],
  ["cajole", "v", "dil dökerek kandırmak", "He cajoled her into lending him money.", "Dil dökerek ondan borç almayı başardı."],
  ["coerce", "v", "zorlamak, baskı yapmak", "He was coerced into signing.", "İmzalamaya zorlandı."],
  ["sway", "v", "etkilemek, fikrini değiştirmek", "Her speech swayed the voters.", "Konuşması seçmenleri etkiledi."],
  ["entice", "v", "cezbetmek, ayartmak", "Low prices entice customers.", "Düşük fiyatlar müşterileri cezbeder."],
  ["lure", "v", "tuzağa çekmek, cezbetmek", "Scammers lure victims with fake prizes.", "Dolandırıcılar sahte ödüllerle kurbanları tuzağa çeker."],
  ["manipulate", "v", "manipüle etmek", "He manipulated the data.", "Verileri manipüle etti."],
  ["indoctrinate", "v", "beynini yıkamak, telkin etmek", "The group indoctrinated young members.", "Grup genç üyelerin beynini yıkadı."],
  ["pressurise", "v", "baskı yapmak", "Don't let them pressurise you.", "Sana baskı yapmalarına izin verme."],
  ["dissuade", "v", "vazgeçirmek, caydırmak", "I tried to dissuade him from quitting.", "Onu istifa etmekten vazgeçirmeye çalıştım."],
  ["prevail upon", "pv", "ikna etmek (resmi)", "We prevailed upon her to stay.", "Kalması için onu ikna ettik."],
  ["browbeat", "v", "yıldırmak, gözdağı vererek zorlamak", "They browbeat him into agreeing.", "Gözdağı vererek onu kabule zorladılar."],
  ["clout", "n", "nüfuz, etki", "The company has political clout.", "Şirketin siyasi nüfuzu var."],
  ["sway over", "phr", "…üzerinde etki", "He has great sway over the committee.", "Komite üzerinde büyük etkisi var."],
  ["charm offensive", "n", "sevimlilik atağı", "The minister launched a charm offensive.", "Bakan bir sevimlilik atağı başlattı."],
  ["arm-twisting", "n", "kol bükme, baskı", "It took some arm-twisting to get him to agree.", "Onu ikna etmek biraz baskı gerektirdi."],
  ["soft power", "n", "yumuşak güç", "Turkish TV series are a form of soft power.", "Türk dizileri bir tür yumuşak güçtür."],
  ["propagate", "v", "yaymak (fikir)", "The website propagates conspiracy theories.", "Web sitesi komplo teorileri yayıyor."],
  ["subliminal", "adj", "bilinçaltına yönelik", "The ad contains subliminal messages.", "Reklam bilinçaltı mesajları içeriyor."],
  ["hold sway", "phr", "etkili olmak, hâkim olmak", "These ideas still hold sway.", "Bu fikirler hâlâ hâkim."],

  // Set 57 — Honesty & deceit
  ["deceit", "n", "hile, aldatmaca", "The relationship was built on deceit.", "İlişki aldatmaca üzerine kuruluydu."],
  ["deceptive", "adj", "aldatıcı", "Appearances can be deceptive.", "Görünüş aldatıcı olabilir."],
  ["duplicity", "n", "ikiyüzlülük", "Her duplicity shocked us.", "İkiyüzlülüğü bizi şoke etti."],
  ["hypocrisy", "n", "ikiyüzlülük", "It's hypocrisy to preach what you don't practise.", "Uygulamadığın şeyi vaaz etmek ikiyüzlülüktür."],
  ["hypocritical", "adj", "ikiyüzlü", "Politicians are often hypocritical.", "Siyasetçiler çoğu zaman ikiyüzlüdür."],
  ["fabricate", "v", "uydurmak, sahtesini yapmak", "The journalist fabricated the interview.", "Gazeteci röportajı uydurdu."],
  ["falsify", "v", "tahrif etmek", "He falsified the documents.", "Belgeleri tahrif etti."],
  ["embezzle", "v", "zimmete geçirmek", "The accountant embezzled millions.", "Muhasebeci milyonları zimmetine geçirdi."],
  ["con", "v", "dolandırmak", "They conned tourists out of their money.", "Turistleri paralarından dolandırdılar."],
  ["hoax", "n", "asılsız haber, şaka", "The bomb threat was a hoax.", "Bomba tehdidi asılsızdı."],
  ["white lie", "n", "masum yalan", "I told a white lie to avoid hurting her.", "Onu kırmamak için masum bir yalan söyledim."],
  ["candour", "n", "açık sözlülük", "I appreciate your candour.", "Açık sözlülüğünü takdir ediyorum."],
  ["forthright", "adj", "dobra, açık sözlü", "She's forthright about her opinions.", "Görüşleri konusunda dobradır."],
  ["transparent", "adj", "şeffaf; bariz", "His excuse was transparent.", "Bahanesi barizdi."],
  ["disingenuous", "adj", "samimiyetsiz", "It's disingenuous to say you didn't know.", "Bilmediğini söylemek samimiyetsizlik."],
  ["come clean", "phr", "itiraf etmek, doğruyu söylemek", "It's time to come clean.", "Doğruyu söyleme zamanı."],
  ["pull the wool over someone's eyes", "phr", "birini kandırmak, gözünü boyamak", "You can't pull the wool over my eyes.", "Benim gözümü boyayamazsın."],
  ["above board", "phr", "dürüst, yasal", "The deal was completely above board.", "Anlaşma tamamen dürüst ve yasaldı."],
  ["cover up", "pv", "örtbas etmek", "They tried to cover up the scandal.", "Skandalı örtbas etmeye çalıştılar."],
  ["cover-up", "n", "örtbas", "The investigation revealed a cover-up.", "Soruşturma bir örtbası ortaya çıkardı."],

  // Set 58 — Ambition
  ["aspiration", "n", "özlem, hedef", "She has aspirations to become a surgeon.", "Cerrah olma hedefi var."],
  ["aspire", "v", "hedeflemek, arzulamak", "He aspires to run his own company.", "Kendi şirketini yönetmeyi hedefliyor."],
  ["driven", "adj", "hırslı, azimli", "She's a very driven person.", "Çok hırslı biri."],
  ["go-getter", "n", "işini bitiren, girişken kişi", "Our new manager is a real go-getter.", "Yeni müdürümüz gerçekten girişken biri."],
  ["overachiever", "n", "aşırı başarı odaklı kişi", "She's an overachiever who never rests.", "Hiç dinlenmeyen aşırı başarı odaklı biri."],
  ["pinnacle", "n", "zirve, doruk", "Winning the Oscar was the pinnacle of his career.", "Oscar kazanmak kariyerinin zirvesiydi."],
  ["heyday", "n", "altın çağ, en parlak dönem", "In its heyday, the port was very busy.", "En parlak döneminde liman çok hareketliydi."],
  ["rise to fame", "n", "şöhrete yükseliş", "Her rise to fame was rapid.", "Şöhrete yükselişi hızlı oldu."],
  ["make a name for yourself", "phr", "adını duyurmak", "He made a name for himself as a chef.", "Aşçı olarak adını duyurdu."],
  ["come into your own", "phr", "yeteneğini göstermek, parlamak", "She really came into her own at university.", "Üniversitede gerçekten parladı."],
  ["fulfilment", "n", "tatmin, doyum", "He finds fulfilment in teaching.", "Öğretmenlikte tatmin buluyor."],
  ["accolade", "n", "övgü, ödül", "The film received many accolades.", "Film birçok övgü aldı."],
  ["laurels", "n", "şan, başarı", "Don't rest on your laurels.", "Başarılarınla yetinip durma."],
  ["trailblazer", "n", "öncü, yol açan", "She was a trailblazer for women in science.", "Bilimde kadınlar için bir öncüydü."],
  ["prodigy", "n", "dâhi (genç yaşta)", "Mozart was a child prodigy.", "Mozart çocuk dâhiydi."],
  ["upwardly mobile", "adj", "yükselen (sosyal statüde)", "They're a young, upwardly mobile couple.", "Genç ve yükselen bir çift."],
  ["reach for the stars", "phr", "yüksek hedefler koymak", "Our teacher told us to reach for the stars.", "Öğretmenimiz yüksek hedefler koymamızı söyledi."],
  ["cut-throat", "adj", "acımasız (rekabet)", "Fashion is a cut-throat industry.", "Moda acımasız bir sektör."],
  ["rat race", "n", "koşuşturma, hayat yarışı", "He left the rat race and moved to a village.", "Hayat yarışını bırakıp köye taşındı."],
  ["at the top of your game", "phr", "formunun zirvesinde", "She's at the top of her game.", "Formunun zirvesinde."],

  // Set 59 — Difficulty & effort
  ["daunting", "adj", "göz korkutucu", "Learning a new language can be daunting.", "Yeni bir dil öğrenmek göz korkutucu olabilir."],
  ["gruelling", "adj", "yorucu, zorlu", "It was a gruelling 12-hour shift.", "Yorucu bir 12 saatlik vardiyaydı."],
  ["strenuous", "adj", "zahmetli, yorucu", "Avoid strenuous exercise after eating.", "Yemekten sonra yorucu egzersizden kaçın."],
  ["formidable", "adj", "zorlu, heybetli", "She's a formidable opponent.", "Zorlu bir rakip."],
  ["uphill battle", "n", "zorlu mücadele", "Changing the law is an uphill battle.", "Yasayı değiştirmek zorlu bir mücadele."],
  ["hurdle", "n", "engel", "The final hurdle is the interview.", "Son engel mülakat."],
  ["grind", "n", "angarya, bitmek bilmeyen iş", "The daily grind wears me down.", "Günlük angarya beni yıpratıyor."],
  ["persevere", "v", "sebat etmek, azimle devam etmek", "If you persevere, you'll succeed.", "Azimle devam edersen başarırsın."],
  ["perseverance", "n", "azim, sebat", "Success requires perseverance.", "Başarı azim gerektirir."],
  ["exert", "v", "(güç, çaba) sarf etmek", "Don't exert yourself too much.", "Kendini fazla yorma."],
  ["toil", "v", "didinmek, çok çalışmak", "Farmers toiled in the fields.", "Çiftçiler tarlalarda didindi."],
  ["labour-intensive", "adj", "emek yoğun", "Carpet weaving is labour-intensive.", "Halı dokuma emek yoğun bir iştir."],
  ["painstaking", "adj", "özenli, titiz", "It was painstaking work.", "Özenli bir işti."],
  ["effortless", "adj", "zahmetsiz", "She makes it look effortless.", "Zahmetsizmiş gibi gösteriyor."],
  ["sweat blood", "phr", "kan ter içinde çalışmak", "We sweated blood to finish on time.", "Zamanında bitirmek için kan ter içinde çalıştık."],
  ["against all odds", "phr", "tüm olasılıklara rağmen", "Against all odds, they won.", "Tüm olasılıklara rağmen kazandılar."],
  ["go to great lengths", "phr", "çok zahmete girmek", "She went to great lengths to help us.", "Bize yardım etmek için çok zahmete girdi."],
  ["bend over backwards", "phr", "elinden gelen her şeyi yapmak", "The staff bent over backwards to help.", "Personel yardım etmek için elinden geleni yaptı."],
  ["Herculean", "adj", "çok zor, dev (iş)", "Cleaning the city after the flood was a Herculean task.", "Selden sonra şehri temizlemek devasa bir işti."],
  ["plain sailing", "phr", "kolay, sorunsuz", "The rest of the project was plain sailing.", "Projenin geri kalanı sorunsuz geçti."],

  // Set 60 — Atmosphere
  ["serene", "adj", "sakin, huzurlu", "The lake was serene at dawn.", "Göl şafakta huzurluydu."],
  ["tranquil", "adj", "dingin, sakin", "We stayed in a tranquil village.", "Dingin bir köyde kaldık."],
  ["idyllic", "adj", "idil gibi, pastoral", "The island is idyllic.", "Ada bir idil gibi."],
  ["eerie", "adj", "ürkütücü, tekinsiz", "There was an eerie silence.", "Tekinsiz bir sessizlik vardı."],
  ["ominous", "adj", "uğursuz, kötü habercisi", "Ominous clouds gathered.", "Kötü habercisi bulutlar toplandı."],
  ["foreboding", "n", "kötü önsezi", "I had a sense of foreboding.", "İçimde kötü bir önsezi vardı."],
  ["oppressive", "adj", "boğucu, baskıcı", "The heat was oppressive.", "Sıcak boğucuydu."],
  ["stifling", "adj", "boğucu, bunaltıcı", "The office was stifling in August.", "Ağustosta ofis bunaltıcıydı."],
  ["convivial", "adj", "neşeli, samimi (ortam)", "The dinner had a convivial atmosphere.", "Akşam yemeğinde samimi ve neşeli bir hava vardı."],
  ["festive", "adj", "şenlikli, bayram havasında", "The streets had a festive feel.", "Sokaklarda bayram havası vardı."],
  ["sombre", "adj", "kasvetli, ağırbaşlı", "The mood at the funeral was sombre.", "Cenazede ağır bir hava vardı."],
  ["bleak", "adj", "iç karartıcı, ümitsiz", "The future looks bleak.", "Gelecek iç karartıcı görünüyor."],
  ["dingy", "adj", "loş ve kirli", "They rented a dingy flat.", "Loş ve kirli bir daire kiraladılar."],
  ["palpable", "adj", "elle tutulur gibi, belirgin", "The tension in the room was palpable.", "Odadaki gerginlik elle tutulur gibiydi."],
  ["electric", "adj", "(atmosfer) coşkulu, elektrikli", "The atmosphere at the stadium was electric.", "Stadyumdaki atmosfer coşkuluydu."],
  ["laid-back", "adj", "rahat, gevşek", "Bodrum has a laid-back vibe.", "Bodrum'un rahat bir havası var."],
  ["frenetic", "adj", "çılgınca hareketli", "The pace of life is frenetic in Istanbul.", "İstanbul'da hayatın temposu çılgınca."],
  ["desolate", "adj", "ıssız, terk edilmiş", "The village was desolate in winter.", "Köy kışın ıssızdı."],
  ["homely atmosphere", "n", "ev sıcaklığında ortam", "The café has a homely atmosphere.", "Kafenin ev sıcaklığında bir ortamı var."],
  ["ambience", "n", "ortam, hava", "The restaurant has a romantic ambience.", "Restoranın romantik bir havası var."],
];
