import type { LexiconEntry } from "../types";

/** C1 sets 66–70: physical sciences, computing, maths & logic, the future, innovation. */
export const C1_PART14: LexiconEntry[] = [
  // Set 66 — Physical sciences
  ["compound", "n", "bileşik", "Water is a compound of hydrogen and oxygen.", "Su hidrojen ve oksijenden oluşan bir bileşiktir."],
  ["element", "n", "element", "Gold is a chemical element.", "Altın kimyasal bir elementtir."],
  ["catalyst", "n", "katalizör", "The crisis was a catalyst for change.", "Kriz değişim için bir katalizördü."],
  ["friction", "n", "sürtünme; anlaşmazlık", "Friction slows the wheel down.", "Sürtünme tekerleği yavaşlatır."],
  ["velocity", "n", "hız (vektörel)", "The rocket reached a high velocity.", "Roket yüksek bir hıza ulaştı."],
  ["momentum", "n", "ivme, momentum", "The campaign is gaining momentum.", "Kampanya ivme kazanıyor."],
  ["kinetic", "adj", "kinetik, hareketle ilgili", "Wind turbines turn kinetic energy into electricity.", "Rüzgâr türbinleri kinetik enerjiyi elektriğe çevirir."],
  ["radiation", "n", "radyasyon", "X-rays use radiation.", "Röntgen radyasyon kullanır."],
  ["nuclear fission", "n", "nükleer fisyon", "Power plants use nuclear fission.", "Santraller nükleer fisyon kullanır."],
  ["electromagnetic", "adj", "elektromanyetik", "Light is an electromagnetic wave.", "Işık elektromanyetik bir dalgadır."],
  ["wavelength", "n", "dalga boyu", "Red light has a longer wavelength.", "Kırmızı ışığın dalga boyu daha uzundur."],
  ["be on the same wavelength", "phr", "aynı frekansta olmak", "We're on the same wavelength.", "Aynı frekanstayız."],
  ["combustion", "n", "yanma", "Combustion releases energy.", "Yanma enerji açığa çıkarır."],
  ["corrosion", "n", "aşınma, paslanma", "Salt water speeds up corrosion.", "Tuzlu su aşınmayı hızlandırır."],
  ["dissolve", "v", "çözünmek, erimek", "Sugar dissolves in water.", "Şeker suda çözünür."],
  ["evaporate", "v", "buharlaşmak", "The water evaporated in the sun.", "Su güneşte buharlaştı."],
  ["condense", "v", "yoğunlaşmak; kısaltmak", "Steam condenses on the cold window.", "Buhar soğuk camda yoğunlaşır."],
  ["density", "n", "yoğunluk", "Ice has a lower density than water.", "Buzun yoğunluğu sudan düşüktür."],
  ["vacuum", "n", "boşluk, vakum", "Sound can't travel in a vacuum.", "Ses boşlukta yayılamaz."],
  ["quantum", "adj", "kuantum", "Quantum computing could change everything.", "Kuantum bilişim her şeyi değiştirebilir."],

  // Set 67 — Computing
  ["source code", "n", "kaynak kodu", "The company released its source code.", "Şirket kaynak kodunu yayımladı."],
  ["debug", "v", "hata ayıklamak", "It took hours to debug the program.", "Programdaki hataları ayıklamak saatler sürdü."],
  ["compatibility", "n", "uyumluluk", "Check compatibility before installing.", "Kurmadan önce uyumluluğu kontrol et."],
  ["latency", "n", "gecikme süresi", "Low latency is vital for online games.", "Çevrimiçi oyunlar için düşük gecikme hayati önemde."],
  ["server", "n", "sunucu", "The server crashed during the sale.", "İndirim sırasında sunucu çöktü."],
  ["interface", "n", "arayüz", "The interface is intuitive.", "Arayüz sezgisel."],
  ["backend", "n", "arka uç", "He works on the backend of the app.", "Uygulamanın arka ucunda çalışıyor."],
  ["scalability", "n", "ölçeklenebilirlik", "Cloud services offer scalability.", "Bulut hizmetleri ölçeklenebilirlik sunar."],
  ["redundancy", "n", "yedeklilik (sistem)", "The system has built-in redundancy.", "Sistemde yerleşik yedeklilik var."],
  ["vulnerability", "n", "güvenlik açığı; savunmasızlık", "Hackers exploited a vulnerability.", "Hackerlar bir güvenlik açığından yararlandı."],
  ["patch", "n", "yama (yazılım)", "Install the latest security patch.", "En son güvenlik yamasını yükle."],
  ["firewall", "n", "güvenlik duvarı", "The firewall blocked the attack.", "Güvenlik duvarı saldırıyı engelledi."],
  ["neural network", "n", "sinir ağı", "The AI uses a neural network.", "Yapay zekâ bir sinir ağı kullanıyor."],
  ["large language model", "n", "büyük dil modeli", "Large language models can write essays.", "Büyük dil modelleri kompozisyon yazabilir."],
  ["training data", "n", "eğitim verisi", "The model's training data was biased.", "Modelin eğitim verisi taraflıydı."],
  ["computing power", "n", "işlem gücü", "AI needs enormous computing power.", "Yapay zekâ muazzam işlem gücü gerektirir."],
  ["legacy system", "n", "eski (miras) sistem", "Banks still run legacy systems.", "Bankalar hâlâ eski sistemleri kullanıyor."],
  ["user experience", "n", "kullanıcı deneyimi", "Good user experience keeps customers.", "İyi kullanıcı deneyimi müşteriyi tutar."],
  ["beta version", "n", "beta sürümü", "You can try the beta version.", "Beta sürümünü deneyebilirsin."],
  ["crash", "v", "(sistem) çökmek", "My laptop keeps crashing.", "Dizüstü bilgisayarım sürekli çöküyor."],

  // Set 68 — Maths & logic
  ["equation", "n", "denklem", "Solve the equation for x.", "Denklemi x için çöz."],
  ["probability", "n", "olasılık", "The probability of rain is 70%.", "Yağmur olasılığı %70."],
  ["statistic", "n", "istatistik (tek veri)", "One statistic stands out.", "Bir istatistik öne çıkıyor."],
  ["median", "n", "medyan, ortanca", "The median income is lower than the average.", "Ortanca gelir ortalamanın altında."],
  ["ratio", "n", "oran", "The ratio of students to teachers is 20:1.", "Öğrenci-öğretmen oranı 20'ye 1."],
  ["proportional", "adj", "orantılı", "Tax should be proportional to income.", "Vergi gelirle orantılı olmalı."],
  ["variable", "adj", "değişken", "The weather is variable in spring.", "İlkbaharda hava değişkendir."],
  ["deduction", "n", "tümdengelim; indirim", "Sherlock Holmes used deduction.", "Sherlock Holmes tümdengelim kullanırdı."],
  ["induction", "n", "tümevarım; oryantasyon", "Science relies on induction.", "Bilim tümevarıma dayanır."],
  ["logical fallacy", "n", "mantık hatası", "That argument contains a logical fallacy.", "O argüman bir mantık hatası içeriyor."],
  ["axiomatic", "adj", "apaçık, tartışmasız", "It's axiomatic that prices rise with demand.", "Fiyatların taleple arttığı tartışmasızdır."],
  ["valid argument", "n", "geçerli argüman", "A valid argument can still be false.", "Geçerli bir argüman yine de yanlış olabilir."],
  ["counterintuitive", "adj", "sezgiye aykırı", "The result is counterintuitive.", "Sonuç sezgiye aykırı."],
  ["margin of error", "n", "hata payı", "The poll has a margin of error of 3%.", "Anketin hata payı %3."],
  ["outlier", "n", "aykırı değer", "Remove the outliers from the data.", "Aykırı değerleri veriden çıkar."],
  ["random sample", "n", "rastgele örneklem", "They surveyed a random sample.", "Rastgele bir örneklemle anket yaptılar."],
  ["statistically significant", "adj", "istatistiksel olarak anlamlı", "The difference was statistically significant.", "Fark istatistiksel olarak anlamlıydı."],
  ["estimate", "n", "tahmin", "At a rough estimate, it'll cost 500 lira.", "Kaba bir tahminle 500 liraya mal olur."],
  ["round up", "pv", "(sayıyı) yukarı yuvarlamak", "Round up the figure to the nearest ten.", "Rakamı en yakın onluğa yuvarla."],
  ["cumulative", "adj", "birikimli, kümülatif", "The cumulative effect of stress is harmful.", "Stresin birikimli etkisi zararlıdır."],

  // Set 69 — The future
  ["futurist", "n", "fütürist", "Futurists predict flying cars.", "Fütüristler uçan arabalar öngörüyor."],
  ["foresee", "v", "önceden görmek", "Nobody foresaw the crisis.", "Krizi kimse önceden görmedi."],
  ["unforeseen", "adj", "öngörülemeyen", "Unforeseen problems delayed the project.", "Öngörülemeyen sorunlar projeyi geciktirdi."],
  ["prospective", "adj", "muhtemel, olası", "Prospective students can visit the campus.", "Aday öğrenciler kampüsü ziyaret edebilir."],
  ["looming", "adj", "yaklaşan (tehdit)", "There's a looming water crisis.", "Yaklaşan bir su krizi var."],
  ["forward-looking", "adj", "ileriye dönük", "The company has a forward-looking strategy.", "Şirketin ileriye dönük bir stratejisi var."],
  ["scenario", "n", "senaryo, olasılık", "In the worst-case scenario, we lose everything.", "En kötü senaryoda her şeyi kaybederiz."],
  ["dystopia", "n", "distopya", "The film shows a future dystopia.", "Film gelecekteki bir distopyayı gösteriyor."],
  ["utopia", "n", "ütopya", "A perfect society is a utopia.", "Kusursuz bir toplum ütopyadır."],
  ["singularity", "n", "tekillik (teknolojik)", "Some fear the technological singularity.", "Bazıları teknolojik tekillikten korkuyor."],
  ["transhumanism", "n", "transhümanizm", "Transhumanism aims to enhance humans.", "Transhümanizm insanı geliştirmeyi amaçlar."],
  ["space colonisation", "n", "uzay kolonizasyonu", "Space colonisation is still science fiction.", "Uzay kolonizasyonu hâlâ bilim kurgu."],
  ["autonomous vehicle", "n", "otonom araç", "Autonomous vehicles are being tested.", "Otonom araçlar test ediliyor."],
  ["obsolescence", "n", "eskime, demode olma", "Many jobs face obsolescence.", "Birçok meslek yok olma tehlikesiyle karşı karşıya."],
  ["long-range", "adj", "uzun vadeli, uzun menzilli", "Long-range forecasts are less accurate.", "Uzun vadeli tahminler daha az isabetlidir."],
  ["uncharted territory", "phr", "keşfedilmemiş alan, bilinmeyen sular", "AI takes us into uncharted territory.", "Yapay zekâ bizi bilinmeyen sulara götürüyor."],
  ["on the horizon", "phr", "ufukta", "Big changes are on the horizon.", "Ufukta büyük değişiklikler var."],
  ["paradigm shift", "n", "paradigma değişimi", "The internet caused a paradigm shift.", "İnternet bir paradigma değişimine yol açtı."],
  ["forecast", "v", "tahmin etmek", "Economists forecast slower growth.", "Ekonomistler daha yavaş büyüme tahmin ediyor."],
  ["speculative", "adj", "spekülatif, varsayıma dayalı", "The report is highly speculative.", "Rapor oldukça varsayıma dayalı."],

  // Set 70 — Innovation
  ["ingenious", "adj", "dâhiyane, yaratıcı", "What an ingenious idea!", "Ne dâhiyane bir fikir!"],
  ["ingenuity", "n", "yaratıcılık, beceriklilik", "The design shows great ingenuity.", "Tasarım büyük bir yaratıcılık gösteriyor."],
  ["pioneer", "n", "öncü", "She was a pioneer of computer science.", "Bilgisayar biliminin öncülerindendi."],
  ["pioneering", "adj", "öncü, çığır açan", "It's a pioneering treatment.", "Öncü bir tedavi."],
  ["groundbreaking", "adj", "çığır açan", "Her research was groundbreaking.", "Araştırması çığır açıcıydı."],
  ["state-of-the-art", "adj", "en son teknoloji", "The hospital has state-of-the-art equipment.", "Hastanenin en son teknoloji ekipmanı var."],
  ["novel", "adj", "yeni, özgün", "They took a novel approach.", "Özgün bir yaklaşım benimsediler."],
  ["inventive", "adj", "yaratıcı, buluşçu", "Children are naturally inventive.", "Çocuklar doğal olarak yaratıcıdır."],
  ["prototype testing", "n", "prototip testi", "Prototype testing revealed problems.", "Prototip testi sorunları ortaya çıkardı."],
  ["research and development", "n", "araştırma-geliştirme (Ar-Ge)", "The company invests in research and development.", "Şirket Ar-Ge'ye yatırım yapıyor."],
  ["patented", "adj", "patentli", "It's a patented design.", "Patentli bir tasarım."],
  ["commercialise", "v", "ticarileştirmek", "They commercialised the invention.", "Buluşu ticarileştirdiler."],
  ["early adopter", "n", "erken benimseyen", "Early adopters bought the first phones.", "İlk telefonları erken benimseyenler aldı."],
  ["iterate", "v", "tekrarlayarak geliştirmek", "We iterate on the design every week.", "Tasarımı her hafta tekrar tekrar geliştiriyoruz."],
  ["reinvent the wheel", "phr", "Amerika'yı yeniden keşfetmek", "Don't reinvent the wheel — use existing tools.", "Amerika'yı yeniden keşfetme, mevcut araçları kullan."],
  ["trial run", "n", "deneme çalışması", "We did a trial run before the launch.", "Lansmandan önce bir deneme çalışması yaptık."],
  ["game-changer", "n", "oyunun kurallarını değiştiren şey", "The smartphone was a game-changer.", "Akıllı telefon oyunun kurallarını değiştirdi."],
  ["brainchild", "n", "(birinin) buluşu, fikri", "The project was the brainchild of two students.", "Proje iki öğrencinin fikriydi."],
  ["spin-off", "n", "yan ürün; yan şirket", "The company is a spin-off from the university.", "Şirket üniversiteden doğan bir yan girişim."],
  ["push the boundaries", "phr", "sınırları zorlamak", "Artists push the boundaries of what's possible.", "Sanatçılar mümkün olanın sınırlarını zorlar."],
];
