import type { LexiconEntry } from "../types";

/** C1 sets 71–75: descriptive writing, light & texture, attitudes, praise & criticism, power. */
export const C1_PART15: LexiconEntry[] = [
  // Set 71 — Descriptive writing
  ["majestic", "adj", "görkemli, heybetli", "Mount Ararat looks majestic at sunrise.", "Ağrı Dağı gün doğumunda görkemli görünüyor."],
  ["verdant", "adj", "yemyeşil", "The valley was verdant after the rain.", "Vadi yağmurdan sonra yemyeşildi."],
  ["undulating", "adj", "dalgalı, inişli çıkışlı", "Undulating hills stretched to the horizon.", "İnişli çıkışlı tepeler ufka kadar uzanıyordu."],
  ["craggy", "adj", "kayalık, sarp", "The craggy coast is dangerous for boats.", "Sarp kıyı tekneler için tehlikeli."],
  ["sheer", "adj", "dik (uçurum); saf", "There's a sheer drop to the sea.", "Denize dimdik bir uçurum var."],
  ["azure", "adj", "gök mavisi", "We swam in the azure waters of Kaş.", "Kaş'ın masmavi sularında yüzdük."],
  ["sun-drenched", "adj", "güneşe boğulmuş", "It's a sun-drenched Aegean village.", "Güneşe boğulmuş bir Ege köyü."],
  ["windswept", "adj", "rüzgârın dövdüğü", "We walked along the windswept beach.", "Rüzgârın dövdüğü sahil boyunca yürüdük."],
  ["mist-shrouded", "adj", "sisle örtülü", "The mist-shrouded mountains looked mysterious.", "Sisle örtülü dağlar gizemli görünüyordu."],
  ["picturesque village", "n", "pitoresk köy", "Şirince is a picturesque village.", "Şirince pitoresk bir köy."],
  ["stretch", "n", "uzanan alan, parça", "It's a beautiful stretch of coastline.", "Güzel bir sahil şeridi."],
  ["expanse", "n", "geniş alan, genişlik", "A vast expanse of desert lay before us.", "Önümüzde uçsuz bucaksız bir çöl uzanıyordu."],
  ["vista", "n", "manzara, görünüm", "The terrace offers stunning vistas.", "Teras muhteşem manzaralar sunuyor."],
  ["nestle", "v", "(bir yere) kurulmak, sokulmak", "The village nestles in the valley.", "Köy vadinin koynuna kurulmuş."],
  ["tower over", "pv", "(üstünde) yükselmek", "The castle towers over the town.", "Kale kasabanın üstünde yükseliyor."],
  ["dotted with", "phr", "…ile noktalanmış, serpiştirilmiş", "The hillside is dotted with olive trees.", "Yamaç zeytin ağaçlarıyla bezeli."],
  ["teeming with", "phr", "…ile kaynayan", "The market was teeming with people.", "Pazar insanla kaynıyordu."],
  ["overgrown", "adj", "otlarla kaplanmış, bakımsız", "The garden was overgrown with weeds.", "Bahçeyi yabani otlar sarmıştı."],
  ["dilapidated", "adj", "harap, yıkık dökük", "They bought a dilapidated old house.", "Harap bir eski ev aldılar."],
  ["awe-inspiring", "adj", "hayranlık uyandıran", "The view from the summit was awe-inspiring.", "Zirvedeki manzara hayranlık uyandırıcıydı."],

  // Set 72 — Light & texture
  ["dazzling", "adj", "göz kamaştırıcı", "The snow was dazzling in the sun.", "Kar güneşte göz kamaştırıcıydı."],
  ["glimmer", "n", "pırıltı; umut ışığı", "There's a glimmer of hope.", "Bir umut ışığı var."],
  ["flicker", "v", "titremek (ışık)", "The candle flickered in the wind.", "Mum rüzgârda titredi."],
  ["glisten", "v", "parıldamak (ıslak yüzey)", "The streets glistened after the rain.", "Yağmurdan sonra sokaklar parıldıyordu."],
  ["shimmer", "v", "pırıldamak, ışıldamak", "The sea shimmered in the moonlight.", "Deniz ay ışığında ışıldıyordu."],
  ["gleam", "v", "parlamak", "His shoes gleamed.", "Ayakkabıları parlıyordu."],
  ["murky", "adj", "bulanık, karanlık", "The water was murky.", "Su bulanıktı."],
  ["luminous", "adj", "parlak, ışıklı", "The watch has a luminous face.", "Saatin ışıklı bir kadranı var."],
  ["translucent", "adj", "yarı saydam", "The curtains are translucent.", "Perdeler yarı saydam."],
  ["opaque", "adj", "opak, ışık geçirmez; anlaşılmaz", "The glass is opaque.", "Cam ışık geçirmiyor."],
  ["hue", "n", "renk tonu", "The sky turned a pink hue.", "Gökyüzü pembe bir tona büründü."],
  ["vivid", "adj", "canlı (renk, anı)", "I have vivid memories of that summer.", "O yaza dair canlı anılarım var."],
  ["muted", "adj", "yumuşak, sönük (renk, ses)", "The room is painted in muted colours.", "Oda yumuşak renklere boyanmış."],
  ["coarse", "adj", "kaba, pürüzlü", "The fabric is coarse.", "Kumaş kaba."],
  ["silky", "adj", "ipeksi", "Her hair is silky.", "Saçları ipeksi."],
  ["brittle", "adj", "kırılgan, gevrek", "Old paper becomes brittle.", "Eski kâğıt kırılganlaşır."],
  ["supple", "adj", "esnek, yumuşak", "The leather is soft and supple.", "Deri yumuşak ve esnek."],
  ["jagged", "adj", "sivri, testere dişli", "Be careful of the jagged rocks.", "Sivri kayalara dikkat et."],
  ["sleek", "adj", "şık ve düzgün, zarif hatlı", "The car has a sleek design.", "Arabanın zarif hatlı bir tasarımı var."],
  ["gnarled", "adj", "boğum boğum, çarpık", "The olive tree has a gnarled trunk.", "Zeytin ağacının boğum boğum bir gövdesi var."],

  // Set 73 — Attitudes
  ["sceptical", "adj", "şüpheci", "I'm sceptical about the plan.", "Plan konusunda şüpheciyim."],
  ["dismissive", "adj", "küçümseyici, umursamaz", "He was dismissive of my ideas.", "Fikirlerimi küçümsedi."],
  ["receptive", "adj", "açık, istekli (fikre)", "The team was receptive to change.", "Ekip değişime açıktı."],
  ["noncommittal", "adj", "net tavır almayan, kaçamak", "She gave a noncommittal answer.", "Kaçamak bir cevap verdi."],
  ["ambivalence", "n", "kararsızlık, iki duygu arasında kalma", "Her ambivalence about the job was clear.", "İşle ilgili kararsızlığı açıktı."],
  ["apathetic", "adj", "ilgisiz, umursamaz", "Young voters are often called apathetic.", "Genç seçmenler çoğu zaman ilgisiz olarak nitelendirilir."],
  ["disdainful", "adj", "küçümseyen", "She gave a disdainful look.", "Küçümseyen bir bakış attı."],
  ["contemptuous", "adj", "hor gören", "He was contemptuous of weakness.", "Zayıflığı hor görürdü."],
  ["indulgent", "adj", "hoşgörülü, müsamahakâr", "My grandmother is very indulgent.", "Büyükannem çok hoşgörülüdür."],
  ["begrudging", "adj", "gönülsüz", "He gave begrudging praise.", "Gönülsüzce övdü."],
  ["wary", "adj", "temkinli, tetikte", "Be wary of strangers online.", "İnternetteki yabancılara karşı temkinli ol."],
  ["resigned", "adj", "kabullenmiş, boyun eğmiş", "He was resigned to losing.", "Kaybetmeyi kabullenmişti."],
  ["defiant", "adj", "meydan okuyan, kafa tutan", "The protesters remained defiant.", "Protestocular kafa tutmaya devam etti."],
  ["conciliatory", "adj", "uzlaştırıcı", "He adopted a conciliatory tone.", "Uzlaştırıcı bir ton benimsedi."],
  ["zealous", "adj", "gayretli, hevesli (aşırı)", "He's a zealous supporter of the club.", "Kulübün gayretli bir destekçisi."],
  ["jaded", "adj", "bıkkın, usanmış", "She's jaded after years in politics.", "Siyasette geçen yıllardan sonra bıkkın."],
  ["optimistic", "adj", "iyimser", "I'm cautiously optimistic.", "Temkinli bir şekilde iyimserim."],
  ["pessimistic", "adj", "kötümser", "He's pessimistic about the economy.", "Ekonomi konusunda kötümser."],
  ["open to persuasion", "phr", "ikna edilmeye açık", "I'm open to persuasion.", "İkna edilmeye açığım."],
  ["set in your ways", "phr", "alışkanlıklarından vazgeçmeyen", "My grandfather is set in his ways.", "Dedem alışkanlıklarından vazgeçmez."],

  // Set 74 — Praise & criticism
  ["commend", "v", "övmek, takdir etmek", "The firefighters were commended for bravery.", "İtfaiyeciler cesaretleri için takdir edildi."],
  ["extol", "v", "göklere çıkarmak", "He extolled the virtues of cycling.", "Bisikletin faydalarını göklere çıkardı."],
  ["acclaim", "v", "övgüyle karşılamak", "The film was acclaimed by critics.", "Film eleştirmenlerce övgüyle karşılandı."],
  ["pay tribute to", "phr", "…e saygı duruşunda bulunmak, övmek", "Colleagues paid tribute to her work.", "Meslektaşları çalışmalarını övdü."],
  ["sing someone's praises", "phr", "birini övüp durmak", "She's always singing his praises.", "Onu sürekli övüp duruyor."],
  ["compliment", "v", "iltifat etmek", "He complimented her on her English.", "İngilizcesi için ona iltifat etti."],
  ["flattery", "n", "dalkavukluk, pohpohlama", "Flattery won't get you anywhere.", "Pohpohlama seni bir yere götürmez."],
  ["condemn", "v", "kınamak", "Leaders condemned the attack.", "Liderler saldırıyı kınadı."],
  ["denounce", "v", "alenen kınamak, ihbar etmek", "He denounced the decision as unfair.", "Kararı haksız diye alenen kınadı."],
  ["censure", "v", "resmi olarak kınamak", "Parliament censured the minister.", "Meclis bakanı resmi olarak kınadı."],
  ["rebuke", "v", "azarlamak, paylamak", "The teacher rebuked the student.", "Öğretmen öğrenciyi azarladı."],
  ["reprimand", "v", "resmi uyarı vermek, kınamak", "He was reprimanded for being late.", "Geç kaldığı için uyarı aldı."],
  ["berate", "v", "fırça atmak", "She berated him for forgetting.", "Unuttuğu için ona fırça attı."],
  ["disparage", "v", "kötülemek, küçümsemek", "Don't disparage other people's work.", "Başkalarının emeğini küçümseme."],
  ["slate", "v", "yerden yere vurmak (eleştiri)", "The play was slated by critics.", "Oyun eleştirmenlerce yerden yere vuruldu."],
  ["nitpick", "v", "kılı kırk yarmak, kusur aramak", "Stop nitpicking about small mistakes.", "Küçük hatalar için kılı kırk yarmayı bırak."],
  ["constructive criticism", "n", "yapıcı eleştiri", "I welcome constructive criticism.", "Yapıcı eleştiriye açığım."],
  ["backhanded compliment", "n", "iğneleyici iltifat", "'You look good for your age' is a backhanded compliment.", "'Yaşına göre iyi görünüyorsun' iğneleyici bir iltifat."],
  ["scathing", "adj", "sert, yakıcı (eleştiri)", "The review was scathing.", "Eleştiri çok sertti."],
  ["glowing", "adj", "övgü dolu", "She got a glowing reference.", "Övgü dolu bir referans aldı."],

  // Set 75 — Power
  ["authority figure", "n", "otorite figürü", "Teachers are authority figures.", "Öğretmenler otorite figürleridir."],
  ["autocratic", "adj", "otokratik, tek adam", "He ran the company in an autocratic way.", "Şirketi tek adam yönetimiyle yönetti."],
  ["dictatorship", "n", "diktatörlük", "The country lived under a dictatorship.", "Ülke bir diktatörlük altında yaşadı."],
  ["tyranny", "n", "zorbalık, tiranlık", "They fought against tyranny.", "Zorbalığa karşı savaştılar."],
  ["oppression", "n", "baskı, zulüm", "The people suffered years of oppression.", "Halk yıllarca baskı gördü."],
  ["subjugate", "v", "boyunduruk altına almak", "The empire subjugated its neighbours.", "İmparatorluk komşularını boyunduruk altına aldı."],
  ["usurp", "v", "gasp etmek (güç, taht)", "He usurped the throne.", "Tahtı gasp etti."],
  ["overthrow", "v", "devirmek", "The army overthrew the government.", "Ordu hükümeti devirdi."],
  ["coup", "n", "darbe", "The coup failed.", "Darbe başarısız oldu."],
  ["hierarchical", "adj", "hiyerarşik", "The army is a hierarchical organisation.", "Ordu hiyerarşik bir kurumdur."],
  ["the establishment", "n", "yerleşik düzen, düzen", "Young people often rebel against the establishment.", "Gençler çoğu zaman yerleşik düzene isyan eder."],
  ["elite", "n", "seçkinler", "A small elite controls the wealth.", "Küçük bir seçkin kesim serveti kontrol ediyor."],
  ["empowerment", "n", "güçlendirme", "Education leads to women's empowerment.", "Eğitim kadınların güçlenmesine yol açar."],
  ["disempower", "v", "gücünü elinden almak", "The new law disempowers local councils.", "Yeni yasa yerel meclislerin gücünü elinden alıyor."],
  ["wield power", "phr", "güç kullanmak", "Tech companies wield enormous power.", "Teknoloji şirketleri muazzam bir güç kullanıyor."],
  ["seize power", "phr", "iktidarı ele geçirmek", "The general seized power in 1980.", "General 1980'de iktidarı ele geçirdi."],
  ["abuse of power", "n", "görevi kötüye kullanma", "The mayor was accused of abuse of power.", "Belediye başkanı görevi kötüye kullanmakla suçlandı."],
  ["power vacuum", "n", "güç boşluğu", "The king's death left a power vacuum.", "Kralın ölümü bir güç boşluğu bıraktı."],
  ["pull strings", "phr", "torpil yaptırmak, ipleri çekmek", "He pulled strings to get the job.", "İşi almak için torpil yaptırdı."],
  ["the powers that be", "phr", "yetkililer, güç sahipleri", "The powers that be have decided.", "Yetkililer karar verdi."],
];
