import type { LexiconEntry } from "../types";

/** C1 sets 36–40: phrasal verbs (talk, situations), advanced verbs, abstract nouns, formal adjectives. */
export const C1_PART8: LexiconEntry[] = [
  // Set 36 — Phrasal verbs: talk & argument
  ["hold forth", "pv", "(bir konuda) uzun uzun konuşmak", "He held forth on politics all evening.", "Bütün akşam siyaset hakkında uzun uzun konuştu."],
  ["butt in", "pv", "(konuşmaya) lafa karışmak", "Sorry to butt in, but you're wrong.", "Lafa karıştığım için kusura bakma ama yanılıyorsun."],
  ["chip in", "pv", "(konuşmaya) katılmak; para katmak", "Everyone chipped in for the gift.", "Hediye için herkes para kattı."],
  ["talk down to", "pv", "tepeden konuşmak", "Don't talk down to me.", "Benimle tepeden konuşma."],
  ["talk someone round", "phr", "birini ikna etmek", "She talked her father round in the end.", "Sonunda babasını ikna etti."],
  ["spell out", "pv", "açık açık anlatmak", "Do I have to spell it out for you?", "Sana açık açık anlatmam mı gerekiyor?"],
  ["drone on", "pv", "tekdüze şekilde uzun uzun konuşmak", "The lecturer droned on for two hours.", "Hoca iki saat boyunca tekdüze şekilde konuştu."],
  ["come out with", "pv", "(beklenmedik şekilde) söylemek", "She came out with a brilliant idea.", "Birden harika bir fikir söyledi."],
  ["fob off", "pv", "(bahaneyle) başından savmak", "Don't let them fob you off with excuses.", "Bahanelerle seni başlarından savmalarına izin verme."],
  ["own up to", "pv", "(hatasını) itiraf etmek", "Nobody owned up to breaking the window.", "Camı kırdığını kimse itiraf etmedi."],
  ["pipe down", "pv", "sesini kesmek, susmak", "Pipe down, the baby's asleep!", "Sesinizi kesin, bebek uyuyor!"],
  ["shout down", "pv", "(bağırarak) susturmak", "The speaker was shouted down.", "Konuşmacı bağrışlarla susturuldu."],
  ["bring up", "pv", "(konuyu) açmak", "Don't bring up money at dinner.", "Yemekte para konusunu açma."],
  ["hammer out", "pv", "(uzun görüşmeyle) anlaşmaya varmak", "They hammered out a deal overnight.", "Bir gecede anlaşmayı çıkardılar."],
  ["thrash out", "pv", "(tartışarak) çözmek", "We need to thrash out the details.", "Ayrıntıları tartışarak çözmemiz gerek."],
  ["back down", "pv", "geri adım atmak", "Neither side will back down.", "İki taraf da geri adım atmayacak."],
  ["hit back", "pv", "karşılık vermek (eleştiriye)", "The minister hit back at his critics.", "Bakan eleştirmenlerine karşılık verdi."],
  ["lash out", "pv", "(sözle) saldırmak, patlamak", "He lashed out at reporters.", "Muhabirlere çıkıştı."],
  ["put across", "pv", "(fikrini) anlatmak, aktarmak", "She put her ideas across clearly.", "Fikirlerini açıkça aktardı."],
  ["tone down", "pv", "yumuşatmak (dil, tavır)", "Can you tone down your language?", "Dilini biraz yumuşatabilir misin?"],

  // Set 37 — Phrasal verbs: situations
  ["blow over", "pv", "(sorun, fırtına) geçip gitmek", "The scandal will soon blow over.", "Skandal yakında geçer gider."],
  ["flare up", "pv", "alevlenmek, tekrar başlamak", "Tensions flared up again.", "Gerginlik yeniden alevlendi."],
  ["peter out", "pv", "yavaş yavaş sönmek, bitmek", "The protest petered out by evening.", "Protesto akşama doğru yavaş yavaş sönümlendi."],
  ["pan out", "pv", "(bir şekilde) gelişmek, sonuçlanmak", "Let's see how things pan out.", "İşlerin nasıl gelişeceğine bakalım."],
  ["drag on", "pv", "uzayıp gitmek", "The meeting dragged on for hours.", "Toplantı saatlerce uzadı."],
  ["spill over", "pv", "yayılmak, sıçramak", "The conflict could spill over into neighbouring countries.", "Çatışma komşu ülkelere sıçrayabilir."],
  ["set off", "pv", "tetiklemek, başlatmak", "The news set off a panic.", "Haber paniği tetikledi."],
  ["play out", "pv", "gerçekleşmek, cereyan etmek", "The drama played out in public.", "Dram herkesin gözü önünde yaşandı."],
  ["unfold", "v", "gelişmek, açığa çıkmak", "We watched events unfold on TV.", "Olayların gelişimini televizyondan izledik."],
  ["snowball", "v", "çığ gibi büyümek", "The problem snowballed quickly.", "Sorun hızla çığ gibi büyüdü."],
  ["loom", "v", "(tehdit) belirmek, yaklaşmak", "Exams are looming.", "Sınavlar kapıda."],
  ["mount", "v", "artmak, birikmek", "Pressure is mounting on the government.", "Hükümet üzerindeki baskı artıyor."],
  ["dwindle", "v", "azalmak, erimek", "Our savings dwindled.", "Birikimlerimiz eridi."],
  ["simmer", "v", "(gerginlik) için için kaynamak", "Anger had been simmering for months.", "Öfke aylardır için için kaynıyordu."],
  ["gather pace", "phr", "hız kazanmak", "The campaign is gathering pace.", "Kampanya hız kazanıyor."],
  ["come to a head", "phr", "doruk noktasına varmak, patlamak", "The crisis came to a head in May.", "Kriz mayısta doruk noktasına ulaştı."],
  ["get out of hand", "phr", "kontrolden çıkmak", "The party got out of hand.", "Parti kontrolden çıktı."],
  ["take its toll", "phr", "yıpratmak, bedelini ödetmek", "Stress is taking its toll on her health.", "Stres sağlığını yıpratıyor."],
  ["hang in the balance", "phr", "belirsizlik içinde olmak, pamuk ipliğine bağlı", "His future hangs in the balance.", "Geleceği pamuk ipliğine bağlı."],
  ["run its course", "phr", "doğal seyrini tamamlamak", "Let the illness run its course.", "Hastalığın doğal seyrini tamamlamasına izin ver."],

  // Set 38 — Advanced verbs
  ["exacerbate", "v", "kötüleştirmek, şiddetlendirmek", "Stress exacerbates the condition.", "Stres rahatsızlığı şiddetlendirir."],
  ["alleviate", "v", "hafifletmek", "The drug alleviates pain.", "İlaç ağrıyı hafifletir."],
  ["circumvent", "v", "atlatmak, etrafından dolaşmak", "They found a way to circumvent the rules.", "Kuralları atlatmanın bir yolunu buldular."],
  ["curtail", "v", "kısıtlamak, azaltmak", "The budget cuts curtailed research.", "Bütçe kesintileri araştırmaları kısıtladı."],
  ["bolster", "v", "desteklemek, güçlendirmek", "The win bolstered the team's confidence.", "Galibiyet takımın özgüvenini güçlendirdi."],
  ["jeopardise", "v", "tehlikeye atmak", "Don't jeopardise your career.", "Kariyerini tehlikeye atma."],
  ["perpetuate", "v", "sürdürmek, kalıcı kılmak", "Films can perpetuate stereotypes.", "Filmler kalıp yargıları sürdürebilir."],
  ["precipitate", "v", "hızlandırmak, tetiklemek", "The scandal precipitated his resignation.", "Skandal istifasını hızlandırdı."],
  ["reiterate", "v", "yinelemek", "Let me reiterate the main point.", "Ana noktayı yineleyeyim."],
  ["relinquish", "v", "bırakmak, vazgeçmek (güç, hak)", "He refused to relinquish control.", "Kontrolü bırakmayı reddetti."],
  ["scrutinise", "v", "dikkatle incelemek", "The auditors scrutinised the accounts.", "Denetçiler hesapları dikkatle inceledi."],
  ["supersede", "v", "yerini almak", "The new law supersedes the old one.", "Yeni yasa eskisinin yerini alıyor."],
  ["underpin", "v", "temel oluşturmak", "Trust underpins every relationship.", "Güven her ilişkinin temelini oluşturur."],
  ["vindicate", "v", "haklı çıkarmak, aklamak", "The results vindicated her decision.", "Sonuçlar kararını haklı çıkardı."],
  ["mitigate risk", "phr", "riski azaltmak", "Insurance helps mitigate risk.", "Sigorta riski azaltmaya yardım eder."],
  ["galvanise", "v", "harekete geçirmek", "The speech galvanised the crowd.", "Konuşma kalabalığı harekete geçirdi."],
  ["exemplify", "v", "örneklemek, örneği olmak", "The building exemplifies modern design.", "Bina modern tasarımın bir örneği."],
  ["encompass", "v", "kapsamak", "The course encompasses all four skills.", "Kurs dört beceriyi de kapsıyor."],
  ["preclude", "v", "önlemek, olanaksız kılmak", "His injury precludes him from playing.", "Sakatlığı oynamasını engelliyor."],
  ["transcend", "v", "aşmak, ötesine geçmek", "Music transcends language.", "Müzik dilin ötesine geçer."],

  // Set 39 — Abstract nouns
  ["ambiguity", "n", "belirsizlik, muğlaklık", "There's some ambiguity in the contract.", "Sözleşmede bazı muğlaklıklar var."],
  ["complacency", "n", "rehavet", "Complacency is dangerous after a win.", "Galibiyetten sonra rehavet tehlikelidir."],
  ["discrepancy", "n", "tutarsızlık, fark", "There's a discrepancy in the figures.", "Rakamlarda bir tutarsızlık var."],
  ["disparity", "n", "eşitsizlik, uçurum", "The disparity between rich and poor is growing.", "Zengin ile yoksul arasındaki uçurum büyüyor."],
  ["ramification", "n", "sonuç, dolaylı etki", "The decision has serious ramifications.", "Kararın ciddi sonuçları var."],
  ["repercussion", "n", "yankı, (olumsuz) sonuç", "The scandal had repercussions for the party.", "Skandalın parti için sonuçları oldu."],
  ["scrutiny", "n", "yakın inceleme", "The plan is under public scrutiny.", "Plan kamuoyunun yakın incelemesi altında."],
  ["impetus", "n", "itici güç", "The crisis gave impetus to reform.", "Kriz reforma itici güç verdi."],
  ["inertia", "n", "atalet, hareketsizlik", "Political inertia delays change.", "Siyasi atalet değişimi geciktiriyor."],
  ["paucity", "n", "kıtlık, azlık", "There is a paucity of reliable data.", "Güvenilir veri kıtlığı var."],
  ["plight", "n", "kötü durum, çile", "The film shows the plight of refugees.", "Film mültecilerin çilesini gösteriyor."],
  ["predicament", "n", "çıkmaz, zor durum", "I'm in a bit of a predicament.", "Biraz zor durumdayım."],
  ["prerequisite", "n", "ön koşul", "A degree is a prerequisite for the job.", "Diploma bu iş için ön koşul."],
  ["proliferation", "n", "hızla çoğalma, yayılma", "The proliferation of apps is amazing.", "Uygulamaların hızla çoğalması şaşırtıcı."],
  ["propensity", "n", "eğilim, yatkınlık", "He has a propensity for exaggeration.", "Abartmaya yatkınlığı var."],
  ["reluctance", "n", "isteksizlik", "She agreed with some reluctance.", "Biraz isteksizce kabul etti."],
  ["resurgence", "n", "yeniden canlanma", "There's been a resurgence of interest in vinyl.", "Plaklara ilgi yeniden canlandı."],
  ["tenacity", "n", "azim, sebat", "Her tenacity is inspiring.", "Azmi ilham verici."],
  ["upheaval", "n", "altüst oluş, çalkantı", "The war caused great upheaval.", "Savaş büyük bir altüst oluşa neden oldu."],
  ["cornerstone", "n", "temel taşı", "Trust is the cornerstone of the business.", "Güven işin temel taşıdır."],

  // Set 40 — Formal adjectives
  ["commendable", "adj", "takdire değer", "Her effort is commendable.", "Çabası takdire değer."],
  ["conducive", "adj", "elverişli, uygun", "The noise isn't conducive to study.", "Gürültü çalışmaya elverişli değil."],
  ["detrimental", "adj", "zararlı", "Smoking is detrimental to health.", "Sigara sağlığa zararlıdır."],
  ["imperative", "adj", "zorunlu, elzem", "It's imperative that we act now.", "Şimdi harekete geçmemiz elzem."],
  ["indispensable", "adj", "vazgeçilmez", "Her help was indispensable.", "Yardımı vazgeçilmezdi."],
  ["inherently", "adv", "doğası gereği", "The job is inherently risky.", "İş doğası gereği riskli."],
  ["intricate", "adj", "karmaşık, girift", "The carpet has an intricate pattern.", "Halının girift bir deseni var."],
  ["lucrative", "adj", "kazançlı, kârlı", "It's a lucrative business.", "Kazançlı bir iş."],
  ["meticulously", "adv", "titizlikle", "The report was meticulously prepared.", "Rapor titizlikle hazırlandı."],
  ["paramount", "adj", "en önemli, üstün", "Safety is paramount.", "Güvenlik her şeyden önemlidir."],
  ["pervasive", "adj", "yaygın, her yere sinmiş", "Corruption is pervasive.", "Yolsuzluk her yere sinmiş durumda."],
  ["prevalent", "adj", "yaygın", "The disease is prevalent in hot climates.", "Hastalık sıcak iklimlerde yaygın."],
  ["salient", "adj", "göze çarpan, önemli", "Summarise the salient points.", "Önemli noktaları özetle."],
  ["tangible", "adj", "somut, elle tutulur", "There are no tangible results yet.", "Henüz somut bir sonuç yok."],
  ["ubiquitous", "adj", "her yerde bulunan", "Smartphones are now ubiquitous.", "Akıllı telefonlar artık her yerde."],
  ["unequivocal", "adj", "kesin, açık", "Her answer was an unequivocal no.", "Cevabı kesin bir hayırdı."],
  ["onerous", "adj", "ağır, külfetli", "The new rules are onerous for small firms.", "Yeni kurallar küçük firmalar için külfetli."],
  ["arduous", "adj", "zahmetli, çetin", "It was an arduous climb.", "Çetin bir tırmanıştı."],
  ["contentious", "adj", "tartışmalı, çekişmeli", "Immigration is a contentious issue.", "Göç tartışmalı bir konu."],
  ["exorbitant", "adj", "fahiş", "The hotel charges exorbitant prices.", "Otel fahiş fiyatlar istiyor."],
];
