import type { LexiconEntry } from "../types";

/** C1 sets 51–55: conflict, crisis response, language & linguistics, time & change, quantity. */
export const C1_PART11: LexiconEntry[] = [
  // Set 51 — Conflict
  ["hostilities", "n", "çatışmalar, düşmanca eylemler", "Hostilities ended in 1945.", "Çatışmalar 1945'te sona erdi."],
  ["skirmish", "n", "çatışma, arbede (küçük)", "There were skirmishes on the border.", "Sınırda küçük çatışmalar yaşandı."],
  ["offensive", "n", "saldırı (askeri)", "The army launched an offensive.", "Ordu bir saldırı başlattı."],
  ["retaliate", "v", "misilleme yapmak", "The country threatened to retaliate.", "Ülke misilleme yapmakla tehdit etti."],
  ["retaliation", "n", "misilleme", "The attack was in retaliation for the bombing.", "Saldırı bombalamaya misillemeydi."],
  ["truce", "n", "ateşkes, mütareke", "The truce lasted only a week.", "Ateşkes sadece bir hafta sürdü."],
  ["armistice", "n", "mütareke", "The Armistice of Mudros was signed in 1918.", "Mondros Mütarekesi 1918'de imzalandı."],
  ["casualties", "n", "kayıplar (ölü ve yaralı)", "There were heavy casualties.", "Ağır kayıplar verildi."],
  ["civilian", "n", "sivil", "Civilians fled the city.", "Siviller şehirden kaçtı."],
  ["atrocity", "n", "vahşet", "The atrocities shocked the world.", "Vahşet dünyayı şoke etti."],
  ["genocide", "n", "soykırım", "The court investigated the genocide.", "Mahkeme soykırımı soruşturdu."],
  ["war crime", "n", "savaş suçu", "He was charged with war crimes.", "Savaş suçlarıyla yargılandı."],
  ["insurgent", "n", "isyancı", "Insurgents attacked the base.", "İsyancılar üsse saldırdı."],
  ["militia", "n", "milis", "Local militias control the area.", "Bölgeyi yerel milisler kontrol ediyor."],
  ["arms race", "n", "silahlanma yarışı", "The Cold War was an arms race.", "Soğuk Savaş bir silahlanma yarışıydı."],
  ["deterrence", "n", "caydırıcılık", "Nuclear deterrence kept the peace.", "Nükleer caydırıcılık barışı korudu."],
  ["occupation", "n", "işgal", "The occupation lasted four years.", "İşgal dört yıl sürdü."],
  ["resistance", "n", "direniş", "The resistance fought for independence.", "Direniş bağımsızlık için savaştı."],
  ["negotiated settlement", "n", "müzakereyle varılan çözüm", "Only a negotiated settlement can end the war.", "Savaşı ancak müzakereyle varılan bir çözüm bitirebilir."],
  ["reconciliation", "n", "barışma, uzlaşma", "The process of reconciliation took decades.", "Uzlaşma süreci onlarca yıl sürdü."],

  // Set 52 — Crisis response
  ["contingency", "n", "olası durum, beklenmedik durum", "We planned for every contingency.", "Her olası durum için plan yaptık."],
  ["disaster relief", "n", "afet yardımı", "Disaster relief arrived within hours.", "Afet yardımı saatler içinde ulaştı."],
  ["search and rescue", "n", "arama kurtarma", "Search and rescue teams worked day and night.", "Arama kurtarma ekipleri gece gündüz çalıştı."],
  ["rubble", "n", "enkaz, moloz", "Survivors were pulled from the rubble.", "Hayatta kalanlar enkazdan çıkarıldı."],
  ["aftershock", "n", "artçı sarsıntı", "Strong aftershocks followed the earthquake.", "Depremi güçlü artçı sarsıntılar izledi."],
  ["makeshift", "adj", "geçici, derme çatma", "They lived in makeshift tents.", "Derme çatma çadırlarda yaşadılar."],
  ["relief effort", "n", "yardım çalışmaları", "Volunteers joined the relief effort.", "Gönüllüler yardım çalışmalarına katıldı."],
  ["death toll", "n", "ölü sayısı", "The death toll has risen.", "Ölü sayısı arttı."],
  ["state of emergency", "n", "olağanüstü hal", "The government declared a state of emergency.", "Hükümet olağanüstü hal ilan etti."],
  ["emergency response", "n", "acil müdahale", "The emergency response was quick.", "Acil müdahale hızlıydı."],
  ["early warning system", "n", "erken uyarı sistemi", "An early warning system saved lives.", "Erken uyarı sistemi hayat kurtardı."],
  ["preparedness", "n", "hazırlıklı olma", "Earthquake preparedness is vital in Turkey.", "Türkiye'de depreme hazırlıklı olmak hayati önemde."],
  ["reconstruction", "n", "yeniden yapılanma", "Reconstruction will take years.", "Yeniden yapılanma yıllar sürecek."],
  ["mobilise", "v", "seferber etmek", "The country mobilised thousands of volunteers.", "Ülke binlerce gönüllüyü seferber etti."],
  ["logistics", "n", "lojistik", "The logistics of delivering aid are complex.", "Yardım dağıtım lojistiği karmaşık."],
  ["stranded", "adj", "mahsur kalmış", "Hundreds of tourists were stranded.", "Yüzlerce turist mahsur kaldı."],
  ["unscathed", "adj", "zarar görmemiş, yara almadan", "The building survived unscathed.", "Bina hasar görmeden ayakta kaldı."],
  ["devastation", "n", "yıkım", "The flood caused widespread devastation.", "Sel geniş çaplı yıkıma yol açtı."],
  ["resilient community", "n", "dayanıklı toplum", "Resilient communities recover faster.", "Dayanıklı toplumlar daha hızlı toparlanır."],
  ["crisis management", "n", "kriz yönetimi", "Good crisis management saves lives.", "İyi kriz yönetimi hayat kurtarır."],

  // Set 53 — Language & linguistics
  ["linguistics", "n", "dilbilim", "She studies linguistics.", "Dilbilim okuyor."],
  ["phonetics", "n", "sesbilgisi", "Phonetics helps with pronunciation.", "Sesbilgisi telaffuza yardımcı olur."],
  ["syntax", "n", "sözdizimi", "English syntax differs from Turkish.", "İngilizce sözdizimi Türkçeden farklı."],
  ["semantics", "n", "anlambilim", "Semantics studies meaning.", "Anlambilim anlamı inceler."],
  ["etymology", "n", "köken bilgisi, etimoloji", "The etymology of 'yoghurt' is Turkish.", "'Yoghurt' kelimesinin kökeni Türkçe."],
  ["idiomatic", "adj", "deyimsel, doğal", "Her English is fluent and idiomatic.", "İngilizcesi akıcı ve doğal."],
  ["colloquial", "adj", "konuşma diline ait", "'Gonna' is colloquial.", "'Gonna' konuşma diline aittir."],
  ["jargon", "n", "jargon, meslek dili", "Avoid technical jargon.", "Teknik jargondan kaçın."],
  ["register", "n", "dil düzeyi, üslup", "Choose the right register for the letter.", "Mektup için doğru üslubu seç."],
  ["lingua franca", "n", "ortak dil", "English is the lingua franca of business.", "İngilizce iş dünyasının ortak dili."],
  ["loanword", "n", "alıntı kelime", "'Kiosk' is a loanword from Turkish.", "'Kiosk' Türkçeden alıntı bir kelime."],
  ["cognate", "n", "kökteş kelime", "'Telefon' and 'telephone' are cognates.", "'Telefon' ve 'telephone' kökteş kelimelerdir."],
  ["false friend", "n", "yanıltıcı benzer kelime", "'Sympathetic' is a false friend for Turkish speakers.", "'Sympathetic' Türkçe konuşanlar için yanıltıcı bir kelime."],
  ["nuance", "n", "nüans, ince fark", "Translation loses some nuance.", "Çeviri bazı nüansları kaybeder."],
  ["inflection", "n", "çekim (dilbilgisi); tonlama", "Turkish uses many inflections.", "Türkçe birçok çekim eki kullanır."],
  ["intonation", "n", "tonlama", "Intonation shows if it's a question.", "Tonlama cümlenin soru olup olmadığını gösterir."],
  ["articulation", "n", "boğumlanma, açık telaffuz", "Clear articulation helps listeners.", "Açık telaffuz dinleyicilere yardım eder."],
  ["fluency", "n", "akıcılık", "Fluency comes with practice.", "Akıcılık pratikle gelir."],
  ["mother-tongue interference", "n", "ana dil etkisi", "Mother-tongue interference causes errors.", "Ana dil etkisi hatalara yol açar."],
  ["polyglot", "n", "çok dilli kişi", "He's a polyglot who speaks seven languages.", "Yedi dil konuşan çok dilli biri."],

  // Set 54 — Time & change
  ["transient", "adj", "geçici, gelip geçici", "Fame is transient.", "Şöhret gelip geçicidir."],
  ["ephemeral", "adj", "kısa ömürlü, uçucu", "Social media trends are ephemeral.", "Sosyal medya trendleri kısa ömürlüdür."],
  ["perennial", "adj", "sürekli, daimi", "Traffic is a perennial problem.", "Trafik daimi bir sorun."],
  ["imminent", "adj", "yakın, eli kulağında", "An announcement is imminent.", "Bir duyuru eli kulağında."],
  ["incremental", "adj", "adım adım, kademeli", "We made incremental improvements.", "Kademeli iyileştirmeler yaptık."],
  ["abrupt", "adj", "ani, beklenmedik", "The meeting came to an abrupt end.", "Toplantı aniden sona erdi."],
  ["protracted", "adj", "uzun süren, uzatılmış", "After protracted negotiations, they agreed.", "Uzun süren müzakerelerden sonra anlaştılar."],
  ["interim", "adj", "geçici, ara", "She was appointed interim director.", "Geçici müdür olarak atandı."],
  ["hitherto", "adv", "şimdiye kadar", "The letters reveal hitherto unknown facts.", "Mektuplar şimdiye kadar bilinmeyen gerçekleri ortaya koyuyor."],
  ["henceforth", "adv", "bundan böyle", "Henceforth, all meetings will be online.", "Bundan böyle tüm toplantılar çevrimiçi olacak."],
  ["at the outset", "phr", "başlangıçta", "At the outset, we had no money.", "Başlangıçta hiç paramız yoktu."],
  ["in the interim", "phr", "bu arada, ara dönemde", "In the interim, please use the old system.", "Bu arada lütfen eski sistemi kullanın."],
  ["in retrospect", "phr", "geriye dönüp bakınca", "In retrospect, it was a mistake.", "Geriye dönüp bakınca hataydı."],
  ["on the verge of", "phr", "…in eşiğinde", "The species is on the verge of extinction.", "Tür yok olmanın eşiğinde."],
  ["the dawn of", "phr", "…in şafağı, başlangıcı", "We are at the dawn of a new era.", "Yeni bir çağın şafağındayız."],
  ["overhaul", "n", "köklü yenileme, revizyon", "The tax system needs an overhaul.", "Vergi sisteminin köklü bir yenilemeye ihtiyacı var."],
  ["metamorphosis", "n", "başkalaşım, dönüşüm", "The city has undergone a metamorphosis.", "Şehir bir dönüşüm geçirdi."],
  ["flux", "n", "sürekli değişim", "The industry is in a state of flux.", "Sektör sürekli değişim halinde."],
  ["stagnation", "n", "durgunluk", "Years of stagnation hurt the economy.", "Yıllarca süren durgunluk ekonomiye zarar verdi."],
  ["revamp", "v", "yenilemek, elden geçirmek", "They revamped the website.", "Web sitesini baştan yenilediler."],

  // Set 55 — Quantity
  ["abundance", "n", "bolluk", "The region has an abundance of fruit.", "Bölgede meyve bolluğu var."],
  ["scarcity", "n", "kıtlık", "Water scarcity is a growing problem.", "Su kıtlığı büyüyen bir sorun."],
  ["surplus", "n", "fazlalık", "There's a surplus of wheat this year.", "Bu yıl buğday fazlası var."],
  ["shortfall", "n", "açık, eksik", "There's a shortfall of 2 million in the budget.", "Bütçede 2 milyonluk açık var."],
  ["a plethora of", "phr", "çok sayıda, bir sürü", "There's a plethora of apps for learning.", "Öğrenme için bir sürü uygulama var."],
  ["a myriad of", "phr", "sayısız", "The city offers a myriad of activities.", "Şehir sayısız etkinlik sunuyor."],
  ["a dearth of", "phr", "…kıtlığı, eksikliği", "There's a dearth of good teachers.", "İyi öğretmen eksikliği var."],
  ["a handful of", "phr", "bir avuç, birkaç", "Only a handful of people came.", "Sadece bir avuç insan geldi."],
  ["the bulk of", "phr", "…in büyük kısmı", "The bulk of the work is done.", "İşin büyük kısmı bitti."],
  ["a fraction", "n", "küçük bir kısım", "Only a fraction of the money was spent.", "Paranın sadece küçük bir kısmı harcandı."],
  ["negligibly", "adv", "önemsiz ölçüde", "Prices rose negligibly.", "Fiyatlar önemsiz ölçüde arttı."],
  ["disproportionate", "adj", "orantısız", "The punishment was disproportionate.", "Ceza orantısızdı."],
  ["commensurate with", "phr", "…ile orantılı", "Salary is commensurate with experience.", "Maaş deneyimle orantılı."],
  ["finite", "adj", "sınırlı, sonlu", "Oil is a finite resource.", "Petrol sınırlı bir kaynaktır."],
  ["infinite", "adj", "sonsuz", "She has infinite patience.", "Sonsuz bir sabrı var."],
  ["copious", "adj", "bol, çok miktarda", "She took copious notes.", "Bol bol not aldı."],
  ["meagre", "adj", "kıt, yetersiz", "They lived on a meagre income.", "Kıt bir gelirle yaşadılar."],
  ["ample", "adj", "bol, yeterinden fazla", "There's ample time to finish.", "Bitirmek için bolca zaman var."],
  ["sparse", "adj", "seyrek", "Vegetation is sparse in the desert.", "Çölde bitki örtüsü seyrek."],
  ["exponential", "adj", "üstel, katlanarak artan", "There's been exponential growth in users.", "Kullanıcılarda katlanarak artış oldu."],
];
