import type { LexiconEntry } from "../types";

/** C1 sets 1–5: character, subtle emotions, social dynamics, rhetoric, thinking. */
export const C1_PART1: LexiconEntry[] = [
  // Set 1 — Character
  ["magnanimous", "adj", "yüce gönüllü", "She was magnanimous in victory.", "Zaferde yüce gönüllü davrandı."],
  ["belligerent", "adj", "kavgacı, saldırgan", "He became belligerent after a few drinks.", "Birkaç kadehten sonra kavgacı oldu."],
  ["complacent", "adj", "rehavete kapılmış, kendinden fazla emin", "We can't afford to be complacent.", "Rehavete kapılmayı göze alamayız."],
  ["diligent", "adj", "çalışkan, özenli", "She's a diligent researcher.", "Özenli bir araştırmacı."],
  ["gregarious", "adj", "sosyal, topluluk seven", "He's gregarious and loves big parties.", "Sosyaldir ve büyük partileri sever."],
  ["obstinate", "adj", "inatçı", "He's too obstinate to admit he's wrong.", "Yanıldığını kabul edemeyecek kadar inatçı."],
  ["pompous", "adj", "kendini beğenmiş, şişirilmiş", "His pompous speech annoyed everyone.", "Şişirilmiş konuşması herkesi rahatsız etti."],
  ["candid", "adj", "açık sözlü, samimi", "She was candid about her mistakes.", "Hataları konusunda açık sözlüydü."],
  ["benevolent", "adj", "iyiliksever", "He was a benevolent employer.", "İyiliksever bir işverendi."],
  ["cynical", "adj", "alaycı, kötümser (insan doğasına dair)", "Years in politics made him cynical.", "Siyasette geçen yıllar onu kötümser yaptı."],
  ["eccentric", "adj", "tuhaf, alışılmadık", "My eccentric uncle collects old clocks.", "Tuhaf amcam eski saatler biriktirir."],
  ["fickle", "adj", "dönek, kararsız", "Fans can be fickle.", "Taraftarlar dönek olabilir."],
  ["meek", "adj", "uysal, yumuşak başlı", "He's too meek to complain.", "Şikâyet edemeyecek kadar uysal."],
  ["pragmatist", "n", "pragmatist, gerçekçi kişi", "She's a pragmatist, not a dreamer.", "O bir hayalperest değil, gerçekçi biri."],
  ["prudent", "adj", "tedbirli, sağduyulu", "It would be prudent to save some money.", "Biraz para biriktirmek sağduyulu olur."],
  ["scrupulous", "adj", "titiz, vicdanlı", "He's scrupulous about paying his taxes.", "Vergilerini ödeme konusunda çok titiz."],
  ["tenacious", "adj", "azimli, yılmaz", "She's a tenacious negotiator.", "Yılmaz bir müzakereci."],
  ["vindictive", "adj", "kinci, intikamcı", "Don't be vindictive — let it go.", "Kinci olma, bırak gitsin."],
  ["aloof", "adj", "mesafeli, soğuk", "He seems aloof, but he's just shy.", "Mesafeli görünüyor ama sadece utangaç."],
  ["affable", "adj", "cana yakın, güler yüzlü", "Our new neighbour is very affable.", "Yeni komşumuz çok cana yakın."],

  // Set 2 — Subtle emotions
  ["ambivalent", "adj", "ikircikli, çelişkili duygular içinde", "I'm ambivalent about moving abroad.", "Yurt dışına taşınma konusunda ikircikliyim."],
  ["disillusioned", "adj", "hayal kırıklığına uğramış, gözü açılmış", "Many voters feel disillusioned.", "Birçok seçmen hayal kırıklığı içinde."],
  ["exasperated", "adj", "bıkmış, çileden çıkmış", "The teacher was exasperated by the noise.", "Öğretmen gürültüden çileden çıkmıştı."],
  ["forlorn", "adj", "kimsesiz, üzgün", "A forlorn dog waited by the door.", "Kimsesiz bir köpek kapının yanında bekliyordu."],
  ["jubilant", "adj", "sevinç içinde, coşkulu", "Jubilant fans filled the streets.", "Coşkulu taraftarlar sokakları doldurdu."],
  ["melancholy", "n", "hüzün, melankoli", "There's a sense of melancholy in his songs.", "Şarkılarında bir hüzün var."],
  ["remorse", "n", "pişmanlık, vicdan azabı", "He showed no remorse for his actions.", "Yaptıklarından dolayı hiç pişmanlık göstermedi."],
  ["trepidation", "n", "tedirginlik, korku", "I opened the letter with trepidation.", "Mektubu tedirginlikle açtım."],
  ["wistful", "adj", "hüzünlü özlem dolu", "She gave a wistful smile.", "Hüzünlü bir özlemle gülümsedi."],
  ["euphoria", "n", "öfori, aşırı mutluluk", "The euphoria of winning didn't last.", "Kazanmanın verdiği aşırı mutluluk uzun sürmedi."],
  ["indignation", "n", "öfke, içerleme (haksızlığa)", "She spoke with indignation about the injustice.", "Haksızlıktan öfkeyle bahsetti."],
  ["apathy", "n", "ilgisizlik, kayıtsızlık", "Voter apathy is a real problem.", "Seçmen kayıtsızlığı gerçek bir sorun."],
  ["angst", "n", "kaygı, bunalım", "The novel captures teenage angst.", "Roman ergen bunalımını yansıtıyor."],
  ["composure", "n", "soğukkanlılık", "She kept her composure under pressure.", "Baskı altında soğukkanlılığını korudu."],
  ["elation", "n", "sevinç, coşku", "There was elation when the results came in.", "Sonuçlar gelince büyük bir sevinç yaşandı."],
  ["pent-up", "adj", "bastırılmış, birikmiş", "He released years of pent-up anger.", "Yıllarca biriken öfkesini boşalttı."],
  ["rattled", "adj", "sarsılmış, tedirgin", "The question clearly rattled him.", "Soru onu açıkça sarstı."],
  ["smug", "adj", "kendini beğenmiş, halinden fazla memnun", "He had a smug look on his face.", "Yüzünde kendini beğenmiş bir ifade vardı."],
  ["crestfallen", "adj", "morali bozuk, yüzü düşmüş", "He looked crestfallen after the defeat.", "Yenilgiden sonra yüzü düşmüştü."],
  ["seethe", "v", "öfkeden köpürmek", "She was seething with anger.", "Öfkeden köpürüyordu."],

  // Set 3 — Social dynamics
  ["camaraderie", "n", "yoldaşlık, dostluk ruhu", "There's great camaraderie in the team.", "Takımda harika bir dostluk ruhu var."],
  ["alienate", "v", "soğutmak, yabancılaştırmak", "His rudeness alienated his friends.", "Kabalığı arkadaşlarını ondan soğuttu."],
  ["ostracise", "v", "dışlamak", "She was ostracised by her classmates.", "Sınıf arkadaşları tarafından dışlandı."],
  ["ingratiate yourself", "phr", "yaranmaya çalışmak", "He tried to ingratiate himself with the boss.", "Patrona yaranmaya çalıştı."],
  ["rapport-building", "n", "ilişki kurma", "Rapport-building is key in sales.", "Satışta ilişki kurmak kilit önemdedir."],
  ["condescending", "adj", "tepeden bakan, küçümseyen", "Don't be so condescending.", "Bu kadar tepeden bakma."],
  ["deferential", "adj", "saygılı, hürmetkâr", "Staff were deferential to the director.", "Personel müdüre karşı hürmetkârdı."],
  ["clique", "n", "klik, kapalı grup", "The school was full of cliques.", "Okul kapalı gruplarla doluydu."],
  ["hierarchy", "n", "hiyerarşi", "The company has a strict hierarchy.", "Şirketin katı bir hiyerarşisi var."],
  ["dynamics", "n", "dinamikler, ilişki düzeni", "The group dynamics changed when she joined.", "O katılınca grup dinamikleri değişti."],
  ["empathise", "v", "empati kurmak", "I can empathise with your frustration.", "Hayal kırıklığınla empati kurabiliyorum."],
  ["solidarity", "n", "dayanışma", "Workers showed solidarity with the strikers.", "İşçiler grevcilerle dayanışma gösterdi."],
  ["ulterior motive", "n", "gizli amaç", "I suspect he has an ulterior motive.", "Gizli bir amacı olduğundan şüpheleniyorum."],
  ["manipulative", "adj", "manipülatif", "She can be very manipulative.", "Çok manipülatif olabilir."],
  ["mediate", "v", "arabuluculuk etmek", "A teacher mediated between the two students.", "Bir öğretmen iki öğrenci arasında arabuluculuk yaptı."],
  ["rift", "n", "(ilişkide) çatlak, ayrılık", "The argument caused a rift in the family.", "Tartışma ailede bir çatlağa neden oldu."],
  ["reciprocate", "v", "karşılık vermek", "He helped me, so I want to reciprocate.", "Bana yardım etti, ben de karşılık vermek istiyorum."],
  ["peer group", "n", "akran grubu", "Teenagers are strongly influenced by their peer group.", "Gençler akran gruplarından güçlü şekilde etkilenir."],
  ["rub someone up the wrong way", "phr", "birinin sinirine dokunmak", "His attitude rubs me up the wrong way.", "Tavrı sinirime dokunuyor."],
  ["on good terms", "phr", "arası iyi", "I'm still on good terms with my ex.", "Eski sevgilimle aram hâlâ iyi."],

  // Set 4 — Rhetoric
  ["rhetoric", "n", "retorik, söz sanatı", "His speech was full of empty rhetoric.", "Konuşması boş retorikle doluydu."],
  ["rhetorical question", "n", "cevap beklenmeyen soru", "It was a rhetorical question.", "Cevap beklenmeyen bir soruydu."],
  ["anecdote", "n", "anekdot, kısa hikâye", "He opened with a funny anecdote.", "Komik bir anekdotla başladı."],
  ["articulate", "v", "açıkça ifade etmek", "She articulated her ideas clearly.", "Fikirlerini açıkça ifade etti."],
  ["assertion", "n", "iddia, savı", "There's no evidence for that assertion.", "O iddiaya dair hiçbir kanıt yok."],
  ["premise", "n", "öncül, varsayım", "The argument is based on a false premise.", "Argüman yanlış bir öncüle dayanıyor."],
  ["fallacy", "n", "safsata, yanılgı", "It's a fallacy that money buys happiness.", "Paranın mutluluk satın aldığı bir yanılgıdır."],
  ["coherent", "adj", "tutarlı", "Write a coherent argument.", "Tutarlı bir argüman yaz."],
  ["cogent", "adj", "ikna edici, sağlam", "She made a cogent case for reform.", "Reform için sağlam bir savunma yaptı."],
  ["polemic", "n", "polemik, sert tartışma yazısı", "The article is a fierce polemic against tourism.", "Makale turizme karşı sert bir polemik."],
  ["emotive", "adj", "duygu uyandıran", "Animal testing is an emotive issue.", "Hayvan deneyleri duygu yüklü bir konu."],
  ["hyperbole", "n", "mübalağa, abartma", "'I've told you a million times' is hyperbole.", "'Sana milyon kere söyledim' bir mübalağadır."],
  ["understatement", "n", "olduğundan hafif anlatma", "'A bit warm' is an understatement — it's 45°C!", "'Biraz sıcak' demek hafif kalır, hava 45 derece!"],
  ["irony", "n", "ironi", "The irony is that he hates flying but became a pilot.", "İronik olan, uçmaktan nefret edip pilot olması."],
  ["sarcasm", "n", "iğneleme, alay", "I couldn't tell if he was using sarcasm.", "Alay mı ettiğini anlayamadım."],
  ["eloquence", "n", "belagat, güzel konuşma", "She spoke with great eloquence.", "Büyük bir belagatle konuştu."],
  ["digression", "n", "konudan sapma", "Excuse the digression.", "Konudan saptığım için kusura bakmayın."],
  ["refutation", "n", "çürütme", "Her reply was a clear refutation of his claims.", "Cevabı iddialarının açık bir çürütmesiydi."],
  ["concede", "v", "kabul etmek (istemeyerek)", "He conceded that she had a point.", "Onun haklı olduğunu kabul etti."],
  ["allude to", "pv", "ima etmek, değinmek", "She alluded to problems in the team.", "Takımdaki sorunlara değindi."],

  // Set 5 — Thinking
  ["contemplate", "v", "enine boyuna düşünmek", "She contemplated leaving her job.", "İşinden ayrılmayı enine boyuna düşündü."],
  ["deliberate", "v", "uzun uzun tartmak, müzakere etmek", "The jury deliberated for two days.", "Jüri iki gün müzakere etti."],
  ["ponder", "v", "üzerine düşünmek", "He pondered the question for a long time.", "Soru üzerine uzun süre düşündü."],
  ["discern", "v", "sezmek, ayırt etmek", "It's hard to discern his true feelings.", "Gerçek duygularını sezmek zor."],
  ["deduce", "v", "sonuç çıkarmak, çıkarsamak", "From the clues, she deduced who the thief was.", "İpuçlarından hırsızın kim olduğunu çıkardı."],
  ["envisage", "v", "öngörmek, tasavvur etmek", "I don't envisage any problems.", "Herhangi bir sorun öngörmüyorum."],
  ["fathom", "v", "(derinliğine) anlamak", "I can't fathom why he did it.", "Neden yaptığını bir türlü anlayamıyorum."],
  ["grapple with", "pv", "boğuşmak, uğraşmak", "Scientists are grappling with the problem.", "Bilim insanları sorunla boğuşuyor."],
  ["preconception", "n", "önyargı, peşin hüküm", "Travel challenges your preconceptions.", "Seyahat peşin hükümlerini sorgulatır."],
  ["insight", "n", "içgörü, kavrayış", "The book gives an insight into village life.", "Kitap köy hayatına dair bir içgörü sunuyor."],
  ["intuitive", "adj", "sezgisel", "The app is very intuitive.", "Uygulama çok sezgisel."],
  ["rationale", "n", "gerekçe, mantık", "What's the rationale behind the decision?", "Kararın arkasındaki gerekçe nedir?"],
  ["hindsight", "n", "sonradan anlama", "In hindsight, I should have studied more.", "Sonradan düşününce daha çok çalışmalıydım."],
  ["foresight", "n", "öngörü, ileri görüşlülük", "She had the foresight to buy early.", "Erken satın alma öngörüsüne sahipti."],
  ["cognition", "n", "biliş", "Sleep affects cognition.", "Uyku bilişi etkiler."],
  ["train of thought", "phr", "düşünce silsilesi", "Sorry, I've lost my train of thought.", "Pardon, düşüncemin ipini kaçırdım."],
  ["second-guess", "v", "(kararı) sürekli sorgulamak", "Stop second-guessing yourself.", "Kendini sürekli sorgulamayı bırak."],
  ["overthink", "v", "fazla düşünmek, kafaya takmak", "Don't overthink it.", "Bunu fazla kafana takma."],
  ["lateral thinking", "n", "yanal düşünme, yaratıcı çözüm", "The puzzle requires lateral thinking.", "Bulmaca yaratıcı düşünme gerektiriyor."],
  ["come to terms with", "phr", "kabullenmek", "She has come to terms with her illness.", "Hastalığını kabullendi."],
];
