import Link from "next/link";
import { ArrowRight, ArrowUpRight, BookOpenCheck, Check, Gauge, Sparkles } from "lucide-react";
import type { ExamLandingContent } from "@/lib/exam-landing";
import type { ExamFamily } from "@/lib/generated/prisma/enums";
import { ExamSectionMenu } from "@/components/exams/ExamSectionMenu";
import { examResourcesHref } from "@/lib/platform";
import { getAuthContext } from "@/server/auth/context";
import { listTopicsForActiveExamGoal, syncStudyGoalStatuses } from "@/server/services/study-goals.service";
import { StudyGoalDialog } from "@/components/dashboard/StudyGoalDialog";

// Matches lib/exam-landing.ts's sharedSteps order (every exam entry, including the YÖKDİL
// branch() helper, uses that same fixed 4-item list) - index 0 jumps to the exam-overview
// section below, the rest deep-link to the matching dashboard tool.
const STEP_HREFS = ["#sinavini-tani", "/seviye-tespit", "/dashboard/practice", "/dashboard/progress"];

export async function ExamShowcase({ name, slug, content, speakingHref, examFamily, children }: { name: string; slug: string; content: ExamLandingContent; speakingHref?: string; examFamily?: ExamFamily; children?: React.ReactNode }) {
  const user = await getAuthContext();
  const topics = user ? await listTopicsForActiveExamGoal(user.id) : [];
  if (user) await syncStudyGoalStatuses(user.id);
  return <div className="lg:grid lg:grid-cols-[260px_minmax(0,1fr)]"><ExamSectionMenu examName={name} slug={slug} speakingHref={speakingHref} examFamily={examFamily} /><main className="min-w-0 bg-white">
    <section className="relative overflow-hidden border-b border-slate-200 bg-[#071b34] text-white">
      <div className="absolute inset-0 opacity-30" style={{ background: `radial-gradient(circle at 75% 35%, ${content.accent}, transparent 34%)` }} />
      <div className="relative mx-auto grid w-full max-w-[1320px] gap-10 px-4 py-16 sm:px-6 lg:grid-cols-[1.05fr_.95fr] lg:px-8 lg:py-24">
        <div><span className="inline-flex rounded-full border border-white/20 bg-white/10 px-4 py-2 text-xs font-extrabold uppercase tracking-[.15em] text-blue-100">{content.badge}</span><h1 className="mt-6 max-w-3xl text-4xl font-black leading-[1.05] tracking-[-.045em] sm:text-6xl">{content.headline}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300">{content.description}</p><div className="mt-8 flex flex-wrap gap-3"><Link href={`/packages?exam=${slug}`} className="primary-button">Hazırlığa başla <ArrowRight size={18} /></Link><Link href={`/konu-anlatim?exam=${slug}`} className="inline-flex items-center justify-center rounded-xl border border-white/30 px-4 py-2 text-sm font-bold text-white transition hover:bg-white/10">Konu anlatımlarını gör</Link><Link href={examResourcesHref(slug)} className="inline-flex items-center justify-center rounded-xl border border-white/30 px-4 py-2 text-sm font-bold text-white transition hover:bg-white/10">{name} Kaynakları</Link></div></div>
        <div className="self-end rounded-[1.75rem] border border-white/15 bg-white/10 p-5 shadow-2xl backdrop-blur sm:p-7"><div className="flex items-center justify-between"><div><p className="text-xs font-extrabold uppercase tracking-widest text-blue-200">Nasıl çalışır?</p><p className="mt-2 text-2xl font-black">4 Adımda Hazırlık</p><p className="mt-1 text-[11px] font-bold uppercase tracking-wide text-blue-300">Detaylar için tıklayın ↗</p></div><span className="grid size-12 place-items-center rounded-2xl" style={{ background: content.accent }}><Gauge /></span></div><div className="mt-6 grid grid-cols-2 gap-3">{content.steps.map((step, index) => <Link key={step.title} href={STEP_HREFS[index] ?? "#"} className="group relative rounded-2xl bg-white/10 p-4 transition hover:bg-white/20"><ArrowUpRight size={14} className="absolute right-3 top-3 text-blue-300 opacity-70 transition group-hover:opacity-100" /><p className="pr-4 text-lg font-black leading-tight">{step.title}</p><p className="mt-1 text-xs font-semibold text-slate-300">{step.description}</p></Link>)}</div>{user ? <StudyGoalDialog topics={topics} triggerClassName="mt-5 flex w-full items-center gap-3 rounded-2xl bg-white p-4 text-left text-[#071b34] transition hover:bg-blue-50" /> : <Link href={`/sign-in?next=${encodeURIComponent(`/exams/${slug}`)}`} className="mt-5 flex items-center gap-3 rounded-2xl bg-white p-4 text-[#071b34] transition hover:bg-blue-50"><Gauge className="text-[color:var(--accent)]" /><div><p className="text-sm font-black">Bugünkü hedeflerini belirle</p><p className="text-xs text-slate-500">Giriş yapıp konu, pratik veya deneme hedefi ekle</p></div></Link>}</div>
      </div>
    </section>

    {speakingHref ? <section className="mx-auto w-full max-w-[1320px] px-4 py-16 sm:px-6 lg:px-8"><div className="rounded-3xl border border-slate-200 bg-slate-50 p-6 sm:flex sm:items-center sm:justify-between"><div className="flex items-start gap-4"><span className="grid size-12 shrink-0 place-items-center rounded-2xl text-white" style={{ background: content.accent }}><Sparkles /></span><div><h3 className="text-xl font-black">Tarayıcıdan Speaking pratiği</h3><p className="mt-1 text-sm leading-6 text-slate-600">Mikrofonla yanıt verin, kaydınızı dinleyin ve anlık akıcılık göstergelerini görün.</p></div></div><Link href={speakingHref} className="primary-button mt-5 shrink-0 sm:mt-0">Speaking’e geç <ArrowRight size={18} /></Link></div></section> : null}

    <section id="sinavini-tani" className="scroll-mt-24 bg-slate-50"><div className="mx-auto w-full max-w-[1320px] px-4 py-16 sm:px-6 lg:px-8"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">Sınavını tanı</p><h2 className="mt-2 text-3xl font-black tracking-tight">{name}</h2><p className="mt-4 leading-7 text-slate-600">{content.description}</p><div className="mt-6 flex gap-3"><span className="flex items-center gap-2 rounded-full bg-white px-4 py-2 text-sm font-bold shadow-sm"><Check size={17} className="text-emerald-600" /> Sınava özel</span><span className="flex items-center gap-2 rounded-full bg-white px-4 py-2 text-sm font-bold shadow-sm"><Check size={17} className="text-emerald-600" /> Kendi hızınızda</span></div></div><ol className="grid grid-cols-2 gap-3 sm:grid-cols-4">{content.stats.map((stat, index) => <li key={stat.label} className="rounded-2xl border border-slate-200 bg-white p-3 text-center"><span className="text-xs font-black" style={{ color: content.accent }}>0{index + 1}</span><h3 className="mt-1 text-lg font-black">{stat.value}</h3><p className="mt-0.5 text-xs leading-tight text-slate-600">{stat.label}</p></li>)}</ol></div></div></section>

    {children}
    <section className="mx-auto w-full max-w-[1320px] px-4 pb-20 sm:px-6 lg:px-8"><div className="overflow-hidden rounded-[2rem] bg-[#071b34] p-8 text-white sm:p-12"><div className="grid items-center gap-6 lg:grid-cols-[1fr_auto]"><div><div className="flex items-center gap-2 text-blue-200"><BookOpenCheck size={20} /><span className="text-xs font-extrabold uppercase tracking-widest">Cannice English</span></div><h2 className="mt-3 text-3xl font-black">{name} hazırlığını bugün başlatın.</h2><p className="mt-3 max-w-2xl leading-7 text-slate-300">Sınavınıza ayrılmış konu anlatımlarını, kaynakları ve çalışma seçeneklerini inceleyin.</p></div><Link href={`/packages?exam=${slug}`} className="primary-button bg-white text-[#071b34] hover:bg-blue-50">Çalışma seçenekleri <ArrowRight size={18} /></Link></div></div></section>
  </main></div>;
}
