import type { DiagnosticQuestionSeed } from "../diagnostic-questions";

// YÖKDİL SAĞLIK BİLİMLERİ — fixed mock exams ("Deneme 1" – "Deneme 5").
// Each Deneme = 20 questions: 8 kelime-bilgisi (MCQ) + 4 ceviri-en-tr + 4 ceviri-tr-en + 4 okuma
// (one shared passage per Deneme, repeated across its 4 reading questions).
// All content is original and health/medical-sciences domain (cardiology, pharmacology,
// epidemiology, nursing, genetics, oncology, neurology, respiratory medicine, mental health,
// emergency medicine, and medical ethics), distinguishing it from YDS and the other YÖKDİL branches.

export const MOCK_YOKDIL_SAGLIK: DiagnosticQuestionSeed[] = [
  // ============================================================
  // DENEME 1 — Cardiology & Public Health
  // ============================================================
  // --- Kelime Bilgisi (8) ---
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "kelime-bilgisi",
    questionType: "MCQ",
    difficulty: "KOLAY",
    prompt:
      "Patients with high blood pressure are advised to ---- their salt intake to protect their cardiovascular health.",
    options: ["reduce", "increase", "ignore", "measure"],
    correctIndex: 0,
    explanation:
      "Yüksek tansiyon hastalarına tuz alımını azaltmaları önerilir; 'increase' anlamca ters, 'ignore/measure' bağlamla uyuşmaz.",
    tags: ["saglik-vocab"],
    mockSetNumber: 1,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "kelime-bilgisi",
    questionType: "MCQ",
    difficulty: "KOLAY",
    prompt: "The nurse checked the patient's ---- to see how fast the heart was beating.",
    options: ["pulse", "posture", "appetite", "reflex"],
    correctIndex: 0,
    explanation:
      "Kalbin atış hızını ölçmek için nabız ('pulse') kontrol edilir; diğer seçenekler kalp atışıyla ilgili değildir.",
    tags: ["saglik-vocab"],
    mockSetNumber: 1,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "kelime-bilgisi",
    questionType: "MCQ",
    difficulty: "ORTA",
    prompt:
      "The cardiologist explained that a diet high in saturated fat can cause fatty deposits to ---- in the arteries.",
    options: ["accumulate", "evaporate", "circulate", "dissolve"],
    correctIndex: 0,
    explanation:
      "Yağlı birikintilerin damarlarda 'birikmesi' 'accumulate' ile ifade edilir; 'circulate' dolaşmak anlamındadır ve birikimi değil hareketi ifade eder, 'evaporate/dissolve' bağlamla uyuşmaz.",
    tags: ["saglik-vocab"],
    mockSetNumber: 1,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "kelime-bilgisi",
    questionType: "MCQ",
    difficulty: "ORTA",
    prompt:
      "Despite the medication, his blood pressure remained ----, refusing to drop to a safe level.",
    options: ["elevated", "diminished", "regulated", "balanced"],
    correctIndex: 0,
    explanation:
      "'Refusing to drop' ifadesi tansiyonun hâlâ yüksek ('elevated') olduğunu gösterir; diğer seçenekler düşük/dengeli bir durumu ima eder ve cümleyle çelişir.",
    tags: ["saglik-vocab"],
    mockSetNumber: 1,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "kelime-bilgisi",
    questionType: "MCQ",
    difficulty: "ORTA",
    prompt: "A sedentary lifestyle is a significant ---- factor for coronary heart disease.",
    options: ["risk", "safety", "recovery", "immune"],
    correctIndex: 0,
    explanation:
      "'Risk factor' (risk faktörü) hastalık olasılığını artıran unsurlar için kullanılan standart tıbbi terimdir.",
    tags: ["saglik-vocab"],
    mockSetNumber: 1,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "kelime-bilgisi",
    questionType: "MCQ",
    difficulty: "ZOR",
    prompt:
      "The patient's condition began to ---- rapidly after the second heart attack, requiring immediate transfer to intensive care.",
    options: ["deteriorate", "recuperate", "stabilize", "flourish"],
    correctIndex: 0,
    explanation:
      "Yoğun bakıma acil nakil gerekmesi durumun kötüleştiğini gösterir; 'deteriorate' (kötüleşmek) doğrudur, diğerleri iyileşme/istikrar anlamı taşır.",
    tags: ["saglik-vocab"],
    mockSetNumber: 1,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "kelime-bilgisi",
    questionType: "MCQ",
    difficulty: "ZOR",
    prompt:
      "Because the two drugs interact badly, prescribing them together is ---- for patients with heart conditions.",
    options: ["contraindicated", "recommended", "subsidized", "customary"],
    correctIndex: 0,
    explanation:
      "İki ilacın kötü etkileşimi nedeniyle birlikte reçetelenmesi tıbben sakıncalıdır; bu 'contraindicated' (kontrendike) ile ifade edilir.",
    tags: ["saglik-vocab"],
    mockSetNumber: 1,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "kelime-bilgisi",
    questionType: "MCQ",
    difficulty: "KOLAY",
    prompt: "Public health officials launched a campaign to ---- awareness about the dangers of smoking.",
    options: ["raise", "lower", "hide", "waste"],
    correctIndex: 0,
    explanation:
      "'Raise awareness' (farkındalık yaratmak) standart bir kalıptır; diğer fiiller bu isimle birlikte kullanılmaz.",
    tags: ["saglik-vocab"],
    mockSetNumber: 1,
  },
  // --- Çeviri (EN → TR) (4) ---
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "ceviri-en-tr",
    questionType: "TRANSLATION_EN_TR",
    difficulty: "KOLAY",
    prompt: "High cholesterol levels can increase the risk of heart disease.",
    options: [
      "Yüksek kolesterol seviyeleri kalp hastalığı riskini artırabilir.",
      "Düşük kolesterol seviyeleri kalp hastalığı riskini azaltabilir.",
      "Yüksek kolesterol seviyeleri kalp hastalığını tamamen önler.",
      "Kalp hastalığı kolesterol seviyelerini artırabilir.",
    ],
    correctIndex: 0,
    explanation:
      "Cümle 'yüksek kolesterolün kalp hastalığı riskini artırabileceğini' söyler; A bunu birebir doğru yansıtır. B ters anlam, C 'önler' diyerek anlamı tersine çevirir, D özne-nesne ilişkisini tersine çevirir.",
    tags: ["saglik-ceviri"],
    mockSetNumber: 1,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "ceviri-en-tr",
    questionType: "TRANSLATION_EN_TR",
    difficulty: "ORTA",
    prompt: "Doctors recommend that patients with hypertension monitor their blood pressure daily.",
    options: [
      "Doktorlar, hipertansiyon hastalarının tansiyonlarını günlük olarak izlemelerini önerir.",
      "Doktorlar, hipertansiyon hastalarının tansiyonlarını haftalık olarak izlemelerini önerir.",
      "Hastalar, doktorların tansiyonlarını günlük olarak izlemelerini önerir.",
      "Doktorlar, hipertansiyon hastalarının tansiyonlarını günlük olarak izlemelerini yasakladı.",
    ],
    correctIndex: 0,
    explanation:
      "'Daily' ifadesi 'günlük' anlamına gelir ve cümle doktorların tavsiyesini anlatır; B yanlış zaman aralığı, C özneleri karıştırıyor, D 'recommend' yerine yasaklama anlamı katıyor.",
    tags: ["saglik-ceviri"],
    mockSetNumber: 1,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "ceviri-en-tr",
    questionType: "TRANSLATION_EN_TR",
    difficulty: "ORTA",
    prompt: "The clinical trial was designed to evaluate the drug's effectiveness in lowering blood pressure.",
    options: [
      "Klinik deneme, ilacın tansiyonu düşürmedeki etkinliğini değerlendirmek için tasarlandı.",
      "Klinik deneme, ilacın tansiyonu yükseltmedeki etkinliğini değerlendirmek için tasarlandı.",
      "Klinik deneme, ilacın yan etkilerini değerlendirmek için tasarlandı.",
      "İlaç, klinik denemenin etkinliğini değerlendirmek için tasarlandı.",
    ],
    correctIndex: 0,
    explanation:
      "Cümle ilacın 'tansiyonu düşürmedeki etkinliğini' değerlendirmek üzere tasarlandığını belirtir; B ters anlam, C farklı bir konu (yan etkiler), D özne-nesne ilişkisini tersine çeviriyor.",
    tags: ["saglik-ceviri"],
    mockSetNumber: 1,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "ceviri-en-tr",
    secondaryTopicSlugs: ["kosul-cumleleri"],
    questionType: "TRANSLATION_EN_TR",
    difficulty: "ZOR",
    prompt: "Had the outbreak been detected earlier, far fewer patients would have required hospitalization.",
    options: [
      "Salgın daha erken tespit edilseydi, çok daha az hasta hastaneye yatırılmak zorunda kalırdı.",
      "Salgın daha erken tespit edildi ve çok daha az hasta hastaneye yatırıldı.",
      "Salgın erken tespit edilmezse, daha fazla hasta hastaneye yatırılacak.",
      "Salgın daha erken tespit edilmeliydi çünkü çok hasta hastaneye yatırıldı.",
    ],
    correctIndex: 0,
    explanation:
      "Cümle 3. tip koşul yapısıyla (Had + PP, would have + PP) geçmişte gerçekleşmemiş bir durumu anlatır; A bu gerçekleşmemişlik anlamını doğru aktarır. B gerçek geçmiş zaman kullanıyor, C farklı bir koşul zamanı, D farklı bir anlam (öneri) katıyor.",
    tags: ["saglik-ceviri"],
    mockSetNumber: 1,
  },
  // --- Çeviri (TR → EN) (4) ---
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "ceviri-tr-en",
    questionType: "TRANSLATION_TR_EN",
    difficulty: "KOLAY",
    prompt: "Hasta, ameliyattan sonra hızla iyileşti.",
    options: [
      "The patient recovered quickly after the surgery.",
      "The patient recovered slowly after the surgery.",
      "The patient will recover quickly after the surgery.",
      "The patient was recovering quickly before the surgery.",
    ],
    correctIndex: 0,
    explanation:
      "Türkçe cümle geçmiş zamanda ve 'hızla' iyileşmeyi anlatır; A bunu doğru zaman ve zarfla yansıtır. B zıt anlam, C yanlış zaman, D yanlış zaman ilişkisi (ameliyattan önce) içerir.",
    tags: ["saglik-ceviri"],
    mockSetNumber: 1,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "ceviri-tr-en",
    questionType: "TRANSLATION_TR_EN",
    difficulty: "ORTA",
    prompt: "Kalp krizi geçiren hastaların çoğu, düzenli egzersiz yaparak iyileşme sürecini hızlandırabilir.",
    options: [
      "Most patients who have had a heart attack can speed up their recovery process by exercising regularly.",
      "Most patients who have had a heart attack can slow down their recovery process by exercising regularly.",
      "Most patients who will have a heart attack can speed up their recovery process by exercising regularly.",
      "A few patients who have had a heart attack can speed up their recovery process by exercising regularly.",
    ],
    correctIndex: 0,
    explanation:
      "'Çoğu' → 'most', 'hızlandırabilir' → 'can speed up' doğru şekilde A'da yer alır; B ters anlam, C yanlış zaman (gelecek), D 'çoğu' yerine 'a few' kullanarak niceliği yanlış yansıtıyor.",
    tags: ["saglik-ceviri"],
    mockSetNumber: 1,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "ceviri-tr-en",
    questionType: "TRANSLATION_TR_EN",
    difficulty: "ORTA",
    prompt: "Bağışıklık sistemi zayıf olan bireyler, enfeksiyonlara karşı daha savunmasızdır.",
    options: [
      "Individuals with a weak immune system are more vulnerable to infections.",
      "Individuals with a strong immune system are more vulnerable to infections.",
      "Individuals with a weak immune system are less vulnerable to infections.",
      "Individuals with a weak immune system are more vulnerable to diseases they already have.",
    ],
    correctIndex: 0,
    explanation:
      "'Zayıf bağışıklık sistemi' → 'weak immune system', 'daha savunmasız' → 'more vulnerable' A'da doğru eşleşir; B 'strong' ile zıtlaştırıyor, C 'less' ile anlamı tersine çeviriyor, D anlamı daraltıp değiştiriyor.",
    tags: ["saglik-ceviri"],
    mockSetNumber: 1,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "ceviri-tr-en",
    secondaryTopicSlugs: ["kosul-cumleleri"],
    questionType: "TRANSLATION_TR_EN",
    difficulty: "ZOR",
    prompt:
      "Doktorlar, hastalık erken teşhis edilmeseydi bu kadar ilerlemiş olacağını belirtti.",
    options: [
      "Doctors stated that if the disease had not been diagnosed early, it would have progressed this much.",
      "Doctors stated that if the disease had not been diagnosed early, it would not have progressed this much.",
      "Doctors stated that if the disease is not diagnosed early, it will progress this much.",
      "Doctors stated that the disease was diagnosed early and progressed this much.",
    ],
    correctIndex: 0,
    explanation:
      "Türkçe cümle 3. tip koşulla ('teşhis edilmeseydi... ilerlemiş olacağını') geçmişte gerçekleşmemiş bir varsayımı anlatır: erken teşhis konulduğu için hastalık bu kadar ilerlememiştir. A bu anlamı doğru aktarır. B olumsuzluğu yanlış yere ekleyerek anlamı tersine çeviriyor, C gerçek (type 1) koşula dönüştürüyor, D koşulu tamamen kaldırıp olguyu değiştiriyor.",
    tags: ["saglik-ceviri"],
    mockSetNumber: 1,
  },
  // --- Okuma (4) ---
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "okuma",
    questionType: "READING_COMPREHENSION",
    difficulty: "KOLAY",
    passageText:
      "Cardiovascular disease remains one of the leading causes of death worldwide, but research shows that a large proportion of cases are preventable. Risk factors such as high blood pressure, elevated cholesterol, smoking, and physical inactivity contribute significantly to the development of heart disease. Public health experts emphasize that lifestyle modifications, including regular exercise, a balanced diet low in saturated fat, and smoking cessation, can substantially lower an individual's risk. In addition, routine screening allows early detection of risk factors before they progress into serious complications, enabling doctors to intervene with medication or lifestyle counseling long before a cardiac event occurs.",
    prompt: "Parçaya göre, kalp-damar hastalıklarının önemli bir kısmı nasıl tanımlanmaktadır?",
    options: ["Önlenebilir olarak", "Tedavi edilemez olarak", "Nadir görülen olarak", "Sadece genetik olarak"],
    correctIndex: 0,
    explanation:
      "Parçanın ikinci cümlesinde vakaların büyük bir kısmının 'preventable' (önlenebilir) olduğu belirtilmiştir.",
    tags: ["saglik-reading"],
    mockSetNumber: 1,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "okuma",
    questionType: "READING_COMPREHENSION",
    difficulty: "ORTA",
    passageText:
      "Cardiovascular disease remains one of the leading causes of death worldwide, but research shows that a large proportion of cases are preventable. Risk factors such as high blood pressure, elevated cholesterol, smoking, and physical inactivity contribute significantly to the development of heart disease. Public health experts emphasize that lifestyle modifications, including regular exercise, a balanced diet low in saturated fat, and smoking cessation, can substantially lower an individual's risk. In addition, routine screening allows early detection of risk factors before they progress into serious complications, enabling doctors to intervene with medication or lifestyle counseling long before a cardiac event occurs.",
    prompt: "Parçada kalp hastalığı riskini artıran faktörler arasında aşağıdakilerden hangisi SAYILMAMIŞTIR?",
    options: ["Düzenli uyku eksikliği", "Yüksek tansiyon", "Sigara kullanımı", "Fiziksel hareketsizlik"],
    correctIndex: 0,
    explanation:
      "Parçada risk faktörleri olarak 'high blood pressure, elevated cholesterol, smoking, and physical inactivity' sayılmıştır; uyku eksikliğinden hiç bahsedilmemiştir.",
    tags: ["saglik-reading"],
    mockSetNumber: 1,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "okuma",
    questionType: "READING_COMPREHENSION",
    difficulty: "ORTA",
    passageText:
      "Cardiovascular disease remains one of the leading causes of death worldwide, but research shows that a large proportion of cases are preventable. Risk factors such as high blood pressure, elevated cholesterol, smoking, and physical inactivity contribute significantly to the development of heart disease. Public health experts emphasize that lifestyle modifications, including regular exercise, a balanced diet low in saturated fat, and smoking cessation, can substantially lower an individual's risk. In addition, routine screening allows early detection of risk factors before they progress into serious complications, enabling doctors to intervene with medication or lifestyle counseling long before a cardiac event occurs.",
    prompt: "Parçaya göre, düzenli tarama (screening) hangi açıdan faydalıdır?",
    options: [
      "Risk faktörlerinin ciddi komplikasyonlara dönüşmeden önce tespit edilmesini sağlar",
      "Hastalığı tamamen ortadan kaldırır",
      "Sadece ameliyat sonrası hastalarda uygulanır",
      "İlaç kullanımını tamamen gereksiz kılar",
    ],
    correctIndex: 0,
    explanation:
      "Parçada taramanın 'risk faktörlerinin ciddi komplikasyonlara ilerlemeden önce erken tespit edilmesini sağladığı' belirtilmiştir.",
    tags: ["saglik-reading"],
    mockSetNumber: 1,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "okuma",
    questionType: "READING_COMPREHENSION",
    difficulty: "ZOR",
    passageText:
      "Cardiovascular disease remains one of the leading causes of death worldwide, but research shows that a large proportion of cases are preventable. Risk factors such as high blood pressure, elevated cholesterol, smoking, and physical inactivity contribute significantly to the development of heart disease. Public health experts emphasize that lifestyle modifications, including regular exercise, a balanced diet low in saturated fat, and smoking cessation, can substantially lower an individual's risk. In addition, routine screening allows early detection of risk factors before they progress into serious complications, enabling doctors to intervene with medication or lifestyle counseling long before a cardiac event occurs.",
    prompt: "Parçanın son cümlesine göre, erken tespitin doktorlara sağladığı avantaj nedir?",
    options: [
      "Kalple ilgili bir olay gerçekleşmeden çok önce ilaç veya yaşam tarzı danışmanlığıyla müdahale edebilme",
      "Hastaları doğrudan ameliyata yönlendirme zorunluluğu",
      "Tüm hastalara aynı tedaviyi uygulama",
      "Taramaların tamamen ortadan kaldırılması",
    ],
    correctIndex: 0,
    explanation:
      "Son cümlede erken tespitin doktorlara 'kalple ilgili bir olay gerçekleşmeden çok önce ilaç ya da yaşam tarzı danışmanlığıyla müdahale etme' imkânı sağladığı belirtilir.",
    tags: ["saglik-reading"],
    mockSetNumber: 1,
  },

  // ============================================================
  // DENEME 2 — Pharmacology & Epidemiology
  // ============================================================
  // --- Kelime Bilgisi (8) ---
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "kelime-bilgisi",
    questionType: "MCQ",
    difficulty: "KOLAY",
    prompt: "The pharmacist advised the patient to take the medication with food to avoid stomach ----.",
    options: ["upset", "surgery", "immunity", "diagnosis"],
    correctIndex: 0,
    explanation:
      "İlacın yemekle alınması mide 'rahatsızlığını' (upset) önlemek içindir; diğer seçenekler bağlamla uyuşmaz.",
    tags: ["saglik-vocab"],
    mockSetNumber: 2,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "kelime-bilgisi",
    questionType: "MCQ",
    difficulty: "KOLAY",
    prompt:
      "It is important to follow the prescribed ---- exactly; taking too much or too little can be dangerous.",
    options: ["dosage", "diagnosis", "symptom", "allergy"],
    correctIndex: 0,
    explanation:
      "'Dosage' (doz) 'çok fazla ya da çok az almak' ifadesiyle doğrudan ilişkilidir; diğer kelimeler doz kavramını karşılamaz.",
    tags: ["saglik-vocab"],
    mockSetNumber: 2,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "kelime-bilgisi",
    questionType: "MCQ",
    difficulty: "ORTA",
    prompt: "Common ---- of the new painkiller include drowsiness, nausea, and mild headaches.",
    options: ["side effects", "prescriptions", "diagnoses", "immunities"],
    correctIndex: 0,
    explanation:
      "Bir ilacın uyku hali, bulantı gibi istenmeyen etkileri 'side effects' (yan etkiler) olarak adlandırılır.",
    tags: ["saglik-vocab"],
    mockSetNumber: 2,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "kelime-bilgisi",
    questionType: "MCQ",
    difficulty: "ORTA",
    prompt: "The new antibiotic was found to be highly ---- against the bacteria causing the infection.",
    options: ["effective", "toxic", "irrelevant", "expired"],
    correctIndex: 0,
    explanation:
      "Bir ilacın enfeksiyona karşı başarılı sonuç vermesi 'effective' (etkili) ile ifade edilir; 'toxic' zehirli, 'expired' süresi dolmuş anlamındadır ve bağlamla uyuşmaz.",
    tags: ["saglik-vocab"],
    mockSetNumber: 2,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "kelime-bilgisi",
    questionType: "MCQ",
    difficulty: "ORTA",
    prompt:
      "Because the virus can ---- from person to person through respiratory droplets, health officials recommended wearing masks in crowded areas.",
    options: ["transmit", "digest", "circulate", "immunize"],
    correctIndex: 0,
    explanation:
      "Kişiden kişiye bulaşan bir virüs için 'transmit' (bulaştırmak/iletmek) doğru fiildir; diğerleri bulaşma sürecini tanımlamaz.",
    tags: ["saglik-vocab"],
    mockSetNumber: 2,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "kelime-bilgisi",
    questionType: "MCQ",
    difficulty: "ZOR",
    prompt:
      "Epidemiologists use statistical models to ---- how quickly a disease might spread through a population.",
    options: ["forecast", "cure", "vaccinate", "sterilize"],
    correctIndex: 0,
    explanation: "İstatistiksel modellerle bir hastalığın yayılma hızını 'öngörmek/tahmin etmek' 'forecast' fiiliyle ifade edilir.",
    tags: ["saglik-vocab"],
    mockSetNumber: 2,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "kelime-bilgisi",
    questionType: "MCQ",
    difficulty: "ZOR",
    prompt:
      "The study found that the drug's effectiveness began to ---- once patients developed a tolerance to it.",
    options: ["wane", "surge", "commence", "intensify"],
    correctIndex: 0,
    explanation:
      "Bir ilacın toleransla birlikte etkisinin azalması 'wane' (zayıflamak) ile ifade edilir; diğerleri artış veya başlangıç anlamı taşır ve bağlamla çelişir.",
    tags: ["saglik-vocab"],
    mockSetNumber: 2,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "kelime-bilgisi",
    questionType: "MCQ",
    difficulty: "KOLAY",
    prompt:
      "During the ---- period, an infected person may not show any symptoms yet can still spread the disease.",
    options: ["incubation", "recovery", "consultation", "immunization"],
    correctIndex: 0,
    explanation:
      "Belirti göstermeden hastalığı taşıyabilme dönemi 'incubation period' (kuluçka dönemi) olarak adlandırılır.",
    tags: ["saglik-vocab"],
    mockSetNumber: 2,
  },
  // --- Çeviri (EN → TR) (4) ---
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "ceviri-en-tr",
    questionType: "TRANSLATION_EN_TR",
    difficulty: "KOLAY",
    prompt: "The doctor prescribed antibiotics to treat the bacterial infection.",
    options: [
      "Doktor, bakteriyel enfeksiyonu tedavi etmek için antibiyotik reçete etti.",
      "Doktor, viral enfeksiyonu tedavi etmek için antibiyotik reçete etti.",
      "Hasta, bakteriyel enfeksiyonu tedavi etmek için antibiyotik istedi.",
      "Doktor, bakteriyel enfeksiyonu önlemek için antibiyotik reçete etti.",
    ],
    correctIndex: 0,
    explanation:
      "Cümle doktorun bakteriyel enfeksiyonu 'tedavi etmek' için antibiyotik reçete ettiğini söyler; B yanlış enfeksiyon türü, C özneyi değiştiriyor, D 'treat' yerine 'önlemek' diyerek anlamı kaydırıyor.",
    tags: ["saglik-ceviri"],
    mockSetNumber: 2,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "ceviri-en-tr",
    questionType: "TRANSLATION_EN_TR",
    difficulty: "ORTA",
    prompt: "Researchers are still investigating why some patients respond better to the treatment than others.",
    options: [
      "Araştırmacılar, bazı hastaların tedaviye neden diğerlerinden daha iyi yanıt verdiğini hâlâ araştırıyor.",
      "Araştırmacılar, bazı hastaların tedaviye neden diğerlerinden daha kötü yanıt verdiğini hâlâ araştırıyor.",
      "Araştırmacılar, tüm hastaların tedaviye aynı şekilde yanıt verdiğini kanıtladı.",
      "Doktorlar, bazı hastaların tedaviye neden diğerlerinden daha iyi yanıt verdiğini hâlâ araştırıyor.",
    ],
    correctIndex: 0,
    explanation:
      "'Better' ifadesi olumlu yanıtı belirtir ve 'still investigating' devam eden bir araştırmayı anlatır; A bunları doğru aktarır. B ters anlam, C kanıtlanmış bir sonuç iddia ediyor, D özneyi ('researchers' yerine 'doktorlar') değiştiriyor.",
    tags: ["saglik-ceviri"],
    mockSetNumber: 2,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "ceviri-en-tr",
    questionType: "TRANSLATION_EN_TR",
    difficulty: "ORTA",
    prompt: "The spread of the disease slowed considerably once the vaccination campaign reached rural areas.",
    options: [
      "Aşılama kampanyası kırsal bölgelere ulaştığında hastalığın yayılması önemli ölçüde yavaşladı.",
      "Aşılama kampanyası kırsal bölgelere ulaştığında hastalığın yayılması önemli ölçüde hızlandı.",
      "Aşılama kampanyası şehir merkezlerine ulaştığında hastalığın yayılması önemli ölçüde yavaşladı.",
      "Hastalığın yayılması yavaşladığında aşılama kampanyası kırsal bölgelere ulaştı.",
    ],
    correctIndex: 0,
    explanation:
      "Cümle aşılama kampanyasının kırsal bölgelere ulaşmasıyla yayılmanın yavaşladığını anlatır; B ters anlam, C yanlış yer (şehir merkezi), D neden-sonuç ilişkisini tersine çeviriyor.",
    tags: ["saglik-ceviri"],
    mockSetNumber: 2,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "ceviri-en-tr",
    secondaryTopicSlugs: ["baglaclar"],
    questionType: "TRANSLATION_EN_TR",
    difficulty: "ZOR",
    prompt: "Not until the clinical trial's final phase did researchers discover the drug's rare but serious side effect.",
    options: [
      "Araştırmacılar, ilacın nadir ama ciddi yan etkisini ancak klinik denemenin son aşamasında keşfettiler.",
      "Araştırmacılar, ilacın nadir ama ciddi yan etkisini klinik denemenin ilk aşamasında keşfettiler.",
      "Araştırmacılar, ilacın yaygın ve ciddi yan etkisini klinik denemenin son aşamasında keşfettiler.",
      "Araştırmacılar, klinik denemenin son aşamasında ilacın herhangi bir yan etkisi olmadığını keşfettiler.",
    ],
    correctIndex: 0,
    explanation:
      "'Not until...did' devrik yapısı 'ancak ... aşamasında' anlamını verir; A bunu doğru yansıtır. B yanlış aşama (ilk), C 'rare' yerine 'yaygın' diyor, D yan etkinin varlığını reddediyor.",
    tags: ["saglik-ceviri"],
    mockSetNumber: 2,
  },
  // --- Çeviri (TR → EN) (4) ---
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "ceviri-tr-en",
    questionType: "TRANSLATION_TR_EN",
    difficulty: "KOLAY",
    prompt: "Eczacı, ilacı günde iki kez almasını tavsiye etti.",
    options: [
      "The pharmacist advised taking the medication twice a day.",
      "The pharmacist advised taking the medication once a day.",
      "The doctor advised taking the medication twice a day.",
      "The pharmacist advised avoiding the medication twice a day.",
    ],
    correctIndex: 0,
    explanation:
      "'Eczacı' → 'pharmacist', 'günde iki kez' → 'twice a day' A'da doğru yer alır; B yanlış sıklık, C yanlış özne, D 'almasını' yerine 'kaçınmasını' anlamı katıyor.",
    tags: ["saglik-ceviri"],
    mockSetNumber: 2,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "ceviri-tr-en",
    secondaryTopicSlugs: ["edilgen-cati"],
    questionType: "TRANSLATION_TR_EN",
    difficulty: "ORTA",
    prompt: "Bu ilacın hamilelik döneminde kullanılması önerilmemektedir.",
    options: [
      "The use of this medication during pregnancy is not recommended.",
      "The use of this medication during pregnancy is highly recommended.",
      "The use of this medication after pregnancy is not recommended.",
      "This medication is not available during pregnancy.",
    ],
    correctIndex: 0,
    explanation:
      "'Önerilmemektedir' → 'is not recommended' A'da doğru edilgen yapıyla verilir; B ters anlam, C yanlış zaman dilimi ('after' yerine 'during' olmalı), D farklı bir anlam (bulunabilirlik) katıyor.",
    tags: ["saglik-ceviri"],
    mockSetNumber: 2,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "ceviri-tr-en",
    secondaryTopicSlugs: ["edilgen-cati"],
    questionType: "TRANSLATION_TR_EN",
    difficulty: "ORTA",
    prompt: "Salgın hastalıkların yayılmasını önlemek için hijyen kurallarına uyulmalıdır.",
    options: [
      "Hygiene rules must be followed to prevent the spread of epidemic diseases.",
      "Hygiene rules must be followed to promote the spread of epidemic diseases.",
      "Hygiene rules should be avoided to prevent the spread of epidemic diseases.",
      "Epidemic diseases must be followed to prevent the spread of hygiene rules.",
    ],
    correctIndex: 0,
    explanation:
      "'Yayılmasını önlemek için' → 'to prevent the spread', 'uyulmalıdır' → 'must be followed' A'da doğru aktarılır; B 'prevent' yerine 'promote', C 'followed' yerine 'avoided', D özne-nesne ilişkisini tamamen tersine çeviriyor.",
    tags: ["saglik-ceviri"],
    mockSetNumber: 2,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "ceviri-tr-en",
    secondaryTopicSlugs: ["modal-fiiller"],
    questionType: "TRANSLATION_TR_EN",
    difficulty: "ZOR",
    prompt: "İlaç piyasaya sürülmeden önce yıllarca klinik denemelerden geçirilmiş olmalıydı.",
    options: [
      "The drug must have gone through years of clinical trials before being launched on the market.",
      "The drug must go through years of clinical trials before being launched on the market.",
      "The drug might have gone through years of clinical trials before being launched on the market.",
      "The drug had gone through years of clinical trials before being launched on the market.",
    ],
    correctIndex: 0,
    explanation:
      "'Geçirilmiş olmalıydı' geçmişe yönelik güçlü bir çıkarımı ifade eder; bu 'must have + PP' yapısıyla karşılanır (A). B şimdiki/gelecek zorunluluk, C daha zayıf bir olasılık ('might have'), D kesinlik/çıkarım anlamı taşımayan düz geçmiş zamandır.",
    tags: ["saglik-ceviri"],
    mockSetNumber: 2,
  },
  // --- Okuma (4) ---
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "okuma",
    questionType: "READING_COMPREHENSION",
    difficulty: "KOLAY",
    passageText:
      "Epidemiologists rely on a key measure known as the basic reproduction number, or R0, to predict how contagious a disease is. This number represents the average number of people that one infected person will pass the disease to in a population with no immunity. If R0 is greater than one, the disease is likely to spread; if it is below one, the outbreak will eventually die out. Public health interventions such as vaccination, quarantine, and social distancing are designed specifically to lower the effective reproduction number, thereby slowing transmission and preventing healthcare systems from becoming overwhelmed during an outbreak.",
    prompt: "Parçaya göre, R0 (temel üreme sayısı) neyi ifade eder?",
    options: [
      "Bağışıklığı olmayan bir toplulukta, enfekte bir kişinin hastalığı ortalama kaç kişiye bulaştıracağını",
      "Bir hastalığın ölüm oranını",
      "Aşılanan kişi sayısını",
      "Karantina süresinin uzunluğunu",
    ],
    correctIndex: 0,
    explanation:
      "Parçada R0'ın 'bağışıklığı olmayan bir toplulukta enfekte bir kişinin hastalığı ortalama kaç kişiye bulaştıracağını' temsil ettiği açıkça belirtilmiştir.",
    tags: ["saglik-reading"],
    mockSetNumber: 2,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "okuma",
    questionType: "READING_COMPREHENSION",
    difficulty: "ORTA",
    passageText:
      "Epidemiologists rely on a key measure known as the basic reproduction number, or R0, to predict how contagious a disease is. This number represents the average number of people that one infected person will pass the disease to in a population with no immunity. If R0 is greater than one, the disease is likely to spread; if it is below one, the outbreak will eventually die out. Public health interventions such as vaccination, quarantine, and social distancing are designed specifically to lower the effective reproduction number, thereby slowing transmission and preventing healthcare systems from becoming overwhelmed during an outbreak.",
    prompt: "Parçaya göre, R0 değeri birin altına düştüğünde ne olur?",
    options: [
      "Salgın zamanla sona erer",
      "Salgın hızla yayılmaya devam eder",
      "Aşılama kampanyaları durdurulur",
      "Hastalık kronik hale gelir",
    ],
    correctIndex: 0,
    explanation:
      "Parçada 'if it is below one, the outbreak will eventually die out' ifadesiyle R0'ın birin altına düşmesi durumunda salgının zamanla sona ereceği belirtilmiştir.",
    tags: ["saglik-reading"],
    mockSetNumber: 2,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "okuma",
    questionType: "READING_COMPREHENSION",
    difficulty: "ORTA",
    passageText:
      "Epidemiologists rely on a key measure known as the basic reproduction number, or R0, to predict how contagious a disease is. This number represents the average number of people that one infected person will pass the disease to in a population with no immunity. If R0 is greater than one, the disease is likely to spread; if it is below one, the outbreak will eventually die out. Public health interventions such as vaccination, quarantine, and social distancing are designed specifically to lower the effective reproduction number, thereby slowing transmission and preventing healthcare systems from becoming overwhelmed during an outbreak.",
    prompt: "Parçaya göre, aşılama, karantina ve sosyal mesafe gibi halk sağlığı müdahalelerinin amacı nedir?",
    options: [
      "Etkin üreme sayısını düşürerek bulaşmayı yavaşlatmak",
      "R0 değerini artırmak",
      "Sağlık sistemlerinin kapasitesini azaltmak",
      "Hastalığın kuluçka süresini uzatmak",
    ],
    correctIndex: 0,
    explanation:
      "Parçanın son cümlesi bu müdahalelerin 'etkin üreme sayısını düşürerek bulaşmayı yavaşlatmak' amacıyla tasarlandığını belirtir.",
    tags: ["saglik-reading"],
    mockSetNumber: 2,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "okuma",
    questionType: "READING_COMPREHENSION",
    difficulty: "ZOR",
    passageText:
      "Epidemiologists rely on a key measure known as the basic reproduction number, or R0, to predict how contagious a disease is. This number represents the average number of people that one infected person will pass the disease to in a population with no immunity. If R0 is greater than one, the disease is likely to spread; if it is below one, the outbreak will eventually die out. Public health interventions such as vaccination, quarantine, and social distancing are designed specifically to lower the effective reproduction number, thereby slowing transmission and preventing healthcare systems from becoming overwhelmed during an outbreak.",
    prompt: "Parçaya göre, sağlık sistemlerinin aşırı yüklenmesi hangi durumla ilişkilendirilmiştir?",
    options: [
      "Halk sağlığı müdahalelerinin uygulanmadığı ve bulaşmanın yavaşlatılmadığı bir salgın süreciyle",
      "R0 değerinin sürekli birin altında kaldığı bir durumla",
      "Aşılama oranının yüzde yüze ulaştığı bir durumla",
      "Karantina uygulamalarının tamamen kaldırıldığı bir dönemle",
    ],
    correctIndex: 0,
    explanation:
      "Parça, halk sağlığı müdahalelerinin bulaşmayı yavaşlatarak sağlık sistemlerinin aşırı yüklenmesini önlemeyi amaçladığını belirtir; dolayısıyla bu müdahaleler olmadan bulaşmanın yavaşlamayacağı ve sistemlerin aşırı yükleneceği çıkarımı yapılabilir.",
    tags: ["saglik-reading"],
    mockSetNumber: 2,
  },

  // ============================================================
  // DENEME 3 — Nursing, Geriatrics & Genetics
  // ============================================================
  // --- Kelime Bilgisi (8) ---
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "kelime-bilgisi",
    questionType: "MCQ",
    difficulty: "KOLAY",
    prompt: "The nurse gently ---- the patient's wound before applying a new bandage.",
    options: ["cleaned", "diagnosed", "prescribed", "operated"],
    correctIndex: 0,
    explanation:
      "Hemşirenin yeni bir bandaj uygulamadan önce yapması gereken şey yarayı 'temizlemek'tir ('cleaned'); diğer fiiller bu görevi tanımlamaz.",
    tags: ["saglik-vocab"],
    mockSetNumber: 3,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "kelime-bilgisi",
    questionType: "MCQ",
    difficulty: "KOLAY",
    prompt: "Elderly patients often need extra ---- when walking to prevent falls.",
    options: ["support", "medication", "surgery", "isolation"],
    correctIndex: 0,
    explanation: "Düşmeleri önlemek için yaşlı hastaların yürürken ihtiyaç duyduğu şey 'destek' ('support')'tir.",
    tags: ["saglik-vocab"],
    mockSetNumber: 3,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "kelime-bilgisi",
    questionType: "MCQ",
    difficulty: "ORTA",
    prompt: "Patients with diabetes must carefully ---- their blood sugar levels throughout the day.",
    options: ["monitor", "ignore", "eliminate", "transmit"],
    correctIndex: 0,
    explanation:
      "Diyabet hastalarının gün boyunca kan şekerini 'izlemesi' ('monitor') gerekir; diğer fiiller bu düzenli takip eylemini karşılamaz.",
    tags: ["saglik-vocab"],
    mockSetNumber: 3,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "kelime-bilgisi",
    questionType: "MCQ",
    difficulty: "ORTA",
    prompt: "The hormone insulin helps regulate the amount of glucose ---- in the bloodstream.",
    options: ["circulating", "evaporating", "solidifying", "fermenting"],
    correctIndex: 0,
    explanation:
      "Kan dolaşımında bulunan/glikozun 'dolaştığı' durumu tanımlamak için 'circulating' doğrudur; diğer fiiller biyolojik olarak anlamsızdır.",
    tags: ["saglik-vocab"],
    mockSetNumber: 3,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "kelime-bilgisi",
    questionType: "MCQ",
    difficulty: "ORTA",
    prompt: "Some diseases are ----, meaning they are passed down from parents to their children through genes.",
    options: ["hereditary", "contagious", "chronic", "terminal"],
    correctIndex: 0,
    explanation:
      "Ebeveynden çocuğa genler yoluyla geçen hastalıklar 'hereditary' (kalıtsal) olarak adlandırılır; 'contagious' bulaşıcı, 'chronic' kronik, 'terminal' ölümcül anlamındadır ve tanımla örtüşmez.",
    tags: ["saglik-vocab"],
    mockSetNumber: 3,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "kelime-bilgisi",
    questionType: "MCQ",
    difficulty: "ZOR",
    prompt:
      "A mutation in a single gene can ---- an individual to a higher risk of developing the disorder.",
    options: ["predispose", "immunize", "sedate", "anesthetize"],
    correctIndex: 0,
    explanation: "Bir gen mutasyonunun kişiyi bir hastalığa karşı 'yatkın hale getirmesi' 'predispose' fiiliyle ifade edilir.",
    tags: ["saglik-vocab"],
    mockSetNumber: 3,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "kelime-bilgisi",
    questionType: "MCQ",
    difficulty: "ZOR",
    prompt:
      "The geriatric ward was designed to ---- the specific needs of elderly patients with multiple chronic conditions.",
    options: ["accommodate", "aggravate", "dismiss", "contradict"],
    correctIndex: 0,
    explanation:
      "Bir birimin yaşlı hastaların ihtiyaçlarına göre düzenlenmesi 'accommodate' (karşılamak, uyum sağlamak) ile ifade edilir; diğerleri bu anlamı taşımaz.",
    tags: ["saglik-vocab"],
    mockSetNumber: 3,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "kelime-bilgisi",
    questionType: "MCQ",
    difficulty: "KOLAY",
    prompt: "After the surgery, the patient was moved to the recovery ---- to be monitored closely.",
    options: ["ward", "textbook", "conference", "forecast"],
    correctIndex: 0,
    explanation: "Ameliyat sonrası hastaların izlendiği hastane bölümü 'ward' (koğuş/servis) olarak adlandırılır.",
    tags: ["saglik-vocab"],
    mockSetNumber: 3,
  },
  // --- Çeviri (EN → TR) (4) ---
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "ceviri-en-tr",
    questionType: "TRANSLATION_EN_TR",
    difficulty: "KOLAY",
    prompt: "The nurse measured the patient's temperature before the doctor arrived.",
    options: [
      "Hemşire, doktor gelmeden önce hastanın ateşini ölçtü.",
      "Hemşire, doktor geldikten sonra hastanın ateşini ölçtü.",
      "Doktor, hemşire gelmeden önce hastanın ateşini ölçtü.",
      "Hemşire, doktorun ateşini ölçtü.",
    ],
    correctIndex: 0,
    explanation:
      "'Before the doctor arrived' → 'doktor gelmeden önce' A'da doğru aktarılmıştır; B ters zaman ilişkisi, C özneleri karıştırıyor, D nesneyi yanlış aktarıyor (hastanın yerine doktorun ateşi).",
    tags: ["saglik-ceviri"],
    mockSetNumber: 3,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "ceviri-en-tr",
    questionType: "TRANSLATION_EN_TR",
    difficulty: "ORTA",
    prompt: "Elderly patients are more likely to experience complications after surgery than younger ones.",
    options: [
      "Yaşlı hastaların ameliyat sonrası komplikasyon yaşama olasılığı genç hastalara göre daha yüksektir.",
      "Genç hastaların ameliyat sonrası komplikasyon yaşama olasılığı yaşlı hastalara göre daha yüksektir.",
      "Yaşlı hastaların ameliyat öncesi komplikasyon yaşama olasılığı genç hastalara göre daha yüksektir.",
      "Yaşlı hastaların ameliyat sonrası iyileşme olasılığı genç hastalara göre daha yüksektir.",
    ],
    correctIndex: 0,
    explanation:
      "Cümle yaşlı hastaların ameliyat SONRASI komplikasyon olasılığının daha yüksek olduğunu söyler; B özneleri yer değiştiriyor, C yanlış zaman (öncesi), D 'complication' yerine 'iyileşme' diyerek anlamı tersine çeviriyor.",
    tags: ["saglik-ceviri"],
    mockSetNumber: 3,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "ceviri-en-tr",
    questionType: "TRANSLATION_EN_TR",
    difficulty: "ORTA",
    prompt: "Genetic counseling helps families understand the likelihood of passing a hereditary condition to their children.",
    options: [
      "Genetik danışmanlık, ailelerin kalıtsal bir rahatsızlığı çocuklarına aktarma olasılığını anlamalarına yardımcı olur.",
      "Genetik danışmanlık, ailelerin kalıtsal bir rahatsızlığı çocuklarına aktarmasını engeller.",
      "Genetik danışmanlık, çocukların kalıtsal bir rahatsızlığı ailelerine aktarma olasılığını anlamalarına yardımcı olur.",
      "Genetik danışmanlık, ailelerin bulaşıcı bir hastalığı çocuklarına aktarma olasılığını anlamalarına yardımcı olur.",
    ],
    correctIndex: 0,
    explanation:
      "Cümle genetik danışmanlığın ailelerin 'olasılığı anlamasına yardımcı olduğunu' söyler, engellediğini değil; B yanlış eylem (engellemek), C özne-nesne ilişkisini tersine çeviriyor, D 'hereditary' yerine 'bulaşıcı' diyerek kavramı değiştiriyor.",
    tags: ["saglik-ceviri"],
    mockSetNumber: 3,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "ceviri-en-tr",
    secondaryTopicSlugs: ["kosul-cumleleri"],
    questionType: "TRANSLATION_EN_TR",
    difficulty: "ZOR",
    prompt: "Were it not for continuous insulin therapy, many patients with type 1 diabetes would not survive.",
    options: [
      "Sürekli insülin tedavisi olmasaydı, tip 1 diyabet hastası birçok kişi hayatta kalamazdı.",
      "Sürekli insülin tedavisi olduğu için, tip 1 diyabet hastası birçok kişi hayatta kalamadı.",
      "Sürekli insülin tedavisi olmasaydı, tip 1 diyabet hastası birçok kişi hayatta kalacaktı.",
      "Sürekli insülin tedavisi sayesinde, tip 1 diyabet hastası birçok kişi hayatta kalamayacak.",
    ],
    correctIndex: 0,
    explanation:
      "'Were it not for' devrik 2. tip koşul yapısı, 'olmasaydı' anlamındaki bir varsayımı ifade eder ve sonucu 'hayatta kalamazdı' şeklinde olumsuzdur; A bunu doğru verir. B gerçek bir nedeni ifade ediyor, C sonucu olumluya çeviriyor, D anlamı tamamen tersine çeviriyor.",
    tags: ["saglik-ceviri"],
    mockSetNumber: 3,
  },
  // --- Çeviri (TR → EN) (4) ---
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "ceviri-tr-en",
    questionType: "TRANSLATION_TR_EN",
    difficulty: "KOLAY",
    prompt: "Hemşire, hastaya ilacını zamanında vermeyi unutmadı.",
    options: [
      "The nurse did not forget to give the patient her medication on time.",
      "The nurse forgot to give the patient her medication on time.",
      "The nurse did not forget to give the patient her medication late.",
      "The patient did not forget to give the nurse her medication on time.",
    ],
    correctIndex: 0,
    explanation:
      "'Unutmadı' → 'did not forget', 'zamanında' → 'on time' A'da doğru yer alır; B anlamı tersine çeviriyor, C 'zamanında' yerine 'geç' diyor, D özneleri karıştırıyor.",
    tags: ["saglik-ceviri"],
    mockSetNumber: 3,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "ceviri-tr-en",
    questionType: "TRANSLATION_TR_EN",
    difficulty: "ORTA",
    prompt: "Yaşlı bireylerde kronik hastalıkların görülme sıklığı, gençlere kıyasla oldukça yüksektir.",
    options: [
      "The prevalence of chronic diseases among elderly individuals is considerably higher compared to younger ones.",
      "The prevalence of chronic diseases among young individuals is considerably higher compared to elderly ones.",
      "The prevalence of chronic diseases among elderly individuals is considerably lower compared to younger ones.",
      "The prevalence of acute diseases among elderly individuals is considerably higher compared to younger ones.",
    ],
    correctIndex: 0,
    explanation:
      "'Yaşlı bireylerde... oldukça yüksektir' ifadesi A'da doğru şekilde 'higher... among elderly individuals' olarak aktarılmıştır; B özneleri ters çeviriyor, C 'higher' yerine 'lower', D 'kronik' yerine 'akut' kullanıyor.",
    tags: ["saglik-ceviri"],
    mockSetNumber: 3,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "ceviri-tr-en",
    questionType: "TRANSLATION_TR_EN",
    difficulty: "ORTA",
    prompt: "Doktorlar, ailede diyabet öyküsü olan bireylerin düzenli olarak kan şekeri testi yaptırmasını önerir.",
    options: [
      "Doctors recommend that individuals with a family history of diabetes have their blood sugar tested regularly.",
      "Doctors recommend that individuals with a family history of diabetes have their blood pressure tested regularly.",
      "Doctors recommend that individuals without a family history of diabetes have their blood sugar tested regularly.",
      "Doctors require that individuals with a family history of diabetes have their blood sugar tested regularly.",
    ],
    correctIndex: 0,
    explanation:
      "'Diyabet öyküsü' → 'family history of diabetes', 'kan şekeri testi' → 'blood sugar tested' A'da doğrudur; B 'blood sugar' yerine 'blood pressure', C 'with' yerine 'without', D 'recommend' yerine 'require' (zorunlu kılmak) kullanıyor.",
    tags: ["saglik-ceviri"],
    mockSetNumber: 3,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "ceviri-tr-en",
    secondaryTopicSlugs: ["kosul-cumleleri"],
    questionType: "TRANSLATION_TR_EN",
    difficulty: "ZOR",
    prompt: "Genetik testler daha yaygınlaşmasaydı, birçok kalıtsal hastalık bu denli erken teşhis edilemeyecekti.",
    options: [
      "If genetic testing had not become more widespread, many hereditary diseases could not have been diagnosed this early.",
      "If genetic testing becomes more widespread, many hereditary diseases will not be diagnosed this early.",
      "If genetic testing had become more widespread, many hereditary diseases could not have been diagnosed this early.",
      "If genetic testing had not become more widespread, many hereditary diseases could have been diagnosed this early.",
    ],
    correctIndex: 0,
    explanation:
      "Cümle geçmişte gerçekleşmemiş bir varsayımı anlatır (3. tip koşul, olumsuz koşul + olumsuz sonuç: yaygınlaşmadığı için erken teşhis edilemezdi); A bunu doğru verir. B gerçek koşula çeviriyor, C koşul cümlesindeki olumsuzluğu kaldırıyor, D sonuç cümlesindeki olumsuzluğu kaldırarak anlamı tersine çeviriyor.",
    tags: ["saglik-ceviri"],
    mockSetNumber: 3,
  },
  // --- Okuma (4) ---
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "okuma",
    questionType: "READING_COMPREHENSION",
    difficulty: "KOLAY",
    passageText:
      "As populations around the world continue to age, nursing care for older adults has become increasingly complex. Many elderly patients live with several chronic conditions simultaneously, a situation known as multimorbidity, which requires nurses to coordinate care across multiple specialists and medications. Poor coordination can lead to dangerous drug interactions or conflicting treatment plans. To address this, many hospitals have introduced case management programs in which a single nurse tracks a patient's entire care journey, communicates with all treating physicians, and ensures that the patient and family fully understand each step of the treatment process.",
    prompt: "Parçaya göre, 'multimorbidity' terimi neyi ifade eder?",
    options: [
      "Bir hastada aynı anda birden fazla kronik hastalığın bulunması",
      "Bir hastalığın hiç tedavi edilmemesi",
      "Bir hastanın hiç ilaç kullanmaması",
      "Yaşlı nüfusun azalması",
    ],
    correctIndex: 0,
    explanation:
      "Parçada 'multimorbidity', 'yaşlı hastaların aynı anda birden fazla kronik durumla yaşaması' olarak tanımlanmıştır.",
    tags: ["saglik-reading"],
    mockSetNumber: 3,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "okuma",
    questionType: "READING_COMPREHENSION",
    difficulty: "ORTA",
    passageText:
      "As populations around the world continue to age, nursing care for older adults has become increasingly complex. Many elderly patients live with several chronic conditions simultaneously, a situation known as multimorbidity, which requires nurses to coordinate care across multiple specialists and medications. Poor coordination can lead to dangerous drug interactions or conflicting treatment plans. To address this, many hospitals have introduced case management programs in which a single nurse tracks a patient's entire care journey, communicates with all treating physicians, and ensures that the patient and family fully understand each step of the treatment process.",
    prompt: "Parçaya göre, zayıf koordinasyon hangi soruna yol açabilir?",
    options: [
      "Tehlikeli ilaç etkileşimleri veya çelişen tedavi planları",
      "Hastane maliyetlerinin azalması",
      "Hastaların daha hızlı iyileşmesi",
      "Doktor sayısının artması",
    ],
    correctIndex: 0,
    explanation:
      "Parçada zayıf koordinasyonun 'tehlikeli ilaç etkileşimlerine veya çelişen tedavi planlarına' yol açabileceği belirtilmiştir.",
    tags: ["saglik-reading"],
    mockSetNumber: 3,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "okuma",
    questionType: "READING_COMPREHENSION",
    difficulty: "ORTA",
    passageText:
      "As populations around the world continue to age, nursing care for older adults has become increasingly complex. Many elderly patients live with several chronic conditions simultaneously, a situation known as multimorbidity, which requires nurses to coordinate care across multiple specialists and medications. Poor coordination can lead to dangerous drug interactions or conflicting treatment plans. To address this, many hospitals have introduced case management programs in which a single nurse tracks a patient's entire care journey, communicates with all treating physicians, and ensures that the patient and family fully understand each step of the treatment process.",
    prompt: "Parçaya göre, vaka yönetimi (case management) programlarında tek bir hemşirenin rolü nedir?",
    options: [
      "Hastanın tüm tedavi sürecini takip edip tüm doktorlarla iletişim kurmak",
      "Sadece ilaç dağıtımını yapmak",
      "Hastane finansmanını yönetmek",
      "Yalnızca ameliyatlarda görev almak",
    ],
    correctIndex: 0,
    explanation:
      "Parçada tek bir hemşirenin 'hastanın tüm tedavi sürecini takip ettiği, tüm doktorlarla iletişim kurduğu' belirtilmiştir.",
    tags: ["saglik-reading"],
    mockSetNumber: 3,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "okuma",
    questionType: "READING_COMPREHENSION",
    difficulty: "ZOR",
    passageText:
      "As populations around the world continue to age, nursing care for older adults has become increasingly complex. Many elderly patients live with several chronic conditions simultaneously, a situation known as multimorbidity, which requires nurses to coordinate care across multiple specialists and medications. Poor coordination can lead to dangerous drug interactions or conflicting treatment plans. To address this, many hospitals have introduced case management programs in which a single nurse tracks a patient's entire care journey, communicates with all treating physicians, and ensures that the patient and family fully understand each step of the treatment process.",
    prompt: "Parçadan hareketle, vaka yönetimi programlarının temel amacı hakkında ne söylenebilir?",
    options: [
      "Kronik hastalığı olan yaşlı hastalarda bakım koordinasyonundaki eksiklikleri gidermeyi amaçlar",
      "Yaşlı hastaların hastaneye başvurmasını engellemeyi amaçlar",
      "Hemşire sayısını azaltmayı amaçlar",
      "Hastaların tedavi sürecinden habersiz kalmasını sağlamayı amaçlar",
    ],
    correctIndex: 0,
    explanation:
      "Parça, zayıf koordinasyonun sorun yarattığını belirttikten sonra bu sorunu çözmek için vaka yönetimi programlarının tanıtıldığını anlatır; dolayısıyla programların amacı bakım koordinasyonundaki eksiklikleri gidermektir.",
    tags: ["saglik-reading"],
    mockSetNumber: 3,
  },

  // ============================================================
  // DENEME 4 — Neurology, Oncology & Respiratory Health
  // ============================================================
  // --- Kelime Bilgisi (8) ---
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "kelime-bilgisi",
    questionType: "MCQ",
    difficulty: "KOLAY",
    prompt: "The doctor asked the patient to describe the exact location of the ---- to help identify the cause.",
    options: ["pain", "vaccine", "therapy", "surgeon"],
    correctIndex: 0,
    explanation: "Hastadan ağrının yerini tarif etmesi istenir; 'pain' (ağrı) bağlama uyan tek isimdir.",
    tags: ["saglik-vocab"],
    mockSetNumber: 4,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "kelime-bilgisi",
    questionType: "MCQ",
    difficulty: "KOLAY",
    prompt: "Regular mammograms allow doctors to ---- breast cancer at an early, more treatable stage.",
    options: ["detect", "cause", "spread", "worsen"],
    correctIndex: 0,
    explanation:
      "Düzenli taramalar kanserin erken 'tespit edilmesini' ('detect') sağlar; diğer fiiller anlam olarak uyuşmaz.",
    tags: ["saglik-vocab"],
    mockSetNumber: 4,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "kelime-bilgisi",
    questionType: "MCQ",
    difficulty: "ORTA",
    prompt: "The tumor was found to be ----, meaning it had not spread to other parts of the body.",
    options: ["benign", "malignant", "contagious", "chronic"],
    correctIndex: 0,
    explanation:
      "Vücudun diğer bölgelerine yayılmamış bir tümör 'benign' (iyi huylu) olarak tanımlanır; 'malignant' kötü huylu anlamına gelir ve cümledeki açıklamayla çelişir.",
    tags: ["saglik-vocab"],
    mockSetNumber: 4,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "kelime-bilgisi",
    questionType: "MCQ",
    difficulty: "ORTA",
    prompt: "Long-term exposure to air pollution can ---- respiratory conditions such as asthma.",
    options: ["aggravate", "cure", "prevent", "diagnose"],
    correctIndex: 0,
    explanation:
      "Hava kirliliğine uzun süreli maruz kalmak solunum yolu rahatsızlıklarını 'kötüleştirir' ('aggravate'); diğer fiiller olumlu ya da alakasız bir etkiyi ifade eder.",
    tags: ["saglik-vocab"],
    mockSetNumber: 4,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "kelime-bilgisi",
    questionType: "MCQ",
    difficulty: "ORTA",
    prompt: "After the stroke, the patient underwent physical ---- to regain movement in her left arm.",
    options: ["rehabilitation", "immunization", "sterilization", "sedation"],
    correctIndex: 0,
    explanation: "İnme sonrası hareket kabiliyetini yeniden kazanmak için uygulanan süreç 'rehabilitation' (rehabilitasyon)'dur.",
    tags: ["saglik-vocab"],
    mockSetNumber: 4,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "kelime-bilgisi",
    questionType: "MCQ",
    difficulty: "ZOR",
    prompt: "The neurologist explained that the disorder gradually ---- the nerve cells responsible for muscle control.",
    options: ["degenerates", "regenerates", "sterilizes", "immunizes"],
    correctIndex: 0,
    explanation:
      "Bir hastalığın sinir hücrelerini zamanla 'bozması/dejenere etmesi' 'degenerate' fiiliyle ifade edilir; 'regenerate' tam tersi bir anlam (yenilenme) taşır.",
    tags: ["saglik-vocab"],
    mockSetNumber: 4,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "kelime-bilgisi",
    questionType: "MCQ",
    difficulty: "ZOR",
    prompt:
      "Because the cancer was diagnosed at an advanced stage, doctors could only offer ---- care to ease her pain.",
    options: ["palliative", "preventive", "cosmetic", "elective"],
    correctIndex: 0,
    explanation:
      "İyileştirici tedavi mümkün olmadığında acıyı hafifletmeye yönelik bakım 'palliative care' (palyatif bakım) olarak adlandırılır.",
    tags: ["saglik-vocab"],
    mockSetNumber: 4,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "kelime-bilgisi",
    questionType: "MCQ",
    difficulty: "KOLAY",
    prompt: "Smoking is one of the leading ---- of lung cancer worldwide.",
    options: ["causes", "cures", "symptoms", "remedies"],
    correctIndex: 0,
    explanation: "Sigara kullanımı akciğer kanserinin başlıca 'nedenlerinden' (causes) biridir.",
    tags: ["saglik-vocab"],
    mockSetNumber: 4,
  },
  // --- Çeviri (EN → TR) (4) ---
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "ceviri-en-tr",
    questionType: "TRANSLATION_EN_TR",
    difficulty: "KOLAY",
    prompt: "Air pollution has been linked to an increase in respiratory diseases.",
    options: [
      "Hava kirliliği, solunum yolu hastalıklarındaki artışla ilişkilendirilmiştir.",
      "Hava kirliliği, solunum yolu hastalıklarındaki azalışla ilişkilendirilmiştir.",
      "Solunum yolu hastalıkları, hava kirliliğindeki artışla ilişkilendirilmiştir.",
      "Hava kirliliği, kalp hastalıklarındaki artışla ilişkilendirilmiştir.",
    ],
    correctIndex: 0,
    explanation:
      "Cümle hava kirliliğinin solunum hastalıklarındaki artışla bağlantılı olduğunu söyler; B ters anlam, C özne-nesne ilişkisini tersine çeviriyor, D yanlış hastalık türü belirtiyor.",
    tags: ["saglik-ceviri"],
    mockSetNumber: 4,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "ceviri-en-tr",
    questionType: "TRANSLATION_EN_TR",
    difficulty: "ORTA",
    prompt: "Early detection significantly increases a patient's chances of surviving cancer.",
    options: [
      "Erken teşhis, bir hastanın kanserden kurtulma şansını önemli ölçüde artırır.",
      "Erken teşhis, bir hastanın kanserden kurtulma şansını önemli ölçüde azaltır.",
      "Geç teşhis, bir hastanın kanserden kurtulma şansını önemli ölçüde artırır.",
      "Erken teşhis, bir hastanın kanser olma riskini önemli ölçüde artırır.",
    ],
    correctIndex: 0,
    explanation:
      "Cümle erken teşhisin hayatta kalma şansını artırdığını söyler; B ters anlam, C 'early' yerine 'geç' kullanıyor, D 'chances of surviving' yerine hastalık riskini artırma anlamı katıyor.",
    tags: ["saglik-ceviri"],
    mockSetNumber: 4,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "ceviri-en-tr",
    questionType: "TRANSLATION_EN_TR",
    difficulty: "ORTA",
    prompt: "The stroke left the patient unable to speak clearly for several months.",
    options: [
      "İnme, hastayı birkaç ay boyunca net konuşamaz hale getirdi.",
      "İnme, hastayı birkaç ay boyunca net duyamaz hale getirdi.",
      "Ameliyat, hastayı birkaç ay boyunca net konuşamaz hale getirdi.",
      "İnme, hastayı birkaç yıl boyunca net konuşamaz hale getirdi.",
    ],
    correctIndex: 0,
    explanation:
      "Cümle inmenin hastayı birkaç ay boyunca net konuşamaz bıraktığını söyler; B 'speak' yerine 'duymak', C yanlış neden (ameliyat), D yanlış süre (yıl) kullanıyor.",
    tags: ["saglik-ceviri"],
    mockSetNumber: 4,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "ceviri-en-tr",
    secondaryTopicSlugs: ["baglaclar"],
    questionType: "TRANSLATION_EN_TR",
    difficulty: "ZOR",
    prompt: "So severe was the patient's neurological damage that doctors doubted she would ever walk again.",
    options: [
      "Hastanın nörolojik hasarı o kadar ağırdı ki doktorlar bir daha hiç yürüyemeyeceğinden şüphe duydu.",
      "Hastanın nörolojik hasarı o kadar hafifti ki doktorlar bir daha hiç yürüyemeyeceğinden şüphe duydu.",
      "Hastanın nörolojik hasarı o kadar ağırdı ki doktorlar bir daha yürüyeceğinden emindi.",
      "Doktorların nörolojik hasarı o kadar ağırdı ki hasta bir daha hiç yürüyemeyeceğinden şüphe duydu.",
    ],
    correctIndex: 0,
    explanation:
      "'So + sıfat + that' devrik yapısı 'o kadar ... ki' anlamını verir ve doktorların hastanın bir daha yürüyemeyeceğinden şüphe duyduğunu anlatır; A doğru. B 'severe' yerine 'hafif', C şüpheyi kesinliğe çeviriyor, D özneleri karıştırıyor.",
    tags: ["saglik-ceviri"],
    mockSetNumber: 4,
  },
  // --- Çeviri (TR → EN) (4) ---
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "ceviri-tr-en",
    questionType: "TRANSLATION_TR_EN",
    difficulty: "KOLAY",
    prompt: "Doktor, hastanın akciğer filmini dikkatle inceledi.",
    options: [
      "The doctor carefully examined the patient's lung X-ray.",
      "The doctor carefully examined the patient's heart X-ray.",
      "The patient carefully examined the doctor's lung X-ray.",
      "The doctor quickly examined the patient's lung X-ray.",
    ],
    correctIndex: 0,
    explanation:
      "'Akciğer filmi' → 'lung X-ray', 'dikkatle' → 'carefully' A'da doğru yer alır; B yanlış organ, C özneleri karıştırıyor, D 'dikkatle' yerine 'hızlıca' anlamı katıyor.",
    tags: ["saglik-ceviri"],
    mockSetNumber: 4,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "ceviri-tr-en",
    questionType: "TRANSLATION_TR_EN",
    difficulty: "ORTA",
    prompt: "Kanser tedavisi gören hastaların büyük bir kısmı, tedavi sürecinde ciddi yorgunluk yaşar.",
    options: [
      "A large proportion of patients undergoing cancer treatment experience severe fatigue during the process.",
      "A small proportion of patients undergoing cancer treatment experience severe fatigue during the process.",
      "A large proportion of patients undergoing cancer treatment experience mild fatigue during the process.",
      "A large proportion of patients who have completed cancer treatment experience severe fatigue during the process.",
    ],
    correctIndex: 0,
    explanation:
      "'Büyük bir kısmı' → 'a large proportion', 'ciddi yorgunluk' → 'severe fatigue', 'tedavi sürecinde' → 'during the process' A'da doğru aktarılır; B 'large' yerine 'small', C 'severe' yerine 'mild', D 'undergoing' yerine 'tamamlamış olan' anlamı katıyor.",
    tags: ["saglik-ceviri"],
    mockSetNumber: 4,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "ceviri-tr-en",
    questionType: "TRANSLATION_TR_EN",
    difficulty: "ORTA",
    prompt: "Beyin, vücuttaki en karmaşık organlardan biri olarak kabul edilir.",
    options: [
      "The brain is considered one of the most complex organs in the body.",
      "The brain is considered one of the simplest organs in the body.",
      "The heart is considered one of the most complex organs in the body.",
      "The brain is considered the only complex organ in the body.",
    ],
    correctIndex: 0,
    explanation:
      "'En karmaşık organlardan biri' → 'one of the most complex organs' A'da doğru verilmiştir; B 'complex' yerine 'simple', C yanlış organ, D 'one of' yerine 'the only' diyerek anlamı değiştiriyor.",
    tags: ["saglik-ceviri"],
    mockSetNumber: 4,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "ceviri-tr-en",
    secondaryTopicSlugs: ["kosul-cumleleri"],
    questionType: "TRANSLATION_TR_EN",
    difficulty: "ZOR",
    prompt: "Hastalar semptomları ciddiye almış olsalardı, teşhis bu kadar gecikmeyecekti.",
    options: [
      "If patients had taken the symptoms seriously, the diagnosis would not have been delayed this much.",
      "If patients take the symptoms seriously, the diagnosis will not be delayed this much.",
      "If patients had not taken the symptoms seriously, the diagnosis would not have been delayed this much.",
      "If patients had taken the symptoms seriously, the diagnosis would have been delayed this much.",
    ],
    correctIndex: 0,
    explanation:
      "Cümle geçmişte gerçekleşmemiş bir durumu anlatır (semptomlar ciddiye alınmadığı için teşhis gecikti); 3. tip koşulla 'had taken... would not have been delayed' A'da doğru kurulmuştur. B gerçek koşula çeviriyor, C koşul cümlesine gereksiz olumsuzluk ekliyor, D sonuç cümlesindeki olumsuzluğu kaldırarak anlamı tersine çeviriyor.",
    tags: ["saglik-ceviri"],
    mockSetNumber: 4,
  },
  // --- Okuma (4) ---
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "okuma",
    questionType: "READING_COMPREHENSION",
    difficulty: "KOLAY",
    passageText:
      "Air pollution is increasingly recognized as one of the most significant environmental threats to human health. Fine particulate matter, known as PM2.5, can penetrate deep into the lungs and even enter the bloodstream, contributing to conditions ranging from asthma to cardiovascular disease. Children and the elderly are particularly vulnerable because their respiratory systems are either still developing or already compromised. In response, several major cities have introduced low-emission zones that restrict the most polluting vehicles from entering densely populated areas, a policy that early studies suggest has measurably improved local air quality and reduced hospital admissions for respiratory complaints.",
    prompt: "Parçaya göre, PM2.5 olarak bilinen madde vücutta nereye kadar ulaşabilir?",
    options: [
      "Akciğerlerin derinliklerine ve kan dolaşımına",
      "Sadece cilt yüzeyine",
      "Sadece mideye",
      "Sadece göz çevresine",
    ],
    correctIndex: 0,
    explanation:
      "Parçada PM2.5'in 'akciğerlerin derinliklerine nüfuz edebildiği ve hatta kan dolaşımına girebildiği' belirtilmiştir.",
    tags: ["saglik-reading"],
    mockSetNumber: 4,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "okuma",
    questionType: "READING_COMPREHENSION",
    difficulty: "ORTA",
    passageText:
      "Air pollution is increasingly recognized as one of the most significant environmental threats to human health. Fine particulate matter, known as PM2.5, can penetrate deep into the lungs and even enter the bloodstream, contributing to conditions ranging from asthma to cardiovascular disease. Children and the elderly are particularly vulnerable because their respiratory systems are either still developing or already compromised. In response, several major cities have introduced low-emission zones that restrict the most polluting vehicles from entering densely populated areas, a policy that early studies suggest has measurably improved local air quality and reduced hospital admissions for respiratory complaints.",
    prompt: "Parçaya göre, çocuklar ve yaşlılar hava kirliliğine karşı neden özellikle savunmasızdır?",
    options: [
      "Solunum sistemleri ya hâlâ gelişmekte ya da zaten zayıflamış durumdadır",
      "Daha fazla açık havada vakit geçirdikleri için",
      "Bağışıklık sistemleri diğer gruplardan daha güçlü olduğu için",
      "Sigara kullanım oranları daha yüksek olduğu için",
    ],
    correctIndex: 0,
    explanation:
      "Parçada bu iki grubun savunmasız olma nedeni 'solunum sistemlerinin ya hâlâ gelişmekte ya da zaten zayıflamış olması' şeklinde açıklanmıştır.",
    tags: ["saglik-reading"],
    mockSetNumber: 4,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "okuma",
    questionType: "READING_COMPREHENSION",
    difficulty: "ORTA",
    passageText:
      "Air pollution is increasingly recognized as one of the most significant environmental threats to human health. Fine particulate matter, known as PM2.5, can penetrate deep into the lungs and even enter the bloodstream, contributing to conditions ranging from asthma to cardiovascular disease. Children and the elderly are particularly vulnerable because their respiratory systems are either still developing or already compromised. In response, several major cities have introduced low-emission zones that restrict the most polluting vehicles from entering densely populated areas, a policy that early studies suggest has measurably improved local air quality and reduced hospital admissions for respiratory complaints.",
    prompt: "Parçaya göre, düşük emisyon bölgeleri (low-emission zones) uygulaması ne yapar?",
    options: [
      "En çok kirlilik yayan araçların yoğun nüfuslu bölgelere girişini kısıtlar",
      "Tüm araçların şehir merkezine girişini tamamen yasaklar",
      "Yalnızca elektrikli araçların üretimini artırır",
      "Hastane sayısını artırır",
    ],
    correctIndex: 0,
    explanation:
      "Parçada bu uygulamanın 'en çok kirlilik yayan araçların yoğun nüfuslu bölgelere girmesini kısıtladığı' belirtilmiştir.",
    tags: ["saglik-reading"],
    mockSetNumber: 4,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "okuma",
    questionType: "READING_COMPREHENSION",
    difficulty: "ZOR",
    passageText:
      "Air pollution is increasingly recognized as one of the most significant environmental threats to human health. Fine particulate matter, known as PM2.5, can penetrate deep into the lungs and even enter the bloodstream, contributing to conditions ranging from asthma to cardiovascular disease. Children and the elderly are particularly vulnerable because their respiratory systems are either still developing or already compromised. In response, several major cities have introduced low-emission zones that restrict the most polluting vehicles from entering densely populated areas, a policy that early studies suggest has measurably improved local air quality and reduced hospital admissions for respiratory complaints.",
    prompt: "Parçanın son cümlesine göre, erken çalışmalar düşük emisyon bölgeleri hakkında ne öne sürmektedir?",
    options: [
      "Bu bölgelerin yerel hava kalitesini ölçülebilir biçimde iyileştirdiğini ve solunumla ilgili hastane başvurularını azalttığını",
      "Bu bölgelerin hava kalitesi üzerinde hiçbir etkisinin olmadığını",
      "Bu bölgelerin yalnızca trafik sıkışıklığını azalttığını",
      "Bu bölgelerin hastane başvurularını artırdığını",
    ],
    correctIndex: 0,
    explanation:
      "Parçanın son cümlesinde erken çalışmaların bu politikanın 'yerel hava kalitesini ölçülebilir şekilde iyileştirdiğini ve solunumla ilgili hastane başvurularını azalttığını' öne sürdüğü belirtilmiştir.",
    tags: ["saglik-reading"],
    mockSetNumber: 4,
  },

  // ============================================================
  // DENEME 5 — Emergency Medicine, Medical Ethics & Digital Health
  // ============================================================
  // --- Kelime Bilgisi (8) ---
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "kelime-bilgisi",
    questionType: "MCQ",
    difficulty: "KOLAY",
    prompt: "The emergency room was full of patients waiting to be ---- by a doctor.",
    options: ["examined", "invoiced", "postponed", "advertised"],
    correctIndex: 0,
    explanation:
      "Acil serviste hastaların bir doktor tarafından 'muayene edilmesi' ('examined') beklenir; diğer fiiller tıbbi bağlamla uyuşmaz.",
    tags: ["saglik-vocab"],
    mockSetNumber: 5,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "kelime-bilgisi",
    questionType: "MCQ",
    difficulty: "KOLAY",
    prompt: "Before the operation, the surgeon washed her hands thoroughly to maintain strict ----.",
    options: ["hygiene", "anxiety", "curiosity", "flexibility"],
    correctIndex: 0,
    explanation:
      "Ellerin iyice yıkanması 'hijyen' (hygiene) kurallarına uymak içindir; diğer isimler bu bağlamla ilgisizdir.",
    tags: ["saglik-vocab"],
    mockSetNumber: 5,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "kelime-bilgisi",
    questionType: "MCQ",
    difficulty: "ORTA",
    prompt: "The hospital adopted telemedicine so that patients in remote areas could ---- doctors without traveling long distances.",
    options: ["consult", "operate", "sterilize", "amputate"],
    correctIndex: 0,
    explanation:
      "Uzak bölgelerdeki hastaların uzun yol kat etmeden doktorlarla görüşebilmesi 'consult' (danışmak) fiiliyle ifade edilir.",
    tags: ["saglik-vocab"],
    mockSetNumber: 5,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "kelime-bilgisi",
    questionType: "MCQ",
    difficulty: "ORTA",
    prompt: "Mental health professionals stress that ---- depression as merely 'feeling sad' trivializes a serious medical condition.",
    options: ["dismissing", "diagnosing", "treating", "monitoring"],
    correctIndex: 0,
    explanation:
      "Depresyonu sadece 'üzgün hissetmek' olarak 'göz ardı etmek/küçümsemek' ('dismissing') ciddi bir durumu önemsizleştirir; diğer fiiller bu olumsuz tutumu ifade etmez.",
    tags: ["saglik-vocab"],
    mockSetNumber: 5,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "kelime-bilgisi",
    questionType: "MCQ",
    difficulty: "ORTA",
    prompt: "Medical ethics requires doctors to obtain informed ---- from patients before performing any procedure.",
    options: ["consent", "diagnosis", "prescription", "anesthesia"],
    correctIndex: 0,
    explanation: "Bir işlemden önce hastadan alınması gereken onay 'informed consent' (bilgilendirilmiş onam) olarak adlandırılır.",
    tags: ["saglik-vocab"],
    mockSetNumber: 5,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "kelime-bilgisi",
    questionType: "MCQ",
    difficulty: "ZOR",
    prompt: "The surgical team had to ---- the operation midway through when the patient's vital signs suddenly dropped.",
    options: ["abort", "schedule", "postpone", "celebrate"],
    correctIndex: 0,
    explanation:
      "Yaşamsal bulgularının aniden düşmesi üzerine ameliyatın yarıda 'durdurulması/iptal edilmesi' 'abort' ile ifade edilir; 'postpone' ertelemek anlamındadır ve devam eden bir işlemi yarıda kesmeyi karşılamaz.",
    tags: ["saglik-vocab"],
    mockSetNumber: 5,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "kelime-bilgisi",
    questionType: "MCQ",
    difficulty: "ZOR",
    prompt: "The new outbreak was eventually traced back to a single ---- event at a crowded wedding reception.",
    options: ["super-spreader", "quarantine", "vaccination", "sterilization"],
    correctIndex: 0,
    explanation:
      "Çok sayıda kişiye bulaşmaya neden olan tek bir olay 'super-spreader event' (süper yayıcı olay) olarak adlandırılır; diğer seçenekler bu tanıma uymaz.",
    tags: ["saglik-vocab"],
    mockSetNumber: 5,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "kelime-bilgisi",
    questionType: "MCQ",
    difficulty: "KOLAY",
    prompt: "Patients are asked to ---- an appointment online before visiting the outpatient clinic.",
    options: ["book", "cancel", "forget", "deny"],
    correctIndex: 0,
    explanation: "Poliklinik ziyaretinden önce hastalardan çevrimiçi randevu 'almaları' ('book') istenir.",
    tags: ["saglik-vocab"],
    mockSetNumber: 5,
  },
  // --- Çeviri (EN → TR) (4) ---
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "ceviri-en-tr",
    questionType: "TRANSLATION_EN_TR",
    difficulty: "KOLAY",
    prompt: "Patients must give their consent before undergoing any surgical procedure.",
    options: [
      "Hastalar, herhangi bir cerrahi işlem uygulanmadan önce onay vermelidir.",
      "Doktorlar, herhangi bir cerrahi işlem uygulanmadan önce onay vermelidir.",
      "Hastalar, herhangi bir cerrahi işlem uygulandıktan sonra onay vermelidir.",
      "Hastalar, herhangi bir cerrahi işlem uygulanmadan önce onay almalıdır.",
    ],
    correctIndex: 0,
    explanation:
      "Cümle hastaların işlem öncesinde onay 'vermesi' gerektiğini söyler; B özneyi değiştiriyor, C yanlış zaman ilişkisi, D 'vermek' yerine 'almak' fiiliyle rolleri tersine çeviriyor.",
    tags: ["saglik-ceviri"],
    mockSetNumber: 5,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "ceviri-en-tr",
    questionType: "TRANSLATION_EN_TR",
    difficulty: "ORTA",
    prompt: "Telemedicine has made it easier for patients in remote areas to access specialist care.",
    options: [
      "Tele-tıp, uzak bölgelerdeki hastaların uzman bakımına erişimini kolaylaştırdı.",
      "Tele-tıp, uzak bölgelerdeki hastaların uzman bakımına erişimini zorlaştırdı.",
      "Tele-tıp, şehir merkezindeki hastaların uzman bakımına erişimini kolaylaştırdı.",
      "Uzman bakımı, uzak bölgelerdeki hastaların tele-tıbba erişimini kolaylaştırdı.",
    ],
    correctIndex: 0,
    explanation:
      "Cümle tele-tıbbın uzak bölgelerdeki hastalar için erişimi kolaylaştırdığını söyler; B ters anlam, C yanlış yer, D özne-nesne ilişkisini tersine çeviriyor.",
    tags: ["saglik-ceviri"],
    mockSetNumber: 5,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "ceviri-en-tr",
    questionType: "TRANSLATION_EN_TR",
    difficulty: "ORTA",
    prompt: "The mental health clinic reported a sharp rise in patients seeking help for anxiety disorders.",
    options: [
      "Ruh sağlığı kliniği, anksiyete bozuklukları için yardım arayan hastaların sayısında keskin bir artış bildirdi.",
      "Ruh sağlığı kliniği, anksiyete bozuklukları için yardım arayan hastaların sayısında keskin bir azalış bildirdi.",
      "Ruh sağlığı kliniği, depresyon için yardım arayan hastaların sayısında keskin bir artış bildirdi.",
      "Hastalar, anksiyete bozuklukları için yardım arayan ruh sağlığı kliniklerinin sayısında keskin bir artış bildirdi.",
    ],
    correctIndex: 0,
    explanation:
      "Cümle anksiyete bozukluğu için başvuran hasta sayısındaki artışı bildirir; B ters anlam, C yanlış rahatsızlık (depresyon), D özne-nesne ilişkisini karıştırıyor.",
    tags: ["saglik-ceviri"],
    mockSetNumber: 5,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "ceviri-en-tr",
    secondaryTopicSlugs: ["baglaclar"],
    questionType: "TRANSLATION_EN_TR",
    difficulty: "ZOR",
    prompt: "Rarely has a single public health measure had as broad an impact as handwashing.",
    options: [
      "Tek bir halk sağlığı önleminin el yıkama kadar geniş bir etkisi nadiren olmuştur.",
      "Tek bir halk sağlığı önleminin el yıkama kadar geniş bir etkisi sıklıkla olmuştur.",
      "Hiçbir halk sağlığı önleminin el yıkama kadar geniş bir etkisi olmamıştır.",
      "Tek bir halk sağlığı önlemi, el yıkamanın etkisini nadiren artırmıştır.",
    ],
    correctIndex: 0,
    explanation:
      "'Rarely has...' devrik yapısı 'nadiren olmuştur' anlamını verir ve el yıkamanın istisnai derecede etkili olduğunu vurgular; A doğru. B 'rarely' yerine 'sıklıkla', C 'nadiren' yerine kesin bir olumsuzluk ('hiçbir'), D anlamı farklı bir yöne (etkiyi artırma) kaydırıyor.",
    tags: ["saglik-ceviri"],
    mockSetNumber: 5,
  },
  // --- Çeviri (TR → EN) (4) ---
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "ceviri-tr-en",
    questionType: "TRANSLATION_TR_EN",
    difficulty: "KOLAY",
    prompt: "Acil serviste görevli doktorlar, hastayı hemen muayene etti.",
    options: [
      "The doctors on duty in the emergency room examined the patient immediately.",
      "The doctors on duty in the emergency room examined the patient later.",
      "The nurses on duty in the emergency room examined the patient immediately.",
      "The doctors on duty in the emergency room ignored the patient immediately.",
    ],
    correctIndex: 0,
    explanation:
      "'Hemen' → 'immediately', 'muayene etti' → 'examined' A'da doğru yer alır; B 'hemen' yerine 'daha sonra', C özneyi ('doktorlar' yerine 'hemşireler') değiştiriyor, D 'muayene etti' yerine 'görmezden geldi' anlamı katıyor.",
    tags: ["saglik-ceviri"],
    mockSetNumber: 5,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "ceviri-tr-en",
    questionType: "TRANSLATION_TR_EN",
    difficulty: "ORTA",
    prompt: "Salgın sırasında sağlık çalışanlarının çoğu, uzun vardiyalar nedeniyle tükenmişlik yaşadı.",
    options: [
      "During the pandemic, most healthcare workers experienced burnout due to long shifts.",
      "During the pandemic, most healthcare workers experienced burnout due to short shifts.",
      "During the pandemic, a few healthcare workers experienced burnout due to long shifts.",
      "Before the pandemic, most healthcare workers experienced burnout due to long shifts.",
    ],
    correctIndex: 0,
    explanation:
      "'Çoğu' → 'most', 'uzun vardiyalar' → 'long shifts', 'salgın sırasında' → 'during the pandemic' A'da doğru verilmiştir; B 'long' yerine 'short', C 'most' yerine 'a few', D 'during' yerine 'before' kullanıyor.",
    tags: ["saglik-ceviri"],
    mockSetNumber: 5,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "ceviri-tr-en",
    questionType: "TRANSLATION_TR_EN",
    difficulty: "ORTA",
    prompt: "Bu hastalığın erken belirtileri genellikle fark edilmeden geçer.",
    options: [
      "The early signs of this disease often go unnoticed.",
      "The early signs of this disease are always noticed immediately.",
      "The late signs of this disease often go unnoticed.",
      "This disease often goes unnoticed by its early signs.",
    ],
    correctIndex: 0,
    explanation:
      "'Fark edilmeden geçer' → 'go unnoticed', 'genellikle' → 'often' A'da doğru aktarılmıştır; B ters anlam ('always noticed'), C 'early' yerine 'late', D cümle yapısını anlamsız şekilde değiştiriyor.",
    tags: ["saglik-ceviri"],
    mockSetNumber: 5,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "ceviri-tr-en",
    secondaryTopicSlugs: ["kosul-cumleleri"],
    questionType: "TRANSLATION_TR_EN",
    difficulty: "ZOR",
    prompt: "Hasta yakınları zamanında bilgilendirilmiş olsaydı, karar süreci bu kadar zor geçmeyecekti.",
    options: [
      "Had the patient's relatives been informed in time, the decision-making process would not have been this difficult.",
      "Had the patient's relatives not been informed in time, the decision-making process would not have been this difficult.",
      "If the patient's relatives are informed in time, the decision-making process will not be this difficult.",
      "Had the patient's relatives been informed in time, the decision-making process would have been this difficult.",
    ],
    correctIndex: 0,
    explanation:
      "Cümle geçmişte gerçekleşmemiş bir durumu anlatır (bilgilendirilmedikleri için süreç zor geçti); devrik 3. tip koşul 'Had... been informed... would not have been' A'da doğru kurulmuştur. B koşula gereksiz olumsuzluk ekliyor, C gerçek koşula çeviriyor, D sonuçtaki olumsuzluğu kaldırarak anlamı tersine çeviriyor.",
    tags: ["saglik-ceviri"],
    mockSetNumber: 5,
  },
  // --- Okuma (4) ---
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "okuma",
    questionType: "READING_COMPREHENSION",
    difficulty: "KOLAY",
    passageText:
      "Telemedicine, once considered a niche service, expanded rapidly after healthcare systems faced unprecedented strain during recent global health crises. By allowing patients to consult physicians through video calls rather than in-person visits, telemedicine reduced the burden on overcrowded clinics and lowered the risk of spreading contagious illness in waiting rooms. Studies suggest it is particularly effective for follow-up appointments and mental health counseling, where physical examination is less critical. However, critics note that remote consultations cannot fully replace hands-on examinations, and that unequal access to reliable internet may leave some patients, especially in rural areas, unable to benefit.",
    prompt: "Parçaya göre, tele-tıp neyi azaltmaya yardımcı oldu?",
    options: [
      "Kalabalık kliniklerin yükünü ve bekleme odalarında bulaşıcı hastalık yayılma riskini",
      "Doktorların maaşlarını",
      "Hastane sayısını",
      "Tıp fakültesi mezun sayısını",
    ],
    correctIndex: 0,
    explanation:
      "Parçada tele-tıbbın 'kalabalık kliniklerin yükünü azalttığı ve bekleme odalarında bulaşıcı hastalık yayılma riskini düşürdüğü' belirtilmiştir.",
    tags: ["saglik-reading"],
    mockSetNumber: 5,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "okuma",
    questionType: "READING_COMPREHENSION",
    difficulty: "ORTA",
    passageText:
      "Telemedicine, once considered a niche service, expanded rapidly after healthcare systems faced unprecedented strain during recent global health crises. By allowing patients to consult physicians through video calls rather than in-person visits, telemedicine reduced the burden on overcrowded clinics and lowered the risk of spreading contagious illness in waiting rooms. Studies suggest it is particularly effective for follow-up appointments and mental health counseling, where physical examination is less critical. However, critics note that remote consultations cannot fully replace hands-on examinations, and that unequal access to reliable internet may leave some patients, especially in rural areas, unable to benefit.",
    prompt: "Parçaya göre, tele-tıp özellikle hangi durumlarda etkilidir?",
    options: [
      "Kontrol randevuları ve ruh sağlığı danışmanlığında",
      "Acil ameliyat gerektiren durumlarda",
      "Doğrudan fiziksel muayene gerektiren kırık teşhislerinde",
      "Yalnızca çocuk hastalarda",
    ],
    correctIndex: 0,
    explanation:
      "Parçada tele-tıbbın 'özellikle kontrol randevuları ve ruh sağlığı danışmanlığında etkili olduğu, çünkü bu durumlarda fiziksel muayenenin daha az kritik olduğu' belirtilmiştir.",
    tags: ["saglik-reading"],
    mockSetNumber: 5,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "okuma",
    questionType: "READING_COMPREHENSION",
    difficulty: "ORTA",
    passageText:
      "Telemedicine, once considered a niche service, expanded rapidly after healthcare systems faced unprecedented strain during recent global health crises. By allowing patients to consult physicians through video calls rather than in-person visits, telemedicine reduced the burden on overcrowded clinics and lowered the risk of spreading contagious illness in waiting rooms. Studies suggest it is particularly effective for follow-up appointments and mental health counseling, where physical examination is less critical. However, critics note that remote consultations cannot fully replace hands-on examinations, and that unequal access to reliable internet may leave some patients, especially in rural areas, unable to benefit.",
    prompt: "Parçaya göre, eleştirmenler tele-tıp hakkında ne belirtmektedir?",
    options: [
      "Uzaktan görüşmelerin elle yapılan muayenelerin yerini tam olarak tutamayacağını",
      "Tele-tıbbın her türlü tıbbi ihtiyacı tamamen karşıladığını",
      "Tele-tıbbın kırsal bölgelerdeki hastalara hiçbir fayda sağlamadığını",
      "Tele-tıbbın maliyetinin çok düşük olduğunu",
    ],
    correctIndex: 0,
    explanation:
      "Parçada eleştirmenlerin 'uzaktan görüşmelerin elle yapılan muayenelerin yerini tam olarak tutamayacağını' belirttiği ifade edilir.",
    tags: ["saglik-reading"],
    mockSetNumber: 5,
  },
  {
    examFamily: "TRANSLATION_GRAMMAR",
    examTypeCode: "YOKDIL_SAGLIK",
    topicSlug: "okuma",
    questionType: "READING_COMPREHENSION",
    difficulty: "ZOR",
    passageText:
      "Telemedicine, once considered a niche service, expanded rapidly after healthcare systems faced unprecedented strain during recent global health crises. By allowing patients to consult physicians through video calls rather than in-person visits, telemedicine reduced the burden on overcrowded clinics and lowered the risk of spreading contagious illness in waiting rooms. Studies suggest it is particularly effective for follow-up appointments and mental health counseling, where physical examination is less critical. However, critics note that remote consultations cannot fully replace hands-on examinations, and that unequal access to reliable internet may leave some patients, especially in rural areas, unable to benefit.",
    prompt: "Parçanın son cümlesine göre, güvenilir internete eşit olmayan erişim hangi soruna yol açabilir?",
    options: [
      "Özellikle kırsal bölgelerdeki bazı hastaların tele-tıptan yararlanamaması",
      "Şehirdeki hastaların tele-tıp hizmetlerinden tamamen men edilmesi",
      "Tüm hastaların aynı anda fayda sağlaması",
      "İnternet şirketlerinin hastane hizmetlerini devralması",
    ],
    correctIndex: 0,
    explanation:
      "Son cümlede güvenilir internete eşit olmayan erişimin 'özellikle kırsal bölgelerdeki bazı hastaların tele-tıptan yararlanamamasına' yol açabileceği belirtilmiştir.",
    tags: ["saglik-reading"],
    mockSetNumber: 5,
  },
];
