import type { LexiconEntry } from "../types";

/** A2 sets 16–20: environment, education, work, the office, money. */
export const A2_PART4: LexiconEntry[] = [
  // Set 16 — Environment
  ["environment", "n", "çevre", "We must protect the environment.", "Çevreyi korumalıyız."],
  ["pollution", "n", "kirlilik", "Air pollution is a big problem in cities.", "Hava kirliliği şehirlerde büyük bir sorun."],
  ["recycle", "v", "geri dönüştürmek", "We recycle paper and glass.", "Kağıt ve camı geri dönüştürüyoruz."],
  ["plastic", "n", "plastik", "Try to use less plastic.", "Daha az plastik kullanmaya çalış."],
  ["waste", "n", "atık; israf", "Don't throw food in the waste bin.", "Yiyecekleri çöpe atma."],
  ["save", "v", "tasarruf etmek; kurtarmak", "Turn off the lights to save energy.", "Enerji tasarrufu için ışıkları kapat."],
  ["energy", "n", "enerji", "Solar energy is clean.", "Güneş enerjisi temizdir."],
  ["climate", "n", "iklim", "The climate is changing.", "İklim değişiyor."],
  ["global warming", "n", "küresel ısınma", "Global warming melts the ice.", "Küresel ısınma buzları eritiyor."],
  ["nature", "n", "doğa", "I love spending time in nature.", "Doğada vakit geçirmeyi severim."],
  ["protect", "v", "korumak", "The law protects wild animals.", "Yasa vahşi hayvanları korur."],
  ["rubbish bin", "n", "çöp kutusu", "Put your rubbish in the bin.", "Çöpünü çöp kutusuna at."],
  ["solar", "adj", "güneş (enerjisi) ile ilgili", "Our house has solar panels.", "Evimizde güneş panelleri var."],
  ["litter", "n", "yere atılan çöp", "Please don't drop litter in the park.", "Lütfen parka çöp atmayın."],
  ["reuse", "v", "yeniden kullanmak", "Reuse your shopping bags.", "Alışveriş poşetlerini yeniden kullan."],
  ["planet", "n", "gezegen", "Earth is our only planet.", "Dünya tek gezegenimiz."],
  ["earth", "n", "dünya; toprak", "The Earth goes round the Sun.", "Dünya Güneş'in etrafında döner."],
  ["flood", "n", "sel", "The flood destroyed many homes.", "Sel pek çok evi yıktı."],
  ["drought", "n", "kuraklık", "The drought killed the crops.", "Kuraklık ekinleri yok etti."],
  ["cut down", "pv", "kesmek (ağaç); azaltmak", "They cut down the old trees.", "Yaşlı ağaçları kestiler."],

  // Set 17 — Education
  ["subject", "n", "ders, konu", "What's your favourite subject?", "En sevdiğin ders hangisi?"],
  ["maths", "n", "matematik", "I'm good at maths.", "Matematikte iyiyim."],
  ["science", "n", "fen, bilim", "We have science on Tuesdays.", "Salı günleri fen dersimiz var."],
  ["history", "n", "tarih", "She studies history at university.", "Üniversitede tarih okuyor."],
  ["geography", "n", "coğrafya", "In geography we learn about countries.", "Coğrafyada ülkeleri öğreniyoruz."],
  ["term", "n", "dönem", "The spring term starts in February.", "Bahar dönemi şubatta başlıyor."],
  ["grade", "n", "not; sınıf", "She got good grades this year.", "Bu yıl iyi notlar aldı."],
  ["pass", "v", "geçmek (sınav)", "I passed my driving test.", "Ehliyet sınavımı geçtim."],
  ["fail", "v", "kalmak, başarısız olmak", "He failed the maths exam.", "Matematik sınavından kaldı."],
  ["revise", "v", "tekrar etmek (sınav için)", "I'm revising for my exams.", "Sınavlarım için tekrar yapıyorum."],
  ["semester", "n", "yarıyıl, dönem", "The semester ends in June.", "Dönem haziranda bitiyor."],
  ["uniform", "n", "üniforma", "We wear a uniform at school.", "Okulda üniforma giyeriz."],
  ["headteacher", "n", "okul müdürü", "The headteacher wants to see you.", "Okul müdürü seni görmek istiyor."],
  ["course", "n", "kurs; ders", "I'm taking an English course.", "Bir İngilizce kursuna gidiyorum."],
  ["diploma", "n", "diploma", "She received her diploma last week.", "Diplomasını geçen hafta aldı."],
  ["graduate", "v", "mezun olmak", "He graduated from university last year.", "Geçen yıl üniversiteden mezun oldu."],
  ["knowledge", "n", "bilgi", "He has a lot of knowledge about history.", "Tarih hakkında çok bilgisi var.", "Sayılamaz."],
  ["mistake", "n", "hata", "Everyone makes mistakes.", "Herkes hata yapar.", "“make a mistake” kalıbıyla kullanılır."],
  ["correct", "adj", "doğru", "Choose the correct answer.", "Doğru cevabı seç."],
  ["dictionary", "n", "sözlük", "Look it up in a dictionary.", "Sözlüğe bak."],

  // Set 18 — Work
  ["career", "n", "kariyer", "She wants a career in medicine.", "Tıpta kariyer yapmak istiyor."],
  ["employee", "n", "çalışan", "The company has 300 employees.", "Şirketin 300 çalışanı var."],
  ["employer", "n", "işveren", "My employer pays well.", "İşverenim iyi para veriyor."],
  ["company", "n", "şirket", "He works for a big company.", "Büyük bir şirkette çalışıyor."],
  ["manager", "n", "müdür, yönetici", "I'd like to speak to the manager.", "Müdürle konuşmak istiyorum."],
  ["salary", "n", "maaş", "She earns a good salary.", "İyi bir maaş kazanıyor."],
  ["earn", "v", "kazanmak (para)", "How much do you earn?", "Ne kadar kazanıyorsun?"],
  ["interview", "n", "mülakat, röportaj", "I have a job interview tomorrow.", "Yarın iş mülakatım var."],
  ["apply", "v", "başvurmak", "I applied for a job in a bank.", "Bir bankadaki işe başvurdum.", "“apply for a job” kalıbıyla kullanılır."],
  ["hire", "v", "işe almak; kiralamak", "They hired two new teachers.", "İki yeni öğretmen işe aldılar."],
  ["full-time", "adj", "tam zamanlı", "She has a full-time job.", "Tam zamanlı bir işi var."],
  ["part-time", "adj", "yarı zamanlı", "I work part-time in a café.", "Bir kafede yarı zamanlı çalışıyorum."],
  ["experience", "n", "deneyim", "Do you have any experience?", "Deneyimin var mı?"],
  ["retire", "v", "emekli olmak", "My father retired at sixty.", "Babam altmışında emekli oldu."],
  ["unemployed", "adj", "işsiz", "He's been unemployed for a year.", "Bir yıldır işsiz."],
  ["factory", "n", "fabrika", "The factory makes car parts.", "Fabrika araba parçaları üretiyor."],
  ["lawyer", "n", "avukat", "You should talk to a lawyer.", "Bir avukatla konuşmalısın."],
  ["mechanic", "n", "tamirci", "The mechanic fixed my car.", "Tamirci arabamı onardı."],
  ["receptionist", "n", "resepsiyonist", "Ask the receptionist for a key.", "Resepsiyonistten anahtar iste."],
  ["uniform", "adj", "tek tip, aynı", "The houses are uniform in style.", "Evler tek tip tarzda."],

  // Set 19 — At the office
  ["meeting", "n", "toplantı", "I have a meeting at ten.", "Saat onda toplantım var."],
  ["report", "n", "rapor", "Please finish the report by Friday.", "Lütfen raporu cumaya kadar bitir."],
  ["project", "n", "proje", "We're working on a new project.", "Yeni bir proje üzerinde çalışıyoruz."],
  ["deadline", "n", "son teslim tarihi", "The deadline is next Monday.", "Son teslim tarihi gelecek pazartesi."],
  ["printer", "n", "yazıcı", "The printer is out of paper.", "Yazıcıda kağıt bitti."],
  ["print", "v", "yazdırmak", "Can you print this page?", "Bu sayfayı yazdırabilir misin?"],
  ["file", "n", "dosya", "Save the file on your desktop.", "Dosyayı masaüstüne kaydet."],
  ["document", "n", "belge", "Sign the document here.", "Belgeyi buradan imzalayın."],
  ["sign", "v", "imzalamak", "Please sign your name.", "Lütfen adınızı imzalayın."],
  ["form", "n", "form", "Fill in this form, please.", "Lütfen bu formu doldurun."],
  ["fill in", "pv", "doldurmak (form)", "Fill in your name and address.", "Adınızı ve adresinizi doldurun."],
  ["organise", "v", "düzenlemek, organize etmek", "She organised the whole event.", "Bütün etkinliği o düzenledi."],
  ["staff", "n", "personel", "The hotel staff were very helpful.", "Otel personeli çok yardımseverdi.", "Genellikle çoğul fiille kullanılır: the staff are..."],
  ["overtime", "n", "fazla mesai", "I worked overtime on Saturday.", "Cumartesi fazla mesai yaptım."],
  ["break", "n", "mola, ara", "Let's take a short break.", "Kısa bir mola verelim."],
  ["task", "n", "görev", "I have three tasks to finish today.", "Bugün bitirmem gereken üç görev var."],
  ["promotion", "n", "terfi", "She got a promotion last month.", "Geçen ay terfi aldı."],
  ["leader", "n", "lider", "She is a natural leader.", "Doğal bir lider."],
  ["business", "n", "iş, ticaret; şirket", "He runs a small business.", "Küçük bir işletme yönetiyor."],
  ["contract", "n", "sözleşme", "I signed a one-year contract.", "Bir yıllık sözleşme imzaladım."],

  // Set 20 — Money
  ["coin", "n", "madeni para", "I found a coin on the street.", "Sokakta bir madeni para buldum."],
  ["note", "n", "kâğıt para; not", "Do you have a fifty-lira note?", "Elli liralık banknotun var mı?"],
  ["borrow", "v", "ödünç almak", "Can I borrow some money?", "Biraz borç para alabilir miyim?"],
  ["lend", "v", "ödünç vermek", "Can you lend me ten lira?", "Bana on lira borç verebilir misin?"],
  ["owe", "v", "borçlu olmak", "I owe you twenty lira.", "Sana yirmi lira borçluyum."],
  ["debt", "n", "borç", "He has a lot of debt.", "Çok borcu var.", "“b” okunmaz: /det/."],
  ["account", "n", "hesap (banka)", "I opened a bank account.", "Bir banka hesabı açtım."],
  ["cash machine", "n", "bankamatik", "Is there a cash machine near here?", "Buralarda bankamatik var mı?"],
  ["credit card", "n", "kredi kartı", "Can I pay by credit card?", "Kredi kartıyla ödeyebilir miyim?"],
  ["save up", "pv", "para biriktirmek", "I'm saving up for a new laptop.", "Yeni bir dizüstü bilgisayar için para biriktiriyorum."],
  ["rich", "adj", "zengin", "He became rich very young.", "Çok genç yaşta zengin oldu."],
  ["poor", "adj", "fakir", "Many families are poor in the area.", "Bölgede birçok aile fakir."],
  ["worth", "adj", "değerinde", "This ring is worth a lot of money.", "Bu yüzük çok para eder."],
  ["value", "n", "değer", "The value of the house went up.", "Evin değeri arttı."],
  ["pocket money", "n", "harçlık", "I get pocket money every week.", "Her hafta harçlık alırım."],
  ["budget", "n", "bütçe", "We're on a tight budget.", "Kısıtlı bir bütçemiz var."],
  ["tax", "n", "vergi", "Prices include tax.", "Fiyatlara vergi dahil."],
  ["waste", "v", "boşa harcamak", "Don't waste your money.", "Paranı çarçur etme."],
  ["currency", "n", "para birimi", "The Turkish currency is the lira.", "Türk para birimi liradır."],
  ["exchange rate", "n", "döviz kuru", "What's the exchange rate today?", "Bugün döviz kuru ne?"],
];
