import type { LexiconEntry } from "../types";

/** A2 sets 31–35: describing things, opinions, adverbs, time, amounts & containers. */
export const A2_PART7: LexiconEntry[] = [
  // Set 31 — Describing things
  ["wide", "adj", "geniş", "The river is very wide here.", "Nehir burada çok geniş."],
  ["narrow", "adj", "dar", "The streets in the old town are narrow.", "Eski şehirde sokaklar dar."],
  ["deep", "adj", "derin", "The lake is very deep.", "Göl çok derin."],
  ["shallow", "adj", "sığ", "The water is shallow near the beach.", "Plaja yakın su sığ."],
  ["huge", "adj", "kocaman", "They live in a huge house.", "Kocaman bir evde yaşıyorlar."],
  ["tiny", "adj", "minicik", "The kitten is tiny.", "Yavru kedi minicik."],
  ["soft", "adj", "yumuşak", "This pillow is very soft.", "Bu yastık çok yumuşak."],
  ["hard", "adj", "sert; zor", "The bed is too hard.", "Yatak çok sert."],
  ["smooth", "adj", "pürüzsüz", "Her skin is smooth.", "Cildi pürüzsüz."],
  ["rough", "adj", "pürüzlü, kaba", "The sea was rough today.", "Deniz bugün dalgalıydı."],
  ["sharp", "adj", "keskin", "Be careful, the knife is sharp.", "Dikkat et, bıçak keskin."],
  ["loud", "adj", "yüksek sesli", "The music is too loud.", "Müzik çok yüksek."],
  ["bright", "adj", "parlak; zeki", "The room is bright and sunny.", "Oda aydınlık ve güneşli."],
  ["solid", "adj", "katı, sağlam", "Ice is solid water.", "Buz katı hâldeki sudur."],
  ["dry", "adj", "kuru", "Is the washing dry yet?", "Çamaşırlar kurudu mu?"],
  ["wet", "adj", "ıslak", "My shoes are wet.", "Ayakkabılarım ıslak."],
  ["broken", "adj", "kırık, bozuk", "The lift is broken.", "Asansör bozuk."],
  ["modern", "adj", "modern", "They live in a modern flat.", "Modern bir dairede yaşıyorlar."],
  ["ancient", "adj", "antik, çok eski", "Ephesus is an ancient city.", "Efes antik bir şehirdir."],
  ["comfortable", "adj", "rahat", "This sofa is really comfortable.", "Bu kanepe gerçekten rahat."],

  // Set 32 — Opinions
  ["amazing", "adj", "harika, inanılmaz", "The view was amazing!", "Manzara inanılmazdı!"],
  ["awful", "adj", "berbat", "The food was awful.", "Yemek berbattı."],
  ["terrible", "adj", "korkunç, berbat", "I had a terrible day.", "Berbat bir gün geçirdim."],
  ["wonderful", "adj", "harika", "We had a wonderful time.", "Harika vakit geçirdik."],
  ["excellent", "adj", "mükemmel", "Your English is excellent.", "İngilizcen mükemmel."],
  ["fantastic", "adj", "fantastik, müthiş", "That's fantastic news!", "Bu müthiş bir haber!"],
  ["perfect", "adj", "mükemmel, kusursuz", "The weather is perfect for a picnic.", "Hava piknik için mükemmel."],
  ["fair", "adj", "adil", "It's not fair!", "Bu adil değil!"],
  ["strange", "adj", "garip", "I heard a strange noise.", "Garip bir ses duydum."],
  ["normal", "adj", "normal", "It's normal to feel nervous.", "Gergin hissetmek normal."],
  ["useful", "adj", "yararlı", "This app is very useful.", "Bu uygulama çok yararlı."],
  ["useless", "adj", "işe yaramaz", "This old phone is useless.", "Bu eski telefon işe yaramaz."],
  ["important", "adj", "önemli", "It's important to sleep well.", "İyi uyumak önemlidir."],
  ["popular", "adj", "popüler, sevilen", "This song is very popular.", "Bu şarkı çok sevilen bir şarkı."],
  ["dangerous", "adj", "tehlikeli", "It's dangerous to swim here.", "Burada yüzmek tehlikeli."],
  ["safe", "adj", "güvenli", "Is this area safe at night?", "Bu bölge gece güvenli mi?"],
  ["possible", "adj", "mümkün", "Is it possible to change my seat?", "Koltuğumu değiştirmem mümkün mü?"],
  ["impossible", "adj", "imkânsız", "It's impossible to finish today.", "Bugün bitirmek imkânsız."],
  ["necessary", "adj", "gerekli", "A passport is necessary for travel abroad.", "Yurt dışı seyahati için pasaport gereklidir."],
  ["exciting", "adj", "heyecan verici", "The match was really exciting.", "Maç gerçekten heyecanlıydı."],

  // Set 33 — Adverbs
  ["quickly", "adv", "hızlıca", "He finished his lunch quickly.", "Öğle yemeğini hızlıca bitirdi."],
  ["slowly", "adv", "yavaşça", "Please speak slowly.", "Lütfen yavaş konuşun."],
  ["carefully", "adv", "dikkatlice", "Read the questions carefully.", "Soruları dikkatlice oku."],
  ["easily", "adv", "kolayca", "She won the race easily.", "Yarışı kolayca kazandı."],
  ["suddenly", "adv", "aniden", "Suddenly the lights went out.", "Aniden ışıklar söndü."],
  ["finally", "adv", "sonunda", "We finally arrived at midnight.", "Sonunda gece yarısı vardık."],
  ["probably", "adv", "muhtemelen", "It will probably rain tomorrow.", "Yarın muhtemelen yağmur yağacak."],
  ["perhaps", "adv", "belki", "Perhaps she's still at work.", "Belki hâlâ iştedir."],
  ["almost", "adv", "neredeyse", "I've almost finished.", "Neredeyse bitirdim."],
  ["exactly", "adv", "tam olarak", "That's exactly what I wanted.", "Tam olarak istediğim buydu."],
  ["quite", "adv", "oldukça", "The test was quite easy.", "Test oldukça kolaydı."],
  ["pretty", "adv", "epey, oldukça", "It's pretty cold today.", "Bugün hava epey soğuk."],
  ["hardly", "adv", "neredeyse hiç", "I could hardly hear him.", "Onu neredeyse hiç duyamıyordum.", "“hard” (sıkı sıkı) ile karıştırma."],
  ["even", "adv", "bile", "Even my grandmother uses a smartphone.", "Büyükannem bile akıllı telefon kullanıyor."],
  ["anyway", "adv", "neyse, yine de", "Anyway, let's talk about something else.", "Neyse, başka bir şeyden bahsedelim."],
  ["especially", "adv", "özellikle", "I love fruit, especially cherries.", "Meyveyi severim, özellikle kirazı."],
  ["immediately", "adv", "hemen", "Call me immediately.", "Beni hemen ara."],
  ["recently", "adv", "son zamanlarda", "Have you seen any good films recently?", "Son zamanlarda iyi bir film izledin mi?"],
  ["nearly", "adv", "neredeyse", "It's nearly midnight.", "Neredeyse gece yarısı."],
  ["outdoors", "adv", "açık havada", "We eat outdoors in summer.", "Yazın açık havada yemek yeriz."],

  // Set 34 — Time
  ["century", "n", "yüzyıl", "The mosque was built in the 16th century.", "Cami 16. yüzyılda yapıldı."],
  ["decade", "n", "on yıl", "Prices have doubled in a decade.", "Fiyatlar on yılda iki katına çıktı."],
  ["future", "n", "gelecek", "What are your plans for the future?", "Gelecek için planların neler?"],
  ["past", "n", "geçmiş", "Don't worry about the past.", "Geçmişi dert etme."],
  ["present", "n", "şimdiki zaman", "Live in the present.", "Anı yaşa."],
  ["moment", "n", "an", "Wait a moment, please.", "Bir dakika bekleyin, lütfen."],
  ["period", "n", "dönem, süre", "It was a difficult period in my life.", "Hayatımda zor bir dönemdi."],
  ["midnight", "n", "gece yarısı", "The party ended at midnight.", "Parti gece yarısı bitti."],
  ["midday", "n", "öğle vakti", "We stopped for lunch at midday.", "Öğle vakti yemek için durduk."],
  ["sunrise", "n", "gün doğumu", "We watched the sunrise from the hill.", "Tepeden gün doğumunu izledik."],
  ["sunset", "n", "gün batımı", "The sunset was beautiful.", "Gün batımı çok güzeldi."],
  ["daily", "adj", "günlük", "Exercise is part of my daily routine.", "Egzersiz günlük rutinimin bir parçası."],
  ["weekly", "adj", "haftalık", "We have a weekly meeting.", "Haftalık bir toplantımız var."],
  ["monthly", "adj", "aylık", "My monthly rent is too high.", "Aylık kiram çok yüksek."],
  ["yearly", "adj", "yıllık", "The festival is a yearly event.", "Festival yıllık bir etkinlik."],
  ["lately", "adv", "son günlerde", "I've been very tired lately.", "Son günlerde çok yorgunum."],
  ["nowadays", "adv", "günümüzde", "Nowadays everyone has a phone.", "Günümüzde herkesin telefonu var."],
  ["at the moment", "phr", "şu anda", "I'm busy at the moment.", "Şu anda meşgulüm."],
  ["on time", "phr", "tam zamanında", "The train arrived on time.", "Tren tam zamanında geldi."],
  ["in time", "phr", "zamanında, vaktinde", "We got there just in time.", "Oraya tam vaktinde yetiştik."],

  // Set 35 — Amounts & containers
  ["amount", "n", "miktar", "Add a small amount of sugar.", "Az miktarda şeker ekle."],
  ["quantity", "n", "miktar, adet", "We ordered a large quantity of paper.", "Çok miktarda kağıt sipariş ettik."],
  ["pair", "n", "çift", "I bought a pair of shoes.", "Bir çift ayakkabı aldım."],
  ["dozen", "n", "düzine", "I bought a dozen eggs.", "Bir düzine yumurta aldım."],
  ["packet", "n", "paket", "A packet of biscuits, please.", "Bir paket bisküvi, lütfen."],
  ["can", "n", "kutu (teneke)", "Can I have a can of lemonade?", "Bir kutu limonata alabilir miyim?"],
  ["jar", "n", "kavanoz", "Pass me the jar of honey.", "Bal kavanozunu uzat."],
  ["carton", "n", "karton kutu", "A carton of milk, please.", "Bir kutu süt, lütfen."],
  ["tin", "n", "konserve kutusu", "Open a tin of tomatoes.", "Bir kutu domates konservesi aç."],
  ["loaf", "n", "somun", "Buy a loaf of bread.", "Bir somun ekmek al.", "Çoğulu: loaves."],
  ["bar", "n", "kalıp, tablet", "I ate a bar of chocolate.", "Bir tablet çikolata yedim."],
  ["tube", "n", "tüp", "I need a new tube of toothpaste.", "Yeni bir tüp diş macununa ihtiyacım var."],
  ["bunch", "n", "demet, salkım", "She bought a bunch of flowers.", "Bir demet çiçek aldı."],
  ["plenty", "pron", "bol, bolca", "Don't worry, we have plenty of time.", "Merak etme, bolca vaktimiz var."],
  ["a few", "det", "birkaç", "I have a few questions.", "Birkaç sorum var.", "Sayılabilen isimlerle kullanılır."],
  ["a little", "det", "biraz", "Add a little milk.", "Biraz süt ekle.", "Sayılamayan isimlerle kullanılır."],
  ["several", "det", "birkaç, çeşitli", "I've been there several times.", "Oraya birkaç kez gittim."],
  ["most", "det", "çoğu", "Most students passed the exam.", "Öğrencilerin çoğu sınavı geçti."],
  ["none", "pron", "hiçbiri", "None of my friends came.", "Arkadaşlarımın hiçbiri gelmedi."],
  ["total", "n", "toplam", "The total is 250 lira.", "Toplam 250 lira."],
];
