import type { LexiconEntry } from "../types";

/** A2 sets 1–5: personality, appearance, relationships, housework, cooking. */
export const A2_PART1: LexiconEntry[] = [
  // Set 1 — Personality
  ["personality", "n", "kişilik", "She has a strong personality.", "Güçlü bir kişiliği var."],
  ["honest", "adj", "dürüst", "He is an honest man.", "O dürüst bir adam.", "“h” okunmaz: /ˈɒnɪst/."],
  ["shy", "adj", "utangaç", "She's shy with new people.", "Yeni insanlarla utangaçtır."],
  ["confident", "adj", "kendinden emin", "He looks confident on stage.", "Sahnede kendinden emin görünüyor."],
  ["generous", "adj", "cömert", "My uncle is very generous.", "Amcam çok cömerttir."],
  ["selfish", "adj", "bencil", "Don't be selfish, share it.", "Bencil olma, paylaş."],
  ["patient", "adj", "sabırlı", "A good teacher is patient.", "İyi bir öğretmen sabırlıdır.", "İsim olarak “hasta” demektir."],
  ["rude", "adj", "kaba", "It's rude to talk with your mouth full.", "Ağzın doluyken konuşmak kabalıktır."],
  ["cheerful", "adj", "neşeli", "She's always cheerful in the morning.", "Sabahları hep neşelidir."],
  ["careful", "adj", "dikkatli", "Be careful with the knife.", "Bıçakla dikkatli ol."],
  ["careless", "adj", "dikkatsiz", "He made a careless mistake.", "Dikkatsiz bir hata yaptı."],
  ["hard-working", "adj", "çalışkan", "Our students are hard-working.", "Öğrencilerimiz çalışkan."],
  ["brave", "adj", "cesur", "The firefighter was very brave.", "İtfaiyeci çok cesurdu."],
  ["calm", "adj", "sakin", "Stay calm and listen.", "Sakin ol ve dinle."],
  ["serious", "adj", "ciddi", "Is he serious or joking?", "Ciddi mi, şaka mı yapıyor?"],
  ["sensible", "adj", "mantıklı, aklı başında", "That's a sensible idea.", "Bu mantıklı bir fikir.", "“sensitive” (hassas) ile karıştırma."],
  ["sensitive", "adj", "hassas, duyarlı", "He is sensitive to criticism.", "Eleştiriye karşı hassastır."],
  ["reliable", "adj", "güvenilir", "She's a reliable friend.", "O güvenilir bir arkadaş."],
  ["mean", "adj", "cimri; kötü kalpli", "Don't be mean to your brother.", "Kardeşine kötü davranma."],
  ["character", "n", "karakter", "The main character is a young girl.", "Ana karakter genç bir kız."],

  // Set 2 — Appearance
  ["appearance", "n", "dış görünüş", "Don't judge people by their appearance.", "İnsanları dış görünüşlerine göre yargılama."],
  ["attractive", "adj", "çekici", "She's an attractive woman.", "Çekici bir kadın."],
  ["ugly", "adj", "çirkin", "What an ugly building!", "Ne çirkin bir bina!"],
  ["slim", "adj", "ince, zayıf (olumlu)", "She keeps slim by running.", "Koşarak formda kalıyor."],
  ["overweight", "adj", "kilolu", "The doctor says I'm overweight.", "Doktor kilolu olduğumu söylüyor."],
  ["medium", "adj", "orta", "He's of medium height.", "Orta boylu."],
  ["height", "n", "boy, yükseklik", "What's your height?", "Boyun kaç?"],
  ["weight", "n", "kilo, ağırlık", "I want to lose weight.", "Kilo vermek istiyorum."],
  ["straight", "adj", "düz", "She has long straight hair.", "Uzun düz saçları var."],
  ["bald", "adj", "kel", "My grandfather is bald.", "Dedem kel."],
  ["moustache", "n", "bıyık", "He has a black moustache.", "Siyah bir bıyığı var."],
  ["skin", "n", "cilt, deri", "She has dark skin.", "Esmer tenli."],
  ["freckles", "n", "çil", "He has freckles on his nose.", "Burnunda çiller var."],
  ["smart", "adj", "şık; zeki", "You look smart in that suit.", "O takım elbiseyle çok şık görünüyorsun."],
  ["elegant", "adj", "zarif", "She wore an elegant black dress.", "Zarif siyah bir elbise giydi."],
  ["cute", "adj", "tatlı, sevimli", "What a cute baby!", "Ne tatlı bir bebek!"],
  ["good-looking", "adj", "yakışıklı, güzel", "He's a good-looking young man.", "Yakışıklı bir genç adam."],
  ["wavy", "adj", "dalgalı", "Her hair is brown and wavy.", "Saçı kahverengi ve dalgalı."],
  ["tattoo", "n", "dövme", "He has a tattoo on his arm.", "Kolunda bir dövme var."],
  ["describe", "v", "tarif etmek, betimlemek", "Can you describe the man?", "Adamı tarif edebilir misin?"],

  // Set 3 — Relationships
  ["relationship", "n", "ilişki", "They have a good relationship.", "İyi bir ilişkileri var."],
  ["relative", "n", "akraba", "All my relatives came to the wedding.", "Tüm akrabalarım düğüne geldi."],
  ["partner", "n", "partner, eş", "She lives with her partner.", "Partneriyle yaşıyor."],
  ["boyfriend", "n", "erkek arkadaş (sevgili)", "Her boyfriend is from Spain.", "Erkek arkadaşı İspanyol."],
  ["girlfriend", "n", "kız arkadaş (sevgili)", "He met his girlfriend at university.", "Kız arkadaşıyla üniversitede tanıştı."],
  ["married", "adj", "evli", "Are you married?", "Evli misin?"],
  ["single", "adj", "bekâr; tek", "He's still single.", "Hâlâ bekâr."],
  ["divorced", "adj", "boşanmış", "Her parents are divorced.", "Anne ve babası boşanmış."],
  ["marry", "v", "evlenmek", "He wants to marry her.", "Onunla evlenmek istiyor."],
  ["get married", "phr", "evlenmek", "They got married last year.", "Geçen yıl evlendiler."],
  ["couple", "n", "çift", "They are a happy couple.", "Mutlu bir çiftler."],
  ["twin", "n", "ikiz", "I have a twin sister.", "İkiz kız kardeşim var."],
  ["grandchild", "n", "torun", "She has five grandchildren.", "Beş torunu var."],
  ["nephew", "n", "yeğen (erkek)", "My nephew is starting school.", "Yeğenim okula başlıyor."],
  ["niece", "n", "yeğen (kız)", "My niece loves drawing.", "Yeğenim resim yapmaya bayılır."],
  ["colleague", "n", "iş arkadaşı", "I had lunch with a colleague.", "Bir iş arkadaşımla öğle yemeği yedim."],
  ["classmate", "n", "sınıf arkadaşı", "She was my classmate at school.", "Okulda sınıf arkadaşımdı."],
  ["get on (with)", "pv", "iyi geçinmek", "I get on well with my sister.", "Kız kardeşimle iyi geçiniyorum."],
  ["trust", "v", "güvenmek", "I trust my best friend.", "En iyi arkadaşıma güvenirim."],
  ["argue", "v", "tartışmak, atışmak", "My brothers argue about everything.", "Kardeşlerim her şey hakkında tartışır."],

  // Set 4 — Housework
  ["housework", "n", "ev işi", "We share the housework.", "Ev işlerini paylaşırız.", "Sayılamaz: “a lot of housework”."],
  ["chore", "n", "angarya, ev işi", "Washing up is my least favourite chore.", "Bulaşık yıkamak en sevmediğim ev işi."],
  ["do the washing-up", "phr", "bulaşık yıkamak", "I'll do the washing-up after dinner.", "Akşam yemeğinden sonra bulaşıkları yıkarım."],
  ["do the laundry", "phr", "çamaşır yıkamak", "I do the laundry on Sundays.", "Pazarları çamaşır yıkarım."],
  ["iron", "v", "ütülemek", "Can you iron my shirt?", "Gömleğimi ütüleyebilir misin?"],
  ["vacuum", "v", "elektrik süpürgesiyle süpürmek", "I vacuum the carpet every week.", "Halıyı her hafta süpürürüm."],
  ["sweep", "v", "(süpürgeyle) süpürmek", "Sweep the kitchen floor.", "Mutfak zeminini süpür."],
  ["dust", "v", "toz almak", "She dusts the shelves on Fridays.", "Cumaları rafların tozunu alır."],
  ["tidy up", "pv", "toparlamak", "Tidy up your room, please.", "Odanı topla, lütfen."],
  ["rubbish", "n", "çöp", "Take out the rubbish.", "Çöpü dışarı çıkar.", "Amerikan İngilizcesinde “trash/garbage”."],
  ["bin", "n", "çöp kutusu", "Put it in the bin.", "Onu çöp kutusuna at."],
  ["washing machine", "n", "çamaşır makinesi", "The washing machine is broken.", "Çamaşır makinesi bozuk."],
  ["dishwasher", "n", "bulaşık makinesi", "Put the plates in the dishwasher.", "Tabakları bulaşık makinesine koy."],
  ["carpet", "n", "halı", "There's a red carpet in the hall.", "Holde kırmızı bir halı var."],
  ["curtain", "n", "perde", "Close the curtains, please.", "Perdeleri kapat, lütfen."],
  ["cupboard", "n", "dolap (mutfak)", "The cups are in the cupboard.", "Fincanlar dolapta.", "“p” okunmaz: /ˈkʌbəd/."],
  ["drawer", "n", "çekmece", "The spoons are in the top drawer.", "Kaşıklar üst çekmecede."],
  ["pillow", "n", "yastık", "I need a soft pillow.", "Yumuşak bir yastığa ihtiyacım var."],
  ["blanket", "n", "battaniye", "Can I have another blanket?", "Bir battaniye daha alabilir miyim?"],
  ["mess", "n", "dağınıklık", "Your room is a mess!", "Odan darmadağın!"],

  // Set 5 — Cooking
  ["ingredient", "n", "malzeme (yemek)", "We need five ingredients for this cake.", "Bu kek için beş malzemeye ihtiyacımız var."],
  ["bake", "v", "fırında pişirmek", "My mum bakes bread every weekend.", "Annem her hafta sonu ekmek pişirir."],
  ["roast", "v", "kızartmak (fırında), kavurmak", "We roast chicken on Sundays.", "Pazarları fırında tavuk yaparız."],
  ["grill", "v", "ızgara yapmak", "Let's grill some fish.", "Biraz balık ızgara yapalım."],
  ["heat", "v", "ısıtmak", "Heat the milk slowly.", "Sütü yavaşça ısıt."],
  ["pour", "v", "dökmek", "Pour the water into the pot.", "Suyu tencereye dök."],
  ["add", "v", "eklemek", "Add a little salt.", "Biraz tuz ekle."],
  ["slice", "n", "dilim", "Can I have a slice of bread?", "Bir dilim ekmek alabilir miyim?"],
  ["peel", "v", "soymak", "Peel the potatoes first.", "Önce patatesleri soy."],
  ["chop", "v", "doğramak", "Chop the onions finely.", "Soğanları ince doğra."],
  ["pot", "n", "tencere; kavanoz", "Put the rice in a big pot.", "Pirinci büyük bir tencereye koy."],
  ["raw", "adj", "çiğ", "You can eat carrots raw.", "Havucu çiğ yiyebilirsin."],
  ["spicy", "adj", "baharatlı, acı", "I love spicy food.", "Acılı yemeklere bayılırım."],
  ["sour", "adj", "ekşi", "Lemons are sour.", "Limonlar ekşidir."],
  ["bitter", "adj", "acı (tat)", "This coffee is too bitter.", "Bu kahve çok acı."],
  ["salty", "adj", "tuzlu", "The soup is too salty.", "Çorba çok tuzlu."],
  ["garlic", "n", "sarımsak", "Add two cloves of garlic.", "İki diş sarımsak ekle."],
  ["mushroom", "n", "mantar", "I don't like mushrooms on pizza.", "Pizzada mantar sevmem."],
  ["cucumber", "n", "salatalık", "Cut the cucumber into slices.", "Salatalığı dilimle."],
  ["dessert", "n", "tatlı (yemek sonrası)", "What's for dessert?", "Tatlı olarak ne var?", "“desert” (çöl) ile karıştırma."],
];
