import type { LexiconEntry } from "../types";

/** A2 sets 36–40: materials, celebrations, safety & crime, the world, science. */
export const A2_PART8: LexiconEntry[] = [
  // Set 36 — Materials & objects
  ["material", "n", "malzeme, kumaş", "What material is this bag made of?", "Bu çanta hangi malzemeden yapılmış?"],
  ["metal", "n", "metal", "The chair is made of metal.", "Sandalye metalden yapılmış."],
  ["wood", "n", "tahta, ahşap", "The table is made of wood.", "Masa ahşaptan yapılmış."],
  ["wooden", "adj", "ahşap", "We have wooden floors.", "Ahşap zeminlerimiz var."],
  ["gold", "n", "altın", "Her ring is made of gold.", "Yüzüğü altından."],
  ["silver", "n", "gümüş", "He won a silver medal.", "Gümüş madalya kazandı."],
  ["steel", "n", "çelik", "The bridge is made of steel.", "Köprü çelikten yapılmış."],
  ["rubber", "n", "kauçuk, lastik", "Tyres are made of rubber.", "Lastikler kauçuktan yapılır."],
  ["silk", "n", "ipek", "Bursa is famous for silk.", "Bursa ipeğiyle ünlüdür."],
  ["brick", "n", "tuğla", "The house is built of red brick.", "Ev kırmızı tuğladan yapılmış."],
  ["shape", "n", "şekil", "What shape is it?", "Ne şekilde?"],
  ["triangle", "n", "üçgen", "Draw a triangle.", "Bir üçgen çiz."],
  ["rectangle", "n", "dikdörtgen", "The table is a rectangle.", "Masa dikdörtgen şeklinde."],
  ["tool", "n", "alet", "You need the right tools for the job.", "İş için doğru aletlere ihtiyacın var."],
  ["hammer", "n", "çekiç", "Hand me the hammer.", "Çekici bana ver."],
  ["rope", "n", "ip, halat", "Tie the boat with a rope.", "Tekneyi halatla bağla."],
  ["object", "n", "nesne", "There's a strange object in the sky.", "Gökyüzünde garip bir nesne var."],
  ["item", "n", "parça, ürün", "Each item costs ten lira.", "Her ürün on lira."],
  ["container", "n", "kap, konteyner", "Keep the food in a plastic container.", "Yiyeceği plastik bir kapta sakla."],
  ["made of", "phr", "-den yapılmış", "This bag is made of leather.", "Bu çanta deriden yapılmış."],

  // Set 37 — Celebrations
  ["anniversary", "n", "yıl dönümü", "It's our wedding anniversary today.", "Bugün evlilik yıl dönümümüz."],
  ["ceremony", "n", "tören", "The graduation ceremony was long.", "Mezuniyet töreni uzundu."],
  ["congratulations", "int", "tebrikler", "Congratulations on your new job!", "Yeni işin için tebrikler!"],
  ["decorate", "v", "süslemek", "We decorated the room with balloons.", "Odayı balonlarla süsledik."],
  ["decoration", "n", "süsleme", "The decorations look beautiful.", "Süslemeler çok güzel görünüyor."],
  ["fireworks", "n", "havai fişek", "We watched the fireworks at midnight.", "Gece yarısı havai fişekleri izledik."],
  ["invitation", "n", "davetiye, davet", "Thank you for the invitation.", "Davetin için teşekkürler."],
  ["host", "n", "ev sahibi", "The host welcomed us at the door.", "Ev sahibi bizi kapıda karşıladı."],
  ["costume", "n", "kostüm", "She wore a pirate costume.", "Korsan kostümü giydi."],
  ["tradition", "n", "gelenek", "It's a family tradition.", "Bu bir aile geleneği."],
  ["traditional", "adj", "geleneksel", "We ate traditional Turkish food.", "Geleneksel Türk yemekleri yedik."],
  ["national", "adj", "ulusal, milli", "April 23 is a national holiday.", "23 Nisan milli bir bayramdır."],
  ["religious", "adj", "dini", "Bayram is a religious holiday.", "Bayram dini bir tatildir."],
  ["celebration", "n", "kutlama", "There was a big celebration after the match.", "Maçtan sonra büyük bir kutlama vardı."],
  ["surprise", "n", "sürpriz", "We planned a surprise party for her.", "Onun için bir sürpriz parti planladık."],
  ["wrap", "v", "paketlemek", "I wrapped the present in red paper.", "Hediyeyi kırmızı kağıda sardım."],
  ["toast", "n", "kadeh kaldırma; kızarmış ekmek", "Let's make a toast to the couple.", "Çiftin şerefine kadeh kaldıralım."],
  ["event", "n", "etkinlik, olay", "The event starts at seven.", "Etkinlik yedide başlıyor."],
  ["parade", "n", "geçit töreni", "There's a parade on Republic Day.", "Cumhuriyet Bayramı'nda geçit töreni var."],
  ["gather", "v", "toplanmak", "The family gathers at Grandma's house.", "Aile büyükannemin evinde toplanır."],

  // Set 38 — Safety & crime
  ["crime", "n", "suç", "Crime is low in this town.", "Bu kasabada suç oranı düşük."],
  ["criminal", "n", "suçlu", "The police caught the criminal.", "Polis suçluyu yakaladı."],
  ["thief", "n", "hırsız", "A thief stole my bag.", "Bir hırsız çantamı çaldı.", "Çoğulu: thieves."],
  ["steal", "v", "çalmak", "Someone stole my bike.", "Biri bisikletimi çaldı."],
  ["rob", "v", "soymak", "Two men robbed the bank.", "İki adam bankayı soydu.", "Kişiyi/yeri “rob”, eşyayı “steal”."],
  ["police station", "n", "karakol", "Report it at the police station.", "Karakola bildir."],
  ["arrest", "v", "tutuklamak", "The police arrested him yesterday.", "Polis dün onu tutukladı."],
  ["prison", "n", "hapishane", "He spent two years in prison.", "İki yıl hapiste kaldı."],
  ["law", "n", "yasa, kanun", "It's against the law.", "Bu yasaya aykırı."],
  ["judge", "n", "hâkim", "The judge listened to both sides.", "Hâkim iki tarafı da dinledi."],
  ["witness", "n", "tanık", "Were there any witnesses?", "Tanık var mıydı?"],
  ["safety", "n", "güvenlik", "Safety is our first priority.", "Güvenlik önceliğimizdir."],
  ["danger", "n", "tehlike", "The sign says 'Danger'.", "Tabelada 'Tehlike' yazıyor."],
  ["warning", "n", "uyarı", "Read the warning on the box.", "Kutunun üzerindeki uyarıyı oku."],
  ["lock", "v", "kilitlemek", "Did you lock the door?", "Kapıyı kilitledin mi?"],
  ["alarm", "n", "alarm", "The car alarm went off.", "Araba alarmı çaldı."],
  ["firefighter", "n", "itfaiyeci", "Firefighters put out the fire.", "İtfaiyeciler yangını söndürdü."],
  ["rescue", "v", "kurtarmak", "They rescued a cat from the tree.", "Ağaçtan bir kedi kurtardılar."],
  ["help", "int", "imdat", "Help! Somebody call the police!", "İmdat! Biri polisi arasın!"],
  ["dial", "v", "numara çevirmek", "Dial 112 for an ambulance.", "Ambulans için 112'yi arayın."],

  // Set 39 — The world
  ["continent", "n", "kıta", "Asia is the largest continent.", "Asya en büyük kıtadır."],
  ["Asia", "n", "Asya", "Turkey is in Europe and Asia.", "Türkiye Avrupa ve Asya'dadır."],
  ["Africa", "n", "Afrika", "Egypt is in Africa.", "Mısır Afrika'dadır."],
  ["border", "n", "sınır", "We crossed the border into Greece.", "Sınırı geçip Yunanistan'a girdik."],
  ["population", "n", "nüfus", "Istanbul has a population of 15 million.", "İstanbul'un nüfusu 15 milyon."],
  ["citizen", "n", "vatandaş", "She's a Turkish citizen.", "O bir Türk vatandaşı."],
  ["government", "n", "hükümet", "The government announced new rules.", "Hükümet yeni kurallar açıkladı."],
  ["president", "n", "cumhurbaşkanı, başkan", "The president gave a speech.", "Cumhurbaşkanı bir konuşma yaptı."],
  ["king", "n", "kral", "The king lived in a palace.", "Kral bir sarayda yaşıyordu."],
  ["queen", "n", "kraliçe", "The queen visited the city.", "Kraliçe şehri ziyaret etti."],
  ["palace", "n", "saray", "We visited Topkapı Palace.", "Topkapı Sarayı'nı gezdik."],
  ["castle", "n", "kale", "There's an old castle on the hill.", "Tepede eski bir kale var."],
  ["region", "n", "bölge", "The Black Sea region is very green.", "Karadeniz bölgesi çok yeşildir."],
  ["international", "adj", "uluslararası", "It's an international school.", "Uluslararası bir okul."],
  ["worldwide", "adj", "dünya çapında", "The film was a worldwide success.", "Film dünya çapında başarı kazandı."],
  ["Spain", "n", "İspanya", "They spent their holiday in Spain.", "Tatillerini İspanya'da geçirdiler."],
  ["Italy", "n", "İtalya", "Rome is the capital of Italy.", "Roma İtalya'nın başkentidir."],
  ["Greece", "n", "Yunanistan", "Greece is our neighbour.", "Yunanistan komşumuzdur."],
  ["Russia", "n", "Rusya", "Russia is a very big country.", "Rusya çok büyük bir ülke."],
  ["China", "n", "Çin", "China has a huge population.", "Çin'in çok büyük bir nüfusu var."],

  // Set 40 — Science
  ["scientist", "n", "bilim insanı", "She wants to be a scientist.", "Bilim insanı olmak istiyor."],
  ["experiment", "n", "deney", "We did an experiment in class.", "Sınıfta bir deney yaptık."],
  ["laboratory", "n", "laboratuvar", "The students work in the laboratory.", "Öğrenciler laboratuvarda çalışıyor.", "Kısaltması: lab."],
  ["research", "n", "araştırma", "He does research on cancer.", "Kanser üzerine araştırma yapıyor.", "Sayılamaz."],
  ["discover", "v", "keşfetmek", "Who discovered penicillin?", "Penisilini kim keşfetti?"],
  ["invent", "v", "icat etmek", "Who invented the telephone?", "Telefonu kim icat etti?"],
  ["invention", "n", "icat", "The internet is a great invention.", "İnternet harika bir icat."],
  ["chemistry", "n", "kimya", "Chemistry is my favourite subject.", "Kimya en sevdiğim ders."],
  ["physics", "n", "fizik", "Physics explains how things move.", "Fizik şeylerin nasıl hareket ettiğini açıklar.", "Sonu -s ile bitse de tekildir."],
  ["biology", "n", "biyoloji", "In biology we study living things.", "Biyolojide canlıları inceleriz."],
  ["space", "n", "uzay; yer", "Astronauts travel into space.", "Astronotlar uzaya gider."],
  ["astronaut", "n", "astronot", "The astronaut stayed in space for six months.", "Astronot altı ay uzayda kaldı."],
  ["robot", "n", "robot", "Robots can build cars.", "Robotlar araba yapabilir."],
  ["machine", "n", "makine", "This machine makes coffee.", "Bu makine kahve yapıyor."],
  ["electricity", "n", "elektrik", "The storm cut the electricity.", "Fırtına elektriği kesti."],
  ["gas", "n", "gaz", "We cook with gas.", "Gazla yemek pişiririz."],
  ["measure", "v", "ölçmek", "Measure the length of the table.", "Masanın uzunluğunu ölç."],
  ["result", "n", "sonuç", "The results of the test are good.", "Testin sonuçları iyi."],
  ["prove", "v", "kanıtlamak", "Can you prove it?", "Bunu kanıtlayabilir misin?"],
  ["gravity", "n", "yer çekimi", "Gravity makes things fall.", "Yer çekimi nesnelerin düşmesini sağlar."],
];
