import type { LexiconEntry } from "../types";

/** A2 sets 11–15: holidays, getting around, directions, weather & landscape, animals. */
export const A2_PART3: LexiconEntry[] = [
  // Set 11 — Holidays
  ["abroad", "adv", "yurt dışında, yurt dışına", "I'd like to study abroad.", "Yurt dışında okumak istiyorum."],
  ["tourist", "n", "turist", "Istanbul is full of tourists in summer.", "İstanbul yazın turist dolu."],
  ["sightseeing", "n", "gezip görme", "We went sightseeing in Rome.", "Roma'da gezip dolaştık."],
  ["guide", "n", "rehber", "Our guide spoke three languages.", "Rehberimiz üç dil konuşuyordu."],
  ["guidebook", "n", "gezi rehberi (kitap)", "I bought a guidebook to Cappadocia.", "Kapadokya için bir gezi rehberi aldım."],
  ["souvenir", "n", "hediyelik eşya", "I bought a souvenir for my mother.", "Anneme bir hediyelik eşya aldım."],
  ["luggage", "n", "bagaj, bavullar", "How much luggage do you have?", "Ne kadar bagajınız var?", "Sayılamaz: “a piece of luggage”."],
  ["pack", "v", "bavul hazırlamak", "Have you packed yet?", "Bavulunu hazırladın mı?"],
  ["unpack", "v", "bavulu boşaltmak", "I unpacked as soon as I arrived.", "Varır varmaz bavulumu boşalttım."],
  ["tent", "n", "çadır", "We slept in a tent by the lake.", "Göl kenarında çadırda uyuduk."],
  ["camping", "n", "kamp", "We go camping every summer.", "Her yaz kampa gideriz."],
  ["resort", "n", "tatil köyü", "They stayed at a beach resort.", "Bir sahil tatil köyünde kaldılar."],
  ["cruise", "n", "gemi turu", "My parents went on a cruise.", "Annemler bir gemi turuna çıktı."],
  ["tour", "n", "tur", "We took a boat tour of the Bosphorus.", "Boğaz'da tekne turu yaptık."],
  ["journey", "n", "yolculuk", "The journey takes six hours.", "Yolculuk altı saat sürüyor."],
  ["destination", "n", "varış yeri, gidilecek yer", "Antalya is a popular destination.", "Antalya popüler bir tatil yeri."],
  ["view", "n", "manzara", "The room has a sea view.", "Odanın deniz manzarası var."],
  ["sunbathe", "v", "güneşlenmek", "We sunbathed on the beach all day.", "Bütün gün plajda güneşlendik."],
  ["relaxing", "adj", "rahatlatıcı", "It was a very relaxing holiday.", "Çok rahatlatıcı bir tatildi."],
  ["crowded", "adj", "kalabalık", "The beach was really crowded.", "Plaj gerçekten kalabalıktı."],

  // Set 12 — Getting around
  ["transport", "n", "ulaşım", "Public transport is cheap here.", "Burada toplu taşıma ucuz."],
  ["public transport", "n", "toplu taşıma", "I use public transport every day.", "Her gün toplu taşıma kullanırım."],
  ["underground", "n", "metro", "Take the underground to the centre.", "Merkeze metroyla git.", "Amerikan İngilizcesinde “subway”."],
  ["tram", "n", "tramvay", "The tram goes along the coast.", "Tramvay sahil boyunca gidiyor."],
  ["ferry", "n", "vapur, feribot", "We took the ferry to Kadıköy.", "Kadıköy'e vapurla geçtik."],
  ["motorbike", "n", "motosiklet", "He rides a motorbike to work.", "İşe motosikletle gidiyor."],
  ["lorry", "n", "kamyon", "A lorry blocked the road.", "Bir kamyon yolu kapattı.", "Amerikan İngilizcesinde “truck”."],
  ["platform", "n", "peron", "The train leaves from platform 3.", "Tren 3. perondan kalkıyor."],
  ["return ticket", "n", "gidiş-dönüş bileti", "A return ticket to Izmir, please.", "İzmir'e gidiş-dönüş bileti, lütfen."],
  ["single ticket", "n", "tek yön bileti", "A single ticket costs twenty lira.", "Tek yön bilet yirmi lira."],
  ["fare", "n", "ücret (yol)", "The bus fare went up again.", "Otobüs ücreti yine arttı."],
  ["route", "n", "güzergâh, rota", "Which route does this bus take?", "Bu otobüs hangi güzergâhı izliyor?"],
  ["delay", "n", "gecikme", "There's a thirty-minute delay.", "Otuz dakikalık bir gecikme var."],
  ["miss", "v", "kaçırmak", "Hurry, or we'll miss the bus!", "Acele et, yoksa otobüsü kaçıracağız!"],
  ["get on", "pv", "binmek (araç)", "Get on the bus at the front.", "Otobüse ön kapıdan bin."],
  ["get off", "pv", "inmek (araç)", "Get off at the third stop.", "Üçüncü durakta in."],
  ["traffic", "n", "trafik", "The traffic is terrible in the morning.", "Sabahları trafik berbat."],
  ["traffic lights", "n", "trafik ışıkları", "Turn right at the traffic lights.", "Trafik ışıklarından sağa dön."],
  ["petrol", "n", "benzin", "We need to stop for petrol.", "Benzin almak için durmamız lazım.", "Amerikan İngilizcesinde “gas”."],
  ["parking", "n", "park yeri, park etme", "Is there parking near the hotel?", "Otelin yakınında park yeri var mı?"],

  // Set 13 — Directions & town
  ["direction", "n", "yön", "Are we going in the right direction?", "Doğru yönde mi gidiyoruz?"],
  ["straight on", "adv", "dümdüz", "Go straight on for two minutes.", "İki dakika dümdüz git."],
  ["corner", "n", "köşe", "The café is on the corner.", "Kafe köşede."],
  ["crossroads", "n", "kavşak", "Turn left at the crossroads.", "Kavşaktan sola dön."],
  ["roundabout", "n", "göbek, döner kavşak", "Take the second exit at the roundabout.", "Göbekten ikinci çıkışa gir."],
  ["pavement", "n", "kaldırım", "Walk on the pavement, not the road.", "Yolda değil, kaldırımda yürü.", "Amerikan İngilizcesinde “sidewalk”."],
  ["pedestrian", "n", "yaya", "This street is for pedestrians only.", "Bu sokak sadece yayalar için."],
  ["avenue", "n", "cadde, bulvar", "The shop is on Bağdat Avenue.", "Mağaza Bağdat Caddesi'nde."],
  ["far", "adj", "uzak", "Is the station far from here?", "İstasyon buraya uzak mı?"],
  ["across", "prep", "karşısına, öbür tarafa", "Walk across the bridge.", "Köprünün karşısına yürü."],
  ["along", "prep", "boyunca", "Walk along the river.", "Nehir boyunca yürü."],
  ["past", "prep", "yanından geçerek", "Go past the bank and turn left.", "Bankayı geç ve sola dön."],
  ["towards", "prep", "-e doğru", "He walked towards the door.", "Kapıya doğru yürüdü."],
  ["through", "prep", "içinden, arasından", "The train goes through a tunnel.", "Tren bir tünelden geçiyor."],
  ["lost", "adj", "kaybolmuş", "Excuse me, I'm lost.", "Affedersiniz, kayboldum."],
  ["sign", "n", "tabela, işaret", "Follow the signs to the airport.", "Havalimanı tabelalarını takip et."],
  ["area", "n", "bölge, alan", "It's a quiet area with lots of parks.", "Çok parkı olan sakin bir bölge."],
  ["suburb", "n", "banliyö, şehir dışı semt", "They live in a suburb of Ankara.", "Ankara'nın bir banliyösünde oturuyorlar."],
  ["downtown", "adv", "şehir merkezine/merkezinde", "Let's go downtown tonight.", "Bu akşam merkeze gidelim."],
  ["local", "adj", "yerel", "We ate at a local restaurant.", "Yerel bir restoranda yedik."],

  // Set 14 — Weather & landscape
  ["storm", "n", "fırtına", "The storm closed the airport.", "Fırtına havalimanını kapattı."],
  ["thunder", "n", "gök gürültüsü", "The dog is afraid of thunder.", "Köpek gök gürültüsünden korkuyor."],
  ["lightning", "n", "şimşek, yıldırım", "Lightning hit the tree.", "Ağaca yıldırım düştü."],
  ["fog", "n", "sis", "There's thick fog this morning.", "Bu sabah yoğun sis var."],
  ["foggy", "adj", "sisli", "Drive slowly, it's foggy.", "Yavaş sür, hava sisli."],
  ["windy", "adj", "rüzgarlı", "It's too windy for the beach.", "Plaj için fazla rüzgarlı."],
  ["ice", "n", "buz", "Be careful, there's ice on the road.", "Dikkat et, yolda buz var."],
  ["freezing", "adj", "buz gibi, dondurucu", "It's freezing outside!", "Dışarısı buz gibi!"],
  ["degree", "n", "derece", "It's five degrees today.", "Bugün hava beş derece."],
  ["forecast", "n", "hava tahmini", "The forecast says it will rain.", "Hava tahmini yağmur yağacağını söylüyor."],
  ["shower", "n", "sağanak; duş", "There may be showers in the afternoon.", "Öğleden sonra sağanak olabilir."],
  ["rainbow", "n", "gökkuşağı", "Look, a rainbow!", "Bak, gökkuşağı!"],
  ["valley", "n", "vadi", "The village is in a green valley.", "Köy yeşil bir vadide."],
  ["desert", "n", "çöl", "Camels live in the desert.", "Develer çölde yaşar."],
  ["coast", "n", "kıyı, sahil", "We drove along the coast.", "Sahil boyunca araba sürdük."],
  ["ocean", "n", "okyanus", "The Pacific is the largest ocean.", "Pasifik en büyük okyanustur."],
  ["wave", "n", "dalga", "The waves are very big today.", "Bugün dalgalar çok büyük."],
  ["waterfall", "n", "şelale", "We walked to a beautiful waterfall.", "Güzel bir şelaleye yürüdük."],
  ["cave", "n", "mağara", "They explored an old cave.", "Eski bir mağarayı keşfettiler."],
  ["countryside", "n", "kırsal kesim", "I prefer the countryside to the city.", "Kırsalı şehre tercih ederim."],

  // Set 15 — Animals
  ["wild", "adj", "vahşi, yabani", "Wild animals live in the forest.", "Vahşi hayvanlar ormanda yaşar."],
  ["wolf", "n", "kurt", "The wolf is the national animal of Turkey.", "Kurt, Türkiye'nin milli hayvanıdır.", "Çoğulu: wolves."],
  ["fox", "n", "tilki", "A fox came into the garden.", "Bahçeye bir tilki girdi."],
  ["deer", "n", "geyik", "We saw a deer in the forest.", "Ormanda bir geyik gördük.", "Tekili ve çoğulu aynı: one deer, two deer."],
  ["camel", "n", "deve", "Camels can live without water for days.", "Develer günlerce susuz yaşayabilir."],
  ["giraffe", "n", "zürafa", "Giraffes eat leaves from tall trees.", "Zürafalar uzun ağaçların yapraklarını yer."],
  ["dolphin", "n", "yunus", "We swam with dolphins.", "Yunuslarla yüzdük."],
  ["whale", "n", "balina", "The blue whale is the biggest animal.", "Mavi balina en büyük hayvandır."],
  ["shark", "n", "köpek balığı", "Sharks have sharp teeth.", "Köpek balıklarının keskin dişleri vardır."],
  ["bee", "n", "arı", "Bees make honey.", "Arılar bal yapar."],
  ["butterfly", "n", "kelebek", "A butterfly landed on the flower.", "Bir kelebek çiçeğe kondu."],
  ["spider", "n", "örümcek", "There's a spider in the bath!", "Küvette bir örümcek var!"],
  ["frog", "n", "kurbağa", "Frogs live near water.", "Kurbağalar suya yakın yaşar."],
  ["turtle", "n", "kaplumbağa (deniz)", "Sea turtles lay eggs on İztuzu beach.", "Deniz kaplumbağaları İztuzu'na yumurta bırakır."],
  ["parrot", "n", "papağan", "Our parrot can say hello.", "Papağanımız merhaba diyebiliyor."],
  ["eagle", "n", "kartal", "An eagle flew over the mountain.", "Dağın üzerinden bir kartal uçtu."],
  ["feed", "v", "beslemek, yem vermek", "Don't forget to feed the cat.", "Kediyi beslemeyi unutma."],
  ["tail", "n", "kuyruk", "The dog wagged its tail.", "Köpek kuyruğunu salladı."],
  ["wing", "n", "kanat", "The bird hurt its wing.", "Kuş kanadını incitti."],
  ["farm", "n", "çiftlik", "My uncle has a farm with goats.", "Amcamın keçileri olan bir çiftliği var."],
];
