import type { LexiconEntry } from "../types";

/** A2 sets 41–45: around the house, personal details, hotels, the airport, social life. */
export const A2_PART9: LexiconEntry[] = [
  // Set 41 — Around the house
  ["furniture", "n", "mobilya", "We bought new furniture for the flat.", "Daire için yeni mobilya aldık.", "Sayılamaz: “a piece of furniture”."],
  ["armchair", "n", "koltuk", "Grandpa sleeps in his armchair.", "Dedem koltuğunda uyuyor."],
  ["wardrobe", "n", "gardırop", "Hang your coat in the wardrobe.", "Paltonu gardıroba as."],
  ["bookcase", "n", "kitaplık", "The bookcase is full.", "Kitaplık dolu."],
  ["ceiling", "n", "tavan", "There's a spider on the ceiling.", "Tavanda bir örümcek var."],
  ["balcony", "n", "balkon", "We have breakfast on the balcony.", "Balkonda kahvaltı yaparız."],
  ["garage", "n", "garaj", "The car is in the garage.", "Araba garajda."],
  ["hall", "n", "hol, koridor", "Leave your shoes in the hall.", "Ayakkabılarını holde bırak."],
  ["lift", "n", "asansör", "Take the lift to the fifth floor.", "Beşinci kata asansörle çık.", "Amerikan İngilizcesinde “elevator”."],
  ["heating", "n", "ısıtma, kalorifer", "Turn on the heating, it's cold.", "Kaloriferi aç, hava soğuk."],
  ["socket", "n", "priz", "Plug it into the socket.", "Onu prize tak."],
  ["tap", "n", "musluk", "Turn off the tap.", "Musluğu kapat."],
  ["sink", "n", "lavabo, eviye", "The dishes are in the sink.", "Bulaşıklar evyede."],
  ["bath", "n", "küvet; banyo yapma", "I have a bath every evening.", "Her akşam banyo yaparım."],
  ["toilet", "n", "tuvalet", "Where's the toilet, please?", "Tuvalet nerede, lütfen?"],
  ["hairdryer", "n", "saç kurutma makinesi", "Is there a hairdryer in the room?", "Odada saç kurutma makinesi var mı?"],
  ["light bulb", "n", "ampul", "We need a new light bulb.", "Yeni bir ampule ihtiyacımız var."],
  ["rent", "n", "kira", "The rent is due on the first of the month.", "Kira ayın birinde ödeniyor."],
  ["rent", "v", "kiralamak", "We rent a flat near the university.", "Üniversitenin yakınında bir daire kiralıyoruz."],
  ["landlord", "n", "ev sahibi", "Our landlord is very nice.", "Ev sahibimiz çok iyi biri."],

  // Set 42 — Personal details
  ["surname", "n", "soyadı", "What's your surname?", "Soyadın ne?"],
  ["first name", "n", "ad, isim", "Write your first name here.", "Adını buraya yaz."],
  ["date of birth", "n", "doğum tarihi", "Please write your date of birth.", "Lütfen doğum tarihinizi yazın."],
  ["gender", "n", "cinsiyet", "Tick your gender on the form.", "Formda cinsiyetini işaretle."],
  ["nickname", "n", "lakap", "My nickname at school was Tiny.", "Okuldaki lakabım Minik'ti."],
  ["occupation", "n", "meslek", "What's your occupation?", "Mesleğiniz nedir?"],
  ["postcode", "n", "posta kodu", "What's your postcode?", "Posta kodun ne?"],
  ["mobile", "n", "cep telefonu", "Call me on my mobile.", "Beni cep telefonumdan ara."],
  ["signature", "n", "imza", "We need your signature here.", "Burada imzanıza ihtiyacımız var."],
  ["ID card", "n", "kimlik kartı", "Please show your ID card.", "Lütfen kimlik kartınızı gösterin."],
  ["marital status", "n", "medeni hâl", "Tick your marital status on the form.", "Formda medeni hâlini işaretle."],
  ["born", "adj", "doğmuş", "I was born in 2005.", "2005'te doğdum."],
  ["hometown", "n", "memleket", "My hometown is Rize.", "Memleketim Rize."],
  ["contact", "v", "iletişime geçmek", "Contact us by email.", "Bizimle e-postayla iletişime geçin."],
  ["detail", "n", "ayrıntı", "Send me the details.", "Bana ayrıntıları gönder."],
  ["personal", "adj", "kişisel", "Don't share personal information online.", "İnternette kişisel bilgilerini paylaşma."],
  ["private", "adj", "özel", "This is a private conversation.", "Bu özel bir konuşma."],
  ["tick", "v", "işaretlemek (✓)", "Tick the correct box.", "Doğru kutucuğu işaretle."],
  ["capital letters", "n", "büyük harfler", "Write your name in capital letters.", "Adını büyük harflerle yaz."],
  ["middle name", "n", "göbek adı", "Do you have a middle name?", "Göbek adın var mı?"],

  // Set 43 — Hotels
  ["accommodation", "n", "konaklama", "The price includes accommodation.", "Fiyata konaklama dahil.", "Sayılamaz."],
  ["reception", "n", "resepsiyon", "Leave your key at reception.", "Anahtarını resepsiyona bırak."],
  ["single room", "n", "tek kişilik oda", "I'd like a single room for two nights.", "İki gece için tek kişilik oda istiyorum."],
  ["double room", "n", "çift kişilik oda", "We booked a double room.", "Çift kişilik oda ayırttık."],
  ["vacancy", "n", "boş oda; açık pozisyon", "The sign says No Vacancies.", "Tabelada \"Boş oda yok\" yazıyor."],
  ["fully booked", "adj", "tamamen dolu", "Sorry, we're fully booked.", "Üzgünüz, tamamen doluyuz."],
  ["guest house", "n", "pansiyon", "We stayed in a small guest house.", "Küçük bir pansiyonda kaldık."],
  ["hostel", "n", "hostel", "Hostels are cheap for students.", "Hosteller öğrenciler için ucuzdur."],
  ["facilities", "n", "olanaklar, tesisler", "The hotel has great facilities.", "Otelin harika olanakları var."],
  ["swimming pool", "n", "yüzme havuzu", "Is there a swimming pool?", "Yüzme havuzu var mı?"],
  ["breakfast included", "phr", "kahvaltı dahil", "The price is 1,000 lira, breakfast included.", "Fiyat kahvaltı dahil 1.000 lira."],
  ["room service", "n", "oda servisi", "We ordered room service.", "Oda servisi söyledik."],
  ["key card", "n", "anahtar kart", "My key card doesn't work.", "Anahtar kartım çalışmıyor."],
  ["stay", "n", "konaklama, kalış", "Enjoy your stay!", "İyi konaklamalar!"],
  ["complaint", "n", "şikâyet", "I'd like to make a complaint.", "Şikâyette bulunmak istiyorum."],
  ["noisy", "adj", "gürültülü", "Our room was too noisy.", "Odamız çok gürültülüydü."],
  ["safe", "n", "kasa (oda)", "Keep your passport in the room safe.", "Pasaportunu oda kasasında sakla."],
  ["porter", "n", "bellboy, hamal", "The porter carried our bags.", "Bellboy çantalarımızı taşıdı."],
  ["lobby", "n", "lobi", "Let's meet in the lobby.", "Lobide buluşalım."],
  ["wake-up call", "n", "uyandırma servisi", "I'd like a wake-up call at six.", "Saat altıda uyandırılmak istiyorum."],

  // Set 44 — The airport
  ["flight", "n", "uçuş", "Our flight is at nine.", "Uçuşumuz dokuzda."],
  ["check-in desk", "n", "check-in bankosu", "Go to check-in desk 12.", "12 numaralı check-in bankosuna gidin."],
  ["boarding pass", "n", "biniş kartı", "Show your boarding pass at the gate.", "Kapıda biniş kartınızı gösterin."],
  ["gate", "n", "kapı (havalimanı)", "The flight leaves from gate B7.", "Uçuş B7 kapısından kalkıyor."],
  ["departure", "n", "kalkış", "Departures are on the upper floor.", "Dış hatlar gidiş üst katta."],
  ["arrival", "n", "varış", "Check the arrivals board.", "Geliş tablosuna bak."],
  ["take off", "pv", "havalanmak", "The plane took off on time.", "Uçak zamanında havalandı."],
  ["land", "v", "iniş yapmak", "We landed in Antalya at noon.", "Öğlen Antalya'ya indik."],
  ["passenger", "n", "yolcu", "All passengers must show a passport.", "Tüm yolcular pasaport göstermeli."],
  ["security", "n", "güvenlik", "We waited an hour at security.", "Güvenlikte bir saat bekledik."],
  ["customs", "n", "gümrük", "We went through customs.", "Gümrükten geçtik."],
  ["hand luggage", "n", "el bagajı", "You can take one piece of hand luggage.", "Bir parça el bagajı alabilirsiniz."],
  ["seat belt", "n", "emniyet kemeri", "Fasten your seat belt.", "Emniyet kemerinizi bağlayın."],
  ["aisle", "n", "koridor (uçak)", "I'd like an aisle seat.", "Koridor tarafında bir koltuk istiyorum.", "“s” okunmaz: /aɪl/."],
  ["window seat", "n", "cam kenarı koltuk", "Can I have a window seat?", "Cam kenarı alabilir miyim?"],
  ["cancel", "v", "iptal etmek", "The flight was cancelled because of fog.", "Uçuş sis nedeniyle iptal edildi."],
  ["delayed", "adj", "rötarlı", "Our flight is delayed by two hours.", "Uçuşumuz iki saat rötarlı."],
  ["announcement", "n", "anons, duyuru", "Listen to the announcements.", "Anonsları dinleyin."],
  ["duty-free", "adj", "gümrüksüz", "She bought perfume in the duty-free shop.", "Gümrüksüz mağazadan parfüm aldı."],
  ["jet lag", "n", "saat farkı yorgunluğu", "I had terrible jet lag after New York.", "New York'tan sonra korkunç bir saat farkı yorgunluğu yaşadım."],

  // Set 45 — Social life
  ["social", "adj", "sosyal", "She has a busy social life.", "Yoğun bir sosyal hayatı var."],
  ["invite over", "pv", "eve davet etmek", "Let's invite them over for dinner.", "Onları akşam yemeğine eve çağıralım."],
  ["get together", "pv", "bir araya gelmek", "We get together every Friday.", "Her cuma bir araya geliriz."],
  ["meet up", "pv", "buluşmak", "Let's meet up after work.", "İşten sonra buluşalım."],
  ["make friends", "phr", "arkadaş edinmek", "It's easy to make friends at university.", "Üniversitede arkadaş edinmek kolay."],
  ["stranger", "n", "yabancı (kişi)", "Don't talk to strangers.", "Yabancılarla konuşma."],
  ["neighbourhood", "n", "mahalle, semt", "It's a friendly neighbourhood.", "Samimi bir mahalle."],
  ["community", "n", "topluluk", "The local community helped the family.", "Yerel topluluk aileye yardım etti."],
  ["volunteer", "n", "gönüllü", "She works as a volunteer at the hospital.", "Hastanede gönüllü olarak çalışıyor."],
  ["charity", "n", "yardım kuruluşu, hayır işi", "We gave money to charity.", "Bir yardım kuruluşuna bağış yaptık."],
  ["visitor", "n", "ziyaretçi", "We had visitors at the weekend.", "Hafta sonu misafirlerimiz vardı."],
  ["welcome", "v", "karşılamak, ağırlamak", "They welcomed us warmly.", "Bizi sıcak karşıladılar."],
  ["introduce", "v", "tanıştırmak", "Let me introduce my wife.", "Size eşimi tanıştırayım."],
  ["greet", "v", "selamlamak", "He greeted everyone with a smile.", "Herkesi gülümseyerek selamladı."],
  ["hug", "v", "sarılmak", "She hugged her grandmother.", "Büyükannesine sarıldı."],
  ["shake hands", "phr", "tokalaşmak", "They shook hands after the meeting.", "Toplantıdan sonra tokalaştılar."],
  ["friendship", "n", "arkadaşlık", "Their friendship lasted forty years.", "Arkadaşlıkları kırk yıl sürdü."],
  ["gossip", "n", "dedikodu", "Don't listen to gossip.", "Dedikodulara kulak asma."],
  ["behave", "v", "davranmak, uslu durmak", "Behave yourself at the party!", "Partide uslu dur!"],
  ["manners", "n", "görgü, terbiye", "It's good manners to say thank you.", "Teşekkür etmek görgü kuralıdır."],
];
