import type { LexiconEntry } from "../types";

/** A2 sets 21–25: technology, media, arts, free time, feelings. */
export const A2_PART5: LexiconEntry[] = [
  // Set 21 — Technology
  ["technology", "n", "teknoloji", "Technology changes very fast.", "Teknoloji çok hızlı değişiyor."],
  ["laptop", "n", "dizüstü bilgisayar", "I take my laptop to class.", "Derse dizüstü bilgisayarımı götürürüm."],
  ["tablet", "n", "tablet", "My son reads books on a tablet.", "Oğlum kitapları tabletten okuyor."],
  ["keyboard", "n", "klavye", "This keyboard is very quiet.", "Bu klavye çok sessiz."],
  ["mouse", "n", "fare (bilgisayar)", "Click the left mouse button.", "Farenin sol tuşuna tıkla."],
  ["charger", "n", "şarj aleti", "Have you got a phone charger?", "Telefon şarj aletin var mı?"],
  ["download", "v", "indirmek", "Download the app for free.", "Uygulamayı ücretsiz indir."],
  ["upload", "v", "yüklemek", "I uploaded the photos last night.", "Fotoğrafları dün gece yükledim."],
  ["install", "v", "kurmak (program)", "Install the latest update.", "En son güncellemeyi kur."],
  ["delete", "v", "silmek", "I deleted the old messages.", "Eski mesajları sildim."],
  ["back up", "pv", "yedeklemek", "Back up your photos every month.", "Fotoğraflarını her ay yedekle."],
  ["search", "v", "aramak (bilgi)", "Search the internet for the answer.", "Cevabı internette ara."],
  ["username", "n", "kullanıcı adı", "Enter your username and password.", "Kullanıcı adını ve şifreni gir."],
  ["log in", "pv", "oturum açmak", "Log in to see your results.", "Sonuçlarını görmek için giriş yap."],
  ["log out", "pv", "oturumu kapatmak", "Always log out on shared computers.", "Ortak bilgisayarlarda her zaman çıkış yap."],
  ["wifi", "n", "kablosuz internet", "What's the wifi password?", "Wifi şifresi ne?"],
  ["social media", "n", "sosyal medya", "She spends hours on social media.", "Sosyal medyada saatler geçiriyor."],
  ["post", "v", "paylaşmak (internette)", "He posted a photo of his cat.", "Kedisinin fotoğrafını paylaştı."],
  ["share", "v", "paylaşmak", "Share this video with your friends.", "Bu videoyu arkadaşlarınla paylaş."],
  ["device", "n", "cihaz", "Turn off all electronic devices.", "Tüm elektronik cihazları kapatın."],

  // Set 22 — Media & entertainment
  ["programme", "n", "program (TV)", "What's your favourite TV programme?", "En sevdiğin televizyon programı hangisi?"],
  ["series", "n", "dizi", "I'm watching a Turkish series.", "Bir Türk dizisi izliyorum.", "Tekili ve çoğulu aynıdır."],
  ["episode", "n", "bölüm", "Did you see the last episode?", "Son bölümü gördün mü?"],
  ["channel", "n", "kanal", "Change the channel, please.", "Kanalı değiştir, lütfen."],
  ["advertisement", "n", "reklam", "There are too many advertisements.", "Çok fazla reklam var.", "Kısaltması: ad / advert."],
  ["documentary", "n", "belgesel", "We watched a documentary about whales.", "Balinalarla ilgili bir belgesel izledik."],
  ["cartoon", "n", "çizgi film", "Children love cartoons.", "Çocuklar çizgi filmlere bayılır."],
  ["comedy", "n", "komedi", "Let's watch a comedy tonight.", "Bu akşam bir komedi izleyelim."],
  ["horror film", "n", "korku filmi", "I can't watch horror films alone.", "Korku filmlerini tek başıma izleyemem."],
  ["actor", "n", "oyuncu (erkek)", "He's a famous Turkish actor.", "Ünlü bir Türk oyuncu."],
  ["actress", "n", "oyuncu (kadın)", "She won an award as best actress.", "En iyi kadın oyuncu ödülünü kazandı."],
  ["audience", "n", "seyirci", "The audience loved the show.", "Seyirciler gösteriye bayıldı."],
  ["famous", "adj", "ünlü", "Pamukkale is famous for its white terraces.", "Pamukkale beyaz travertenleriyle ünlüdür."],
  ["star", "n", "yıldız (ünlü)", "She's a big film star.", "Büyük bir film yıldızı."],
  ["journalist", "n", "gazeteci", "The journalist asked many questions.", "Gazeteci çok soru sordu."],
  ["article", "n", "makale, yazı", "I read an interesting article.", "İlginç bir makale okudum."],
  ["headline", "n", "manşet", "The story was on every headline.", "Haber her manşetteydi."],
  ["podcast", "n", "podcast", "I listen to English podcasts.", "İngilizce podcast dinlerim."],
  ["entertainment", "n", "eğlence", "The hotel offers evening entertainment.", "Otel akşam eğlencesi sunuyor."],
  ["subtitles", "n", "altyazı", "I watch films with English subtitles.", "Filmleri İngilizce altyazıyla izlerim."],

  // Set 23 — Music & art
  ["band", "n", "müzik grubu", "My brother plays in a rock band.", "Ağabeyim bir rock grubunda çalıyor."],
  ["concert hall", "n", "konser salonu", "The concert hall was full.", "Konser salonu doluydu."],
  ["instrument", "n", "enstrüman, çalgı", "Do you play an instrument?", "Bir enstrüman çalar mısın?"],
  ["piano", "n", "piyano", "She practises the piano every day.", "Her gün piyano çalışır."],
  ["violin", "n", "keman", "He plays the violin beautifully.", "Kemanı çok güzel çalar."],
  ["drums", "n", "davul, bateri", "The drums are too loud.", "Bateri çok gürültülü."],
  ["musician", "n", "müzisyen", "He's a talented musician.", "Yetenekli bir müzisyen."],
  ["album", "n", "albüm", "Her new album comes out in May.", "Yeni albümü mayısta çıkıyor."],
  ["lyrics", "n", "şarkı sözleri", "I don't understand the lyrics.", "Şarkı sözlerini anlamıyorum."],
  ["tune", "n", "melodi, ezgi", "I can't get this tune out of my head.", "Bu melodi aklımdan çıkmıyor."],
  ["painting", "n", "tablo, resim", "This painting is very old.", "Bu tablo çok eski."],
  ["paint", "v", "boyamak; resim yapmak", "She paints landscapes.", "Manzara resimleri yapar."],
  ["gallery", "n", "galeri", "We visited an art gallery.", "Bir sanat galerisini gezdik."],
  ["exhibition", "n", "sergi", "There's a photo exhibition downtown.", "Merkezde bir fotoğraf sergisi var."],
  ["theatre", "n", "tiyatro", "We saw a play at the theatre.", "Tiyatroda bir oyun izledik."],
  ["play", "n", "oyun (tiyatro)", "The play lasts two hours.", "Oyun iki saat sürüyor."],
  ["stage", "n", "sahne", "The singer came onto the stage.", "Şarkıcı sahneye çıktı."],
  ["poem", "n", "şiir", "She wrote a poem for her mother.", "Annesi için bir şiir yazdı."],
  ["novel", "n", "roman", "I'm reading a novel by Orhan Pamuk.", "Orhan Pamuk'un bir romanını okuyorum."],
  ["author", "n", "yazar", "Who is the author of this book?", "Bu kitabın yazarı kim?"],

  // Set 24 — Free time
  ["leisure", "n", "boş zaman", "What do you do in your leisure time?", "Boş zamanlarında ne yaparsın?"],
  ["collect", "v", "biriktirmek, toplamak", "He collects old stamps.", "Eski pul biriktiriyor."],
  ["hiking", "n", "doğa yürüyüşü", "We go hiking in the mountains.", "Dağlarda doğa yürüyüşüne çıkarız."],
  ["fishing", "n", "balık tutma", "My grandfather loves fishing.", "Dedem balık tutmaya bayılır."],
  ["photography", "n", "fotoğrafçılık", "Photography is my hobby.", "Fotoğrafçılık benim hobim."],
  ["gardening", "n", "bahçıvanlık", "My mother enjoys gardening.", "Annem bahçıvanlıktan hoşlanır."],
  ["knit", "v", "örgü örmek", "My grandmother knitted me a scarf.", "Büyükannem bana bir atkı ördü."],
  ["chess", "n", "satranç", "Do you play chess?", "Satranç oynar mısın?"],
  ["board game", "n", "masa oyunu", "We play board games on Sunday evenings.", "Pazar akşamları masa oyunları oynarız."],
  ["puzzle", "n", "yapboz, bulmaca", "He finished the puzzle in an hour.", "Yapbozu bir saatte bitirdi."],
  ["take up", "pv", "(hobiye) başlamak", "I took up yoga last year.", "Geçen yıl yogaya başladım."],
  ["club", "n", "kulüp", "She's in the school drama club.", "Okulun drama kulübünde."],
  ["member", "n", "üye", "Are you a member of the gym?", "Spor salonunun üyesi misin?"],
  ["spare time", "n", "boş vakit", "I read in my spare time.", "Boş vakitlerimde okurum."],
  ["go for a walk", "phr", "yürüyüşe çıkmak", "Let's go for a walk after dinner.", "Akşam yemeğinden sonra yürüyüşe çıkalım."],
  ["hang out", "pv", "takılmak, vakit geçirmek", "We hang out at the mall.", "AVM'de takılırız."],
  ["chat", "v", "sohbet etmek", "We chatted for hours.", "Saatlerce sohbet ettik."],
  ["crossword", "n", "çengel bulmaca", "My dad does the crossword every day.", "Babam her gün bulmaca çözer."],
  ["enjoyable", "adj", "keyifli", "It was an enjoyable evening.", "Keyifli bir akşamdı."],
  ["be into", "phr", "-e merakı olmak", "I'm really into photography.", "Fotoğrafçılığa çok meraklıyım."],

  // Set 25 — Feelings
  ["emotion", "n", "duygu", "It's hard to control your emotions.", "Duygularını kontrol etmek zor."],
  ["pleased", "adj", "memnun", "I'm pleased with my results.", "Sonuçlarımdan memnunum."],
  ["proud", "adj", "gururlu", "My parents are proud of me.", "Ailem benimle gurur duyuyor.", "“proud of” kalıbıyla kullanılır."],
  ["disappointed", "adj", "hayal kırıklığına uğramış", "I was disappointed with the film.", "Filmden hayal kırıklığına uğradım."],
  ["embarrassed", "adj", "utanmış, mahcup", "I felt embarrassed when I fell.", "Düşünce çok utandım."],
  ["jealous", "adj", "kıskanç", "He's jealous of his brother.", "Ağabeyini kıskanıyor."],
  ["lonely", "adj", "yalnız (hisseden)", "She feels lonely in the new city.", "Yeni şehirde kendini yalnız hissediyor."],
  ["upset", "adj", "üzgün, keyifsiz", "Don't be upset, it's not your fault.", "Üzülme, senin hatan değil."],
  ["scared", "adj", "korkmuş", "The little boy was scared.", "Küçük oğlan korkmuştu."],
  ["frightened", "adj", "korkmuş, dehşete düşmüş", "I'm frightened of spiders.", "Örümceklerden korkarım."],
  ["relaxed", "adj", "rahat, gevşemiş", "I feel relaxed after yoga.", "Yogadan sonra kendimi rahat hissediyorum."],
  ["confused", "adj", "kafası karışık", "I'm confused by the instructions.", "Talimatlar kafamı karıştırdı."],
  ["annoyed", "adj", "sinirli, rahatsız", "He was annoyed by the noise.", "Gürültüden rahatsız oldu."],
  ["amazed", "adj", "hayran kalmış, şaşkın", "I was amazed by the view.", "Manzaraya hayran kaldım."],
  ["grateful", "adj", "minnettar", "I'm grateful for your help.", "Yardımın için minnettarım."],
  ["fear", "n", "korku", "She has a fear of flying.", "Uçma korkusu var."],
  ["joy", "n", "sevinç", "The children shouted with joy.", "Çocuklar sevinçle bağırdı."],
  ["mood", "n", "ruh hâli, keyif", "You're in a good mood today!", "Bugün keyfin yerinde!"],
  ["homesick", "adj", "memleket/ev hasreti çeken", "I felt homesick in my first week abroad.", "Yurt dışındaki ilk haftamda eve özlem duydum."],
  ["cheer up", "pv", "neşelenmek, neşelendirmek", "Cheer up! It's not so bad.", "Neşelen! O kadar da kötü değil."],
];
