import type { LexiconEntry } from "../types";

/** A2 sets 26–30: communication, movement, everyday verbs, phrasal verbs. */
export const A2_PART6: LexiconEntry[] = [
  // Set 26 — Communication
  ["explain", "v", "açıklamak", "Can you explain this word?", "Bu kelimeyi açıklayabilir misin?"],
  ["announce", "v", "duyurmak", "They announced the winner on TV.", "Kazananı televizyonda duyurdular."],
  ["discuss", "v", "tartışmak, görüşmek", "Let's discuss the plan.", "Planı konuşalım.", "“about” almaz: discuss the plan."],
  ["mention", "v", "bahsetmek", "She didn't mention the party.", "Partiden bahsetmedi."],
  ["reply", "v", "yanıt vermek", "Please reply to my email.", "Lütfen e-postama yanıt ver."],
  ["warn", "v", "uyarmak", "I warned you about the traffic.", "Seni trafik konusunda uyarmıştım."],
  ["whisper", "v", "fısıldamak", "She whispered a secret to me.", "Bana bir sır fısıldadı."],
  ["promise", "v", "söz vermek", "I promise I'll call you.", "Seni arayacağıma söz veriyorum."],
  ["agree", "v", "katılmak (fikre)", "I agree with you.", "Sana katılıyorum."],
  ["disagree", "v", "katılmamak", "I'm sorry, but I disagree.", "Kusura bakma ama katılmıyorum."],
  ["complain", "v", "şikâyet etmek", "He always complains about the food.", "Hep yemekten şikâyet eder."],
  ["apologise", "v", "özür dilemek", "You should apologise to her.", "Ondan özür dilemelisin."],
  ["persuade", "v", "ikna etmek", "She persuaded me to come.", "Gelmem için beni ikna etti."],
  ["suggest", "v", "önermek", "I suggest we take a taxi.", "Taksiye binmemizi öneriyorum."],
  ["advice", "n", "tavsiye", "Can you give me some advice?", "Bana biraz tavsiye verebilir misin?", "Sayılamaz: “a piece of advice”."],
  ["conversation", "n", "sohbet, konuşma", "We had a long conversation.", "Uzun bir sohbet ettik."],
  ["opinion", "n", "fikir, görüş", "In my opinion, it's too expensive.", "Bence çok pahalı."],
  ["joke", "n", "şaka, fıkra", "He told a funny joke.", "Komik bir fıkra anlattı."],
  ["secret", "n", "sır", "Can you keep a secret?", "Sır tutabilir misin?"],
  ["text", "v", "mesaj atmak", "Text me when you arrive.", "Varınca bana mesaj at."],

  // Set 27 — Movement
  ["hurry", "v", "acele etmek", "Hurry up, we're late!", "Acele et, geç kaldık!"],
  ["rush", "v", "koşturmak, aceleyle gitmek", "Everyone rushed to the door.", "Herkes kapıya koştu."],
  ["follow", "v", "takip etmek", "Follow me, please.", "Beni takip edin, lütfen."],
  ["lead", "v", "yol göstermek, liderlik etmek", "The guide led us to the castle.", "Rehber bizi kaleye götürdü."],
  ["cross", "v", "karşıya geçmek", "Be careful when you cross the road.", "Yolun karşısına geçerken dikkatli ol."],
  ["enter", "v", "girmek", "Please knock before you enter.", "Girmeden önce lütfen kapıyı çal."],
  ["exit", "n", "çıkış", "Where's the emergency exit?", "Acil çıkış nerede?"],
  ["return", "v", "geri dönmek; iade etmek", "She returned from London yesterday.", "Dün Londra'dan döndü."],
  ["fall", "v", "düşmek", "Be careful not to fall.", "Düşmemeye dikkat et."],
  ["drop", "v", "düşürmek", "I dropped my phone and broke it.", "Telefonumu düşürüp kırdım."],
  ["lift", "v", "kaldırmak", "Can you help me lift this box?", "Bu kutuyu kaldırmama yardım eder misin?"],
  ["push", "v", "itmek", "Push the door to open it.", "Açmak için kapıyı it."],
  ["pull", "v", "çekmek", "Pull the rope hard.", "İpi sıkıca çek."],
  ["hold", "v", "tutmak", "Hold my hand when we cross.", "Karşıya geçerken elimi tut."],
  ["reach", "v", "ulaşmak, uzanmak", "We reached the top of the hill.", "Tepenin zirvesine ulaştık."],
  ["lie down", "pv", "uzanmak", "Lie down and rest for a while.", "Uzan ve biraz dinlen."],
  ["kneel", "v", "diz çökmek", "He knelt down to tie his shoe.", "Ayakkabısını bağlamak için diz çöktü."],
  ["bend", "v", "eğilmek, bükmek", "Bend your knees slowly.", "Dizlerini yavaşça bük."],
  ["wave", "v", "el sallamak", "She waved goodbye from the train.", "Trenden el sallayarak veda etti."],
  ["shake", "v", "sallamak, titremek", "Shake the bottle before use.", "Kullanmadan önce şişeyi çalkala."],

  // Set 28 — Everyday verbs
  ["allow", "v", "izin vermek", "Mobile phones are not allowed in class.", "Sınıfta cep telefonuna izin verilmez."],
  ["let", "v", "izin vermek, bırakmak", "Let me help you.", "Sana yardım edeyim."],
  ["decide", "v", "karar vermek", "I decided to stay home.", "Evde kalmaya karar verdim."],
  ["prefer", "v", "tercih etmek", "I prefer tea to coffee.", "Çayı kahveye tercih ederim."],
  ["prepare", "v", "hazırlamak", "She is preparing dinner.", "Akşam yemeğini hazırlıyor."],
  ["arrange", "v", "ayarlamak, düzenlemek", "I arranged a meeting for Monday.", "Pazartesi için bir toplantı ayarladım."],
  ["check", "v", "kontrol etmek", "Check your answers carefully.", "Cevaplarını dikkatle kontrol et."],
  ["remind", "v", "hatırlatmak", "Remind me to call my mother.", "Anneme telefon etmeyi bana hatırlat."],
  ["manage", "v", "başarmak; yönetmek", "I managed to finish on time.", "Zamanında bitirmeyi başardım."],
  ["fix", "v", "tamir etmek", "Can you fix my bike?", "Bisikletimi tamir edebilir misin?"],
  ["break", "v", "kırmak, bozmak", "Who broke the window?", "Pencereyi kim kırdı?"],
  ["hide", "v", "saklamak, saklanmak", "The children hid behind the door.", "Çocuklar kapının arkasına saklandı."],
  ["guess", "v", "tahmin etmek", "Guess what happened today!", "Bil bakalım bugün ne oldu!"],
  ["imagine", "v", "hayal etmek", "Imagine you are on a beach.", "Bir plajda olduğunu hayal et."],
  ["notice", "v", "fark etmek", "Did you notice his new haircut?", "Yeni saç kesimini fark ettin mi?"],
  ["realise", "v", "farkına varmak, anlamak", "I didn't realise it was so late.", "Saatin bu kadar geç olduğunu fark etmedim."],
  ["worry", "v", "endişelenmek", "Don't worry, everything will be fine.", "Merak etme, her şey yoluna girecek."],
  ["mind", "v", "sakınca görmek", "Do you mind if I open the window?", "Pencereyi açmamın sakıncası var mı?"],
  ["wish", "v", "dilemek, keşke demek", "I wish you a happy birthday.", "Sana mutlu yıllar dilerim."],
  ["pretend", "v", "-miş gibi yapmak", "He pretended to be asleep.", "Uyuyormuş gibi yaptı."],

  // Set 29 — Phrasal verbs 1
  ["look for", "pv", "aramak", "I'm looking for my keys.", "Anahtarlarımı arıyorum."],
  ["look after", "pv", "bakmak, ilgilenmek", "Can you look after my cat?", "Kedime bakabilir misin?"],
  ["look forward to", "pv", "dört gözle beklemek", "I'm looking forward to the holiday.", "Tatili dört gözle bekliyorum.", "Arkasından isim ya da -ing gelir."],
  ["find out", "pv", "öğrenmek, keşfetmek", "I found out the truth.", "Gerçeği öğrendim."],
  ["give up", "pv", "vazgeçmek, bırakmak", "Don't give up!", "Pes etme!"],
  ["turn on", "pv", "açmak (cihaz)", "Turn on the light, please.", "Işığı aç, lütfen."],
  ["turn off", "pv", "kapatmak (cihaz)", "Turn off your phones.", "Telefonlarınızı kapatın."],
  ["turn up", "pv", "sesini açmak; gelmek", "Turn up the music!", "Müziğin sesini aç!"],
  ["turn down", "pv", "sesini kısmak; reddetmek", "Please turn down the TV.", "Lütfen televizyonun sesini kıs."],
  ["pick up", "pv", "almak, yerden kaldırmak", "Pick up your clothes from the floor.", "Giysilerini yerden topla."],
  ["put away", "pv", "kaldırmak, yerine koymak", "Put away your books.", "Kitaplarını kaldır."],
  ["sit down", "pv", "oturmak", "Please sit down.", "Lütfen oturun."],
  ["stand up", "pv", "ayağa kalkmak", "Stand up when the teacher comes in.", "Öğretmen girince ayağa kalk."],
  ["write down", "pv", "not almak, yazmak", "Write down the new words.", "Yeni kelimeleri not al."],
  ["set off", "pv", "yola çıkmak", "We set off early in the morning.", "Sabah erkenden yola çıktık."],
  ["check in", "pv", "giriş yapmak (otel, uçuş)", "We checked in at the hotel at two.", "Otele saat ikide giriş yaptık."],
  ["check out", "pv", "çıkış yapmak (otel)", "You must check out by noon.", "Öğlene kadar çıkış yapmalısınız."],
  ["run out of", "pv", "tükenmek, bitmek", "We've run out of milk.", "Sütümüz bitti."],
  ["come in", "pv", "içeri girmek", "Come in and sit down.", "İçeri gir ve otur."],
  ["go on", "pv", "devam etmek", "Go on, I'm listening.", "Devam et, dinliyorum."],

  // Set 30 — Phrasal verbs 2
  ["grow up", "pv", "büyümek", "I grew up in Trabzon.", "Trabzon'da büyüdüm."],
  ["bring up", "pv", "yetiştirmek (çocuk); gündeme getirmek", "She was brought up by her grandparents.", "Onu büyükannesiyle büyükbabası büyüttü."],
  ["take care of", "pv", "ilgilenmek, bakmak", "Nurses take care of patients.", "Hemşireler hastalarla ilgilenir."],
  ["get along", "pv", "iyi anlaşmak", "We get along really well.", "Gerçekten iyi anlaşıyoruz."],
  ["call back", "pv", "geri aramak", "I'll call you back later.", "Seni sonra geri ararım."],
  ["hang up", "pv", "telefonu kapatmak", "Don't hang up, please hold.", "Kapatmayın, lütfen bekleyin."],
  ["break down", "pv", "bozulmak (araç)", "Our car broke down on the motorway.", "Arabamız otoyolda bozuldu."],
  ["slow down", "pv", "yavaşlamak", "Slow down, you're driving too fast!", "Yavaşla, çok hızlı sürüyorsun!"],
  ["speed up", "pv", "hızlanmak", "The train speeded up after the station.", "Tren istasyondan sonra hızlandı."],
  ["try out", "pv", "denemek", "I want to try out the new recipe.", "Yeni tarifi denemek istiyorum."],
  ["fill up", "pv", "doldurmak, depoyu doldurmak", "Fill up the tank, please.", "Depoyu doldurun, lütfen."],
  ["throw away", "pv", "atmak (çöpe)", "Don't throw away old clothes, give them away.", "Eski giysileri atma, birilerine ver."],
  ["clean up", "pv", "temizlemek, toparlamak", "Let's clean up after the party.", "Partiden sonra ortalığı toparlayalım."],
  ["get up early", "phr", "erken kalkmak", "I get up early on weekdays.", "Hafta içi erken kalkarım."],
  ["stay up", "pv", "geç saate kadar uyumamak", "We stayed up until two.", "İkiye kadar uyumadık."],
  ["eat out", "pv", "dışarıda yemek", "We eat out on Fridays.", "Cumaları dışarıda yeriz."],
  ["dress up", "pv", "şık giyinmek, kılık değiştirmek", "Everyone dressed up for the wedding.", "Herkes düğün için şık giyindi."],
  ["show around", "pv", "gezdirmek", "Let me show you around the school.", "Seni okulda gezdireyim."],
  ["drop off", "pv", "bırakmak (birini bir yere)", "I'll drop you off at the station.", "Seni istasyona bırakırım."],
  ["get back", "pv", "geri dönmek; geri almak", "When did you get back from Izmir?", "İzmir'den ne zaman döndün?"],
];
