import type { LexiconEntry } from "../types";

/** A2 sets 6–10: eating out, shopping, fashion, health, sport & fitness. */
export const A2_PART2: LexiconEntry[] = [
  // Set 6 — Eating out
  ["order", "v", "sipariş vermek", "Are you ready to order?", "Sipariş vermeye hazır mısınız?"],
  ["bill", "n", "hesap, fatura", "Can we have the bill, please?", "Hesabı alabilir miyiz, lütfen?"],
  ["tip", "n", "bahşiş", "We left a tip for the waiter.", "Garsona bahşiş bıraktık."],
  ["book", "v", "rezervasyon yapmak", "I booked a table for two.", "İki kişilik masa ayırttım."],
  ["reservation", "n", "rezervasyon", "Do you have a reservation?", "Rezervasyonunuz var mı?"],
  ["starter", "n", "başlangıç (yemek)", "We had soup as a starter.", "Başlangıç olarak çorba içtik."],
  ["main course", "n", "ana yemek", "For the main course I'll have fish.", "Ana yemek olarak balık alacağım."],
  ["vegetarian", "adj", "vejetaryen", "Do you have any vegetarian dishes?", "Vejetaryen yemekleriniz var mı?"],
  ["dish", "n", "yemek; tabak", "Kebab is a famous Turkish dish.", "Kebap ünlü bir Türk yemeğidir."],
  ["serve", "v", "servis etmek", "Breakfast is served until ten.", "Kahvaltı ona kadar servis edilir."],
  ["portion", "n", "porsiyon", "The portions here are huge.", "Buradaki porsiyonlar çok büyük."],
  ["snack", "n", "atıştırmalık", "I have a snack at four o'clock.", "Saat dörtte bir şeyler atıştırırım."],
  ["takeaway", "n", "paket servis", "Let's get a takeaway tonight.", "Bu akşam paket yemek söyleyelim."],
  ["recommend", "v", "tavsiye etmek", "What do you recommend?", "Ne tavsiye edersiniz?"],
  ["tasty", "adj", "lezzetli", "The kebab was really tasty.", "Kebap gerçekten lezzetliydi."],
  ["cutlery", "n", "çatal bıçak takımı", "The cutlery is in the drawer.", "Çatal bıçaklar çekmecede.", "Sayılamaz."],
  ["napkin", "n", "peçete", "Here's a napkin.", "Buyrun, peçete."],
  ["waitress", "n", "kadın garson", "The waitress was very friendly.", "Garson kız çok samimiydi."],
  ["buffet", "n", "açık büfe", "Breakfast is a buffet.", "Kahvaltı açık büfe.", "Sondaki “t” okunmaz: /ˈbʊfeɪ/."],
  ["self-service", "adj", "self servis", "It's a self-service restaurant.", "Burası self servis bir restoran."],

  // Set 7 — Shopping
  ["shopping centre", "n", "alışveriş merkezi", "There's a new shopping centre in town.", "Şehirde yeni bir alışveriş merkezi var."],
  ["department store", "n", "büyük mağaza", "You can buy it at the department store.", "Onu büyük mağazadan alabilirsin."],
  ["bakery", "n", "fırın, pastane", "I buy bread from the bakery.", "Ekmeği fırından alırım."],
  ["butcher's", "n", "kasap", "The butcher's is next to the bank.", "Kasap bankanın yanında."],
  ["chemist's", "n", "eczane", "Get some aspirin from the chemist's.", "Eczaneden biraz aspirin al."],
  ["bookshop", "n", "kitapçı", "I found this novel in a small bookshop.", "Bu romanı küçük bir kitapçıda buldum."],
  ["discount", "n", "indirim", "Students get a ten percent discount.", "Öğrencilere yüzde on indirim var."],
  ["bargain", "n", "kelepir", "These shoes were a real bargain.", "Bu ayakkabılar tam kelepirdi."],
  ["refund", "n", "para iadesi", "Can I get a refund?", "Paramı geri alabilir miyim?"],
  ["exchange", "v", "değiştirmek (ürün)", "Can I exchange this for a bigger size?", "Bunu daha büyük bedenle değiştirebilir miyim?"],
  ["queue", "n", "kuyruk, sıra", "There was a long queue at the checkout.", "Kasada uzun bir kuyruk vardı.", "Amerikan İngilizcesinde “line”."],
  ["checkout", "n", "kasa", "Please pay at the checkout.", "Lütfen kasada ödeyin."],
  ["trolley", "n", "alışveriş arabası", "Get a trolley, we need a lot.", "Bir araba al, çok şey lazım."],
  ["basket", "n", "sepet", "Put the apples in the basket.", "Elmaları sepete koy."],
  ["afford", "v", "(parası) yetmek", "I can't afford a new car.", "Yeni bir araba almaya gücüm yetmez."],
  ["brand", "n", "marka", "What brand is your phone?", "Telefonun hangi marka?"],
  ["label", "n", "etiket", "Read the label before you buy.", "Almadan önce etiketi oku."],
  ["deliver", "v", "teslim etmek, getirmek", "They deliver the order in two days.", "Siparişi iki günde teslim ediyorlar."],
  ["compare", "v", "karşılaştırmak", "Compare the prices online.", "Fiyatları internette karşılaştır."],
  ["on sale", "phr", "indirimde; satışta", "All winter coats are on sale.", "Tüm kışlık montlar indirimde."],

  // Set 8 — Fashion
  ["fashion", "n", "moda", "She works in fashion.", "Moda sektöründe çalışıyor."],
  ["fashionable", "adj", "moda, modaya uygun", "These boots are very fashionable.", "Bu botlar çok moda."],
  ["style", "n", "tarz, stil", "I like your style.", "Tarzını beğeniyorum."],
  ["suit", "n", "takım elbise", "He wore a dark suit to the interview.", "Mülakata koyu renk takım elbise giydi."],
  ["tie", "n", "kravat", "Do I need to wear a tie?", "Kravat takmam gerekiyor mu?"],
  ["sweater", "n", "kazak", "Put on a warm sweater.", "Sıcak bir kazak giy."],
  ["hoodie", "n", "kapüşonlu sweatshirt", "He always wears a hoodie.", "Hep kapüşonlu giyer."],
  ["shorts", "n", "şort", "It's hot, wear shorts.", "Hava sıcak, şort giy."],
  ["boots", "n", "bot, çizme", "I need boots for the snow.", "Kar için bota ihtiyacım var."],
  ["trainers", "n", "spor ayakkabı", "My trainers are very comfortable.", "Spor ayakkabılarım çok rahat.", "Amerikan İngilizcesinde “sneakers”."],
  ["belt", "n", "kemer", "These trousers need a belt.", "Bu pantolona kemer lazım."],
  ["scarf", "n", "atkı, eşarp", "Wear a scarf, it's windy.", "Atkı tak, rüzgarlı."],
  ["gloves", "n", "eldiven", "My hands are cold without gloves.", "Eldivensiz ellerim üşüyor."],
  ["necklace", "n", "kolye", "She's wearing a gold necklace.", "Altın bir kolye takıyor."],
  ["earrings", "n", "küpe", "Those earrings are beautiful.", "O küpeler çok güzel."],
  ["cotton", "n", "pamuk", "This shirt is made of cotton.", "Bu gömlek pamuktan."],
  ["wool", "n", "yün", "A wool sweater keeps you warm.", "Yün kazak insanı sıcak tutar."],
  ["leather", "n", "deri", "He bought a leather jacket.", "Deri bir ceket aldı."],
  ["fit", "v", "(beden) olmak, uymak", "These jeans don't fit me.", "Bu kot bana olmuyor.", "Beden için “fit”, uyum/renk için “suit”."],
  ["suit", "v", "yakışmak", "That colour really suits you.", "O renk sana gerçekten yakışıyor."],

  // Set 9 — Health
  ["illness", "n", "hastalık", "He's recovering from a long illness.", "Uzun bir hastalıktan iyileşiyor."],
  ["disease", "n", "hastalık (ciddi)", "Heart disease is common.", "Kalp hastalığı yaygındır."],
  ["symptom", "n", "belirti", "What are your symptoms?", "Belirtileriniz neler?"],
  ["flu", "n", "grip", "I stayed in bed with flu.", "Grip olup yatakta kaldım."],
  ["sore throat", "n", "boğaz ağrısı", "I have a sore throat.", "Boğazım ağrıyor."],
  ["toothache", "n", "diş ağrısı", "I've got a terrible toothache.", "Korkunç bir diş ağrım var."],
  ["injury", "n", "yaralanma", "He missed the match because of an injury.", "Sakatlığı yüzünden maçı kaçırdı."],
  ["injure", "v", "yaralamak", "She injured her knee skiing.", "Kayak yaparken dizini sakatladı."],
  ["bleed", "v", "kanamak", "My finger is bleeding.", "Parmağım kanıyor."],
  ["pill", "n", "hap", "Take one pill after each meal.", "Her yemekten sonra bir hap al."],
  ["prescription", "n", "reçete", "You need a prescription for this medicine.", "Bu ilaç için reçete gerekiyor."],
  ["appointment", "n", "randevu", "I have a doctor's appointment at three.", "Saat üçte doktor randevum var."],
  ["check-up", "n", "kontrol, check-up", "I go for a check-up every year.", "Her yıl kontrole giderim."],
  ["recover", "v", "iyileşmek", "She recovered quickly after the operation.", "Ameliyattan sonra çabuk iyileşti."],
  ["allergic", "adj", "alerjik", "I'm allergic to cats.", "Kedilere alerjim var.", "“allergic to” kalıbıyla kullanılır."],
  ["sneeze", "v", "hapşırmak", "Dust makes me sneeze.", "Toz beni hapşırtıyor."],
  ["dizzy", "adj", "başı dönen", "I feel dizzy when I stand up.", "Ayağa kalkınca başım dönüyor."],
  ["stress", "n", "stres", "Exams cause a lot of stress.", "Sınavlar çok stres yaratır."],
  ["diet", "n", "diyet, beslenme", "A healthy diet includes vegetables.", "Sağlıklı beslenme sebze içerir."],
  ["emergency", "n", "acil durum", "In an emergency, call 112.", "Acil durumda 112'yi arayın."],

  // Set 10 — Sport & fitness
  ["fit", "adj", "formda, zinde", "I swim to keep fit.", "Formda kalmak için yüzerim."],
  ["gym", "n", "spor salonu", "I go to the gym three times a week.", "Haftada üç kez spor salonuna giderim."],
  ["match", "n", "maç", "Did you watch the match last night?", "Dün akşam maçı izledin mi?"],
  ["score", "v", "gol/sayı atmak", "He scored two goals.", "İki gol attı."],
  ["goal", "n", "gol; hedef", "What a fantastic goal!", "Ne harika bir gol!"],
  ["player", "n", "oyuncu", "He's the best player in the team.", "Takımın en iyi oyuncusu."],
  ["coach", "n", "antrenör", "Our coach is very strict.", "Antrenörümüz çok katı."],
  ["champion", "n", "şampiyon", "She's the national tennis champion.", "Ulusal tenis şampiyonu."],
  ["competition", "n", "yarışma", "He won a swimming competition.", "Bir yüzme yarışması kazandı."],
  ["race", "n", "yarış", "Who won the race?", "Yarışı kim kazandı?"],
  ["draw", "v", "berabere kalmak", "The two teams drew 1–1.", "İki takım 1-1 berabere kaldı."],
  ["beat", "v", "yenmek", "We beat them easily.", "Onları kolayca yendik."],
  ["train", "v", "antrenman yapmak", "She trains every day for the marathon.", "Maraton için her gün antrenman yapıyor."],
  ["cycling", "n", "bisiklet sporu", "Cycling is good for your legs.", "Bisiklet bacaklara iyi gelir."],
  ["skiing", "n", "kayak", "We go skiing in Uludağ.", "Uludağ'da kayağa gideriz."],
  ["volleyball", "n", "voleybol", "Turkey has a strong volleyball team.", "Türkiye'nin güçlü bir voleybol takımı var."],
  ["stadium", "n", "stadyum", "The stadium holds 50,000 people.", "Stadyum 50.000 kişi alıyor."],
  ["referee", "n", "hakem", "The referee gave a red card.", "Hakem kırmızı kart gösterdi."],
  ["fan", "n", "taraftar, hayran", "He's a big fan of Galatasaray.", "Galatasaray'ın büyük bir taraftarı."],
  ["jog", "v", "hafif tempoda koşmak", "I jog along the seaside every morning.", "Her sabah sahil boyunca koşarım."],
];
