import type { LexiconEntry } from "../types";

/** A2 sets 46–50: ideas & abstract nouns, linking words, useful verbs, useful adjectives, everyday expressions. */
export const A2_PART10: LexiconEntry[] = [
  // Set 46 — Ideas & abstract nouns
  ["reason", "n", "sebep, neden", "What's the reason for the delay?", "Gecikmenin sebebi ne?"],
  ["choice", "n", "seçim, tercih", "You have two choices.", "İki seçeneğin var."],
  ["decision", "n", "karar", "It was a difficult decision.", "Zor bir karardı."],
  ["chance", "n", "şans, fırsat", "Give me another chance.", "Bana bir şans daha ver."],
  ["success", "n", "başarı", "The party was a big success.", "Parti büyük başarıydı."],
  ["future plans", "n", "gelecek planları", "Tell me about your future plans.", "Bana gelecek planlarından bahset."],
  ["purpose", "n", "amaç", "What's the purpose of your visit?", "Ziyaretinizin amacı nedir?"],
  ["situation", "n", "durum", "It's a difficult situation.", "Zor bir durum."],
  ["advantage", "n", "avantaj", "Speaking English is a big advantage.", "İngilizce konuşmak büyük bir avantaj."],
  ["disadvantage", "n", "dezavantaj", "The disadvantage is the price.", "Dezavantajı fiyatı."],
  ["difference", "n", "fark", "What's the difference between them?", "Aralarındaki fark ne?"],
  ["memory", "n", "hafıza; anı", "I have a good memory.", "Hafızam iyidir."],
  ["freedom", "n", "özgürlük", "Freedom is important to everyone.", "Özgürlük herkes için önemlidir."],
  ["peace", "n", "barış; huzur", "We all want peace.", "Hepimiz barış istiyoruz."],
  ["truth", "n", "gerçek, doğruluk", "Tell me the truth.", "Bana gerçeği söyle."],
  ["luck", "n", "şans", "Good luck with your exam!", "Sınavında bol şans!"],
  ["rule", "n", "kural", "Follow the rules of the game.", "Oyunun kurallarına uy."],
  ["aim", "n", "amaç, hedef", "The aim of the course is to improve speaking.", "Kursun amacı konuşmayı geliştirmek."],
  ["skill", "n", "beceri", "Communication is an important skill.", "İletişim önemli bir beceridir."],
  ["ability", "n", "yetenek, beceri", "She has the ability to learn quickly.", "Hızlı öğrenme yeteneği var."],

  // Set 47 — Linking words
  ["although", "conj", "-e rağmen, gerçi", "Although it was cold, we went out.", "Hava soğuk olmasına rağmen dışarı çıktık."],
  ["however", "adv", "ancak, fakat", "It's expensive. However, it's very good.", "Pahalı. Ancak çok iyi."],
  ["unless", "conj", "-medikçe, eğer ... -mezse", "You won't pass unless you study.", "Çalışmazsan geçemezsin."],
  ["while", "conj", "-iken", "I listen to music while I cook.", "Yemek yaparken müzik dinlerim."],
  ["since", "conj", "-den beri; çünkü", "I've lived here since 2019.", "2019'dan beri burada yaşıyorum."],
  ["as soon as", "conj", "-ir -mez", "Call me as soon as you arrive.", "Varır varmaz beni ara."],
  ["in order to", "phr", "-mek için", "I study hard in order to pass.", "Geçmek için çok çalışıyorum."],
  ["instead of", "prep", "yerine", "I'll have tea instead of coffee.", "Kahve yerine çay alacağım."],
  ["except", "prep", "hariç", "Everyone came except Ali.", "Ali hariç herkes geldi."],
  ["besides", "adv", "üstelik; -den başka", "Besides, it's too late now.", "Üstelik artık çok geç."],
  ["for example", "phr", "örneğin", "I like fruit, for example apples.", "Meyve severim, örneğin elma."],
  ["such as", "phr", "gibi", "I play sports such as tennis and golf.", "Tenis ve golf gibi sporlar yaparım."],
  ["first of all", "phr", "her şeyden önce", "First of all, thank you for coming.", "Her şeyden önce geldiğiniz için teşekkürler."],
  ["in the end", "phr", "sonunda", "In the end we took a taxi.", "Sonunda taksiye bindik."],
  ["on the other hand", "phr", "öte yandan", "It's cheap. On the other hand, it's slow.", "Ucuz. Öte yandan yavaş."],
  ["as well", "adv", "de, da", "I'd like a coffee as well.", "Ben de bir kahve istiyorum."],
  ["either", "adv", "de (olumsuz)", "I don't like it either.", "Ben de sevmiyorum.", "Olumsuz cümlelerde “too” yerine kullanılır."],
  ["neither", "det", "hiçbiri (ikisinden)", "Neither answer is correct.", "Cevapların ikisi de doğru değil."],
  ["whether", "conj", "-ip -mediği", "I don't know whether he's coming.", "Gelip gelmeyeceğini bilmiyorum."],
  ["so that", "conj", "-sin diye", "Speak louder so that everyone can hear.", "Herkes duysun diye daha yüksek sesle konuş."],

  // Set 48 — Useful verbs
  ["accept", "v", "kabul etmek", "She accepted the job offer.", "İş teklifini kabul etti."],
  ["refuse", "v", "reddetmek", "He refused to answer.", "Cevap vermeyi reddetti."],
  ["achieve", "v", "başarmak", "You can achieve your goals.", "Hedeflerine ulaşabilirsin."],
  ["improve", "v", "geliştirmek, iyileştirmek", "I want to improve my English.", "İngilizcemi geliştirmek istiyorum."],
  ["increase", "v", "artmak, artırmak", "Prices increased last month.", "Geçen ay fiyatlar arttı."],
  ["reduce", "v", "azaltmak", "We must reduce plastic waste.", "Plastik atığı azaltmalıyız."],
  ["depend", "v", "bağlı olmak", "It depends on the weather.", "Havaya bağlı.", "“depend on” kalıbıyla kullanılır."],
  ["belong", "v", "ait olmak", "This book belongs to me.", "Bu kitap bana ait."],
  ["contain", "v", "içermek", "This drink contains a lot of sugar.", "Bu içecek çok şeker içeriyor."],
  ["include", "v", "dahil etmek, kapsamak", "The price includes breakfast.", "Fiyata kahvaltı dahil."],
  ["provide", "v", "sağlamak", "The school provides free lunch.", "Okul ücretsiz öğle yemeği sağlıyor."],
  ["produce", "v", "üretmek", "Turkey produces a lot of hazelnuts.", "Türkiye çok fındık üretir."],
  ["develop", "v", "geliştirmek, gelişmek", "The city developed quickly.", "Şehir hızla gelişti."],
  ["prevent", "v", "önlemek", "Washing your hands prevents illness.", "El yıkamak hastalığı önler."],
  ["solve", "v", "çözmek", "Can you solve this problem?", "Bu sorunu çözebilir misin?"],
  ["support", "v", "desteklemek; tutmak (takım)", "My family always supports me.", "Ailem beni her zaman destekler."],
  ["expect", "v", "beklemek (olasılık)", "I expect it will rain.", "Yağmur yağacağını tahmin ediyorum."],
  ["happen", "v", "olmak, meydana gelmek", "What happened?", "Ne oldu?"],
  ["appear", "v", "görünmek, ortaya çıkmak", "A rainbow appeared in the sky.", "Gökyüzünde bir gökkuşağı belirdi."],
  ["disappear", "v", "kaybolmak", "The sun disappeared behind the clouds.", "Güneş bulutların arkasında kayboldu."],

  // Set 49 — Useful adjectives
  ["convenient", "adj", "uygun, elverişli", "Is ten o'clock convenient for you?", "Saat on sana uygun mu?"],
  ["familiar", "adj", "tanıdık", "Your face looks familiar.", "Yüzün tanıdık geliyor."],
  ["similar", "adj", "benzer", "Our bags are very similar.", "Çantalarımız çok benzer."],
  ["simple", "adj", "basit", "The instructions are simple.", "Talimatlar basit."],
  ["complicated", "adj", "karmaşık", "The rules are too complicated.", "Kurallar çok karmaşık."],
  ["main", "adj", "ana, esas", "The main street is closed today.", "Ana cadde bugün kapalı."],
  ["whole", "adj", "bütün, tüm", "I ate the whole pizza.", "Pizzanın tamamını yedim."],
  ["extra", "adj", "ekstra, fazladan", "Can I have an extra pillow?", "Fazladan bir yastık alabilir miyim?"],
  ["special", "adj", "özel", "Today is a special day.", "Bugün özel bir gün."],
  ["usual", "adj", "olağan, her zamanki", "I'll have my usual coffee.", "Her zamanki kahvemi alacağım."],
  ["unusual", "adj", "alışılmadık", "It's unusual to see snow here.", "Burada kar görmek alışılmadık."],
  ["certain", "adj", "emin; belirli", "Are you certain?", "Emin misin?"],
  ["sure", "adj", "emin", "I'm not sure.", "Emin değilim."],
  ["clear", "adj", "açık, net", "Is that clear?", "Anlaşıldı mı?"],
  ["exact", "adj", "tam, kesin", "What's the exact time?", "Saat tam olarak kaç?"],
  ["whole-grain", "adj", "tam tahıllı", "Whole-grain bread is healthy.", "Tam tahıllı ekmek sağlıklıdır."],
  ["public", "adj", "kamuya ait, halka açık", "The park is open to the public.", "Park halka açık."],
  ["official", "adj", "resmi", "English is the official language.", "İngilizce resmi dildir."],
  ["recent", "adj", "yakın zamandaki", "Here are the most recent results.", "İşte en son sonuçlar."],
  ["previous", "adj", "önceki", "I met him on a previous visit.", "Onunla önceki bir ziyarette tanıştım."],

  // Set 50 — Everyday expressions
  ["never mind", "phr", "boş ver, önemli değil", "Never mind, it's not important.", "Boş ver, önemli değil."],
  ["no problem", "phr", "sorun değil", "Thanks! — No problem.", "Teşekkürler! — Sorun değil."],
  ["you're welcome", "phr", "rica ederim", "Thank you. — You're welcome.", "Teşekkür ederim. — Rica ederim."],
  ["take care", "phr", "kendine iyi bak", "Bye, take care!", "Hoşça kal, kendine iyi bak!"],
  ["good luck", "phr", "bol şans", "Good luck tomorrow!", "Yarın için bol şans!"],
  ["well done", "phr", "aferin, tebrikler", "Well done! You passed!", "Aferin! Geçtin!"],
  ["what a pity", "phr", "ne yazık", "You can't come? What a pity!", "Gelemiyor musun? Ne yazık!"],
  ["it doesn't matter", "phr", "fark etmez", "It doesn't matter if you're late.", "Geç kalsan da fark etmez."],
  ["hurry up", "phr", "acele et", "Hurry up, the bus is coming!", "Acele et, otobüs geliyor!"],
  ["watch out", "phr", "dikkat et", "Watch out! There's a car!", "Dikkat et! Araba var!"],
  ["how about", "phr", "... ne dersin?", "How about going to the cinema?", "Sinemaya gitmeye ne dersin?"],
  ["why don't we", "phr", "neden ... -mıyoruz?", "Why don't we eat out tonight?", "Neden bu akşam dışarıda yemiyoruz?"],
  ["I'm afraid", "phr", "maalesef, korkarım", "I'm afraid the shop is closed.", "Maalesef dükkan kapalı."],
  ["by the way", "phr", "bu arada", "By the way, I saw Ali yesterday.", "Bu arada, dün Ali'yi gördüm."],
  ["in fact", "phr", "aslında", "In fact, I've never been there.", "Aslında oraya hiç gitmedim."],
  ["at least", "phr", "en azından", "At least we tried.", "En azından denedik."],
  ["at last", "phr", "nihayet", "At last the holidays are here!", "Nihayet tatil geldi!"],
  ["for sure", "phr", "kesinlikle", "I'll be there for sure.", "Kesinlikle orada olacağım."],
  ["it's up to you", "phr", "sana kalmış", "Tea or coffee? It's up to you.", "Çay mı kahve mi? Sana kalmış."],
  ["make sure", "phr", "emin olmak", "Make sure you lock the door.", "Kapıyı kilitlediğinden emin ol."],
];
