import type { LexiconEntry } from "../types";

/** B2 sets 6–10: learning, higher education, career, management, the economy. */
export const B2_PART2: LexiconEntry[] = [
  // Set 6 — How we learn
  ["acquire", "v", "edinmek, kazanmak", "Children acquire languages naturally.", "Çocuklar dilleri doğal yolla edinir."],
  ["grasp", "v", "kavramak", "It took me a while to grasp the idea.", "Fikri kavramam biraz zaman aldı."],
  ["retain", "v", "akılda tutmak; elde tutmak", "Repetition helps you retain new words.", "Tekrar, yeni kelimeleri akılda tutmana yardım eder."],
  ["rote learning", "n", "ezberci öğrenme", "Rote learning isn't always effective.", "Ezberci öğrenme her zaman etkili değildir."],
  ["aptitude", "n", "yetenek, kabiliyet", "She has an aptitude for languages.", "Dillere yeteneği var."],
  ["proficiency", "n", "yeterlilik, ustalık", "The course requires a high level of English proficiency.", "Kurs yüksek düzeyde İngilizce yeterliliği gerektiriyor."],
  ["literacy", "n", "okuryazarlık", "Digital literacy is essential today.", "Dijital okuryazarlık bugün vazgeçilmezdir."],
  ["curriculum", "n", "müfredat", "Coding is now part of the school curriculum.", "Kodlama artık okul müfredatının bir parçası."],
  ["assessment", "n", "değerlendirme", "Continuous assessment reduces exam stress.", "Sürekli değerlendirme sınav stresini azaltır."],
  ["feedback loop", "n", "geri bildirim döngüsü", "Quick tests create a useful feedback loop.", "Kısa testler faydalı bir geri bildirim döngüsü oluşturur."],
  ["self-study", "n", "kendi kendine çalışma", "Self-study requires discipline.", "Kendi kendine çalışma disiplin gerektirir."],
  ["cram", "v", "(sınava) son dakika yüklenmek", "I crammed all night for the test.", "Sınav için bütün gece son dakika çalıştım."],
  ["brush up on", "pv", "tazelemek, üzerinden geçmek", "I need to brush up on my French.", "Fransızcamı tazelemem gerek."],
  ["mnemonic", "n", "hafıza tekniği, anımsatıcı", "This mnemonic helps me remember the planets.", "Bu anımsatıcı gezegenleri hatırlamama yardım ediyor."],
  ["plagiarism", "n", "intihal", "Plagiarism is taken very seriously at university.", "Üniversitede intihal çok ciddiye alınır."],
  ["dissertation", "n", "tez (lisans/yüksek lisans)", "She's writing her dissertation on migration.", "Göç üzerine tezini yazıyor."],
  ["well-informed", "adj", "bilgili, iyi haberdar", "He's well-informed about politics.", "Siyaset konusunda iyi haberdar."],
  ["learning curve", "n", "öğrenme eğrisi", "There's a steep learning curve in the first month.", "İlk ay dik bir öğrenme eğrisi var."],
  ["distance learning", "n", "uzaktan eğitim", "Distance learning became common in 2020.", "Uzaktan eğitim 2020'de yaygınlaştı."],
  ["lifelong learning", "n", "yaşam boyu öğrenme", "Lifelong learning keeps your mind active.", "Yaşam boyu öğrenme zihnini aktif tutar."],

  // Set 7 — Higher education
  ["tuition", "n", "öğretim, ders ücreti", "Tuition is free at state universities.", "Devlet üniversitelerinde öğretim ücretsiz."],
  ["postgraduate", "adj", "lisansüstü", "She's doing a postgraduate course in law.", "Hukukta lisansüstü bir program okuyor."],
  ["major", "v", "(bir alanda) uzmanlaşmak, ana dal okumak", "He majored in economics.", "Ekonomi ana dalında okudu."],
  ["alumni", "n", "mezunlar", "The university has a strong alumni network.", "Üniversitenin güçlü bir mezun ağı var."],
  ["tutorial", "n", "küçük grup dersi; eğitim videosu", "We have a tutorial with our professor every week.", "Her hafta profesörümüzle küçük grup dersimiz var."],
  ["peer review", "n", "hakem değerlendirmesi", "The article passed peer review.", "Makale hakem değerlendirmesinden geçti."],
  ["academic year", "n", "akademik yıl", "The academic year starts in September.", "Akademik yıl eylülde başlar."],
  ["exchange programme", "n", "değişim programı", "I spent a term in Spain on an exchange programme.", "Değişim programıyla bir dönem İspanya'da kaldım."],
  ["gap year", "n", "ara yıl (okul öncesi/sonrası)", "She took a gap year to travel.", "Seyahat etmek için bir ara yıl verdi."],
  ["grant", "n", "hibe, burs", "He received a research grant.", "Araştırma hibesi aldı."],
  ["drop-out", "n", "okulu bırakan kişi", "The drop-out rate has fallen.", "Okulu bırakma oranı düştü."],
  ["entrance exam", "n", "giriş sınavı", "The university entrance exam is very competitive.", "Üniversite giriş sınavı çok rekabetçi."],
  ["deadline extension", "n", "süre uzatımı", "I asked for a deadline extension.", "Süre uzatımı istedim."],
  ["reading list", "n", "okuma listesi", "The reading list for the course is long.", "Dersin okuma listesi uzun."],
  ["citation", "n", "alıntı, kaynak gösterme", "Every citation must include the page number.", "Her alıntıda sayfa numarası olmalı."],
  ["bibliography", "n", "kaynakça", "Add a bibliography at the end.", "Sona bir kaynakça ekle."],
  ["hypothesis", "n", "hipotez", "The experiment tested his hypothesis.", "Deney onun hipotezini test etti."],
  ["methodology", "n", "yöntem bilimi, metodoloji", "Describe your methodology clearly.", "Metodolojini açıkça anlat."],
  ["findings", "n", "bulgular", "The findings were published last month.", "Bulgular geçen ay yayımlandı."],
  ["tenure", "n", "kadro, görev süresi", "The professor was given tenure.", "Profesöre kadro verildi."],

  // Set 8 — Career
  ["prospects", "n", "(gelecek) olanaklar, beklentiler", "Engineers have good career prospects.", "Mühendislerin iyi kariyer olanakları var."],
  ["recruit", "v", "işe almak", "The company recruited 50 new staff.", "Şirket 50 yeni personel işe aldı."],
  ["headhunt", "v", "(yetenekli birini) transfer etmek", "She was headhunted by a rival firm.", "Rakip bir firma tarafından transfer edildi."],
  ["probation", "n", "deneme süresi", "New staff have a three-month probation period.", "Yeni personelin üç aylık deneme süresi var."],
  ["perks", "n", "yan haklar", "Free lunch is one of the perks of the job.", "Bedava öğle yemeği işin yan haklarından biri."],
  ["redundancy", "n", "işten çıkarılma (kadro fazlası)", "Hundreds of workers face redundancy.", "Yüzlerce işçi işten çıkarılma tehlikesiyle karşı karşıya."],
  ["career ladder", "n", "kariyer basamakları", "He climbed the career ladder quickly.", "Kariyer basamaklarını hızla tırmandı."],
  ["job security", "n", "iş güvencesi", "Civil servants have good job security.", "Devlet memurlarının iyi bir iş güvencesi var."],
  ["burnout", "n", "tükenmişlik", "Long hours can lead to burnout.", "Uzun çalışma saatleri tükenmişliğe yol açabilir."],
  ["flexitime", "n", "esnek çalışma saati", "Our office offers flexitime.", "Ofisimiz esnek çalışma saati sunuyor."],
  ["remote work", "n", "uzaktan çalışma", "Remote work saves commuting time.", "Uzaktan çalışma yol zamanından tasarruf ettirir."],
  ["networking", "n", "ağ kurma, bağlantı geliştirme", "Networking is key to finding a job.", "Bağlantı kurmak iş bulmanın anahtarıdır."],
  ["mentor", "n", "akıl hocası, mentor", "My mentor helped me plan my career.", "Mentorum kariyerimi planlamama yardım etti."],
  ["internship", "n", "staj", "I did an internship at a bank.", "Bir bankada staj yaptım."],
  ["notice", "n", "işten ayrılma bildirimi", "She handed in her notice yesterday.", "Dün istifa bildirimini verdi.", "give/hand in your notice"],
  ["dismiss", "v", "işten çıkarmak; reddetmek", "He was dismissed for misconduct.", "Kötü davranış nedeniyle işten çıkarıldı."],
  ["climb the ladder", "phr", "yükselmek (kariyer)", "It takes years to climb the ladder.", "Kariyerde yükselmek yıllar alır."],
  ["make a career change", "phr", "kariyer değiştirmek", "At 40, she made a career change.", "40 yaşında kariyer değiştirdi."],
  ["transferable skills", "n", "aktarılabilir beceriler", "Communication is a transferable skill.", "İletişim aktarılabilir bir beceridir."],
  ["job-hunting", "n", "iş arama", "Job-hunting can be exhausting.", "İş aramak yorucu olabilir."],

  // Set 9 — Management
  ["delegate", "v", "yetki devretmek", "Good managers know how to delegate.", "İyi yöneticiler yetki devretmeyi bilir."],
  ["oversee", "v", "denetlemek, gözetmek", "She oversees a team of twelve.", "On iki kişilik bir ekibi yönetiyor."],
  ["prioritise", "v", "önceliklendirmek", "Learn to prioritise your tasks.", "Görevlerini önceliklendirmeyi öğren."],
  ["implement", "v", "uygulamaya koymak", "The new policy will be implemented next year.", "Yeni politika gelecek yıl uygulamaya konacak."],
  ["streamline", "v", "sadeleştirmek, verimli hale getirmek", "We streamlined the ordering process.", "Sipariş sürecini sadeleştirdik."],
  ["objective", "n", "hedef, amaç", "What are the main objectives of the project?", "Projenin ana hedefleri neler?"],
  ["strategy", "n", "strateji", "We need a new marketing strategy.", "Yeni bir pazarlama stratejisine ihtiyacımız var."],
  ["stakeholder", "n", "paydaş", "All stakeholders were invited to the meeting.", "Tüm paydaşlar toplantıya davet edildi."],
  ["accountable", "adj", "hesap verebilir, sorumlu", "Managers are accountable for their team's results.", "Yöneticiler ekiplerinin sonuçlarından sorumludur."],
  ["hands-on", "adj", "işin içinde olan, uygulamalı", "She has a hands-on management style.", "İşin içinde olan bir yönetim tarzı var."],
  ["morale", "n", "moral (ekip)", "Staff morale is low after the cuts.", "Kesintilerden sonra personelin morali düşük."],
  ["productivity", "n", "verimlilik", "Short breaks increase productivity.", "Kısa molalar verimliliği artırır."],
  ["benchmark", "n", "ölçüt, kıyas noktası", "These results set a new benchmark.", "Bu sonuçlar yeni bir ölçüt belirledi."],
  ["milestone", "n", "dönüm noktası, önemli aşama", "Reaching 1,000 customers was a milestone.", "1.000 müşteriye ulaşmak önemli bir aşamaydı."],
  ["outsource", "v", "dış kaynak kullanmak", "Many companies outsource their IT support.", "Birçok şirket BT desteği için dış kaynak kullanır."],
  ["restructure", "v", "yeniden yapılandırmak", "The company was restructured last year.", "Şirket geçen yıl yeniden yapılandırıldı."],
  ["chair", "v", "(toplantıya) başkanlık etmek", "Who's chairing the meeting?", "Toplantıya kim başkanlık ediyor?"],
  ["brainstorm", "v", "beyin fırtınası yapmak", "Let's brainstorm some ideas.", "Birkaç fikir için beyin fırtınası yapalım."],
  ["follow up", "pv", "takip etmek, arkasını getirmek", "I'll follow up with an email.", "Bir e-postayla takip edeceğim."],
  ["on the same page", "phr", "aynı noktada, hemfikir", "Let's make sure we're all on the same page.", "Hepimizin aynı noktada olduğundan emin olalım."],

  // Set 10 — The economy
  ["recession", "n", "durgunluk, resesyon", "The country is in a recession.", "Ülke durgunluk içinde."],
  ["growth", "n", "büyüme", "Economic growth slowed this year.", "Ekonomik büyüme bu yıl yavaşladı."],
  ["interest rate", "n", "faiz oranı", "The bank raised interest rates.", "Banka faiz oranlarını yükseltti."],
  ["fiscal policy", "n", "maliye politikası", "The government changed its fiscal policy.", "Hükümet maliye politikasını değiştirdi."],
  ["purchasing power", "n", "satın alma gücü", "Inflation reduces purchasing power.", "Enflasyon satın alma gücünü düşürür."],
  ["minimum wage", "n", "asgari ücret", "The minimum wage was increased.", "Asgari ücret artırıldı."],
  ["deficit", "n", "açık (bütçe/ticaret)", "The trade deficit grew last year.", "Dış ticaret açığı geçen yıl büyüdü."],
  ["subsidy", "n", "sübvansiyon, devlet desteği", "Farmers receive subsidies from the state.", "Çiftçiler devletten destek alıyor."],
  ["boom", "n", "patlama, hızlı büyüme", "There was a housing boom in the 2010s.", "2010'larda konut patlaması yaşandı."],
  ["slump", "n", "ani düşüş, durgunluk", "Sales are in a slump.", "Satışlar durgun."],
  ["fluctuate", "v", "dalgalanmak", "Prices fluctuate with the seasons.", "Fiyatlar mevsimlere göre dalgalanır."],
  ["soar", "v", "fırlamak (fiyat)", "Rents have soared in the city.", "Şehirde kiralar fırladı."],
  ["plummet", "v", "hızla düşmek, çakılmak", "Share prices plummeted.", "Hisse fiyatları çakıldı."],
  ["stagnate", "v", "durgunlaşmak", "Wages have stagnated for years.", "Maaşlar yıllardır yerinde sayıyor."],
  ["consumer spending", "n", "tüketici harcaması", "Consumer spending rose before the holiday.", "Bayram öncesi tüketici harcaması arttı."],
  ["gross domestic product (GDP)", "n", "gayrisafi yurt içi hasıla", "GDP grew by 3%.", "GSYH %3 büyüdü."],
  ["shareholder", "n", "hissedar", "Shareholders will vote on the plan.", "Hissedarlar plan için oy verecek."],
  ["monopoly", "n", "tekel", "The company has a monopoly on the market.", "Şirketin piyasada tekeli var."],
  ["globalisation", "n", "küreselleşme", "Globalisation has changed how we shop.", "Küreselleşme alışveriş şeklimizi değiştirdi."],
  ["the cost of borrowing", "phr", "borçlanma maliyeti", "The cost of borrowing is very high now.", "Borçlanma maliyeti şu an çok yüksek."],
];
