import type { LexiconEntry } from "../types";

/** B2 sets 51–55: fashion & looks, household life, landscapes, weather, animal behaviour. */
export const B2_PART11: LexiconEntry[] = [
  // Set 51 — Fashion & looks
  ["trendy", "adj", "moda, havalı", "She always wears trendy clothes.", "Hep moda kıyafetler giyer."],
  ["outdated", "adj", "modası geçmiş", "That hairstyle looks outdated.", "O saç modeli modası geçmiş görünüyor."],
  ["timeless", "adj", "zamansız, eskimeyen", "A white shirt is a timeless classic.", "Beyaz gömlek eskimeyen bir klasiktir."],
  ["flattering", "adj", "(kıyafet) yakışan, gösterişli gösteren", "That colour is very flattering on you.", "O renk sana çok yakışıyor."],
  ["baggy", "adj", "bol (kıyafet)", "He wears baggy jeans.", "Bol kot pantolon giyiyor."],
  ["tight-fitting", "adj", "dar, vücudu saran", "Tight-fitting clothes aren't comfortable.", "Dar kıyafetler rahat değil."],
  ["tailored", "adj", "ısmarlama, üzerine göre dikilmiş", "He wore a tailored suit.", "Üzerine göre dikilmiş bir takım giydi."],
  ["accessorise", "v", "aksesuarla tamamlamak", "She accessorised the dress with a scarf.", "Elbiseyi bir eşarpla tamamladı."],
  ["catwalk", "n", "podyum", "Models walked down the catwalk.", "Modeller podyumda yürüdü."],
  ["designer label", "n", "tasarımcı markası", "He only buys designer labels.", "Sadece tasarımcı markaları alıyor."],
  ["second-hand clothes", "n", "ikinci el kıyafet", "Second-hand clothes are better for the planet.", "İkinci el kıyafetler gezegen için daha iyi."],
  ["hand-me-down", "n", "(kardeşten kalma) eski kıyafet", "I wore my brother's hand-me-downs.", "Abimden kalan kıyafetleri giyerdim."],
  ["well-groomed", "adj", "bakımlı", "He's always well-groomed.", "Her zaman bakımlıdır."],
  ["unkempt", "adj", "dağınık, bakımsız (saç, görünüm)", "His hair was long and unkempt.", "Saçları uzun ve bakımsızdı."],
  ["complexion", "n", "ten, cilt rengi", "She has a clear complexion.", "Temiz bir cildi var."],
  ["slender", "adj", "ince, narin", "She has slender fingers.", "İnce parmakları var."],
  ["stocky", "adj", "tıknaz", "He's short and stocky.", "Kısa ve tıknaz."],
  ["receding hairline", "n", "açılan saç çizgisi", "He has a receding hairline.", "Saçları öndan açılıyor."],
  ["dress to impress", "phr", "etkilemek için şık giyinmek", "Dress to impress at the interview.", "Mülakatta etkilemek için şık giyin."],
  ["look the part", "phr", "rolüne uygun görünmek", "In his suit, he really looks the part.", "Takım elbisesiyle gerçekten rolüne uygun görünüyor."],

  // Set 52 — Household life
  ["household chores", "n", "ev işleri", "We share the household chores.", "Ev işlerini paylaşıyoruz."],
  ["clutter", "n", "dağınıklık, ıvır zıvır", "The garage is full of clutter.", "Garaj ıvır zıvırla dolu."],
  ["declutter", "v", "fazlalıklardan arındırmak", "I decluttered my wardrobe.", "Gardırobumu fazlalıklardan arındırdım."],
  ["spotless", "adj", "tertemiz, lekesiz", "The kitchen was spotless.", "Mutfak tertemizdi."],
  ["cosy", "adj", "sıcak, samimi, rahat", "It's a small but cosy flat.", "Küçük ama sıcak bir daire."],
  ["draughty", "adj", "cereyan yapan", "The old house is draughty in winter.", "Eski ev kışın cereyan yapıyor."],
  ["damp", "adj", "rutubetli, nemli", "The basement is damp.", "Bodrum rutubetli."],
  ["appliance", "n", "(ev) aleti", "We bought new kitchen appliances.", "Yeni mutfak aletleri aldık."],
  ["dishwasher-safe", "adj", "bulaşık makinesinde yıkanabilir", "Are these plates dishwasher-safe?", "Bu tabaklar bulaşık makinesinde yıkanabilir mi?"],
  ["hoover", "v", "elektrik süpürgesiyle süpürmek", "I hoovered the living room.", "Oturma odasını elektrik süpürgesiyle süpürdüm."],
  ["mop", "v", "paspaslamak", "Mop the floor after cooking.", "Yemekten sonra yeri paspasla."],
  ["iron out creases", "phr", "kırışıkları ütüyle gidermek", "Iron out the creases before you go.", "Gitmeden önce kırışıkları ütüle."],
  ["chore chart", "n", "ev işi çizelgesi", "The kids follow a chore chart.", "Çocuklar bir ev işi çizelgesine uyuyor."],
  ["make do with", "phr", "…ile idare etmek", "We had to make do with a small kitchen.", "Küçük bir mutfakla idare etmek zorunda kaldık."],
  ["housebound", "adj", "evden çıkamayan", "My grandmother is housebound.", "Büyükannem evden çıkamıyor."],
  ["house-proud", "adj", "evine çok özen gösteren", "She's very house-proud.", "Evine çok özen gösterir."],
  ["homely", "adj", "ev gibi, sıcak", "The hotel has a homely feel.", "Otelin ev gibi sıcak bir havası var."],
  ["domestic", "adj", "ev içi; yurt içi", "Domestic tasks take hours every week.", "Ev içi işler her hafta saatler alıyor."],
  ["pest", "n", "haşere", "We called someone to deal with the pests.", "Haşerelerle ilgilenmesi için birini çağırdık."],
  ["spring-clean", "v", "(evi) baştan aşağı temizlemek", "We spring-clean the house before the holiday.", "Bayramdan önce evi baştan aşağı temizleriz."],

  // Set 53 — Landscapes
  ["terrain", "n", "arazi", "The terrain is rocky and steep.", "Arazi kayalık ve dik."],
  ["plateau", "n", "plato, yayla", "Cappadocia lies on a high plateau.", "Kapadokya yüksek bir plato üzerinde yer alır."],
  ["gorge", "n", "boğaz, kanyon", "We hiked through the Saklıkent gorge.", "Saklıkent kanyonunda yürüyüş yaptık."],
  ["cliff", "n", "uçurum, yalıyar", "The house stands on a cliff.", "Ev bir uçurumun üzerinde duruyor."],
  ["peninsula", "n", "yarımada", "The Datça peninsula is beautiful.", "Datça yarımadası çok güzel."],
  ["bay", "n", "koy", "We swam in a quiet bay.", "Sakin bir koyda yüzdük."],
  ["lagoon", "n", "lagün", "Ölüdeniz has a famous blue lagoon.", "Ölüdeniz'in ünlü mavi bir lagünü var."],
  ["estuary", "n", "nehir ağzı, haliç", "Birds gather in the estuary.", "Kuşlar nehir ağzında toplanıyor."],
  ["meadow", "n", "çayır", "Cows graze in the meadow.", "İnekler çayırda otluyor."],
  ["summit", "n", "zirve", "We reached the summit of Erciyes.", "Erciyes'in zirvesine ulaştık."],
  ["ridge", "n", "sırt (dağ)", "We walked along the ridge.", "Sırt boyunca yürüdük."],
  ["slope", "n", "yamaç, eğim", "The ski slopes open in December.", "Kayak pistleri aralıkta açılıyor."],
  ["marsh", "n", "bataklık", "The marsh is home to many birds.", "Bataklık birçok kuşa ev sahipliği yapıyor."],
  ["scenery", "n", "manzara, doğal görünüm", "The scenery in Artvin is breathtaking.", "Artvin'in manzarası nefes kesici."],
  ["panoramic", "adj", "panoramik", "The hotel has panoramic views of the sea.", "Otelin panoramik deniz manzarası var."],
  ["rugged", "adj", "engebeli, sarp", "The coastline is rugged.", "Kıyı şeridi sarp."],
  ["barren", "adj", "çorak", "The land is dry and barren.", "Toprak kuru ve çorak."],
  ["lush", "adj", "gür, yemyeşil", "The Black Sea region is lush and green.", "Karadeniz bölgesi yemyeşil."],
  ["remote", "adj", "uzak, ıssız", "They live in a remote village.", "Uzak bir köyde yaşıyorlar."],
  ["secluded", "adj", "gözden uzak, kuytu", "We found a secluded beach.", "Kuytu bir plaj bulduk."],

  // Set 54 — Weather & climate
  ["humid", "adj", "nemli, bunaltıcı", "Istanbul is humid in summer.", "İstanbul yazın nemlidir."],
  ["humidity", "n", "nem", "The humidity makes it feel hotter.", "Nem havayı daha sıcak hissettiriyor."],
  ["drizzle", "n", "çisenti", "It's only a light drizzle.", "Sadece hafif bir çisenti."],
  ["downpour", "n", "sağanak", "We got caught in a downpour.", "Sağanağa yakalandık."],
  ["hailstorm", "n", "dolu fırtınası", "The hailstorm damaged cars.", "Dolu fırtınası arabalara zarar verdi."],
  ["gale", "n", "şiddetli rüzgâr, fırtına", "Ferries were cancelled because of the gale.", "Şiddetli rüzgâr yüzünden vapurlar iptal edildi."],
  ["blizzard", "n", "tipi, kar fırtınası", "The blizzard closed the roads.", "Kar fırtınası yolları kapattı."],
  ["frost", "n", "don, kırağı", "There was frost on the car this morning.", "Bu sabah arabada kırağı vardı."],
  ["scorching", "adj", "kavurucu", "It was a scorching day.", "Kavurucu bir gündü."],
  ["mild", "adj", "ılıman", "Winters are mild on the coast.", "Kıyıda kışlar ılımandır."],
  ["overcast", "adj", "kapalı, bulutlu", "The sky was overcast all day.", "Gökyüzü bütün gün kapalıydı."],
  ["changeable", "adj", "değişken", "The weather is changeable in spring.", "İlkbaharda hava değişkendir."],
  ["clear up", "pv", "(hava) açmak", "The weather cleared up in the afternoon.", "Öğleden sonra hava açtı."],
  ["forecast to", "phr", "…ceği tahmin ediliyor", "Temperatures are forecast to reach 40°C.", "Sıcaklıkların 40 dereceye ulaşacağı tahmin ediliyor."],
  ["extreme weather", "n", "aşırı hava olayları", "Extreme weather is becoming more common.", "Aşırı hava olayları daha yaygın hale geliyor."],
  ["flash flood", "n", "ani sel", "A flash flood hit the village.", "Köyü ani bir sel vurdu."],
  ["heat stroke", "n", "güneş çarpması, sıcak çarpması", "Drink water to avoid heat stroke.", "Sıcak çarpmasından korunmak için su iç."],
  ["weather warning", "n", "meteorolojik uyarı", "There's a weather warning for the coast.", "Kıyı için meteorolojik uyarı var."],
  ["subzero", "adj", "sıfırın altında", "Subzero temperatures froze the pipes.", "Sıfırın altındaki sıcaklıklar boruları dondurdu."],
  ["muggy", "adj", "boğucu, sıkıntılı (hava)", "It's so muggy today.", "Bugün hava çok boğucu."],

  // Set 55 — Animal behaviour
  ["instinct", "n", "içgüdü", "Birds migrate by instinct.", "Kuşlar içgüdüyle göç eder."],
  ["domesticated", "adj", "evcilleştirilmiş", "Dogs were domesticated thousands of years ago.", "Köpekler binlerce yıl önce evcilleştirildi."],
  ["breed", "v", "üremek; yetiştirmek", "Turtles breed on this beach.", "Kaplumbağalar bu plajda ürer."],
  ["offspring", "n", "yavru, döl", "The bird feeds its offspring.", "Kuş yavrularını besliyor."],
  ["pack", "n", "sürü (kurt, köpek)", "Wolves hunt in packs.", "Kurtlar sürü halinde avlanır."],
  ["swarm", "n", "sürü (böcek), oğul (arı)", "A swarm of bees flew past.", "Bir arı sürüsü yanımızdan geçti."],
  ["territory", "n", "bölge (hayvan)", "Lions defend their territory.", "Aslanlar bölgelerini savunur."],
  ["camouflage", "n", "kamuflaj", "The lizard uses camouflage to hide.", "Kertenkele saklanmak için kamuflaj kullanır."],
  ["nocturnal", "adj", "gece aktif olan", "Owls are nocturnal.", "Baykuşlar gece aktiftir."],
  ["carnivore", "n", "etobur", "Tigers are carnivores.", "Kaplanlar etoburdur."],
  ["herbivore", "n", "otobur", "Cows are herbivores.", "İnekler otoburdur."],
  ["scavenger", "n", "leş yiyen hayvan", "Vultures are scavengers.", "Akbabalar leş yiyen hayvanlardır."],
  ["pollinate", "v", "tozlaştırmak", "Bees pollinate flowers.", "Arılar çiçekleri tozlaştırır."],
  ["hatch", "v", "yumurtadan çıkmak", "The eggs hatched after two weeks.", "Yumurtalar iki hafta sonra çatladı."],
  ["prowl", "v", "(av için) sinsice dolaşmak", "A cat was prowling in the garden.", "Bahçede bir kedi sinsice dolaşıyordu."],
  ["stray", "adj", "sokak (hayvanı), başıboş", "Many stray cats live in Istanbul.", "İstanbul'da birçok sokak kedisi yaşıyor."],
  ["poaching", "n", "kaçak avcılık", "Poaching threatens elephants.", "Kaçak avcılık filleri tehdit ediyor."],
  ["captivity", "n", "esaret, tutsaklık (hayvan)", "Animals in captivity often live longer.", "Esaret altındaki hayvanlar çoğu zaman daha uzun yaşar."],
  ["sanctuary", "n", "koruma alanı, barınak", "The donkeys live in an animal sanctuary.", "Eşekler bir hayvan barınağında yaşıyor."],
  ["food chain", "n", "besin zinciri", "Sharks are at the top of the food chain.", "Köpekbalıkları besin zincirinin tepesinde."],
];
