import type { LexiconEntry } from "../types";

/** B2 sets 16–20: environmental issues, energy, cities, the housing market, transport. */
export const B2_PART4: LexiconEntry[] = [
  // Set 16 — Environmental issues
  ["biodiversity", "n", "biyoçeşitlilik", "Deforestation threatens biodiversity.", "Ormansızlaşma biyoçeşitliliği tehdit ediyor."],
  ["ecosystem", "n", "ekosistem", "Plastic damages marine ecosystems.", "Plastik deniz ekosistemlerine zarar verir."],
  ["depletion", "n", "tükenme, azalma", "The depletion of fish stocks is serious.", "Balık stoklarının tükenmesi ciddi bir sorun."],
  ["contaminate", "v", "kirletmek, bulaştırmak", "Chemicals contaminated the river.", "Kimyasallar nehri kirletti."],
  ["degradation", "n", "bozulma, tahribat", "Soil degradation affects farming.", "Toprak tahribatı tarımı etkiliyor."],
  ["carbon neutral", "adj", "karbon nötr", "The company aims to be carbon neutral by 2035.", "Şirket 2035'e kadar karbon nötr olmayı hedefliyor."],
  ["offset", "v", "dengelemek, telafi etmek", "You can offset your flight's emissions by planting trees.", "Uçuşunun emisyonlarını ağaç dikerek dengeleyebilirsin."],
  ["landfill", "n", "çöp sahası", "Most plastic ends up in landfill.", "Plastiğin çoğu çöp sahasında son bulur."],
  ["drought-resistant", "adj", "kuraklığa dayanıklı", "Farmers are planting drought-resistant crops.", "Çiftçiler kuraklığa dayanıklı ürünler ekiyor."],
  ["desertification", "n", "çölleşme", "Desertification is a growing threat in Central Anatolia.", "Çölleşme İç Anadolu'da büyüyen bir tehdit."],
  ["marine life", "n", "deniz yaşamı", "Oil spills kill marine life.", "Petrol sızıntıları deniz yaşamını öldürür."],
  ["overfishing", "n", "aşırı avlanma", "Overfishing has emptied parts of the sea.", "Aşırı avlanma denizin bazı bölümlerini boşalttı."],
  ["mitigate", "v", "hafifletmek, azaltmak", "Trees help mitigate the effects of heat.", "Ağaçlar sıcağın etkilerini hafifletmeye yardım eder."],
  ["irreversible", "adj", "geri döndürülemez", "Some damage to the climate is irreversible.", "İklime verilen bazı zararlar geri döndürülemez."],
  ["eco-conscious", "adj", "çevre bilinçli", "Eco-conscious shoppers avoid plastic.", "Çevre bilinçli alıcılar plastikten kaçınır."],
  ["single-use", "adj", "tek kullanımlık", "Single-use plastics are banned in many countries.", "Birçok ülkede tek kullanımlık plastikler yasak."],
  ["upcycle", "v", "ileri dönüştürmek", "She upcycles old furniture.", "Eski mobilyaları ileri dönüştürüyor."],
  ["conservationist", "n", "doğa koruma uzmanı", "Conservationists are trying to save the turtles.", "Doğa korumacılar kaplumbağaları kurtarmaya çalışıyor."],
  ["ecological footprint", "n", "ekolojik ayak izi", "Eating less meat reduces your ecological footprint.", "Daha az et yemek ekolojik ayak izini azaltır."],
  ["tipping point", "n", "kırılma noktası", "Scientists warn we are near a tipping point.", "Bilim insanları bir kırılma noktasına yakın olduğumuz konusunda uyarıyor."],

  // Set 17 — Energy
  ["solar panel", "n", "güneş paneli", "We installed solar panels on the roof.", "Çatıya güneş panelleri kurduk."],
  ["wind turbine", "n", "rüzgâr türbini", "Wind turbines line the hills near Çeşme.", "Çeşme yakınındaki tepeler rüzgâr türbinleriyle dolu."],
  ["hydroelectric", "adj", "hidroelektrik", "The dam produces hydroelectric power.", "Baraj hidroelektrik enerji üretiyor."],
  ["nuclear power", "n", "nükleer enerji", "Nuclear power is a controversial topic.", "Nükleer enerji tartışmalı bir konu."],
  ["geothermal", "adj", "jeotermal", "Denizli uses geothermal energy for heating.", "Denizli ısınmada jeotermal enerji kullanıyor."],
  ["grid", "n", "(elektrik) şebeke", "The house isn't connected to the grid.", "Ev şebekeye bağlı değil."],
  ["power cut", "n", "elektrik kesintisi", "There was a power cut during the storm.", "Fırtına sırasında elektrik kesintisi oldu."],
  ["energy-efficient", "adj", "enerji verimli", "LED bulbs are energy-efficient.", "LED ampuller enerji verimlidir."],
  ["insulation", "n", "yalıtım", "Good insulation lowers heating bills.", "İyi yalıtım ısınma faturalarını düşürür."],
  ["consumption", "n", "tüketim", "Energy consumption peaks in winter.", "Enerji tüketimi kışın zirve yapar."],
  ["fossil fuels", "n", "fosil yakıtlar", "We must reduce our dependence on fossil fuels.", "Fosil yakıtlara bağımlılığımızı azaltmalıyız."],
  ["crude oil", "n", "ham petrol", "The price of crude oil rose sharply.", "Ham petrol fiyatı keskin şekilde yükseldi."],
  ["natural gas", "n", "doğal gaz", "Most homes are heated with natural gas.", "Evlerin çoğu doğal gazla ısıtılıyor."],
  ["pipeline", "n", "boru hattı", "A new gas pipeline was built.", "Yeni bir doğal gaz boru hattı inşa edildi."],
  ["electric vehicle", "n", "elektrikli araç", "Electric vehicles are becoming cheaper.", "Elektrikli araçlar ucuzluyor."],
  ["charging station", "n", "şarj istasyonu", "There are few charging stations on this road.", "Bu yolda az sayıda şarj istasyonu var."],
  ["generate", "v", "üretmek (enerji)", "The panels generate enough power for the house.", "Paneller ev için yeterli enerji üretiyor."],
  ["harness", "v", "(doğal gücü) kullanmak, yararlanmak", "We need to harness the power of the sun.", "Güneşin gücünden yararlanmalıyız."],
  ["sustainability", "n", "sürdürülebilirlik", "Sustainability is at the heart of the plan.", "Sürdürülebilirlik planın merkezinde."],
  ["energy crisis", "n", "enerji krizi", "Europe faced an energy crisis in 2022.", "Avrupa 2022'de bir enerji kriziyle karşılaştı."],

  // Set 18 — Cities
  ["urbanisation", "n", "kentleşme", "Rapid urbanisation creates housing problems.", "Hızlı kentleşme konut sorunları yaratır."],
  ["urban sprawl", "n", "kentsel yayılma", "Urban sprawl is eating up farmland.", "Kentsel yayılma tarım arazilerini yutuyor."],
  ["metropolis", "n", "büyük şehir, metropol", "Istanbul is a huge metropolis.", "İstanbul devasa bir metropol."],
  ["densely populated", "adj", "yoğun nüfuslu", "Hong Kong is densely populated.", "Hong Kong yoğun nüfuslu."],
  ["inner city", "n", "şehir merkezi (yoksul semtler)", "Inner-city schools need more funding.", "Merkezdeki yoksul semt okullarının daha fazla fona ihtiyacı var."],
  ["gentrification", "n", "soylulaştırma", "Gentrification has pushed up rents in Cihangir.", "Soylulaştırma Cihangir'de kiraları artırdı."],
  ["regeneration", "n", "yeniden canlandırma, kentsel dönüşüm", "The harbour area is part of a regeneration project.", "Liman bölgesi bir kentsel dönüşüm projesinin parçası."],
  ["amenities", "n", "sosyal olanaklar", "The area has good amenities such as parks and shops.", "Bölgede park ve dükkân gibi iyi olanaklar var."],
  ["green space", "n", "yeşil alan", "Cities need more green spaces.", "Şehirlerin daha fazla yeşil alana ihtiyacı var."],
  ["pedestrianise", "v", "yayalaştırmak", "The main street was pedestrianised.", "Ana cadde yayalaştırıldı."],
  ["congestion", "n", "(trafik) sıkışıklığı", "Congestion is worst at 6 p.m.", "Trafik sıkışıklığı en çok akşam altıda."],
  ["noise pollution", "n", "gürültü kirliliği", "Noise pollution affects sleep.", "Gürültü kirliliği uykuyu etkiler."],
  ["slum", "n", "gecekondu bölgesi", "Millions live in slums around the world.", "Dünya genelinde milyonlarca insan gecekondu bölgelerinde yaşıyor."],
  ["zoning", "n", "imar (bölgeleme)", "Zoning laws restrict building heights.", "İmar kanunları bina yüksekliklerini sınırlıyor."],
  ["municipality", "n", "belediye", "The municipality repaired the roads.", "Belediye yolları onardı."],
  ["high-rise", "adj", "yüksek katlı", "They live in a high-rise building.", "Yüksek katlı bir binada yaşıyorlar."],
  ["run-down", "adj", "bakımsız, köhne", "The neighbourhood was run-down twenty years ago.", "Mahalle yirmi yıl önce bakımsızdı."],
  ["bustling", "adj", "hareketli, kalabalık", "Kadıköy has a bustling market.", "Kadıköy'ün hareketli bir çarşısı var."],
  ["vibrant", "adj", "canlı, hayat dolu", "Izmir is a vibrant city.", "İzmir hayat dolu bir şehir."],
  ["smart city", "n", "akıllı şehir", "Smart cities use data to manage traffic.", "Akıllı şehirler trafiği yönetmek için veri kullanır."],

  // Set 19 — The housing market
  ["property market", "n", "emlak piyasası", "The property market is booming.", "Emlak piyasası patlama yaşıyor."],
  ["landlady", "n", "ev sahibesi", "Our landlady lives downstairs.", "Ev sahibemiz alt katta oturuyor."],
  ["lease", "n", "kira sözleşmesi", "We signed a one-year lease.", "Bir yıllık kira sözleşmesi imzaladık."],
  ["evict", "v", "tahliye etmek (evden)", "They were evicted for not paying rent.", "Kira ödemedikleri için tahliye edildiler."],
  ["affordable housing", "n", "uygun fiyatlı konut", "There's a shortage of affordable housing.", "Uygun fiyatlı konut sıkıntısı var."],
  ["first-time buyer", "n", "ilk kez ev alan kişi", "Prices are too high for first-time buyers.", "Fiyatlar ilk kez ev alacaklar için çok yüksek."],
  ["down payment", "n", "peşinat", "We need a 25% down payment.", "%25 peşinata ihtiyacımız var."],
  ["valuation", "n", "değerleme, ekspertiz", "The bank ordered a valuation of the flat.", "Banka daire için ekspertiz istedi."],
  ["freehold", "n", "tam mülkiyet", "They own the freehold of the building.", "Binanın tam mülkiyeti onların."],
  ["utility bills", "n", "fatura giderleri", "Utility bills have doubled this winter.", "Fatura giderleri bu kış iki katına çıktı."],
  ["maintenance fee", "n", "aidat", "The monthly maintenance fee is 1,500 lira.", "Aylık aidat 1.500 lira."],
  ["homeowner", "n", "ev sahibi (mülk sahibi)", "Homeowners pay property tax.", "Ev sahipleri emlak vergisi öder."],
  ["downsize", "v", "daha küçük eve geçmek; küçülmek", "After the kids left, they downsized.", "Çocuklar gidince daha küçük bir eve geçtiler."],
  ["relocate", "v", "yer değiştirmek, taşınmak", "The company relocated to Ankara.", "Şirket Ankara'ya taşındı."],
  ["commuter belt", "n", "banliyö kuşağı", "They live in the commuter belt outside the city.", "Şehir dışındaki banliyö kuşağında yaşıyorlar."],
  ["house-hunting", "n", "ev arama", "We spent the weekend house-hunting.", "Hafta sonunu ev arayarak geçirdik."],
  ["open-plan", "adj", "açık plan (mekân)", "The flat has an open-plan kitchen.", "Dairenin açık plan bir mutfağı var."],
  ["en suite", "adj", "odaya bağlı banyolu", "The master bedroom has an en suite bathroom.", "Ebeveyn yatak odasında ebeveyn banyosu var."],
  ["property ladder", "n", "(ev sahibi olma) merdiveni", "It's hard to get on the property ladder.", "Ev sahibi olmanın ilk basamağına adım atmak zor."],
  ["rent control", "n", "kira denetimi", "Some cities have introduced rent control.", "Bazı şehirler kira denetimi getirdi."],

  // Set 20 — Transport & infrastructure
  ["infrastructure project", "n", "altyapı projesi", "The new bridge is a major infrastructure project.", "Yeni köprü büyük bir altyapı projesi."],
  ["high-speed rail", "n", "hızlı tren", "High-speed rail connects Ankara and Konya.", "Hızlı tren Ankara ile Konya'yı bağlıyor."],
  ["toll", "n", "geçiş ücreti", "You have to pay a toll on this motorway.", "Bu otoyolda geçiş ücreti ödemen gerekiyor."],
  ["bypass", "n", "çevre yolu", "The bypass takes traffic away from the centre.", "Çevre yolu trafiği merkezden uzaklaştırıyor."],
  ["junction", "n", "kavşak", "Turn left at the next junction.", "Bir sonraki kavşaktan sola dön."],
  ["lane", "n", "şerit", "Stay in the right lane.", "Sağ şeritte kal."],
  ["tailback", "n", "araç kuyruğu", "There's a five-kilometre tailback on the bridge.", "Köprüde beş kilometrelik araç kuyruğu var."],
  ["gridlock", "n", "trafik kilitlenmesi", "The city was in gridlock after the accident.", "Kazadan sonra şehir trafiği kilitlendi."],
  ["public transport network", "n", "toplu taşıma ağı", "Izmir has a good public transport network.", "İzmir'in iyi bir toplu taşıma ağı var."],
  ["timetable change", "n", "sefer saati değişikliği", "Check the timetable changes for the holiday.", "Bayram için sefer saati değişikliklerini kontrol et."],
  ["connecting flight", "n", "aktarmalı uçuş", "I missed my connecting flight in Istanbul.", "İstanbul'daki aktarmalı uçuşumu kaçırdım."],
  ["layover", "n", "aktarma bekleme süresi", "We had a six-hour layover in Doha.", "Doha'da altı saatlik aktarma beklememiz vardı."],
  ["fuel consumption", "n", "yakıt tüketimi", "This car has low fuel consumption.", "Bu arabanın yakıt tüketimi düşük."],
  ["ride-sharing", "n", "araç paylaşımı", "Ride-sharing apps are popular in big cities.", "Araç paylaşım uygulamaları büyük şehirlerde popüler."],
  ["e-scooter", "n", "elektrikli scooter", "E-scooters are everywhere in Istanbul.", "Elektrikli scooterlar İstanbul'da her yerde."],
  ["road rage", "n", "trafik öfkesi", "Road rage causes many fights.", "Trafik öfkesi birçok kavgaya yol açıyor."],
  ["breathalyser", "n", "alkolmetre", "The police used a breathalyser.", "Polis alkolmetre kullandı."],
  ["collide", "v", "çarpışmak", "Two lorries collided on the motorway.", "Otoyolda iki kamyon çarpıştı."],
  ["divert", "v", "(trafiği) başka yöne yönlendirmek", "Traffic was diverted because of roadworks.", "Yol çalışması nedeniyle trafik başka yöne yönlendirildi."],
  ["roadworks", "n", "yol çalışması", "Roadworks are causing delays.", "Yol çalışmaları gecikmelere neden oluyor."],
];
