import type { LexiconEntry } from "../types";

/** B2 sets 66–70: prefixes & word building, reactions, trends & graphs, risk & safety, natural expressions. */
export const B2_PART14: LexiconEntry[] = [
  // Set 66 — Prefixes & word building
  ["underestimate", "v", "hafife almak, küçümsemek", "Never underestimate your opponent.", "Rakibini asla hafife alma."],
  ["overestimate", "v", "gözünde büyütmek, fazla tahmin etmek", "I overestimated how much time I had.", "Ne kadar vaktim olduğunu fazla tahmin ettim."],
  ["overlook", "v", "gözden kaçırmak; (manzaraya) bakmak", "I overlooked a small mistake.", "Küçük bir hatayı gözden kaçırdım."],
  ["outnumber", "v", "sayıca üstün olmak", "Women outnumber men in the class.", "Sınıfta kadınlar erkeklerden sayıca fazla."],
  ["outgrow", "v", "(büyüyüp) sığmamak, geride bırakmak", "Children quickly outgrow their shoes.", "Çocuklar ayakkabılarını çabucak küçük getirir."],
  ["outweigh", "v", "ağır basmak", "The benefits outweigh the risks.", "Faydalar risklerden ağır basıyor."],
  ["rethink", "v", "yeniden düşünmek", "We need to rethink our strategy.", "Stratejimizi yeniden düşünmeliyiz."],
  ["reassure", "v", "içini rahatlatmak, güven vermek", "The doctor reassured me that it wasn't serious.", "Doktor ciddi olmadığını söyleyerek içimi rahatlattı."],
  ["mismanage", "v", "kötü yönetmek", "The company was badly mismanaged.", "Şirket çok kötü yönetildi."],
  ["misconception", "n", "yanlış kanı", "It's a common misconception that bats are blind.", "Yarasaların kör olduğu yaygın bir yanlış kanıdır."],
  ["disapprove", "v", "onaylamamak, hoş görmemek", "My father disapproves of tattoos.", "Babam dövmeleri hoş görmez."],
  ["discontinue", "v", "(üretimi) durdurmak", "This model has been discontinued.", "Bu modelin üretimi durduruldu."],
  ["irresponsible", "adj", "sorumsuz", "It was irresponsible to leave the child alone.", "Çocuğu yalnız bırakmak sorumsuzluktu."],
  ["irrelevant", "adj", "alakasız", "Your comment is irrelevant.", "Yorumun konuyla alakasız."],
  ["illogical", "adj", "mantıksız", "His argument is completely illogical.", "Argümanı tamamen mantıksız."],
  ["inaccurate", "adj", "yanlış, hatalı", "The report contains inaccurate information.", "Rapor hatalı bilgiler içeriyor."],
  ["unprecedented", "adj", "eşi görülmemiş", "The heatwave was unprecedented.", "Sıcak hava dalgası eşi görülmemiş boyuttaydı."],
  ["counterproductive", "adj", "ters etki yapan", "Punishment can be counterproductive.", "Ceza ters etki yapabilir."],
  ["multitask", "v", "aynı anda birden fazla iş yapmak", "I'm not good at multitasking.", "Aynı anda birden fazla iş yapmakta iyi değilim."],
  ["post-war", "adj", "savaş sonrası", "The city was rebuilt in the post-war years.", "Şehir savaş sonrası yıllarda yeniden inşa edildi."],

  // Set 67 — Reactions
  ["astonish", "v", "hayrete düşürmek", "Her talent astonished everyone.", "Yeteneği herkesi hayrete düşürdü."],
  ["bewilder", "v", "şaşkına çevirmek", "The instructions bewildered me.", "Talimatlar beni şaşkına çevirdi."],
  ["dismay", "n", "dehşet, büyük hayal kırıklığı", "To our dismay, the museum was closed.", "Büyük hayal kırıklığımızla müze kapalıydı."],
  ["outrage", "n", "öfke, infial", "The decision caused public outrage.", "Karar kamuoyunda infiale yol açtı."],
  ["resent", "v", "içerlemek, kızmak", "He resents being told what to do.", "Ne yapacağının söylenmesine içerliyor."],
  ["dread", "v", "çok korkmak, (bir şeyden) ürkmek", "I dread going to the dentist.", "Dişçiye gitmekten çok korkuyorum."],
  ["cherish", "v", "(değerini bilip) el üstünde tutmak", "I cherish the memories of my childhood.", "Çocukluk anılarımı çok değerli tutarım."],
  ["long for", "pv", "hasret çekmek, çok istemek", "She longed for a quiet life.", "Sakin bir hayata hasret çekiyordu."],
  ["be moved", "phr", "duygulanmak", "I was deeply moved by the film.", "Filmden çok duygulandım."],
  ["be taken aback", "phr", "şaşırıp kalmak", "I was taken aback by his rudeness.", "Kabalığı karşısında şaşırıp kaldım."],
  ["burst into tears", "phr", "birden ağlamaya başlamak", "She burst into tears when she heard the news.", "Haberi duyunca ağlamaya başladı."],
  ["burst out laughing", "phr", "kahkahayı basmak", "We all burst out laughing.", "Hepimiz kahkahayı bastık."],
  ["keep a straight face", "phr", "gülmemek için kendini tutmak", "I couldn't keep a straight face.", "Gülmemek için kendimi tutamadım."],
  ["sigh with relief", "phr", "rahat bir nefes almak", "She sighed with relief when she passed.", "Geçince rahat bir nefes aldı."],
  ["shrug", "v", "omuz silkmek", "He just shrugged and walked away.", "Sadece omuz silkti ve uzaklaştı."],
  ["frown", "v", "kaşlarını çatmak", "The teacher frowned at me.", "Öğretmen bana kaşlarını çattı."],
  ["grin", "v", "sırıtmak, geniş geniş gülümsemek", "He grinned when he saw his score.", "Puanını görünce sırıttı."],
  ["blush", "v", "kızarmak (utanıp)", "She blushed when he complimented her.", "İltifat edince kızardı."],
  ["tremble", "v", "titremek", "My hands were trembling.", "Ellerim titriyordu."],
  ["gasp", "v", "(şaşkınlıkla) nefesi kesilmek", "The audience gasped in surprise.", "Seyircilerin şaşkınlıktan nefesi kesildi."],

  // Set 68 — Trends & graphs
  ["peak", "v", "zirveye ulaşmak", "Sales peaked in December.", "Satışlar aralıkta zirveye ulaştı."],
  ["level off", "pv", "sabitlenmek, dengelenmek", "Prices have levelled off.", "Fiyatlar sabitlendi."],
  ["surge", "n", "ani artış, dalga", "There was a surge in demand.", "Talepte ani bir artış oldu."],
  ["steady", "adj", "istikrarlı, düzenli", "There has been a steady increase in tourists.", "Turistlerde istikrarlı bir artış var."],
  ["gradual", "adj", "kademeli, aşamalı", "We saw a gradual decline in sales.", "Satışlarda kademeli bir düşüş gördük."],
  ["dramatic", "adj", "çarpıcı, büyük", "There was a dramatic fall in prices.", "Fiyatlarda çarpıcı bir düşüş oldu."],
  ["fluctuation", "n", "dalgalanma", "Fluctuations in currency affect prices.", "Kurdaki dalgalanmalar fiyatları etkiliyor."],
  ["upward trend", "n", "yükseliş eğilimi", "House prices show an upward trend.", "Konut fiyatları yükseliş eğilimi gösteriyor."],
  ["downward trend", "n", "düşüş eğilimi", "The birth rate shows a downward trend.", "Doğum oranı düşüş eğilimi gösteriyor."],
  ["remain stable", "phr", "sabit kalmak", "Unemployment remained stable.", "İşsizlik sabit kaldı."],
  ["bar chart", "n", "sütun grafik", "The bar chart compares five countries.", "Sütun grafik beş ülkeyi karşılaştırıyor."],
  ["pie chart", "n", "pasta grafik", "The pie chart shows how money is spent.", "Pasta grafik paranın nasıl harcandığını gösteriyor."],
  ["line graph", "n", "çizgi grafik", "The line graph shows temperature over a year.", "Çizgi grafik bir yıl boyunca sıcaklığı gösteriyor."],
  ["axis", "n", "eksen", "Years are shown on the horizontal axis.", "Yıllar yatay eksende gösteriliyor."],
  ["respectively", "adv", "sırasıyla", "Ali and Ayşe scored 80 and 90 respectively.", "Ali ve Ayşe sırasıyla 80 ve 90 aldı."],
  ["account for 20%", "phr", "%20'sini oluşturmak", "Young people account for 20% of voters.", "Gençler seçmenlerin %20'sini oluşturuyor."],
  ["double in size", "phr", "iki katına çıkmak (büyüklük)", "The city has doubled in size.", "Şehir iki katına çıktı."],
  ["a fraction of", "phr", "…nın küçük bir kısmı", "It costs a fraction of the price.", "Fiyatın küçük bir kısmına mal oluyor."],
  ["on average", "phr", "ortalama olarak", "On average, people sleep seven hours.", "İnsanlar ortalama yedi saat uyur."],
  ["the lowest point", "phr", "en düşük nokta", "Sales hit their lowest point in 2020.", "Satışlar 2020'de en düşük noktaya indi."],

  // Set 69 — Risk & safety
  ["hazard", "n", "tehlike, risk", "Wet floors are a hazard.", "Islak zeminler tehlikelidir."],
  ["hazardous", "adj", "tehlikeli", "Hazardous waste must be handled carefully.", "Tehlikeli atıklar dikkatle işlenmeli."],
  ["precaution", "n", "önlem", "As a precaution, wear a helmet.", "Önlem olarak kask tak."],
  ["safeguard", "v", "korumak, güvence altına almak", "We must safeguard children online.", "Çocukları internette korumalıyız."],
  ["emergency exit", "n", "acil çıkış", "Keep the emergency exit clear.", "Acil çıkışı boş tut."],
  ["evacuation", "n", "tahliye", "The evacuation took two hours.", "Tahliye iki saat sürdü."],
  ["assembly point", "n", "toplanma alanı", "Go to the assembly point in the park.", "Parktaki toplanma alanına git."],
  ["first aid kit", "n", "ilk yardım çantası", "Every car should have a first aid kit.", "Her arabada ilk yardım çantası olmalı."],
  ["fire extinguisher", "n", "yangın söndürücü", "Do you know how to use a fire extinguisher?", "Yangın söndürücüyü nasıl kullanacağını biliyor musun?"],
  ["risk assessment", "n", "risk değerlendirmesi", "We did a risk assessment before the trip.", "Geziden önce risk değerlendirmesi yaptık."],
  ["health and safety", "n", "iş sağlığı ve güvenliği", "Health and safety rules are strict here.", "Burada iş sağlığı ve güvenliği kuralları katı."],
  ["protective gear", "n", "koruyucu ekipman", "Workers must wear protective gear.", "İşçiler koruyucu ekipman giymeli."],
  ["life jacket", "n", "can yeleği", "Put on a life jacket on the boat.", "Teknede can yeleği giy."],
  ["at risk", "phr", "risk altında", "Elderly people are most at risk.", "En çok yaşlılar risk altında."],
  ["safety net", "n", "güvenlik ağı, güvence", "Savings are a safety net.", "Birikim bir güvencedir."],
  ["near miss", "n", "kıl payı atlatılan kaza", "It was a near miss — the car almost hit us.", "Kıl payı atlattık, araba neredeyse bize çarpıyordu."],
  ["reckless driving", "n", "pervasız sürüş", "He was fined for reckless driving.", "Pervasız sürüşten ceza aldı."],
  ["on standby", "phr", "hazırda, beklemede", "Ambulances are on standby.", "Ambulanslar hazırda bekliyor."],
  ["drill", "n", "tatbikat", "We have an earthquake drill twice a year.", "Yılda iki kez deprem tatbikatı yapıyoruz."],
  ["better safe than sorry", "phr", "sonradan pişman olmaktansa tedbirli olmak iyidir", "Take an umbrella — better safe than sorry.", "Şemsiye al, tedbirli olmak iyidir."],

  // Set 70 — Natural expressions
  ["it's high time", "phr", "…nin zamanı çoktan geldi", "It's high time you found a job.", "İş bulmanın zamanı çoktan geldi."],
  ["I'd rather not", "phr", "yapmasam daha iyi", "I'd rather not talk about it.", "Bunun hakkında konuşmasam daha iyi."],
  ["I wouldn't mind", "phr", "hiç fena olmaz, isterim", "I wouldn't mind a cup of tea.", "Bir fincan çay hiç fena olmaz."],
  ["be on the safe side", "phr", "ne olur ne olmaz", "I'll leave early to be on the safe side.", "Ne olur ne olmaz, erken çıkacağım."],
  ["for what it's worth", "phr", "ne kadar işine yarar bilmem ama", "For what it's worth, I think you did well.", "Ne kadar işine yarar bilmem ama bence iyi iş çıkardın."],
  ["it's not the end of the world", "phr", "dünyanın sonu değil", "You failed one test — it's not the end of the world.", "Bir sınavda kaldın, dünyanın sonu değil."],
  ["mind you", "phr", "ama şunu da söyleyeyim", "It's expensive. Mind you, it's very good.", "Pahalı. Ama şunu da söyleyeyim, çok iyi."],
  ["come what may", "phr", "ne olursa olsun", "Come what may, I'll finish this course.", "Ne olursa olsun bu kursu bitireceğim."],
  ["as it happens", "phr", "tesadüfe bakın ki", "As it happens, I know the owner.", "Tesadüfe bakın ki sahibini tanıyorum."],
  ["if all else fails", "phr", "hiçbir şey işe yaramazsa", "If all else fails, call a technician.", "Hiçbir şey işe yaramazsa bir teknisyen çağır."],
  ["you never know", "phr", "belli olmaz", "Buy a ticket — you never know!", "Bir bilet al, belli olmaz!"],
  ["that's the last thing I need", "phr", "bir bu eksikti", "A flat tyre? That's the last thing I need!", "Lastik mi patladı? Bir bu eksikti!"],
  ["I've had enough", "phr", "bıktım, yeter artık", "I've had enough of this noise.", "Bu gürültüden bıktım."],
  ["it's worth a try", "phr", "denemeye değer", "It might not work, but it's worth a try.", "İşe yaramayabilir ama denemeye değer."],
  ["it slipped my mind", "phr", "aklımdan çıktı", "Sorry, it completely slipped my mind.", "Üzgünüm, tamamen aklımdan çıktı."],
  ["I'm not in the mood", "phr", "havamda değilim", "I'm not in the mood for a party.", "Parti havamda değilim."],
  ["that makes two of us", "phr", "ben de öyle", "I'm exhausted. — That makes two of us.", "Çok yorgunum. — Ben de öyle."],
  ["what a small world", "phr", "dünya ne kadar küçük", "You know my cousin? What a small world!", "Kuzenimi tanıyor musun? Dünya ne kadar küçük!"],
  ["let's face it", "phr", "kabul edelim", "Let's face it, we're not going to win.", "Kabul edelim, kazanamayacağız."],
  ["so to speak", "phr", "tabiri caizse", "He's the brain of the team, so to speak.", "Tabiri caizse takımın beyni o."],
];
