import type { LexiconEntry } from "../types";

/** B2 sets 11–15: personal finance, marketing, consumer society, law, politics. */
export const B2_PART3: LexiconEntry[] = [
  // Set 11 — Personal finance
  ["overdraft", "n", "ek hesap, hesaptan fazla çekilen para", "I'm using my overdraft this month.", "Bu ay ek hesabımı kullanıyorum."],
  ["savings account", "n", "tasarruf hesabı", "I put 10% of my salary into a savings account.", "Maaşımın %10'unu tasarruf hesabına koyuyorum."],
  ["expenditure", "n", "harcama, gider", "Keep your expenditure below your income.", "Giderlerini gelirinin altında tut."],
  ["disposable income", "n", "harcanabilir gelir", "Young people have less disposable income.", "Gençlerin harcanabilir geliri daha az."],
  ["frugal", "adj", "tutumlu, idareli", "My grandparents lived a frugal life.", "Büyükannemler idareli bir hayat yaşadı."],
  ["extravagant", "adj", "savurgan, müsrif", "Buying a new car every year is extravagant.", "Her yıl yeni araba almak savurganlık."],
  ["splash out", "pv", "(bir şeye) bol para harcamak", "We splashed out on a nice hotel.", "Güzel bir otele bol para harcadık."],
  ["tighten your belt", "phr", "kemerleri sıkmak", "We'll have to tighten our belts this year.", "Bu yıl kemerleri sıkmamız gerekecek."],
  ["be in debt", "phr", "borçlu olmak", "Many students are in debt after university.", "Birçok öğrenci üniversiteden sonra borçlu."],
  ["pay back", "pv", "(borcu) geri ödemek", "I'll pay you back next week.", "Sana gelecek hafta geri öderim."],
  ["credit score", "n", "kredi notu", "A good credit score helps you get a loan.", "İyi bir kredi notu kredi almana yardım eder."],
  ["pension fund", "n", "emeklilik fonu", "She pays into a private pension fund.", "Özel bir emeklilik fonuna ödeme yapıyor."],
  ["inheritance", "n", "miras (para, mülk)", "He received a large inheritance.", "Büyük bir miras aldı."],
  ["windfall", "n", "beklenmedik kazanç", "The bonus was a nice windfall.", "Prim hoş bir beklenmedik kazançtı."],
  ["commission", "n", "komisyon", "The bank charges a commission on transfers.", "Banka havalelerden komisyon alıyor."],
  ["hidden costs", "n", "gizli maliyetler", "Watch out for hidden costs.", "Gizli maliyetlere dikkat et."],
  ["break even", "phr", "başa baş gelmek (kâr/zarar yok)", "The café broke even in its first year.", "Kafe ilk yılında başa baş geldi."],
  ["cut back on", "pv", "azaltmak, kısmak", "We need to cut back on eating out.", "Dışarıda yemeyi azaltmamız gerek."],
  ["live beyond your means", "phr", "gelirinden fazla harcamak", "Credit cards tempt people to live beyond their means.", "Kredi kartları insanları gelirinden fazla harcamaya iter."],
  ["nest egg", "n", "kenardaki birikim, kara gün akçesi", "They've built up a nice nest egg.", "Güzel bir birikim yaptılar."],

  // Set 12 — Marketing & advertising
  ["target audience", "n", "hedef kitle", "Teenagers are the target audience for this ad.", "Bu reklamın hedef kitlesi gençler."],
  ["brand awareness", "n", "marka bilinirliği", "The campaign increased brand awareness.", "Kampanya marka bilinirliğini artırdı."],
  ["endorse", "v", "(ürünü) tanıtmak, desteklemek", "Famous athletes endorse sports brands.", "Ünlü sporcular spor markalarını tanıtır."],
  ["slogan", "n", "slogan", "The company has a catchy slogan.", "Şirketin akılda kalıcı bir sloganı var."],
  ["catchy", "adj", "akılda kalıcı", "That jingle is really catchy.", "O reklam müziği gerçekten akılda kalıcı."],
  ["advertising standards", "n", "reklam standartları", "The advert broke advertising standards.", "Reklam, reklam standartlarını ihlal etti."],
  ["misleading", "adj", "yanıltıcı", "The advert was banned for being misleading.", "Reklam yanıltıcı olduğu için yasaklandı."],
  ["sponsor", "v", "sponsor olmak", "A bank sponsors the football league.", "Bir banka futbol ligine sponsor oluyor."],
  ["commercial", "n", "(TV/radyo) reklam", "They showed the commercial during the final.", "Reklamı final sırasında gösterdiler."],
  ["billboard", "n", "reklam panosu", "There's a huge billboard on the motorway.", "Otoyolda devasa bir reklam panosu var."],
  ["launch", "v", "piyasaya sürmek", "The company launched a new phone.", "Şirket yeni bir telefon piyasaya sürdü."],
  ["market research", "n", "pazar araştırması", "Market research showed a demand for vegan snacks.", "Pazar araştırması vegan atıştırmalıklara talep olduğunu gösterdi."],
  ["niche", "n", "niş, özel alan", "They found a niche in eco-friendly toys.", "Çevre dostu oyuncaklarda bir niş buldular."],
  ["word of mouth", "phr", "kulaktan kulağa", "The restaurant became popular by word of mouth.", "Restoran kulaktan kulağa yayılarak popüler oldu."],
  ["viral", "adj", "(internette) hızla yayılan", "The video went viral overnight.", "Video bir gecede viral oldu."],
  ["influencer marketing", "n", "fenomen pazarlaması", "Influencer marketing is growing fast.", "Fenomen pazarlaması hızla büyüyor."],
  ["loyal customer", "n", "sadık müşteri", "Loyal customers get a discount.", "Sadık müşteriler indirim alıyor."],
  ["unique selling point", "n", "benzersiz satış özelliği", "Speed is the app's unique selling point.", "Hız, uygulamanın öne çıkan özelliği."],
  ["hype", "n", "abartılı tanıtım, yaygara", "The film didn't live up to the hype.", "Film abartılı tanıtımın hakkını veremedi."],
  ["publicity", "n", "tanıtım, reklam; kamuoyu ilgisi", "The scandal gave the brand a lot of publicity.", "Skandal markaya çok ilgi kazandırdı."],

  // Set 13 — Consumer society
  ["consumerism", "n", "tüketim kültürü", "Consumerism encourages people to buy more than they need.", "Tüketim kültürü insanları ihtiyacından fazlasını almaya teşvik eder."],
  ["materialistic", "adj", "maddeci", "Society has become more materialistic.", "Toplum daha maddeci oldu."],
  ["status symbol", "n", "statü sembolü", "An expensive phone is a status symbol.", "Pahalı bir telefon statü sembolüdür."],
  ["disposable", "adj", "tek kullanımlık", "Avoid disposable cups.", "Tek kullanımlık bardaklardan kaçın."],
  ["fast fashion", "n", "hızlı moda", "Fast fashion creates huge amounts of waste.", "Hızlı moda devasa miktarda atık yaratır."],
  ["rip-off", "n", "kazık, fahiş fiyat", "Ten euros for a coffee? What a rip-off!", "Bir kahveye on avro mu? Tam kazık!"],
  ["bargain hunter", "n", "indirim avcısı", "Bargain hunters queued outside the shop.", "İndirim avcıları dükkânın önünde kuyruk oldu."],
  ["shop around", "pv", "fiyat karşılaştırmak", "Shop around before you buy insurance.", "Sigorta almadan önce fiyatları karşılaştır."],
  ["consumer rights", "n", "tüketici hakları", "Know your consumer rights.", "Tüketici haklarını bil."],
  ["warranty", "n", "garanti (belgesi)", "The TV has a two-year warranty.", "Televizyonun iki yıllık garantisi var."],
  ["faulty goods", "n", "kusurlu mallar", "You can return faulty goods.", "Kusurlu malları iade edebilirsin."],
  ["overconsumption", "n", "aşırı tüketim", "Overconsumption harms the planet.", "Aşırı tüketim gezegene zarar verir."],
  ["throwaway culture", "n", "at-kullan kültürü", "We live in a throwaway culture.", "At-kullan kültüründe yaşıyoruz."],
  ["ethical", "adj", "etik", "She only buys from ethical brands.", "Sadece etik markalardan alışveriş yapıyor."],
  ["fair trade", "n", "adil ticaret", "This coffee is fair trade.", "Bu kahve adil ticaret ürünü."],
  ["must-have", "n", "olmazsa olmaz ürün", "This bag is the must-have of the season.", "Bu çanta sezonun olmazsa olmazı."],
  ["splurge", "v", "savurganca harcamak", "I splurged on designer shoes.", "Tasarım ayakkabılara para savurdum."],
  ["compulsive", "adj", "kontrol edilemeyen, saplantılı", "He's a compulsive shopper.", "Kontrolsüz alışveriş yapan biri."],
  ["upgrade", "v", "yükseltmek, daha iyisine geçmek", "Do you really need to upgrade your phone?", "Telefonunu gerçekten yenilemen gerekiyor mu?"],
  ["planned obsolescence", "n", "planlı eskitme", "Planned obsolescence makes products break sooner.", "Planlı eskitme ürünlerin daha erken bozulmasına yol açar."],

  // Set 14 — Law
  ["legislation", "n", "mevzuat, yasa", "New legislation protects consumers.", "Yeni mevzuat tüketicileri koruyor."],
  ["enforce", "v", "uygulamak, yürürlüğe koymak", "The police enforce the law.", "Polis yasayı uygular."],
  ["offence", "n", "suç, kabahat", "Driving without a licence is an offence.", "Ehliyetsiz araba kullanmak suçtur."],
  ["offender", "n", "suçlu, fail", "Young offenders are sent to special centres.", "Genç suçlular özel merkezlere gönderiliyor."],
  ["prosecute", "v", "kovuşturmak, dava açmak", "Shoplifters will be prosecuted.", "Hırsızlar hakkında dava açılacaktır."],
  ["defendant", "n", "sanık", "The defendant pleaded not guilty.", "Sanık suçsuz olduğunu savundu."],
  ["witness statement", "n", "tanık ifadesi", "The police took a witness statement.", "Polis tanık ifadesi aldı."],
  ["acquit", "v", "beraat ettirmek", "She was acquitted of all charges.", "Tüm suçlamalardan beraat etti."],
  ["convict", "v", "mahkûm etmek", "He was convicted of fraud.", "Dolandırıcılıktan mahkûm edildi."],
  ["appeal", "n", "temyiz, itiraz", "They lost the appeal.", "Temyizi kaybettiler."],
  ["charge", "n", "suçlama", "He faces a charge of theft.", "Hırsızlık suçlamasıyla karşı karşıya."],
  ["lawsuit", "n", "dava", "The company is facing a lawsuit.", "Şirket bir davayla karşı karşıya."],
  ["sue", "v", "dava etmek", "She sued the hospital for negligence.", "İhmal nedeniyle hastaneyi dava etti."],
  ["compensation", "n", "tazminat", "The victims received compensation.", "Mağdurlar tazminat aldı."],
  ["loophole", "n", "(yasal) boşluk", "They used a loophole to avoid tax.", "Vergiden kaçmak için yasal bir boşluk kullandılar."],
  ["deterrent", "n", "caydırıcı", "Is prison an effective deterrent?", "Hapis etkili bir caydırıcı mı?"],
  ["community service", "n", "kamu hizmeti cezası", "He was sentenced to community service.", "Kamu hizmeti cezasına çarptırıldı."],
  ["parole", "n", "şartlı tahliye", "She was released on parole.", "Şartlı tahliyeyle serbest bırakıldı."],
  ["jury", "n", "jüri", "The jury took two days to decide.", "Jürinin karar vermesi iki gün sürdü."],
  ["take legal action", "phr", "yasal yola başvurmak", "We may take legal action against the landlord.", "Ev sahibine karşı yasal yola başvurabiliriz."],

  // Set 15 — Politics & government
  ["policy", "n", "politika, siyaset (plan)", "The government announced a new housing policy.", "Hükümet yeni bir konut politikası açıkladı."],
  ["legislature", "n", "yasama organı", "The legislature passed the bill.", "Yasama organı tasarıyı kabul etti."],
  ["parliament", "n", "meclis, parlamento", "Parliament meets in Ankara.", "Meclis Ankara'da toplanır."],
  ["referendum", "n", "referandum", "The country held a referendum.", "Ülke bir referandum yaptı."],
  ["coalition", "n", "koalisyon", "A coalition government was formed.", "Bir koalisyon hükümeti kuruldu."],
  ["opposition", "n", "muhalefet", "The opposition criticised the budget.", "Muhalefet bütçeyi eleştirdi."],
  ["manifesto", "n", "seçim bildirgesi", "The party published its manifesto.", "Parti seçim bildirgesini yayımladı."],
  ["constituency", "n", "seçim bölgesi", "She represents a rural constituency.", "Kırsal bir seçim bölgesini temsil ediyor."],
  ["ballot", "n", "oy pusulası", "Voters put their ballots in the box.", "Seçmenler oy pusulalarını sandığa attı."],
  ["turnout", "n", "katılım oranı (seçim)", "Turnout was over 80%.", "Katılım oranı %80'in üzerindeydi."],
  ["campaign trail", "n", "seçim kampanyası turu", "The candidates are on the campaign trail.", "Adaylar seçim kampanyası turunda."],
  ["lobby", "v", "lobi yapmak", "Environmental groups lobbied for the law.", "Çevre grupları yasa için lobi yaptı."],
  ["reform", "n", "reform", "The education system needs reform.", "Eğitim sisteminin reforma ihtiyacı var."],
  ["corruption", "n", "yolsuzluk", "The minister resigned over corruption claims.", "Bakan yolsuzluk iddiaları nedeniyle istifa etti."],
  ["transparency", "n", "şeffaflık", "Citizens demand more transparency.", "Vatandaşlar daha fazla şeffaflık talep ediyor."],
  ["accountability", "n", "hesap verebilirlik", "Politicians must accept accountability.", "Siyasetçiler hesap verebilirliği kabul etmeli."],
  ["grassroots", "adj", "tabandan gelen", "It started as a grassroots movement.", "Tabandan gelen bir hareket olarak başladı."],
  ["left-wing", "adj", "sol görüşlü", "She writes for a left-wing newspaper.", "Sol görüşlü bir gazeteye yazıyor."],
  ["right-wing", "adj", "sağ görüşlü", "The right-wing parties won more seats.", "Sağ görüşlü partiler daha fazla sandalye kazandı."],
  ["head of state", "n", "devlet başkanı", "The head of state visited Japan.", "Devlet başkanı Japonya'yı ziyaret etti."],
];
