import type { LexiconEntry } from "../types";

/** B2 sets 46–50: body idioms, everyday idioms, sport, travel, dining. */
export const B2_PART10: LexiconEntry[] = [
  // Set 46 — Idioms with the body
  ["a sight for sore eyes", "phr", "görmek ne güzel, göz aydınlığı", "After a long trip, home is a sight for sore eyes.", "Uzun bir yolculuktan sonra evi görmek ne güzel."],
  ["pull someone's leg", "phr", "birine şaka yapmak, işletmek", "Relax, I'm just pulling your leg.", "Rahatla, sadece seni işletiyorum."],
  ["keep your chin up", "phr", "moralini bozmamak", "Keep your chin up — things will get better.", "Moralini bozma, işler düzelecek."],
  ["give someone a hand", "phr", "birine yardım etmek", "Can you give me a hand with these boxes?", "Bu kutularla bana yardım eder misin?"],
  ["get cold feet", "phr", "son anda cesaretini kaybetmek", "He got cold feet before the wedding.", "Düğünden önce son anda cesaretini kaybetti."],
  ["give someone the cold shoulder", "phr", "birine soğuk davranmak", "She gave me the cold shoulder at the party.", "Partide bana soğuk davrandı."],
  ["have a lot on your plate", "phr", "başı iş ile dolu olmak", "I have a lot on my plate this month.", "Bu ay başım iş ile dolu."],
  ["bite your tongue", "phr", "dilini tutmak", "I wanted to argue but I bit my tongue.", "Tartışmak istedim ama dilimi tuttum."],
  ["face the music", "phr", "sonuçlarına katlanmak", "You made the mistake — now face the music.", "Hatayı sen yaptın, şimdi sonuçlarına katlan."],
  ["put your foot down", "phr", "kesin tavır koymak", "My mum put her foot down about screen time.", "Annem ekran süresi konusunda kesin tavır koydu."],
  ["put your foot in it", "phr", "pot kırmak, gaf yapmak", "I really put my foot in it when I mentioned her ex.", "Eski sevgilisinden bahsedince resmen pot kırdım."],
  ["off the top of my head", "phr", "hemen aklıma gelen, düşünmeden", "Off the top of my head, I'd say fifty people.", "Hemen aklıma gelen, elli kişi derim."],
  ["head over heels", "phr", "sırılsıklam (âşık)", "He's head over heels in love.", "Sırılsıklam âşık."],
  ["have your heart set on", "phr", "gönlünü …e kaptırmak, çok istemek", "She has her heart set on studying abroad.", "Yurt dışında okumayı çok istiyor."],
  ["get something off your chest", "phr", "içini dökmek", "I need to get this off my chest.", "İçimi dökmem gerek."],
  ["turn a blind eye", "phr", "görmezden gelmek", "The teacher turned a blind eye to the noise.", "Öğretmen gürültüyü görmezden geldi."],
  ["my lips are sealed", "phr", "ağzım sıkıdır, kimseye söylemem", "Don't worry — my lips are sealed.", "Merak etme, kimseye söylemem."],
  ["stick your neck out", "phr", "riske girmek (birini savunmak için)", "She stuck her neck out for me.", "Benim için riske girdi."],
  ["be all ears", "phr", "can kulağıyla dinlemek", "Tell me everything — I'm all ears.", "Her şeyi anlat, can kulağıyla dinliyorum."],
  ["break a leg", "phr", "bol şans (sahne öncesi)", "Break a leg tonight!", "Bu akşam bol şans!"],

  // Set 47 — Everyday idioms
  ["the ball is in your court", "phr", "top sende", "I've made my offer — the ball is in your court.", "Teklifimi yaptım, top sende."],
  ["in hot water", "phr", "başı dertte", "He's in hot water with his boss.", "Patronuyla başı dertte."],
  ["a blessing in disguise", "phr", "her işte bir hayır var", "Losing that job was a blessing in disguise.", "O işi kaybetmek aslında hayırlı oldu."],
  ["call it a day", "phr", "bugünlük paydos etmek", "Let's call it a day.", "Bugünlük paydos edelim."],
  ["cut corners", "phr", "işi baştan savma yapmak", "Don't cut corners on safety.", "Güvenlik konusunda işi baştan savma yapma."],
  ["get the hang of", "phr", "alışmak, işi kapmak", "You'll soon get the hang of it.", "Yakında işi kaparsın."],
  ["hit the nail on the head", "phr", "tam üstüne basmak", "You've hit the nail on the head.", "Tam üstüne bastın."],
  ["let the cat out of the bag", "phr", "baklayı ağzından çıkarmak", "Who let the cat out of the bag about the party?", "Parti konusunda baklayı ağzından kim çıkardı?"],
  ["miss the boat", "phr", "fırsatı kaçırmak", "Book now or you'll miss the boat.", "Şimdi ayırt, yoksa fırsatı kaçırırsın."],
  ["on the fence", "phr", "kararsız", "I'm still on the fence about the job.", "İş konusunda hâlâ kararsızım."],
  ["out of the blue", "phr", "birdenbire, beklenmedik şekilde", "She called me out of the blue.", "Birdenbire beni aradı."],
  ["rain cats and dogs", "phr", "bardaktan boşanırcasına yağmak", "It's raining cats and dogs.", "Bardaktan boşanırcasına yağmur yağıyor."],
  ["sit on the fence", "phr", "tarafsız kalmak, taraf seçmemek", "You can't sit on the fence forever.", "Sonsuza kadar taraf seçmeden duramazsın."],
  ["the tip of the iceberg", "phr", "buzdağının görünen kısmı", "These problems are just the tip of the iceberg.", "Bu sorunlar buzdağının sadece görünen kısmı."],
  ["under pressure", "phr", "baskı altında", "I work well under pressure.", "Baskı altında iyi çalışırım."],
  ["up in the air", "phr", "belirsiz, askıda", "Our plans are still up in the air.", "Planlarımız hâlâ belirsiz."],
  ["a drop in the ocean", "phr", "devede kulak", "The donation was a drop in the ocean.", "Bağış devede kulaktı."],
  ["the elephant in the room", "phr", "herkesin bildiği ama konuşulmayan sorun", "Money was the elephant in the room.", "Para, herkesin bildiği ama kimsenin konuşmadığı sorundu."],
  ["kill two birds with one stone", "phr", "bir taşla iki kuş vurmak", "I killed two birds with one stone.", "Bir taşla iki kuş vurdum."],
  ["when pigs fly", "phr", "balık kavağa çıkınca", "He'll clean his room when pigs fly.", "Balık kavağa çıkınca odasını temizler."],

  // Set 48 — Sport
  ["professionalism", "n", "profesyonellik", "The team showed great professionalism.", "Takım büyük profesyonellik gösterdi."],
  ["stamina", "n", "dayanıklılık", "Marathon runners need stamina.", "Maraton koşucularının dayanıklılığa ihtiyacı var."],
  ["agility", "n", "çeviklik", "Goalkeepers need agility.", "Kalecilerin çevikliğe ihtiyacı var."],
  ["sportsmanship", "n", "sportmenlik", "Shaking hands shows good sportsmanship.", "El sıkışmak iyi sportmenlik gösterir."],
  ["underdog", "n", "kazanma şansı az görülen", "Everyone supports the underdog.", "Herkes kazanma şansı az görülen tarafı destekler."],
  ["comeback", "n", "geri dönüş", "The team made an amazing comeback.", "Takım inanılmaz bir geri dönüş yaptı."],
  ["disqualify", "v", "diskalifiye etmek", "She was disqualified for a false start.", "Hatalı çıkış nedeniyle diskalifiye edildi."],
  ["doping", "n", "doping", "He was banned for doping.", "Doping nedeniyle men edildi."],
  ["fixture", "n", "maç (programı)", "The fixtures for next season are out.", "Gelecek sezonun maç programı açıklandı."],
  ["home advantage", "n", "saha avantajı", "They have home advantage tonight.", "Bu akşam saha avantajı onlarda."],
  ["injury time", "n", "uzatma dakikaları", "They scored in injury time.", "Uzatma dakikalarında gol attılar."],
  ["relegation", "n", "küme düşme", "The club is fighting relegation.", "Kulüp küme düşmemek için mücadele ediyor."],
  ["promoted", "adj", "üst lige çıkmış", "The team was promoted to the Süper Lig.", "Takım Süper Lig'e yükseldi."],
  ["season ticket", "n", "kombine bilet", "I bought a season ticket.", "Kombine bilet aldım."],
  ["personal best", "n", "kişisel rekor", "She ran a personal best.", "Kişisel rekorunu koştu."],
  ["hat-trick", "n", "hat-trick (üç gol)", "He scored a hat-trick.", "Hat-trick yaptı."],
  ["level the score", "phr", "skoru eşitlemek", "They levelled the score in the second half.", "İkinci yarıda skoru eşitlediler."],
  ["go the distance", "phr", "sonuna kadar dayanmak", "Can the boxer go the distance?", "Boksör sonuna kadar dayanabilecek mi?"],
  ["neck and neck", "phr", "başa baş", "The two runners were neck and neck.", "İki koşucu başa baştı."],
  ["throw in the towel", "phr", "pes etmek", "Don't throw in the towel yet.", "Henüz pes etme."],

  // Set 49 — Travel
  ["wanderlust", "n", "gezme tutkusu", "Her wanderlust took her to 40 countries.", "Gezme tutkusu onu 40 ülkeye götürdü."],
  ["off-peak", "adj", "yoğun olmayan (dönem/saat)", "Off-peak tickets are cheaper.", "Yoğun olmayan saat biletleri daha ucuz."],
  ["peak season", "n", "yoğun sezon", "Hotels are expensive in peak season.", "Oteller yoğun sezonda pahalı."],
  ["all-inclusive", "adj", "her şey dahil", "We stayed at an all-inclusive resort.", "Her şey dahil bir tatil köyünde kaldık."],
  ["stopover", "n", "ara durak, mola", "We had a two-day stopover in Dubai.", "Dubai'de iki günlük bir ara durak yaptık."],
  ["jet-lagged", "adj", "saat farkı yorgunu", "I'm still jet-lagged after the flight.", "Uçuştan sonra hâlâ saat farkı yorgunuyum."],
  ["overbooked", "adj", "fazla rezervasyon alınmış", "The flight was overbooked.", "Uçuşa fazla rezervasyon alınmıştı."],
  ["upgrade", "n", "üst sınıfa geçiş", "We got a free upgrade to business class.", "Bedava business sınıfına geçiş yaptık."],
  ["travel insurance", "n", "seyahat sigortası", "Don't forget travel insurance.", "Seyahat sigortasını unutma."],
  ["exotic", "adj", "egzotik", "They went on an exotic holiday.", "Egzotik bir tatile gittiler."],
  ["unspoilt", "adj", "bozulmamış, el değmemiş", "The island has unspoilt beaches.", "Adanın el değmemiş plajları var."],
  ["overrun with tourists", "phr", "turist istilasına uğramış", "The old town is overrun with tourists in August.", "Eski şehir ağustosta turist istilasına uğruyor."],
  ["eco-tourism", "n", "ekoturizm", "Eco-tourism is growing in the Black Sea region.", "Karadeniz'de ekoturizm büyüyor."],
  ["hitchhike", "v", "otostop çekmek", "They hitchhiked across Europe.", "Avrupa'yı otostopla dolaştılar."],
  ["globetrotter", "n", "dünya gezgini", "She's a real globetrotter.", "Gerçek bir dünya gezgini."],
  ["tourist trap", "n", "turist tuzağı", "That restaurant is a tourist trap.", "O restoran bir turist tuzağı."],
  ["get away from it all", "phr", "her şeyden uzaklaşmak", "We went to the mountains to get away from it all.", "Her şeyden uzaklaşmak için dağlara gittik."],
  ["hit the road", "phr", "yola koyulmak", "Let's hit the road early.", "Erkenden yola koyulalım."],
  ["travel light", "phr", "az eşyayla seyahat etmek", "I always travel light.", "Her zaman az eşyayla seyahat ederim."],
  ["sightseer", "n", "gezmeye gelen turist", "The square was full of sightseers.", "Meydan gezmeye gelen turistlerle doluydu."],

  // Set 50 — Dining
  ["cuisine", "n", "mutfak (yemek kültürü)", "Turkish cuisine is famous worldwide.", "Türk mutfağı dünyaca ünlü."],
  ["gourmet", "adj", "gurme", "They opened a gourmet burger bar.", "Gurme bir burger restoranı açtılar."],
  ["appetising", "adj", "iştah açıcı", "The dish looks very appetising.", "Yemek çok iştah açıcı görünüyor."],
  ["bland", "adj", "tatsız, yavan", "The soup was rather bland.", "Çorba epey yavandı."],
  ["savoury", "adj", "tuzlu (tatlı olmayan)", "I prefer savoury snacks to sweets.", "Tuzlu atıştırmalıkları tatlılara tercih ederim."],
  ["succulent", "adj", "sulu, lezzetli (et, meyve)", "The lamb was succulent.", "Kuzu eti sulu ve lezzetliydi."],
  ["mouth-watering", "adj", "ağız sulandıran", "The bakery smells mouth-watering.", "Fırın ağız sulandıran bir koku yayıyor."],
  ["stodgy", "adj", "ağır (yemek)", "The pudding was heavy and stodgy.", "Puding ağır ve doyurucuydu."],
  ["overpriced menu", "n", "fahiş fiyatlı menü", "The view is nice but the menu is overpriced.", "Manzara güzel ama menü fahiş fiyatlı."],
  ["set menu", "n", "fiks menü", "The set menu includes three courses.", "Fiks menü üç çeşitten oluşuyor."],
  ["à la carte", "adj", "alakart", "We ordered à la carte.", "Alakart sipariş verdik."],
  ["dietary requirements", "n", "beslenme gereksinimleri", "Please tell us about any dietary requirements.", "Lütfen beslenme gereksinimlerinizi bize bildirin."],
  ["food poisoning", "n", "gıda zehirlenmesi", "He got food poisoning from the seafood.", "Deniz ürünlerinden gıda zehirlenmesi geçirdi."],
  ["street food", "n", "sokak yemeği", "Simit is Istanbul's favourite street food.", "Simit İstanbul'un en sevilen sokak yemeği."],
  ["delicacy", "n", "özel lezzet", "Baklava from Gaziantep is a delicacy.", "Gaziantep baklavası özel bir lezzettir."],
  ["culinary", "adj", "mutfakla ilgili, yemek", "Hatay is a culinary capital.", "Hatay bir gastronomi başkenti."],
  ["tuck in", "pv", "(iştahla) yemeğe başlamak", "Dinner's ready — tuck in!", "Yemek hazır, buyurun başlayın!"],
  ["wolf down", "pv", "yiyip yutmak, hızla yemek", "He wolfed down his lunch.", "Öğle yemeğini yiyip yuttu."],
  ["have a sweet tooth", "phr", "tatlıya düşkün olmak", "I have a real sweet tooth.", "Gerçekten tatlıya düşkünüm."],
  ["foodie", "n", "yemek meraklısı", "Izmir is a paradise for foodies.", "İzmir yemek meraklıları için bir cennet."],
];
