import type { LexiconEntry } from "../types";

/** B2 sets 61–65: space, population & geography, the mind, architecture & design, music & performance. */
export const B2_PART13: LexiconEntry[] = [
  // Set 61 — Space
  ["universe", "n", "evren", "The universe is about 14 billion years old.", "Evren yaklaşık 14 milyar yaşında."],
  ["galaxy", "n", "galaksi", "Our galaxy is called the Milky Way.", "Galaksimizin adı Samanyolu."],
  ["solar system", "n", "güneş sistemi", "Jupiter is the largest planet in the solar system.", "Jüpiter güneş sistemindeki en büyük gezegen."],
  ["orbit", "v", "yörüngede dönmek", "The Moon orbits the Earth.", "Ay Dünya'nın etrafında döner."],
  ["satellite", "n", "uydu", "Türksat is a communications satellite.", "Türksat bir iletişim uydusu."],
  ["telescope", "n", "teleskop", "We looked at Saturn through a telescope.", "Teleskopla Satürn'e baktık."],
  ["spacecraft", "n", "uzay aracı", "The spacecraft landed on Mars.", "Uzay aracı Mars'a indi."],
  ["launch pad", "n", "fırlatma rampası", "The rocket is on the launch pad.", "Roket fırlatma rampasında."],
  ["astronomer", "n", "gökbilimci", "The astronomer discovered a new planet.", "Gökbilimci yeni bir gezegen keşfetti."],
  ["asteroid", "n", "asteroit", "An asteroid passed close to Earth.", "Bir asteroit Dünya'ya yakın geçti."],
  ["comet", "n", "kuyruklu yıldız", "You can see the comet without a telescope.", "Kuyruklu yıldızı teleskopsuz görebilirsin."],
  ["eclipse", "n", "tutulma", "There was a solar eclipse in 2006.", "2006'da bir güneş tutulması vardı."],
  ["light year", "n", "ışık yılı", "The star is ten light years away.", "Yıldız on ışık yılı uzaklıkta."],
  ["atmosphere", "n", "atmosfer", "Mars has a thin atmosphere.", "Mars'ın ince bir atmosferi var."],
  ["space exploration", "n", "uzay keşfi", "Space exploration is very expensive.", "Uzay keşfi çok pahalıdır."],
  ["extraterrestrial", "adj", "dünya dışı", "Is there extraterrestrial life?", "Dünya dışı yaşam var mı?"],
  ["observatory", "n", "gözlemevi", "We visited the observatory at night.", "Gece gözlemevini ziyaret ettik."],
  ["crater", "n", "krater", "The Moon is covered in craters.", "Ay kraterlerle kaplı."],
  ["zero gravity", "n", "sıfır yerçekimi", "Water floats in zero gravity.", "Sıfır yerçekiminde su havada süzülür."],
  ["mission", "n", "görev (uzay)", "The mission lasted six months.", "Görev altı ay sürdü."],

  // Set 62 — Population & geography
  ["demographic", "adj", "demografik", "Demographic changes affect the economy.", "Demografik değişiklikler ekonomiyi etkiler."],
  ["census", "n", "nüfus sayımı", "The census is carried out every ten years.", "Nüfus sayımı on yılda bir yapılır."],
  ["inhabitant", "n", "sakin, yaşayan", "The town has 5,000 inhabitants.", "Kasabanın 5.000 sakini var."],
  ["overpopulation", "n", "aşırı nüfus", "Overpopulation puts pressure on resources.", "Aşırı nüfus kaynaklar üzerinde baskı oluşturur."],
  ["sparsely populated", "adj", "seyrek nüfuslu", "Eastern Anatolia is sparsely populated.", "Doğu Anadolu seyrek nüfuslu."],
  ["rural exodus", "n", "köyden kente göç", "Rural exodus has emptied many villages.", "Köyden kente göç birçok köyü boşalttı."],
  ["natural resources", "n", "doğal kaynaklar", "The country is rich in natural resources.", "Ülke doğal kaynaklar açısından zengin."],
  ["fertile", "adj", "verimli (toprak)", "The Çukurova plain is very fertile.", "Çukurova ovası çok verimli."],
  ["arid", "adj", "kurak", "The region has an arid climate.", "Bölgenin kurak bir iklimi var."],
  ["tropical", "adj", "tropikal", "Bananas grow in tropical climates.", "Muz tropikal iklimlerde yetişir."],
  ["equator", "n", "ekvator", "Countries near the equator are hot.", "Ekvatora yakın ülkeler sıcaktır."],
  ["hemisphere", "n", "yarım küre", "Australia is in the southern hemisphere.", "Avustralya güney yarım kürede."],
  ["latitude", "n", "enlem", "Istanbul is at about 41 degrees latitude.", "İstanbul yaklaşık 41 derece enlemde."],
  ["longitude", "n", "boylam", "Find the city's longitude on the map.", "Şehrin boylamını haritada bul."],
  ["landlocked", "adj", "denize kıyısı olmayan", "Switzerland is a landlocked country.", "İsviçre denize kıyısı olmayan bir ülke."],
  ["border crossing", "n", "sınır kapısı", "There's a long queue at the border crossing.", "Sınır kapısında uzun bir kuyruk var."],
  ["fault line", "n", "fay hattı", "Istanbul lies near a major fault line.", "İstanbul büyük bir fay hattının yakınında."],
  ["seismic", "adj", "sismik", "The region has high seismic activity.", "Bölgede sismik aktivite yüksek."],
  ["tectonic plate", "n", "tektonik levha", "Earthquakes happen when tectonic plates move.", "Depremler tektonik levhalar hareket edince olur."],
  ["topography", "n", "topografya, yüzey şekilleri", "The topography makes building roads difficult.", "Yüzey şekilleri yol yapımını zorlaştırıyor."],

  // Set 63 — The mind
  ["subconscious", "adj", "bilinçaltı", "Dreams may reflect our subconscious fears.", "Rüyalar bilinçaltı korkularımızı yansıtabilir."],
  ["perception", "n", "algı", "Our perception of time changes with age.", "Zaman algımız yaşla değişir."],
  ["cognitive", "adj", "bilişsel", "Puzzles improve cognitive skills.", "Bulmacalar bilişsel becerileri geliştirir."],
  ["memory lapse", "n", "anlık unutkanlık", "I had a memory lapse during the exam.", "Sınavda anlık bir unutkanlık yaşadım."],
  ["willpower", "n", "irade gücü", "It takes willpower to stop smoking.", "Sigarayı bırakmak irade gücü ister."],
  ["self-discipline", "n", "öz disiplin", "Self-discipline is the key to success.", "Öz disiplin başarının anahtarıdır."],
  ["procrastinate", "v", "(işi) ertelemek, sürüncemede bırakmak", "I always procrastinate before exams.", "Sınavlardan önce hep işleri ertelerim."],
  ["procrastination", "n", "erteleme alışkanlığı", "Procrastination is a common problem for students.", "Erteleme öğrenciler için yaygın bir sorundur."],
  ["peer influence", "n", "akran etkisi", "Teenagers are sensitive to peer influence.", "Gençler akran etkisine duyarlıdır."],
  ["conform", "v", "uymak (topluma, kurallara)", "Many people feel pressure to conform.", "Birçok insan topluma uyma baskısı hisseder."],
  ["introverted", "adj", "içe dönük", "Introverted people need time alone.", "İçe dönük insanların yalnız zamana ihtiyacı var."],
  ["extroverted", "adj", "dışa dönük", "Extroverted people gain energy from others.", "Dışa dönük insanlar başkalarından enerji alır."],
  ["phobia", "n", "fobi", "She has a phobia of spiders.", "Örümcek fobisi var."],
  ["obsession", "n", "saplantı", "His obsession with fitness worries me.", "Spora olan saplantısı beni endişelendiriyor."],
  ["compulsion", "n", "dürtü, zorlantı", "He felt a compulsion to check his phone.", "Telefonunu kontrol etme dürtüsü hissetti."],
  ["daydream", "v", "hayal kurmak (dalıp gitmek)", "Stop daydreaming and focus!", "Dalıp gitmeyi bırak ve odaklan!"],
  ["intuition", "n", "sezgi", "Trust your intuition.", "Sezgine güven."],
  ["rationalise", "v", "(mazeretle) haklı göstermek", "He rationalised his bad behaviour.", "Kötü davranışını mazeretlerle haklı göstermeye çalıştı."],
  ["mindset", "n", "zihniyet, bakış açısı", "A positive mindset helps you learn.", "Olumlu bir bakış açısı öğrenmene yardım eder."],
  ["growth mindset", "n", "gelişim odaklı zihniyet", "Teachers encourage a growth mindset.", "Öğretmenler gelişim odaklı zihniyeti teşvik ediyor."],

  // Set 64 — Architecture & design
  ["architecture", "n", "mimari", "Ottoman architecture is famous for its domes.", "Osmanlı mimarisi kubbeleriyle ünlüdür."],
  ["dome", "n", "kubbe", "The dome of Hagia Sophia is huge.", "Ayasofya'nın kubbesi devasa."],
  ["arch", "n", "kemer", "The bridge has three stone arches.", "Köprünün üç taş kemeri var."],
  ["facade", "n", "cephe", "The building has a beautiful facade.", "Binanın güzel bir cephesi var."],
  ["blueprint", "n", "mavi kopya, plan", "The architect showed us the blueprints.", "Mimar bize planları gösterdi."],
  ["layout", "n", "yerleşim planı, düzen", "I like the layout of the flat.", "Dairenin yerleşim planını beğendim."],
  ["minimalist", "adj", "minimalist, sade", "The room has a minimalist design.", "Odanın sade bir tasarımı var."],
  ["ornate", "adj", "süslü, bezemeli", "The palace has ornate ceilings.", "Sarayın süslü tavanları var."],
  ["functional", "adj", "işlevsel", "The furniture is simple and functional.", "Mobilyalar sade ve işlevsel."],
  ["sustainable design", "n", "sürdürülebilir tasarım", "The school is an example of sustainable design.", "Okul sürdürülebilir tasarıma bir örnek."],
  ["listed building", "n", "tescilli yapı", "You can't change a listed building.", "Tescilli bir yapıyı değiştiremezsin."],
  ["landmark building", "n", "simge yapı", "The tower is a landmark building.", "Kule bir simge yapı."],
  ["renovation", "n", "yenileme, tadilat", "The renovation took a year.", "Tadilat bir yıl sürdü."],
  ["construction site", "n", "şantiye", "Wear a helmet on the construction site.", "Şantiyede kask tak."],
  ["earthquake-resistant", "adj", "depreme dayanıklı", "New buildings must be earthquake-resistant.", "Yeni binalar depreme dayanıklı olmalı."],
  ["urban planner", "n", "şehir plancısı", "Urban planners designed the new district.", "Şehir plancıları yeni semti tasarladı."],
  ["interior design", "n", "iç mimari", "She studied interior design.", "İç mimarlık okudu."],
  ["spacious layout", "n", "ferah yerleşim", "The office has a spacious layout.", "Ofisin ferah bir yerleşimi var."],
  ["concrete", "n", "beton", "The building is made of concrete and glass.", "Bina beton ve camdan yapılmış."],
  ["timber", "n", "kereste, ahşap malzeme", "Traditional Black Sea houses are made of timber.", "Geleneksel Karadeniz evleri ahşaptan yapılır."],

  // Set 65 — Music & performance
  ["melody", "n", "melodi, ezgi", "The song has a beautiful melody.", "Şarkının güzel bir melodisi var."],
  ["rhythm", "n", "ritim", "Clap to the rhythm.", "Ritme göre el çırp."],
  ["harmony", "n", "armoni, uyum", "The choir sang in perfect harmony.", "Koro mükemmel bir uyum içinde söyledi."],
  ["lyricist", "n", "söz yazarı", "The lyricist wrote the words in one night.", "Söz yazarı sözleri bir gecede yazdı."],
  ["orchestra", "n", "orkestra", "She plays violin in an orchestra.", "Bir orkestrada keman çalıyor."],
  ["conductor", "n", "orkestra şefi", "The conductor raised his baton.", "Orkestra şefi bagetini kaldırdı."],
  ["choir", "n", "koro", "My mother sings in a choir.", "Annem bir koroda şarkı söylüyor."],
  ["encore", "n", "bis", "The audience shouted for an encore.", "Seyirciler bis diye bağırdı."],
  ["standing ovation", "n", "ayakta alkış", "The pianist got a standing ovation.", "Piyanist ayakta alkışlandı."],
  ["gig economy", "n", "serbest/geçici iş ekonomisi", "Many musicians work in the gig economy.", "Birçok müzisyen geçici işlerle çalışıyor."],
  ["tune in", "pv", "(radyo/TV) açıp dinlemek/izlemek", "Tune in at eight for the concert.", "Konser için saat sekizde kanalımızı açın."],
  ["out of tune", "phr", "akortsuz, falsolu", "The piano is out of tune.", "Piyano akortsuz."],
  ["improvise", "v", "doğaçlama yapmak", "Jazz musicians often improvise.", "Caz müzisyenleri sık sık doğaçlama yapar."],
  ["acoustic", "adj", "akustik", "They played an acoustic set.", "Akustik bir set çaldılar."],
  ["stage fright", "n", "sahne korkusu", "I get terrible stage fright.", "Korkunç bir sahne korkusu yaşarım."],
  ["debut album", "n", "ilk albüm", "Her debut album was a hit.", "İlk albümü hit oldu."],
  ["chart-topping", "adj", "listelerin zirvesindeki", "It was a chart-topping single.", "Listelerin zirvesindeki bir single'dı."],
  ["live performance", "n", "canlı performans", "Their live performance was amazing.", "Canlı performansları muhteşemdi."],
  ["busker", "n", "sokak müzisyeni", "A busker was playing guitar on İstiklal.", "İstiklal'de bir sokak müzisyeni gitar çalıyordu."],
  ["world music", "n", "dünya müziği", "The festival celebrates world music.", "Festival dünya müziğini kutluyor."],
];
