import type { LexiconEntry } from "../types";

/** B2 sets 21–25: medicine, mental health, diet science, scientific research, technology & AI. */
export const B2_PART5: LexiconEntry[] = [
  // Set 21 — Medicine
  ["diagnosis", "n", "teşhis", "The doctor made a quick diagnosis.", "Doktor hızlı bir teşhis koydu."],
  ["diagnose", "v", "teşhis koymak", "She was diagnosed with diabetes.", "Ona diyabet teşhisi konuldu."],
  ["chronic", "adj", "kronik, süreğen", "He suffers from chronic back pain.", "Kronik bel ağrısı çekiyor."],
  ["acute", "adj", "akut, şiddetli", "She was taken to hospital with acute pain.", "Şiddetli ağrıyla hastaneye kaldırıldı."],
  ["contagious", "adj", "bulaşıcı", "Chickenpox is very contagious.", "Su çiçeği çok bulaşıcıdır."],
  ["outbreak", "n", "salgın (başlangıcı)", "There was an outbreak of measles.", "Bir kızamık salgını çıktı."],
  ["epidemic", "n", "salgın", "Obesity is becoming an epidemic.", "Obezite bir salgına dönüşüyor."],
  ["immune system", "n", "bağışıklık sistemi", "Sleep strengthens your immune system.", "Uyku bağışıklık sistemini güçlendirir."],
  ["antibiotic", "n", "antibiyotik", "Antibiotics don't work against viruses.", "Antibiyotikler virüslere karşı işe yaramaz."],
  ["dosage", "n", "doz", "Don't exceed the recommended dosage.", "Önerilen dozu aşma."],
  ["recovery", "n", "iyileşme", "She made a full recovery.", "Tamamen iyileşti."],
  ["relapse", "n", "(hastalık) nüksetme", "He had a relapse after a month.", "Bir ay sonra hastalığı nüksetti."],
  ["prognosis", "n", "(hastalığın) seyri, tahmini", "The prognosis is good.", "Hastalığın seyri iyi görünüyor."],
  ["transplant", "n", "nakil", "She needs a kidney transplant.", "Böbrek nakline ihtiyacı var."],
  ["anaesthetic", "n", "anestezi, uyuşturucu ilaç", "The operation was done under local anaesthetic.", "Ameliyat lokal anesteziyle yapıldı."],
  ["inflammation", "n", "iltihap", "The cream reduces inflammation.", "Krem iltihabı azaltır."],
  ["pandemic", "n", "pandemi, küresel salgın", "The pandemic changed how we work.", "Pandemi çalışma şeklimizi değiştirdi."],
  ["life expectancy", "n", "ortalama yaşam süresi", "Life expectancy has risen in Turkey.", "Türkiye'de ortalama yaşam süresi arttı."],
  ["preventive", "adj", "önleyici", "Preventive medicine saves money.", "Önleyici tıp para tasarrufu sağlar."],
  ["GP (general practitioner)", "n", "aile hekimi, pratisyen hekim", "Make an appointment with your GP.", "Aile hekiminden randevu al."],

  // Set 22 — Mental health
  ["mental health", "n", "ruh sağlığı", "Exercise is good for your mental health.", "Egzersiz ruh sağlığın için iyidir."],
  ["well-balanced", "adj", "dengeli", "She's a well-balanced young woman.", "Dengeli bir genç kadın."],
  ["depression", "n", "depresyon", "Depression is a common illness.", "Depresyon yaygın bir hastalıktır."],
  ["therapist", "n", "terapist", "Talking to a therapist helped me.", "Bir terapistle konuşmak bana yardım etti."],
  ["cope", "v", "başa çıkmak", "She's coping well with the stress.", "Stresle iyi başa çıkıyor."],
  ["coping strategy", "n", "başa çıkma stratejisi", "Breathing exercises are a useful coping strategy.", "Nefes egzersizleri faydalı bir başa çıkma stratejisi."],
  ["panic attack", "n", "panik atak", "He had a panic attack on the plane.", "Uçakta panik atak geçirdi."],
  ["insomnia", "n", "uykusuzluk", "Stress can cause insomnia.", "Stres uykusuzluğa neden olabilir."],
  ["mindfulness", "n", "farkındalık (bilinçli farkındalık)", "Mindfulness helps reduce anxiety.", "Bilinçli farkındalık kaygıyı azaltmaya yardım eder."],
  ["stigma", "n", "damga, önyargı", "There's still a stigma around mental illness.", "Ruhsal hastalıklar konusunda hâlâ bir damgalama var."],
  ["self-care", "n", "öz bakım", "Make time for self-care.", "Öz bakıma zaman ayır."],
  ["emotional", "adj", "duygusal", "It was an emotional goodbye.", "Duygusal bir vedaydı."],
  ["vulnerable", "adj", "savunmasız, kırılgan", "Children are especially vulnerable.", "Çocuklar özellikle savunmasızdır."],
  ["trauma", "n", "travma", "The earthquake left many people with trauma.", "Deprem birçok insanda travma bıraktı."],
  ["counselling", "n", "danışmanlık (psikolojik)", "The school offers free counselling.", "Okul ücretsiz psikolojik danışmanlık sunuyor."],
  ["burn out", "pv", "tükenmek", "If you work like this, you'll burn out.", "Böyle çalışırsan tükenirsin."],
  ["unwind", "v", "gevşemek, rahatlamak", "I unwind by listening to music.", "Müzik dinleyerek rahatlarım."],
  ["recharge your batteries", "phr", "pillerini şarj etmek, dinlenmek", "A weekend away will help you recharge your batteries.", "Bir hafta sonu kaçamağı pillerini şarj etmene yardım eder."],
  ["at breaking point", "phr", "dayanma sınırında", "The nurses are at breaking point.", "Hemşireler dayanma sınırında."],
  ["peace of mind", "n", "iç huzuru", "Insurance gives you peace of mind.", "Sigorta sana iç huzuru verir."],

  // Set 23 — Diet science
  ["nutrient", "n", "besin öğesi", "Vegetables are full of nutrients.", "Sebzeler besin öğeleriyle doludur."],
  ["carbohydrate", "n", "karbonhidrat", "Bread and rice are rich in carbohydrates.", "Ekmek ve pirinç karbonhidrat açısından zengindir."],
  ["metabolism", "n", "metabolizma", "Exercise speeds up your metabolism.", "Egzersiz metabolizmanı hızlandırır."],
  ["deficiency", "n", "eksiklik", "Vitamin D deficiency is common in winter.", "D vitamini eksikliği kışın yaygındır."],
  ["intake", "n", "alım (besin, sıvı)", "Reduce your sugar intake.", "Şeker alımını azalt."],
  ["additive", "n", "katkı maddesi", "This product contains no artificial additives.", "Bu ürün yapay katkı maddesi içermez."],
  ["preservative", "n", "koruyucu madde", "Processed meat is full of preservatives.", "İşlenmiş et koruyucu maddelerle doludur."],
  ["wholefood", "n", "doğal (işlenmemiş) gıda", "Try to eat more wholefoods.", "Daha fazla işlenmemiş gıda yemeye çalış."],
  ["intolerance", "n", "intolerans, hassasiyet", "She has a lactose intolerance.", "Laktoz intoleransı var."],
  ["cholesterol", "n", "kolesterol", "Fried food raises cholesterol.", "Kızartmalar kolesterolü yükseltir."],
  ["obesity", "n", "obezite", "Childhood obesity is rising.", "Çocukluk çağı obezitesi artıyor."],
  ["sugary", "adj", "şekerli", "Avoid sugary drinks.", "Şekerli içeceklerden kaçın."],
  ["nutritious", "adj", "besleyici", "Lentil soup is cheap and nutritious.", "Mercimek çorbası ucuz ve besleyici."],
  ["fad diet", "n", "moda diyet", "Fad diets rarely work in the long term.", "Moda diyetler uzun vadede nadiren işe yarar."],
  ["portion control", "n", "porsiyon kontrolü", "Portion control is key to losing weight.", "Porsiyon kontrolü kilo vermenin anahtarıdır."],
  ["hydrated", "adj", "susuz kalmamış, yeterince sıvı almış", "Stay hydrated in the heat.", "Sıcakta yeterince su iç."],
  ["plant-based", "adj", "bitki bazlı", "Plant-based diets are becoming popular.", "Bitki bazlı beslenme popülerleşiyor."],
  ["supplement", "n", "takviye", "Do you take any vitamin supplements?", "Vitamin takviyesi alıyor musun?"],
  ["binge", "v", "tıkınmak, aşırıya kaçmak", "I binged on chocolate last night.", "Dün gece çikolataya gömüldüm."],
  ["cut out", "pv", "(diyetten) çıkarmak", "I've cut out sugar completely.", "Şekeri tamamen bıraktım."],

  // Set 24 — Scientific research
  ["empirical", "adj", "deneysel, gözleme dayalı", "We need empirical evidence.", "Gözleme dayalı kanıta ihtiyacımız var."],
  ["variable", "n", "değişken", "Temperature is an important variable.", "Sıcaklık önemli bir değişken."],
  ["sample size", "n", "örneklem büyüklüğü", "The sample size was too small.", "Örneklem büyüklüğü çok küçüktü."],
  ["correlation", "n", "korelasyon, ilişki", "There's a correlation between sleep and grades.", "Uyku ile notlar arasında bir ilişki var."],
  ["conduct", "v", "yürütmek (araştırma)", "They conducted a survey of 2,000 people.", "2.000 kişiyle bir anket yürüttüler."],
  ["replicate", "v", "tekrarlamak (deney)", "Other scientists couldn't replicate the results.", "Diğer bilim insanları sonuçları tekrarlayamadı."],
  ["breakthrough discovery", "n", "çığır açan keşif", "It was a breakthrough discovery in genetics.", "Genetikte çığır açan bir keşifti."],
  ["laboratory test", "n", "laboratuvar testi", "Laboratory tests confirmed the result.", "Laboratuvar testleri sonucu doğruladı."],
  ["clinical trial", "n", "klinik deney", "The drug is in clinical trials.", "İlaç klinik deney aşamasında."],
  ["data set", "n", "veri seti", "We analysed a large data set.", "Büyük bir veri setini analiz ettik."],
  ["peer-reviewed", "adj", "hakemli", "Only use peer-reviewed sources.", "Yalnızca hakemli kaynaklar kullan."],
  ["inconclusive", "adj", "sonuçsuz, kesin olmayan", "The results were inconclusive.", "Sonuçlar kesin değildi."],
  ["anomaly", "n", "anormallik, sapma", "The data showed a strange anomaly.", "Veriler garip bir sapma gösterdi."],
  ["formula", "n", "formül", "What's the formula for water?", "Suyun formülü nedir?"],
  ["particle", "n", "parçacık", "Dust particles float in the air.", "Toz parçacıkları havada uçuşuyor."],
  ["molecule", "n", "molekül", "A water molecule has three atoms.", "Bir su molekülünde üç atom vardır."],
  ["genetic", "adj", "genetik", "The disease is genetic.", "Hastalık genetiktir."],
  ["evolution", "n", "evrim", "Darwin developed the theory of evolution.", "Darwin evrim teorisini geliştirdi."],
  ["innovation", "n", "yenilik, inovasyon", "The company is famous for innovation.", "Şirket yenilikçiliğiyle ünlü."],
  ["cutting-edge", "adj", "son teknoloji, en ileri", "They use cutting-edge equipment.", "Son teknoloji ekipman kullanıyorlar."],

  // Set 25 — Technology & AI
  ["algorithm", "n", "algoritma", "The app uses an algorithm to suggest videos.", "Uygulama video önermek için bir algoritma kullanıyor."],
  ["machine learning", "n", "makine öğrenmesi", "Machine learning helps doctors read X-rays.", "Makine öğrenmesi doktorların röntgen okumasına yardım ediyor."],
  ["automation", "n", "otomasyon", "Automation will replace some jobs.", "Otomasyon bazı işlerin yerini alacak."],
  ["encryption", "n", "şifreleme", "The app uses end-to-end encryption.", "Uygulama uçtan uca şifreleme kullanıyor."],
  ["cybersecurity", "n", "siber güvenlik", "Banks invest heavily in cybersecurity.", "Bankalar siber güvenliğe büyük yatırım yapıyor."],
  ["data breach", "n", "veri ihlali", "Millions of passwords were exposed in the data breach.", "Veri ihlalinde milyonlarca şifre açığa çıktı."],
  ["user interface", "n", "kullanıcı arayüzü", "The new user interface is much clearer.", "Yeni kullanıcı arayüzü çok daha anlaşılır."],
  ["bandwidth", "n", "bant genişliği", "Video calls need a lot of bandwidth.", "Görüntülü aramalar çok bant genişliği ister."],
  ["glitch", "n", "küçük arıza, aksaklık", "A technical glitch delayed the launch.", "Teknik bir aksaklık lansmanı geciktirdi."],
  ["obsolete", "adj", "modası geçmiş, kullanılmayan", "CDs are almost obsolete.", "CD'ler neredeyse kullanılmaz oldu."],
  ["breakthrough technology", "n", "çığır açan teknoloji", "Batteries are the key breakthrough technology.", "Piller çığır açan temel teknoloji."],
  ["wearable", "adj", "giyilebilir", "Wearable devices track your health.", "Giyilebilir cihazlar sağlığını takip eder."],
  ["virtual reality", "n", "sanal gerçeklik", "Virtual reality is used in training pilots.", "Sanal gerçeklik pilot eğitiminde kullanılıyor."],
  ["augmented reality", "n", "artırılmış gerçeklik", "The museum uses augmented reality.", "Müze artırılmış gerçeklik kullanıyor."],
  ["chatbot", "n", "sohbet robotu", "The bank's chatbot answered my question.", "Bankanın sohbet robotu soruma cevap verdi."],
  ["tech-savvy", "adj", "teknolojiden anlayan", "My grandmother is surprisingly tech-savvy.", "Büyükannem şaşırtıcı derecede teknolojiden anlıyor."],
  ["digital footprint", "n", "dijital ayak izi", "Be careful about your digital footprint.", "Dijital ayak izine dikkat et."],
  ["screen time", "n", "ekran süresi", "Parents limit their children's screen time.", "Ebeveynler çocuklarının ekran süresini sınırlıyor."],
  ["troubleshoot", "v", "sorun gidermek", "The IT team is troubleshooting the problem.", "BT ekibi sorunu gideriyor."],
  ["disrupt", "v", "sarsmak, altüst etmek (sektörü)", "Streaming disrupted the music industry.", "Dijital yayın müzik sektörünü altüst etti."],
];
