import type { LexiconEntry } from "../types";

/** B2 sets 56–60: formal writing, negotiation, complaints, agreeing & disagreeing, planning ahead. */
export const B2_PART12: LexiconEntry[] = [
  // Set 56 — Formal writing
  ["I am writing to", "phr", "…amacıyla yazıyorum", "I am writing to apply for the position.", "Pozisyona başvurmak amacıyla yazıyorum."],
  ["with reference to", "phr", "…ile ilgili olarak", "With reference to your letter of 3 May…", "3 Mayıs tarihli mektubunuzla ilgili olarak…"],
  ["please find attached", "phr", "ekte bulabilirsiniz", "Please find attached my CV.", "Özgeçmişimi ekte bulabilirsiniz."],
  ["I look forward to hearing from you", "phr", "yanıtınızı bekliyorum", "I look forward to hearing from you soon.", "Yakında yanıtınızı bekliyorum."],
  ["yours sincerely", "phr", "saygılarımla (ismi bilinen alıcıya)", "Yours sincerely, Ayşe Demir", "Saygılarımla, Ayşe Demir", "Dear Sir/Madam ile Yours faithfully kullanılır."],
  ["yours faithfully", "phr", "saygılarımla (ismi bilinmeyen alıcıya)", "Yours faithfully, Ali Kaya", "Saygılarımla, Ali Kaya"],
  ["at your earliest convenience", "phr", "en kısa sürede, müsait olduğunuz ilk anda", "Please reply at your earliest convenience.", "Lütfen en kısa sürede yanıt verin."],
  ["do not hesitate to", "phr", "…mekten çekinmeyin", "Do not hesitate to contact me.", "Benimle iletişime geçmekten çekinmeyin."],
  ["I would be grateful if", "phr", "…rseniz minnettar olurum", "I would be grateful if you could send me a brochure.", "Bana bir broşür gönderirseniz minnettar olurum."],
  ["regarding", "prep", "…hakkında, …ile ilgili", "I have a question regarding the invoice.", "Fatura hakkında bir sorum var."],
  ["invoice", "n", "fatura (ticari)", "We'll send the invoice by email.", "Faturayı e-postayla göndereceğiz."],
  ["enclose", "v", "(mektuba) eklemek", "I enclose a copy of my certificate.", "Sertifikamın bir kopyasını ekliyorum."],
  ["acknowledge receipt", "phr", "alındığını teyit etmek", "Please acknowledge receipt of this email.", "Lütfen bu e-postanın alındığını teyit edin."],
  ["cc", "v", "bilgi olarak eklemek (e-posta)", "Can you cc me on the email?", "E-postada beni de bilgiye ekler misin?"],
  ["recipient", "n", "alıcı", "Check the recipient's address.", "Alıcının adresini kontrol et."],
  ["subject line", "n", "konu satırı", "Write a clear subject line.", "Açık bir konu satırı yaz."],
  ["formal register", "n", "resmi dil (üslup)", "Use a formal register in a cover letter.", "Ön yazıda resmi bir üslup kullan."],
  ["cover letter", "n", "ön yazı", "Send a cover letter with your CV.", "Özgeçmişinle birlikte bir ön yazı gönder."],
  ["on behalf of", "phr", "…adına", "I'm writing on behalf of my manager.", "Müdürüm adına yazıyorum."],
  ["further to", "phr", "…e ek olarak, …in devamı olarak", "Further to our phone call, here are the details.", "Telefon görüşmemizin devamı olarak ayrıntılar aşağıda."],

  // Set 57 — Negotiation
  ["negotiable", "adj", "pazarlığa açık", "The salary is negotiable.", "Maaş pazarlığa açık."],
  ["counteroffer", "n", "karşı teklif", "They rejected our counteroffer.", "Karşı teklifimizi reddettiler."],
  ["concession", "n", "taviz", "Both sides made concessions.", "İki taraf da taviz verdi."],
  ["meet halfway", "phr", "ortada buluşmak, orta yol bulmak", "Let's meet halfway on the price.", "Fiyatta orta yolu bulalım."],
  ["bargaining power", "n", "pazarlık gücü", "Unions increase workers' bargaining power.", "Sendikalar işçilerin pazarlık gücünü artırır."],
  ["deal-breaker", "n", "anlaşmayı bozan şart", "Working weekends is a deal-breaker for me.", "Hafta sonu çalışmak benim için anlaşmayı bozan bir şart."],
  ["win-win", "adj", "iki tarafın da kazandığı", "It's a win-win situation.", "İki tarafın da kazançlı olduğu bir durum."],
  ["terms and conditions", "n", "şartlar ve koşullar", "Read the terms and conditions carefully.", "Şartları ve koşulları dikkatlice oku."],
  ["draft", "n", "taslak", "Here's the first draft of the contract.", "İşte sözleşmenin ilk taslağı."],
  ["clause", "n", "madde (sözleşme)", "There's a clause about cancellations.", "İptallerle ilgili bir madde var."],
  ["sign on the dotted line", "phr", "(sözleşmeyi) imzalamak", "Read everything before you sign on the dotted line.", "İmzalamadan önce her şeyi oku."],
  ["strike a deal", "phr", "anlaşma yapmak", "They struck a deal after hours of talks.", "Saatlerce süren görüşmelerden sonra anlaşma yaptılar."],
  ["reach a compromise", "phr", "uzlaşmaya varmak", "We finally reached a compromise.", "Sonunda uzlaşmaya vardık."],
  ["stand firm", "phr", "geri adım atmamak", "The union stood firm on pay.", "Sendika ücret konusunda geri adım atmadı."],
  ["the bottom line", "phr", "sonuç olarak, işin özü", "The bottom line is we can't afford it.", "İşin özü, buna gücümüz yetmiyor."],
  ["in good faith", "phr", "iyi niyetle", "We negotiated in good faith.", "İyi niyetle müzakere ettik."],
  ["leverage", "n", "koz, etki gücü", "We have little leverage in these talks.", "Bu görüşmelerde pek kozumuz yok."],
  ["mutually beneficial", "adj", "karşılıklı yararlı", "We want a mutually beneficial partnership.", "Karşılıklı yararlı bir ortaklık istiyoruz."],
  ["impasse", "n", "çıkmaz", "The talks have reached an impasse.", "Görüşmeler bir çıkmaza girdi."],
  ["haggle", "v", "pazarlık etmek", "Tourists haggle in the Grand Bazaar.", "Turistler Kapalıçarşı'da pazarlık yapar."],

  // Set 58 — Complaints
  ["unacceptable", "adj", "kabul edilemez", "The delay is completely unacceptable.", "Gecikme tamamen kabul edilemez."],
  ["dissatisfied", "adj", "memnun olmayan", "I'm dissatisfied with the service.", "Hizmetten memnun değilim."],
  ["inconvenience", "n", "rahatsızlık, zahmet", "We apologise for any inconvenience.", "Yaşanan rahatsızlıktan dolayı özür dileriz."],
  ["reimburse", "v", "(masrafı) geri ödemek", "The company will reimburse your travel costs.", "Şirket yol masraflarını geri ödeyecek."],
  ["replacement", "n", "yenisi, değişim", "They sent me a replacement.", "Bana yenisini gönderdiler."],
  ["escalate", "v", "(şikâyeti) üst makama taşımak; tırmanmak", "I'll escalate the issue to a manager.", "Konuyu bir yöneticiye taşıyacağım."],
  ["resolve an issue", "phr", "bir sorunu çözmek", "We aim to resolve the issue within 48 hours.", "Sorunu 48 saat içinde çözmeyi hedefliyoruz."],
  ["take the matter further", "phr", "konuyu ileri taşımak", "If I don't hear back, I'll take the matter further.", "Yanıt alamazsam konuyu ileri taşıyacağım."],
  ["goodwill gesture", "n", "iyi niyet jesti", "They gave us a voucher as a goodwill gesture.", "İyi niyet jesti olarak bize bir hediye çeki verdiler."],
  ["voucher", "n", "hediye çeki, kupon", "I got a 100-lira voucher.", "100 liralık bir hediye çeki aldım."],
  ["defective", "adj", "kusurlu, arızalı", "The phone was defective.", "Telefon arızalıydı."],
  ["substandard", "adj", "standartların altında", "The work was substandard.", "İş standartların altındaydı."],
  ["lodge a complaint", "phr", "şikâyette bulunmak (resmi)", "He lodged a complaint with the airline.", "Havayoluna resmi şikâyette bulundu."],
  ["formal complaint", "n", "resmi şikâyet", "She made a formal complaint to the council.", "Belediyeye resmi bir şikâyette bulundu."],
  ["customer satisfaction", "n", "müşteri memnuniyeti", "Customer satisfaction is our priority.", "Müşteri memnuniyeti önceliğimizdir."],
  ["apologetic", "adj", "özür diler durumda, mahcup", "The manager was very apologetic.", "Müdür çok mahcuptu."],
  ["compensate", "v", "tazmin etmek, telafi etmek", "The airline compensated the passengers.", "Havayolu yolcuların zararını tazmin etti."],
  ["complaint procedure", "n", "şikâyet prosedürü", "Follow the complaint procedure on the website.", "Web sitesindeki şikâyet prosedürünü izle."],
  ["fall short of", "phr", "…in altında kalmak, karşılamamak", "The hotel fell short of our expectations.", "Otel beklentilerimizin altında kaldı."],
  ["be entitled to", "phr", "…e hakkı olmak", "You're entitled to a full refund.", "Tam para iadesine hakkınız var."],

  // Set 59 — Agreeing & disagreeing
  ["I take your point", "phr", "ne demek istediğini anlıyorum", "I take your point, but it's too expensive.", "Ne demek istediğini anlıyorum ama çok pahalı."],
  ["that's debatable", "phr", "bu tartışılır", "Is it the best film ever? That's debatable.", "Tüm zamanların en iyi filmi mi? Bu tartışılır."],
  ["I beg to differ", "phr", "katılmıyorum (kibar)", "I beg to differ — I think it was a success.", "Katılmıyorum, bence başarılıydı."],
  ["you have a point", "phr", "haklısın, bir noktada haklısın", "You have a point there.", "Orada haklısın."],
  ["that's not how I see it", "phr", "ben öyle görmüyorum", "That's not how I see it at all.", "Ben hiç öyle görmüyorum."],
  ["I'm in two minds", "phr", "ikilemdeyim, kararsızım", "I'm in two minds about the offer.", "Teklif konusunda kararsızım."],
  ["I see where you're coming from", "phr", "bakış açını anlıyorum", "I see where you're coming from, but…", "Bakış açını anlıyorum ama…"],
  ["that's exactly what I think", "phr", "ben de tam olarak öyle düşünüyorum", "That's exactly what I think.", "Ben de tam olarak öyle düşünüyorum."],
  ["up to a point", "phr", "bir yere kadar", "I agree up to a point.", "Bir yere kadar katılıyorum."],
  ["with all due respect", "phr", "kusura bakmayın ama, saygısızlık etmek istemem ama", "With all due respect, you're wrong.", "Kusura bakmayın ama yanılıyorsunuz."],
  ["I have my doubts", "phr", "şüphelerim var", "I have my doubts about the plan.", "Plan konusunda şüphelerim var."],
  ["point taken", "phr", "anlaşıldı, haklısın", "Point taken — I'll be more careful.", "Anlaşıldı, daha dikkatli olacağım."],
  ["far from it", "phr", "hiç de öyle değil", "Is he lazy? Far from it!", "Tembel mi? Hiç de değil!"],
  ["it goes without saying", "phr", "söylemeye gerek yok", "It goes without saying that we'll help.", "Yardım edeceğimizi söylemeye gerek yok."],
  ["to be fair", "phr", "hakkını vermek gerekirse", "To be fair, he did apologise.", "Hakkını vermek gerekirse, özür diledi."],
  ["I couldn't disagree more", "phr", "hiç katılmıyorum", "I couldn't disagree more with that idea.", "O fikre hiç katılmıyorum."],
  ["agree to disagree", "phr", "anlaşamadığımızda anlaşmak", "Let's agree to disagree.", "Anlaşamadığımız konusunda anlaşalım."],
  ["common ground", "n", "ortak nokta", "We need to find some common ground.", "Ortak bir nokta bulmamız gerek."],
  ["I'm with you on that", "phr", "bu konuda seninleyim", "I'm with you on that — it's too risky.", "Bu konuda seninleyim, çok riskli."],
  ["be of the opinion that", "phr", "…görüşünde olmak", "I am of the opinion that exams should be shorter.", "Sınavların daha kısa olması gerektiği görüşündeyim."],

  // Set 60 — Planning ahead
  ["in the pipeline", "phr", "hazırlık aşamasında", "A new app is in the pipeline.", "Yeni bir uygulama hazırlık aşamasında."],
  ["short-term", "adj", "kısa vadeli", "It's only a short-term solution.", "Sadece kısa vadeli bir çözüm."],
  ["long-term", "adj", "uzun vadeli", "What are your long-term goals?", "Uzun vadeli hedeflerin neler?"],
  ["foreseeable", "adj", "öngörülebilir", "Prices will stay high for the foreseeable future.", "Fiyatlar öngörülebilir gelecekte yüksek kalacak."],
  ["contingency plan", "n", "acil durum planı, B planı", "We need a contingency plan.", "Bir B planına ihtiyacımız var."],
  ["timeframe", "n", "zaman çerçevesi", "What's the timeframe for the project?", "Projenin zaman çerçevesi nedir?"],
  ["schedule", "v", "planlamak, programa almak", "The meeting is scheduled for Friday.", "Toplantı cumaya planlandı."],
  ["ahead of schedule", "phr", "planlanandan erken", "The bridge was finished ahead of schedule.", "Köprü planlanandan erken bitti."],
  ["behind schedule", "phr", "programın gerisinde", "The project is behind schedule.", "Proje programın gerisinde."],
  ["tentative", "adj", "geçici, kesin olmayan", "We made tentative plans for the weekend.", "Hafta sonu için kesin olmayan planlar yaptık."],
  ["provisional", "adj", "geçici, şartlı", "This is only a provisional booking.", "Bu sadece geçici bir rezervasyon."],
  ["pencil in", "pv", "(taslak olarak) takvime yazmak", "Let's pencil in a meeting for Tuesday.", "Salı için taslak bir toplantı yazalım."],
  ["in due course", "phr", "zamanı gelince", "You'll be informed in due course.", "Zamanı gelince bilgilendirileceksiniz."],
  ["at short notice", "phr", "kısa süre önce haber vererek", "The concert was cancelled at short notice.", "Konser kısa süre önce haber verilerek iptal edildi."],
  ["forward planning", "n", "ileriye dönük planlama", "Good forward planning saves time.", "İyi bir ileriye dönük planlama zaman kazandırır."],
  ["set a date", "phr", "tarih belirlemek", "Have you set a date for the wedding?", "Düğün için tarih belirlediniz mi?"],
  ["plan ahead", "phr", "önceden plan yapmak", "It's wise to plan ahead.", "Önceden plan yapmak akıllıca."],
  ["on track", "phr", "yolunda, hedefe uygun", "We're on track to finish by June.", "Hazirana kadar bitirmek için yolundayız."],
  ["run behind", "phr", "gecikmek, geride kalmak", "The doctor is running behind today.", "Doktor bugün gecikiyor."],
  ["when the time comes", "phr", "zamanı geldiğinde", "We'll decide when the time comes.", "Zamanı geldiğinde karar veririz."],
];
