import type { LexiconEntry } from "../types";

/** B2 sets 36–40: phrasal verbs (work & plans, ideas & problems), verbs of change, academic verbs, formal verbs. */
export const B2_PART8: LexiconEntry[] = [
  // Set 36 — Phrasal verbs: work & plans
  ["draw up", "pv", "(plan, belge) hazırlamak", "The lawyer will draw up a contract.", "Avukat bir sözleşme hazırlayacak."],
  ["carry out", "pv", "yürütmek, gerçekleştirmek", "They plan to carry out a detailed study.", "Ayrıntılı bir çalışma yürütmeyi planlıyorlar."],
  ["take on", "pv", "üstlenmek; işe almak", "I can't take on any more work.", "Daha fazla iş üstlenemem."],
  ["lay off", "pv", "işten çıkarmak (ekonomik nedenle)", "The factory may lay off 200 workers.", "Fabrika 200 işçiyi işten çıkarabilir."],
  ["step down", "pv", "görevden çekilmek", "The CEO will step down after the scandal.", "CEO skandalın ardından görevden çekilecek."],
  ["fall through", "pv", "suya düşmek, gerçekleşmemek", "I hope our holiday plans don't fall through.", "Umarım tatil planlarımız suya düşmez."],
  ["put forward", "pv", "(fikir) öne sürmek", "She wants to put forward a new proposal.", "Yeni bir öneri öne sürmek istiyor."],
  ["bring forward", "pv", "(tarihi) öne almak", "The meeting has been brought forward to Monday.", "Toplantı pazartesiye alındı."],
  ["push back", "pv", "ertelemek, ileri atmak", "We had to push back the launch by a month.", "Lansmanı bir ay ertelemek zorunda kaldık."],
  ["wind down", "pv", "yavaş yavaş kapatmak; rahatlamak", "The company is winding down its operations.", "Şirket faaliyetlerini yavaş yavaş sonlandırıyor."],
  ["get round to", "pv", "(nihayet) fırsat bulup yapmak", "I finally got round to fixing the door.", "Sonunda kapıyı tamir etmeye fırsat buldum."],
  ["see through", "pv", "sonuna kadar götürmek", "She saw the project through to the end.", "Projeyi sonuna kadar götürdü."],
  ["pull off", "pv", "(zor bir şeyi) başarmak", "Nobody thought we could pull it off.", "Kimse bunu başarabileceğimizi düşünmemişti."],
  ["back out", "pv", "caymak, sözünden dönmek", "It's too late to back out of the deal now.", "Anlaşmadan caymak için artık çok geç."],
  ["draw on", "pv", "(deneyimden) yararlanmak", "She can draw on her experience as a teacher.", "Öğretmenlik deneyiminden yararlanabilir."],
  ["phase out", "pv", "aşamalı olarak kaldırmak", "Plastic bags are being phased out.", "Plastik poşetler aşamalı olarak kaldırılıyor."],
  ["roll out", "pv", "(yeni ürün/hizmet) kullanıma sunmak", "The bank will roll out a new app.", "Banka yeni bir uygulama kullanıma sunacak."],
  ["iron out", "pv", "(küçük sorunları) gidermek", "We need to iron out a few problems.", "Birkaç sorunu gidermemiz gerek."],
  ["knuckle down", "pv", "(ciddi şekilde) işe koyulmak", "It's time to knuckle down and study.", "Artık ciddi şekilde çalışmaya koyulma zamanı."],
  ["snowed under", "phr", "işe gömülmüş", "I'm snowed under with work this week.", "Bu hafta işe gömüldüm."],

  // Set 37 — Phrasal verbs: ideas & problems
  ["come across", "pv", "rastlamak; …izlenimi vermek", "I came across an old photo.", "Eski bir fotoğrafa rastladım."],
  ["come up", "pv", "(konu, sorun) çıkmak, gündeme gelmek", "Something came up, so I can't come.", "Bir şey çıktı, gelemiyorum."],
  ["crop up", "pv", "beklenmedik şekilde ortaya çıkmak", "Problems keep cropping up.", "Sürekli sorunlar çıkıyor."],
  ["boil down to", "pv", "(özünde) …e varmak", "It all boils down to money.", "Her şey sonunda paraya çıkıyor."],
  ["rule out", "pv", "olasılık dışı bırakmak", "The police haven't ruled out murder.", "Polis cinayet ihtimalini dışlamadı."],
  ["think over", "pv", "iyice düşünmek", "Think it over and let me know.", "İyice düşün ve bana haber ver."],
  ["look into", "pv", "araştırmak, incelemek", "We'll look into your complaint.", "Şikâyetinizi inceleyeceğiz."],
  ["weigh up", "pv", "(artı-eksi) tartmak", "Weigh up the pros and cons.", "Artıları ve eksileri tart."],
  ["stem from", "pv", "…den kaynaklanmak", "His anger stems from fear.", "Öfkesi korkudan kaynaklanıyor."],
  ["account for", "pv", "açıklamak; (oranı) oluşturmak", "Tourism accounts for 10% of the economy.", "Turizm ekonominin %10'unu oluşturuyor."],
  ["make out", "pv", "seçebilmek, anlamak", "I couldn't make out what he said.", "Ne dediğini seçemedim."],
  ["play down", "pv", "önemsizmiş gibi göstermek", "The government played down the risks.", "Hükümet riskleri önemsizmiş gibi gösterdi."],
  ["build on", "pv", "üzerine inşa etmek, geliştirmek", "We can build on this success.", "Bu başarının üzerine inşa edebiliriz."],
  ["back up", "pv", "desteklemek, doğrulamak", "Can you back up your claim with evidence?", "İddianı kanıtla destekleyebilir misin?"],
  ["gloss over", "pv", "geçiştirmek, üstünkörü geçmek", "The report glosses over the main problem.", "Rapor asıl sorunu geçiştiriyor."],
  ["jump to conclusions", "phr", "hemen sonuç çıkarmak", "Don't jump to conclusions.", "Hemen sonuç çıkarma."],
  ["mull over", "pv", "üzerinde uzun uzun düşünmek", "I'm still mulling over his offer.", "Hâlâ teklifi üzerinde düşünüyorum."],
  ["hit on", "pv", "(fikri) birden bulmak", "She hit on a brilliant solution.", "Birden parlak bir çözüm buldu."],
  ["narrow down", "pv", "(seçenekleri) daraltmak", "We've narrowed it down to two candidates.", "Seçenekleri iki adaya indirdik."],
  ["opt for", "pv", "tercih etmek, seçmek", "Many students opt for online courses.", "Birçok öğrenci çevrimiçi kursları tercih ediyor."],

  // Set 38 — Verbs of change & cause
  ["alter", "v", "değiştirmek (biraz)", "The tailor altered my suit.", "Terzi takımımda değişiklik yaptı."],
  ["modify", "v", "değiştirmek, uyarlamak", "We modified the plan slightly.", "Planı biraz değiştirdik."],
  ["adjust", "v", "ayarlamak; uyum sağlamak", "It took time to adjust to the new job.", "Yeni işe uyum sağlamak zaman aldı."],
  ["convert", "v", "dönüştürmek", "They converted the barn into a house.", "Ahırı eve dönüştürdüler."],
  ["enhance", "v", "geliştirmek, artırmak", "Good lighting enhances a room.", "İyi aydınlatma bir odayı güzelleştirir."],
  ["deteriorate", "v", "kötüleşmek", "His health deteriorated quickly.", "Sağlığı hızla kötüleşti."],
  ["diminish", "v", "azalmak", "Her interest in the project diminished.", "Projeye ilgisi azaldı."],
  ["expand", "v", "genişlemek, büyümek", "The company expanded into Europe.", "Şirket Avrupa'ya açıldı."],
  ["shrink", "v", "küçülmek, çekmek", "My sweater shrank in the wash.", "Kazağım yıkamada çekti."],
  ["accelerate", "v", "hızlanmak, hızlandırmak", "Climate change is accelerating.", "İklim değişikliği hızlanıyor."],
  ["boost", "v", "artırmak, desteklemek", "The festival boosts local business.", "Festival yerel ticareti canlandırıyor."],
  ["hinder", "v", "engellemek, zorlaştırmak", "Bad weather hindered the rescue.", "Kötü hava kurtarma çalışmalarını zorlaştırdı."],
  ["provoke", "v", "kışkırtmak, (tepkiye) yol açmak", "The decision provoked anger.", "Karar öfkeye yol açtı."],
  ["give rise to", "phr", "…e yol açmak", "The new law gave rise to protests.", "Yeni yasa protestolara yol açtı."],
  ["bring about", "pv", "(değişim) meydana getirmek", "Technology has brought about huge changes.", "Teknoloji büyük değişiklikler getirdi."],
  ["stimulate", "v", "uyarmak, canlandırmak", "Lower taxes can stimulate the economy.", "Daha düşük vergiler ekonomiyi canlandırabilir."],
  ["induce", "v", "neden olmak, tetiklemek", "This medicine may induce sleep.", "Bu ilaç uyku yapabilir."],
  ["attribute to", "v", "…e bağlamak, atfetmek", "She attributes her success to hard work.", "Başarısını sıkı çalışmaya bağlıyor."],
  ["contribute to", "phr", "…e katkıda bulunmak; …e yol açmak", "Stress contributes to heart disease.", "Stres kalp hastalığına katkıda bulunur."],
  ["be responsible for", "phr", "…den sorumlu olmak, …e neden olmak", "Cars are responsible for much of the pollution.", "Kirliliğin büyük kısmından arabalar sorumlu."],

  // Set 39 — Academic verbs
  ["illustrate", "v", "örneklerle açıklamak", "This graph illustrates the trend.", "Bu grafik eğilimi gösteriyor."],
  ["demonstrate", "v", "göstermek, kanıtlamak", "The study demonstrates a clear link.", "Çalışma açık bir bağlantı gösteriyor."],
  ["indicate", "v", "göstermek, işaret etmek", "Research indicates that sleep improves memory.", "Araştırmalar uykunun hafızayı güçlendirdiğini gösteriyor."],
  ["highlight", "v", "vurgulamak, öne çıkarmak", "The report highlights three problems.", "Rapor üç sorunu öne çıkarıyor."],
  ["outline", "v", "ana hatlarıyla anlatmak", "Outline your plan in 100 words.", "Planını 100 kelimeyle ana hatlarıyla anlat."],
  ["evaluate", "v", "değerlendirmek", "Evaluate the advantages of each option.", "Her seçeneğin avantajlarını değerlendir."],
  ["interpret", "v", "yorumlamak", "How do you interpret these results?", "Bu sonuçları nasıl yorumluyorsun?"],
  ["derive", "v", "türetmek, elde etmek", "Many English words derive from Latin.", "Birçok İngilizce kelime Latinceden türemiştir."],
  ["categorise", "v", "sınıflandırmak", "Categorise the words by topic.", "Kelimeleri konuya göre sınıflandır."],
  ["distinguish", "v", "ayırt etmek", "Can you distinguish between the two sounds?", "İki sesi ayırt edebilir misin?"],
  ["assess", "v", "değerlendirmek, ölçmek", "The exam assesses all four skills.", "Sınav dört beceriyi de ölçüyor."],
  ["verify", "v", "doğrulamak", "Please verify your email address.", "Lütfen e-posta adresini doğrula."],
  ["speculate", "v", "tahminde bulunmak, spekülasyon yapmak", "Let's not speculate about the cause.", "Neden hakkında tahmin yürütmeyelim."],
  ["infer", "v", "çıkarım yapmak", "What can you infer from the text?", "Metinden ne çıkarım yapabilirsin?"],
  ["summarise", "v", "özetlemek", "Summarise the article in three sentences.", "Makaleyi üç cümlede özetle."],
  ["compile", "v", "derlemek", "She compiled a list of useful phrases.", "Faydalı ifadelerden bir liste derledi."],
  ["cite", "v", "alıntılamak, kaynak göstermek", "Cite at least three sources.", "En az üç kaynak göster."],
  ["formulate", "v", "formüle etmek, oluşturmak", "Formulate a clear research question.", "Net bir araştırma sorusu oluştur."],
  ["hypothesise", "v", "varsayımda bulunmak", "Scientists hypothesise that the virus came from bats.", "Bilim insanları virüsün yarasalardan geldiğini varsayıyor."],
  ["correlate", "v", "ilişkili olmak", "Income correlates with education.", "Gelir eğitimle ilişkilidir."],

  // Set 40 — Formal verbs
  ["commence", "v", "başlamak (resmi)", "The ceremony will commence at ten.", "Tören saat onda başlayacaktır."],
  ["terminate", "v", "sona erdirmek", "The contract was terminated.", "Sözleşme feshedildi."],
  ["obtain", "v", "elde etmek", "You must obtain a visa first.", "Önce vize almalısınız."],
  ["endeavour", "v", "çabalamak (resmi)", "We endeavour to reply within 24 hours.", "24 saat içinde cevap vermeye çalışıyoruz."],
  ["facilitate", "v", "kolaylaştırmak", "The new system facilitates communication.", "Yeni sistem iletişimi kolaylaştırıyor."],
  ["allocate", "v", "tahsis etmek, ayırmak", "Funds were allocated to schools.", "Okullara fon ayrıldı."],
  ["comply with", "phr", "…e uymak", "All products must comply with safety rules.", "Tüm ürünler güvenlik kurallarına uymalıdır."],
  ["notify", "v", "bildirmek", "Please notify us of any changes.", "Değişiklikleri lütfen bize bildirin."],
  ["enquire", "v", "bilgi istemek, sormak", "I'm writing to enquire about the course.", "Kurs hakkında bilgi almak için yazıyorum."],
  ["acquire a skill", "phr", "bir beceri edinmek", "It takes time to acquire a new skill.", "Yeni bir beceri edinmek zaman alır."],
  ["reside", "v", "ikamet etmek", "He resides in Antalya.", "Antalya'da ikamet ediyor."],
  ["assist", "v", "yardımcı olmak", "Staff will assist passengers.", "Personel yolculara yardımcı olacaktır."],
  ["endorse a plan", "phr", "bir planı onaylamak", "The board endorsed the plan.", "Yönetim kurulu planı onayladı."],
  ["exceed", "v", "aşmak", "Don't exceed the speed limit.", "Hız sınırını aşma."],
  ["retrieve", "v", "geri almak, erişmek", "I couldn't retrieve the deleted files.", "Silinen dosyaları geri getiremedim."],
  ["submit", "v", "sunmak, teslim etmek", "Submit your application online.", "Başvurunu çevrimiçi olarak gönder."],
  ["undertake", "v", "üstlenmek", "She undertook a major research project.", "Büyük bir araştırma projesi üstlendi."],
  ["waive", "v", "(hak, ücret) feragat etmek, almamak", "The bank waived the fee.", "Banka ücreti almadı."],
  ["ascertain", "v", "tespit etmek, kesinleştirmek", "We need to ascertain the facts.", "Gerçekleri tespit etmemiz gerek."],
  ["prior to", "prep", "…den önce (resmi)", "Arrive 30 minutes prior to departure.", "Kalkıştan 30 dakika önce gelin."],
];
