import type { LexiconEntry } from "../types";

/** B2 sets 31–35: social issues, migration, crime, the past, ethics & ideas. */
export const B2_PART7: LexiconEntry[] = [
  // Set 31 — Social issues
  ["inequality", "n", "eşitsizlik", "Income inequality is growing.", "Gelir eşitsizliği büyüyor."],
  ["discrimination", "n", "ayrımcılık", "Discrimination at work is illegal.", "İş yerinde ayrımcılık yasa dışıdır."],
  ["prejudice", "n", "önyargı", "We must fight prejudice.", "Önyargıyla mücadele etmeliyiz."],
  ["marginalised", "adj", "dışlanmış, ötekileştirilmiş", "The charity helps marginalised groups.", "Yardım kuruluşu dışlanmış gruplara destek oluyor."],
  ["homelessness", "n", "evsizlik", "Homelessness has risen in big cities.", "Büyük şehirlerde evsizlik arttı."],
  ["social mobility", "n", "sosyal hareketlilik", "Education improves social mobility.", "Eğitim sosyal hareketliliği artırır."],
  ["poverty line", "n", "yoksulluk sınırı", "Millions live below the poverty line.", "Milyonlarca kişi yoksulluk sınırının altında yaşıyor."],
  ["welfare state", "n", "sosyal devlet", "The welfare state provides healthcare.", "Sosyal devlet sağlık hizmeti sunar."],
  ["gender gap", "n", "cinsiyet uçurumu", "The gender gap in pay is closing slowly.", "Ücretlerdeki cinsiyet uçurumu yavaşça kapanıyor."],
  ["ageing population", "n", "yaşlanan nüfus", "Japan has an ageing population.", "Japonya'nın nüfusu yaşlanıyor."],
  ["birth rate", "n", "doğum oranı", "The birth rate is falling.", "Doğum oranı düşüyor."],
  ["deprived", "adj", "yoksun, yoksul", "The school is in a deprived area.", "Okul yoksul bir bölgede."],
  ["underprivileged", "adj", "imkânsız, dezavantajlı", "Scholarships help underprivileged students.", "Burslar dezavantajlı öğrencilere yardım ediyor."],
  ["activist", "n", "aktivist", "Climate activists marched in the city.", "İklim aktivistleri şehirde yürüdü."],
  ["petition", "n", "dilekçe, imza kampanyası", "Over 10,000 people signed the petition.", "10.000'den fazla kişi imza kampanyasını imzaladı."],
  ["raise awareness", "phr", "farkındalık yaratmak", "The campaign aims to raise awareness of recycling.", "Kampanya geri dönüşüm konusunda farkındalık yaratmayı amaçlıyor."],
  ["tackle a problem", "phr", "bir sorunu ele almak", "We must tackle the problem at its root.", "Sorunu kökünden ele almalıyız."],
  ["taboo", "n", "tabu", "Money is a taboo subject in some families.", "Bazı ailelerde para tabu bir konudur."],
  ["norm", "n", "norm, olağan durum", "Working from home is now the norm.", "Evden çalışmak artık olağan."],
  ["cohesion", "n", "birlik, bütünlük", "Sport can strengthen social cohesion.", "Spor toplumsal birliği güçlendirebilir."],

  // Set 32 — Migration & identity
  ["migrant", "n", "göçmen", "Migrants often send money home.", "Göçmenler çoğu zaman memleketlerine para gönderir."],
  ["emigrate", "v", "(başka ülkeye) göç etmek", "Her grandparents emigrated to Germany in the 1960s.", "Dedesiyle ninesi 1960'larda Almanya'ya göç etti."],
  ["asylum", "n", "sığınma", "They applied for asylum.", "Sığınma başvurusu yaptılar."],
  ["asylum seeker", "n", "sığınmacı", "Asylum seekers wait months for a decision.", "Sığınmacılar bir karar için aylarca bekliyor."],
  ["integrate", "v", "uyum sağlamak, entegre olmak", "Language helps immigrants integrate.", "Dil göçmenlerin uyum sağlamasına yardım eder."],
  ["assimilate", "v", "asimile olmak/etmek", "The second generation assimilated quickly.", "İkinci kuşak hızla asimile oldu."],
  ["diaspora", "n", "diaspora", "The Turkish diaspora in Germany is large.", "Almanya'daki Türk diasporası büyük."],
  ["citizenship", "n", "vatandaşlık", "He was granted citizenship.", "Ona vatandaşlık verildi."],
  ["residence permit", "n", "oturma izni", "Foreign students need a residence permit.", "Yabancı öğrencilerin oturma iznine ihtiyacı var."],
  ["brain drain", "n", "beyin göçü", "Brain drain is a problem for many countries.", "Beyin göçü birçok ülke için bir sorun."],
  ["multicultural", "adj", "çok kültürlü", "London is a multicultural city.", "Londra çok kültürlü bir şehir."],
  ["cultural identity", "n", "kültürel kimlik", "Food is part of our cultural identity.", "Yemek kültürel kimliğimizin bir parçası."],
  ["sense of belonging", "n", "aidiyet duygusu", "Moving often can weaken your sense of belonging.", "Sık taşınmak aidiyet duygusunu zayıflatabilir."],
  ["culture shock", "n", "kültür şoku", "I experienced culture shock in Japan.", "Japonya'da kültür şoku yaşadım."],
  ["expat", "n", "yurt dışında yaşayan kişi", "Many expats live in Fethiye.", "Fethiye'de birçok yabancı yaşıyor."],
  ["stereotype", "n", "kalıp yargı, klişe", "It's a stereotype that all Turks drink tea all day.", "Tüm Türklerin bütün gün çay içtiği bir kalıp yargı."],
  ["xenophobia", "n", "yabancı düşmanlığı", "Xenophobia often grows in hard times.", "Yabancı düşmanlığı çoğu zaman zor dönemlerde artar."],
  ["deport", "v", "sınır dışı etmek", "He was deported for overstaying his visa.", "Vize süresini aştığı için sınır dışı edildi."],
  ["displaced", "adj", "yerinden edilmiş", "The war displaced millions of people.", "Savaş milyonlarca insanı yerinden etti."],
  ["homeland", "n", "anavatan, yurt", "She never forgot her homeland.", "Anavatanını hiç unutmadı."],

  // Set 33 — Crime
  ["fraudster", "n", "dolandırıcı", "The fraudster stole millions online.", "Dolandırıcı internetten milyonlar çaldı."],
  ["smuggling", "n", "kaçakçılık", "Smuggling across the border has increased.", "Sınırda kaçakçılık arttı."],
  ["bribery", "n", "rüşvet (verme)", "The official was jailed for bribery.", "Yetkili rüşvetten hapse girdi."],
  ["vandalism", "n", "vandalizm", "The park was damaged by vandalism.", "Park vandalizm yüzünden hasar gördü."],
  ["assault", "n", "saldırı", "He was arrested for assault.", "Saldırıdan tutuklandı."],
  ["kidnap", "v", "kaçırmak (insan)", "The businessman was kidnapped.", "İş insanı kaçırıldı."],
  ["hostage", "n", "rehine", "The hostages were freed.", "Rehineler serbest bırakıldı."],
  ["cybercrime", "n", "siber suç", "Cybercrime costs billions each year.", "Siber suç her yıl milyarlara mal oluyor."],
  ["surveillance", "n", "gözetim", "The city uses CCTV surveillance.", "Şehir kamera gözetimi kullanıyor."],
  ["forensic", "adj", "adli", "Forensic evidence solved the case.", "Adli kanıtlar davayı çözdü."],
  ["alibi", "n", "(suç anında başka yerde olduğunun) kanıtı", "He had a strong alibi.", "Suç anında başka yerde olduğuna dair güçlü bir kanıtı vardı."],
  ["motive", "n", "(suç) güdü", "The police are looking for a motive.", "Polis bir güdü arıyor."],
  ["suspicious", "adj", "şüpheli", "Report any suspicious behaviour.", "Şüpheli davranışları bildirin."],
  ["crackdown", "n", "sert önlem, operasyon", "There's been a crackdown on illegal parking.", "Yasa dışı parka karşı sert önlemler alındı."],
  ["crime rate", "n", "suç oranı", "The crime rate has fallen.", "Suç oranı düştü."],
  ["rehabilitation", "n", "rehabilitasyon, topluma kazandırma", "Prisons should focus on rehabilitation.", "Cezaevleri topluma kazandırmaya odaklanmalı."],
  ["reoffend", "v", "yeniden suç işlemek", "Many prisoners reoffend after release.", "Birçok mahkûm tahliyeden sonra yeniden suç işliyor."],
  ["life sentence", "n", "müebbet hapis", "He received a life sentence.", "Müebbet hapis cezası aldı."],
  ["get away with", "pv", "cezasız kalmak, paçayı kurtarmak", "He thought he could get away with it.", "Paçayı kurtarabileceğini düşündü."],
  ["turn yourself in", "phr", "teslim olmak (polise)", "The thief turned himself in.", "Hırsız polise teslim oldu."],

  // Set 34 — The past
  ["ancestry", "n", "soy, ata", "She's researching her ancestry.", "Soy ağacını araştırıyor."],
  ["archive", "n", "arşiv", "The documents are kept in the national archive.", "Belgeler ulusal arşivde saklanıyor."],
  ["artefact", "n", "eser (arkeolojik)", "The museum has thousands of artefacts.", "Müzede binlerce eser var."],
  ["excavation", "n", "kazı", "The excavation at Göbeklitepe continues.", "Göbeklitepe'deki kazı devam ediyor."],
  ["colonial", "adj", "sömürge (dönemi)", "The city has colonial architecture.", "Şehirde sömürge dönemi mimarisi var."],
  ["dynastic", "adj", "hanedana ait", "It was a dynastic struggle for power.", "Hanedan içi bir güç mücadelesiydi."],
  ["medieval", "adj", "ortaçağa ait", "We visited a medieval castle.", "Ortaçağdan kalma bir kaleyi gezdik."],
  ["prehistoric", "adj", "tarih öncesi", "Prehistoric people lived in caves.", "Tarih öncesi insanlar mağaralarda yaşardı."],
  ["treaty", "n", "antlaşma", "The Treaty of Lausanne was signed in 1923.", "Lozan Antlaşması 1923'te imzalandı."],
  ["uprising", "n", "ayaklanma", "The uprising was quickly stopped.", "Ayaklanma hızla bastırıldı."],
  ["siege", "n", "kuşatma", "The siege lasted 53 days.", "Kuşatma 53 gün sürdü."],
  ["reign", "n", "saltanat, hükümdarlık dönemi", "During his reign, the empire grew.", "Hükümdarlığı döneminde imparatorluk büyüdü."],
  ["legacy", "n", "miras, bıraktığı iz", "Atatürk's legacy is still strong.", "Atatürk'ün bıraktığı miras hâlâ güçlü."],
  ["turning point", "n", "dönüm noktası", "The battle was a turning point in the war.", "Muharebe savaşta bir dönüm noktasıydı."],
  ["collapse", "n", "çöküş", "The collapse of the empire took decades.", "İmparatorluğun çöküşü onlarca yıl sürdü."],
  ["chronological", "adj", "kronolojik", "List the events in chronological order.", "Olayları kronolojik sırayla listele."],
  ["commemorate", "v", "anmak", "We commemorate the victims every year.", "Her yıl kurbanları anıyoruz."],
  ["restoration", "n", "restorasyon", "The mosque is closed for restoration.", "Cami restorasyon nedeniyle kapalı."],
  ["preserve", "v", "korumak, muhafaza etmek", "We must preserve old buildings.", "Eski binaları korumalıyız."],
  ["oral history", "n", "sözlü tarih", "Oral history records people's memories.", "Sözlü tarih insanların anılarını kaydeder."],

  // Set 35 — Ethics & ideas
  ["ethics", "n", "etik, ahlak bilimi", "Medical ethics is a complex subject.", "Tıp etiği karmaşık bir konudur."],
  ["moral", "adj", "ahlaki", "It's a moral question, not a legal one.", "Bu hukuki değil ahlaki bir soru."],
  ["justification", "n", "gerekçe, haklı sebep", "There is no justification for violence.", "Şiddetin hiçbir haklı gerekçesi yoktur."],
  ["principle", "n", "ilke", "It's against my principles.", "İlkelerime aykırı."],
  ["integrity", "n", "dürüstlük, ahlaki bütünlük", "She's a woman of great integrity.", "Çok dürüst ve ilkeli bir kadın."],
  ["conscience", "n", "vicdan", "My conscience wouldn't let me lie.", "Vicdanım yalan söylememe izin vermedi."],
  ["virtue", "n", "erdem", "Patience is a virtue.", "Sabır bir erdemdir."],
  ["philosophy", "n", "felsefe", "He studied philosophy at university.", "Üniversitede felsefe okudu."],
  ["ideology", "n", "ideoloji", "The party's ideology has changed.", "Partinin ideolojisi değişti."],
  ["rational", "adj", "akılcı, mantıklı", "Try to make a rational decision.", "Akılcı bir karar vermeye çalış."],
  ["irrational", "adj", "mantıksız", "He has an irrational fear of dogs.", "Köpeklere karşı mantıksız bir korkusu var."],
  ["free will", "n", "özgür irade", "Do we really have free will?", "Gerçekten özgür irademiz var mı?"],
  ["tolerance", "n", "hoşgörü", "Tolerance is important in a diverse society.", "Çeşitliliğin olduğu bir toplumda hoşgörü önemlidir."],
  ["secular", "adj", "laik", "Turkey is a secular republic.", "Türkiye laik bir cumhuriyettir."],
  ["atheist", "n", "ateist", "He's an atheist.", "O bir ateist."],
  ["spirituality", "n", "maneviyat", "Many people seek spirituality in nature.", "Birçok insan maneviyatı doğada arar."],
  ["idealistic", "adj", "idealist", "Young people are often idealistic.", "Gençler çoğu zaman idealisttir."],
  ["pragmatic", "adj", "pragmatik, gerçekçi", "We need a pragmatic solution.", "Pragmatik bir çözüme ihtiyacımız var."],
  ["the greater good", "phr", "daha büyük iyilik, toplumun yararı", "She sacrificed her career for the greater good.", "Toplumun yararı için kariyerini feda etti."],
  ["human rights", "n", "insan hakları", "Human rights must be protected.", "İnsan hakları korunmalıdır."],
];
