import type { LexiconEntry } from "../types";

/** B2 sets 1–5: personality, feelings, relationships, communication, persuasion. */
export const B2_PART1: LexiconEntry[] = [
  // Set 1 — Personality in depth
  ["conscientious", "adj", "vicdanlı, işini titizlikle yapan", "She's a conscientious student who never misses a deadline.", "Hiçbir teslim tarihini kaçırmayan, işini titizlikle yapan bir öğrenci."],
  ["assertive", "adj", "kendinden emin, iddialı", "You need to be more assertive in meetings.", "Toplantılarda daha kendinden emin olmalısın."],
  ["compassionate", "adj", "şefkatli, merhametli", "Nurses need to be compassionate.", "Hemşirelerin şefkatli olması gerekir."],
  ["narrow-minded", "adj", "dar görüşlü", "It's narrow-minded to judge a whole country.", "Koca bir ülkeyi yargılamak dar görüşlülüktür."],
  ["open-minded", "adj", "açık fikirli", "Travelling makes you more open-minded.", "Seyahat etmek insanı daha açık fikirli yapar."],
  ["resilient", "adj", "dayanıklı, çabuk toparlanan", "Children are often more resilient than adults.", "Çocuklar çoğu zaman yetişkinlerden daha dayanıklıdır."],
  ["impulsive", "adj", "dürtüsel, düşünmeden hareket eden", "He's impulsive and often regrets his decisions.", "Dürtüseldir ve kararlarından sık sık pişman olur."],
  ["indecisive", "adj", "kararsız", "I'm so indecisive when I order food.", "Yemek sipariş ederken çok kararsızım."],
  ["meticulous", "adj", "titiz, ince eleyip sık dokuyan", "He keeps meticulous records of his spending.", "Harcamalarının titiz kayıtlarını tutar."],
  ["naive", "adj", "saf, toy", "It was naive of me to trust him.", "Ona güvenmem saflıktı."],
  ["pushy", "adj", "ısrarcı, işgüzar", "The salesman was really pushy.", "Satıcı gerçekten çok ısrarcıydı."],
  ["gullible", "adj", "her şeye inanan, kolay kandırılan", "Don't be so gullible — it's a scam.", "Bu kadar saf olma, bu bir dolandırıcılık."],
  ["witty", "adj", "esprili, nükteli", "Her speech was witty and short.", "Konuşması esprili ve kısaydı."],
  ["down-to-earth", "adj", "ayakları yere basan, gösterişsiz", "Despite being famous, she's very down-to-earth.", "Ünlü olmasına rağmen çok mütevazı ve gerçekçi."],
  ["self-centred", "adj", "bencil, kendini merkeze koyan", "He's too self-centred to notice other people's problems.", "Başkalarının sorunlarını fark edemeyecek kadar kendine odaklı."],
  ["temperamental", "adj", "huysuz, ruh hali değişken", "The chef is talented but temperamental.", "Şef yetenekli ama ruh hali değişken."],
  ["inquisitive", "adj", "meraklı, soru soran", "Inquisitive students ask a lot of questions.", "Meraklı öğrenciler çok soru sorar."],
  ["humble", "adj", "alçakgönüllü", "He stayed humble after his success.", "Başarısından sonra alçakgönüllü kaldı."],
  ["reckless", "adj", "pervasız, umursamaz", "Reckless driving causes many accidents.", "Pervasız sürüş birçok kazaya neden olur."],
  ["trait", "n", "özellik (kişilik)", "Patience is her best trait.", "Sabır onun en iyi özelliği."],

  // Set 2 — Shades of feeling
  ["overwhelmed", "adj", "bunalmış, altında ezilmiş", "I felt overwhelmed by all the work.", "Bütün o işin altında ezildim."],
  ["resentful", "adj", "içerlemiş, kırgın", "She was resentful of her sister's success.", "Kız kardeşinin başarısına içerliyordu."],
  ["apprehensive", "adj", "tedirgin, kaygılı", "I'm a little apprehensive about the interview.", "Mülakat konusunda biraz tedirginim."],
  ["content", "adj", "halinden memnun", "He's content with a simple life.", "Sade bir hayattan memnun.", "content (n) /ˈkɒntent/ içerik; content (adj) /kənˈtent/"],
  ["elated", "adj", "sevinçten uçan", "We were elated at the news.", "Haberle sevinçten uçtuk."],
  ["devastated", "adj", "yıkılmış, perişan", "She was devastated when her dog died.", "Köpeği ölünce yıkıldı."],
  ["baffled", "adj", "şaşkın, afallamış", "I was baffled by his reaction.", "Tepkisi karşısında afalladım."],
  ["indifferent", "adj", "kayıtsız, ilgisiz", "He seemed indifferent to the result.", "Sonuca kayıtsız görünüyordu."],
  ["nostalgia", "n", "nostalji, geçmişe özlem", "The old photos filled me with nostalgia.", "Eski fotoğraflar içimi nostaljiyle doldurdu."],
  ["grief", "n", "yas, derin üzüntü", "Grief affects everyone differently.", "Yas herkesi farklı etkiler."],
  ["relief", "n", "rahatlama", "It was a relief to hear she was safe.", "Onun güvende olduğunu duymak rahatlattı."],
  ["frustration", "n", "hüsran, bıkkınlık", "I shouted in frustration.", "Bıkkınlıkla bağırdım."],
  ["anxiety", "n", "kaygı", "Exams cause a lot of anxiety.", "Sınavlar çok kaygıya neden olur."],
  ["contentment", "n", "huzur, memnuniyet", "She smiled with contentment.", "Memnuniyetle gülümsedi."],
  ["mixed feelings", "phr", "karışık duygular", "I have mixed feelings about moving.", "Taşınma konusunda karışık duygularım var."],
  ["bottle up", "pv", "(duyguyu) içine atmak", "Don't bottle up your feelings.", "Duygularını içine atma."],
  ["cheer someone up", "phr", "birini neşelendirmek", "I bought her flowers to cheer her up.", "Onu neşelendirmek için çiçek aldım."],
  ["lose your temper", "phr", "sinirlenip kendini kaybetmek", "He lost his temper and shouted.", "Kendini kaybedip bağırdı."],
  ["on edge", "phr", "gergin, diken üstünde", "Everyone was on edge before the results.", "Sonuçlardan önce herkes diken üstündeydi."],
  ["heartbroken", "adj", "kalbi kırık", "He was heartbroken when she left.", "O gidince kalbi kırıldı."],

  // Set 3 — Relationships
  ["bond", "n", "bağ", "There's a strong bond between the twins.", "İkizler arasında güçlü bir bağ var."],
  ["rapport", "n", "uyum, iyi ilişki", "She has a good rapport with her students.", "Öğrencileriyle iyi bir uyumu var."],
  ["companionship", "n", "arkadaşlık, yoldaşlık", "Pets provide companionship for elderly people.", "Evcil hayvanlar yaşlılara arkadaşlık eder."],
  ["commitment", "n", "bağlılık, taahhüt", "Marriage is a big commitment.", "Evlilik büyük bir bağlılıktır."],
  ["rivalry", "n", "rekabet, çekişme", "There's a friendly rivalry between the two teams.", "İki takım arasında dostça bir rekabet var."],
  ["estranged", "adj", "arası açık, küs", "He's estranged from his father.", "Babasıyla arası açık."],
  ["confide in", "pv", "(birine) sır vermek, açılmak", "I can confide in my sister about anything.", "Kız kardeşime her konuda açılabilirim."],
  ["drift apart", "pv", "zamanla uzaklaşmak", "Old friends often drift apart.", "Eski arkadaşlar çoğu zaman zamanla uzaklaşır."],
  ["patch things up", "phr", "arayı düzeltmek", "They finally patched things up after the argument.", "Tartışmadan sonra sonunda aralarını düzelttiler."],
  ["hit it off", "phr", "hemen anlaşmak, kaynaşmak", "We hit it off from the first day.", "İlk günden kaynaştık."],
  ["get on like a house on fire", "phr", "çok iyi anlaşmak", "The two boys get on like a house on fire.", "İki çocuk çok iyi anlaşıyor."],
  ["take sides", "phr", "taraf tutmak", "I don't want to take sides in their argument.", "Tartışmalarında taraf tutmak istemiyorum."],
  ["betray", "v", "ihanet etmek", "He felt betrayed by his best friend.", "En iyi arkadaşı tarafından ihanete uğramış hissetti."],
  ["reconcile", "v", "barıştırmak, uzlaştırmak", "They were reconciled after years of silence.", "Yıllarca süren sessizlikten sonra barıştılar."],
  ["sibling rivalry", "n", "kardeş kıskançlığı", "Sibling rivalry is normal in big families.", "Kalabalık ailelerde kardeş kıskançlığı normaldir."],
  ["mutual respect", "n", "karşılıklı saygı", "Good relationships are built on mutual respect.", "İyi ilişkiler karşılıklı saygı üzerine kurulur."],
  ["intimate", "adj", "samimi, yakın; mahrem", "It was an intimate dinner with close friends.", "Yakın arkadaşlarla samimi bir akşam yemeğiydi."],
  ["loyalty", "n", "sadakat", "Dogs are known for their loyalty.", "Köpekler sadakatleriyle bilinir."],
  ["acquaint", "v", "tanıştırmak, bilgilendirmek", "Please acquaint yourself with the rules.", "Lütfen kurallar hakkında bilgi edinin.", "acquaint yourself with…"],
  ["break the news", "phr", "(kötü) haberi vermek", "Who's going to break the news to her?", "Haberi ona kim verecek?"],

  // Set 4 — Communication styles
  ["articulate", "adj", "kendini iyi ifade eden", "She's an articulate speaker.", "Kendini iyi ifade eden bir konuşmacı."],
  ["concise", "adj", "kısa ve öz", "Keep your answers concise.", "Cevaplarını kısa ve öz tut."],
  ["blunt", "adj", "dobra, lafını esirgemeyen", "To be blunt, your essay needs a lot of work.", "Açık konuşmak gerekirse, kompozisyonunun çok çalışmaya ihtiyacı var."],
  ["tactful", "adj", "nazik, diplomatik", "Try to be tactful when you give feedback.", "Geri bildirim verirken diplomatik olmaya çalış."],
  ["vague", "adj", "belirsiz, muğlak", "His instructions were very vague.", "Talimatları çok muğlaktı."],
  ["straightforward", "adj", "açık sözlü; basit, anlaşılır", "The application process is straightforward.", "Başvuru süreci basit ve anlaşılır."],
  ["long-winded", "adj", "uzun ve sıkıcı, lafı uzatan", "The speech was long-winded.", "Konuşma uzun ve sıkıcıydı."],
  ["eloquent", "adj", "belagatli, etkili konuşan", "He gave an eloquent speech.", "Etkileyici bir konuşma yaptı."],
  ["tone of voice", "n", "ses tonu", "Her tone of voice showed she was angry.", "Ses tonu kızgın olduğunu gösteriyordu."],
  ["eye contact", "n", "göz teması", "Make eye contact with the examiner.", "Sınav görevlisiyle göz teması kur."],
  ["small talk", "n", "havadan sudan sohbet", "I'm not good at small talk.", "Havadan sudan sohbette iyi değilim."],
  ["misinterpret", "v", "yanlış yorumlamak", "She misinterpreted my joke.", "Şakamı yanlış yorumladı."],
  ["convey", "v", "aktarmak, iletmek", "Pictures can convey emotions better than words.", "Resimler duyguları kelimelerden daha iyi aktarabilir."],
  ["elaborate", "v", "ayrıntılandırmak", "Could you elaborate on that point?", "O noktayı biraz açar mısınız?", "elaborate on sth"],
  ["digress", "v", "konudan sapmak", "Sorry, I'm digressing — back to the topic.", "Pardon, konudan sapıyorum; konuya dönelim."],
  ["get to the point", "phr", "sadede gelmek", "Please get to the point — we're short of time.", "Lütfen sadede gel, vaktimiz az."],
  ["beat around the bush", "phr", "lafı dolandırmak", "Stop beating around the bush and tell me.", "Lafı dolandırmayı bırak da söyle."],
  ["speak your mind", "phr", "düşündüğünü açıkça söylemek", "She's not afraid to speak her mind.", "Düşündüğünü açıkça söylemekten korkmaz."],
  ["hint", "v", "ima etmek", "He hinted that he might leave the company.", "Şirketten ayrılabileceğini ima etti."],
  ["imply", "v", "ima etmek, dolaylı anlatmak", "Are you implying that I'm lying?", "Yalan söylediğimi mi ima ediyorsun?"],

  // Set 5 — Persuasion & argument
  ["argue that", "phr", "…diye savunmak", "Some people argue that exams are unfair.", "Bazı insanlar sınavların adil olmadığını savunur."],
  ["counter-argument", "n", "karşı argüman", "Include a counter-argument in your essay.", "Kompozisyonuna bir karşı argüman ekle."],
  ["justify", "v", "haklı çıkarmak, gerekçelendirmek", "How can you justify such a high price?", "Böyle yüksek bir fiyatı nasıl gerekçelendirebilirsin?"],
  ["valid", "adj", "geçerli, yerinde", "That's a valid point.", "Bu geçerli bir nokta."],
  ["convincing", "adj", "ikna edici", "Her argument was very convincing.", "Argümanı çok ikna ediciydi."],
  ["dispute", "n", "anlaşmazlık", "The dispute was settled in court.", "Anlaşmazlık mahkemede çözüldü."],
  ["controversial", "adj", "tartışmalı", "It's a controversial topic.", "Tartışmalı bir konu."],
  ["consensus", "n", "fikir birliği", "We couldn't reach a consensus.", "Fikir birliğine varamadık."],
  ["stance", "n", "tutum, duruş", "What's your stance on this issue?", "Bu konudaki tutumun nedir?"],
  ["acknowledge", "v", "kabul etmek, teslim etmek", "He acknowledged that he was wrong.", "Yanıldığını kabul etti."],
  ["refute", "v", "çürütmek", "She refuted all his claims.", "Onun tüm iddialarını çürüttü."],
  ["undermine", "v", "zayıflatmak, baltalamak", "Constant criticism undermines confidence.", "Sürekli eleştiri özgüveni zayıflatır."],
  ["reinforce", "v", "pekiştirmek, güçlendirmek", "Examples reinforce your argument.", "Örnekler argümanını güçlendirir."],
  ["bias", "n", "önyargı, taraflılık", "The article shows a clear bias.", "Makale açık bir taraflılık gösteriyor."],
  ["biased", "adj", "taraflı", "The referee was biased.", "Hakem taraflıydı."],
  ["objective", "adj", "tarafsız, nesnel", "Try to be objective.", "Tarafsız olmaya çalış."],
  ["subjective", "adj", "öznel", "Taste in music is subjective.", "Müzik zevki özneldir."],
  ["win someone over", "phr", "birini kendi tarafına çekmek", "His honesty won the audience over.", "Dürüstlüğü dinleyicileri kendi tarafına çekti."],
  ["play devil's advocate", "phr", "(tartışma için) karşı tarafı savunmak", "Let me play devil's advocate for a moment.", "Bir anlığına karşı tarafı savunayım."],
  ["compelling", "adj", "çok ikna edici, etkileyici", "There is compelling evidence for climate change.", "İklim değişikliğine dair çok güçlü kanıtlar var."],
];
