import type { LexiconEntry } from "../types";

/** B2 sets 41–45: evaluative adjectives, hedging, discourse markers, adjective collocations, verb collocations. */
export const B2_PART9: LexiconEntry[] = [
  // Set 41 — Evaluating things
  ["remarkable", "adj", "dikkate değer, olağanüstü", "She made a remarkable recovery.", "Olağanüstü bir iyileşme gösterdi."],
  ["substantial", "adj", "önemli miktarda, kayda değer", "They made a substantial profit.", "Kayda değer bir kâr elde ettiler."],
  ["significant", "adj", "önemli, anlamlı", "There's been a significant increase in prices.", "Fiyatlarda önemli bir artış oldu."],
  ["negligible", "adj", "önemsiz, ihmal edilebilir", "The difference is negligible.", "Fark ihmal edilebilir düzeyde."],
  ["inadequate", "adj", "yetersiz", "The facilities are inadequate.", "Tesisler yetersiz."],
  ["superficial", "adj", "yüzeysel", "The report is superficial.", "Rapor yüzeysel."],
  ["thorough", "adj", "kapsamlı, eksiksiz", "The police carried out a thorough search.", "Polis kapsamlı bir arama yaptı."],
  ["flawed", "adj", "kusurlu", "The argument is seriously flawed.", "Argüman ciddi şekilde kusurlu."],
  ["flawless", "adj", "kusursuz", "Her performance was flawless.", "Performansı kusursuzdu."],
  ["mediocre", "adj", "vasat", "The food was mediocre.", "Yemek vasattı."],
  ["exceptional", "adj", "istisnai, olağanüstü", "She's an exceptional student.", "İstisnai bir öğrenci."],
  ["overrated", "adj", "abartılmış, olduğundan fazla değer verilen", "I think the film is overrated.", "Bence film abartılıyor."],
  ["underrated", "adj", "hak ettiği değeri görmeyen", "It's an underrated restaurant.", "Hak ettiği değeri görmeyen bir restoran."],
  ["far-fetched", "adj", "akla yatkın olmayan, uçuk", "The plot is a bit far-fetched.", "Konu biraz uçuk."],
  ["plausible", "adj", "akla yatkın, makul", "That's a plausible explanation.", "Bu akla yatkın bir açıklama."],
  ["feasible", "adj", "uygulanabilir", "Is the plan financially feasible?", "Plan mali açıdan uygulanabilir mi?"],
  ["viable", "adj", "yaşayabilir, uygulanabilir", "Solar power is a viable alternative.", "Güneş enerjisi uygulanabilir bir alternatif."],
  ["crucial", "adj", "çok önemli, kritik", "Sleep is crucial for learning.", "Uyku öğrenme için kritik öneme sahip."],
  ["trivial", "adj", "önemsiz, basit", "Don't worry about trivial details.", "Önemsiz ayrıntılar için endişelenme."],
  ["inevitable", "adj", "kaçınılmaz", "Change is inevitable.", "Değişim kaçınılmazdır."],

  // Set 42 — Hedging & stance
  ["arguably", "adv", "tartışmaya açık olsa da, muhtemelen", "He is arguably the best player in the league.", "Tartışmaya açık olsa da ligin en iyi oyuncusu."],
  ["presumably", "adv", "tahminen, muhtemelen", "Presumably, the train is late.", "Tahminen tren gecikti."],
  ["supposedly", "adv", "güya, sözde", "The hotel is supposedly the best in town.", "Güya otel şehrin en iyisi."],
  ["undoubtedly", "adv", "şüphesiz", "It was undoubtedly a success.", "Şüphesiz bir başarıydı."],
  ["virtually", "adv", "neredeyse, hemen hemen", "It's virtually impossible to find a flat here.", "Burada daire bulmak neredeyse imkânsız."],
  ["relatively", "adv", "nispeten", "The exam was relatively easy.", "Sınav nispeten kolaydı."],
  ["somewhat", "adv", "biraz, bir ölçüde", "I was somewhat surprised.", "Biraz şaşırdım."],
  ["considerably", "adv", "önemli ölçüde", "Prices have risen considerably.", "Fiyatlar önemli ölçüde arttı."],
  ["marginally", "adv", "çok az, azıcık", "Sales increased marginally.", "Satışlar çok az arttı."],
  ["predominantly", "adv", "ağırlıklı olarak", "The audience was predominantly young.", "Seyirciler ağırlıklı olarak gençti."],
  ["essentially", "adv", "özünde, temelde", "Essentially, the two plans are the same.", "Temelde iki plan aynı."],
  ["inevitably", "adv", "kaçınılmaz olarak", "Inevitably, prices went up.", "Kaçınılmaz olarak fiyatlar arttı."],
  ["seemingly", "adv", "görünüşte", "It was a seemingly simple task.", "Görünüşte basit bir görevdi."],
  ["allegedly", "adv", "iddiaya göre", "He allegedly stole the money.", "İddiaya göre parayı çaldı."],
  ["it could be argued that", "phr", "…ileri sürülebilir", "It could be argued that exams are outdated.", "Sınavların modasının geçtiği ileri sürülebilir."],
  ["to some extent", "phr", "bir dereceye kadar", "I agree with you to some extent.", "Sana bir dereceye kadar katılıyorum."],
  ["by and large", "phr", "genel olarak", "By and large, the trip was a success.", "Genel olarak gezi başarılıydı."],
  ["in theory", "phr", "teoride", "In theory, it should work.", "Teoride işe yaraması lazım."],
  ["in practice", "phr", "pratikte, uygulamada", "In practice, it's more complicated.", "Uygulamada daha karmaşık."],
  ["as far as I'm concerned", "phr", "bana kalırsa", "As far as I'm concerned, the matter is closed.", "Bana kalırsa konu kapanmıştır."],

  // Set 43 — Discourse markers
  ["nonetheless", "adv", "yine de, buna rağmen", "It was expensive; nonetheless, we bought it.", "Pahalıydı; yine de aldık."],
  ["hence", "adv", "bu yüzden, dolayısıyla", "The flight was delayed, hence the late arrival.", "Uçuş gecikti, dolayısıyla geç varış."],
  ["thus", "adv", "böylece, bu nedenle", "Prices rose; thus, demand fell.", "Fiyatlar arttı; bu nedenle talep düştü."],
  ["whereby", "conj", "…mek suretiyle, ki bununla", "It's a system whereby students can resit exams.", "Öğrencilerin sınava yeniden girebildiği bir sistem."],
  ["notwithstanding", "prep", "…e rağmen", "Notwithstanding the cost, the project went ahead.", "Maliyete rağmen proje devam etti."],
  ["likewise", "adv", "aynı şekilde", "She works hard; likewise, her brother.", "O çok çalışır; kardeşi de aynı şekilde."],
  ["conversely", "adv", "tersine, buna karşılık", "Conversely, some people prefer the city.", "Buna karşılık bazı insanlar şehri tercih eder."],
  ["in contrast", "phr", "buna karşılık, aksine", "In contrast, rural areas are quieter.", "Buna karşılık kırsal alanlar daha sakin."],
  ["with regard to", "phr", "…ile ilgili olarak", "With regard to your question, the answer is yes.", "Sorunuzla ilgili olarak cevap evet."],
  ["in terms of", "phr", "…açısından", "In terms of price, this is the best option.", "Fiyat açısından bu en iyi seçenek."],
  ["on the whole", "phr", "genel olarak, bütünüyle", "On the whole, I enjoyed the course.", "Genel olarak kursu beğendim."],
  ["as opposed to", "phr", "…in aksine, …e karşın", "I prefer tea as opposed to coffee.", "Kahvenin aksine çayı tercih ederim."],
  ["given that", "conj", "…dığı göz önüne alınırsa", "Given that it's raining, let's stay in.", "Yağmur yağdığı göz önüne alınırsa, evde kalalım."],
  ["not to mention", "phr", "…den bahsetmeye bile gerek yok", "The hotel was dirty, not to mention noisy.", "Otel kirliydi, gürültülü olduğunu söylemeye gerek bile yok."],
  ["let alone", "phr", "şöyle dursun", "I can't boil an egg, let alone cook a meal.", "Yemek pişirmek şöyle dursun, yumurta bile haşlayamam."],
  ["that is to say", "phr", "yani, başka bir deyişle", "He's flexible — that is to say, he works any hours.", "Esnektir, yani her saatte çalışır."],
  ["to put it another way", "phr", "başka bir şekilde söylemek gerekirse", "To put it another way, we're losing money.", "Başka bir şekilde söylemek gerekirse, para kaybediyoruz."],
  ["all things considered", "phr", "her şey göz önüne alındığında", "All things considered, it was a good year.", "Her şey göz önüne alındığında iyi bir yıldı."],
  ["in the light of", "phr", "…ışığında", "In the light of new evidence, the case was reopened.", "Yeni kanıtlar ışığında dava yeniden açıldı."],
  ["for the sake of", "phr", "…uğruna, …için", "They stayed together for the sake of the children.", "Çocuklar için birlikte kaldılar."],

  // Set 44 — Adjective collocations
  ["heavy traffic", "n", "yoğun trafik", "There's heavy traffic on the bridge.", "Köprüde yoğun trafik var."],
  ["heavy rain", "n", "şiddetli yağmur", "Heavy rain caused flooding.", "Şiddetli yağmur sele neden oldu."],
  ["strong coffee", "n", "sert kahve", "I need a strong coffee.", "Sert bir kahveye ihtiyacım var."],
  ["high expectations", "n", "yüksek beklentiler", "Parents often have high expectations.", "Ebeveynlerin çoğu zaman yüksek beklentileri olur."],
  ["deep sleep", "n", "derin uyku", "He fell into a deep sleep.", "Derin bir uykuya daldı."],
  ["bitter disappointment", "n", "acı hayal kırıklığı", "The result was a bitter disappointment.", "Sonuç acı bir hayal kırıklığıydı."],
  ["fierce competition", "n", "kıyasıya rekabet", "There's fierce competition for jobs.", "İşler için kıyasıya rekabet var."],
  ["vast majority", "n", "büyük çoğunluk", "The vast majority of students passed.", "Öğrencilerin büyük çoğunluğu geçti."],
  ["narrow escape", "n", "kıl payı kurtuluş", "We had a narrow escape.", "Kıl payı kurtulduk."],
  ["broad range", "n", "geniş yelpaze", "The shop sells a broad range of books.", "Dükkân geniş bir kitap yelpazesi satıyor."],
  ["sharp rise", "n", "keskin artış", "There's been a sharp rise in prices.", "Fiyatlarda keskin bir artış oldu."],
  ["slight chance", "n", "küçük bir ihtimal", "There's a slight chance of rain.", "Küçük bir yağmur ihtimali var."],
  ["mixed reviews", "n", "karışık eleştiriler", "The film got mixed reviews.", "Film karışık eleştiriler aldı."],
  ["common knowledge", "n", "herkesin bildiği şey", "It's common knowledge that he's leaving.", "Ayrılacağı herkesin bildiği bir şey."],
  ["rough idea", "n", "kabaca bir fikir", "Can you give me a rough idea of the cost?", "Maliyet hakkında kabaca bir fikir verebilir misin?"],
  ["hard evidence", "n", "somut kanıt", "There's no hard evidence against him.", "Aleyhine somut bir kanıt yok."],
  ["golden opportunity", "n", "altın fırsat", "This is a golden opportunity.", "Bu bir altın fırsat."],
  ["heated debate", "n", "hararetli tartışma", "There was a heated debate in parliament.", "Mecliste hararetli bir tartışma yaşandı."],
  ["stiff competition", "n", "çetin rekabet", "We face stiff competition from abroad.", "Yurt dışından çetin bir rekabetle karşı karşıyayız."],
  ["utter nonsense", "n", "tamamen saçmalık", "What he said was utter nonsense.", "Söylediği tamamen saçmalıktı."],

  // Set 45 — Verb collocations
  ["reach an agreement", "phr", "anlaşmaya varmak", "The two sides reached an agreement.", "İki taraf anlaşmaya vardı."],
  ["draw a conclusion", "phr", "sonuç çıkarmak", "It's too early to draw a conclusion.", "Sonuç çıkarmak için çok erken."],
  ["meet a deadline", "phr", "son tarihe yetiştirmek", "We worked all night to meet the deadline.", "Son tarihe yetiştirmek için bütün gece çalıştık."],
  ["raise a question", "phr", "bir soru gündeme getirmek", "The report raises important questions.", "Rapor önemli soruları gündeme getiriyor."],
  ["pose a threat", "phr", "tehdit oluşturmak", "Rising sea levels pose a threat to cities.", "Yükselen deniz seviyeleri şehirler için tehdit oluşturuyor."],
  ["bear in mind", "phr", "aklında bulundurmak", "Bear in mind that the shop closes early.", "Dükkânın erken kapandığını aklında bulundur."],
  ["run the risk of", "phr", "…riskini göze almak", "You run the risk of losing everything.", "Her şeyi kaybetme riskini göze alıyorsun."],
  ["hold a meeting", "phr", "toplantı yapmak", "We hold a meeting every Monday.", "Her pazartesi toplantı yaparız."],
  ["gain experience", "phr", "deneyim kazanmak", "Internships help you gain experience.", "Stajlar deneyim kazanmana yardım eder."],
  ["make a contribution", "phr", "katkıda bulunmak", "Everyone made a contribution to the project.", "Herkes projeye katkıda bulundu."],
  ["take precautions", "phr", "önlem almak", "Take precautions against the heat.", "Sıcağa karşı önlem al."],
  ["set an example", "phr", "örnek olmak", "Parents should set a good example.", "Ebeveynler iyi bir örnek olmalı."],
  ["fulfil an ambition", "phr", "bir hayali gerçekleştirmek", "She fulfilled her ambition to become a pilot.", "Pilot olma hayalini gerçekleştirdi."],
  ["break a record", "phr", "rekor kırmak", "He broke the world record.", "Dünya rekorunu kırdı."],
  ["catch someone's eye", "phr", "birinin dikkatini çekmek", "A red dress caught my eye.", "Kırmızı bir elbise dikkatimi çekti."],
  ["play a role", "phr", "rol oynamak", "Diet plays an important role in health.", "Beslenme sağlıkta önemli bir rol oynar."],
  ["draw attention to", "phr", "…e dikkat çekmek", "The campaign draws attention to poverty.", "Kampanya yoksulluğa dikkat çekiyor."],
  ["face the consequences", "phr", "sonuçlarına katlanmak", "You'll have to face the consequences.", "Sonuçlarına katlanmak zorunda kalacaksın."],
  ["keep track of", "phr", "takibini yapmak", "I use an app to keep track of my spending.", "Harcamalarımı takip etmek için bir uygulama kullanıyorum."],
  ["lose sight of", "phr", "gözden kaçırmak, unutmak", "Don't lose sight of your goals.", "Hedeflerini gözden kaçırma."],
];
