import type { LexiconEntry } from "../types";

/** B2 sets 26–30: journalism, online life, the arts, literature, screen industry. */
export const B2_PART6: LexiconEntry[] = [
  // Set 26 — Journalism
  ["headline news", "n", "manşet haber", "The election was headline news.", "Seçim manşet haberdi."],
  ["editorial", "n", "başyazı", "The editorial criticised the new law.", "Başyazı yeni yasayı eleştirdi."],
  ["correspondent", "n", "muhabir (bölge)", "Our correspondent in Brussels reports.", "Brüksel muhabirimiz bildiriyor."],
  ["press freedom", "n", "basın özgürlüğü", "Press freedom is essential in a democracy.", "Basın özgürlüğü bir demokraside vazgeçilmezdir."],
  ["investigative journalism", "n", "araştırmacı gazetecilik", "Investigative journalism exposed the scandal.", "Araştırmacı gazetecilik skandalı ortaya çıkardı."],
  ["sensationalism", "n", "sansasyonellik", "Tabloids are known for sensationalism.", "Magazin gazeteleri sansasyonellikleriyle bilinir."],
  ["scoop", "n", "özel haber, atlatma", "The reporter got a scoop.", "Muhabir özel bir haber yakaladı."],
  ["exclusive", "n", "özel haber/röportaj", "The magazine ran an exclusive with the star.", "Dergi yıldızla özel bir röportaj yayımladı."],
  ["anonymous source", "n", "isimsiz kaynak", "The story was based on an anonymous source.", "Haber isimsiz bir kaynağa dayanıyordu."],
  ["fact-check", "v", "doğruluğunu kontrol etmek", "Always fact-check before sharing.", "Paylaşmadan önce her zaman doğruluğunu kontrol et."],
  ["misinformation", "n", "yanlış bilgi", "Misinformation spreads quickly online.", "Yanlış bilgi internette hızla yayılır."],
  ["propaganda", "n", "propaganda", "The poster was wartime propaganda.", "Afiş savaş dönemi propagandasıydı."],
  ["circulation", "n", "tiraj", "The newspaper's circulation has fallen.", "Gazetenin tirajı düştü."],
  ["press release", "n", "basın bülteni", "The company issued a press release.", "Şirket bir basın bülteni yayımladı."],
  ["broadsheet", "n", "ciddi (büyük boy) gazete", "Broadsheets have more in-depth analysis.", "Ciddi gazetelerde daha derin analizler bulunur."],
  ["impartial", "adj", "tarafsız", "The BBC aims to be impartial.", "BBC tarafsız olmayı amaçlar."],
  ["make the headlines", "phr", "manşetlere çıkmak", "Her discovery made the headlines.", "Keşfi manşetlere çıktı."],
  ["cover a story", "phr", "bir haberi takip etmek/yapmak", "She's covering the story from Gaziantep.", "Haberi Gaziantep'ten takip ediyor."],
  ["breaking story", "n", "son dakika haberi", "We're following a breaking story.", "Son dakika bir haberi takip ediyoruz."],
  ["paparazzi", "n", "paparazzi", "The paparazzi followed her everywhere.", "Paparazziler onu her yerde takip etti."],

  // Set 27 — Life online
  ["online presence", "n", "çevrimiçi görünürlük", "Businesses need a strong online presence.", "İşletmelerin güçlü bir çevrimiçi görünürlüğe ihtiyacı var."],
  ["troll", "n", "trol", "Don't feed the trolls.", "Trollere yem olma."],
  ["clickbait", "n", "tık tuzağı", "That headline is pure clickbait.", "O başlık tamamen tık tuzağı."],
  ["echo chamber", "n", "yankı odası", "Social media can become an echo chamber.", "Sosyal medya bir yankı odasına dönüşebilir."],
  ["filter bubble", "n", "filtre balonu", "Algorithms trap us in a filter bubble.", "Algoritmalar bizi bir filtre balonuna hapseder."],
  ["scroll", "v", "(ekranı) kaydırmak", "I spent an hour scrolling through Instagram.", "Instagram'da kaydırarak bir saat geçirdim."],
  ["doomscrolling", "n", "kötü haberlerde sürekli gezinme", "Doomscrolling before bed ruins your sleep.", "Yatmadan önce kötü haberlerde gezinmek uykunu mahveder."],
  ["go offline", "phr", "çevrimdışı olmak, internetten uzaklaşmak", "I go offline every Sunday.", "Her pazar internetten uzak dururum."],
  ["digital detox", "n", "dijital arınma", "I need a digital detox.", "Dijital arınmaya ihtiyacım var."],
  ["catfish", "v", "sahte profille kandırmak", "He was catfished by someone on a dating app.", "Bir arkadaşlık uygulamasında sahte profille kandırıldı."],
  ["phishing", "n", "oltalama (dolandırıcılık)", "Be careful of phishing emails.", "Oltalama e-postalarına dikkat et."],
  ["scam", "n", "dolandırıcılık", "The 'free iPhone' offer is a scam.", "'Bedava iPhone' teklifi bir dolandırıcılık."],
  ["identity theft", "n", "kimlik hırsızlığı", "Identity theft is increasing.", "Kimlik hırsızlığı artıyor."],
  ["content creator", "n", "içerik üreticisi", "She works as a content creator.", "İçerik üreticisi olarak çalışıyor."],
  ["monetise", "v", "paraya çevirmek", "He monetised his YouTube channel.", "YouTube kanalından gelir elde etti."],
  ["engagement", "n", "etkileşim", "Videos get more engagement than photos.", "Videolar fotoğraflardan daha fazla etkileşim alır."],
  ["go viral", "phr", "viral olmak", "Her cat video went viral.", "Kedi videosu viral oldu."],
  ["anonymity", "n", "anonimlik", "Online anonymity can encourage bad behaviour.", "Çevrimiçi anonimlik kötü davranışı teşvik edebilir."],
  ["screen addiction", "n", "ekran bağımlılığı", "Screen addiction worries many parents.", "Ekran bağımlılığı birçok ebeveyni endişelendiriyor."],
  ["cancel culture", "n", "linç kültürü, iptal kültürü", "Cancel culture is a hot topic online.", "İptal kültürü internette sıcak bir konu."],

  // Set 28 — The arts
  ["contemporary", "adj", "çağdaş", "The museum shows contemporary art.", "Müze çağdaş sanat sergiliyor."],
  ["abstract", "adj", "soyut", "I don't understand abstract paintings.", "Soyut resimleri anlamıyorum."],
  ["installation", "n", "enstalasyon", "The installation fills the whole room.", "Enstalasyon bütün odayı dolduruyor."],
  ["curator", "n", "küratör", "The curator chose 50 works for the show.", "Küratör sergi için 50 eser seçti."],
  ["retrospective", "n", "retrospektif sergi", "The gallery is holding a retrospective of her work.", "Galeri onun eserlerinden oluşan bir retrospektif düzenliyor."],
  ["patron", "n", "hami, sanat destekçisi", "The Medici were famous patrons of the arts.", "Medici ailesi ünlü sanat hamileriydi."],
  ["aesthetic", "adj", "estetik", "The building has great aesthetic appeal.", "Bina büyük bir estetik çekiciliğe sahip."],
  ["medium", "n", "(sanatta) araç, malzeme", "Watercolour is her favourite medium.", "Suluboya en sevdiği malzeme."],
  ["depict", "v", "tasvir etmek", "The painting depicts a village wedding.", "Tablo bir köy düğününü tasvir ediyor."],
  ["evoke", "v", "(duygu) uyandırmak, çağrıştırmak", "The music evokes memories of childhood.", "Müzik çocukluk anılarını çağrıştırıyor."],
  ["provocative", "adj", "kışkırtıcı, düşündürücü", "The exhibition is deliberately provocative.", "Sergi bilerek kışkırtıcı."],
  ["critically acclaimed", "adj", "eleştirmenlerce beğenilen", "It's a critically acclaimed novel.", "Eleştirmenlerce beğenilen bir roman."],
  ["mainstream", "adj", "ana akım", "Her music is becoming more mainstream.", "Müziği daha ana akım hale geliyor."],
  ["avant-garde", "adj", "avangart, öncü", "They staged an avant-garde play.", "Avangart bir oyun sahnelediler."],
  ["calligraphy", "n", "hat sanatı, kaligrafi", "Ottoman calligraphy is beautiful.", "Osmanlı hat sanatı çok güzel."],
  ["ceramics", "n", "seramik (sanatı)", "She studies ceramics in Kütahya.", "Kütahya'da seramik okuyor."],
  ["auction", "n", "müzayede", "The painting sold at auction for millions.", "Tablo müzayedede milyonlara satıldı."],
  ["forgery", "n", "sahte (eser), sahtecilik", "The painting turned out to be a forgery.", "Tablonun sahte olduğu ortaya çıktı."],
  ["commission", "v", "(eser) sipariş etmek", "The city commissioned a statue.", "Şehir bir heykel sipariş etti."],
  ["self-expression", "n", "kendini ifade etme", "Art is a form of self-expression.", "Sanat bir kendini ifade etme biçimidir."],

  // Set 29 — Literature
  ["narrator", "n", "anlatıcı", "The narrator is a young girl.", "Anlatıcı genç bir kız."],
  ["protagonist", "n", "baş kahraman", "The protagonist returns to his village.", "Baş kahraman köyüne döner."],
  ["antagonist", "n", "kötü karakter, karşı karakter", "The antagonist is a corrupt mayor.", "Karşı karakter yozlaşmış bir belediye başkanı."],
  ["theme", "n", "tema, ana fikir", "Loss is a major theme in the book.", "Kayıp, kitabın ana temalarından biri."],
  ["symbolism", "n", "simgecilik", "The novel is full of symbolism.", "Roman simgelerle dolu."],
  ["metaphor", "n", "metafor, eğretileme", "'Time is money' is a metaphor.", "'Zaman paradır' bir metafordur."],
  ["flashback", "n", "geriye dönüş (anlatım)", "The story is told in flashbacks.", "Hikâye geriye dönüşlerle anlatılıyor."],
  ["twist", "n", "beklenmedik gelişme", "The ending has a clever twist.", "Sonunda zekice bir beklenmedik gelişme var."],
  ["page-turner", "n", "sürükleyici kitap", "This thriller is a real page-turner.", "Bu gerilim romanı gerçekten sürükleyici."],
  ["memoir", "n", "anı kitabı, hatırat", "She wrote a memoir about her childhood.", "Çocukluğu hakkında bir anı kitabı yazdı."],
  ["anthology", "n", "seçki, antoloji", "It's an anthology of Turkish poetry.", "Türk şiiri seçkisi."],
  ["prose", "n", "düzyazı", "His prose is simple and clear.", "Düzyazısı sade ve açık."],
  ["verse", "n", "şiir, dize", "The play is written in verse.", "Oyun manzum olarak yazılmış."],
  ["satire", "n", "hiciv, yergi", "Aziz Nesin was a master of satire.", "Aziz Nesin bir hiciv ustasıydı."],
  ["allegory", "n", "alegori", "'Animal Farm' is a political allegory.", "'Hayvan Çiftliği' siyasi bir alegoridir."],
  ["characterisation", "n", "karakter yaratımı", "The characterisation is excellent.", "Karakter yaratımı mükemmel."],
  ["well-written", "adj", "iyi yazılmış", "It's a well-written story.", "İyi yazılmış bir hikâye."],
  ["literary", "adj", "edebi", "She won a literary prize.", "Edebi bir ödül kazandı."],
  ["publisher", "n", "yayınevi, yayıncı", "The publisher rejected his first novel.", "Yayınevi ilk romanını reddetti."],
  ["manuscript", "n", "el yazması, müsvedde", "She sent the manuscript to five publishers.", "Müsveddeyi beş yayınevine gönderdi."],

  // Set 30 — The screen industry
  ["blockbuster", "n", "gişe rekortmeni", "The summer blockbuster broke records.", "Yaz gişe rekortmeni rekorlar kırdı."],
  ["box-office hit", "n", "gişe başarısı", "The comedy was a box-office hit.", "Komedi gişede büyük başarı elde etti."],
  ["flop", "n", "fiyasko", "The film was a complete flop.", "Film tam bir fiyaskoydu."],
  ["screenplay", "n", "senaryo", "He wrote the screenplay himself.", "Senaryoyu kendisi yazdı."],
  ["adaptation", "n", "uyarlama", "The series is an adaptation of a novel.", "Dizi bir roman uyarlaması."],
  ["casting", "n", "oyuncu seçimi", "The casting was perfect.", "Oyuncu seçimi mükemmeldi."],
  ["cameo", "n", "kısa konuk rol", "The director makes a cameo in the film.", "Yönetmen filmde kısa bir konuk rolde görünüyor."],
  ["dubbed", "adj", "dublajlı", "I prefer subtitled films to dubbed ones.", "Altyazılı filmleri dublajlılara tercih ederim."],
  ["streaming service", "n", "dijital yayın platformu", "Which streaming service do you use?", "Hangi dijital platformu kullanıyorsun?"],
  ["binge-watch", "v", "art arda izlemek", "We binge-watched the whole series.", "Tüm diziyi art arda izledik."],
  ["spoiler", "n", "sürprizbozan", "No spoilers, please!", "Sürprizbozan yok lütfen!"],
  ["cliffhanger", "n", "merak uyandıran son", "The season ended on a cliffhanger.", "Sezon merak uyandıran bir sonla bitti."],
  ["plot hole", "n", "senaryo boşluğu", "The film has a big plot hole.", "Filmde büyük bir senaryo boşluğu var."],
  ["box set", "n", "(dizinin tamamı) set", "I got the box set for my birthday.", "Doğum günümde dizinin tam setini aldım."],
  ["red carpet", "n", "kırmızı halı", "Stars walked the red carpet at Antalya.", "Yıldızlar Antalya'da kırmızı halıda yürüdü."],
  ["on location", "phr", "(stüdyo dışında) gerçek mekânda", "The series was filmed on location in Mardin.", "Dizi Mardin'de gerçek mekânda çekildi."],
  ["behind the scenes", "phr", "kamera arkası", "The DVD shows what happens behind the scenes.", "DVD kamera arkasında olanları gösteriyor."],
  ["typecast", "v", "(oyuncuyu) hep aynı tip role sokmak", "He was typecast as a villain.", "Hep kötü adam rolüne sokuldu."],
  ["critic's choice", "n", "eleştirmenlerin seçimi", "The documentary was the critic's choice this week.", "Belgesel bu hafta eleştirmenlerin seçimiydi."],
  ["audience rating", "n", "izleyici puanı", "The show has a high audience rating.", "Programın izleyici puanı yüksek."],
];
