import type { LexiconEntry } from "../types";

/** B1 sets 31–35: history, beliefs & traditions, languages, change, cause & effect. */
export const B1_PART7: LexiconEntry[] = [
  // Set 31 — History
  ["historic", "adj", "tarihi (önemli)", "It was a historic moment.", "Tarihi bir andı."],
  ["historical", "adj", "tarihsel", "The film is based on historical events.", "Film tarihsel olaylara dayanıyor."],
  ["empire", "n", "imparatorluk", "The Ottoman Empire lasted six centuries.", "Osmanlı İmparatorluğu altı yüzyıl sürdü."],
  ["war", "n", "savaş", "The war ended in 1918.", "Savaş 1918'de sona erdi."],
  ["battle", "n", "muharebe, savaş", "The Battle of Gallipoli was in 1915.", "Çanakkale Savaşı 1915'teydi."],
  ["army", "n", "ordu", "He served in the army.", "Orduda görev yaptı."],
  ["soldier", "n", "asker", "The soldiers marched through the city.", "Askerler şehirde yürüdü."],
  ["independence", "n", "bağımsızlık", "The country gained independence in 1960.", "Ülke 1960'ta bağımsızlığını kazandı."],
  ["revolution", "n", "devrim", "The French Revolution began in 1789.", "Fransız Devrimi 1789'da başladı."],
  ["republic", "n", "cumhuriyet", "Turkey became a republic in 1923.", "Türkiye 1923'te cumhuriyet oldu."],
  ["ruler", "n", "hükümdar", "Süleyman was a powerful ruler.", "Süleyman güçlü bir hükümdardı."],
  ["conquer", "v", "fethetmek", "Mehmed II conquered Constantinople in 1453.", "II. Mehmed 1453'te Konstantinopolis'i fethetti."],
  ["ruins", "n", "kalıntılar, harabeler", "We visited the ruins of an old temple.", "Eski bir tapınağın kalıntılarını gezdik."],
  ["archaeologist", "n", "arkeolog", "Archaeologists found ancient coins.", "Arkeologlar antik sikkeler buldu."],
  ["dynasty", "n", "hanedan", "The Ottoman dynasty ruled for centuries.", "Osmanlı hanedanı yüzyıllarca hüküm sürdü."],
  ["era", "n", "çağ, devir", "We live in the digital era.", "Dijital çağda yaşıyoruz."],
  ["BC", "phr", "Milattan Önce (MÖ)", "Troy was destroyed around 1180 BC.", "Truva MÖ 1180 civarında yıkıldı."],
  ["AD", "phr", "Milattan Sonra (MS)", "The church was built in 537 AD.", "Kilise MS 537'de inşa edildi."],
  ["monument", "n", "anıt", "The monument honours the soldiers.", "Anıt askerleri onurlandırıyor."],
  ["civilisation", "n", "medeniyet", "Anatolia is home to ancient civilisations.", "Anadolu antik medeniyetlere ev sahipliği yapar."],

  // Set 32 — Beliefs & traditions
  ["religion", "n", "din", "Freedom of religion is a basic right.", "Din özgürlüğü temel bir haktır."],
  ["faith", "n", "inanç, iman", "Her faith helped her in hard times.", "İnancı zor zamanlarda ona yardım etti."],
  ["pray", "v", "dua etmek", "They pray five times a day.", "Günde beş kez dua ederler."],
  ["mosque", "n", "cami", "The mosque is over 400 years old.", "Cami 400 yıldan eski."],
  ["church", "n", "kilise", "The old church is now a museum.", "Eski kilise artık bir müze."],
  ["fast", "v", "oruç tutmak", "Many people fast during Ramadan.", "Birçok kişi Ramazan'da oruç tutar."],
  ["festival", "n", "bayram, şenlik", "Eid is an important religious festival.", "Bayram önemli bir dini bayramdır."],
  ["ritual", "n", "ritüel", "Drinking tea is a daily ritual in Turkey.", "Çay içmek Türkiye'de günlük bir ritüeldir."],
  ["superstition", "n", "batıl inanç", "Some people believe the superstition about black cats.", "Bazıları kara kedilerle ilgili batıl inanca inanır."],
  ["legend", "n", "efsane", "According to legend, the city was founded by a wolf.", "Efsaneye göre şehri bir kurt kurmuş."],
  ["myth", "n", "mit, efsane; yanlış inanış", "It's a myth that we only use 10% of our brain.", "Beynimizin sadece %10'unu kullandığımız bir efsanedir."],
  ["spiritual", "adj", "manevi", "Music has a spiritual side for him.", "Müziğin onun için manevi bir yanı var."],
  ["sacred", "adj", "kutsal", "The river is sacred to local people.", "Nehir yerel halk için kutsaldır."],
  ["pilgrim", "n", "hacı", "Millions of pilgrims visit Mecca.", "Milyonlarca hacı Mekke'yi ziyaret eder."],
  ["value", "n", "değer (ahlaki)", "Family values are important to us.", "Aile değerleri bizim için önemlidir."],
  ["respect", "n", "saygı", "Show respect to your elders.", "Büyüklerine saygı göster."],
  ["generation gap", "n", "kuşak farkı", "There's a big generation gap in our family.", "Ailemizde büyük bir kuşak farkı var."],
  ["heritage", "n", "kültürel miras", "We must protect our cultural heritage.", "Kültürel mirasımızı korumalıyız."],
  ["procession", "n", "alay, tören yürüyüşü", "A long procession moved through the streets.", "Uzun bir tören alayı sokaklarda ilerledi."],
  ["hospitality", "n", "misafirperverlik", "Turkish hospitality is famous.", "Türk misafirperverliği ünlüdür."],

  // Set 33 — Languages
  ["native speaker", "n", "anadili olan kişi", "Our teacher is a native speaker of English.", "Öğretmenimizin anadili İngilizce."],
  ["mother tongue", "n", "anadil", "My mother tongue is Turkish.", "Anadilim Türkçe."],
  ["bilingual", "adj", "iki dilli", "Their children are bilingual.", "Çocukları iki dilli."],
  ["accent", "n", "aksan", "She speaks English with a Scottish accent.", "İngilizceyi İskoç aksanıyla konuşuyor."],
  ["pronunciation", "n", "telaffuz", "Your pronunciation is very clear.", "Telaffuzun çok net."],
  ["pronounce", "v", "telaffuz etmek", "How do you pronounce this word?", "Bu kelimeyi nasıl telaffuz ediyorsun?"],
  ["grammar", "n", "dil bilgisi", "English grammar isn't too hard.", "İngilizce dil bilgisi çok zor değil."],
  ["dialect", "n", "lehçe, ağız", "People in the Black Sea region have a strong dialect.", "Karadenizlilerin belirgin bir ağzı vardır."],
  ["slang", "n", "argo", "Teenagers use a lot of slang.", "Gençler çok argo kullanır."],
  ["idiom", "n", "deyim", "'Break a leg' is an English idiom.", "'Break a leg' bir İngilizce deyimdir."],
  ["phrase", "n", "ifade, söz öbeği", "Learn some useful phrases before you travel.", "Seyahat etmeden önce bazı faydalı ifadeler öğren."],
  ["meaning", "n", "anlam", "What's the meaning of this word?", "Bu kelimenin anlamı ne?"],
  ["definition", "n", "tanım", "Look up the definition in a dictionary.", "Tanıma sözlükten bak."],
  ["look up", "pv", "(sözlükte) bakmak", "I looked up the word online.", "Kelimeye internetten baktım."],
  ["interpreter", "n", "tercüman (sözlü)", "The president spoke through an interpreter.", "Cumhurbaşkanı bir tercüman aracılığıyla konuştu."],
  ["translator", "n", "çevirmen", "She works as a translator.", "Çevirmen olarak çalışıyor."],
  ["communicate", "v", "iletişim kurmak", "We communicated using gestures.", "El hareketleriyle iletişim kurduk."],
  ["gesture", "n", "jest, el hareketi", "Some gestures are rude in other cultures.", "Bazı jestler başka kültürlerde kabadır."],
  ["body language", "n", "beden dili", "Body language says a lot.", "Beden dili çok şey anlatır."],
  ["misunderstand", "v", "yanlış anlamak", "Sorry, I misunderstood you.", "Pardon, seni yanlış anladım."],

  // Set 34 — Change
  ["change", "n", "değişim", "The city has seen a lot of change.", "Şehir çok değişime tanık oldu."],
  ["transform", "v", "dönüştürmek", "The internet transformed our lives.", "İnternet hayatlarımızı dönüştürdü."],
  ["evolve", "v", "evrimleşmek, gelişmek", "Languages evolve over time.", "Diller zamanla evrimleşir."],
  ["development", "n", "gelişme, kalkınma", "The development of the region is slow.", "Bölgenin kalkınması yavaş."],
  ["decrease", "v", "azalmak", "The number of visitors decreased.", "Ziyaretçi sayısı azaldı."],
  ["rise", "v", "yükselmek, artmak", "Prices rose by 10%.", "Fiyatlar %10 arttı."],
  ["decline", "v", "azalmak, düşüşe geçmek", "The number of smokers has declined.", "Sigara içenlerin sayısı azaldı."],
  ["grow", "v", "büyümek, yetişmek", "The company grew quickly.", "Şirket hızla büyüdü."],
  ["gradually", "adv", "yavaş yavaş, giderek", "The weather gradually got warmer.", "Hava yavaş yavaş ısındı."],
  ["rapidly", "adv", "hızla", "Technology is changing rapidly.", "Teknoloji hızla değişiyor."],
  ["dramatically", "adv", "çarpıcı biçimde", "Prices have risen dramatically.", "Fiyatlar çarpıcı biçimde arttı."],
  ["slightly", "adv", "biraz, hafifçe", "The price went up slightly.", "Fiyat biraz arttı."],
  ["trend", "n", "eğilim, trend", "There's a trend towards healthy eating.", "Sağlıklı beslenmeye doğru bir eğilim var."],
  ["modernise", "v", "modernleştirmek", "The government modernised the railways.", "Hükümet demiryollarını modernleştirdi."],
  ["adapt", "v", "uyum sağlamak", "Children adapt quickly to new schools.", "Çocuklar yeni okullara çabuk uyum sağlar."],
  ["replace", "v", "yerini almak, değiştirmek", "Robots may replace some workers.", "Robotlar bazı işçilerin yerini alabilir."],
  ["emerge", "v", "ortaya çıkmak", "New problems emerged after the change.", "Değişiklikten sonra yeni sorunlar ortaya çıktı."],
  ["turn into", "pv", "-e dönüşmek", "The old factory was turned into a museum.", "Eski fabrika müzeye dönüştürüldü."],
  ["get used to", "phr", "alışmak", "I'm getting used to the cold weather.", "Soğuk havaya alışıyorum.", "Arkasından isim veya -ing gelir."],
  ["used to", "modal", "eskiden ...-irdi", "I used to live in Bursa.", "Eskiden Bursa'da yaşardım."],

  // Set 35 — Cause & effect
  ["cause", "v", "neden olmak", "Smoking causes cancer.", "Sigara kansere neden olur."],
  ["cause", "n", "neden", "What was the cause of the fire?", "Yangının nedeni neydi?"],
  ["effect", "n", "etki", "Stress has a bad effect on health.", "Stresin sağlık üzerinde kötü bir etkisi var."],
  ["affect", "v", "etkilemek", "The weather affects my mood.", "Hava ruh hâlimi etkiliyor.", "Fiil “affect”, isim “effect”."],
  ["result in", "pv", "ile sonuçlanmak", "The storm resulted in power cuts.", "Fırtına elektrik kesintilerine yol açtı."],
  ["lead to", "pv", "yol açmak", "Poor diet can lead to illness.", "Kötü beslenme hastalığa yol açabilir."],
  ["due to", "prep", "nedeniyle", "The flight was cancelled due to fog.", "Uçuş sis nedeniyle iptal edildi."],
  ["because of", "prep", "yüzünden", "We stayed home because of the rain.", "Yağmur yüzünden evde kaldık."],
  ["as a result", "phr", "sonuç olarak", "He didn't study. As a result, he failed.", "Çalışmadı. Sonuç olarak kaldı."],
  ["consequence", "n", "sonuç (genelde olumsuz)", "Think about the consequences.", "Sonuçlarını düşün."],
  ["influence", "v", "etkilemek", "Friends influence our decisions.", "Arkadaşlar kararlarımızı etkiler."],
  ["influence", "n", "etki, nüfuz", "He's a bad influence on you.", "Senin üzerinde kötü bir etkisi var."],
  ["factor", "n", "etken", "Price is an important factor.", "Fiyat önemli bir etkendir."],
  ["impact", "n", "etki", "The factory had a big impact on the town.", "Fabrikanın kasaba üzerinde büyük etkisi oldu."],
  ["responsible for", "phr", "-den sorumlu", "Who is responsible for the accident?", "Kazadan kim sorumlu?"],
  ["blame", "v", "suçlamak", "Don't blame me!", "Beni suçlama!"],
  ["thanks to", "prep", "sayesinde", "Thanks to your help, we finished early.", "Yardımın sayesinde erken bitirdik."],
  ["owing to", "prep", "…den dolayı", "The flight was cancelled owing to fog.", "Uçuş sis nedeniyle iptal edildi."],
  ["contribute", "v", "katkıda bulunmak", "Everyone contributed to the project.", "Herkes projeye katkıda bulundu."],
  ["trigger", "v", "tetiklemek", "Pollen can trigger an allergy.", "Polen alerjiyi tetikleyebilir."],
];
