import type { LexiconEntry } from "../types";

/** B1 sets 6–10: learning, university, careers, business, finance. */
export const B1_PART2: LexiconEntry[] = [
  // Set 6 — Learning
  ["education", "n", "eğitim", "Education should be free for everyone.", "Eğitim herkes için ücretsiz olmalı."],
  ["educational", "adj", "eğitici", "This game is fun and educational.", "Bu oyun hem eğlenceli hem eğitici."],
  ["concentrate", "v", "odaklanmak", "I can't concentrate with this noise.", "Bu gürültüde odaklanamıyorum."],
  ["memorise", "v", "ezberlemek", "Try to memorise ten words a day.", "Günde on kelime ezberlemeye çalış."],
  ["progress", "n", "ilerleme", "You're making good progress.", "İyi ilerleme kaydediyorsun.", "Sayılamaz: “make progress”."],
  ["effort", "n", "çaba", "Learning a language takes effort.", "Dil öğrenmek çaba ister."],
  ["attend", "v", "katılmak, devam etmek", "She attends evening classes.", "Akşam derslerine devam ediyor."],
  ["absent", "adj", "yok, devamsız", "Three students were absent today.", "Bugün üç öğrenci yoktu."],
  ["assignment", "n", "ödev, görev", "The assignment is due on Friday.", "Ödevin teslimi cuma."],
  ["essay", "n", "kompozisyon, deneme", "Write an essay of 250 words.", "250 kelimelik bir kompozisyon yaz."],
  ["mark", "v", "not vermek, okumak", "The teacher is marking our exams.", "Öğretmen sınavlarımızı okuyor."],
  ["cheat", "v", "kopya çekmek, hile yapmak", "He was caught cheating in the exam.", "Sınavda kopya çekerken yakalandı."],
  ["tutor", "n", "özel öğretmen", "I have a maths tutor twice a week.", "Haftada iki kez matematik özel öğretmenim geliyor."],
  ["instructions", "n", "talimatlar", "Read the instructions carefully.", "Talimatları dikkatle oku."],
  ["beginner", "n", "başlangıç seviyesindeki kişi", "This course is for beginners.", "Bu kurs yeni başlayanlar için."],
  ["advanced", "adj", "ileri düzey", "She's in the advanced class.", "İleri düzey sınıfta."],
  ["intermediate", "adj", "orta düzey", "I have an intermediate level of English.", "Orta düzey İngilizcem var."],
  ["fluent", "adj", "akıcı", "He's fluent in three languages.", "Üç dili akıcı konuşuyor."],
  ["vocabulary", "n", "kelime bilgisi", "Reading helps build your vocabulary.", "Okumak kelime dağarcığını geliştirir."],
  ["qualification", "n", "nitelik, yeterlilik belgesi", "What qualifications do you need for this job?", "Bu iş için hangi niteliklere ihtiyaç var?"],

  // Set 7 — University
  ["campus", "n", "kampüs", "The library is in the middle of the campus.", "Kütüphane kampüsün ortasında."],
  ["faculty", "n", "fakülte", "She works in the Faculty of Medicine.", "Tıp Fakültesi'nde çalışıyor."],
  ["lecture", "n", "ders (konferans tipi)", "The lecture starts at nine.", "Ders dokuzda başlıyor."],
  ["lecturer", "n", "öğretim görevlisi", "Our lecturer is an expert in history.", "Hocamız tarih uzmanı."],
  ["professor", "n", "profesör", "Professor Demir teaches physics.", "Profesör Demir fizik öğretiyor."],
  ["undergraduate", "n", "lisans öğrencisi", "Undergraduates study for four years.", "Lisans öğrencileri dört yıl okur."],
  ["master's degree", "n", "yüksek lisans", "He's doing a master's degree in London.", "Londra'da yüksek lisans yapıyor."],
  ["PhD", "n", "doktora", "She has a PhD in chemistry.", "Kimyada doktorası var."],
  ["scholarship", "n", "burs", "He won a scholarship to study abroad.", "Yurt dışında okumak için burs kazandı."],
  ["tuition fees", "n", "okul ücreti, harç", "Tuition fees are very high in the UK.", "İngiltere'de okul ücretleri çok yüksek."],
  ["dormitory", "n", "yurt", "I lived in a dormitory in my first year.", "İlk yılımda yurtta kaldım.", "Kısaltması: dorm."],
  ["major", "n", "ana dal", "My major is economics.", "Ana dalım ekonomi."],
  ["thesis", "n", "tez", "She's writing her thesis on climate change.", "İklim değişikliği üzerine tezini yazıyor."],
  ["entry requirements", "n", "giriş koşulları", "Check the entry requirements before you apply.", "Başvurmadan önce giriş koşullarını kontrol et."],
  ["enrol", "v", "kaydolmak", "I enrolled on a Spanish course.", "Bir İspanyolca kursuna kaydoldum."],
  ["graduation", "n", "mezuniyet", "My parents came to my graduation.", "Annemle babam mezuniyetime geldi."],
  ["seminar", "n", "seminer", "We discuss the readings in the seminar.", "Okumaları seminerde tartışırız."],
  ["academic", "adj", "akademik", "This is an academic book.", "Bu akademik bir kitap."],
  ["research paper", "n", "araştırma makalesi", "He published a research paper last year.", "Geçen yıl bir araştırma makalesi yayımladı."],
  ["exam period", "n", "sınav dönemi", "The library is full during the exam period.", "Sınav döneminde kütüphane dolu olur."],

  // Set 8 — Careers
  ["profession", "n", "meslek", "Teaching is a noble profession.", "Öğretmenlik saygın bir meslektir."],
  ["professional", "adj", "profesyonel", "He's a professional footballer.", "Profesyonel bir futbolcu."],
  ["position", "n", "pozisyon, konum", "She applied for the position of manager.", "Müdürlük pozisyonuna başvurdu."],
  ["candidate", "n", "aday", "There are five candidates for the job.", "İş için beş aday var."],
  ["CV", "n", "özgeçmiş", "Send your CV by email.", "Özgeçmişini e-postayla gönder.", "Amerikan İngilizcesinde “résumé”."],
  ["reference", "n", "referans", "My old boss gave me a good reference.", "Eski patronum bana iyi bir referans verdi."],
  ["skilled", "adj", "vasıflı, becerikli", "We need skilled workers.", "Vasıflı işçilere ihtiyacımız var."],
  ["resign", "v", "istifa etmek", "He resigned after two years.", "İki yıl sonra istifa etti."],
  ["fire", "v", "kovmak (işten)", "She was fired for being late.", "Geç kaldığı için kovuldu."],
  ["sack", "v", "işten atmak", "The company sacked fifty workers.", "Şirket elli işçiyi işten çıkardı."],
  ["wage", "n", "ücret (saatlik/haftalık)", "The minimum wage went up.", "Asgari ücret arttı."],
  ["income", "n", "gelir", "Their income is too low.", "Gelirleri çok düşük."],
  ["pension", "n", "emekli maaşı", "My grandfather lives on his pension.", "Dedem emekli maaşıyla geçiniyor."],
  ["shift", "n", "vardiya", "Nurses often work night shifts.", "Hemşireler sık sık gece vardiyasında çalışır."],
  ["workplace", "n", "iş yeri", "Smoking is banned in the workplace.", "İş yerinde sigara içmek yasak."],
  ["opportunity", "n", "fırsat", "It's a great opportunity to learn.", "Öğrenmek için harika bir fırsat."],
  ["ambition", "n", "hırs, tutku", "Her ambition is to become a pilot.", "Tutkusu pilot olmak."],
  ["responsibility", "n", "sorumluluk", "Managers have a lot of responsibility.", "Yöneticilerin çok sorumluluğu var."],
  ["job satisfaction", "n", "iş tatmini", "Job satisfaction is more important than salary to me.", "Benim için iş tatmini maaştan daha önemli."],
  ["work experience", "n", "iş deneyimi, staj", "I did two weeks' work experience at a bank.", "Bir bankada iki haftalık staj yaptım."],

  // Set 9 — Business
  ["economy", "n", "ekonomi", "The economy is growing slowly.", "Ekonomi yavaş büyüyor."],
  ["economic", "adj", "ekonomik (ekonomiyle ilgili)", "The country has economic problems.", "Ülkenin ekonomik sorunları var.", "“economical” = tasarruflu."],
  ["industry", "n", "sanayi, sektör", "Tourism is a big industry in Antalya.", "Turizm Antalya'da büyük bir sektör."],
  ["firm", "n", "firma", "He works for a law firm.", "Bir hukuk firmasında çalışıyor."],
  ["customer service", "n", "müşteri hizmetleri", "Call customer service for help.", "Yardım için müşteri hizmetlerini ara."],
  ["client", "n", "müşteri (hizmet)", "The lawyer met her client.", "Avukat müvekkiliyle görüştü."],
  ["product", "n", "ürün", "They sell their products online.", "Ürünlerini internetten satıyorlar."],
  ["profit", "n", "kâr", "The company made a big profit.", "Şirket büyük kâr etti."],
  ["loss", "n", "zarar, kayıp", "The shop made a loss this year.", "Dükkan bu yıl zarar etti."],
  ["competitor", "n", "rakip", "Our competitors have lower prices.", "Rakiplerimizin fiyatları daha düşük."],
  ["advertise", "v", "reklamını yapmak", "They advertise on social media.", "Sosyal medyada reklam veriyorlar."],
  ["market", "n", "piyasa, pazar", "The market for electric cars is growing.", "Elektrikli araba pazarı büyüyor."],
  ["supply", "n", "arz, tedarik", "There's a short supply of water.", "Su sıkıntısı var."],
  ["demand", "n", "talep", "There's a high demand for nurses.", "Hemşirelere yüksek talep var."],
  ["export", "v", "ihraç etmek", "Turkey exports hazelnuts.", "Türkiye fındık ihraç eder."],
  ["import", "v", "ithal etmek", "We import oil from other countries.", "Diğer ülkelerden petrol ithal ediyoruz."],
  ["trade", "n", "ticaret", "Trade between the two countries is growing.", "İki ülke arasındaki ticaret büyüyor."],
  ["deal", "n", "anlaşma", "We made a deal with a new supplier.", "Yeni bir tedarikçiyle anlaşma yaptık."],
  ["negotiate", "v", "müzakere etmek, pazarlık etmek", "They negotiated a better price.", "Daha iyi bir fiyat için pazarlık ettiler."],
  ["run", "v", "yönetmek, işletmek", "She runs a small hotel.", "Küçük bir otel işletiyor."],

  // Set 10 — Finance
  ["finance", "n", "finans, maliye", "He works in finance.", "Finans sektöründe çalışıyor."],
  ["financial", "adj", "mali, finansal", "The company has financial problems.", "Şirketin mali sorunları var."],
  ["invest", "v", "yatırım yapmak", "They invested in property.", "Gayrimenkule yatırım yaptılar."],
  ["investment", "n", "yatırım", "A house is a good investment.", "Ev iyi bir yatırımdır."],
  ["loan", "n", "kredi, borç", "We took out a loan to buy a car.", "Araba almak için kredi çektik."],
  ["mortgage", "n", "konut kredisi", "They're paying off their mortgage.", "Konut kredilerini ödüyorlar.", "“t” okunmaz: /ˈmɔːɡɪdʒ/."],
  ["interest", "n", "faiz; ilgi", "The bank pays 3% interest.", "Banka %3 faiz veriyor."],
  ["savings", "n", "birikim", "He spent all his savings on a car.", "Tüm birikimini arabaya harcadı."],
  ["expense", "n", "masraf", "Living in London is a big expense.", "Londra'da yaşamak büyük bir masraf."],
  ["costly", "adj", "masraflı", "Mistakes can be costly.", "Hatalar pahalıya mal olabilir."],
  ["inflation", "n", "enflasyon", "Inflation is very high this year.", "Bu yıl enflasyon çok yüksek."],
  ["bank transfer", "n", "havale, banka transferi", "You can pay by bank transfer.", "Havale ile ödeyebilirsiniz."],
  ["fee", "n", "ücret (hizmet)", "There's a small fee for the service.", "Hizmet için küçük bir ücret var."],
  ["withdraw", "v", "(para) çekmek", "I withdrew 500 lira from the cash machine.", "Bankamatikten 500 lira çektim."],
  ["deposit", "n", "depozito; yatırılan para", "We paid a deposit on the flat.", "Daire için depozito ödedik."],
  ["transfer", "v", "havale etmek, aktarmak", "I'll transfer the money tomorrow.", "Parayı yarın havale edeceğim."],
  ["instalment", "n", "taksit", "I'm paying for the laptop in six instalments.", "Dizüstü bilgisayarı altı taksitle ödüyorum."],
  ["wealthy", "adj", "varlıklı", "He comes from a wealthy family.", "Varlıklı bir aileden geliyor."],
  ["cost of living", "n", "hayat pahalılığı, geçim maliyeti", "The cost of living has risen sharply.", "Hayat pahalılığı keskin şekilde arttı."],
  ["worth it", "phr", "değer, buna değmek", "It was expensive, but it was worth it.", "Pahalıydı ama buna değdi."],
];
