import type { LexiconEntry } from "../types";

/** B1 sets 1–5: behaviour, emotions, family life, discussion, arguing a point. */
export const B1_PART1: LexiconEntry[] = [
  // Set 1 — Behaviour
  ["behaviour", "n", "davranış", "His behaviour in class has improved.", "Sınıftaki davranışları düzeldi."],
  ["attitude", "n", "tutum", "She has a positive attitude to work.", "İşe karşı olumlu bir tutumu var."],
  ["ambitious", "adj", "hırslı", "He's ambitious and wants to be a manager.", "Hırslı ve yönetici olmak istiyor."],
  ["arrogant", "adj", "kibirli", "The arrogant player refused to shake hands.", "Kibirli oyuncu tokalaşmayı reddetti."],
  ["modest", "adj", "alçakgönüllü", "She's very modest about her success.", "Başarısı konusunda çok alçakgönüllü."],
  ["stubborn", "adj", "inatçı", "My grandfather is too stubborn to change his mind.", "Dedem fikrini değiştirmeyecek kadar inatçı."],
  ["loyal", "adj", "sadık", "Dogs are loyal animals.", "Köpekler sadık hayvanlardır."],
  ["sincere", "adj", "içten, samimi", "Please accept my sincere apologies.", "Lütfen içten özürlerimi kabul edin."],
  ["tolerant", "adj", "hoşgörülü", "We should be tolerant of other opinions.", "Başka fikirlere hoşgörülü olmalıyız."],
  ["aggressive", "adj", "saldırgan", "The dog became aggressive.", "Köpek saldırganlaştı."],
  ["cautious", "adj", "temkinli", "Be cautious when you invest money.", "Para yatırırken temkinli ol."],
  ["curious", "adj", "meraklı", "Children are naturally curious.", "Çocuklar doğal olarak meraklıdır."],
  ["independent", "adj", "bağımsız", "She's been independent since she was eighteen.", "On sekiz yaşından beri bağımsız."],
  ["mature", "adj", "olgun", "He's very mature for his age.", "Yaşına göre çok olgun."],
  ["immature", "adj", "olgunlaşmamış, çocuksu", "That was an immature thing to do.", "Bu çocukça bir davranıştı."],
  ["responsible", "adj", "sorumlu", "Who is responsible for this mess?", "Bu dağınıklıktan kim sorumlu?"],
  ["enthusiastic", "adj", "hevesli, coşkulu", "The students were enthusiastic about the trip.", "Öğrenciler gezi için hevesliydi."],
  ["considerate", "adj", "düşünceli", "It was considerate of you to call.", "Araman çok düşünceliydi."],
  ["bossy", "adj", "emir vermeyi seven", "My older sister is really bossy.", "Ablam çok emir vericidir."],
  ["easy-going", "adj", "uysal, rahat", "He's easy-going and never gets angry.", "Rahat biri, hiç sinirlenmez."],

  // Set 2 — Emotions
  ["anxious", "adj", "kaygılı", "I'm anxious about my exam results.", "Sınav sonuçlarım konusunda kaygılıyım."],
  ["depressed", "adj", "bunalımda, çökmüş", "He felt depressed after losing his job.", "İşini kaybettikten sonra bunalıma girdi."],
  ["delighted", "adj", "çok memnun", "We're delighted to accept your invitation.", "Davetinizi kabul etmekten çok memnunuz."],
  ["furious", "adj", "öfkeden deliye dönmüş", "She was furious when she saw the damage.", "Hasarı görünce öfkeden deliye döndü."],
  ["terrified", "adj", "dehşete düşmüş", "I'm terrified of heights.", "Yükseklikten ödüm kopar."],
  ["exhausted", "adj", "bitkin", "I was exhausted after the long journey.", "Uzun yolculuktan sonra bitkindim."],
  ["relieved", "adj", "rahatlamış", "I was relieved to hear you were safe.", "Güvende olduğunu duyunca rahatladım."],
  ["ashamed", "adj", "utanmış", "He was ashamed of his behaviour.", "Davranışından utandı."],
  ["guilty", "adj", "suçlu (hisseden)", "I feel guilty about forgetting her birthday.", "Doğum gününü unuttuğum için kendimi suçlu hissediyorum."],
  ["satisfied", "adj", "tatmin olmuş, memnun", "Are you satisfied with the service?", "Hizmetten memnun musunuz?"],
  ["frustrated", "adj", "hayal kırıklığı ve öfke hisseden", "I get frustrated when my computer is slow.", "Bilgisayarım yavaş olunca sinirim bozuluyor."],
  ["thrilled", "adj", "çok heyecanlı ve mutlu", "She was thrilled with her present.", "Hediyesine çok sevindi."],
  ["nostalgic", "adj", "nostaljik, geçmişe özlem duyan", "Old songs make me feel nostalgic.", "Eski şarkılar beni nostaljik yapıyor."],
  ["hopeful", "adj", "umutlu", "We're hopeful about the future.", "Gelecekten umutluyuz."],
  ["hopeless", "adj", "umutsuz", "The situation seemed hopeless.", "Durum umutsuz görünüyordu."],
  ["panic", "v", "paniğe kapılmak", "Don't panic, just stay calm.", "Paniğe kapılma, sakin ol."],
  ["regret", "v", "pişman olmak", "I regret not studying harder.", "Daha çok çalışmadığım için pişmanım."],
  ["envy", "n", "kıskançlık, gıpta", "She looked at his car with envy.", "Arabasına gıptayla baktı."],
  ["sympathy", "n", "anlayış, başsağlığı", "You have my sympathy.", "Başınız sağ olsun."],
  ["tension", "n", "gerginlik", "There was tension in the room.", "Odada bir gerginlik vardı."],

  // Set 3 — Family life
  ["upbringing", "n", "yetiştirilme", "She had a strict upbringing.", "Katı bir şekilde yetiştirildi."],
  ["generation", "n", "kuşak, nesil", "Three generations live in this house.", "Bu evde üç kuşak yaşıyor."],
  ["ancestor", "n", "ata", "My ancestors came from the Balkans.", "Atalarım Balkanlardan gelmiş."],
  ["household", "n", "hane, ev halkı", "Every household has a television.", "Her hanede bir televizyon var."],
  ["sibling", "n", "kardeş", "Do you have any siblings?", "Kardeşin var mı?"],
  ["stepmother", "n", "üvey anne", "He gets on well with his stepmother.", "Üvey annesiyle iyi geçiniyor."],
  ["only child", "n", "tek çocuk", "As an only child, I was often lonely.", "Tek çocuk olarak sık sık yalnız kalırdım."],
  ["adopt", "v", "evlat edinmek", "They adopted a baby girl.", "Bir kız bebek evlat edindiler."],
  ["raise", "v", "büyütmek, yetiştirmek", "She raised three children alone.", "Üç çocuğu tek başına büyüttü."],
  ["pregnant", "adj", "hamile", "My sister is pregnant with twins.", "Kız kardeşim ikizlere hamile."],
  ["engaged", "adj", "nişanlı", "They got engaged last summer.", "Geçen yaz nişanlandılar."],
  ["bride", "n", "gelin", "The bride wore a white dress.", "Gelin beyaz bir gelinlik giymişti."],
  ["groom", "n", "damat", "The groom was very nervous.", "Damat çok gergindi."],
  ["honeymoon", "n", "balayı", "They went to Bali on their honeymoon.", "Balayı için Bali'ye gittiler."],
  ["elderly", "adj", "yaşlı (kibar)", "She looks after her elderly parents.", "Yaşlı anne babasına bakıyor."],
  ["teenager", "n", "genç, ergen", "Teenagers spend a lot of time online.", "Gençler internette çok zaman geçiriyor."],
  ["childhood", "n", "çocukluk", "I had a happy childhood.", "Mutlu bir çocukluk geçirdim."],
  ["adult", "n", "yetişkin", "Tickets cost 50 lira for adults.", "Biletler yetişkinler için 50 lira."],
  ["look up to", "pv", "saygı duymak, örnek almak", "I've always looked up to my uncle.", "Amcamı hep örnek aldım."],
  ["take after", "pv", "(aileden birine) benzemek", "She takes after her mother.", "Annesine çekmiş."],

  // Set 4 — Discussion
  ["discussion", "n", "tartışma, görüşme", "We had a long discussion about the plan.", "Plan hakkında uzun bir görüşme yaptık."],
  ["debate", "n", "münazara, tartışma", "There's a debate about school uniforms.", "Okul üniformaları hakkında bir tartışma var."],
  ["argument", "n", "tartışma, kavga; argüman", "They had an argument about money.", "Para yüzünden tartıştılar."],
  ["point", "n", "nokta; görüş", "That's a good point.", "Bu iyi bir nokta."],
  ["point of view", "n", "bakış açısı", "From my point of view, it's unfair.", "Benim bakış açımdan adaletsiz."],
  ["convince", "v", "ikna etmek", "I couldn't convince him to come.", "Onu gelmeye ikna edemedim."],
  ["claim", "v", "iddia etmek", "He claims he saw a ghost.", "Hayalet gördüğünü iddia ediyor."],
  ["admit", "v", "kabul etmek, itiraf etmek", "I admit I was wrong.", "Yanıldığımı kabul ediyorum."],
  ["deny", "v", "inkâr etmek", "He denied taking the money.", "Parayı aldığını inkâr etti."],
  ["insist", "v", "ısrar etmek", "She insisted on paying the bill.", "Hesabı ödemekte ısrar etti.", "“insist on + -ing” kalıbıyla kullanılır."],
  ["interrupt", "v", "sözünü kesmek", "Please don't interrupt me.", "Lütfen sözümü kesme."],
  ["respond", "v", "yanıt vermek", "How did he respond to the news?", "Habere nasıl tepki verdi?"],
  ["persuasive", "adj", "ikna edici", "She made a persuasive speech.", "İkna edici bir konuşma yaptı."],
  ["compromise", "n", "uzlaşma, orta yol", "We reached a compromise.", "Bir orta yol bulduk."],
  ["objection", "n", "itiraz", "Does anyone have any objections?", "İtirazı olan var mı?"],
  ["criticise", "v", "eleştirmek", "The film was criticised for being too long.", "Film çok uzun olduğu için eleştirildi."],
  ["criticism", "n", "eleştiri", "He can't take criticism.", "Eleştiriyi kaldıramıyor."],
  ["praise", "v", "övmek", "The teacher praised her work.", "Öğretmen çalışmasını övdü."],
  ["topic", "n", "konu", "Let's change the topic.", "Konuyu değiştirelim."],
  ["issue", "n", "mesele, sorun", "Climate change is a global issue.", "İklim değişikliği küresel bir meseledir."],

  // Set 5 — Arguing a point
  ["evidence", "n", "kanıt", "There's no evidence that he was there.", "Onun orada olduğuna dair kanıt yok.", "Sayılamaz: “a piece of evidence”."],
  ["assumption", "n", "varsayım", "Don't make assumptions about people.", "İnsanlar hakkında varsayımlarda bulunma."],
  ["belief", "n", "inanç", "It's a common belief that carrots help you see.", "Havucun görmeye yardımcı olduğu yaygın bir inançtır."],
  ["support", "n", "destek", "Thank you for your support.", "Desteğin için teşekkürler."],
  ["oppose", "v", "karşı çıkmak", "Many people oppose the new law.", "Birçok kişi yeni yasaya karşı çıkıyor."],
  ["in favour of", "phr", "-den yana", "Are you in favour of the plan?", "Plandan yana mısın?"],
  ["against", "prep", "-e karşı", "I'm against animal testing.", "Hayvan deneylerine karşıyım."],
  ["pros and cons", "phr", "artılar ve eksiler", "Let's discuss the pros and cons.", "Artıları ve eksileri konuşalım."],
  ["on the one hand", "phr", "bir yandan", "On the one hand, it's cheap.", "Bir yandan ucuz."],
  ["whereas", "conj", "oysa, -iken", "I like tea, whereas my wife prefers coffee.", "Ben çayı severim, oysa eşim kahveyi tercih eder."],
  ["therefore", "adv", "bu nedenle", "It's late; therefore, we should leave.", "Geç oldu; bu nedenle gitmeliyiz."],
  ["moreover", "adv", "üstelik, ayrıca", "The hotel is cheap. Moreover, it's near the beach.", "Otel ucuz. Üstelik plaja yakın."],
  ["nevertheless", "adv", "yine de", "It was raining. Nevertheless, we went out.", "Yağmur yağıyordu. Yine de dışarı çıktık."],
  ["in conclusion", "phr", "sonuç olarak", "In conclusion, exercise is essential.", "Sonuç olarak egzersiz şarttır."],
  ["for instance", "phr", "örneğin", "Some fruits, for instance oranges, are rich in vitamin C.", "Bazı meyveler, örneğin portakal, C vitamini açısından zengindir."],
  ["obviously", "adv", "açıkçası, belli ki", "Obviously, he didn't read the book.", "Belli ki kitabı okumamış."],
  ["personally", "adv", "şahsen", "Personally, I think it's a mistake.", "Şahsen bunun bir hata olduğunu düşünüyorum."],
  ["according to", "prep", "-e göre", "According to the news, it will snow.", "Haberlere göre kar yağacak."],
  ["as far as I know", "phr", "bildiğim kadarıyla", "As far as I know, the shop is still open.", "Bildiğim kadarıyla dükkan hâlâ açık."],
  ["to be honest", "phr", "dürüst olmak gerekirse", "To be honest, I didn't like the film.", "Dürüst olmak gerekirse filmi beğenmedim."],
];
