import type { LexiconEntry } from "../types";

/** B1 sets 46–50: take/have/get collocations, idioms, home & DIY, body & senses, jobs. */
export const B1_PART10: LexiconEntry[] = [
  // Set 46 — Collocations: take, have, get, pay
  ["take a risk", "phr", "risk almak", "Sometimes you have to take a risk.", "Bazen risk almak zorundasın."],
  ["take part in", "phr", "katılmak", "Over 200 students took part in the competition.", "Yarışmaya 200'den fazla öğrenci katıldı."],
  ["take place", "phr", "gerçekleşmek, yer almak", "The wedding will take place in June.", "Düğün haziranda gerçekleşecek."],
  ["take advantage of", "phr", "fırsatı değerlendirmek; istismar etmek", "Take advantage of the sale while it lasts.", "Bitmeden indirimi değerlendir."],
  ["take notes", "phr", "not almak", "Take notes during the lecture.", "Ders sırasında not al."],
  ["take turns", "phr", "sırayla yapmak", "We take turns to cook dinner.", "Akşam yemeğini sırayla pişiriyoruz."],
  ["take into account", "phr", "hesaba katmak", "You should take the cost into account.", "Maliyeti hesaba katmalısın."],
  ["take for granted", "phr", "hafife almak, olağan saymak", "Don't take your health for granted.", "Sağlığını olağan sayma."],
  ["have a go", "phr", "denemek, bir şans vermek", "Can I have a go on your bike?", "Bisikletini bir deneyebilir miyim?"],
  ["have a word with", "phr", "biriyle (kısaca) konuşmak", "Can I have a word with you after class?", "Dersten sonra seninle biraz konuşabilir miyim?"],
  ["have second thoughts", "phr", "tereddüt etmek, fikri değişmek", "I'm having second thoughts about the trip.", "Gezi konusunda tereddüt ediyorum."],
  ["have an argument", "phr", "tartışmak, kavga etmek", "They had an argument about money.", "Para konusunda tartıştılar."],
  ["get the chance", "phr", "fırsat bulmak", "If you get the chance, visit Mardin.", "Fırsat bulursan Mardin'i ziyaret et."],
  ["get in touch", "phr", "iletişime geçmek", "I'll get in touch with you next week.", "Gelecek hafta seninle iletişime geçeceğim."],
  ["get lost", "phr", "kaybolmak", "We got lost in the old city.", "Eski şehirde kaybolduk."],
  ["get the message", "phr", "mesajı almak, anlamak", "She didn't reply, so I got the message.", "Cevap vermedi, ben de mesajı aldım."],
  ["get worse", "phr", "kötüleşmek", "The traffic is getting worse every year.", "Trafik her yıl kötüleşiyor."],
  ["pay attention", "phr", "dikkat etmek", "Please pay attention to the instructions.", "Lütfen talimatlara dikkat edin."],
  ["pay a visit", "phr", "ziyaret etmek, uğramak", "We paid a visit to our grandparents.", "Büyükannemlere uğradık."],
  ["keep a promise", "phr", "sözünü tutmak", "He always keeps his promises.", "Her zaman sözünü tutar.", "break a promise: sözünü tutmamak"],

  // Set 47 — Idioms & fixed expressions
  ["a piece of cake", "phr", "çocuk oyuncağı, çok kolay", "The test was a piece of cake.", "Sınav çocuk oyuncağıydı."],
  ["break the ice", "phr", "buzları eritmek", "A funny story helped to break the ice.", "Komik bir hikâye buzları eritti."],
  ["once in a blue moon", "phr", "kırk yılda bir", "I eat fast food once in a blue moon.", "Kırk yılda bir fast food yerim."],
  ["under the weather", "phr", "keyifsiz, hasta", "I'm feeling a bit under the weather.", "Kendimi biraz keyifsiz hissediyorum."],
  ["hit the books", "phr", "sıkı ders çalışmak", "Exams start next week, so I need to hit the books.", "Sınavlar gelecek hafta başlıyor, sıkı çalışmam gerek."],
  ["cost an arm and a leg", "phr", "servete mal olmak", "That car cost an arm and a leg.", "O araba servete mal oldu."],
  ["keep an eye on", "phr", "göz kulak olmak", "Can you keep an eye on my bag?", "Çantama göz kulak olur musun?"],
  ["on the tip of my tongue", "phr", "dilimin ucunda", "His name is on the tip of my tongue.", "Adı dilimin ucunda."],
  ["see eye to eye", "phr", "aynı fikirde olmak", "We don't always see eye to eye.", "Her zaman aynı fikirde değiliz."],
  ["a waste of time", "phr", "zaman kaybı", "That meeting was a complete waste of time.", "O toplantı tam bir zaman kaybıydı."],
  ["in the long run", "phr", "uzun vadede", "Studying every day pays off in the long run.", "Her gün çalışmak uzun vadede karşılığını verir."],
  ["by heart", "phr", "ezbere", "I know this poem by heart.", "Bu şiiri ezbere biliyorum."],
  ["feel like", "phr", "canı istemek", "I don't feel like going out tonight.", "Bu akşam dışarı çıkmak içimden gelmiyor.", "feel like + -ing"],
  ["it's no use", "phr", "faydası yok", "It's no use crying about it now.", "Artık buna ağlamanın faydası yok."],
  ["no wonder", "phr", "hiç şaşırtıcı değil, ondan", "No wonder you're tired — you slept four hours!", "Yorgun olmana şaşmamalı, dört saat uyudun!"],
  ["get on someone's nerves", "phr", "sinirine dokunmak", "His loud music gets on my nerves.", "Yüksek sesli müziği sinirime dokunuyor."],
  ["make ends meet", "phr", "iki yakasını bir araya getirmek", "Many families struggle to make ends meet.", "Birçok aile iki yakasını bir araya getirmekte zorlanıyor."],
  ["better late than never", "phr", "geç olsun güç olmasın", "You finally called! Better late than never.", "Sonunda aradın! Geç olsun güç olmasın."],
  ["the last straw", "phr", "bardağı taşıran son damla", "His rude comment was the last straw.", "Kaba yorumu bardağı taşıran son damlaydı."],
  ["over the moon", "phr", "havalara uçmak, çok mutlu", "She was over the moon about her results.", "Sonuçları yüzünden havalara uçtu."],

  // Set 48 — Home & DIY
  ["repair", "v", "tamir etmek, onarmak", "Can you repair my phone?", "Telefonumu tamir edebilir misiniz?"],
  ["drill", "n", "matkap", "I need a drill to put up the shelf.", "Rafı asmak için matkaba ihtiyacım var."],
  ["screw", "n", "vida", "One of the screws is loose.", "Vidalardan biri gevşek."],
  ["nail", "n", "çivi; tırnak", "Hammer the nail into the wall.", "Çiviyi duvara çak."],
  ["ladder", "n", "merdiven (taşınabilir)", "He climbed the ladder to fix the roof.", "Çatıyı tamir etmek için merdivene çıktı."],
  ["paintbrush", "n", "boya fırçası", "Wash the paintbrush after you use it.", "Kullandıktan sonra boya fırçasını yıka."],
  ["wallpaper", "n", "duvar kâğıdı", "We chose a blue wallpaper for the bedroom.", "Yatak odası için mavi bir duvar kâğıdı seçtik."],
  ["leak", "n", "sızıntı, kaçak", "There's a leak under the sink.", "Lavabonun altında bir sızıntı var."],
  ["plumber", "n", "tesisatçı", "We called a plumber to fix the pipe.", "Boruyu tamir etmesi için tesisatçı çağırdık."],
  ["electrician", "n", "elektrikçi", "An electrician checked the wiring.", "Bir elektrikçi kabloları kontrol etti."],
  ["pipe", "n", "boru", "The water pipe burst in the winter.", "Kışın su borusu patladı."],
  ["plug", "n", "fiş; tıkaç", "Pull out the plug before cleaning the iron.", "Ütüyü temizlemeden önce fişi çek."],
  ["switch", "n", "düğme, şalter", "The light switch is next to the door.", "Işık düğmesi kapının yanında."],
  ["fix up", "pv", "onarıp düzenlemek", "They're fixing up an old house in Ayvalık.", "Ayvalık'ta eski bir evi onarıp düzenliyorlar."],
  ["put up", "pv", "asmak, kurmak", "Can you help me put up these pictures?", "Bu resimleri asmama yardım eder misin?"],
  ["storage", "n", "depolama alanı", "The flat has plenty of storage.", "Dairede bol depolama alanı var."],
  ["basement", "n", "bodrum", "We keep our bikes in the basement.", "Bisikletlerimizi bodrumda tutuyoruz."],
  ["attic", "n", "çatı katı", "The old photos are in the attic.", "Eski fotoğraflar çatı katında."],
  ["do-it-yourself (DIY)", "n", "kendin yap, ev tamiratı", "He loves DIY and built his own desk.", "Kendin yap işlerini sever, masasını kendisi yaptı."],
  ["mould", "n", "küf", "There's mould on the bathroom ceiling.", "Banyo tavanında küf var."],

  // Set 49 — Body & senses
  ["brain", "n", "beyin", "The brain needs sleep to learn.", "Beynin öğrenmek için uykuya ihtiyacı var."],
  ["lung", "n", "akciğer", "Smoking damages your lungs.", "Sigara akciğerlerine zarar verir."],
  ["muscle", "n", "kas", "I pulled a muscle playing football.", "Futbol oynarken bir kasımı zorladım."],
  ["bone", "n", "kemik", "He broke a bone in his foot.", "Ayağında bir kemik kırıldı."],
  ["wrist", "n", "bilek", "She wears a watch on her left wrist.", "Sol bileğinde saat takıyor."],
  ["ankle", "n", "ayak bileği", "I twisted my ankle on the stairs.", "Merdivenlerde ayak bileğimi burktum."],
  ["chest", "n", "göğüs", "He felt a pain in his chest.", "Göğsünde bir ağrı hissetti."],
  ["forehead", "n", "alın", "She touched my forehead to check for a fever.", "Ateşim var mı diye alnıma dokundu."],
  ["eyebrow", "n", "kaş", "He raised his eyebrows in surprise.", "Şaşkınlıkla kaşlarını kaldırdı."],
  ["sight", "n", "görme (duyusu); manzara", "My grandmother's sight is getting worse.", "Büyükannemin görmesi kötüleşiyor."],
  ["hearing", "n", "işitme", "Loud music can damage your hearing.", "Yüksek müzik işitmene zarar verebilir."],
  ["smell", "n", "koku; koku alma duyusu", "I love the smell of fresh bread.", "Taze ekmek kokusuna bayılırım."],
  ["touch", "n", "dokunma, dokunuş", "The fabric is soft to the touch.", "Kumaş dokununca yumuşak."],
  ["stare", "v", "gözünü dikip bakmak", "It's rude to stare at people.", "İnsanlara gözünü dikip bakmak kabalıktır."],
  ["glance", "v", "göz atmak, şöyle bir bakmak", "She glanced at her watch.", "Saatine şöyle bir baktı."],
  ["scream", "v", "çığlık atmak", "The children screamed with excitement.", "Çocuklar heyecanla çığlık attı."],
  ["breathe", "v", "nefes almak", "Breathe in slowly through your nose.", "Burnundan yavaşça nefes al.", "breath (isim) / breathe (fiil)"],
  ["swallow", "v", "yutmak", "It hurts when I swallow.", "Yutkununca canım acıyor."],
  ["itch", "v", "kaşınmak", "This sweater makes my skin itch.", "Bu kazak cildimi kaşındırıyor."],
  ["sweat", "v", "terlemek", "I was sweating after the run.", "Koşudan sonra terliyordum."],

  // Set 50 — Jobs
  ["accountant", "n", "muhasebeci", "Our accountant prepares the tax forms.", "Muhasebecimiz vergi formlarını hazırlıyor."],
  ["architect", "n", "mimar", "The architect designed a modern library.", "Mimar modern bir kütüphane tasarladı."],
  ["surgeon", "n", "cerrah", "The surgeon operated for six hours.", "Cerrah altı saat ameliyat yaptı."],
  ["vet", "n", "veteriner", "We took the cat to the vet.", "Kediyi veterinere götürdük."],
  ["hairdresser", "n", "kuaför", "My hairdresser cut my hair too short.", "Kuaförüm saçımı çok kısa kesti."],
  ["carpenter", "n", "marangoz", "The carpenter made a wooden table.", "Marangoz ahşap bir masa yaptı."],
  ["civil servant", "n", "devlet memuru", "My mother is a civil servant.", "Annem devlet memuru."],
  ["sales representative", "n", "satış temsilcisi", "She works as a sales representative.", "Satış temsilcisi olarak çalışıyor."],
  ["software developer", "n", "yazılım geliştirici", "Software developers are in high demand.", "Yazılım geliştiricilere büyük talep var."],
  ["flight attendant", "n", "kabin memuru, hostes", "The flight attendant served drinks.", "Kabin memuru içecek servisi yaptı."],
  ["construction worker", "n", "inşaat işçisi", "Construction workers start early in the morning.", "İnşaat işçileri sabah erkenden başlıyor."],
  ["chef", "n", "şef, aşçıbaşı", "The chef prepared a special menu.", "Şef özel bir menü hazırladı."],
  ["tailor", "n", "terzi", "The tailor shortened my trousers.", "Terzi pantolonumu kısalttı."],
  ["security guard", "n", "güvenlik görevlisi", "A security guard stands at the entrance.", "Girişte bir güvenlik görevlisi duruyor."],
  ["cleaner", "n", "temizlikçi", "The cleaner comes every Monday.", "Temizlikçi her pazartesi geliyor."],
  ["self-employed", "adj", "serbest çalışan", "She's self-employed and works from home.", "Serbest çalışıyor ve evden çalışıyor."],
  ["freelance", "adj", "serbest (proje bazlı)", "He's a freelance translator.", "Serbest çevirmen."],
  ["lifeguard", "n", "cankurtaran", "The lifeguard watched the swimmers.", "Cankurtaran yüzücüleri izledi."],
  ["employment", "n", "istihdam, iş", "The factory provides employment for 500 people.", "Fabrika 500 kişiye istihdam sağlıyor."],
  ["retirement", "n", "emeklilik", "He's enjoying his retirement in Bodrum.", "Bodrum'da emekliliğinin tadını çıkarıyor."],
];
