import type { LexiconEntry } from "../types";

/** B1 sets 51–55: the office, problems & solutions, success & failure, rules & permission, numbers & measurement. */
export const B1_PART11: LexiconEntry[] = [
  // Set 51 — At the office
  ["agenda", "n", "gündem", "What's on the agenda for today's meeting?", "Bugünkü toplantının gündeminde ne var?"],
  ["minutes", "n", "toplantı tutanağı", "Who is taking the minutes?", "Tutanağı kim tutuyor?"],
  ["presentation", "n", "sunum", "I have to give a presentation on Monday.", "Pazartesi bir sunum yapmam gerek."],
  ["schedule", "n", "program, takvim", "My schedule is very busy this week.", "Bu hafta programım çok yoğun."],
  ["department", "n", "departman, bölüm", "She works in the marketing department.", "Pazarlama departmanında çalışıyor."],
  ["team leader", "n", "ekip lideri", "Our team leader organised the project.", "Ekip liderimiz projeyi organize etti."],
  ["staff meeting", "n", "personel toplantısı", "There's a staff meeting every Monday.", "Her pazartesi personel toplantısı var."],
  ["photocopy", "n", "fotokopi", "Can you make ten photocopies of this?", "Bundan on fotokopi çekebilir misin?"],
  ["stationery", "n", "kırtasiye", "The stationery is in the top drawer.", "Kırtasiye malzemeleri üst çekmecede."],
  ["reminder", "n", "hatırlatma", "I set a reminder for the meeting.", "Toplantı için bir hatırlatma kurdum."],
  ["spreadsheet", "n", "elektronik tablo", "I keep all the figures in a spreadsheet.", "Tüm rakamları bir tabloda tutuyorum."],
  ["target", "n", "hedef", "We met our sales target this month.", "Bu ay satış hedefimize ulaştık."],
  ["workload", "n", "iş yükü", "My workload has doubled this year.", "Bu yıl iş yüküm iki katına çıktı."],
  ["teamwork", "n", "ekip çalışması", "Good teamwork is the key to success.", "İyi ekip çalışması başarının anahtarıdır."],
  ["feedback", "n", "geri bildirim", "My manager gave me useful feedback.", "Müdürüm bana faydalı geri bildirim verdi."],
  ["conference call", "n", "konferans görüşmesi", "We have a conference call with the Berlin office.", "Berlin ofisiyle bir konferans görüşmemiz var."],
  ["postpone", "v", "ertelemek (resmi)", "The meeting has been postponed until Thursday.", "Toplantı perşembeye ertelendi."],
  ["attend a meeting", "phr", "toplantıya katılmak", "All staff must attend the meeting.", "Tüm personel toplantıya katılmak zorunda."],
  ["run late", "phr", "gecikmek (programdan)", "Sorry, I'm running a bit late.", "Kusura bakma, biraz gecikiyorum."],
  ["in charge of", "phr", "…den sorumlu", "Who is in charge of this project?", "Bu projeden kim sorumlu?"],

  // Set 52 — Problems & solutions
  ["solution", "n", "çözüm", "We need to find a solution quickly.", "Hızlıca bir çözüm bulmamız gerek."],
  ["difficulty", "n", "zorluk", "I had difficulty finding the address.", "Adresi bulmakta zorlandım.", "have difficulty + -ing"],
  ["obstacle", "n", "engel", "Lack of money is the main obstacle.", "Para eksikliği ana engel."],
  ["challenge", "n", "zorluk, meydan okuma", "Moving abroad was a big challenge.", "Yurt dışına taşınmak büyük bir zorluktu."],
  ["crisis", "n", "kriz", "The country is facing an economic crisis.", "Ülke ekonomik bir krizle karşı karşıya."],
  ["risk", "n", "risk", "There's a risk of flooding this week.", "Bu hafta sel riski var."],
  ["cope with", "pv", "başa çıkmak", "How do you cope with stress?", "Stresle nasıl başa çıkıyorsun?"],
  ["overcome", "v", "üstesinden gelmek", "She overcame her fear of flying.", "Uçma korkusunun üstesinden geldi."],
  ["handle", "v", "idare etmek, halletmek", "Can you handle this on your own?", "Bunu tek başına halledebilir misin?"],
  ["tackle", "v", "ele almak, üstüne gitmek", "The city must tackle air pollution.", "Şehir hava kirliliğini ele almalı."],
  ["struggle", "v", "mücadele etmek, zorlanmak", "I struggled with maths at school.", "Okulda matematikte zorlandım."],
  ["avoid", "v", "kaçınmak", "Try to avoid driving in rush hour.", "Yoğun saatte araba kullanmaktan kaçın.", "avoid + -ing"],
  ["suggestion", "n", "öneri", "Do you have any suggestions?", "Önerin var mı?"],
  ["option", "n", "seçenek", "We have two options.", "İki seçeneğimiz var."],
  ["alternative", "n", "alternatif, seçenek", "Is there a cheaper alternative?", "Daha ucuz bir alternatif var mı?"],
  ["effective", "adj", "etkili", "This is an effective way to learn words.", "Bu, kelime öğrenmenin etkili bir yolu."],
  ["urgent", "adj", "acil", "I have an urgent message for you.", "Sana acil bir mesajım var."],
  ["dilemma", "n", "ikilem", "I'm in a dilemma about which job to take.", "Hangi işi alacağım konusunda ikilemdeyim."],
  ["resolve", "v", "çözmek, çözüme kavuşturmak", "The problem was resolved in a day.", "Sorun bir günde çözüldü."],
  ["trial and error", "phr", "deneme yanılma", "I learned to cook by trial and error.", "Yemek yapmayı deneme yanılmayla öğrendim."],

  // Set 53 — Success & failure
  ["succeed", "v", "başarmak, başarılı olmak", "She succeeded in passing the exam.", "Sınavı geçmeyi başardı.", "succeed in + -ing"],
  ["successful", "adj", "başarılı", "He's a successful businessman.", "Başarılı bir iş insanı."],
  ["failure", "n", "başarısızlık", "Failure is part of learning.", "Başarısızlık öğrenmenin bir parçasıdır."],
  ["achievement", "n", "başarı, kazanım", "Graduating was a great achievement.", "Mezun olmak büyük bir başarıydı."],
  ["accomplish", "v", "başarmak, tamamlamak", "We accomplished a lot this week.", "Bu hafta çok şey başardık."],
  ["reward", "n", "ödül, karşılık", "A holiday is my reward for working hard.", "Tatil, sıkı çalışmamın ödülü."],
  ["prize", "n", "ödül (yarışma)", "She won first prize in the contest.", "Yarışmada birincilik ödülünü kazandı."],
  ["award", "n", "ödül (resmi)", "The film won three awards.", "Film üç ödül kazandı."],
  ["goal-setting", "n", "hedef belirleme", "Goal-setting helps you stay motivated.", "Hedef belirleme motive kalmana yardımcı olur."],
  ["motivation", "n", "motivasyon", "I've lost my motivation to study.", "Ders çalışma motivasyonumu kaybettim."],
  ["motivated", "adj", "motive, istekli", "The students are highly motivated.", "Öğrenciler son derece istekli."],
  ["persistent", "adj", "ısrarcı, azimli", "Be persistent and you'll improve.", "Azimli ol, gelişeceksin."],
  ["give it a try", "phr", "bir denemek", "I've never skied, but I'll give it a try.", "Hiç kayak yapmadım ama bir deneyeceğim."],
  ["pay off", "pv", "karşılığını vermek; (borç) kapatmak", "All that hard work paid off.", "Tüm o sıkı çalışma karşılığını verdi."],
  ["fall behind", "pv", "geride kalmak", "I fell behind with my homework.", "Ödevlerimde geride kaldım."],
  ["disappointment", "n", "hayal kırıklığı", "The result was a big disappointment.", "Sonuç büyük bir hayal kırıklığıydı."],
  ["setback", "n", "aksilik, geri adım", "The injury was a setback for the team.", "Sakatlık takım için bir aksilikti."],
  ["breakthrough", "n", "atılım, çığır açan gelişme", "Scientists made a breakthrough in cancer research.", "Bilim insanları kanser araştırmasında bir atılım yaptı."],
  ["potential", "n", "potansiyel", "She has the potential to be a great player.", "Harika bir oyuncu olma potansiyeli var."],
  ["deserve", "v", "hak etmek", "You deserve a break.", "Bir molayı hak ettin."],

  // Set 54 — Rules & permission
  ["permission", "n", "izin", "You need permission to take photos here.", "Burada fotoğraf çekmek için izin gerekiyor."],
  ["be allowed to", "phr", "…mesine izin verilmek", "We're not allowed to use phones in class.", "Sınıfta telefon kullanmamıza izin verilmiyor."],
  ["obey", "v", "uymak, itaat etmek", "Drivers must obey the speed limit.", "Sürücüler hız sınırına uymalı."],
  ["prohibited", "adj", "yasak", "Smoking is prohibited in the building.", "Binada sigara içmek yasaktır."],
  ["compulsory", "adj", "zorunlu", "English is compulsory at our school.", "Okulumuzda İngilizce zorunlu."],
  ["optional", "adj", "isteğe bağlı, seçmeli", "The trip is optional.", "Gezi isteğe bağlı."],
  ["strict", "adj", "sıkı, katı", "My parents were very strict.", "Ailem çok katıydı."],
  ["curfew", "n", "sokağa çıkma yasağı; eve dönüş saati", "My parents set a curfew of ten o'clock.", "Ailem eve dönüş saatimi ona ayarladı."],
  ["unfair", "adj", "haksız, adaletsiz", "The decision was unfair.", "Karar haksızdı."],
  ["disobey", "v", "karşı gelmek, itaat etmemek", "He disobeyed his teacher's instructions.", "Öğretmeninin talimatlarına karşı geldi."],
  ["restriction", "n", "kısıtlama", "There are restrictions on how much luggage you can take.", "Ne kadar bagaj alabileceğine dair kısıtlamalar var."],
  ["permit", "v", "izin vermek (resmi)", "Dogs are not permitted in the park.", "Parka köpek girmesine izin verilmez."],
  ["ban", "v", "yasaklamak", "The city banned plastic bags.", "Şehir plastik poşetleri yasakladı."],
  ["ban", "n", "yasak", "There's a ban on fishing in this lake.", "Bu gölde balık tutma yasağı var."],
  ["break a rule", "phr", "kuralı çiğnemek", "If you break the rules, you'll be punished.", "Kuralları çiğnersen cezalandırılırsın."],
  ["follow the rules", "phr", "kurallara uymak", "Everyone has to follow the rules.", "Herkes kurallara uymak zorunda."],
  ["dress code", "n", "kıyafet kuralı", "The restaurant has a strict dress code.", "Restoranın sıkı bir kıyafet kuralı var."],
  ["fine", "v", "para cezası kesmek", "He was fined for parking illegally.", "Yasa dışı park ettiği için ceza yedi."],
  ["must not", "modal", "…memeli (yasak)", "You must not use your phone while driving.", "Araba kullanırken telefon kullanmamalısın.", "don't have to: zorunda değilsin"],
  ["be supposed to", "phr", "…mesi gerekiyor (beklenti)", "You're supposed to wear a helmet.", "Kask takman gerekiyor."],

  // Set 55 — Numbers & measurement
  ["percentage", "n", "yüzde, oran", "What percentage of students passed?", "Öğrencilerin yüzde kaçı geçti?"],
  ["per cent", "n", "yüzde", "Prices rose by ten per cent.", "Fiyatlar yüzde on arttı."],
  ["average", "n", "ortalama", "The average age of the class is 20.", "Sınıfın yaş ortalaması 20."],
  ["figure", "n", "rakam, sayı", "The sales figures are very good.", "Satış rakamları çok iyi."],
  ["calculate", "v", "hesaplamak", "Calculate the total cost.", "Toplam maliyeti hesapla."],
  ["length", "n", "uzunluk", "What's the length of the room?", "Odanın uzunluğu ne kadar?"],
  ["width", "n", "genişlik", "The width of the road is ten metres.", "Yolun genişliği on metre."],
  ["depth", "n", "derinlik", "The lake has a depth of 50 metres.", "Gölün derinliği 50 metre."],
  ["weigh", "v", "tartmak; …ağırlığında olmak", "The suitcase weighs 23 kilos.", "Bavul 23 kilo geliyor.", "weight (isim) / weigh (fiil)"],
  ["litre", "n", "litre", "Drink two litres of water a day.", "Günde iki litre su iç."],
  ["kilometre", "n", "kilometre", "The beach is five kilometres away.", "Plaj beş kilometre uzakta."],
  ["square metre", "n", "metrekare", "The flat is 90 square metres.", "Daire 90 metrekare."],
  ["double", "v", "iki katına çıkmak", "The price of rent has doubled.", "Kira fiyatı iki katına çıktı."],
  ["triple", "v", "üç katına çıkmak", "The number of visitors tripled.", "Ziyaretçi sayısı üç katına çıktı."],
  ["divide", "v", "bölmek", "Divide the cake into eight pieces.", "Pastayı sekiz parçaya böl."],
  ["multiply", "v", "çarpmak", "Multiply five by three.", "Beşi üçle çarp."],
  ["proportion", "n", "oran, pay", "A large proportion of students live at home.", "Öğrencilerin büyük bir kısmı evde yaşıyor."],
  ["dozens of", "phr", "düzinelerce, onlarca", "Dozens of people were waiting.", "Onlarca insan bekliyordu."],
  ["a quarter of", "phr", "…nın dörtte biri", "A quarter of the students are from abroad.", "Öğrencilerin dörtte biri yurt dışından."],
  ["roughly", "adv", "kabaca, yaklaşık", "It costs roughly 500 lira.", "Kabaca 500 lira tutuyor."],
];
