import type { LexiconEntry } from "../types";

/** B1 sets 41–45: describing things, adverbs of degree, linking words, abstract nouns, make & do. */
export const B1_PART9: LexiconEntry[] = [
  // Set 41 — Describing things
  ["ordinary", "adj", "sıradan, olağan", "It was just an ordinary day.", "Sıradan bir gündü."],
  ["unique", "adj", "eşsiz, benzersiz", "Every fingerprint is unique.", "Her parmak izi benzersizdir."],
  ["valuable", "adj", "değerli", "Keep your valuable things in the hotel safe.", "Değerli eşyalarınızı otel kasasında saklayın."],
  ["fragile", "adj", "kırılgan, kolay kırılır", "Be careful — the box is fragile.", "Dikkat et, kutu kırılabilir."],
  ["practical", "adj", "pratik, kullanışlı", "Trainers are more practical than high heels.", "Spor ayakkabılar topuklulardan daha kullanışlı."],
  ["efficient", "adj", "verimli, etkili", "The new heating system is very efficient.", "Yeni ısıtma sistemi çok verimli."],
  ["awkward", "adj", "garip, tuhaf; rahatsız edici", "There was an awkward silence.", "Garip bir sessizlik oldu."],
  ["obvious", "adj", "açık, belli", "It was obvious that she was tired.", "Yorgun olduğu belliydi."],
  ["rare", "adj", "nadir, seyrek", "This bird is very rare in Turkey.", "Bu kuş Türkiye'de çok nadirdir."],
  ["typical", "adj", "tipik", "It's a typical Aegean village.", "Tipik bir Ege köyü."],
  ["suitable", "adj", "uygun", "This film isn't suitable for children.", "Bu film çocuklar için uygun değil."],
  ["reasonable", "adj", "makul, mantıklı", "The prices here are very reasonable.", "Buradaki fiyatlar çok makul."],
  ["original", "adj", "özgün, orijinal", "Her designs are very original.", "Tasarımları çok özgün."],
  ["temporary", "adj", "geçici", "He found a temporary job for the summer.", "Yaz için geçici bir iş buldu."],
  ["permanent", "adj", "kalıcı, daimi", "Is this a permanent position?", "Bu kalıcı bir pozisyon mu?"],
  ["enormous", "adj", "devasa, kocaman", "They live in an enormous house.", "Kocaman bir evde yaşıyorlar."],
  ["dull", "adj", "sıkıcı; donuk (renk)", "The lecture was long and dull.", "Ders uzun ve sıkıcıydı."],
  ["ridiculous", "adj", "gülünç, saçma", "That's a ridiculous price for a coffee!", "Bir kahve için saçma bir fiyat!"],
  ["impressive", "adj", "etkileyici", "Her English is really impressive.", "İngilizcesi gerçekten etkileyici."],
  ["outstanding", "adj", "olağanüstü, seçkin", "He's an outstanding student.", "Olağanüstü bir öğrenci."],

  // Set 42 — Adverbs of degree & attitude
  ["absolutely", "adv", "kesinlikle, tamamen", "The view was absolutely amazing.", "Manzara kesinlikle muhteşemdi.", "Güçlü sıfatlarla: absolutely delicious"],
  ["completely", "adv", "tamamen", "I completely forgot about the meeting.", "Toplantıyı tamamen unuttum."],
  ["extremely", "adv", "son derece", "The test was extremely difficult.", "Sınav son derece zordu."],
  ["fairly", "adv", "oldukça, epey", "I'm fairly sure he'll agree.", "Kabul edeceğinden oldukça eminim."],
  ["rather", "adv", "oldukça, epeyce", "It's rather cold today.", "Bugün epey soğuk.", "would rather: tercih etmek"],
  ["totally", "adv", "tamamen, büsbütün", "I totally agree with you.", "Sana tamamen katılıyorum."],
  ["barely", "adv", "zar zor, ancak", "I could barely hear him.", "Onu zar zor duyabiliyordum."],
  ["entirely", "adv", "tamamen, bütünüyle", "It's entirely your decision.", "Bu tamamen senin kararın."],
  ["highly", "adv", "çok, son derece", "I highly recommend this book.", "Bu kitabı şiddetle tavsiye ederim."],
  ["incredibly", "adv", "inanılmaz derecede", "The concert was incredibly loud.", "Konser inanılmaz derecede gürültülüydü."],
  ["mainly", "adv", "çoğunlukla, esas olarak", "The students are mainly from Ankara.", "Öğrenciler çoğunlukla Ankara'dan."],
  ["particularly", "adv", "özellikle", "I particularly liked the ending.", "Özellikle sonunu beğendim."],
  ["seriously", "adv", "ciddi olarak, ciddi biçimde", "He was seriously injured.", "Ciddi şekilde yaralandı."],
  ["surprisingly", "adv", "şaşırtıcı biçimde", "Surprisingly, the exam was easy.", "Şaşırtıcı şekilde sınav kolaydı."],
  ["unfortunately", "adv", "maalesef, ne yazık ki", "Unfortunately, the flight was cancelled.", "Maalesef uçuş iptal edildi."],
  ["luckily", "adv", "neyse ki, şans eseri", "Luckily, nobody was hurt.", "Neyse ki kimse yaralanmadı."],
  ["eventually", "adv", "sonunda, eninde sonunda", "We eventually found the hotel.", "Sonunda oteli bulduk.", "Türkçedeki 'eventüel' ile karıştırma."],
  ["apparently", "adv", "görünüşe göre, anlaşılan", "Apparently, the shop is closing down.", "Görünüşe göre dükkân kapanıyor."],
  ["definitely", "adv", "kesinlikle, mutlaka", "I'll definitely come to your party.", "Partine kesinlikle geleceğim."],
  ["approximately", "adv", "yaklaşık olarak", "The trip takes approximately three hours.", "Yolculuk yaklaşık üç saat sürüyor."],

  // Set 43 — Linking words
  ["despite", "prep", "-e rağmen", "Despite the rain, we went for a walk.", "Yağmura rağmen yürüyüşe çıktık.", "despite + isim / -ing"],
  ["in spite of", "prep", "-e rağmen", "In spite of his age, he runs every day.", "Yaşına rağmen her gün koşuyor."],
  ["furthermore", "adv", "ayrıca, bundan başka", "The flat is cheap. Furthermore, it's near the station.", "Daire ucuz. Üstelik istasyona yakın."],
  ["in addition", "phr", "buna ek olarak", "In addition, students get a free lunch.", "Buna ek olarak öğrenciler bedava öğle yemeği alıyor."],
  ["otherwise", "adv", "aksi halde, yoksa", "Hurry up, otherwise we'll miss the bus.", "Acele et, yoksa otobüsü kaçıracağız."],
  ["as long as", "conj", "…dığı sürece", "You can borrow my car as long as you're careful.", "Dikkatli olduğun sürece arabamı ödünç alabilirsin."],
  ["even though", "conj", "…e rağmen, …dığı halde", "Even though he was tired, he kept working.", "Yorgun olduğu halde çalışmaya devam etti."],
  ["unlike", "prep", "…in aksine, …e benzemeyen", "Unlike my sister, I love mornings.", "Kız kardeşimin aksine sabahları severim."],
  ["apart from", "prep", "…dışında, …den başka", "Apart from Ali, everyone came.", "Ali dışında herkes geldi."],
  ["instead", "adv", "onun yerine", "There was no tea, so I had coffee instead.", "Çay yoktu, onun yerine kahve içtim."],
  ["meanwhile", "adv", "bu arada, o sırada", "I cooked dinner. Meanwhile, the kids set the table.", "Ben yemeği pişirdim. Bu arada çocuklar sofrayı kurdu."],
  ["on the contrary", "phr", "tam tersine", "It wasn't boring. On the contrary, it was fascinating.", "Sıkıcı değildi. Tam tersine, büyüleyiciydi."],
  ["in other words", "phr", "başka bir deyişle", "He's economical — in other words, he's mean!", "Tutumludur, başka bir deyişle cimridir!"],
  ["as a matter of fact", "phr", "aslına bakarsan", "As a matter of fact, I've been there twice.", "Aslına bakarsan oraya iki kez gittim."],
  ["consequently", "adv", "sonuç olarak, bu nedenle", "He missed the bus and consequently was late.", "Otobüsü kaçırdı ve bu nedenle geç kaldı."],
  ["provided that", "conj", "…mesi şartıyla", "You can go out provided that you finish your homework.", "Ödevini bitirmen şartıyla dışarı çıkabilirsin."],
  ["in case", "conj", "…ihtimaline karşı", "Take an umbrella in case it rains.", "Yağmur yağma ihtimaline karşı şemsiye al."],
  ["to sum up", "phr", "özetlemek gerekirse", "To sum up, the project was a success.", "Özetlemek gerekirse, proje başarılı oldu."],
  ["similarly", "adv", "benzer şekilde", "Similarly, prices in Izmir have gone up.", "Benzer şekilde İzmir'de de fiyatlar arttı."],
  ["as well as", "prep", "…in yanı sıra", "She speaks German as well as English.", "İngilizcenin yanı sıra Almanca da konuşuyor."],

  // Set 44 — Abstract nouns
  ["confidence", "n", "özgüven; güven", "Speaking clubs gave me more confidence.", "Konuşma kulüpleri bana daha fazla özgüven verdi."],
  ["patience", "n", "sabır", "Learning a language takes patience.", "Dil öğrenmek sabır ister."],
  ["honesty", "n", "dürüstlük", "I value honesty in a friend.", "Bir arkadaşta dürüstlüğe değer veririm."],
  ["courage", "n", "cesaret", "It takes courage to speak in public.", "Topluluk önünde konuşmak cesaret ister."],
  ["pride", "n", "gurur", "She spoke with pride about her son.", "Oğlundan gururla bahsetti."],
  ["anger", "n", "öfke", "He couldn't hide his anger.", "Öfkesini saklayamadı."],
  ["happiness", "n", "mutluluk", "Money doesn't always bring happiness.", "Para her zaman mutluluk getirmez."],
  ["wisdom", "n", "bilgelik", "My grandfather was a man of great wisdom.", "Dedem çok bilge bir adamdı."],
  ["curiosity", "n", "merak", "Children are full of curiosity.", "Çocuklar merak doludur."],
  ["kindness", "n", "nezaket, iyilik", "Thank you for your kindness.", "İyiliğiniz için teşekkür ederim."],
  ["jealousy", "n", "kıskançlık", "Jealousy can ruin a friendship.", "Kıskançlık bir arkadaşlığı mahvedebilir."],
  ["loneliness", "n", "yalnızlık", "Many elderly people suffer from loneliness.", "Birçok yaşlı insan yalnızlıktan muzdarip."],
  ["justice", "n", "adalet", "The victims want justice.", "Mağdurlar adalet istiyor."],
  ["imagination", "n", "hayal gücü", "Reading develops your imagination.", "Okumak hayal gücünü geliştirir."],
  ["awareness", "n", "farkındalık, bilinç", "The campaign raised awareness of the problem.", "Kampanya soruna dair farkındalık yarattı."],
  ["strength", "n", "güç; güçlü yön", "Patience is one of her strengths.", "Sabır onun güçlü yönlerinden biri."],
  ["weakness", "n", "zayıflık; zayıf yön", "Chocolate is my weakness.", "Çikolata benim zaafım."],
  ["sense of humour", "n", "mizah anlayışı", "He has a great sense of humour.", "Harika bir mizah anlayışı var."],
  ["identity", "n", "kimlik", "Language is part of our identity.", "Dil kimliğimizin bir parçasıdır."],
  ["self-esteem", "n", "özsaygı, öz değer", "Praise can improve a child's self-esteem.", "Övgü bir çocuğun özsaygısını artırabilir."],

  // Set 45 — Collocations: make & do
  ["make a decision", "phr", "karar vermek", "I need to make a decision by Friday.", "Cumaya kadar bir karar vermem gerek.", "take a decision değil, make a decision"],
  ["make an effort", "phr", "çaba göstermek", "Please make an effort to arrive on time.", "Lütfen zamanında gelmek için çaba gösterin."],
  ["make progress", "phr", "ilerleme kaydetmek", "You're making good progress with your English.", "İngilizcende iyi ilerleme kaydediyorsun."],
  ["make a complaint", "phr", "şikâyette bulunmak", "I'd like to make a complaint about the service.", "Hizmetle ilgili şikâyette bulunmak istiyorum."],
  ["make a living", "phr", "geçimini sağlamak", "He makes a living as a photographer.", "Fotoğrafçı olarak geçimini sağlıyor."],
  ["make a difference", "phr", "fark yaratmak", "Small changes can make a big difference.", "Küçük değişiklikler büyük fark yaratabilir."],
  ["make fun of", "phr", "dalga geçmek", "Don't make fun of his accent.", "Aksanıyla dalga geçme."],
  ["make an appointment", "phr", "randevu almak", "I made an appointment with the dentist.", "Dişçiden randevu aldım."],
  ["make room for", "phr", "yer açmak", "Can you make room for one more person?", "Bir kişi daha için yer açabilir misin?"],
  ["make a mess", "phr", "ortalığı dağıtmak", "The kids made a mess in the kitchen.", "Çocuklar mutfağı darmadağın etti."],
  ["make sense", "phr", "anlamlı olmak, mantıklı gelmek", "Your explanation makes sense.", "Açıklaman mantıklı."],
  ["make an excuse", "phr", "bahane uydurmak", "Stop making excuses and start studying.", "Bahane uydurmayı bırak ve çalışmaya başla."],
  ["do your best", "phr", "elinden geleni yapmak", "Just do your best in the exam.", "Sınavda sadece elinden gelenin en iyisini yap."],
  ["do business", "phr", "iş yapmak, ticaret yapmak", "We do business with companies in Germany.", "Almanya'daki şirketlerle iş yapıyoruz."],
  ["do research", "phr", "araştırma yapmak", "She's doing research on climate change.", "İklim değişikliği üzerine araştırma yapıyor.", "make research denmez"],
  ["do someone a favour", "phr", "birine iyilik yapmak", "Could you do me a favour and close the window?", "Bana bir iyilik yapıp pencereyi kapatır mısın?"],
  ["do harm", "phr", "zarar vermek", "A little chocolate won't do you any harm.", "Biraz çikolata sana zarar vermez."],
  ["do without", "pv", "…sız idare etmek", "I can't do without my morning coffee.", "Sabah kahvem olmadan idare edemem."],
  ["do well", "phr", "başarılı olmak, iyi iş çıkarmak", "She did well in her exams.", "Sınavlarında başarılı oldu."],
  ["do the shopping", "phr", "alışveriş yapmak (günlük)", "I usually do the shopping on Saturdays.", "Genelde cumartesileri alışveriş yaparım."],
];
