import type { LexiconEntry } from "../types";

/** B1 sets 36–40: phrasal verbs (daily life, people), thinking verbs, reporting verbs, describing people. */
export const B1_PART8: LexiconEntry[] = [
  // Set 36 — Phrasal verbs: daily life
  ["carry on", "pv", "devam etmek", "Carry on working — I'll be back in a minute.", "Çalışmaya devam et, bir dakikaya dönerim.", "carry on + -ing"],
  ["put off", "pv", "ertelemek", "Don't put off your homework until Sunday.", "Ödevini pazara erteleme."],
  ["turn out", "pv", "(sonunda) ortaya çıkmak, …olduğu anlaşılmak", "The film turned out to be really good.", "Filmin çok iyi olduğu ortaya çıktı.", "turn out to be + sıfat/isim"],
  ["figure out", "pv", "çözmek, anlamak", "I can't figure out how this app works.", "Bu uygulamanın nasıl çalıştığını çözemiyorum."],
  ["come up with", "pv", "(fikir) bulmak, ortaya atmak", "She came up with a great idea.", "Harika bir fikir buldu."],
  ["deal with", "pv", "ilgilenmek, başa çıkmak", "The manager will deal with your complaint.", "Müdür şikâyetinizle ilgilenecek."],
  ["get over", "pv", "atlatmak, üstesinden gelmek", "It took him weeks to get over the flu.", "Gribi atlatması haftalar sürdü."],
  ["go through", "pv", "yaşamak (zor bir dönem); gözden geçirmek", "She went through a difficult time last year.", "Geçen yıl zor bir dönem yaşadı."],
  ["run into", "pv", "tesadüfen karşılaşmak", "I ran into my old teacher at the market.", "Pazarda eski öğretmenime rastladım."],
  ["sort out", "pv", "halletmek, düzene sokmak", "We need to sort out this problem today.", "Bu sorunu bugün halletmemiz gerek."],
  ["point out", "pv", "belirtmek, dikkat çekmek", "He pointed out a mistake in my essay.", "Kompozisyonumdaki bir hataya dikkat çekti."],
  ["take over", "pv", "devralmak, kontrolü ele geçirmek", "Her son took over the family business.", "Aile işini oğlu devraldı."],
  ["keep up with", "pv", "ayak uydurmak, geri kalmamak", "It's hard to keep up with new technology.", "Yeni teknolojiye ayak uydurmak zor."],
  ["catch up", "pv", "yetişmek, aradaki farkı kapatmak", "I missed a week of school, so I need to catch up.", "Okulda bir haftayı kaçırdım, yetişmem gerek.", "catch up with sb: biriyle hasret gidermek"],
  ["end up", "pv", "sonunda (bir yere/duruma) varmak", "We got lost and ended up in a small village.", "Kaybolduk ve sonunda küçük bir köye vardık.", "end up + -ing"],
  ["hand in", "pv", "teslim etmek", "Please hand in your essays on Friday.", "Lütfen kompozisyonlarınızı cuma günü teslim edin."],
  ["give away", "pv", "bedava vermek, dağıtmak; ele vermek", "She gave away all her old books.", "Tüm eski kitaplarını dağıttı."],
  ["set up", "pv", "kurmak", "They set up a small company in 2020.", "2020'de küçük bir şirket kurdular."],
  ["work on", "pv", "üzerinde çalışmak", "I'm working on my pronunciation.", "Telaffuzum üzerinde çalışıyorum."],
  ["get rid of", "phr", "kurtulmak, elden çıkarmak", "I want to get rid of this old sofa.", "Bu eski kanepeden kurtulmak istiyorum."],

  // Set 37 — Phrasal verbs: people & relationships
  ["fall out", "pv", "bozuşmak, küsmek", "They fell out over money.", "Para yüzünden bozuştular.", "fall out with sb"],
  ["make up", "pv", "barışmak; uydurmak", "They argued but made up the next day.", "Tartıştılar ama ertesi gün barıştılar."],
  ["break up", "pv", "(ilişki) bitirmek, ayrılmak", "She broke up with her boyfriend.", "Erkek arkadaşından ayrıldı."],
  ["count on", "pv", "güvenmek, bel bağlamak", "You can always count on me.", "Bana her zaman güvenebilirsin."],
  ["let down", "pv", "hayal kırıklığına uğratmak, yüzüstü bırakmak", "I promised to help and I won't let you down.", "Yardım edeceğime söz verdim, seni yüzüstü bırakmayacağım."],
  ["split up", "pv", "ayrılmak (çift, grup)", "Her parents split up when she was ten.", "O on yaşındayken annesiyle babası ayrıldı."],
  ["settle down", "pv", "düzen kurmak, yerleşmek", "He wants to settle down and have children.", "Düzen kurup çocuk sahibi olmak istiyor."],
  ["grow apart", "pv", "(zamanla) birbirinden uzaklaşmak", "We were best friends, but we grew apart.", "En iyi arkadaştık ama zamanla uzaklaştık."],
  ["ask out", "pv", "çıkma teklif etmek", "He finally asked her out.", "Sonunda ona çıkma teklif etti."],
  ["put up with", "pv", "katlanmak, tahammül etmek", "I can't put up with this noise any more.", "Bu gürültüye artık katlanamıyorum."],
  ["stand up for", "pv", "savunmak, arka çıkmak", "You should stand up for your friends.", "Arkadaşlarına arka çıkmalısın."],
  ["calm down", "pv", "sakinleşmek", "Calm down and tell me what happened.", "Sakin ol ve bana ne olduğunu anlat."],
  ["show off", "pv", "gösteriş yapmak, hava atmak", "He's always showing off his new car.", "Sürekli yeni arabasıyla hava atıyor."],
  ["turn to", "pv", "(yardım için) başvurmak", "She had no one to turn to.", "Başvurabileceği kimse yoktu."],
  ["go out with", "pv", "(biriyle) çıkmak", "How long have you been going out with him?", "Ne zamandır onunla çıkıyorsun?"],
  ["drop out", "pv", "(okulu) bırakmak", "He dropped out of university after a year.", "Bir yıl sonra üniversiteyi bıraktı."],
  ["call off", "pv", "iptal etmek", "The match was called off because of the rain.", "Maç yağmur yüzünden iptal edildi."],
  ["pick on", "pv", "(birine) sataşmak, üstüne gitmek", "Stop picking on your little brother!", "Küçük kardeşine sataşmayı bırak!"],
  ["open up", "pv", "içini açmak", "It took time for him to open up to me.", "Bana içini açması zaman aldı."],
  ["look down on", "pv", "küçümsemek, tepeden bakmak", "Don't look down on people with less money.", "Daha az parası olan insanları küçümseme."],

  // Set 38 — Thinking & opinions
  ["assume", "v", "varsaymak, farz etmek", "I assumed you already knew.", "Zaten bildiğini varsaydım."],
  ["consider", "v", "düşünmek, göz önünde bulundurmak", "We're considering moving to Izmir.", "İzmir'e taşınmayı düşünüyoruz.", "consider + -ing"],
  ["doubt", "v", "şüphe etmek", "I doubt he will come on time.", "Zamanında geleceğinden şüpheliyim."],
  ["wonder", "v", "merak etmek", "I wonder why she left so early.", "Neden bu kadar erken gittiğini merak ediyorum."],
  ["suppose", "v", "sanmak, farz etmek", "I suppose you're right.", "Sanırım haklısın.", "be supposed to: …mesi gerekiyor"],
  ["recognise", "v", "tanımak; kabul etmek", "I didn't recognise you with short hair.", "Kısa saçla seni tanıyamadım."],
  ["estimate", "v", "tahmin etmek (sayı/miktar)", "They estimate the cost at 2 million lira.", "Maliyeti 2 milyon lira olarak tahmin ediyorlar."],
  ["predict", "v", "öngörmek, tahmin etmek", "Nobody predicted the result of the match.", "Maçın sonucunu kimse öngörmedi."],
  ["judge", "v", "yargılamak, değerlendirmek", "Don't judge people by their clothes.", "İnsanları kıyafetlerine göre yargılama."],
  ["reckon", "v", "sanmak, düşünmek (günlük)", "I reckon it's going to rain.", "Bence yağmur yağacak.", "Konuşma dilinde think anlamında."],
  ["conclude", "v", "sonucuna varmak", "The report concluded that the plan was too expensive.", "Rapor planın çok pahalı olduğu sonucuna vardı."],
  ["suspect", "v", "şüphelenmek, sezmek", "I suspect he's not telling the truth.", "Doğruyu söylemediğinden şüpheleniyorum."],
  ["reflect", "v", "üzerine düşünmek; yansıtmak", "Take a moment to reflect on your mistakes.", "Hataların üzerine düşünmek için biraz zaman ayır."],
  ["ignore", "v", "görmezden gelmek", "She ignored my message.", "Mesajımı görmezden geldi."],
  ["approve of", "pv", "onaylamak, uygun bulmak", "My parents don't approve of my new job.", "Ailem yeni işimi onaylamıyor."],
  ["be aware of", "phr", "farkında olmak", "Are you aware of the risks?", "Risklerin farkında mısın?"],
  ["make up your mind", "phr", "karar vermek", "Have you made up your mind yet?", "Kararını verdin mi?"],
  ["keep in mind", "phr", "aklında tutmak", "Keep in mind that the shop closes at six.", "Dükkânın altıda kapandığını aklında tut."],
  ["on second thoughts", "phr", "bir daha düşündüm de", "On second thoughts, I'll have tea instead.", "Bir daha düşündüm de, onun yerine çay alayım."],
  ["tend", "v", "eğiliminde olmak", "I tend to wake up early at weekends.", "Hafta sonları erken uyanma eğilimindeyim.", "tend to + fiil"],

  // Set 39 — Reporting & communication
  ["reveal", "v", "açığa çıkarmak, ortaya koymak", "The study revealed some surprising facts.", "Çalışma bazı şaşırtıcı gerçekleri ortaya koydu."],
  ["confirm", "v", "onaylamak, teyit etmek", "Please confirm your booking by email.", "Lütfen rezervasyonunuzu e-postayla teyit edin."],
  ["declare", "v", "ilan etmek, beyan etmek", "The government declared a state of emergency.", "Hükümet olağanüstü hal ilan etti."],
  ["remark", "v", "(yorum olarak) söylemek", "She remarked that the room was cold.", "Odanın soğuk olduğunu söyledi."],
  ["emphasise", "v", "vurgulamak", "The teacher emphasised the importance of reading.", "Öğretmen okumanın önemini vurguladı."],
  ["stress", "v", "vurgulamak, altını çizmek", "He stressed that safety comes first.", "Güvenliğin önce geldiğinin altını çizdi."],
  ["refer to", "pv", "değinmek, bahsetmek", "Which article are you referring to?", "Hangi makaleden bahsediyorsun?"],
  ["inform", "v", "bilgilendirmek", "Please inform us of any changes.", "Lütfen her türlü değişiklikten bizi haberdar edin."],
  ["assure", "v", "temin etmek, güvence vermek", "I assure you everything is fine.", "Sizi temin ederim ki her şey yolunda."],
  ["beg", "v", "yalvarmak", "He begged me to stay.", "Kalmam için bana yalvardı."],
  ["threaten", "v", "tehdit etmek", "They threatened to call the police.", "Polisi aramakla tehdit ettiler."],
  ["boast", "v", "övünmek, böbürlenmek", "He always boasts about his grades.", "Notlarıyla hep övünür."],
  ["accuse", "v", "suçlamak", "She accused him of lying.", "Onu yalan söylemekle suçladı.", "accuse sb of + -ing"],
  ["express", "v", "ifade etmek", "It's hard to express my feelings in English.", "Duygularımı İngilizce ifade etmek zor."],
  ["request", "v", "rica etmek, talep etmek", "Passengers are requested to stay seated.", "Yolcuların oturmaları rica olunur."],
  ["exaggerate", "v", "abartmak", "Don't exaggerate — it wasn't that bad!", "Abartma, o kadar da kötü değildi!"],
  ["encourage", "v", "cesaretlendirmek, teşvik etmek", "My teacher encouraged me to take the exam.", "Öğretmenim sınava girmem için beni cesaretlendirdi."],
  ["forbid", "v", "yasaklamak", "My father forbade me to go out.", "Babam dışarı çıkmamı yasakladı.", "forbid – forbade – forbidden"],
  ["advise", "v", "tavsiye etmek", "The doctor advised me to rest.", "Doktor dinlenmemi tavsiye etti.", "advice (isim) / advise (fiil)"],
  ["clarify", "v", "açıklığa kavuşturmak", "Could you clarify what you mean?", "Ne demek istediğini açar mısın?"],

  // Set 40 — Describing people
  ["skinny", "adj", "sıska", "He was a skinny boy but now he's strong.", "Sıska bir çocuktu ama şimdi güçlü."],
  ["muscular", "adj", "kaslı", "The swimmer has a muscular body.", "Yüzücünün kaslı bir vücudu var."],
  ["pale", "adj", "solgun, soluk", "You look pale. Are you OK?", "Solgun görünüyorsun. İyi misin?"],
  ["wrinkle", "n", "kırışıklık", "My grandmother has lots of wrinkles.", "Büyükannemin çok kırışıklığı var."],
  ["scar", "n", "yara izi", "He has a scar on his forehead.", "Alnında bir yara izi var."],
  ["well-dressed", "adj", "şık giyimli", "She's always well-dressed at work.", "İşte hep şık giyimlidir."],
  ["scruffy", "adj", "dağınık, pejmürde", "He looked scruffy in his old jeans.", "Eski kotuyla pejmürde görünüyordu."],
  ["middle-aged", "adj", "orta yaşlı", "A middle-aged man opened the door.", "Kapıyı orta yaşlı bir adam açtı."],
  ["in his twenties", "phr", "yirmili yaşlarında", "The new teacher is in his twenties.", "Yeni öğretmen yirmili yaşlarında.", "in her thirties, in their forties…"],
  ["sociable", "adj", "sosyal, girişken", "She's very sociable and loves parties.", "Çok sosyaldir, partileri sever."],
  ["outgoing", "adj", "dışa dönük", "My brother is outgoing, but I'm quite shy.", "Kardeşim dışa dönük ama ben oldukça utangacım."],
  ["reserved", "adj", "çekingen, ağzı sıkı", "He's reserved at first, but very kind.", "İlk başta çekingendir ama çok naziktir."],
  ["bad-tempered", "adj", "huysuz, sinirli", "He's always bad-tempered in the morning.", "Sabahları hep huysuzdur."],
  ["cheeky", "adj", "şımarık, arsız (sevimli şekilde)", "Don't be cheeky to your teacher!", "Öğretmenine arsızlık etme!"],
  ["determined", "adj", "kararlı", "She's determined to pass the exam.", "Sınavı geçmeye kararlı."],
  ["impatient", "adj", "sabırsız", "Don't be so impatient — the bus will come.", "Bu kadar sabırsız olma, otobüs gelecek."],
  ["selfless", "adj", "özverili", "Nurses do selfless work every day.", "Hemşireler her gün özverili bir iş yapıyor."],
  ["thoughtful", "adj", "düşünceli, ince", "What a thoughtful present!", "Ne kadar düşünceli bir hediye!"],
  ["big-headed", "adj", "kendini beğenmiş", "Since he won the prize, he's become big-headed.", "Ödülü kazandığından beri kendini beğenmiş biri oldu."],
  ["trustworthy", "adj", "güvenilir", "She's the most trustworthy person I know.", "Tanıdığım en güvenilir kişi o."],
];
