import type { LexiconEntry } from "../types";

/** B1 sets 21–25: research, the internet, news, culture, books & reading. */
export const B1_PART5: LexiconEntry[] = [
  // Set 21 — Research
  ["scientific", "adj", "bilimsel", "There's no scientific proof.", "Bilimsel bir kanıt yok."],
  ["theory", "n", "kuram, teori", "Darwin's theory of evolution changed science.", "Darwin'in evrim kuramı bilimi değiştirdi."],
  ["data", "n", "veri", "We collected data from 500 students.", "500 öğrenciden veri topladık."],
  ["analyse", "v", "analiz etmek", "Scientists are analysing the results.", "Bilim insanları sonuçları analiz ediyor."],
  ["analysis", "n", "analiz", "The analysis took three months.", "Analiz üç ay sürdü."],
  ["survey", "n", "anket, araştırma", "A survey shows most people want change.", "Bir anket çoğu insanın değişim istediğini gösteriyor."],
  ["sample", "n", "örnek, numune", "The doctor took a blood sample.", "Doktor kan örneği aldı."],
  ["method", "n", "yöntem", "We need a new method.", "Yeni bir yönteme ihtiyacımız var."],
  ["conclusion", "n", "sonuç, kanı", "What conclusion did you reach?", "Hangi sonuca vardın?"],
  ["discovery", "n", "keşif", "It was an important discovery.", "Önemli bir keşifti."],
  ["observe", "v", "gözlemlemek", "We observed the birds for an hour.", "Kuşları bir saat gözlemledik."],
  ["test", "v", "test etmek", "The new drug was tested on volunteers.", "Yeni ilaç gönüllüler üzerinde test edildi."],
  ["expert", "n", "uzman", "She's an expert on ancient history.", "Antik tarih uzmanı."],
  ["microscope", "n", "mikroskop", "Look at the cells under the microscope.", "Hücrelere mikroskopla bak."],
  ["cell", "n", "hücre", "The body is made of billions of cells.", "Vücut milyarlarca hücreden oluşur."],
  ["gene", "n", "gen", "Eye colour is controlled by genes.", "Göz rengi genlerle belirlenir."],
  ["chemical", "n", "kimyasal", "Wear gloves when using chemicals.", "Kimyasal kullanırken eldiven giy."],
  ["atom", "n", "atom", "Everything is made of atoms.", "Her şey atomlardan oluşur."],
  ["oxygen", "n", "oksijen", "Plants produce oxygen.", "Bitkiler oksijen üretir."],
  ["statistics", "n", "istatistik", "The statistics show a rise in crime.", "İstatistikler suçta artış gösteriyor."],

  // Set 22 — The internet
  ["browser", "n", "tarayıcı", "Open the link in your browser.", "Bağlantıyı tarayıcında aç."],
  ["search engine", "n", "arama motoru", "Use a search engine to find it.", "Bulmak için bir arama motoru kullan."],
  ["link", "n", "bağlantı", "Click on the link to register.", "Kaydolmak için bağlantıya tıkla."],
  ["attachment", "n", "ek (e-posta)", "I sent the file as an attachment.", "Dosyayı ek olarak gönderdim."],
  ["sign up", "pv", "kaydolmak, üye olmak", "Sign up to get our newsletter.", "Bültenimizi almak için kaydol."],
  ["profile", "n", "profil", "Update your profile picture.", "Profil fotoğrafını güncelle."],
  ["follower", "n", "takipçi", "She has a million followers.", "Bir milyon takipçisi var."],
  ["influencer", "n", "sosyal medya fenomeni", "Brands pay influencers to advertise.", "Markalar reklam için fenomenlere para ödüyor."],
  ["hashtag", "n", "etiket (#)", "Use the hashtag in your post.", "Paylaşımında bu etiketi kullan."],
  ["stream", "v", "canlı yayın yapmak, çevrim içi izlemek", "We streamed the match online.", "Maçı internetten izledik."],
  ["hacker", "n", "bilgisayar korsanı", "Hackers stole customer data.", "Bilgisayar korsanları müşteri verilerini çaldı."],
  ["malware", "n", "kötü amaçlı yazılım", "Don't click that link — it could be malware.", "O bağlantıya tıklama, kötü amaçlı yazılım olabilir."],
  ["update", "n", "güncelleme", "Install the latest update.", "En son güncellemeyi yükle."],
  ["cyberbullying", "n", "siber zorbalık", "Schools are fighting cyberbullying.", "Okullar siber zorbalıkla mücadele ediyor."],
  ["privacy", "n", "gizlilik", "Check your privacy settings.", "Gizlilik ayarlarını kontrol et."],
  ["digital", "adj", "dijital", "We live in a digital world.", "Dijital bir dünyada yaşıyoruz."],
  ["software", "n", "yazılım", "The company makes accounting software.", "Şirket muhasebe yazılımı üretiyor."],
  ["hardware", "n", "donanım", "The problem is with the hardware.", "Sorun donanımda."],
  ["crash", "v", "çökmek (bilgisayar)", "My computer crashed and I lost my work.", "Bilgisayarım çöktü ve çalışmamı kaybettim."],
  ["artificial intelligence", "n", "yapay zekâ", "Artificial intelligence is changing jobs.", "Yapay zekâ meslekleri değiştiriyor."],

  // Set 23 — News
  ["the media", "n", "medya", "The media reported the story widely.", "Medya haberi geniş şekilde yayınladı."],
  ["broadcast", "v", "yayınlamak", "The match will be broadcast live.", "Maç canlı yayınlanacak."],
  ["reporter", "n", "muhabir", "A reporter interviewed the mayor.", "Bir muhabir belediye başkanıyla röportaj yaptı."],
  ["editor", "n", "editör", "The editor checks every article.", "Editör her makaleyi kontrol eder."],
  ["press", "n", "basın", "The minister spoke to the press.", "Bakan basına konuştu."],
  ["publish", "v", "yayımlamak", "The book was published in 2020.", "Kitap 2020'de yayımlandı."],
  ["current affairs", "n", "güncel olaylar", "She follows current affairs closely.", "Güncel olayları yakından takip ediyor."],
  ["breaking news", "n", "son dakika haberi", "Here's some breaking news.", "İşte son dakika haberi."],
  ["report", "v", "haber yapmak, bildirmek", "The newspaper reported the accident.", "Gazete kazayı haber yaptı."],
  ["press conference", "n", "basın toplantısı", "The minister held a press conference.", "Bakan bir basın toplantısı düzenledi."],
  ["reliable source", "n", "güvenilir kaynak", "Always check news from a reliable source.", "Haberleri her zaman güvenilir bir kaynaktan kontrol et."],
  ["fake news", "n", "sahte haber", "Fake news spreads fast online.", "Sahte haberler internette hızla yayılır."],
  ["tabloid", "n", "magazin gazetesi", "Tabloids write about celebrities.", "Magazin gazeteleri ünlüler hakkında yazar."],
  ["celebrity", "n", "ünlü", "Celebrities often avoid photographers.", "Ünlüler sık sık fotoğrafçılardan kaçar."],
  ["interview", "v", "röportaj yapmak", "She interviewed the prime minister.", "Başbakanla röportaj yaptı."],
  ["viewer", "n", "izleyici", "The show has millions of viewers.", "Programın milyonlarca izleyicisi var."],
  ["coverage", "n", "haber, yayın (kapsamı)", "The election got a lot of coverage.", "Seçim geniş yer buldu."],
  ["censorship", "n", "sansür", "There is strict censorship in some countries.", "Bazı ülkelerde sıkı sansür var."],
  ["journalism", "n", "gazetecilik", "She studied journalism at university.", "Üniversitede gazetecilik okudu."],
  ["columnist", "n", "köşe yazarı", "He's a well-known newspaper columnist.", "Tanınmış bir gazete köşe yazarı."],

  // Set 24 — Culture
  ["culture", "n", "kültür", "I'm interested in Japanese culture.", "Japon kültürüyle ilgileniyorum."],
  ["cultural", "adj", "kültürel", "Istanbul has a rich cultural life.", "İstanbul'un zengin bir kültürel hayatı var."],
  ["custom", "n", "gelenek, âdet", "It's a local custom to bring sweets.", "Tatlı getirmek yerel bir âdettir."],
  ["film critic", "n", "film eleştirmeni", "The film critic gave it five stars.", "Film eleştirmeni ona beş yıldız verdi."],
  ["sculpture", "n", "heykel", "The museum has Roman sculptures.", "Müzede Roma heykelleri var."],
  ["artwork", "n", "sanat eseri", "The gallery sold three artworks.", "Galeri üç sanat eseri sattı."],
  ["masterpiece", "n", "başyapıt", "The Mona Lisa is a masterpiece.", "Mona Lisa bir başyapıttır."],
  ["portrait", "n", "portre", "She painted a portrait of her father.", "Babasının portresini yaptı."],
  ["photographer", "n", "fotoğrafçı", "The photographer took pictures of the wedding.", "Fotoğrafçı düğünün fotoğraflarını çekti."],
  ["performance", "n", "gösteri, performans", "The dancers gave a great performance.", "Dansçılar harika bir gösteri sundu."],
  ["perform", "v", "sahnelemek, sahne almak", "The band performed in the square.", "Grup meydanda sahne aldı."],
  ["rehearsal", "n", "prova", "We have a rehearsal before the show.", "Gösteriden önce provamız var."],
  ["opera", "n", "opera", "We went to the opera in Vienna.", "Viyana'da operaya gittik."],
  ["ballet", "n", "bale", "She has done ballet since she was five.", "Beş yaşından beri bale yapıyor."],
  ["classical", "adj", "klasik", "I listen to classical music when I study.", "Ders çalışırken klasik müzik dinlerim."],
  ["folk", "adj", "halk (müziği, dansı)", "They danced to Turkish folk music.", "Türk halk müziğiyle dans ettiler."],
  ["craft", "n", "el sanatı, zanaat", "Carpet weaving is a traditional craft.", "Halı dokumacılığı geleneksel bir el sanatıdır."],
  ["creative", "adj", "yaratıcı", "She's a very creative designer.", "Çok yaratıcı bir tasarımcı."],
  ["inspire", "v", "ilham vermek", "Nature inspires many artists.", "Doğa birçok sanatçıya ilham verir."],
  ["talented", "adj", "yetenekli", "He's a talented young painter.", "Yetenekli genç bir ressam."],

  // Set 25 — Books & reading
  ["fiction", "n", "kurgu", "I prefer fiction to biographies.", "Kurguyu biyografilere tercih ederim."],
  ["non-fiction", "n", "kurgu dışı", "Non-fiction books are based on facts.", "Kurgu dışı kitaplar gerçeklere dayanır."],
  ["biography", "n", "biyografi", "I'm reading a biography of Atatürk.", "Atatürk'ün bir biyografisini okuyorum."],
  ["plot", "n", "olay örgüsü", "The plot is very exciting.", "Olay örgüsü çok heyecan verici."],
  ["chapter", "n", "bölüm", "I read two chapters last night.", "Dün gece iki bölüm okudum."],
  ["main character", "n", "baş karakter", "The main character is a detective.", "Baş karakter bir dedektif."],
  ["setting", "n", "mekan, geçtiği yer", "The setting of the novel is Istanbul.", "Romanın geçtiği yer İstanbul."],
  ["ending", "n", "son", "The film has a happy ending.", "Filmin mutlu bir sonu var."],
  ["bestseller", "n", "çok satan", "Her new book is a bestseller.", "Yeni kitabı çok satanlar arasında."],
  ["poetry", "n", "şiir (türü)", "I love reading poetry.", "Şiir okumayı severim."],
  ["poet", "n", "şair", "Nazım Hikmet is a famous poet.", "Nazım Hikmet ünlü bir şairdir."],
  ["writer", "n", "yazar", "She's a writer of children's books.", "Çocuk kitapları yazarı."],
  ["translate", "v", "çevirmek", "The book was translated into 40 languages.", "Kitap 40 dile çevrildi."],
  ["translation", "n", "çeviri", "I read the English translation.", "İngilizce çevirisini okudum."],
  ["review", "n", "eleştiri yazısı, inceleme", "The film got good reviews.", "Film iyi eleştiriler aldı."],
  ["edition", "n", "baskı", "This is the first edition of the book.", "Bu kitabın ilk baskısı."],
  ["e-book", "n", "e-kitap", "I read e-books on my tablet.", "E-kitapları tabletimde okurum."],
  ["literature", "n", "edebiyat", "She studied English literature.", "İngiliz edebiyatı okudu."],
  ["summary", "n", "özet", "Write a short summary of the story.", "Hikayenin kısa bir özetini yaz."],
  ["gripping", "adj", "sürükleyici", "It's a gripping thriller.", "Sürükleyici bir gerilim romanı."],
];
