import type { LexiconEntry } from "../types";

/** B1 sets 16–20: journeys, housing, climate, the natural world, disasters. */
export const B1_PART4: LexiconEntry[] = [
  // Set 16 — Journeys & driving
  ["commute", "v", "işe gidip gelmek", "I commute to Istanbul every day.", "Her gün İstanbul'a gidip geliyorum."],
  ["commuter", "n", "işe gidip gelen kişi", "The trains are full of commuters.", "Trenler işe gidip gelenlerle dolu."],
  ["rush hour", "n", "trafiğin yoğun olduğu saat", "Avoid driving in rush hour.", "Yoğun saatte araba kullanmaktan kaçın."],
  ["traffic jam", "n", "trafik sıkışıklığı", "We were stuck in a traffic jam for an hour.", "Bir saat trafikte sıkıştık."],
  ["motorway", "n", "otoyol", "Take the motorway to Ankara.", "Ankara'ya otoyoldan git.", "Amerikan İngilizcesinde “highway”."],
  ["speed limit", "n", "hız sınırı", "The speed limit here is 50.", "Burada hız sınırı 50."],
  ["fine", "n", "para cezası", "He got a fine for speeding.", "Hız yaptığı için para cezası yedi."],
  ["driving licence", "n", "ehliyet", "I got my driving licence at 18.", "Ehliyetimi 18 yaşında aldım."],
  ["overtake", "v", "sollamak", "Don't overtake on a bend.", "Virajda sollama yapma."],
  ["reverse", "v", "geri gitmek (araç)", "Reverse into the parking space.", "Park yerine geri geri gir."],
  ["breakdown", "n", "arıza", "We had a breakdown on the way.", "Yolda arabamız arıza yaptı."],
  ["flat tyre", "n", "patlak lastik", "I had a flat tyre on the motorway.", "Otoyolda lastiğim patladı."],
  ["vehicle", "n", "araç", "No vehicles are allowed in the centre.", "Merkeze araç girişine izin verilmiyor."],
  ["detour", "n", "sapma, dolambaçlı yol", "We made a detour to avoid the traffic.", "Trafikten kaçınmak için yolumuzu değiştirdik."],
  ["departure lounge", "n", "giden yolcu salonu", "We waited in the departure lounge for an hour.", "Giden yolcu salonunda bir saat bekledik."],
  ["connection", "n", "aktarma", "I missed my connection in Frankfurt.", "Frankfurt'taki aktarmamı kaçırdım."],
  ["one-way", "adj", "tek yönlü", "This is a one-way street.", "Bu tek yönlü bir sokak."],
  ["cycle lane", "n", "bisiklet yolu", "The city built new cycle lanes.", "Şehir yeni bisiklet yolları yaptı."],
  ["carpool", "v", "arabayı paylaşmak", "We carpool to save money.", "Para biriktirmek için arabayı paylaşıyoruz."],
  ["accident-prone", "adj", "kazaya yatkın", "This junction is accident-prone.", "Bu kavşakta sık kaza olur."],

  // Set 17 — Housing & city life
  ["urban", "adj", "kentsel", "Urban areas are growing fast.", "Kentsel alanlar hızla büyüyor."],
  ["rural", "adj", "kırsal", "They moved to a rural area.", "Kırsal bir bölgeye taşındılar."],
  ["resident", "n", "sakin (oturan)", "Local residents complained about the noise.", "Yerel sakinler gürültüden şikâyet etti."],
  ["housing", "n", "konut", "There's a shortage of cheap housing.", "Ucuz konut sıkıntısı var."],
  ["property", "n", "mülk, gayrimenkul", "Property prices are rising.", "Gayrimenkul fiyatları artıyor."],
  ["tenant", "n", "kiracı", "The tenants pay rent every month.", "Kiracılar her ay kira öder."],
  ["estate agent", "n", "emlakçı", "The estate agent showed us three flats.", "Emlakçı bize üç daire gösterdi."],
  ["furnished", "adj", "eşyalı", "We're looking for a furnished flat.", "Eşyalı bir daire arıyoruz."],
  ["spacious", "adj", "ferah, geniş", "The living room is bright and spacious.", "Oturma odası aydınlık ve ferah."],
  ["cramped", "adj", "dar, sıkışık", "Our first flat was very cramped.", "İlk dairemiz çok dardı."],
  ["skyscraper", "n", "gökdelen", "New York is full of skyscrapers.", "New York gökdelenlerle dolu."],
  ["block of flats", "n", "apartman", "We live in a block of flats.", "Bir apartmanda yaşıyoruz."],
  ["district", "n", "ilçe, semt", "Kadıköy is a lively district.", "Kadıköy canlı bir semt."],
  ["utilities", "n", "faturalar (elektrik, su, gaz)", "The rent doesn't include utilities.", "Kiraya faturalar dahil değil."],
  ["lively", "adj", "canlı, hareketli", "The city centre is lively at night.", "Şehir merkezi geceleri hareketli."],
  ["pedestrian zone", "n", "yaya bölgesi", "İstiklal Avenue is a pedestrian zone.", "İstiklal Caddesi bir yaya bölgesi."],
  ["homeless", "adj", "evsiz", "The charity helps homeless people.", "Yardım kuruluşu evsizlere yardım ediyor."],
  ["overcrowded", "adj", "aşırı kalabalık", "The city centre is overcrowded in summer.", "Şehir merkezi yazın aşırı kalabalık."],
  ["move house", "phr", "taşınmak", "We're moving house next month.", "Gelecek ay taşınıyoruz."],
  ["renovate", "v", "yenilemek, tadilat yapmak", "They renovated the old building.", "Eski binayı yenilediler."],

  // Set 18 — Climate
  ["climate change", "n", "iklim değişikliği", "Climate change affects everyone.", "İklim değişikliği herkesi etkiliyor."],
  ["greenhouse gas", "n", "sera gazı", "Cars produce greenhouse gases.", "Arabalar sera gazı üretir."],
  ["carbon footprint", "n", "karbon ayak izi", "Flying increases your carbon footprint.", "Uçmak karbon ayak izini artırır."],
  ["emission", "n", "salım, emisyon", "We need to reduce carbon emissions.", "Karbon salımını azaltmamız gerekiyor."],
  ["fossil fuel", "n", "fosil yakıt", "Coal is a fossil fuel.", "Kömür bir fosil yakıttır."],
  ["renewable", "adj", "yenilenebilir", "Wind power is a renewable energy source.", "Rüzgar enerjisi yenilenebilir bir kaynaktır."],
  ["sustainable", "adj", "sürdürülebilir", "We need sustainable farming.", "Sürdürülebilir tarıma ihtiyacımız var."],
  ["environmentally friendly", "adj", "çevre dostu", "This car is environmentally friendly.", "Bu araba çevre dostu."],
  ["endangered", "adj", "nesli tükenmekte olan", "The panda is an endangered species.", "Panda nesli tükenmekte olan bir türdür."],
  ["extinct", "adj", "nesli tükenmiş", "Dinosaurs are extinct.", "Dinozorların nesli tükenmiştir."],
  ["species", "n", "tür", "There are thousands of species of insects.", "Binlerce böcek türü var.", "Tekili ve çoğulu aynıdır."],
  ["habitat", "n", "yaşam alanı", "Forests are the natural habitat of bears.", "Ormanlar ayıların doğal yaşam alanıdır."],
  ["deforestation", "n", "ormansızlaşma", "Deforestation destroys habitats.", "Ormansızlaşma yaşam alanlarını yok eder."],
  ["conservation", "n", "koruma", "The group works on wildlife conservation.", "Grup yaban hayatı koruma üzerine çalışıyor."],
  ["pollute", "v", "kirletmek", "Factories pollute the river.", "Fabrikalar nehri kirletiyor."],
  ["toxic", "adj", "zehirli", "The factory released toxic waste.", "Fabrika zehirli atık bıraktı."],
  ["ozone layer", "n", "ozon tabakası", "The ozone layer protects us from the sun.", "Ozon tabakası bizi güneşten korur."],
  ["melt", "v", "erimek", "The ice at the poles is melting.", "Kutuplardaki buzlar eriyor."],
  ["sea level", "n", "deniz seviyesi", "Sea levels are rising.", "Deniz seviyesi yükseliyor."],
  ["recycling", "n", "geri dönüşüm", "Recycling bins are on every street.", "Her sokakta geri dönüşüm kutuları var."],

  // Set 19 — The natural world
  ["wildlife", "n", "yaban hayatı", "The park is full of wildlife.", "Park yaban hayatıyla dolu."],
  ["creature", "n", "yaratık, canlı", "The octopus is a strange creature.", "Ahtapot tuhaf bir canlıdır."],
  ["mammal", "n", "memeli", "Whales are mammals, not fish.", "Balinalar balık değil memelidir."],
  ["reptile", "n", "sürüngen", "Snakes and lizards are reptiles.", "Yılanlar ve kertenkeleler sürüngendir."],
  ["predator", "n", "yırtıcı hayvan", "Lions are powerful predators.", "Aslanlar güçlü yırtıcılardır."],
  ["prey", "n", "av", "The eagle caught its prey.", "Kartal avını yakaladı."],
  ["hunt", "v", "avlamak", "Wolves hunt in groups.", "Kurtlar grup hâlinde avlanır."],
  ["nest", "n", "yuva (kuş)", "There's a bird's nest in the tree.", "Ağaçta bir kuş yuvası var."],
  ["flock", "n", "sürü (kuş, koyun)", "A flock of birds flew over us.", "Bir kuş sürüsü üzerimizden uçtu."],
  ["herd", "n", "sürü (büyükbaş)", "A herd of cows blocked the road.", "Bir inek sürüsü yolu kapattı."],
  ["fur", "n", "kürk, tüy", "The cat has soft fur.", "Kedinin yumuşak tüyleri var."],
  ["feather", "n", "tüy (kuş)", "Peacocks have beautiful feathers.", "Tavus kuşlarının güzel tüyleri vardır."],
  ["claw", "n", "pençe", "Bears have sharp claws.", "Ayıların keskin pençeleri vardır."],
  ["hibernate", "v", "kış uykusuna yatmak", "Bears hibernate in winter.", "Ayılar kışın kış uykusuna yatar."],
  ["migrate", "v", "göç etmek", "Storks migrate south in autumn.", "Leylekler sonbaharda güneye göç eder."],
  ["root", "n", "kök", "The tree has deep roots.", "Ağacın derin kökleri var."],
  ["branch", "n", "dal; şube", "A bird sat on the branch.", "Bir kuş dala kondu."],
  ["leaf", "n", "yaprak", "The leaves turn red in autumn.", "Yapraklar sonbaharda kızarır.", "Çoğulu: leaves."],
  ["seed", "n", "tohum", "Plant the seeds in spring.", "Tohumları ilkbaharda ek."],
  ["bloom", "v", "çiçek açmak", "The cherry trees bloom in April.", "Kiraz ağaçları nisanda çiçek açar."],

  // Set 20 — Natural disasters
  ["disaster", "n", "felaket", "The earthquake was a terrible disaster.", "Deprem korkunç bir felaketti."],
  ["earthquake", "n", "deprem", "Turkey has many earthquakes.", "Türkiye'de çok deprem olur."],
  ["hurricane", "n", "kasırga", "The hurricane destroyed hundreds of homes.", "Kasırga yüzlerce evi yıktı."],
  ["tornado", "n", "hortum", "A tornado hit the town.", "Kasabayı bir hortum vurdu."],
  ["volcano", "n", "yanardağ", "Mount Etna is an active volcano.", "Etna Dağı aktif bir yanardağdır."],
  ["erupt", "v", "püskürmek", "The volcano erupted last year.", "Yanardağ geçen yıl püskürdü."],
  ["tsunami", "n", "tsunami", "The earthquake caused a tsunami.", "Deprem bir tsunamiye yol açtı."],
  ["wildfire", "n", "orman yangını", "Wildfires spread quickly in dry weather.", "Kuru havada orman yangınları hızla yayılır."],
  ["landslide", "n", "heyelan", "Heavy rain caused a landslide.", "Şiddetli yağmur heyelana neden oldu."],
  ["avalanche", "n", "çığ", "The skiers were caught in an avalanche.", "Kayakçılar çığa yakalandı."],
  ["heatwave", "n", "sıcak hava dalgası", "Europe is suffering a heatwave.", "Avrupa bir sıcak hava dalgası yaşıyor."],
  ["victim", "n", "kurban, mağdur", "Help was sent to the flood victims.", "Sel mağdurlarına yardım gönderildi."],
  ["survivor", "n", "hayatta kalan", "Rescuers found three survivors.", "Kurtarma ekipleri üç kazazede buldu."],
  ["survive", "v", "hayatta kalmak", "Nobody knows how he survived.", "Nasıl hayatta kaldığını kimse bilmiyor."],
  ["damage", "n", "hasar", "The storm caused a lot of damage.", "Fırtına çok hasara yol açtı.", "Sayılamaz."],
  ["destroy", "v", "yok etmek, yıkmak", "The fire destroyed the forest.", "Yangın ormanı yok etti."],
  ["evacuate", "v", "tahliye etmek", "The village was evacuated.", "Köy tahliye edildi."],
  ["shelter", "n", "barınak, sığınak", "Families found shelter in schools.", "Aileler okullarda barınak buldu."],
  ["aid", "n", "yardım", "Countries sent aid to the region.", "Ülkeler bölgeye yardım gönderdi."],
  ["alert", "n", "alarm, uyarı (resmi)", "The city is on high alert for floods.", "Şehir sel için yüksek alarm durumunda."],
];
