import type { LexiconEntry } from "../types";

/** B1 sets 26–30: film & music, competition, crime & justice, society, public services. */
export const B1_PART6: LexiconEntry[] = [
  // Set 26 — Film & music
  ["director", "n", "yönetmen", "Nuri Bilge Ceylan is a famous director.", "Nuri Bilge Ceylan ünlü bir yönetmendir."],
  ["cast", "n", "oyuncu kadrosu", "The film has a great cast.", "Filmin harika bir oyuncu kadrosu var."],
  ["scene", "n", "sahne", "The last scene made me cry.", "Son sahne beni ağlattı."],
  ["script", "n", "senaryo", "He wrote the script in six months.", "Senaryoyu altı ayda yazdı."],
  ["soundtrack", "n", "film müziği", "The soundtrack is amazing.", "Film müziği harika."],
  ["special effects", "n", "özel efektler", "The special effects look very real.", "Özel efektler çok gerçekçi görünüyor."],
  ["thriller", "n", "gerilim filmi/romanı", "I watched a thriller last night.", "Dün gece bir gerilim filmi izledim."],
  ["science fiction", "n", "bilim kurgu", "He loves science fiction films.", "Bilim kurgu filmlerine bayılır."],
  ["animation", "n", "animasyon", "The animation is beautiful.", "Animasyon çok güzel."],
  ["premiere", "n", "gala, ilk gösterim", "The stars came to the premiere.", "Yıldızlar galaya geldi."],
  ["box office", "n", "gişe", "The film was a box office hit.", "Film gişede büyük başarı kazandı."],
  ["sequel", "n", "devam filmi", "The sequel is better than the first film.", "Devam filmi ilkinden daha iyi."],
  ["genre", "n", "tür (sanat)", "What's your favourite film genre?", "En sevdiğin film türü ne?"],
  ["hit", "n", "hit, başarılı eser", "The song was a huge hit.", "Şarkı büyük bir hit oldu."],
  ["chart", "n", "liste (müzik)", "The song is number one in the charts.", "Şarkı listelerde bir numara."],
  ["release", "v", "yayınlamak, çıkarmak", "The band released a new album.", "Grup yeni bir albüm çıkardı."],
  ["live", "adj", "canlı", "I love live music.", "Canlı müziği severim."],
  ["gig", "n", "konser (küçük)", "We went to a gig in a small club.", "Küçük bir kulüpte konsere gittik."],
  ["record", "v", "kaydetmek", "They recorded the album in two weeks.", "Albümü iki haftada kaydettiler."],
  ["composer", "n", "besteci", "Mozart was a great composer.", "Mozart büyük bir besteciydi."],

  // Set 27 — Competition
  ["tournament", "n", "turnuva", "Our team won the tournament.", "Takımımız turnuvayı kazandı."],
  ["league", "n", "lig", "They're top of the league.", "Liginde birinciler."],
  ["final", "n", "final", "The final is on Sunday.", "Final pazar günü."],
  ["opponent", "n", "rakip", "She beat her opponent easily.", "Rakibini kolayca yendi."],
  ["athlete", "n", "sporcu, atlet", "Athletes train for years.", "Sporcular yıllarca antrenman yapar."],
  ["medal", "n", "madalya", "He won a gold medal at the Olympics.", "Olimpiyatlarda altın madalya kazandı."],
  ["trophy", "n", "kupa", "The captain lifted the trophy.", "Kaptan kupayı kaldırdı."],
  ["record", "n", "rekor", "She broke the world record.", "Dünya rekorunu kırdı."],
  ["draw", "n", "beraberlik", "The match ended in a draw.", "Maç berabere bitti."],
  ["victory", "n", "zafer", "It was a great victory for the team.", "Takım için büyük bir zaferdi."],
  ["defeat", "n", "yenilgi", "They suffered a heavy defeat.", "Ağır bir yenilgi aldılar."],
  ["captain", "n", "kaptan", "He's the captain of the team.", "Takımın kaptanı."],
  ["fitness", "n", "kondisyon", "Swimming improves your fitness.", "Yüzmek kondisyonunu artırır."],
  ["spectator", "n", "seyirci", "Thousands of spectators watched the race.", "Binlerce seyirci yarışı izledi."],
  ["cheer", "v", "tezahürat yapmak", "The fans cheered loudly.", "Taraftarlar yüksek sesle tezahürat yaptı."],
  ["penalty", "n", "penaltı; ceza", "He scored from the penalty.", "Penaltıdan gol attı."],
  ["foul", "n", "faul", "The referee didn't see the foul.", "Hakem faulü görmedi."],
  ["compete", "v", "yarışmak", "Twenty countries will compete.", "Yirmi ülke yarışacak."],
  ["qualify", "v", "elemeyi geçmek, hak kazanmak", "Turkey qualified for the World Cup.", "Türkiye Dünya Kupası'na katılmaya hak kazandı."],
  ["amateur", "adj", "amatör", "He plays in an amateur football team.", "Amatör bir futbol takımında oynuyor."],

  // Set 28 — Crime & justice
  ["commit", "v", "işlemek (suç)", "He committed a serious crime.", "Ciddi bir suç işledi."],
  ["burglar", "n", "(ev) hırsız", "A burglar broke into our house.", "Evimize bir hırsız girdi."],
  ["burglary", "n", "hırsızlık (ev)", "Burglaries have increased this year.", "Bu yıl ev hırsızlıkları arttı."],
  ["shoplifting", "n", "mağazadan hırsızlık", "He was arrested for shoplifting.", "Mağazadan hırsızlık yaptığı için tutuklandı."],
  ["fraud", "n", "dolandırıcılık", "She was jailed for fraud.", "Dolandırıcılıktan hapse girdi."],
  ["murder", "n", "cinayet", "The police are investigating the murder.", "Polis cinayeti soruşturuyor."],
  ["suspect", "n", "şüpheli", "The police questioned two suspects.", "Polis iki şüpheliyi sorguladı."],
  ["investigate", "v", "soruşturmak", "Detectives are investigating the case.", "Dedektifler davayı soruşturuyor."],
  ["detective", "n", "dedektif", "The detective solved the mystery.", "Dedektif gizemi çözdü."],
  ["court", "n", "mahkeme", "The case went to court.", "Dava mahkemeye taşındı."],
  ["trial", "n", "yargılama, dava", "The trial lasted three weeks.", "Yargılama üç hafta sürdü."],
  ["verdict", "n", "hüküm, karar (mahkeme)", "The jury reached a verdict of guilty.", "Jüri suçlu kararına vardı."],
  ["innocent", "adj", "masum", "She says she's innocent.", "Masum olduğunu söylüyor."],
  ["sentence", "n", "ceza, hüküm", "He got a five-year sentence.", "Beş yıl hapis cezası aldı."],
  ["punish", "v", "cezalandırmak", "Criminals should be punished.", "Suçlular cezalandırılmalı."],
  ["punishment", "n", "ceza", "The punishment was too harsh.", "Ceza çok ağırdı."],
  ["illegal", "adj", "yasa dışı", "It's illegal to drive without a licence.", "Ehliyetsiz araba kullanmak yasa dışıdır."],
  ["legal", "adj", "yasal", "Is it legal to park here?", "Buraya park etmek yasal mı?"],
  ["break the law", "phr", "yasayı çiğnemek", "You're breaking the law.", "Yasayı çiğniyorsun."],
  ["security camera", "n", "güvenlik kamerası", "A security camera filmed the thief.", "Güvenlik kamerası hırsızı kaydetti."],

  // Set 29 — Society
  ["society", "n", "toplum", "Technology has changed our society.", "Teknoloji toplumumuzu değiştirdi."],
  ["politics", "n", "siyaset", "I'm not interested in politics.", "Siyasetle ilgilenmiyorum."],
  ["political", "adj", "siyasi", "There are three main political parties.", "Üç ana siyasi parti var."],
  ["politician", "n", "siyasetçi", "Politicians often make promises.", "Siyasetçiler sık sık vaatlerde bulunur."],
  ["election", "n", "seçim", "The election is in May.", "Seçim mayısta."],
  ["vote", "v", "oy vermek", "Who did you vote for?", "Kime oy verdin?"],
  ["party", "n", "parti (siyasi)", "Which party won the election?", "Seçimi hangi parti kazandı?"],
  ["minister", "n", "bakan", "The education minister visited our school.", "Eğitim bakanı okulumuzu ziyaret etti."],
  ["mayor", "n", "belediye başkanı", "The mayor opened the new park.", "Belediye başkanı yeni parkı açtı."],
  ["rights", "n", "haklar", "Everyone has the right to education.", "Herkesin eğitim hakkı vardır."],
  ["equality", "n", "eşitlik", "They fight for gender equality.", "Cinsiyet eşitliği için mücadele ediyorlar."],
  ["poverty", "n", "yoksulluk", "Millions of people live in poverty.", "Milyonlarca insan yoksulluk içinde yaşıyor."],
  ["unemployment", "n", "işsizlik", "Unemployment is falling.", "İşsizlik azalıyor."],
  ["protest", "n", "protesto", "Thousands joined the protest.", "Binlerce kişi protestoya katıldı."],
  ["campaign", "n", "kampanya", "They started a campaign against smoking.", "Sigaraya karşı bir kampanya başlattılar."],
  ["immigrant", "n", "göçmen", "Many immigrants work in agriculture.", "Birçok göçmen tarımda çalışıyor."],
  ["refugee", "n", "mülteci", "Turkey hosts millions of refugees.", "Türkiye milyonlarca mülteciye ev sahipliği yapıyor."],
  ["minority", "n", "azınlık", "Only a minority of people agree.", "İnsanların yalnızca azınlığı katılıyor."],
  ["majority", "n", "çoğunluk", "The majority voted yes.", "Çoğunluk evet oyu verdi."],
  ["democracy", "n", "demokrasi", "Free elections are part of democracy.", "Özgür seçimler demokrasinin parçasıdır."],

  // Set 30 — Public services
  ["public services", "n", "kamu hizmetleri", "Taxes pay for public services.", "Vergiler kamu hizmetlerini finanse eder."],
  ["council", "n", "belediye meclisi, konsey", "The council collects the rubbish.", "Belediye çöpleri topluyor."],
  ["authority", "n", "yetkili makam, otorite", "The local authority built a new school.", "Yerel yönetim yeni bir okul yaptı."],
  ["official", "n", "görevli, yetkili", "A government official answered our questions.", "Bir hükümet yetkilisi sorularımızı yanıtladı."],
  ["application", "n", "başvuru", "Fill in the application form.", "Başvuru formunu doldur."],
  ["permit", "n", "izin belgesi", "You need a work permit.", "Çalışma iznine ihtiyacın var."],
  ["register", "v", "kaydolmak, kaydetmek", "You must register with a doctor.", "Bir doktora kayıt olmalısın."],
  ["certificate", "n", "sertifika, belge", "You'll get a certificate at the end.", "Sonunda bir sertifika alacaksın."],
  ["benefit", "n", "sosyal yardım; fayda", "He receives unemployment benefit.", "İşsizlik yardımı alıyor."],
  ["welfare", "n", "refah, sosyal yardım", "The government spends a lot on welfare.", "Hükümet sosyal yardıma çok para harcıyor."],
  ["healthcare", "n", "sağlık hizmetleri", "Healthcare is free for children.", "Çocuklar için sağlık hizmetleri ücretsiz."],
  ["emergency services", "n", "acil servisler", "The emergency services arrived quickly.", "Acil servisler hızla geldi."],
  ["fire brigade", "n", "itfaiye", "Call the fire brigade!", "İtfaiyeyi arayın!"],
  ["post", "n", "posta", "The post arrives at ten.", "Posta onda geliyor."],
  ["parcel", "n", "koli, paket", "I'm waiting for a parcel.", "Bir koli bekliyorum."],
  ["queue up", "pv", "sıraya girmek", "We queued up for an hour.", "Bir saat sırada bekledik."],
  ["bureaucracy", "n", "bürokrasi", "There's too much bureaucracy.", "Çok fazla bürokrasi var."],
  ["regulation", "n", "yönetmelik, düzenleme", "New safety regulations came into force.", "Yeni güvenlik yönetmelikleri yürürlüğe girdi."],
  ["tax return", "n", "vergi beyannamesi", "I filled in my tax return online.", "Vergi beyannamemi internetten doldurdum."],
  ["infrastructure", "n", "altyapı", "The city needs better infrastructure.", "Şehrin daha iyi bir altyapıya ihtiyacı var."],
];
