import type { LexiconEntry } from "../types";

/** B1 sets 11–15: consumers, nutrition, medicine, lifestyle, tourism. */
export const B1_PART3: LexiconEntry[] = [
  // Set 11 — Consumers
  ["consumer", "n", "tüketici", "Consumers want lower prices.", "Tüketiciler daha düşük fiyat istiyor."],
  ["purchase", "v", "satın almak (resmi)", "You can purchase tickets online.", "Biletleri internetten satın alabilirsiniz."],
  ["goods", "n", "mallar, ürünler", "The shop sells electrical goods.", "Dükkan elektrikli ürünler satıyor."],
  ["guarantee", "n", "garanti", "The TV has a two-year guarantee.", "Televizyonun iki yıl garantisi var."],
  ["faulty", "adj", "arızalı, kusurlu", "I returned the faulty kettle.", "Arızalı su ısıtıcısını iade ettim."],
  ["second-hand", "adj", "ikinci el", "I bought a second-hand bike.", "İkinci el bir bisiklet aldım."],
  ["catalogue", "n", "katalog", "Look through the catalogue.", "Kataloğa göz at."],
  ["online shopping", "n", "internetten alışveriş", "Online shopping saves time.", "İnternetten alışveriş zaman kazandırır."],
  ["delivery", "n", "teslimat", "Delivery is free for orders over 200 lira.", "200 lira üzeri siparişlerde teslimat ücretsiz."],
  ["order", "n", "sipariş", "Your order will arrive tomorrow.", "Siparişiniz yarın gelecek."],
  ["stock", "n", "stok", "Sorry, that size is out of stock.", "Üzgünüz, o beden stokta yok."],
  ["value for money", "phr", "fiyatına değer", "This meal is good value for money.", "Bu yemek fiyatına değer."],
  ["overpriced", "adj", "fahiş fiyatlı", "The drinks here are overpriced.", "Buradaki içecekler fahiş fiyatlı."],
  ["luxury", "n", "lüks", "They live in luxury.", "Lüks içinde yaşıyorlar."],
  ["essential", "adj", "temel, zorunlu", "Water is essential for life.", "Su yaşam için zorunludur."],
  ["impulse buy", "n", "anlık satın alma", "These shoes were an impulse buy.", "Bu ayakkabıları düşünmeden aldım."],
  ["loyalty card", "n", "sadakat kartı", "Do you have a loyalty card?", "Sadakat kartınız var mı?"],
  ["refundable", "adj", "iade edilebilir", "The ticket is not refundable.", "Bilet iade edilemez."],
  ["shopaholic", "n", "alışveriş bağımlısı", "My sister is a real shopaholic.", "Kız kardeşim tam bir alışveriş bağımlısı."],
  ["window-shopping", "n", "vitrin gezme", "We went window-shopping on Saturday.", "Cumartesi vitrin gezdik."],

  // Set 12 — Nutrition
  ["nutrition", "n", "beslenme", "Good nutrition is important for children.", "İyi beslenme çocuklar için önemlidir."],
  ["protein", "n", "protein", "Eggs are full of protein.", "Yumurta protein doludur."],
  ["vitamin", "n", "vitamin", "Oranges contain vitamin C.", "Portakal C vitamini içerir."],
  ["calorie", "n", "kalori", "This cake has a lot of calories.", "Bu kekte çok kalori var."],
  ["fat", "n", "yağ (besin)", "Fried food contains a lot of fat.", "Kızartmalarda çok yağ vardır."],
  ["balanced", "adj", "dengeli", "Try to eat a balanced diet.", "Dengeli beslenmeye çalış."],
  ["junk food", "n", "abur cubur", "Too much junk food is bad for you.", "Çok fazla abur cubur zararlıdır."],
  ["organic", "adj", "organik", "We buy organic vegetables.", "Organik sebze alıyoruz."],
  ["processed", "adj", "işlenmiş", "Avoid processed meat.", "İşlenmiş etten kaçın."],
  ["fibre", "n", "lif (besin)", "Brown bread is high in fibre.", "Esmer ekmek lif bakımından zengindir."],
  ["overeat", "v", "aşırı yemek", "People often overeat at weddings.", "İnsanlar düğünlerde sık sık aşırı yer."],
  ["appetite", "n", "iştah", "I've lost my appetite.", "İştahım kesildi."],
  ["starving", "adj", "çok aç", "I'm starving! When's dinner?", "Açlıktan ölüyorum! Yemek ne zaman?"],
  ["homemade", "adj", "ev yapımı", "Nothing beats homemade bread.", "Hiçbir şey ev yapımı ekmeğin yerini tutmaz."],
  ["flavour", "n", "tat, aroma", "What flavour ice cream do you want?", "Hangi aromalı dondurma istersin?"],
  ["recipe book", "n", "yemek kitabı", "I got a recipe book for my birthday.", "Doğum günümde bir yemek kitabı aldım."],
  ["vegan", "adj", "vegan", "This restaurant has vegan options.", "Bu restoranda vegan seçenekler var."],
  ["dairy", "adj", "süt ürünü", "I can't eat dairy products.", "Süt ürünleri yiyemiyorum."],
  ["grain", "n", "tahıl, tane", "Rice is a grain.", "Pirinç bir tahıldır."],
  ["seafood", "n", "deniz ürünleri", "The seafood in Izmir is excellent.", "İzmir'deki deniz ürünleri harika."],

  // Set 13 — Medicine
  ["treatment", "n", "tedavi", "The treatment lasts three weeks.", "Tedavi üç hafta sürüyor."],
  ["treat", "v", "tedavi etmek", "Doctors treated him for burns.", "Doktorlar onu yanıklar için tedavi etti."],
  ["cure", "n", "tedavi, çare", "There's no cure for the common cold.", "Soğuk algınlığının kesin bir çaresi yok."],
  ["surgery", "n", "ameliyat", "She needs surgery on her knee.", "Dizinden ameliyat olması gerekiyor."],
  ["operation", "n", "ameliyat; işlem", "The operation was a success.", "Ameliyat başarılı geçti."],
  ["specialist", "n", "uzman", "He was sent to a heart specialist.", "Bir kalp uzmanına gönderildi."],
  ["infection", "n", "enfeksiyon", "The cut got an infection.", "Kesik enfeksiyon kaptı."],
  ["virus", "n", "virüs", "Flu is caused by a virus.", "Gribe bir virüs neden olur."],
  ["vaccine", "n", "aşı", "Have you had the flu vaccine?", "Grip aşısı oldun mu?"],
  ["painkiller", "n", "ağrı kesici", "Take a painkiller for your headache.", "Baş ağrın için bir ağrı kesici al."],
  ["side effect", "n", "yan etki", "This medicine has no side effects.", "Bu ilacın yan etkisi yok."],
  ["blood pressure", "n", "tansiyon", "The nurse checked my blood pressure.", "Hemşire tansiyonumu ölçtü."],
  ["heart attack", "n", "kalp krizi", "He had a heart attack at 60.", "60 yaşında kalp krizi geçirdi."],
  ["wound", "n", "yara", "Clean the wound with water.", "Yarayı suyla temizle."],
  ["bandage", "n", "bandaj", "The nurse put a bandage on my arm.", "Hemşire koluma bandaj sardı."],
  ["X-ray", "n", "röntgen", "The X-ray showed a broken bone.", "Röntgen kırık bir kemik gösterdi."],
  ["pharmacist", "n", "eczacı", "Ask the pharmacist for advice.", "Eczacıdan tavsiye iste."],
  ["ward", "n", "koğuş, servis", "She's in the children's ward.", "Çocuk servisinde yatıyor."],
  ["heal", "v", "iyileşmek (yara)", "The cut healed quickly.", "Kesik çabuk iyileşti."],
  ["unconscious", "adj", "bilinçsiz, baygın", "He was unconscious for ten minutes.", "On dakika baygın kaldı."],

  // Set 14 — Lifestyle
  ["lifestyle", "n", "yaşam tarzı", "She has a healthy lifestyle.", "Sağlıklı bir yaşam tarzı var."],
  ["habit", "n", "alışkanlık", "Smoking is a bad habit.", "Sigara içmek kötü bir alışkanlıktır."],
  ["work-life balance", "n", "iş-özel hayat dengesi", "I want a better work-life balance.", "Daha iyi bir iş-özel hayat dengesi istiyorum."],
  ["workout", "n", "antrenman", "I do a 30-minute workout every morning.", "Her sabah 30 dakikalık antrenman yaparım."],
  ["active", "adj", "aktif, hareketli", "My grandmother is still very active.", "Büyükannem hâlâ çok hareketli."],
  ["couch potato", "n", "tembel, sürekli televizyon izleyen kişi", "Stop being a couch potato and go outside!", "Koltuktan kalk ve dışarı çık!"],
  ["quit", "v", "bırakmak (alışkanlık, iş)", "He quit smoking last year.", "Geçen yıl sigarayı bıraktı.", "quit – quit – quit"],
  ["cut down on", "pv", "azaltmak", "I'm trying to cut down on sugar.", "Şekeri azaltmaya çalışıyorum."],
  ["addicted", "adj", "bağımlı", "Many teenagers are addicted to their phones.", "Birçok genç telefonuna bağımlı."],
  ["balance", "n", "denge", "It's important to have a work-life balance.", "İş-yaşam dengesi önemlidir."],
  ["meditation", "n", "meditasyon", "Meditation helps me relax.", "Meditasyon rahatlamama yardım ediyor."],
  ["well-being", "n", "iyi olma hâli, esenlik", "Exercise improves your well-being.", "Egzersiz genel iyiliğini artırır."],
  ["sleep pattern", "n", "uyku düzeni", "Shift work affects your sleep pattern.", "Vardiyalı çalışma uyku düzenini bozar."],
  ["stressful", "adj", "stresli", "Moving house is very stressful.", "Taşınmak çok streslidir."],
  ["energetic", "adj", "enerjik", "I feel more energetic in the morning.", "Sabahları daha enerjik hissediyorum."],
  ["sedentary", "adj", "hareketsiz (yaşam)", "Office workers often have a sedentary lifestyle.", "Ofis çalışanları genelde hareketsiz bir yaşam sürer."],
  ["stretch", "v", "esnemek, gerinmek", "Always stretch before running.", "Koşmadan önce mutlaka esneme yap."],
  ["get into", "pv", "(bir şeye) merak salmak", "I got into running during the lockdown.", "Karantina döneminde koşuya merak saldım."],
  ["keep fit", "phr", "formda kalmak", "Walking is an easy way to keep fit.", "Yürümek formda kalmanın kolay bir yolu."],
  ["put on weight", "phr", "kilo almak", "I put on weight over the holidays.", "Tatilde kilo aldım."],

  // Set 15 — Tourism
  ["tourism", "n", "turizm", "Tourism brings money to the region.", "Turizm bölgeye para getiriyor."],
  ["attraction", "n", "turistik yer, cazibe", "The Blue Mosque is a major attraction.", "Sultanahmet Camii önemli bir turistik yerdir."],
  ["landmark", "n", "simge yapı", "The Galata Tower is a famous landmark.", "Galata Kulesi ünlü bir simge yapıdır."],
  ["itinerary", "n", "gezi programı", "Our itinerary includes three cities.", "Gezi programımız üç şehri kapsıyor."],
  ["package holiday", "n", "paket tur", "A package holiday includes flights and hotel.", "Paket tur uçuş ve oteli kapsar."],
  ["backpacker", "n", "sırt çantalı gezgin", "The hostel is full of backpackers.", "Hostel sırt çantalı gezginlerle dolu."],
  ["excursion", "n", "gezi, tur", "We went on an excursion to Ephesus.", "Efes'e bir geziye gittik."],
  ["guided tour", "n", "rehberli tur", "We took a guided tour of Topkapı Palace.", "Topkapı Sarayı'nda rehberli bir tura katıldık."],
  ["breathtaking", "adj", "nefes kesici", "The view from the top was breathtaking.", "Zirveden manzara nefes kesiciydi."],
  ["picturesque", "adj", "resim gibi, pitoresk", "Şirince is a picturesque village.", "Şirince resim gibi bir köy."],
  ["touristy", "adj", "turistik (olumsuz)", "This area is too touristy for me.", "Bu bölge bana göre fazla turistik."],
  ["off the beaten track", "phr", "turistlerin bilmediği", "We found a beach off the beaten track.", "Turistlerin bilmediği bir plaj bulduk."],
  ["high season", "n", "yüksek sezon", "Prices double in high season.", "Yüksek sezonda fiyatlar iki katına çıkar."],
  ["visa", "n", "vize", "Do I need a visa for Canada?", "Kanada için vize gerekiyor mu?"],
  ["currency exchange", "n", "döviz bürosu", "There's a currency exchange at the airport.", "Havalimanında döviz bürosu var."],
  ["travel agent", "n", "seyahat acentesi", "The travel agent booked our flights.", "Seyahat acentesi uçuşlarımızı ayırttı."],
  ["explore", "v", "keşfetmek", "We spent the day exploring the old town.", "Günü eski şehri keşfederek geçirdik."],
  ["overseas", "adv", "denizaşırı, yurt dışında", "Many students go overseas to study.", "Birçok öğrenci okumak için yurt dışına gider."],
  ["self-catering", "adj", "mutfaklı (kendi yemeğini yaptığın)", "We stayed in a self-catering apartment.", "Mutfaklı bir apart dairede kaldık."],
  ["local cuisine", "n", "yöresel mutfak", "Try the local cuisine in Gaziantep.", "Gaziantep'te yöresel mutfağı dene."],
];
