import type { LexiconEntry } from "../types";

/** B1 sets 56–60: time & frequency, social life, devices, cooking, conversation phrases. */
export const B1_PART12: LexiconEntry[] = [
  // Set 56 — Time & frequency
  ["occasionally", "adv", "ara sıra", "I occasionally go to the cinema.", "Ara sıra sinemaya giderim."],
  ["rarely", "adv", "nadiren", "We rarely eat out.", "Nadiren dışarıda yemek yeriz."],
  ["regularly", "adv", "düzenli olarak", "You should exercise regularly.", "Düzenli olarak spor yapmalısın."],
  ["constantly", "adv", "sürekli", "He's constantly checking his phone.", "Sürekli telefonunu kontrol ediyor."],
  ["frequently", "adv", "sık sık", "This word is used frequently.", "Bu kelime sık sık kullanılır."],
  ["from time to time", "phr", "zaman zaman", "From time to time, I visit my old school.", "Zaman zaman eski okulumu ziyaret ederim."],
  ["every now and then", "phr", "arada bir", "Every now and then we have a barbecue.", "Arada bir mangal yaparız."],
  ["in the meantime", "phr", "bu arada, o zamana kadar", "The doctor is coming. In the meantime, sit down.", "Doktor geliyor. O zamana kadar otur."],
  ["for the time being", "phr", "şimdilik", "I'm living with my parents for the time being.", "Şimdilik ailemle yaşıyorum."],
  ["in advance", "phr", "önceden", "Book your tickets in advance.", "Biletlerini önceden al."],
  ["sooner or later", "phr", "er ya da geç", "Sooner or later, you'll have to decide.", "Er ya da geç karar vermek zorunda kalacaksın."],
  ["at the latest", "phr", "en geç", "Send it by Friday at the latest.", "En geç cumaya kadar gönder."],
  ["so far", "phr", "şimdiye kadar", "So far, everything is going well.", "Şimdiye kadar her şey yolunda gidiyor."],
  ["up to now", "phr", "şu ana kadar", "Up to now, nobody has complained.", "Şu ana kadar kimse şikâyet etmedi."],
  ["these days", "phr", "bugünlerde", "Everyone works from home these days.", "Bugünlerde herkes evden çalışıyor."],
  ["in the past", "phr", "geçmişte", "In the past, people wrote letters.", "Geçmişte insanlar mektup yazardı."],
  ["the other day", "phr", "geçen gün", "I saw your brother the other day.", "Geçen gün kardeşini gördüm."],
  ["temporarily", "adv", "geçici olarak", "The museum is temporarily closed.", "Müze geçici olarak kapalı."],
  ["immediate", "adj", "anında, acil", "We need an immediate answer.", "Anında bir cevaba ihtiyacımız var."],
  ["lifetime", "n", "ömür", "It was the trip of a lifetime.", "Ömürde bir kez yapılacak bir geziydi."],

  // Set 57 — Social life
  ["acquaintance", "n", "tanıdık", "He's not a friend, just an acquaintance.", "Arkadaşım değil, sadece bir tanıdık."],
  ["close friend", "n", "yakın arkadaş", "She's been my close friend since school.", "Okuldan beri yakın arkadaşım."],
  ["get-together", "n", "buluşma, toplantı (samimi)", "We're having a small get-together on Saturday.", "Cumartesi küçük bir buluşma yapıyoruz."],
  ["gathering", "n", "toplantı, bir araya gelme", "It was a family gathering for the holiday.", "Bayram için bir aile toplantısıydı."],
  ["socialise", "v", "sosyalleşmek", "I don't have much time to socialise.", "Sosyalleşmek için pek vaktim yok."],
  ["keep in touch", "phr", "iletişimi sürdürmek", "Let's keep in touch after the course.", "Kurstan sonra iletişimde kalalım."],
  ["lose touch", "phr", "bağlantıyı kaybetmek", "We lost touch after university.", "Üniversiteden sonra bağlantımız koptu."],
  ["relationship status", "n", "ilişki durumu", "She changed her relationship status online.", "İnternette ilişki durumunu değiştirdi."],
  ["flatmate", "n", "ev arkadaşı", "My flatmate is from Konya.", "Ev arkadaşım Konyalı."],
  ["host", "v", "ev sahipliği yapmak", "We're hosting a dinner for our neighbours.", "Komşularımız için bir yemeğe ev sahipliği yapıyoruz."],
  ["accept an invitation", "phr", "daveti kabul etmek", "I'm happy to accept your invitation.", "Davetinizi memnuniyetle kabul ediyorum."],
  ["show up", "pv", "gelmek, ortaya çıkmak", "Only five people showed up to the party.", "Partiye sadece beş kişi geldi."],
  ["get to know", "phr", "tanımak (zamanla)", "It takes time to get to know people.", "İnsanları tanımak zaman alır."],
  ["have a lot in common", "phr", "birçok ortak noktası olmak", "We have a lot in common.", "Birçok ortak noktamız var."],
  ["introvert", "n", "içe dönük kişi", "As an introvert, I prefer small groups.", "İçe dönük biri olarak küçük grupları tercih ederim."],
  ["reunion", "n", "yeniden bir araya gelme, buluşma", "We had a class reunion after ten years.", "On yıl sonra sınıf buluşması yaptık."],
  ["peer pressure", "n", "akran baskısı", "Teenagers often feel peer pressure.", "Gençler sık sık akran baskısı hisseder."],
  ["romantic", "adj", "romantik", "They had a romantic dinner by the sea.", "Deniz kenarında romantik bir akşam yemeği yediler."],
  ["break someone's heart", "phr", "birinin kalbini kırmak", "She broke his heart when she left.", "Gittiğinde onun kalbini kırdı."],
  ["mutual", "adj", "karşılıklı, ortak", "We met through a mutual friend.", "Ortak bir arkadaş aracılığıyla tanıştık."],

  // Set 58 — Devices & technology
  ["gadget", "n", "alet, cihaz (küçük)", "He loves the latest gadgets.", "En yeni aletlere bayılır."],
  ["touchscreen", "n", "dokunmatik ekran", "The touchscreen isn't working.", "Dokunmatik ekran çalışmıyor."],
  ["headphones", "n", "kulaklık", "Put your headphones on — it's a quiet carriage.", "Kulaklığını tak, burası sessiz vagon."],
  ["speaker", "n", "hoparlör; konuşmacı", "Connect your phone to the speaker.", "Telefonunu hoparlöre bağla."],
  ["wireless", "adj", "kablosuz", "I bought a wireless mouse.", "Kablosuz bir fare aldım."],
  ["plug in", "pv", "prize takmak", "Plug in the charger, please.", "Şarj aletini prize tak lütfen."],
  ["switch off", "pv", "kapatmak", "Switch off your phones during the exam.", "Sınav sırasında telefonlarınızı kapatın."],
  ["restart", "v", "yeniden başlatmak", "Try restarting your computer.", "Bilgisayarını yeniden başlatmayı dene."],
  ["crash", "n", "çökme (sistem)", "I lost my work in a computer crash.", "Bilgisayar çökünce çalışmamı kaybettim."],
  ["update", "v", "güncellemek", "Update your apps regularly.", "Uygulamalarını düzenli olarak güncelle."],
  ["settings", "n", "ayarlar", "Change the language in the settings.", "Dili ayarlardan değiştir."],
  ["storage space", "n", "depolama alanı (cihaz)", "My phone has no storage space left.", "Telefonumda depolama alanı kalmadı."],
  ["screenshot", "n", "ekran görüntüsü", "Send me a screenshot of the error.", "Hatanın ekran görüntüsünü bana gönder."],
  ["notification", "n", "bildirim", "Turn off notifications while you study.", "Ders çalışırken bildirimleri kapat."],
  ["user-friendly", "adj", "kullanıcı dostu", "The website is very user-friendly.", "Web sitesi çok kullanıcı dostu."],
  ["cable", "n", "kablo", "I need a longer cable.", "Daha uzun bir kabloya ihtiyacım var."],
  ["smartwatch", "n", "akıllı saat", "My smartwatch counts my steps.", "Akıllı saatim adımlarımı sayıyor."],
  ["virtual", "adj", "sanal", "We had a virtual meeting on Zoom.", "Zoom'da sanal bir toplantı yaptık."],
  ["cloud storage", "n", "bulut depolama", "I keep my photos in cloud storage.", "Fotoğraflarımı bulutta saklıyorum."],
  ["out of order", "phr", "bozuk, hizmet dışı", "The lift is out of order.", "Asansör bozuk."],

  // Set 59 — Cooking
  ["stir", "v", "karıştırmak", "Stir the soup every few minutes.", "Çorbayı birkaç dakikada bir karıştır."],
  ["grate", "v", "rendelemek", "Grate some cheese on top.", "Üstüne biraz peynir rendele."],
  ["slice", "v", "dilimlemek", "Slice the tomatoes thinly.", "Domatesleri ince dilimle."],
  ["whisk", "v", "çırpmak", "Whisk the eggs and sugar together.", "Yumurtaları ve şekeri birlikte çırp."],
  ["steam", "v", "buharda pişirmek", "Steam the vegetables for five minutes.", "Sebzeleri beş dakika buharda pişir."],
  ["marinate", "v", "marine etmek, terbiye etmek", "Marinate the chicken in yoghurt overnight.", "Tavuğu bir gece yoğurtta marine et."],
  ["simmer", "v", "kısık ateşte pişirmek", "Let the sauce simmer for twenty minutes.", "Sosu yirmi dakika kısık ateşte pişir."],
  ["season", "v", "tuz-baharat eklemek", "Season the meat with salt and pepper.", "Eti tuz ve karabiberle tatlandır."],
  ["frying pan", "n", "tava", "Heat some oil in a frying pan.", "Bir tavada biraz yağ ısıt."],
  ["saucepan", "n", "tencere (saplı)", "Boil the pasta in a large saucepan.", "Makarnayı büyük bir tencerede haşla."],
  ["oven tray", "n", "fırın tepsisi", "Put the potatoes on an oven tray.", "Patatesleri fırın tepsisine koy."],
  ["chopping board", "n", "kesme tahtası", "Cut the onions on a chopping board.", "Soğanları kesme tahtasında doğra."],
  ["homemade jam", "n", "ev yapımı reçel", "My grandmother makes homemade jam.", "Büyükannem ev yapımı reçel yapar."],
  ["herbs", "n", "otlar (baharat)", "Add some fresh herbs like mint and parsley.", "Nane ve maydanoz gibi taze otlar ekle."],
  ["spices", "n", "baharatlar", "Turkish food uses a lot of spices.", "Türk yemeklerinde çok baharat kullanılır."],
  ["overcooked", "adj", "fazla pişmiş", "The rice was overcooked.", "Pilav fazla pişmişti."],
  ["crispy", "adj", "çıtır", "I like my chips crispy.", "Patates kızartmamı çıtır severim."],
  ["tender", "adj", "yumuşak (et)", "The lamb was very tender.", "Kuzu eti çok yumuşaktı."],
  ["leftovers", "n", "yemek artıkları, artan yemek", "We had the leftovers for lunch.", "Artan yemeği öğle yemeğinde yedik."],
  ["heat up", "pv", "ısıtmak", "Heat up the soup in the microwave.", "Çorbayı mikrodalgada ısıt."],

  // Set 60 — Conversation phrases
  ["I see what you mean", "phr", "ne demek istediğini anlıyorum", "I see what you mean, but I don't agree.", "Ne demek istediğini anlıyorum ama katılmıyorum."],
  ["that reminds me", "phr", "aklıma gelmişken", "That reminds me — I need to call my mum.", "Aklıma gelmişken, annemi aramam lazım."],
  ["come to think of it", "phr", "şimdi düşünüyorum da", "Come to think of it, he did look worried.", "Şimdi düşünüyorum da, gerçekten endişeli görünüyordu."],
  ["as I was saying", "phr", "diyordum ki", "As I was saying, the trip starts at eight.", "Diyordum ki, gezi sekizde başlıyor."],
  ["what I mean is", "phr", "demek istediğim şu", "What I mean is, we need more time.", "Demek istediğim şu, daha fazla zamana ihtiyacımız var."],
  ["you know what", "phr", "biliyor musun", "You know what? Let's go to the beach.", "Biliyor musun? Hadi plaja gidelim."],
  ["fair enough", "phr", "haklısın, makul", "Fair enough — let's do it your way.", "Haklısın, senin dediğin gibi yapalım."],
  ["it depends", "phr", "duruma göre değişir", "Will you come? — It depends on the weather.", "Gelecek misin? — Havaya bağlı."],
  ["I couldn't agree more", "phr", "kesinlikle katılıyorum", "I couldn't agree more with you.", "Sana kesinlikle katılıyorum."],
  ["I'm not so sure", "phr", "o kadar emin değilim", "I'm not so sure that's a good idea.", "Bunun iyi bir fikir olduğundan o kadar emin değilim."],
  ["that's a good point", "phr", "iyi bir noktaya değindin", "That's a good point — I hadn't thought of that.", "İyi bir noktaya değindin, bunu düşünmemiştim."],
  ["let me think", "phr", "bir düşüneyim", "Let me think about it and call you back.", "Bir düşüneyim, seni geri ararım."],
  ["how come", "phr", "nasıl oluyor da, neden", "How come you're not at work today?", "Nasıl oluyor da bugün işte değilsin?"],
  ["no way", "phr", "olamaz, asla", "No way! I don't believe it.", "Olamaz! İnanmıyorum."],
  ["just in case", "phr", "ne olur ne olmaz", "Take a jacket, just in case.", "Ne olur ne olmaz, bir ceket al."],
  ["I'm afraid not", "phr", "maalesef hayır", "Is there any cake left? — I'm afraid not.", "Hiç pasta kaldı mı? — Maalesef hayır."],
  ["don't mention it", "phr", "rica ederim, lafı olmaz", "Thanks for your help! — Don't mention it.", "Yardımın için teşekkürler! — Lafı olmaz."],
  ["take it easy", "phr", "sakin ol; kendini yorma", "Take it easy — the exam isn't until June.", "Sakin ol, sınav hazirana kadar değil."],
  ["what's the point", "phr", "ne anlamı var", "What's the point of waiting? Let's go.", "Beklemenin ne anlamı var? Hadi gidelim."],
  ["sounds good", "phr", "kulağa hoş geliyor, olur", "Pizza tonight? — Sounds good!", "Bu akşam pizza? — Olur!"],
];
