import type { LexiconEntry } from "../types";

/** A1 sets 16–20: places in town, transport & travel, animals, nature, hobbies & sport. */
export const A1_PART4: LexiconEntry[] = [
  // Set 16 — Places in town
  ["city", "n", "şehir", "Istanbul is a big city.", "İstanbul büyük bir şehir."],
  ["town", "n", "kasaba, küçük şehir", "I grew up in a small town.", "Küçük bir kasabada büyüdüm."],
  ["village", "n", "köy", "My grandparents live in a village.", "Büyükannemlerle büyükbabam bir köyde yaşıyor."],
  ["shop", "n", "dükkan, mağaza", "The shop is closed on Sunday.", "Dükkan pazar günü kapalı."],
  ["market", "n", "pazar, market", "We buy vegetables at the market.", "Sebzeleri pazardan alırız."],
  ["supermarket", "n", "süpermarket", "Is there a supermarket near here?", "Buralarda bir süpermarket var mı?"],
  ["bank", "n", "banka", "The bank opens at nine.", "Banka dokuzda açılır."],
  ["hospital", "n", "hastane", "She works at the hospital.", "Hastanede çalışıyor."],
  ["hotel", "n", "otel", "Our hotel is near the beach.", "Otelimiz plaja yakın."],
  ["park", "n", "park", "Let's go for a walk in the park.", "Parkta yürüyüşe çıkalım."],
  ["museum", "n", "müze", "The museum has old coins.", "Müzede eski paralar var."],
  ["library", "n", "kütüphane", "I study in the library.", "Kütüphanede ders çalışırım.", "“bookshop” (kitapçı) ile karıştırma."],
  ["cinema", "n", "sinema", "We go to the cinema on Fridays.", "Cumaları sinemaya gideriz."],
  ["post office", "n", "postane", "Where is the post office?", "Postane nerede?"],
  ["station", "n", "istasyon", "The train station is very busy.", "Tren istasyonu çok kalabalık."],
  ["airport", "n", "havalimanı", "We go to the airport by taxi.", "Havalimanına taksiyle gideriz."],
  ["bridge", "n", "köprü", "The bridge crosses the river.", "Köprü nehrin üzerinden geçiyor."],
  ["building", "n", "bina", "It's the tallest building in the city.", "Şehrin en yüksek binası."],
  ["centre", "n", "merkez", "The hotel is in the city centre.", "Otel şehir merkezinde."],
  ["map", "n", "harita", "Look at the map.", "Haritaya bak."],

  // Set 17 — Transport & travel
  ["car", "n", "araba", "My father drives a blue car.", "Babam mavi bir araba kullanıyor."],
  ["bus", "n", "otobüs", "I take the bus to work.", "İşe otobüsle giderim."],
  ["train", "n", "tren", "The train leaves at seven.", "Tren yedide kalkıyor."],
  ["plane", "n", "uçak", "The plane lands at noon.", "Uçak öğlen iniyor."],
  ["bike", "n", "bisiklet", "I ride my bike to school.", "Okula bisikletle giderim."],
  ["boat", "n", "tekne, gemi", "We take a boat to the island.", "Adaya tekneyle gideriz."],
  ["taxi", "n", "taksi", "Let's take a taxi.", "Taksiye binelim."],
  ["ticket", "n", "bilet", "Two tickets to Ankara, please.", "Ankara'ya iki bilet, lütfen."],
  ["road", "n", "yol", "Be careful on the road.", "Yolda dikkatli ol."],
  ["drive", "v", "araba sürmek", "Can you drive?", "Araba sürebilir misin?"],
  ["ride", "v", "binmek (bisiklet, at)", "She rides a horse.", "At biniyor."],
  ["travel", "v", "seyahat etmek", "I love to travel.", "Seyahat etmeyi çok severim."],
  ["trip", "n", "gezi, yolculuk", "We are going on a trip to Cappadocia.", "Kapadokya'ya geziye gidiyoruz."],
  ["holiday", "n", "tatil", "Where are you going on holiday?", "Tatile nereye gidiyorsun?", "Amerikan İngilizcesinde “vacation”."],
  ["passport", "n", "pasaport", "Don't forget your passport.", "Pasaportunu unutma."],
  ["suitcase", "n", "bavul", "My suitcase is very heavy.", "Bavulum çok ağır."],
  ["arrive", "v", "varmak, gelmek", "We arrive in Rome at eight.", "Roma'ya sekizde varıyoruz.", "Şehir/ülke için “arrive in”, bina için “arrive at”."],
  ["leave", "v", "ayrılmak, çıkmak", "The bus leaves at noon.", "Otobüs öğlen kalkıyor."],
  ["stop", "n", "durak", "Get off at the next stop.", "Bir sonraki durakta in."],
  ["walk", "v", "yürümek", "I walk to work every day.", "Her gün işe yürüyerek giderim."],

  // Set 18 — Animals
  ["animal", "n", "hayvan", "What's your favourite animal?", "En sevdiğin hayvan hangisi?"],
  ["dog", "n", "köpek", "The dog is barking.", "Köpek havlıyor."],
  ["cat", "n", "kedi", "Istanbul has many cats.", "İstanbul'da çok kedi var."],
  ["bird", "n", "kuş", "A bird is singing in the tree.", "Ağaçta bir kuş ötüyor."],
  ["horse", "n", "at", "The horse runs very fast.", "At çok hızlı koşuyor."],
  ["cow", "n", "inek", "Cows give us milk.", "İnekler bize süt verir."],
  ["sheep", "n", "koyun", "There are sheep on the hill.", "Tepede koyunlar var.", "Tekili ve çoğulu aynıdır: one sheep, two sheep."],
  ["goat", "n", "keçi", "The goat is eating grass.", "Keçi ot yiyor."],
  ["rabbit", "n", "tavşan", "The rabbit eats carrots.", "Tavşan havuç yer."],
  ["mouse", "n", "fare", "The cat is chasing a mouse.", "Kedi bir fareyi kovalıyor.", "Çoğulu düzensizdir: mice."],
  ["lion", "n", "aslan", "The lion is the king of the jungle.", "Aslan ormanlar kralıdır."],
  ["tiger", "n", "kaplan", "Tigers have stripes.", "Kaplanların çizgileri vardır."],
  ["elephant", "n", "fil", "Elephants are very big.", "Filler çok büyüktür."],
  ["monkey", "n", "maymun", "The monkey is climbing a tree.", "Maymun ağaca tırmanıyor."],
  ["bear", "n", "ayı", "Bears sleep in winter.", "Ayılar kışın uyur."],
  ["snake", "n", "yılan", "I'm afraid of snakes.", "Yılanlardan korkarım."],
  ["duck", "n", "ördek", "Ducks swim in the lake.", "Ördekler gölde yüzer."],
  ["pet", "n", "evcil hayvan", "Do you have a pet?", "Evcil hayvanın var mı?"],
  ["zoo", "n", "hayvanat bahçesi", "We saw a giraffe at the zoo.", "Hayvanat bahçesinde bir zürafa gördük."],
  ["insect", "n", "böcek", "Bees are useful insects.", "Arılar faydalı böceklerdir."],

  // Set 19 — Nature
  ["tree", "n", "ağaç", "There is an old tree in the garden.", "Bahçede yaşlı bir ağaç var."],
  ["flower", "n", "çiçek", "She gave me flowers.", "Bana çiçek verdi."],
  ["grass", "n", "çimen, ot", "Don't walk on the grass.", "Çimlere basmayın."],
  ["sea", "n", "deniz", "The sea is warm in July.", "Temmuzda deniz ılıktır."],
  ["beach", "n", "plaj, kumsal", "We spent the day on the beach.", "Günü plajda geçirdik."],
  ["river", "n", "nehir", "The river is very long.", "Nehir çok uzun."],
  ["lake", "n", "göl", "We swam in the lake.", "Gölde yüzdük."],
  ["mountain", "n", "dağ", "Ağrı is the highest mountain in Turkey.", "Ağrı Türkiye'nin en yüksek dağıdır."],
  ["hill", "n", "tepe", "Our house is on a hill.", "Evimiz bir tepenin üzerinde."],
  ["forest", "n", "orman", "Wolves live in the forest.", "Kurtlar ormanda yaşar."],
  ["island", "n", "ada", "We visited an island near Bodrum.", "Bodrum yakınlarında bir adayı ziyaret ettik.", "“s” harfi okunmaz: /ˈaɪlənd/."],
  ["field", "n", "tarla, alan", "Cows eat grass in the field.", "İnekler tarlada ot yiyor."],
  ["stone", "n", "taş", "The house is made of stone.", "Ev taştan yapılmış."],
  ["sand", "n", "kum", "The children are playing in the sand.", "Çocuklar kumda oynuyor."],
  ["star", "n", "yıldız", "I can see many stars tonight.", "Bu gece çok yıldız görebiliyorum."],
  ["moon", "n", "ay (gök cismi)", "The moon is full tonight.", "Bu gece dolunay var."],
  ["world", "n", "dünya", "I want to travel around the world.", "Dünyayı dolaşmak istiyorum."],
  ["air", "n", "hava (soluduğumuz)", "The air is fresh in the mountains.", "Dağlarda hava temiz."],
  ["fire", "n", "ateş, yangın", "We sat around the fire.", "Ateşin etrafında oturduk."],
  ["plant", "n", "bitki", "Water the plants every day.", "Bitkileri her gün sula."],

  // Set 20 — Hobbies & sport
  ["hobby", "n", "hobi", "My hobby is photography.", "Hobim fotoğrafçılık."],
  ["sport", "n", "spor", "Football is a popular sport.", "Futbol popüler bir spordur."],
  ["football", "n", "futbol", "We play football after school.", "Okuldan sonra futbol oynarız."],
  ["basketball", "n", "basketbol", "He's tall and good at basketball.", "Uzun boylu ve basketbolda iyi."],
  ["tennis", "n", "tenis", "Do you play tennis?", "Tenis oynar mısın?"],
  ["swim", "v", "yüzmek", "I can swim very well.", "Çok iyi yüzebilirim."],
  ["run", "v", "koşmak", "I run in the park every morning.", "Her sabah parkta koşarım."],
  ["dance", "v", "dans etmek", "She loves to dance.", "Dans etmeye bayılır."],
  ["sing", "v", "şarkı söylemek", "We sing songs in class.", "Sınıfta şarkı söyleriz."],
  ["play", "v", "oynamak; çalmak (enstrüman)", "He plays the guitar.", "Gitar çalar.", "Spor için “play football”, enstrüman için “play the guitar”."],
  ["game", "n", "oyun; maç", "Let's play a game.", "Bir oyun oynayalım."],
  ["music", "n", "müzik", "I listen to music on the bus.", "Otobüste müzik dinlerim."],
  ["song", "n", "şarkı", "This is my favourite song.", "Bu en sevdiğim şarkı."],
  ["film", "n", "film", "Let's watch a film tonight.", "Bu akşam bir film izleyelim.", "Amerikan İngilizcesinde “movie”."],
  ["photo", "n", "fotoğraf", "Can I take a photo?", "Fotoğraf çekebilir miyim?"],
  ["guitar", "n", "gitar", "My brother plays the guitar.", "Ağabeyim gitar çalar."],
  ["team", "n", "takım", "Which team do you support?", "Hangi takımı tutuyorsun?"],
  ["ball", "n", "top", "Throw the ball to me.", "Topu bana at."],
  ["party", "n", "parti", "We're having a party on Saturday.", "Cumartesi parti veriyoruz."],
  ["free time", "n", "boş zaman", "What do you do in your free time?", "Boş zamanında ne yaparsın?"],
];
