import type { LexiconEntry } from "../types";

/** A1 sets 26–30: pronouns & determiners, place words, questions & linking words, how often, shopping & money. */
export const A1_PART6: LexiconEntry[] = [
  // Set 26 — Pronouns & determiners
  ["I", "pron", "ben", "I am from Turkey.", "Ben Türkiye'denim.", "Her zaman büyük harfle yazılır."],
  ["you", "pron", "sen, siz", "You are my best friend.", "Sen benim en iyi arkadaşımsın."],
  ["he", "pron", "o (erkek)", "He is a doctor.", "O bir doktor."],
  ["she", "pron", "o (kadın)", "She is my sister.", "O benim kız kardeşim."],
  ["it", "pron", "o (cansız, hayvan)", "It is a nice day.", "Güzel bir gün."],
  ["we", "pron", "biz", "We are students.", "Biz öğrenciyiz."],
  ["they", "pron", "onlar", "They live next door.", "Onlar yan dairede oturuyor."],
  ["my", "det", "benim", "This is my room.", "Burası benim odam."],
  ["your", "det", "senin, sizin", "Is this your bag?", "Bu senin çantan mı?"],
  ["his", "det", "onun (erkek)", "His car is red.", "Onun arabası kırmızı."],
  ["her", "det", "onun (kadın)", "Her name is Elif.", "Onun adı Elif."],
  ["our", "det", "bizim", "Our house is near the sea.", "Evimiz denize yakın."],
  ["their", "det", "onların", "Their children are at school.", "Çocukları okulda."],
  ["this", "det", "bu", "This book is mine.", "Bu kitap benim."],
  ["that", "det", "şu, o", "Who is that man?", "Şu adam kim?"],
  ["these", "det", "bunlar", "These shoes are new.", "Bu ayakkabılar yeni."],
  ["those", "det", "şunlar", "Those are my friends.", "Şunlar benim arkadaşlarım."],
  ["every", "det", "her", "I run every morning.", "Her sabah koşarım."],
  ["other", "det", "diğer", "Where are the other students?", "Diğer öğrenciler nerede?"],
  ["something", "pron", "bir şey", "I want to tell you something.", "Sana bir şey söylemek istiyorum."],

  // Set 27 — Where things are
  ["in", "prep", "içinde, -de", "The keys are in my bag.", "Anahtarlar çantamda."],
  ["on", "prep", "üstünde", "The book is on the table.", "Kitap masanın üstünde."],
  ["under", "prep", "altında", "The cat is under the bed.", "Kedi yatağın altında."],
  ["next to", "prep", "yanında", "The bank is next to the café.", "Banka kafenin yanında."],
  ["near", "prep", "yakınında", "I live near the school.", "Okulun yakınında oturuyorum."],
  ["behind", "prep", "arkasında", "The garden is behind the house.", "Bahçe evin arkasında."],
  ["in front of", "prep", "önünde", "Wait in front of the cinema.", "Sinemanın önünde bekle."],
  ["between", "prep", "arasında (iki şey)", "The shop is between the bank and the park.", "Dükkan bankayla parkın arasında."],
  ["opposite", "prep", "karşısında", "The hotel is opposite the station.", "Otel istasyonun karşısında."],
  ["at", "prep", "-de (nokta, adres, saat)", "I'm at home.", "Evdeyim.", "Saatlerle de kullanılır: at 5 o'clock."],
  ["to", "prep", "-e, -a (yön)", "I go to work by bus.", "İşe otobüsle giderim."],
  ["from", "prep", "-den, -dan", "I'm from Ankara.", "Ankaralıyım."],
  ["here", "adv", "burada, buraya", "Come here!", "Buraya gel!"],
  ["there", "adv", "orada, oraya", "Put it there.", "Onu oraya koy.", "“there is / there are” = var."],
  ["left", "n", "sol", "Turn left at the corner.", "Köşeden sola dön."],
  ["right", "n", "sağ", "The door is on the right.", "Kapı sağda."],
  ["up", "adv", "yukarı", "Look up at the sky.", "Gökyüzüne bak."],
  ["down", "adv", "aşağı", "Sit down, please.", "Oturun, lütfen."],
  ["inside", "adv", "içeride, içeri", "It's cold. Let's go inside.", "Hava soğuk. İçeri girelim."],
  ["outside", "adv", "dışarıda, dışarı", "The children are playing outside.", "Çocuklar dışarıda oynuyor."],

  // Set 28 — Question & linking words
  ["what", "pron", "ne", "What is your name?", "Adın ne?"],
  ["who", "pron", "kim", "Who is your teacher?", "Öğretmenin kim?"],
  ["where", "adv", "nerede, nereye", "Where do you live?", "Nerede oturuyorsun?"],
  ["when", "adv", "ne zaman", "When is your birthday?", "Doğum günün ne zaman?"],
  ["why", "adv", "neden", "Why are you late?", "Neden geç kaldın?"],
  ["how", "adv", "nasıl", "How are you?", "Nasılsın?"],
  ["which", "det", "hangi", "Which colour do you like?", "Hangi rengi seversin?"],
  ["how much", "phr", "ne kadar (fiyat, miktar)", "How much is this shirt?", "Bu gömlek ne kadar?"],
  ["how many", "phr", "kaç tane", "How many brothers do you have?", "Kaç erkek kardeşin var?"],
  ["and", "conj", "ve", "I like tea and coffee.", "Çay ve kahveyi severim."],
  ["but", "conj", "ama", "It's cold but sunny.", "Hava soğuk ama güneşli."],
  ["or", "conj", "veya, ya da", "Tea or coffee?", "Çay mı kahve mi?"],
  ["because", "conj", "çünkü", "I'm tired because I worked late.", "Yorgunum çünkü geç saate kadar çalıştım."],
  ["so", "conj", "bu yüzden", "It was raining, so we stayed home.", "Yağmur yağıyordu, bu yüzden evde kaldık."],
  ["then", "adv", "sonra; o zaman", "First wash, then dry your hands.", "Önce ellerini yıka, sonra kurula."],
  ["also", "adv", "de, da, ayrıca", "She speaks English and also German.", "İngilizce ve ayrıca Almanca konuşuyor."],
  ["too", "adv", "de, da; fazla", "I like pizza too.", "Ben de pizza severim.", "Cümle sonunda “de/da”, sıfattan önce “fazla” anlamına gelir: too hot."],
  ["very", "adv", "çok", "It's very cold today.", "Bugün hava çok soğuk."],
  ["with", "prep", "ile, birlikte", "I live with my parents.", "Annem ve babamla yaşıyorum."],
  ["without", "prep", "-sız, olmadan", "I drink coffee without sugar.", "Kahveyi şekersiz içerim."],

  // Set 29 — How often & when
  ["always", "adv", "her zaman", "I always get up at seven.", "Her zaman yedide kalkarım.", "Sıklık zarfları genelde fiilden önce gelir."],
  ["usually", "adv", "genellikle", "I usually walk to work.", "Genellikle işe yürüyerek giderim."],
  ["often", "adv", "sık sık", "We often eat fish.", "Sık sık balık yeriz."],
  ["sometimes", "adv", "bazen", "I sometimes watch TV.", "Bazen televizyon izlerim."],
  ["never", "adv", "asla, hiç", "I never drink coffee at night.", "Geceleri asla kahve içmem."],
  ["again", "adv", "tekrar", "Say it again, please.", "Tekrar söyler misin, lütfen?"],
  ["already", "adv", "çoktan, zaten", "I've already had lunch.", "Öğle yemeğini zaten yedim."],
  ["soon", "adv", "yakında", "See you soon!", "Yakında görüşürüz!"],
  ["still", "adv", "hâlâ", "He's still at school.", "Hâlâ okulda."],
  ["before", "prep", "önce", "Wash your hands before dinner.", "Akşam yemeğinden önce ellerini yıka."],
  ["after", "prep", "sonra", "We play football after school.", "Okuldan sonra futbol oynarız."],
  ["every day", "phr", "her gün", "I read every day.", "Her gün okurum."],
  ["once", "adv", "bir kez", "I go to the gym once a week.", "Haftada bir kez spor salonuna giderim."],
  ["twice", "adv", "iki kez", "I brush my teeth twice a day.", "Dişlerimi günde iki kez fırçalarım."],
  ["tonight", "adv", "bu gece, bu akşam", "What are you doing tonight?", "Bu akşam ne yapıyorsun?"],
  ["ago", "adv", "önce (geçmiş)", "I moved here two years ago.", "İki yıl önce buraya taşındım.", "Süreden sonra gelir: two days ago."],
  ["next", "adj", "gelecek, sonraki", "See you next week.", "Gelecek hafta görüşürüz."],
  ["during", "prep", "sırasında, boyunca", "Don't talk during the film.", "Film sırasında konuşma."],
  ["until", "prep", "-e kadar", "The shop is open until nine.", "Dükkan dokuza kadar açık."],
  ["just", "adv", "yeni, az önce; sadece", "I've just arrived.", "Az önce geldim."],

  // Set 30 — Shopping & money
  ["money", "n", "para", "I don't have much money.", "Fazla param yok.", "Sayılamaz: “much money”, “a lot of money”."],
  ["price", "n", "fiyat", "The price is too high.", "Fiyat çok yüksek."],
  ["cost", "v", "(fiyatı) tutmak", "How much does it cost?", "Ne kadar tutuyor?"],
  ["spend", "v", "harcamak (para, zaman)", "I spend a lot of money on books.", "Kitaplara çok para harcarım."],
  ["card", "n", "kart", "Can I pay by card?", "Kartla ödeyebilir miyim?"],
  ["cash", "n", "nakit", "Do you have cash?", "Nakit paran var mı?"],
  ["customer", "n", "müşteri", "The customer wants a refund.", "Müşteri parasını geri istiyor."],
  ["open", "adj", "açık", "Is the shop open?", "Dükkan açık mı?"],
  ["closed", "adj", "kapalı", "The bank is closed today.", "Banka bugün kapalı."],
  ["sale", "n", "indirim; satış", "Everything is on sale.", "Her şey indirimde."],
  ["shopping", "n", "alışveriş", "I go shopping on Saturdays.", "Cumartesileri alışverişe giderim."],
  ["try on", "pv", "denemek (giysi)", "Can I try on this jacket?", "Bu ceketi deneyebilir miyim?"],
  ["receipt", "n", "fiş, makbuz", "Can I have a receipt?", "Fiş alabilir miyim?", "“p” harfi okunmaz: /rɪˈsiːt/."],
  ["change", "n", "para üstü; bozuk para", "Here's your change.", "Buyrun para üstünüz."],
  ["bottle", "n", "şişe", "A bottle of water, please.", "Bir şişe su, lütfen."],
  ["kilo", "n", "kilo", "Two kilos of apples, please.", "İki kilo elma, lütfen."],
  ["piece", "n", "parça, adet", "A piece of cake, please.", "Bir dilim kek, lütfen."],
  ["wallet", "n", "cüzdan", "My wallet is in my bag.", "Cüzdanım çantamda."],
  ["free", "adj", "bedava; boş, serbest", "The museum is free on Sundays.", "Müze pazar günleri ücretsiz."],
  ["lira", "n", "lira", "It costs fifty lira.", "Elli lira tutuyor."],
];
