import type { LexiconEntry } from "../types";

/** A1 sets 31–35: health, technology, daily routine, in the kitchen, countries & languages. */
export const A1_PART7: LexiconEntry[] = [
  // Set 31 — Health
  ["health", "n", "sağlık", "Sport is good for your health.", "Spor sağlığın için iyidir."],
  ["healthy", "adj", "sağlıklı", "Eat healthy food.", "Sağlıklı yiyecekler ye."],
  ["ill", "adj", "hasta", "She is ill in bed.", "Hasta yatıyor."],
  ["pain", "n", "ağrı, acı", "I have a pain in my back.", "Sırtımda bir ağrı var."],
  ["headache", "n", "baş ağrısı", "I have a headache.", "Başım ağrıyor."],
  ["cold", "n", "soğuk algınlığı, nezle", "I have a cold.", "Nezleyim.", "“have a cold” kalıbıyla kullanılır."],
  ["medicine", "n", "ilaç", "Take this medicine twice a day.", "Bu ilacı günde iki kez al."],
  ["hurt", "v", "acımak, incitmek", "My foot hurts.", "Ayağım acıyor."],
  ["rest", "v", "dinlenmek", "You need to rest.", "Dinlenmen gerekiyor."],
  ["pharmacy", "n", "eczane", "The pharmacy is open all night.", "Eczane bütün gece açık."],
  ["patient", "n", "hasta (kişi)", "The doctor is with a patient.", "Doktor bir hastayla ilgileniyor."],
  ["better", "adj", "daha iyi", "I feel better today.", "Bugün kendimi daha iyi hissediyorum."],
  ["fever", "n", "ateş (hastalık)", "The baby has a fever.", "Bebeğin ateşi var."],
  ["cough", "n", "öksürük", "I have a bad cough.", "Kötü bir öksürüğüm var."],
  ["accident", "n", "kaza", "There was an accident on the road.", "Yolda bir kaza oldu."],
  ["ambulance", "n", "ambulans", "Call an ambulance!", "Ambulans çağırın!"],
  ["exercise", "n", "egzersiz, alıştırma", "I do exercise every morning.", "Her sabah egzersiz yaparım."],
  ["blood", "n", "kan", "The nurse takes some blood.", "Hemşire biraz kan alıyor."],
  ["dead", "adj", "ölü", "The plant is dead.", "Bitki ölmüş."],
  ["alive", "adj", "canlı, hayatta", "The fish is still alive.", "Balık hâlâ canlı."],

  // Set 32 — Technology & media
  ["phone", "n", "telefon", "My phone is on the table.", "Telefonum masanın üstünde."],
  ["computer", "n", "bilgisayar", "I work on a computer.", "Bilgisayarda çalışırım."],
  ["internet", "n", "internet", "I read the news on the internet.", "Haberleri internetten okurum."],
  ["email", "n", "e-posta", "Send me an email.", "Bana bir e-posta gönder."],
  ["message", "n", "mesaj", "I got your message.", "Mesajını aldım."],
  ["website", "n", "web sitesi", "Visit our website.", "Web sitemizi ziyaret edin."],
  ["television (TV)", "n", "televizyon", "Turn off the TV.", "Televizyonu kapat."],
  ["radio", "n", "radyo", "I listen to the radio in the car.", "Arabada radyo dinlerim."],
  ["camera", "n", "kamera, fotoğraf makinesi", "This camera takes good photos.", "Bu makine iyi fotoğraf çeker."],
  ["newspaper", "n", "gazete", "My father reads the newspaper.", "Babam gazete okur."],
  ["magazine", "n", "dergi", "She buys a fashion magazine.", "Bir moda dergisi alıyor."],
  ["news", "n", "haberler", "Did you hear the news?", "Haberleri duydun mu?", "Sonu -s ile bitse de tekildir: “The news is good.”"],
  ["video", "n", "video", "Watch this funny video.", "Bu komik videoyu izle."],
  ["app", "n", "uygulama", "I use an app to learn words.", "Kelime öğrenmek için bir uygulama kullanıyorum."],
  ["send", "v", "göndermek", "Send me the photos.", "Fotoğrafları bana gönder."],
  ["click", "v", "tıklamak", "Click on the link.", "Bağlantıya tıkla."],
  ["password", "n", "şifre", "Don't share your password.", "Şifreni paylaşma."],
  ["online", "adv", "çevrimiçi, internette", "I buy books online.", "Kitapları internetten alırım."],
  ["screen", "n", "ekran", "The screen is too small.", "Ekran çok küçük."],
  ["battery", "n", "pil, batarya", "My phone battery is low.", "Telefonumun şarjı az."],

  // Set 33 — Daily routine
  ["get up", "pv", "kalkmak (yataktan)", "I get up at seven.", "Yedide kalkarım."],
  ["get dressed", "phr", "giyinmek", "I get dressed after breakfast.", "Kahvaltıdan sonra giyinirim."],
  ["have a shower", "phr", "duş almak", "I have a shower every morning.", "Her sabah duş alırım."],
  ["brush", "v", "fırçalamak", "Brush your teeth.", "Dişlerini fırçala."],
  ["go to bed", "phr", "yatmak", "I go to bed at eleven.", "On birde yatarım."],
  ["go out", "pv", "dışarı çıkmak", "We go out on Friday nights.", "Cuma akşamları dışarı çıkarız."],
  ["come back", "pv", "geri gelmek", "I come back home at six.", "Altıda eve dönerim."],
  ["go shopping", "phr", "alışverişe gitmek", "Let's go shopping.", "Hadi alışverişe gidelim."],
  ["relax", "v", "rahatlamak, dinlenmek", "I relax with a book.", "Kitapla rahatlarım."],
  ["routine", "n", "rutin, günlük düzen", "Tell me about your daily routine.", "Bana günlük düzenini anlat."],
  ["every morning", "phr", "her sabah", "I drink tea every morning.", "Her sabah çay içerim."],
  ["lunch break", "n", "öğle arası", "I call my mother in my lunch break.", "Öğle arasında annemi ararım."],
  ["alarm clock", "n", "çalar saat", "My alarm clock rings at six.", "Çalar saatim altıda çalar."],
  ["timetable", "n", "ders/sefer programı", "Check the bus timetable.", "Otobüs saatlerine bak."],
  ["tidy", "adj", "düzenli, toplu", "Keep your room tidy.", "Odanı düzenli tut."],
  ["busy day", "phr", "yoğun gün", "Today is a busy day for me.", "Bugün benim için yoğun bir gün."],
  ["walk the dog", "phr", "köpeği gezdirmek", "I walk the dog after dinner.", "Akşam yemeğinden sonra köpeği gezdiririm."],
  ["make the bed", "phr", "yatağı toplamak", "Make your bed every morning.", "Her sabah yatağını topla."],
  ["catch", "v", "yakalamak; (otobüse) yetişmek", "I catch the bus at 7:30.", "7.30 otobüsüne yetişirim."],
  ["arrive home", "phr", "eve varmak", "I arrive home at six.", "Eve altıda varırım.", "“home” ile “at/in” kullanılmaz."],

  // Set 34 — In the kitchen
  ["cut", "v", "kesmek", "Cut the onion.", "Soğanı kes."],
  ["boil", "v", "kaynatmak, haşlamak", "Boil the eggs for ten minutes.", "Yumurtaları on dakika haşla."],
  ["fry", "v", "kızartmak", "Fry the potatoes in oil.", "Patatesleri yağda kızart."],
  ["mix", "v", "karıştırmak", "Mix the flour and the eggs.", "Unu ve yumurtaları karıştır."],
  ["oil", "n", "yağ", "Use olive oil for the salad.", "Salata için zeytinyağı kullan."],
  ["butter", "n", "tereyağı", "I put butter on my bread.", "Ekmeğime tereyağı sürerim."],
  ["flour", "n", "un", "We need flour for the cake.", "Kek için una ihtiyacımız var."],
  ["onion", "n", "soğan", "Onions make me cry.", "Soğan beni ağlatır."],
  ["carrot", "n", "havuç", "Rabbits love carrots.", "Tavşanlar havuca bayılır."],
  ["lemon", "n", "limon", "Add some lemon juice.", "Biraz limon suyu ekle."],
  ["pepper", "n", "biber; karabiber", "Add salt and pepper.", "Tuz ve karabiber ekle."],
  ["bowl", "n", "kase, kâse", "Put the salad in a bowl.", "Salatayı bir kaseye koy."],
  ["fork", "n", "çatal", "Eat with a fork.", "Çatalla ye."],
  ["pan", "n", "tava", "Heat the pan.", "Tavayı ısıt."],
  ["oven", "n", "fırın", "Put the cake in the oven.", "Keki fırına koy."],
  ["recipe", "n", "tarif", "This is my grandmother's recipe.", "Bu büyükannemin tarifi."],
  ["taste", "v", "tadına bakmak; tadı olmak", "Taste the soup.", "Çorbanın tadına bak."],
  ["sweet", "adj", "tatlı", "The cake is very sweet.", "Kek çok tatlı."],
  ["fresh", "adj", "taze", "This bread is fresh.", "Bu ekmek taze."],
  ["kettle", "n", "su ısıtıcısı, çaydanlık", "Put the kettle on.", "Suyu ısıtmaya koy."],

  // Set 35 — Countries & languages
  ["country", "n", "ülke", "Turkey is a beautiful country.", "Türkiye güzel bir ülke."],
  ["Turkey", "n", "Türkiye", "I live in Turkey.", "Türkiye'de yaşıyorum."],
  ["Turkish", "adj", "Türk; Türkçe", "I speak Turkish.", "Türkçe konuşuyorum."],
  ["England", "n", "İngiltere", "London is in England.", "Londra İngiltere'de."],
  ["English", "n", "İngilizce", "I'm learning English.", "İngilizce öğreniyorum."],
  ["Germany", "n", "Almanya", "My uncle works in Germany.", "Amcam Almanya'da çalışıyor."],
  ["German", "adj", "Alman; Almanca", "She speaks German.", "Almanca konuşuyor."],
  ["France", "n", "Fransa", "Paris is in France.", "Paris Fransa'da."],
  ["French", "adj", "Fransız; Fransızca", "I like French food.", "Fransız yemeklerini severim."],
  ["America", "n", "Amerika", "They live in America.", "Amerika'da yaşıyorlar."],
  ["American", "adj", "Amerikalı", "My teacher is American.", "Öğretmenim Amerikalı."],
  ["language", "n", "dil", "How many languages do you speak?", "Kaç dil konuşuyorsun?"],
  ["foreign", "adj", "yabancı", "I want to learn a foreign language.", "Bir yabancı dil öğrenmek istiyorum."],
  ["capital", "n", "başkent", "Ankara is the capital of Turkey.", "Ankara Türkiye'nin başkentidir."],
  ["flag", "n", "bayrak", "The Turkish flag is red and white.", "Türk bayrağı kırmızı ve beyazdır."],
  ["nationality", "n", "uyruk, milliyet", "What's your nationality?", "Uyruğun ne?"],
  ["Europe", "n", "Avrupa", "Istanbul is in Europe and Asia.", "İstanbul Avrupa ve Asya'dadır."],
  ["north", "n", "kuzey", "Samsun is in the north of Turkey.", "Samsun Türkiye'nin kuzeyindedir."],
  ["south", "n", "güney", "Antalya is in the south.", "Antalya güneyde."],
  ["east", "n", "doğu", "The sun rises in the east.", "Güneş doğudan doğar."],
];
