import type { LexiconEntry } from "../types";

/** A1 sets 11–15: time, days & months, weather & seasons, jobs, school. */
export const A1_PART3: LexiconEntry[] = [
  // Set 11 — Time
  ["time", "n", "zaman; saat", "What time is it?", "Saat kaç?"],
  ["hour", "n", "saat (60 dakika)", "The film is two hours long.", "Film iki saat sürüyor."],
  ["minute", "n", "dakika", "Wait a minute, please.", "Bir dakika bekleyin, lütfen."],
  ["second", "n", "saniye", "It only takes a few seconds.", "Sadece birkaç saniye sürer."],
  ["day", "n", "gün", "Have a nice day!", "İyi günler!"],
  ["week", "n", "hafta", "I go swimming twice a week.", "Haftada iki kez yüzmeye giderim."],
  ["month", "n", "ay", "This month is very busy.", "Bu ay çok yoğun."],
  ["year", "n", "yıl", "I'm twenty years old.", "Yirmi yaşındayım."],
  ["today", "adv", "bugün", "Today is my birthday.", "Bugün benim doğum günüm."],
  ["tomorrow", "adv", "yarın", "See you tomorrow!", "Yarın görüşürüz!"],
  ["yesterday", "adv", "dün", "I was at home yesterday.", "Dün evdeydim."],
  ["now", "adv", "şimdi", "I'm busy now.", "Şu an meşgulüm."],
  ["later", "adv", "daha sonra", "Call me later.", "Beni sonra ara."],
  ["early", "adv", "erken", "I get up early.", "Erken kalkarım."],
  ["late", "adj", "geç", "Sorry, I'm late.", "Özür dilerim, geç kaldım."],
  ["o'clock", "adv", "saat (tam)", "The lesson starts at nine o'clock.", "Ders saat dokuzda başlar.", "Sadece tam saatlerde kullanılır."],
  ["quarter", "n", "çeyrek", "It's a quarter past ten.", "Saat onu çeyrek geçiyor."],
  ["weekend", "n", "hafta sonu", "What do you do at the weekend?", "Hafta sonu ne yaparsın?"],
  ["birthday", "n", "doğum günü", "Happy birthday!", "Doğum günün kutlu olsun!"],
  ["age", "n", "yaş", "What age is your son?", "Oğlun kaç yaşında?"],

  // Set 12 — Days & months
  ["Monday", "n", "pazartesi", "School starts on Monday.", "Okul pazartesi başlıyor.", "Günler büyük harfle yazılır ve “on” ile kullanılır."],
  ["Tuesday", "n", "salı", "I have English on Tuesdays.", "Salıları İngilizce dersim var."],
  ["Wednesday", "n", "çarşamba", "The museum is closed on Wednesday.", "Müze çarşamba günü kapalı."],
  ["Thursday", "n", "perşembe", "Let's meet on Thursday.", "Perşembe günü buluşalım."],
  ["Friday", "n", "cuma", "Friday is my favourite day.", "Cuma en sevdiğim gün."],
  ["Saturday", "n", "cumartesi", "I sleep late on Saturday.", "Cumartesi geç uyurum."],
  ["Sunday", "n", "pazar", "We visit my grandparents on Sunday.", "Pazar günü büyükannemlerle büyükbabamı ziyaret ederiz."],
  ["January", "n", "ocak", "It snows in January.", "Ocakta kar yağar.", "Aylar büyük harfle yazılır ve “in” ile kullanılır."],
  ["February", "n", "şubat", "February is a short month.", "Şubat kısa bir aydır."],
  ["March", "n", "mart", "Spring starts in March.", "Bahar martta başlar."],
  ["April", "n", "nisan", "My birthday is in April.", "Doğum günüm nisanda."],
  ["May", "n", "mayıs", "The weather is nice in May.", "Mayısta hava güzeldir."],
  ["June", "n", "haziran", "School finishes in June.", "Okul haziranda biter."],
  ["July", "n", "temmuz", "July is very hot.", "Temmuz çok sıcaktır."],
  ["August", "n", "ağustos", "We go on holiday in August.", "Ağustosta tatile gideriz."],
  ["September", "n", "eylül", "The new school year begins in September.", "Yeni okul yılı eylülde başlar."],
  ["October", "n", "ekim", "Leaves fall in October.", "Yapraklar ekimde dökülür."],
  ["November", "n", "kasım", "November is often rainy.", "Kasım genelde yağmurludur."],
  ["December", "n", "aralık", "December is the last month.", "Aralık son aydır."],
  ["date", "n", "tarih", "What's the date today?", "Bugünün tarihi ne?"],

  // Set 13 — Weather & seasons
  ["weather", "n", "hava (durumu)", "The weather is lovely today.", "Bugün hava çok güzel.", "Sayılamaz: “a weather” denmez."],
  ["sun", "n", "güneş", "The sun is shining.", "Güneş parlıyor."],
  ["sunny", "adj", "güneşli", "It's a sunny day.", "Güneşli bir gün."],
  ["rain", "n", "yağmur", "I love the sound of rain.", "Yağmurun sesini severim."],
  ["rainy", "adj", "yağmurlu", "London is often rainy.", "Londra genelde yağmurludur."],
  ["snow", "n", "kar", "The children play in the snow.", "Çocuklar karda oynuyor."],
  ["wind", "n", "rüzgar", "The wind is very strong today.", "Bugün rüzgar çok sert."],
  ["cloud", "n", "bulut", "There are dark clouds in the sky.", "Gökyüzünde kara bulutlar var."],
  ["cloudy", "adj", "bulutlu", "It's cloudy but warm.", "Bulutlu ama ılık."],
  ["hot", "adj", "sıcak", "It's very hot in August.", "Ağustosta hava çok sıcaktır."],
  ["cold", "adj", "soğuk", "The water is cold.", "Su soğuk."],
  ["warm", "adj", "ılık, sıcak", "Wear something warm.", "Sıcak tutan bir şey giy."],
  ["cool", "adj", "serin", "Evenings are cool in autumn.", "Sonbaharda akşamlar serin olur."],
  ["season", "n", "mevsim", "Which season do you like best?", "En çok hangi mevsimi seversin?"],
  ["spring", "n", "ilkbahar", "Flowers open in spring.", "Çiçekler ilkbaharda açar."],
  ["summer", "n", "yaz", "We swim in the sea in summer.", "Yazın denizde yüzeriz."],
  ["autumn", "n", "sonbahar", "Autumn is my favourite season.", "Sonbahar en sevdiğim mevsim.", "Amerikan İngilizcesinde “fall”."],
  ["winter", "n", "kış", "Winter is cold in Erzurum.", "Erzurum'da kış soğuktur."],
  ["sky", "n", "gökyüzü", "The sky is clear tonight.", "Bu gece gökyüzü açık."],
  ["temperature", "n", "sıcaklık, ateş", "The temperature is 30 degrees.", "Sıcaklık 30 derece."],

  // Set 14 — Jobs
  ["job", "n", "iş, meslek", "What's your job?", "Mesleğin ne?"],
  ["work", "v", "çalışmak", "I work in an office.", "Bir ofiste çalışıyorum."],
  ["teacher", "n", "öğretmen", "Our teacher is very friendly.", "Öğretmenimiz çok samimi."],
  ["doctor", "n", "doktor", "You should see a doctor.", "Bir doktora görünmelisin."],
  ["nurse", "n", "hemşire", "The nurse helps the patients.", "Hemşire hastalara yardım eder."],
  ["driver", "n", "şoför, sürücü", "The bus driver is waiting.", "Otobüs şoförü bekliyor."],
  ["cook", "n", "aşçı", "My father is a good cook.", "Babam iyi bir aşçıdır."],
  ["farmer", "n", "çiftçi", "The farmer has many cows.", "Çiftçinin çok ineği var."],
  ["police officer", "n", "polis memuru", "Ask a police officer for help.", "Bir polis memurundan yardım iste."],
  ["engineer", "n", "mühendis", "She is a computer engineer.", "O bir bilgisayar mühendisi."],
  ["student", "n", "öğrenci", "I'm a university student.", "Üniversite öğrencisiyim."],
  ["worker", "n", "işçi, çalışan", "The factory has 200 workers.", "Fabrikanın 200 çalışanı var."],
  ["office", "n", "ofis, büro", "The office opens at nine.", "Ofis dokuzda açılır."],
  ["boss", "n", "patron, şef", "My boss is on holiday.", "Patronum tatilde."],
  ["waiter", "n", "garson", "The waiter brings the menu.", "Garson menüyü getiriyor."],
  ["shop assistant", "n", "tezgâhtar, satış görevlisi", "The shop assistant is very helpful.", "Satış görevlisi çok yardımsever."],
  ["artist", "n", "sanatçı", "The artist paints every day.", "Sanatçı her gün resim yapar."],
  ["singer", "n", "şarkıcı", "She wants to be a singer.", "Şarkıcı olmak istiyor."],
  ["dentist", "n", "diş hekimi", "I go to the dentist twice a year.", "Yılda iki kez dişçiye giderim."],
  ["pilot", "n", "pilot", "The pilot speaks to the passengers.", "Pilot yolcularla konuşuyor."],

  // Set 15 — School
  ["school", "n", "okul", "I walk to school.", "Okula yürüyerek giderim.", "“go to school” derken “the” kullanılmaz."],
  ["class", "n", "sınıf; ders", "There are 25 students in my class.", "Sınıfımda 25 öğrenci var."],
  ["classroom", "n", "sınıf (oda)", "Our classroom is on the first floor.", "Sınıfımız birinci katta."],
  ["lesson", "n", "ders", "The English lesson is fun.", "İngilizce dersi eğlenceli."],
  ["book", "n", "kitap", "I'm reading a good book.", "İyi bir kitap okuyorum."],
  ["notebook", "n", "defter", "Write the words in your notebook.", "Kelimeleri defterine yaz."],
  ["pen", "n", "tükenmez kalem", "Can I borrow your pen?", "Kalemini ödünç alabilir miyim?"],
  ["pencil", "n", "kurşun kalem", "Draw with a pencil.", "Kurşun kalemle çiz."],
  ["paper", "n", "kağıt", "I need a piece of paper.", "Bir parça kağıda ihtiyacım var."],
  ["homework", "n", "ödev", "I do my homework after dinner.", "Ödevimi akşam yemeğinden sonra yaparım.", "Sayılamaz: “do homework”, “a lot of homework”."],
  ["exam", "n", "sınav", "I have an exam tomorrow.", "Yarın sınavım var."],
  ["test", "n", "test, sınav", "The test is very easy.", "Test çok kolay."],
  ["question", "n", "soru", "Can I ask a question?", "Bir soru sorabilir miyim?"],
  ["answer", "n", "cevap", "What's the answer?", "Cevap ne?"],
  ["word", "n", "kelime", "Learn ten new words every day.", "Her gün on yeni kelime öğren."],
  ["page", "n", "sayfa", "Open your books at page ten.", "Kitaplarınızı onuncu sayfada açın."],
  ["learn", "v", "öğrenmek", "I learn English at school.", "Okulda İngilizce öğreniyorum."],
  ["study", "v", "ders çalışmak, okumak", "She studies medicine.", "Tıp okuyor."],
  ["teach", "v", "öğretmek", "He teaches maths.", "Matematik öğretiyor."],
  ["university", "n", "üniversite", "My sister goes to university.", "Ablam üniversiteye gidiyor."],
];
