import type { LexiconEntry } from "../types";

/** A1 sets 6–10: food, drinks, the home, household objects, clothes. */
export const A1_PART2: LexiconEntry[] = [
  // Set 6 — Food
  ["food", "n", "yiyecek, yemek", "I like Turkish food.", "Türk yemeklerini severim."],
  ["bread", "n", "ekmek", "We buy fresh bread every day.", "Her gün taze ekmek alırız.", "Sayılamaz: “a piece of bread”, “some bread”."],
  ["cheese", "n", "peynir", "I have cheese for breakfast.", "Kahvaltıda peynir yerim."],
  ["egg", "n", "yumurta", "She eats two eggs every morning.", "Her sabah iki yumurta yer."],
  ["meat", "n", "et", "He doesn't eat meat.", "O et yemez."],
  ["chicken", "n", "tavuk", "We are having chicken for dinner.", "Akşam yemeğinde tavuk yiyoruz."],
  ["fish", "n", "balık", "Fish is good for you.", "Balık sağlığa iyidir."],
  ["rice", "n", "pirinç, pilav", "I cook rice with vegetables.", "Pilavı sebzeli pişiririm."],
  ["soup", "n", "çorba", "This soup is hot.", "Bu çorba sıcak."],
  ["salad", "n", "salata", "I'd like a green salad.", "Yeşil salata istiyorum."],
  ["fruit", "n", "meyve", "Eat more fruit.", "Daha fazla meyve ye."],
  ["apple", "n", "elma", "An apple a day is healthy.", "Günde bir elma sağlıklıdır."],
  ["banana", "n", "muz", "The monkey is eating a banana.", "Maymun muz yiyor."],
  ["vegetable", "n", "sebze", "Potatoes are vegetables.", "Patates bir sebzedir."],
  ["potato", "n", "patates", "I love baked potatoes.", "Fırında patatese bayılırım."],
  ["tomato", "n", "domates", "Put a tomato in the salad.", "Salataya bir domates koy."],
  ["sugar", "n", "şeker", "Do you take sugar in your tea?", "Çayına şeker alır mısın?"],
  ["salt", "n", "tuz", "Pass me the salt, please.", "Tuzu uzatır mısın, lütfen?"],
  ["breakfast", "n", "kahvaltı", "We have breakfast at eight.", "Saat sekizde kahvaltı yaparız.", "“have breakfast” kalıbıyla kullanılır."],
  ["dinner", "n", "akşam yemeği", "Dinner is ready!", "Akşam yemeği hazır!"],

  // Set 7 — Drinks & meals
  ["drink", "v", "içmek", "I drink a lot of water.", "Çok su içerim."],
  ["water", "n", "su", "Can I have a glass of water?", "Bir bardak su alabilir miyim?"],
  ["tea", "n", "çay", "Turkish people drink a lot of tea.", "Türkler çok çay içer."],
  ["coffee", "n", "kahve", "I need a cup of coffee.", "Bir fincan kahveye ihtiyacım var."],
  ["milk", "n", "süt", "Children should drink milk.", "Çocuklar süt içmeli."],
  ["juice", "n", "meyve suyu", "I'd like an orange juice.", "Bir portakal suyu istiyorum."],
  ["eat", "v", "yemek (yemek yemek)", "We eat lunch at school.", "Öğle yemeğini okulda yeriz."],
  ["lunch", "n", "öğle yemeği", "What's for lunch?", "Öğle yemeğinde ne var?"],
  ["meal", "n", "öğün, yemek", "Breakfast is the most important meal.", "Kahvaltı en önemli öğündür."],
  ["hungry", "adj", "aç", "I'm hungry. Let's eat.", "Açım. Hadi yiyelim."],
  ["thirsty", "adj", "susamış", "I'm thirsty after the game.", "Maçtan sonra susadım."],
  ["cake", "n", "kek, pasta", "She makes a birthday cake.", "Doğum günü pastası yapıyor."],
  ["chocolate", "n", "çikolata", "Do you like chocolate?", "Çikolata sever misin?"],
  ["ice cream", "n", "dondurma", "Let's have ice cream.", "Hadi dondurma yiyelim."],
  ["sandwich", "n", "sandviç", "I take a sandwich to work.", "İşe sandviç götürürüm."],
  ["pizza", "n", "pizza", "We order pizza on Fridays.", "Cuma günleri pizza sipariş ederiz."],
  ["restaurant", "n", "restoran", "This restaurant is very good.", "Bu restoran çok iyi."],
  ["menu", "n", "menü", "Can we see the menu, please?", "Menüyü görebilir miyiz, lütfen?"],
  ["delicious", "adj", "lezzetli", "This soup is delicious!", "Bu çorba çok lezzetli!"],
  ["cup", "n", "fincan, bardak", "Would you like a cup of tea?", "Bir fincan çay ister misiniz?"],

  // Set 8 — The home
  ["house", "n", "ev (bina)", "They have a house with a garden.", "Bahçeli bir evleri var."],
  ["home", "n", "ev, yuva", "I go home at six.", "Saat altıda eve giderim.", "“go home” derken “to” kullanılmaz."],
  ["flat", "n", "daire (apartman)", "I live in a small flat.", "Küçük bir dairede yaşıyorum.", "Amerikan İngilizcesinde “apartment”."],
  ["room", "n", "oda", "My room is on the second floor.", "Odam ikinci katta."],
  ["kitchen", "n", "mutfak", "Mum is in the kitchen.", "Annem mutfakta."],
  ["bedroom", "n", "yatak odası", "The flat has two bedrooms.", "Dairenin iki yatak odası var."],
  ["bathroom", "n", "banyo", "The bathroom is next to my room.", "Banyo odamın yanında."],
  ["living room", "n", "oturma odası", "We watch TV in the living room.", "Oturma odasında televizyon izleriz."],
  ["garden", "n", "bahçe", "The children play in the garden.", "Çocuklar bahçede oynuyor."],
  ["door", "n", "kapı", "Please close the door.", "Lütfen kapıyı kapat."],
  ["window", "n", "pencere", "Open the window, it's hot.", "Pencereyi aç, sıcak."],
  ["wall", "n", "duvar", "There is a picture on the wall.", "Duvarda bir resim var."],
  ["floor", "n", "yer, zemin; kat", "The keys are on the floor.", "Anahtarlar yerde."],
  ["stairs", "n", "merdiven", "Go up the stairs to the first floor.", "Merdivenlerden birinci kata çık."],
  ["roof", "n", "çatı", "There is a bird on the roof.", "Çatıda bir kuş var."],
  ["key", "n", "anahtar", "I can't find my keys.", "Anahtarlarımı bulamıyorum."],
  ["address", "n", "adres", "What's your address?", "Adresin ne?"],
  ["street", "n", "sokak, cadde", "I live on a quiet street.", "Sakin bir sokakta yaşıyorum."],
  ["live", "v", "yaşamak, oturmak", "Where do you live?", "Nerede yaşıyorsun?"],
  ["neighbour", "n", "komşu", "Our neighbours are very kind.", "Komşularımız çok nazik."],

  // Set 9 — Furniture & household objects
  ["table", "n", "masa", "The food is on the table.", "Yemek masada."],
  ["chair", "n", "sandalye", "Take a chair and sit down.", "Bir sandalye al ve otur."],
  ["bed", "n", "yatak", "I go to bed at eleven.", "Saat on birde yatarım.", "“go to bed” = yatmak."],
  ["sofa", "n", "kanepe", "The cat is sleeping on the sofa.", "Kedi kanepede uyuyor."],
  ["desk", "n", "çalışma masası, sıra", "My computer is on my desk.", "Bilgisayarım masamın üstünde."],
  ["lamp", "n", "lamba", "Turn on the lamp, please.", "Lambayı yak, lütfen."],
  ["clock", "n", "saat (duvar/masa)", "The clock on the wall is slow.", "Duvardaki saat geri kalıyor."],
  ["mirror", "n", "ayna", "She looks in the mirror.", "Aynaya bakıyor."],
  ["shelf", "n", "raf", "Put the books on the shelf.", "Kitapları rafa koy.", "Çoğulu: shelves."],
  ["box", "n", "kutu", "The toys are in a box.", "Oyuncaklar bir kutunun içinde."],
  ["bag", "n", "çanta, torba", "My bag is heavy.", "Çantam ağır."],
  ["picture", "n", "resim, fotoğraf", "Look at this picture.", "Şu resme bak."],
  ["fridge", "n", "buzdolabı", "The milk is in the fridge.", "Süt buzdolabında."],
  ["cooker", "n", "ocak, fırın", "The soup is on the cooker.", "Çorba ocakta."],
  ["towel", "n", "havlu", "Here's a clean towel.", "İşte temiz bir havlu."],
  ["soap", "n", "sabun", "Wash your hands with soap.", "Ellerini sabunla yıka."],
  ["glass", "n", "bardak; cam", "Be careful, the glass is broken.", "Dikkat et, bardak kırık."],
  ["plate", "n", "tabak", "Put the cake on a plate.", "Keki bir tabağa koy."],
  ["knife", "n", "bıçak", "Cut the bread with a knife.", "Ekmeği bıçakla kes.", "Çoğulu: knives."],
  ["spoon", "n", "kaşık", "I need a spoon for my soup.", "Çorbam için bir kaşığa ihtiyacım var."],

  // Set 10 — Clothes
  ["clothes", "n", "giysiler, kıyafetler", "I need new clothes.", "Yeni kıyafetlere ihtiyacım var.", "Her zaman çoğuldur."],
  ["shirt", "n", "gömlek", "He's wearing a white shirt.", "Beyaz bir gömlek giyiyor."],
  ["T-shirt", "n", "tişört", "I wear a T-shirt in summer.", "Yazın tişört giyerim."],
  ["trousers", "n", "pantolon", "These trousers are too long.", "Bu pantolon çok uzun.", "Her zaman çoğul: “a pair of trousers”."],
  ["jeans", "n", "kot pantolon", "I like wearing jeans.", "Kot pantolon giymeyi severim."],
  ["dress", "n", "elbise", "She has a beautiful dress.", "Güzel bir elbisesi var."],
  ["skirt", "n", "etek", "Her skirt is blue.", "Eteği mavi."],
  ["jacket", "n", "ceket, mont", "Take your jacket, it's cold.", "Montunu al, hava soğuk."],
  ["coat", "n", "palto", "I wear a coat in winter.", "Kışın palto giyerim."],
  ["shoe", "n", "ayakkabı", "These shoes are new.", "Bu ayakkabılar yeni."],
  ["sock", "n", "çorap", "I can't find my socks.", "Çoraplarımı bulamıyorum."],
  ["hat", "n", "şapka", "Wear a hat in the sun.", "Güneşte şapka tak."],
  ["wear", "v", "giymek, takmak", "Students wear a uniform.", "Öğrenciler üniforma giyer."],
  ["put on", "pv", "giymek, üstüne geçirmek", "Put on your shoes, we're late.", "Ayakkabılarını giy, geç kaldık.", "Giyinme eylemini anlatır; “wear” ise giymiş olma hâlidir."],
  ["take off", "pv", "çıkarmak (giysi)", "Take off your shoes at the door.", "Kapıda ayakkabılarını çıkar."],
  ["size", "n", "beden, boyut", "What size are you?", "Kaç beden giyiyorsun?"],
  ["pocket", "n", "cep", "My phone is in my pocket.", "Telefonum cebimde."],
  ["glasses", "n", "gözlük", "I wear glasses for reading.", "Okumak için gözlük takarım.", "Gözlük anlamında her zaman çoğuldur."],
  ["watch", "n", "kol saati", "What a nice watch!", "Ne güzel bir kol saati!"],
  ["umbrella", "n", "şemsiye", "Take an umbrella, it's raining.", "Şemsiye al, yağmur yağıyor."],
];
