import type { LexiconEntry } from "../types";

/** A1 sets 36–40: describing people, celebrations, everyday nouns, more verbs, useful words. */
export const A1_PART8: LexiconEntry[] = [
  // Set 36 — Describing people
  ["man", "n", "adam, erkek", "The man is wearing a hat.", "Adam şapka takıyor.", "Çoğulu düzensizdir: men."],
  ["woman", "n", "kadın", "The woman is my teacher.", "O kadın benim öğretmenim.", "Çoğulu düzensizdir: women."],
  ["person", "n", "kişi", "She's a very nice person.", "O çok hoş bir insan."],
  ["pretty", "adj", "sevimli, güzel", "What a pretty dress!", "Ne güzel bir elbise!"],
  ["handsome", "adj", "yakışıklı", "He's a handsome man.", "Yakışıklı bir adam."],
  ["fat", "adj", "şişman", "The cat is too fat.", "Kedi çok şişman."],
  ["thin", "adj", "zayıf; ince", "She is tall and thin.", "Uzun boylu ve zayıf."],
  ["strong", "adj", "güçlü", "He is very strong.", "O çok güçlü."],
  ["weak", "adj", "zayıf, güçsüz", "I feel weak after the illness.", "Hastalıktan sonra kendimi güçsüz hissediyorum."],
  ["quiet", "adj", "sessiz", "She's a quiet girl.", "Sessiz bir kız."],
  ["clever", "adj", "zeki", "He's a clever student.", "Zeki bir öğrenci."],
  ["lazy", "adj", "tembel", "Don't be lazy!", "Tembel olma!"],
  ["polite", "adj", "kibar", "Be polite to your teachers.", "Öğretmenlerine karşı kibar ol."],
  ["curly", "adj", "kıvırcık", "She has curly hair.", "Kıvırcık saçları var."],
  ["blond", "adj", "sarışın", "My sister is blond.", "Kız kardeşim sarışın."],
  ["beard", "n", "sakal", "My grandfather has a white beard.", "Dedemin beyaz bir sakalı var."],
  ["look like", "phr", "benzemek", "You look like your mother.", "Annene benziyorsun."],
  ["favourite", "adj", "en sevilen, favori", "What's your favourite food?", "En sevdiğin yemek ne?"],
  ["best", "adj", "en iyi", "She's my best friend.", "O benim en iyi arkadaşım."],
  ["different", "adj", "farklı", "We are very different.", "Biz çok farklıyız."],

  // Set 37 — Celebrations & free time
  ["present", "n", "hediye", "Thank you for the present!", "Hediye için teşekkürler!"],
  ["gift", "n", "hediye", "This is a gift for you.", "Bu senin için bir hediye."],
  ["invite", "v", "davet etmek", "I want to invite you to my party.", "Seni partime davet etmek istiyorum."],
  ["celebrate", "v", "kutlamak", "We celebrate New Year with family.", "Yeni yılı aileyle kutlarız."],
  ["wedding", "n", "düğün", "My cousin's wedding is in June.", "Kuzenimin düğünü haziranda."],
  ["festival", "n", "festival", "There's a music festival in the park.", "Parkta bir müzik festivali var."],
  ["concert", "n", "konser", "We have tickets for the concert.", "Konser için biletlerimiz var."],
  ["guest", "n", "misafir", "We have guests tonight.", "Bu akşam misafirimiz var."],
  ["candle", "n", "mum", "Blow out the candles!", "Mumları üfle!"],
  ["postcard", "n", "kartpostal", "Send me a postcard from Paris.", "Paris'ten bana bir kartpostal gönder."],
  ["fun", "n", "eğlence", "The party was great fun.", "Parti çok eğlenceliydi."],
  ["enjoy", "v", "keyif almak, beğenmek", "Enjoy your meal!", "Afiyet olsun!"],
  ["balloon", "n", "balon", "The room is full of balloons.", "Oda balonlarla dolu."],
  ["picnic", "n", "piknik", "Let's have a picnic by the lake.", "Göl kenarında piknik yapalım."],
  ["have fun", "phr", "eğlenmek", "Have fun at the party!", "Partide iyi eğlenceler!"],
  ["café", "n", "kafe", "Let's meet at the café.", "Kafede buluşalım."],
  ["join", "v", "katılmak", "Can I join you?", "Size katılabilir miyim?"],
  ["New Year", "n", "yılbaşı, yeni yıl", "Happy New Year!", "Mutlu yıllar!"],
  ["show", "n", "gösteri", "The show starts at eight.", "Gösteri sekizde başlıyor."],
  ["ticket office", "n", "gişe", "Buy tickets at the ticket office.", "Biletleri gişeden al."],

  // Set 38 — Everyday nouns
  ["thing", "n", "şey", "What is that thing?", "Şu şey ne?"],
  ["way", "n", "yol; yöntem", "This is the way to the station.", "İstasyonun yolu bu."],
  ["idea", "n", "fikir", "That's a great idea!", "Harika bir fikir!"],
  ["place", "n", "yer", "This is a nice place.", "Burası güzel bir yer."],
  ["life", "n", "hayat", "Life is beautiful.", "Hayat güzel."],
  ["problem", "n", "sorun", "No problem!", "Sorun değil!"],
  ["example", "n", "örnek", "Can you give an example?", "Bir örnek verebilir misin?"],
  ["part", "n", "parça, bölüm", "This is the best part of the film.", "Filmin en güzel kısmı bu."],
  ["kind", "n", "tür, çeşit", "What kind of music do you like?", "Ne tür müzik seversin?"],
  ["story", "n", "hikaye", "Read me a story.", "Bana bir hikaye oku."],
  ["letter", "n", "mektup; harf", "I got a letter from my friend.", "Arkadaşımdan bir mektup aldım."],
  ["list", "n", "liste", "Make a shopping list.", "Bir alışveriş listesi yap."],
  ["group", "n", "grup", "Work in groups of three.", "Üçlü gruplar hâlinde çalışın."],
  ["side", "n", "taraf, yan", "Walk on the left side.", "Sol tarafta yürü."],
  ["end", "n", "son", "The end of the film is sad.", "Filmin sonu üzücü."],
  ["top", "n", "tepe, üst", "Write your name at the top of the page.", "Adını sayfanın üst kısmına yaz."],
  ["noise", "n", "gürültü", "Don't make a noise!", "Gürültü yapma!"],
  ["dream", "n", "rüya; hayal", "I had a strange dream.", "Garip bir rüya gördüm."],
  ["fact", "n", "gerçek, olgu", "Is it a fact?", "Bu bir gerçek mi?"],
  ["information", "n", "bilgi", "I need some information.", "Biraz bilgiye ihtiyacım var.", "Sayılamaz: “an information” denmez."],

  // Set 39 — More verbs
  ["begin", "v", "başlamak", "The lesson begins at nine.", "Ders dokuzda başlıyor."],
  ["become", "v", "olmak (dönüşmek)", "She wants to become a doctor.", "Doktor olmak istiyor."],
  ["change", "v", "değiştirmek, değişmek", "I want to change my job.", "İşimi değiştirmek istiyorum."],
  ["choose", "v", "seçmek", "Choose one answer.", "Bir cevap seç."],
  ["climb", "v", "tırmanmak", "We climb the mountain.", "Dağa tırmanıyoruz."],
  ["cry", "v", "ağlamak", "The baby is crying.", "Bebek ağlıyor."],
  ["laugh", "v", "gülmek", "We laugh a lot together.", "Birlikte çok güleriz."],
  ["smile", "v", "gülümsemek", "Smile for the photo!", "Fotoğraf için gülümse!"],
  ["hope", "v", "umut etmek", "I hope you feel better.", "Umarım daha iyi hissedersin."],
  ["jump", "v", "zıplamak", "The children jump in the water.", "Çocuklar suya atlıyor."],
  ["kiss", "v", "öpmek", "She kisses her baby.", "Bebeğini öpüyor."],
  ["move", "v", "hareket etmek; taşınmak", "We are moving to Izmir.", "İzmir'e taşınıyoruz."],
  ["plan", "v", "planlamak", "We plan our holiday together.", "Tatilimizi birlikte planlarız."],
  ["practise", "v", "pratik yapmak", "Practise English every day.", "Her gün İngilizce pratik yap.", "Amerikan İngilizcesinde fiil de “practice” yazılır."],
  ["repeat", "v", "tekrarlamak", "Repeat after me.", "Benden sonra tekrarlayın."],
  ["shout", "v", "bağırmak", "Don't shout, I can hear you.", "Bağırma, seni duyabiliyorum."],
  ["spell", "v", "hecelemek", "How do you spell your name?", "Adını nasıl heceliyorsun?"],
  ["throw", "v", "atmak, fırlatmak", "Throw the ball!", "Topu at!"],
  ["win", "v", "kazanmak", "Our team wins every match.", "Takımımız her maçı kazanıyor."],
  ["work out", "pv", "spor yapmak", "I work out at the gym.", "Spor salonunda antrenman yaparım."],

  // Set 40 — Useful little words
  ["everyone", "pron", "herkes", "Everyone is here.", "Herkes burada."],
  ["nothing", "pron", "hiçbir şey", "There's nothing in the box.", "Kutuda hiçbir şey yok."],
  ["someone", "pron", "birisi", "Someone is at the door.", "Kapıda biri var."],
  ["anything", "pron", "herhangi bir şey", "Do you need anything?", "Bir şeye ihtiyacın var mı?"],
  ["everything", "pron", "her şey", "Everything is fine.", "Her şey yolunda."],
  ["nobody", "pron", "hiç kimse", "Nobody is at home.", "Evde kimse yok."],
  ["each", "det", "her bir", "Each student has a book.", "Her öğrencinin bir kitabı var."],
  ["both", "det", "her ikisi", "Both my parents are teachers.", "Annemle babamın ikisi de öğretmen."],
  ["a lot of", "det", "çok, bir sürü", "I have a lot of friends.", "Bir sürü arkadaşım var.", "Sayılabilen ve sayılamayan isimlerle kullanılabilir."],
  ["enough", "det", "yeterli", "We have enough food.", "Yeterince yiyeceğimiz var."],
  ["really", "adv", "gerçekten", "I really like this song.", "Bu şarkıyı gerçekten seviyorum."],
  ["maybe", "adv", "belki", "Maybe it will rain.", "Belki yağmur yağar."],
  ["of course", "phr", "tabii ki", "Of course you can come.", "Tabii ki gelebilirsin."],
  ["together", "adv", "birlikte", "Let's go together.", "Birlikte gidelim."],
  ["alone", "adj", "yalnız", "She lives alone.", "Yalnız yaşıyor."],
  ["same", "adj", "aynı", "We are in the same class.", "Aynı sınıftayız."],
  ["ready", "adj", "hazır", "Are you ready?", "Hazır mısın?"],
  ["right", "adj", "doğru", "That's the right answer.", "Doğru cevap bu."],
  ["wrong", "adj", "yanlış", "Sorry, wrong number.", "Özür dilerim, yanlış numara."],
  ["west", "n", "batı", "The sun sets in the west.", "Güneş batıdan batar."],
];
