import type { LexiconEntry } from "../types";

/** A1 sets 1–5: greetings, family, numbers, colours & shapes, the body. */
export const A1_PART1: LexiconEntry[] = [
  // Set 1 — Greetings & basics
  ["hello", "int", "merhaba", "Hello! How are you?", "Merhaba! Nasılsın?"],
  ["goodbye", "int", "hoşça kal, güle güle", "Goodbye, see you tomorrow.", "Hoşça kal, yarın görüşürüz."],
  ["please", "adv", "lütfen", "Can I have some water, please?", "Biraz su alabilir miyim, lütfen?", "Rica ederken cümlenin sonuna ya da başına gelir."],
  ["thank you", "phr", "teşekkür ederim", "Thank you for your help.", "Yardımın için teşekkür ederim."],
  ["sorry", "adj", "üzgün; özür dilerim", "Sorry, I am late.", "Özür dilerim, geç kaldım."],
  ["yes", "adv", "evet", "Yes, I like coffee.", "Evet, kahveyi severim."],
  ["no", "adv", "hayır", "No, thank you.", "Hayır, teşekkürler."],
  ["name", "n", "isim, ad", "My name is Ayşe.", "Benim adım Ayşe."],
  ["friend", "n", "arkadaş", "Ali is my best friend.", "Ali en iyi arkadaşım."],
  ["morning", "n", "sabah", "Good morning, everyone!", "Herkese günaydın!"],
  ["afternoon", "n", "öğleden sonra", "Good afternoon, Mr Smith.", "Tünaydın, Bay Smith."],
  ["evening", "n", "akşam", "We watch TV in the evening.", "Akşamları televizyon izleriz."],
  ["night", "n", "gece", "Good night, sleep well.", "İyi geceler, iyi uykular."],
  ["welcome", "adj", "hoş geldin(iz)", "Welcome to our school!", "Okulumuza hoş geldiniz!"],
  ["nice", "adj", "hoş, güzel", "Nice to meet you.", "Tanıştığımıza memnun oldum.", "“Nice to meet you” ilk tanışmada kullanılır."],
  ["meet", "v", "tanışmak; buluşmak", "I meet my friends on Saturdays.", "Cumartesileri arkadaşlarımla buluşurum."],
  ["fine", "adj", "iyi, güzel", "I'm fine, thanks.", "İyiyim, teşekkürler."],
  ["excuse me", "phr", "affedersiniz", "Excuse me, where is the bank?", "Affedersiniz, banka nerede?", "Birinin dikkatini çekmek ya da yol istemek için kullanılır."],
  ["OK", "adj", "tamam", "Is it OK if I sit here?", "Buraya oturmam sorun olur mu?"],
  ["mister (Mr)", "n", "bay", "Mr Brown is our teacher.", "Bay Brown bizim öğretmenimiz."],

  // Set 2 — Family
  ["family", "n", "aile", "I have a big family.", "Kalabalık bir ailem var."],
  ["mother", "n", "anne", "My mother is a doctor.", "Annem doktor."],
  ["father", "n", "baba", "My father cooks dinner.", "Babam akşam yemeğini pişirir."],
  ["parent", "n", "ebeveyn (anne ya da baba)", "My parents live in Izmir.", "Annemle babam İzmir'de yaşıyor."],
  ["brother", "n", "erkek kardeş, ağabey", "My brother is ten years old.", "Erkek kardeşim on yaşında."],
  ["sister", "n", "kız kardeş, abla", "I have one sister.", "Bir kız kardeşim var."],
  ["son", "n", "oğul", "Their son goes to school.", "Oğulları okula gidiyor."],
  ["daughter", "n", "kız evlat", "She has two daughters.", "Onun iki kızı var."],
  ["child", "n", "çocuk", "The child is playing.", "Çocuk oynuyor.", "Çoğulu düzensizdir: children."],
  ["baby", "n", "bebek", "The baby is sleeping.", "Bebek uyuyor."],
  ["grandmother", "n", "büyükanne, nine", "My grandmother makes great cakes.", "Büyükannem harika kekler yapar."],
  ["grandfather", "n", "büyükbaba, dede", "My grandfather reads the newspaper.", "Dedem gazete okur."],
  ["husband", "n", "koca, eş", "Her husband is a teacher.", "Kocası öğretmen."],
  ["wife", "n", "karı, eş", "His wife works in a bank.", "Karısı bir bankada çalışıyor."],
  ["uncle", "n", "amca, dayı", "My uncle lives in Ankara.", "Amcam Ankara'da yaşıyor.", "İngilizcede amca ve dayı için aynı kelime kullanılır."],
  ["aunt", "n", "teyze, hala", "My aunt has a cat.", "Teyzemin bir kedisi var.", "Teyze, hala ve yenge için aynı kelime kullanılır."],
  ["cousin", "n", "kuzen", "My cousin is my age.", "Kuzenim benimle yaşıt."],
  ["boy", "n", "erkek çocuk, oğlan", "The boy has a red ball.", "Oğlanın kırmızı bir topu var."],
  ["girl", "n", "kız çocuk", "The girl is reading a book.", "Kız bir kitap okuyor."],
  ["people", "n", "insanlar", "Many people live in Istanbul.", "İstanbul'da çok insan yaşıyor.", "“person” kelimesinin çoğuludur."],

  // Set 3 — Numbers & quantity
  ["one", "num", "bir", "I have one brother.", "Bir erkek kardeşim var."],
  ["two", "num", "iki", "She has two cats.", "Onun iki kedisi var."],
  ["three", "num", "üç", "We need three chairs.", "Üç sandalyeye ihtiyacımız var."],
  ["four", "num", "dört", "The table has four legs.", "Masanın dört ayağı var."],
  ["five", "num", "beş", "I get up at five o'clock.", "Saat beşte kalkarım."],
  ["ten", "num", "on", "The shop opens at ten.", "Dükkan onda açılıyor."],
  ["twenty", "num", "yirmi", "There are twenty students in the class.", "Sınıfta yirmi öğrenci var."],
  ["hundred", "num", "yüz", "It costs a hundred lira.", "Yüz lira tutuyor."],
  ["thousand", "num", "bin", "The city has a thousand years of history.", "Şehrin bin yıllık tarihi var."],
  ["first", "adj", "birinci, ilk", "This is my first day at work.", "Bu işteki ilk günüm."],
  ["second", "adj", "ikinci", "She is in the second class.", "O ikinci sınıfta."],
  ["last", "adj", "son; geçen", "December is the last month of the year.", "Aralık yılın son ayıdır."],
  ["number", "n", "sayı, numara", "What is your phone number?", "Telefon numaran ne?"],
  ["many", "det", "çok (sayılabilen)", "There are many books on the shelf.", "Rafta çok kitap var.", "Sayılabilen çoğul isimlerle kullanılır: many books."],
  ["much", "det", "çok (sayılamayan)", "I don't have much time.", "Çok zamanım yok.", "Sayılamayan isimlerle kullanılır: much water, much time."],
  ["some", "det", "biraz, birkaç", "I want some bread.", "Biraz ekmek istiyorum."],
  ["all", "det", "hepsi, bütün", "All my friends are here.", "Bütün arkadaşlarım burada."],
  ["half", "n", "yarım, yarı", "I ate half of the pizza.", "Pizzanın yarısını yedim."],
  ["only", "adv", "sadece", "I have only one pen.", "Sadece bir kalemim var."],
  ["more", "det", "daha fazla", "Can I have more tea?", "Biraz daha çay alabilir miyim?"],

  // Set 4 — Colours & shapes
  ["colour", "n", "renk", "What colour is your car?", "Araban ne renk?", "Amerikan İngilizcesinde “color” yazılır."],
  ["red", "adj", "kırmızı", "I have a red bag.", "Kırmızı bir çantam var."],
  ["blue", "adj", "mavi", "The sky is blue today.", "Bugün gökyüzü mavi."],
  ["green", "adj", "yeşil", "The grass is green.", "Çimen yeşil."],
  ["yellow", "adj", "sarı", "Bananas are yellow.", "Muzlar sarıdır."],
  ["black", "adj", "siyah", "He is wearing black shoes.", "Siyah ayakkabı giyiyor."],
  ["white", "adj", "beyaz", "The walls are white.", "Duvarlar beyaz."],
  ["brown", "adj", "kahverengi", "My dog is brown.", "Köpeğim kahverengi."],
  ["orange", "adj", "turuncu", "She has an orange T-shirt.", "Turuncu bir tişörtü var.", "İsim olarak “portakal” anlamına da gelir."],
  ["pink", "adj", "pembe", "The flowers are pink.", "Çiçekler pembe."],
  ["purple", "adj", "mor", "Her favourite colour is purple.", "En sevdiği renk mor."],
  ["grey", "adj", "gri", "It is a grey, rainy day.", "Gri, yağmurlu bir gün."],
  ["dark", "adj", "karanlık; koyu", "It gets dark early in winter.", "Kışın erken karanlık olur."],
  ["light", "adj", "açık (renk); aydınlık", "She wears a light blue dress.", "Açık mavi bir elbise giyiyor."],
  ["circle", "n", "daire, çember", "Draw a circle on the paper.", "Kağıda bir daire çiz."],
  ["square", "n", "kare; meydan", "The window is a square.", "Pencere kare şeklinde."],
  ["line", "n", "çizgi; sıra", "Write your name on the line.", "Adını çizginin üzerine yaz."],
  ["round", "adj", "yuvarlak", "We have a round table.", "Yuvarlak bir masamız var."],
  ["big", "adj", "büyük", "They live in a big house.", "Büyük bir evde yaşıyorlar."],
  ["small", "adj", "küçük", "I have a small room.", "Küçük bir odam var."],

  // Set 5 — The body
  ["body", "n", "vücut, beden", "Exercise is good for your body.", "Egzersiz vücudun için iyidir."],
  ["head", "n", "baş, kafa", "I have a pain in my head.", "Başımda bir ağrı var."],
  ["face", "n", "yüz", "Wash your face.", "Yüzünü yıka."],
  ["eye", "n", "göz", "She has green eyes.", "Yeşil gözleri var."],
  ["ear", "n", "kulak", "The rabbit has long ears.", "Tavşanın uzun kulakları var."],
  ["nose", "n", "burun", "He has a small nose.", "Küçük bir burnu var."],
  ["mouth", "n", "ağız", "Open your mouth, please.", "Ağzınızı açın, lütfen."],
  ["tooth", "n", "diş", "I brush my teeth every morning.", "Her sabah dişlerimi fırçalarım.", "Çoğulu düzensizdir: teeth."],
  ["hair", "n", "saç", "She has long black hair.", "Uzun siyah saçları var.", "Saç anlamında sayılamaz: “her hair is long”."],
  ["hand", "n", "el", "Raise your hand.", "Elini kaldır."],
  ["arm", "n", "kol", "He broke his arm.", "Kolunu kırdı."],
  ["leg", "n", "bacak", "My legs are tired.", "Bacaklarım yorgun."],
  ["foot", "n", "ayak", "I go to school on foot.", "Okula yürüyerek giderim.", "Çoğulu düzensizdir: feet. “on foot” = yürüyerek."],
  ["finger", "n", "parmak", "She has a ring on her finger.", "Parmağında bir yüzük var."],
  ["back", "n", "sırt", "My back hurts.", "Sırtım ağrıyor."],
  ["stomach", "n", "mide, karın", "I have a stomach ache.", "Midem ağrıyor."],
  ["heart", "n", "kalp", "The heart is a strong muscle.", "Kalp güçlü bir kastır."],
  ["neck", "n", "boyun", "Giraffes have long necks.", "Zürafaların uzun boyunları vardır."],
  ["shoulder", "n", "omuz", "He carries the bag on his shoulder.", "Çantayı omzunda taşıyor."],
  ["knee", "n", "diz", "I hurt my knee playing football.", "Futbol oynarken dizimi incittim."],
];
