import type { LexiconEntry } from "../types";

/** A1 sets 21–25: everyday verbs, describing things, feelings. */
export const A1_PART5: LexiconEntry[] = [
  // Set 21 — Core verbs 1
  ["be", "v", "olmak", "I am a student.", "Ben bir öğrenciyim.", "Çekimi düzensizdir: am / is / are, geçmişte was / were."],
  ["have", "v", "sahip olmak", "I have two cats.", "İki kedim var."],
  ["do", "v", "yapmak", "What do you do on Sundays?", "Pazar günleri ne yaparsın?"],
  ["go", "v", "gitmek", "We go to the beach in summer.", "Yazın plaja gideriz."],
  ["come", "v", "gelmek", "Come here, please.", "Buraya gel, lütfen."],
  ["get", "v", "almak, elde etmek; olmak", "I get a lot of emails.", "Çok e-posta alırım.", "Çok anlamlıdır: get up (kalkmak), get tired (yorulmak)."],
  ["make", "v", "yapmak, yaratmak", "She makes her own clothes.", "Kendi kıyafetlerini diker.", "Üretmek için “make”, eylem için “do”: make a cake, do homework."],
  ["take", "v", "almak, götürmek", "Take an umbrella with you.", "Yanına şemsiye al."],
  ["give", "v", "vermek", "Give me the book, please.", "Kitabı bana ver, lütfen."],
  ["say", "v", "söylemek, demek", "What did he say?", "Ne dedi?"],
  ["tell", "v", "anlatmak, söylemek (birine)", "Tell me a story.", "Bana bir hikaye anlat.", "Kime söylendiği belirtilir: tell someone something."],
  ["see", "v", "görmek", "I can see the sea from my window.", "Pencereden denizi görebiliyorum."],
  ["look", "v", "bakmak", "Look at the board.", "Tahtaya bakın."],
  ["watch", "v", "izlemek", "We watch football on TV.", "Televizyonda futbol izleriz."],
  ["hear", "v", "duymak", "Can you hear me?", "Beni duyabiliyor musun?"],
  ["listen", "v", "dinlemek", "Listen to the teacher.", "Öğretmeni dinleyin.", "“to” ile kullanılır: listen to music."],
  ["know", "v", "bilmek, tanımak", "I know the answer.", "Cevabı biliyorum."],
  ["think", "v", "düşünmek", "I think it's a good idea.", "Bence iyi bir fikir."],
  ["want", "v", "istemek", "I want a new phone.", "Yeni bir telefon istiyorum."],
  ["need", "v", "ihtiyaç duymak", "I need your help.", "Yardımına ihtiyacım var."],

  // Set 22 — Core verbs 2
  ["like", "v", "sevmek, hoşlanmak", "I like reading.", "Okumayı severim."],
  ["love", "v", "çok sevmek", "I love my family.", "Ailemi çok seviyorum."],
  ["open", "v", "açmak", "Open the door, please.", "Kapıyı aç, lütfen."],
  ["close", "v", "kapatmak", "Close your books.", "Kitaplarınızı kapatın."],
  ["start", "v", "başlamak", "The film starts at eight.", "Film sekizde başlıyor."],
  ["finish", "v", "bitirmek, bitmek", "I finish work at five.", "İşi beşte bitiririm."],
  ["help", "v", "yardım etmek", "Can you help me?", "Bana yardım edebilir misin?"],
  ["ask", "v", "sormak; istemek", "Ask the teacher.", "Öğretmene sor."],
  ["answer", "v", "cevaplamak", "Answer the questions.", "Soruları cevaplayın."],
  ["read", "v", "okumak", "I read before I sleep.", "Uyumadan önce okurum."],
  ["write", "v", "yazmak", "Write your name here.", "Adını buraya yaz."],
  ["speak", "v", "konuşmak (dil)", "Do you speak English?", "İngilizce konuşuyor musun?"],
  ["talk", "v", "konuşmak, sohbet etmek", "We talk on the phone every day.", "Her gün telefonda konuşuruz."],
  ["call", "v", "aramak (telefonla); çağırmak", "I'll call you tonight.", "Bu akşam seni ararım."],
  ["buy", "v", "satın almak", "I want to buy a new bag.", "Yeni bir çanta almak istiyorum."],
  ["sell", "v", "satmak", "They sell fruit at the market.", "Pazarda meyve satıyorlar."],
  ["pay", "v", "ödemek", "Can I pay by card?", "Kartla ödeyebilir miyim?"],
  ["wait", "v", "beklemek", "Wait for me!", "Beni bekle!", "“for” ile kullanılır: wait for the bus."],
  ["sleep", "v", "uyumak", "I sleep eight hours a night.", "Gece sekiz saat uyurum."],
  ["wake up", "pv", "uyanmak", "I wake up at seven.", "Yedide uyanırım."],

  // Set 23 — Core verbs 3
  ["sit", "v", "oturmak", "Please sit down.", "Lütfen oturun."],
  ["stand", "v", "ayakta durmak", "Stand up, please.", "Ayağa kalkın, lütfen."],
  ["carry", "v", "taşımak", "Can you carry this box?", "Bu kutuyu taşıyabilir misin?"],
  ["bring", "v", "getirmek", "Bring your books tomorrow.", "Yarın kitaplarınızı getirin."],
  ["find", "v", "bulmak", "I can't find my phone.", "Telefonumu bulamıyorum."],
  ["lose", "v", "kaybetmek", "Don't lose your ticket.", "Biletini kaybetme."],
  ["put", "v", "koymak", "Put your bag on the chair.", "Çantanı sandalyeye koy."],
  ["show", "v", "göstermek", "Show me your photos.", "Bana fotoğraflarını göster."],
  ["try", "v", "denemek, çalışmak", "Try this cake!", "Bu keki bir dene!"],
  ["use", "v", "kullanmak", "Can I use your phone?", "Telefonunu kullanabilir miyim?"],
  ["cook", "v", "pişirmek, yemek yapmak", "I cook dinner every night.", "Her akşam yemek yaparım."],
  ["clean", "v", "temizlemek", "I clean my room on Saturdays.", "Cumartesileri odamı temizlerim."],
  ["wash", "v", "yıkamak", "Wash your hands before lunch.", "Öğle yemeğinden önce ellerini yıka."],
  ["draw", "v", "çizmek", "The children draw pictures.", "Çocuklar resim çizer."],
  ["visit", "v", "ziyaret etmek", "We visit our grandparents every week.", "Her hafta büyükannemlerle büyükbabamı ziyaret ederiz."],
  ["stay", "v", "kalmak", "We stay in a hotel.", "Bir otelde kalıyoruz."],
  ["turn", "v", "dönmek, çevirmek", "Turn left at the bank.", "Bankadan sola dön."],
  ["remember", "v", "hatırlamak", "I remember your name.", "Adını hatırlıyorum."],
  ["forget", "v", "unutmak", "Don't forget your keys.", "Anahtarlarını unutma."],
  ["understand", "v", "anlamak", "I don't understand the question.", "Soruyu anlamıyorum."],

  // Set 24 — Describing things
  ["good", "adj", "iyi", "This is a good book.", "Bu iyi bir kitap."],
  ["bad", "adj", "kötü", "The weather is bad today.", "Bugün hava kötü."],
  ["new", "adj", "yeni", "I have a new phone.", "Yeni bir telefonum var."],
  ["old", "adj", "eski; yaşlı", "This is an old house.", "Bu eski bir ev."],
  ["young", "adj", "genç", "My mother looks young.", "Annem genç görünüyor."],
  ["long", "adj", "uzun", "It's a long road.", "Uzun bir yol."],
  ["short", "adj", "kısa", "The film is short.", "Film kısa."],
  ["tall", "adj", "uzun boylu, yüksek", "My brother is very tall.", "Ağabeyim çok uzun boylu.", "İnsanlar ve binalar için “tall”, nesneler için “long”."],
  ["fast", "adj", "hızlı", "This is a fast car.", "Bu hızlı bir araba."],
  ["slow", "adj", "yavaş", "The bus is very slow.", "Otobüs çok yavaş."],
  ["easy", "adj", "kolay", "The test is easy.", "Test kolay."],
  ["difficult", "adj", "zor", "Maths is difficult for me.", "Matematik benim için zor."],
  ["cheap", "adj", "ucuz", "This shirt is cheap.", "Bu gömlek ucuz."],
  ["expensive", "adj", "pahalı", "London is expensive.", "Londra pahalı."],
  ["clean", "adj", "temiz", "The kitchen is clean.", "Mutfak temiz."],
  ["dirty", "adj", "kirli", "Your shoes are dirty.", "Ayakkabıların kirli."],
  ["full", "adj", "dolu; tok", "The bus is full.", "Otobüs dolu."],
  ["empty", "adj", "boş", "The fridge is empty.", "Buzdolabı boş."],
  ["heavy", "adj", "ağır", "This bag is heavy.", "Bu çanta ağır."],
  ["beautiful", "adj", "güzel", "What a beautiful view!", "Ne güzel bir manzara!"],

  // Set 25 — Feelings
  ["happy", "adj", "mutlu", "I'm happy to see you.", "Seni gördüğüme sevindim."],
  ["sad", "adj", "üzgün", "Why are you sad?", "Neden üzgünsün?"],
  ["tired", "adj", "yorgun", "I'm tired after work.", "İşten sonra yorgunum."],
  ["angry", "adj", "kızgın", "My father is angry with me.", "Babam bana kızgın.", "“angry with someone” kalıbıyla kullanılır."],
  ["afraid", "adj", "korkmuş", "I'm afraid of the dark.", "Karanlıktan korkarım.", "“afraid of” kalıbıyla kullanılır."],
  ["bored", "adj", "sıkılmış", "I'm bored. Let's go out.", "Sıkıldım. Hadi dışarı çıkalım.", "Sıkılan kişi “bored”, sıkıcı şey “boring”dir."],
  ["boring", "adj", "sıkıcı", "The film is boring.", "Film sıkıcı."],
  ["interesting", "adj", "ilginç", "This book is very interesting.", "Bu kitap çok ilginç."],
  ["excited", "adj", "heyecanlı", "The children are excited about the trip.", "Çocuklar gezi için heyecanlı."],
  ["worried", "adj", "endişeli", "She's worried about the exam.", "Sınav konusunda endişeli."],
  ["nervous", "adj", "gergin", "I'm nervous before exams.", "Sınavlardan önce gergin olurum."],
  ["surprised", "adj", "şaşırmış", "I was surprised by the news.", "Habere şaşırdım."],
  ["glad", "adj", "memnun, sevinçli", "I'm glad you're here.", "Burada olmana sevindim."],
  ["sick", "adj", "hasta", "I feel sick today.", "Bugün kendimi hasta hissediyorum."],
  ["well", "adj", "iyi, sağlıklı", "I don't feel well.", "Kendimi iyi hissetmiyorum."],
  ["kind", "adj", "nazik, iyi kalpli", "It's very kind of you.", "Çok naziksiniz."],
  ["friendly", "adj", "cana yakın, arkadaş canlısı", "Our neighbours are friendly.", "Komşularımız cana yakın."],
  ["funny", "adj", "komik", "He tells funny stories.", "Komik hikayeler anlatır."],
  ["busy", "adj", "meşgul; kalabalık", "I'm very busy this week.", "Bu hafta çok meşgulüm."],
  ["feel", "v", "hissetmek", "How do you feel today?", "Bugün kendini nasıl hissediyorsun?"],
];
